pinpoint-apm/pinpoint

profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/connector/httpclient4/interceptor/AbstractHttpRequestExecute.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/connector/httpclient4/interceptor/AsyncClientExecuteInterceptor.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/connector/httpclient4/interceptor/AsyncInternalClientExecuteInterceptor.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/connector/httpclient4/interceptor/HttpRequestExecuteInterceptor.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/connector/httpclient4/interceptor/HttpUriRequestExecuteInterceptor.java

Can collect status code infomation 
But, not yet collect when call call back method 
ex) Mthod public <T> T execute(final HttpUriRequest request,final ResponseHandler<? extends T> responseHandler, final HttpContext context)
One of these days I will commit code which be able to profiling status code for call back method.

[#76] Add profiling status code for httpclient 4

---

rpc/src/main/java/com/navercorp/pinpoint/rpc/client/ConnectFuture.java
rpc/src/main/java/com/navercorp/pinpoint/rpc/client/PinpointSocketFactory.java
rpc/src/main/java/com/navercorp/pinpoint/rpc/client/PinpointSocketHandler.java
rpc/src/main/java/com/navercorp/pinpoint/rpc/client/ReconnectStateSocketHandler.java
rpc/src/main/java/com/navercorp/pinpoint/rpc/client/SocketHandler.java
rpc/src/test/java/com/navercorp/pinpoint/rpc/client/ConnectFutureTest.java

Use netty's channelConnected method instead of SocketHandler's open
method. 
(Netty manage channel's lifecycle. So we can manage
PinpointSocketHandler state more precisely.)

Improve state synchronization between server and client. #136

---

bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/instrument/ByteCodeInstrumentor.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/interceptor/bci/JavaAssistByteCodeInstrumentor.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/AbstractModifierDelegate.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/DefaultModifierRegistry.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/ModifierDelegate.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/db/interceptor/PreparedStatementCreateInterceptor.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/db/oracle/OracleClassConstants.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/db/oracle/OraclePreparedStatementModifier.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/db/oracle/OraclePreparedStatementModifierDelegate.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/db/oracle/OraclePreparedStatementWrapperModifier.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/db/oracle/OracleStatementModifier.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/db/oracle/OracleStatementModifierDelegate.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/db/oracle/OracleStatementWrapperModifier.java

Added tracing support for Oracle jdbc drivers 10.x and older.
Modifiers can now also check if a class can exists in a given class loader's path. (Necessary for ojdbc 11+ as `OracleStatementModifier` and `OraclePreparedStatementModifier` should not modify their target classes when their wrapper classes exist)

Added support for older Oracle jdbc drivers - fixes #193

---

bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/AgentClassLoader.java
bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/PinpointBootStrap.java
bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/context/ServerMetaDataHolder.java
bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/LifeCycleEventListener.java
plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/interceptor/StandardServiceStartInterceptor.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/AgentInfoSender.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/DefaultAgent.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultServerMetaDataHolder.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/util/ApplicationServerTypeResolver.java
profiler/src/main/java/com/navercorp/pinpoint/test/PluginTestAgent.java
profiler/src/main/java/com/navercorp/pinpoint/test/TestableServerMetaDataListener.java
profiler/src/main/java/com/navercorp/pinpoint/test/junit4/BasePinpointTest.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/AgentInfoSenderTest.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/context/DefaultServerMetaDataHolderTest.java

Agent's lifecycle and the application's lifecycle is now completely separated.
Interceptors can no longer call agent's start method. This was done previously to send `ServerMetaData` along with `AgentInfo`, and the agent had no way of knowing when to send this data.
Now, the `AgentInfo` is sent as soon as Pinpoint agent is booted up, and the interceptors can specify when to send `ServerMetaData` independently.
resolve #215

[#215] Let bootstrap handle agent's lifecycle. 

---

collector/src/main/java/com/navercorp/pinpoint/collector/handler/SpanChunkHandler.java
collector/src/main/java/com/navercorp/pinpoint/collector/handler/SpanHandler.java
commons/src/main/java/com/navercorp/pinpoint/common/bo/SpanBo.java
commons/src/test/java/com/navercorp/pinpoint/common/bo/SpanBoTest.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/DefaultAgent.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTrace.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTraceContext.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/SpanChunkFactory.java
profiler/src/main/java/com/navercorp/pinpoint/test/MockTraceContextFactory.java
profiler/src/main/java/com/navercorp/pinpoint/test/TestAgentInformation.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/context/DefaultTraceContextTest.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/context/DefaultTraceTest.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/context/ThreadLocalTraceFactoryTest.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/context/TraceTest.java
thrift/src/main/java/com/navercorp/pinpoint/thrift/dto/TSpan.java
thrift/src/main/java/com/navercorp/pinpoint/thrift/dto/TSpanChunk.java
thrift/src/main/thrift/Trace.thrift
web/src/main/java/com/navercorp/pinpoint/web/calltree/span/SpanAligner2.java
web/src/main/java/com/navercorp/pinpoint/web/filter/FromToFilter.java
web/src/main/java/com/navercorp/pinpoint/web/filter/FromToResponseFilter.java
web/src/main/java/com/navercorp/pinpoint/web/service/DotExtractor.java
web/src/main/java/com/navercorp/pinpoint/web/service/FilteredMapServiceImpl.java

This should resolve #228, allowing for an application to have its own service type, and not be bound to a single service type which generates its root spans.
For example, a stand alone application running embedded tomcat will now show up as a STAND_ALONE node in the server map, while having its call stack generated from a TOMCAT span.

[#228] Decouple application type and span service type.

---

commons/src/main/java/com/navercorp/pinpoint/common/util/ApplicationMapStatisticsUtils.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/LinkList.java
web/src/main/java/com/navercorp/pinpoint/web/mapper/MapStatisticsCalleeMapper.java

An exception is thrown when drawing the server map in situations where users call multiple nodes with the same application name (but different service types). This was caused because it was not possible to have a single user node pointing to more than 1 destination node.
The user nodes are uniquely identified by their destination node's application name only and this resulted in only a single user node being created when there were multiple nodes with the same application name.
This commit fixes #254 by taking the destination node's service type into account when creating user nodes.

#254 fix exception when user node points to nodes with the same app name

---

pom.xml

CDH 4.5.0 -> CDH 4.7.1
hadoop 2.0.0-cdh4.5.0 -> 2.0.0-cdh4.7.1
hbase 0.94.6-cdh4.5.0 -> 0.94.15-cdh4.7.1
zookeeper 3.4.5-cdh4.5.0 -> 3.4.5-cdh4.7.1
hadoop-core  2.0.0-mr1-cdh4.5.0 -> 2.0.0-mr1-cdh4.7.1

#271 CDH minor version up

---

pom.xml

Change maven plugin repository becuase Codehaus services will be
terminated.
http://repository.codehaus.org -> http://repo1.maven.org/maven2

change maven plugin repository #417

---

collector/pom.xml
quickstart/collector/pom.xml
quickstart/web/pom.xml

Collector's pom file in the cherry-picked commit did not have Plugins dependency, which resulted in plugins not being deployed.
This commit restores the dependency.

#382 added missing plugins dependency to collector's pom

---

commons/src/test/java/com/navercorp/pinpoint/common/buffer/AutomaticBufferTest.java
commons/src/test/java/com/navercorp/pinpoint/common/buffer/FixedBufferTest.java
commons/src/test/java/com/navercorp/pinpoint/common/util/ApplicationMapStatisticsUtilsTest.java
commons/src/test/java/com/navercorp/pinpoint/common/util/BytesUtilsTest.java
commons/src/test/java/com/navercorp/pinpoint/common/util/SpanUtilsTest.java

Pinpoint now uses HBase 1.0.x, which is compiled against jdk 1.7.
Pinpoint commons however is compiled with jdk 1.6 and would throw
UnsupportedClassVersionError when tests that use classes in Hadoop/HBase
library.
This commit removes these so such tests won't fail - fixes #432

Remove hadoop dependency from Pinpoint commons test.

---

quickstart/bin/start-hbase.sh

Added unlink command to script and a remove command to the data directory if downloading/installing hbase is necessary.
should fix #452

fixed start-hbase script to work when hbase installation exists

---

README.md
profiler-optional/README.md
quickstart/README.Win.ko.md
quickstart/README.md

Inline code can be written with one backtick `` `code` ``. Three backticks are used for multiline code:
```
code
```

Fix syntax of markdown files

---

agent/pom.xml
agent/src/test/java/com/navercorp/pinpoint/plugin/gson/GsonMethodFilterIT.java
plugins/gson/.gitignore
plugins/gson/pom.xml
plugins/gson/src/main/java/com/navercorp/pinpoint/plugin/gson/GsonMetadataProvider.java
plugins/gson/src/main/java/com/navercorp/pinpoint/plugin/gson/GsonPlugin.java
plugins/gson/src/main/java/com/navercorp/pinpoint/plugin/gson/filter/GsonMethodFilter.java
plugins/gson/src/main/java/com/navercorp/pinpoint/plugin/gson/filter/GsonMethodNames.java
plugins/gson/src/main/java/com/navercorp/pinpoint/plugin/gson/interceptor/GsonMethodInterceptor.java
plugins/gson/src/main/resources/META-INF/services/com.navercorp.pinpoint.bootstrap.plugin.ProfilerPlugin
plugins/gson/src/main/resources/META-INF/services/com.navercorp.pinpoint.common.trace.TraceMetadataProvider
plugins/pom.xml

See https://code.google.com/p/google-gson/.
It records start time and end time of the calls of `fromJson` and `toJson`. If an user passes a `String` to `fromJson`, or doesn't pass a `Appendable` or `JsonWriter` to `toJson`, then this plugin records the length of JSON as an attribute. See `plugins/gson/src/main/java/com/navercorp/pinpoint/plugin/gson/interceptor/GsonMethodInterceptor.java`.
It currently uses 7000 as the code of `ServiceType`, 9000 as the code of `AnnotationKey`. If you want to use other codes, please let me know. Also if you think some additional Javadoc comments are needed, please mention the methods or classes.

Add Gson plugin

---

agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/client/AsyncEchoTestClient.java
agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/client/SyncEchoTestClient.java
agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/server/AsyncEchoTestServer.java
agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/server/SyncEchoTestServer.java

There may yet be a mismatch between hostname resolved by the Thrift plugin and those used to check in integration tests. Trying fix.

#329 modify ITs to retrieve hostnames from InetSocketAddress

---

plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/ThriftClientCallContext.java
plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/ThriftHeader.java
plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/ThriftRequestProperty.java
plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/interceptor/client/TServiceClientSendBaseInterceptor.java
plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/interceptor/client/async/TAsyncClientManagerCallInterceptor.java
plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/interceptor/tprotocol/client/TProtocolWriteFieldStopInterceptor.java
plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/interceptor/tprotocol/server/TProtocolReadFieldBeginInterceptor.java
plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/interceptor/tprotocol/server/TProtocolReadMessageEndInterceptor.java
plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/interceptor/tprotocol/server/TProtocolReadTTypeInterceptor.java

This was done to ease up future refactoring that would pull up trace
headers used for tracing various RPC calls into a single common class.

#329 refactored Thrift trace headers

---

agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/TestEnvironment.java
agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/client/AsyncEchoTestClient.java
agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/client/SyncEchoTestClient.java
agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/server/AsyncEchoTestServer.java
agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/server/EchoTestServer.java
agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/server/SyncEchoTestServer.java
agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/EchoTestRunner.java
agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/asynchronous/ThriftHalfSyncHalfAsyncServerAsyncIT.java
agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/asynchronous/ThriftNonblockingServerAsyncIT.java
agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/asynchronous/ThriftThreadedSelectorServerAsyncIT.java
agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/synchronous/ThriftHalfSyncHalfAsyncServerIT.java
agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/synchronous/ThriftNonblockingServerIT.java
agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/synchronous/ThriftSimpleServerIT.java
agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/synchronous/ThriftThreadPoolServerIT.java
agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/synchronous/ThriftThreadedSelectorServerIT.java

* Span/SpanEvent order for client/server traces cannot be guaranteed
with the current implementation of OrderedSpanRecorder. Client/server
trace verification tests are therefore seperated.
* Async call tests are disabled as well as the current implementation of
OrderedSpanRecorder does not adequately support async client SpanEvents.
A modification should be in place soon, and these tests will be added to
the suite when that happens.

Seperate out client/server verification tests due to potential timing issues

---

plugins/jdbc-driver/src/main/java/com/navercorp/pinpoint/plugin/jdbc/common/interceptor/PreparedStatementExecuteQueryInterceptor.java

temp.length와 key 값이 같을때 통과하지만 temp[key]는 array의 index 범위를 넘어버림

배열의 key 비교 잘못으로 오류가 발생함.

---

pom.xml
profiler/src/main/java/com/navercorp/pinpoint/test/junit4/PinpointJUnit4ClassRunner.java

fix PinpointJUnit4ClassRunner to work with junit-4.12 required by Spring 4 mentioned in #765 .

fix PinpointJUnit4ClassRunner to work with the updated junit

---

agent/src/main/resources/pinpoint-real-env-lowoverhead-sample.config
agent/src/main/resources/pinpoint.config
collector/src/main/resources/pinpoint-collector.properties

For Agent.
Some items like ```profiler.enable=true``` weren't being used, so I didn't add comments to those.

Adding comments to configs.

---

agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/TestEnvironment.java
agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/client/AsyncEchoTestClient.java
agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/client/EchoTestClient.java
agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/client/SyncEchoTestClient.java
agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/server/AsyncEchoTestServer.java
agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/server/EchoTestServer.java
agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/server/SyncEchoTestServer.java
agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/EchoTestRunner.java
agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/asynchronous/ThriftHalfSyncHalfAsyncServerAsyncIT.java
agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/asynchronous/ThriftNonblockingServerAsyncIT.java
agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/asynchronous/ThriftThreadedSelectorServerAsyncIT.java
agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/synchronous/ThriftHalfSyncHalfAsyncServerIT.java
agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/synchronous/ThriftNonblockingServerIT.java
agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/synchronous/ThriftSimpleServerIT.java
agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/synchronous/ThriftThreadPoolServerIT.java
agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/synchronous/ThriftThreadedSelectorServerIT.java

Thrift integration tests now uses a random port between 9091~9099 to fix occasional port collision.
Fixes #329

Allow tests to use different ports for different test runs

---

web/src/main/java/com/navercorp/pinpoint/web/applicationmap/ApplicationMapBuilder.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/ServerBuilder.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/ServerInstance.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/ServerInstanceList.java
web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseAgentLifeCycleDao.java
web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoService.java
web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoServiceImpl.java
web/src/main/java/com/navercorp/pinpoint/web/service/AgentServiceImpl.java
web/src/main/java/com/navercorp/pinpoint/web/service/MapServiceImpl.java
web/src/main/java/com/navercorp/pinpoint/web/vo/AgentInfo.java
web/src/main/webapp/features/nodeInfoDetails/node-info-details.directive.js
web/src/test/java/com/navercorp/pinpoint/web/applicationmap/ServerInstanceListTest.java
web/src/test/java/com/navercorp/pinpoint/web/view/ServerInstanceListSerializerTest.java

Allow agents without transactions to be displayed in the server map as long as they were running at the time of querying. Also add agent status data to be utilized in the server map.

Add status information to server map and allow transaction-less nodes to be displayed

---

profiler/src/main/java/com/navercorp/pinpoint/profiler/AgentInfoSender.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/DefaultAgent.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/AgentInfoSenderTest.java

Agent now sends AgentInfo every 24 hours (default) to prevent data loss by HBase TTL.
Initial attempt to send AgentInfo upon startup is retried indefinitely until success, whereas subsequent attempts are limited to 3 attempts (default).
Resolves #1117

Refresh AgentInfo to decouple them from HBase TTL

---

agent/src/main/resources/pinpoint.config
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/DefaultProfilerConfig.java
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/ProfilerConfig.java
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/JdbcConfig.java
plugins/cubrid-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/cubrid/CubridConfig.java
plugins/cubrid-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/cubrid/CubridPlugin.java
plugins/jtds/src/main/java/com/navercorp/pinpoint/plugin/jdbc/jtds/JtdsConfig.java
plugins/jtds/src/main/java/com/navercorp/pinpoint/plugin/jdbc/jtds/JtdsPlugin.java
plugins/mysql-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/mysql/MySqlConfig.java
plugins/mysql-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/mysql/MySqlPlugin.java
plugins/oracle-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/oracle/OracleConfig.java
plugins/oracle-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/oracle/OraclePlugin.java

Adds configuration to enable/disable tracing SQL bind values with a single global option that may be overridden on a per-plugin basis.

Add configuration for tracing SQL bind values

---

agent/src/main/resources/pinpoint.config
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/DefaultProfilerConfig.java
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/ProfilerConfig.java
plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/interceptor/StandardHostValveInvokeInterceptor.java

Adds configuration to enable/disable tracing HTTP request parameters received by Tomcat.
Resolves #1217

Add configuration for tracing request parameters received by Tomcat

---

profiler/src/test/java/com/navercorp/pinpoint/profiler/AgentInfoSenderTest.java
rpc/src/main/java/com/navercorp/pinpoint/rpc/util/ClientFactoryUtils.java

Test modified to reduce potential timing issues when client connects/reconnects to server while the server starts, restarts, and shutdowns.
Also fixed a small typo.

Improve AgentInfoSenderTest client server comm timing

---

web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoService.java
web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoServiceImpl.java
web/src/main/java/com/navercorp/pinpoint/web/service/AgentService.java
web/src/main/java/com/navercorp/pinpoint/web/service/AgentServiceImpl.java
web/src/main/java/com/navercorp/pinpoint/web/websocket/ActiveThreadCountResponseAggregator.java
web/src/main/java/com/navercorp/pinpoint/web/websocket/WorkerActiveManager.java

This adds a time buffer (currently a week) when querying agents for the real time active thread chart to filter out agents that have been dead for too long.
Closes #1318

Exclude agents that have been down for over a week when getting real time active thread information

---

web/src/main/java/com/navercorp/pinpoint/web/calltree/span/SpanAlign.java
web/src/main/java/com/navercorp/pinpoint/web/calltree/span/SpanAligner2.java

Repeated logging of Spans could generate huge log files for transactions with thousands of asynchronous traces. This change only logs Spans once for each span.

Refactor SpanAligner - remove repeated span logs for async traces

---

web/src/main/resources/applicationContext-hbase.xml

For cases where the options are not present in *hbase.properties*.

Add default hbase parallel scanning options

---

web/src/main/java/com/navercorp/pinpoint/web/controller/AdminController.java
web/src/main/java/com/navercorp/pinpoint/web/dao/AgentStatDao.java
web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseAgentStatDao.java
web/src/main/java/com/navercorp/pinpoint/web/service/AdminService.java
web/src/main/java/com/navercorp/pinpoint/web/service/AdminServiceImpl.java
web/src/test/java/com/navercorp/pinpoint/web/alarm/AlarmPartitionerTest.java
web/src/test/java/com/navercorp/pinpoint/web/alarm/checker/GcCountCheckerTest.java
web/src/test/java/com/navercorp/pinpoint/web/alarm/checker/HeapUsageRateCheckerTest.java
web/src/test/java/com/navercorp/pinpoint/web/alarm/checker/JvmCpuUsageRateCheckerTest.java

Adds the following APIs:
1. `/agentIdMap.pinpoint` : Returns the mapping of agent ids and application names.
2. `/duplicateAgentIdMap.pinpoint` : Identical to above except that this returns the agent ids that are mapped to more than 1 application names.
3. `getInactiveAgents.pinpoint` : Returns the list of agents for the given application that does not have agent stat data for longer than the given duration in days.
Resolves #1462 
@emeroad

Add APIs for detecting inactive and duplicate agents

---

web/src/main/java/com/navercorp/pinpoint/web/service/AgentServiceImpl.java
web/src/main/resources/pinpoint-web.properties

Adds configuration option for the duration determining agent inactivity.
ping @koo-taejin 
resolves #1318

Make active thread agent query duration configurable

---

commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/parallel/ScanTask.java

include tableFactory object when to execute releaseTable method.

#1362 Make scanner creation run parallel

---

hbase/pom.xml

There  is no Hbase 1.0.2 from apache.mirrors.pair.com/hbase.

Modified Hbase version to 1.0.3 to fix docker:build error.

---

quickstart/README.md

Update QuickStart README to use HBase 1.0.3

---

pom.xml
web/pom.xml

- Now the plugin tests whether APIs used for pinpoint are compatible for java 1.6.
- Two files are modified: pom.xml, web/pom.xml
- This test automatically runs during project build. (ex command/ mvn install -Dmaven.test.skip=true)
***pinpoint-web is tested if it is compatible with java 1.7
***sun libraries are ignored at the test.
https://github.com/naver/kaist-oss-course/issues/65

Animal Sniffer Plugin applied for Java compatibility test

---

quickstart/README.md

Changed the order of the *Start Pinpoint Daemons* from
**Collector** - Run `quickstart/bin/start-collector.sh`
**Web UI** - Run `quickstart/bin/start-web.sh`
**TestApp** - Run `quickstart/bin/start-testapp.sh`
_______________________________
TO:
**Collector** - Run `quickstart/bin/start-collector.sh`
**TestApp** - Run `quickstart/bin/start-testapp.sh`
**Web UI** - Run `quickstart/bin/start-web.sh`
Which is the correct order

Updated README.md

---

agent/src/main/resources-local/lib/log4j.xml
agent/src/main/resources-release/lib/log4j.xml

Agents built with local profile logs to a separate log file.
Agents built with release profile writes WARN/ERROR logs generated by the agent to console as well.
Related to #1822

Add file appender to local, console appender to release

---

collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/stat/HbaseActiveTraceDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/stat/HbaseCpuLoadDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/stat/HbaseJvmGcDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/stat/HbaseJvmGcDetailedDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/stat/HbaseTransactionDao.java
commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseOperations2.java

`List<Put> HbaseTemplate2.asyncPut(TableName, List<Put>)` method may return null instead of an empty collection.
This fixes agent stat daos so that they handle nulls when checking for rejected puts.
Also adds documentation mentioning the possible null return.
related to #1533

Fix rejected puts check when all puts are successfully queued

---

collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/JvmGcBoMapper.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/JvmGcType.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v1/JvmGcCodecV1.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/JvmGcBo.java
commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/codec/stat/TestAgentStatFactory.java
web/src/main/java/com/navercorp/pinpoint/web/controller/AgentStatController.java
web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/stat/v1/Aggregator.java
web/src/main/java/com/navercorp/pinpoint/web/mapper/stat/AgentStatMapperV1.java
web/src/main/java/com/navercorp/pinpoint/web/mapper/stat/AgentStatMapperV2.java
web/src/main/java/com/navercorp/pinpoint/web/mapper/stat/SampledJvmGcResultExtractor.java
web/src/main/java/com/navercorp/pinpoint/web/vo/stat/SampledJvmGc.java
web/src/main/java/com/navercorp/pinpoint/web/vo/stat/chart/JvmGcChartGroup.java
web/src/main/java/com/navercorp/pinpoint/web/vo/stat/chart/LegacyAgentStatChartGroup.java

Gc Type serialization was removed when storing agent stat data (in particular for Memory/GC data) due to it being stored in *AgentInfo* table. However, Gc type is stored in *AgentInfo* table only for 1.5.2+ agents.
In order to maintain compatibility a bit longer, GC type is added back to *AgentStatV2* table alongside Memory/GC serialization.
related to #1533

Adds GC type back into JvmGc serialization

---

plugins/jdk-http/src/main/java/com/navercorp/pinpoint/plugin/jdk/http/JdkHttpConstants.java

Adds RECORD_STATISTICS ServiceTypeProperty to Jdk HttpUrlConnection ServiceType so that the server map correctly displays call statistics and renders target node.
fixes #2010

Adds RECORD_STATISTICS property to Jdk HttpUrlConnection ServiceType

---

profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/ASMMethodNodeAdapterAddInterceptorTest.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/ASMMethodNodeAdapterRenameTest.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/ASMMethodNodeTest.java

fix asm testcase.

---

agent/pom.xml
agent/src/assembly/distribution.xml
bootstrap-core-optional/.gitignore
bootstrap-core-optional/clover.license
bootstrap-core-optional/pom.xml
bootstrap-core-optional/src/main/java/com/navercorp/pinpoint/bootstrap/util/jdk/JdkThreadLocalRandomFactory.java
bootstrap-core/pom.xml
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/context/SpanId.java
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/util/jdk/PinpointThreadLocalRandomFactory.java
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/util/jdk/ThreadLocalRandomFactory.java
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/util/jdk/ThreadLocalRandomUtils.java
bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/AgentOption.java
bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/ClassPathResolver.java
bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/DefaultAgentOption.java
bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/PinpointBootStrap.java
bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/PinpointStarter.java
pom.xml
profiler-optional/profiler-optional-parent/pom.xml
profiler/src/main/java/com/navercorp/pinpoint/profiler/DefaultAgent.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMClassPool.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/JavassistClassPool.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/PlainClassLoaderHandler.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/PluginConfig.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/ProfilerPluginLoader.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/JarProfilerPluginClassInjectorTest.java
quickstart/agent/pom.xml
quickstart/agent/src/assembly/distribution.xml

This allows for the agent to use enhancements made in JDK7+ if it is running on Java7 and above.
In order to do this, a new module is added(*bootstrap-core-optional*) in which the classes here are compiled using JDK7. The agent then links these classes during runtime only if it is running on Java7+.
Also removed the shading of *pinpoint-commons* module from *bootstrap-core*, so that *pinpoint-commons.jar*, *bootstrap-core.jar*, and *bootstrap-core-optional.jar* are all packaged separately into the agent's *boot* directory. The agent now finds these and adds them to the bootstrap classloader's search path.
Care must be taken when implementing new classes in *bootstrap-core-optional* so that:
1. classes in *bootstrap-core* should not statically reference classes in …

Creates bootstrap-core-optional that has optional classes for Java7+

---

bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/util/jdk/ThreadLocalRandomUtils.java

Use system class loader to load optional ThreadLocalRandomFactory before bootstrap class loader.
Related to #2027

Use system class loader before boostrap class loader

---

pom.xml

1. upgrage netty (3.6.6.Final -> 3.10.6.Final) to avoid JDK logger conflict with JBOSS.

JDK logger conflict in JBoss #2026

---

web/src/main/java/com/navercorp/pinpoint/web/mapper/stat/SampledActiveTraceResultExtractor.java
web/src/main/java/com/navercorp/pinpoint/web/mapper/stat/SampledJvmGcDetailedResultExtractor.java
web/src/main/java/com/navercorp/pinpoint/web/mapper/stat/SampledJvmGcResultExtractor.java
web/src/main/java/com/navercorp/pinpoint/web/vo/chart/LegacyChartBuilder.java
web/src/main/java/com/navercorp/pinpoint/web/vo/chart/LegacySampledChartBuilder.java
web/src/main/java/com/navercorp/pinpoint/web/vo/chart/LegacySampledTimeSeriesChartBuilder.java
web/src/main/java/com/navercorp/pinpoint/web/vo/chart/LegacySampledTitledTimeSeriesChartBuilder.java
web/src/main/java/com/navercorp/pinpoint/web/vo/chart/Point.java
web/src/main/java/com/navercorp/pinpoint/web/vo/chart/TitledPoint.java
web/src/main/java/com/navercorp/pinpoint/web/vo/chart/UncollectedPoint.java
web/src/main/java/com/navercorp/pinpoint/web/vo/stat/chart/CpuLoadChartGroup.java
web/src/main/java/com/navercorp/pinpoint/web/vo/stat/chart/DownSampler.java
web/src/main/java/com/navercorp/pinpoint/web/vo/stat/chart/DownSamplers.java
web/src/main/java/com/navercorp/pinpoint/web/vo/stat/chart/LegacyAgentStatChartGroup.java

This allows non-floating point stat values to yield floating point averages when sampling them.
related to #1533

Allow non-floating point samples to return floating point averages

---

agent/src/test/java/com/navercorp/pinpoint/plugin/hystrix/HystrixCommand_1_3_20_IT.java
agent/src/test/java/com/navercorp/pinpoint/plugin/hystrix/HystrixCommand_1_4_1_to_1_4_2_IT.java
agent/src/test/java/com/navercorp/pinpoint/plugin/hystrix/HystrixCommand_1_4_3_to_1_5_2_IT.java
agent/src/test/java/com/navercorp/pinpoint/plugin/hystrix/HystrixCommand_1_5_3_to_1_5_x_IT.java

Hystrix 1.4.1 and 1.4.2 dropped Java 6 support so these tests may fail when ran with java 6. ITs that tests 1.4.1 and 1.4.2 are now run with Java 7.

Split integration tests for testing Hystrix 1.4.1 and 1.4.2

---

agent/pom.xml
agent/src/test/java/com/navercorp/pinpoint/plugin/jdbc/mariadb/MariaDB_1_3_x_IT.java
agent/src/test/java/com/navercorp/pinpoint/plugin/jdbc/mariadb/MariaDB_1_4_x_IT.java

mariaDB4j is pulled from maven central.
Fixes #2072

Updates mariaDB4j dependency

---

plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/TomcatConfiguration.java

`TomcatConfiguration` does not initialize `tomcatExcludeUrlFilter` (remains null) when `profiler.tomcat.excludeurl` is not set. This causes the agent unable to inject `StandardHostValveInvokeInterceptor` when transforming `StandardHostValve.invoke(...)` method.
This makes it so that `TomcatConfiguration`'s `tomcatExcludeFilter` is never null.
Fixes #2077

Fixes StandardHostValve.invoke() not being transformed when excludeurl is not set

---

agent/src/main/resources-local/pinpoint.config
agent/src/main/resources-release/pinpoint.config
agent/src/main/resources/pinpoint-real-env-lowoverhead-sample.config
agent/src/test/java/com/navercorp/pinpoint/plugin/jdbc/mariadb/MariaDB_1_4_x_IT.java

This pull request adds configuration options to enable/disable mariadb and cassandra client tracing, as well as expanding integration test coverage to cover mariadb-java-client version 1.5+.

Adds enable/disable configurations for mariadb and cassandra plugins

---

plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/ThriftConstants.java
plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/ThriftPlugin.java
plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/field/getter/TProtocolFieldGetter.java
plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/interceptor/server/ProcessFunctionProcessInterceptor.java

`TProtocolDecorator` is added in 0.9.1.
When tracing Thrift processors, the agent marks whether to trace a request by setting an injected field to `TProtocol` instance when `ProcessFunction.process(int, TProtocol, TProtocol, I)` is invoked.
If the input protocol (2nd parameter) is an instance of `TProtocolDecorator`, the `ProcessFunction.process` interceptor marks it to the decorator, and not the actual `TProtocol` it is decorating.
This PR fixes this by retrieving the actual `TProtocol` instance before marking it.
for #2106

Adds support for TProtocolDecorators

---

web/src/main/java/com/navercorp/pinpoint/web/websocket/ActiveThreadCountHandler.java

If webSocketSession status is not opened, then do not binding to flush aggregator.

[PinpiontWeb] fix a ActiveThread concurrency problem #1482

---

agent/src/main/resources-local/pinpoint.config
agent/src/main/resources-release/pinpoint.config
agent/src/main/resources/pinpoint-real-env-lowoverhead-sample.config
agent/src/test/resources/pinpoint-disabled-plugin-test.config
agent/src/test/resources/pinpoint-spring-bean-test.config
plugins/spring/src/main/java/com/navercorp/pinpoint/plugin/spring/beans/SpringBeansTarget.java
plugins/spring/src/test/java/com/navercorp/pinpoint/plugin/spring/beans/SpringBeansTargetTest.java
plugins/spring/src/test/java/com/navercorp/pinpoint/plugin/spring/beans/interceptor/TargetBeanFilterTest.java
quickstart/agent/src/main/resources/pinpoint.config
quickstart/conf/pinpoint.config

~~~
** - matches zero or more 'directories' in a path
~~~

add ant-style path pattern.

---

agent/src/main/resources-local/pinpoint.config
agent/src/main/resources-release/pinpoint.config
agent/src/main/resources/pinpoint-real-env-lowoverhead-sample.config
agent/src/test/resources/activemq/client/pinpoint-activemq-client.config
agent/src/test/resources/pinpoint-disabled-plugin-test.config
agent/src/test/resources/pinpoint-spring-bean-test.config
plugins/google-httpclient/src/test/resources/pinpoint.config
plugins/httpclient3/src/test/resources/pinpoint.config
plugins/httpclient4/src/test/resources/pinpoint.config
plugins/jboss/src/main/java/com/navercorp/pinpoint/plugin/jboss/JbossConfig.java
plugins/jboss/src/main/java/com/navercorp/pinpoint/plugin/jboss/JbossPlugin.java
plugins/jboss/src/test/resources/pinpoint.config
plugins/redis/src/test/resources/pinpoint.config
plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/TomcatConfig.java
plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/TomcatPlugin.java
plugins/tomcat/src/test/resources/pinpoint.config
plugins/user/src/test/resources/pinpoint.config
profiler-optional/profiler-optional-jdk8/src/test/resources/pinpoint-lambda-test.config
profiler/src/test/resources/pinpoint-spring-bean-test.config
profiler/src/test/resources/pinpoint.config
quickstart/agent/src/main/resources/pinpoint.config
quickstart/conf/pinpoint.config

This allows Tomcat and JBoss plugins to check the application's main class to determine if they should add class file transformers.
Tomcat plugin checks if the application was launched via Tomcat's Bootstrap, or one of SpringBoot's many launchers.
JBoss plugin checks if the application was launched via JBoss' Main.
Configuration option is also added to disable this check entirely.
resolves #2178

Adds conditional registration of class transformers for Tomcat and JBoss plugins

---

collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseTraceDaoFactory.java
collector/src/main/java/com/navercorp/pinpoint/collector/handler/AgentStatHandlerFactory.java
collector/src/test/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseTraceDaoFactoryTest.java
collector/src/test/java/com/navercorp/pinpoint/collector/handler/AgentStatHandlerFactoryTest.java
commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HBaseAdminTemplate.java
web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseTraceDaoFactory.java
web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/stat/AgentStatDaoFactory.java
web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/stat/SampledAgentStatDaoFactory.java
web/src/main/java/com/navercorp/pinpoint/web/service/stat/LegacyAgentStatChartServiceFactory.java
web/src/test/java/com/navercorp/pinpoint/web/dao/hbase/HbaseTraceDaoFactoryTest.java
web/src/test/java/com/navercorp/pinpoint/web/dao/hbase/stat/AgentStatDaoFactoryTest.java
web/src/test/java/com/navercorp/pinpoint/web/dao/hbase/stat/SampledAgentStatDaoFactoryTest.java
web/src/test/java/com/navercorp/pinpoint/web/service/stat/LegacyAgentStatChartServiceFactoryTest.java

This checks whether the required tables for trace and stat data are present in hbase when pinpoint collector and web starts up, instead of failing in runtime.
The required tables and the configuration settings are detailed in #2187.
resolves #2187

Adds checks for trace/stat tables on collector/web startup

---

agent/src/test/java/com/navercorp/pinpoint/plugin/httpclient3/HttpClientIT.java

Sometimes HttpClient3 stuck on execute releaseConnection method.
Set the connection timeout to ensure release connection .
```
"main" prio=10 tid=0x00007fb0e800d000 nid=0x1faa runnable [0x00007fb0ec4b1000]
java.lang.Thread.State: RUNNABLE
at java.net.SocketInputStream.socketRead0(Native Method)
at java.net.SocketInputStream.read(SocketInputStream.java:129)
at java.io.BufferedInputStream.fill(BufferedInputStream.java:218)
at java.io.BufferedInputStream.read1(BufferedInputStream.java:258)
at java.io.BufferedInputStream.read(BufferedInputStream.java:317)
- locked <0x00000007ad42b490> (a java.io.BufferedInputStream)
at org.apache.commons.httpclient.ChunkedInputStream.read(ChunkedInputStream.java:181)
at org.apache.commons.httpclient.ChunkedInputStream.read(ChunkedInputStream.java:195)
at …
```

[no issue] Fixed test case.

---

agent/src/test/java/com/navercorp/pinpoint/plugin/httpclient3/HttpClientIT.java

Sometimes HttpClient3 stuck on execute releaseConnection method.
Set the so_timeout to ensure release connection .
"main" prio=10 tid=0x00007fb0e800d000 nid=0x1faa runnable [0x00007fb0ec4b1000]
java.lang.Thread.State: RUNNABLE
at java.net.SocketInputStream.socketRead0(Native Method)
at java.net.SocketInputStream.read(SocketInputStream.java:129)
at java.io.BufferedInputStream.fill(BufferedInputStream.java:218)
at java.io.BufferedInputStream.read1(BufferedInputStream.java:258)
at java.io.BufferedInputStream.read(BufferedInputStream.java:317)
- locked <0x00000007ad42b490> (a java.io.BufferedInputStream)
at org.apache.commons.httpclient.ChunkedInputStream.read(ChunkedInputStream.java:181)
at org.apache.commons.httpclient.ChunkedInputStream.read(ChunkedInputStream.java:195)
at …

[no issue] Fixed test case

---

bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/bindvalue/BindValueUtils.java
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/bindvalue/ClassNameConverter.java
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/bindvalue/ObjectConverter.java
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/bindvalue/SimpleTypeConverter.java
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/util/StringUtils.java
bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/util/StringUtilsTest.java
plugins/httpclient3/src/main/java/com/navercorp/pinpoint/plugin/httpclient3/interceptor/HttpMethodBaseExecuteMethodInterceptor.java
plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/DefaultClientExchangeHandlerImplStartMethodInterceptor.java
plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/HttpRequestExecutorExecuteMethodInterceptor.java
plugins/jboss/src/main/java/com/navercorp/pinpoint/plugin/jboss/interceptor/StandardHostValveInvokeInterceptor.java
plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/interceptor/AbstractServerHandleInterceptor.java
plugins/ning-asynchttpclient/src/main/java/com/navercorp/pinpoint/plugin/ning/asynchttpclient/interceptor/ExecuteRequestInterceptor.java
plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/interceptor/HttpEngineSendRequestMethodInterceptor.java
plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/interceptor/client/TServiceClientReceiveBaseInterceptor.java
plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/interceptor/client/TServiceClientSendBaseInterceptor.java
plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/interceptor/StandardHostValveInvokeInterceptor.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/AbstractRecorder.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/util/AnnotationValueMapper.java

#2312
- drop() -> abbreviate()
- Similar to apache-common-lang StringUtils.abbreviate()

#2312 Deprecated StringUtils.drop() api

---

pom.xml

- hbase-client : 1.2.0-cdh5.7.3 -> hbase-shaded-client : 1.2.4
(Avoid servlet classLoading problem)

#2321 Update library

---

web/src/main/java/com/navercorp/pinpoint/web/controller/AdminController.java
web/src/main/java/com/navercorp/pinpoint/web/interceptor/AdminAuthInterceptor.java

If `admin.password` is not set in *pinpoint-web.properties*, admin APIs do not require password parameter.

Makes password for admin APIs optional

---

.gitignore
CONTRIBUTING.md
hbase/pom.xml

When I use this `mvn -f hbase docker: build` command, to build the hbase project inside the pinpoint, I received this message 'returned a non-zero`.
When I looked at the pom.xml and I saw two different uses between the same variable.
So I changed `$ {HBASE_HOME}` to `$ HBASE_HOME` and everything works fine.

Fix hbase pom

---

web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/stat/v2/HbaseAgentStatDaoOperationsV2.java
web/src/main/java/com/navercorp/pinpoint/web/mapper/stat/AbstractAgentStatSampler.java
web/src/main/java/com/navercorp/pinpoint/web/mapper/stat/ActiveTraceSampler.java
web/src/main/java/com/navercorp/pinpoint/web/mapper/stat/AgentStatSampler.java
web/src/main/java/com/navercorp/pinpoint/web/mapper/stat/CpuLoadSampler.java
web/src/main/java/com/navercorp/pinpoint/web/mapper/stat/JvmGcDetailedSampler.java
web/src/main/java/com/navercorp/pinpoint/web/mapper/stat/JvmGcSampler.java
web/src/main/java/com/navercorp/pinpoint/web/mapper/stat/SampledAgentStatResultExtractor.java
web/src/main/java/com/navercorp/pinpoint/web/mapper/stat/TransactionSampler.java
web/src/test/java/com/navercorp/pinpoint/web/mapper/stat/SampledAgentStatResultExtractorTest.java

When multiple agents are registered under a single agent id, stat data from different agents are mixed up and the stat charts shows unpredictable data.
This change makes it so that in cases where there are multiple stat data to choose from in a single timeslot, it chooses the stat data from the most recently started agent.
resolves #2345

Picks the most recently started agent's data when multiple agents with the same agent id sent stat data simultaneouly

---

web/src/main/java/com/navercorp/pinpoint/web/mapper/stat/AbstractAgentStatSampler.java
web/src/main/java/com/navercorp/pinpoint/web/mapper/stat/ActiveTraceSampler.java
web/src/main/java/com/navercorp/pinpoint/web/mapper/stat/CpuLoadSampler.java
web/src/main/java/com/navercorp/pinpoint/web/mapper/stat/JvmGcDetailedSampler.java
web/src/main/java/com/navercorp/pinpoint/web/mapper/stat/JvmGcSampler.java
web/src/main/java/com/navercorp/pinpoint/web/mapper/stat/TransactionSampler.java
web/src/test/java/com/navercorp/pinpoint/web/mapper/stat/JvmGcSamplerTest.java
web/src/test/java/com/navercorp/pinpoint/web/mapper/stat/SampledAgentStatResultExtractorTest.java

Agent stat samplers need timeslot index to tell if a data point is the start of jvm life cycle or is the first timeslot when there is not previous data point.
related to #2345

Exposes timeslot index to agent stat samplers

---

commons-server/pom.xml
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/header/BitCountingHeaderDecoder.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/header/BitCountingHeaderEncoder.java
commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/codec/stat/header/BitCountingHeaderEncoderTest.java
commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/codec/stat/header/Jdk7BitCountingHeaderDecoder.java
commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/codec/stat/header/Jdk7BitCountingHeaderEncoder.java

Remove `BitSet` JDK 7 API usages.
Related to #2415

Removes JDK 7 API usage

---

agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/asynchronous/ThriftHalfSyncHalfAsyncServerAsyncIT.java
agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/asynchronous/ThriftNonblockingServerAsyncIT.java
agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/asynchronous/ThriftThreadedSelectorServerAsyncIT.java
agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/synchronous/ThriftHalfSyncHalfAsyncServerIT.java
agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/synchronous/ThriftNonblockingServerIT.java
agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/synchronous/ThriftSimpleServerIT.java
agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/synchronous/ThriftThreadPoolServerIT.java
agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/synchronous/ThriftThreadedSelectorServerIT.java

Disable thrift integration tests for 0.10.0+ until Pinpoint thrift plugin is updated to support libthrift v0.10.0.

Disables integration tests for thrift 0.10.0

---

agent/src/test/java/com/navercorp/pinpoint/plugin/jdbc/mariadb/MariaDB_IT_Base.java

mariadb connector 1.5.8 seems to throw an exception when resultset cursor is moved to an absolute index when Statement is created using their default methods.

Fixes mariadb plugin integration test

---

commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/AgentEventTypeCategory.java
web/src/main/java/com/navercorp/pinpoint/web/controller/AgentInfoController.java
web/src/main/java/com/navercorp/pinpoint/web/filter/agent/AgentEventFilter.java
web/src/main/java/com/navercorp/pinpoint/web/service/AgentEventServiceImpl.java
web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoService.java
web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoServiceImpl.java
web/src/main/java/com/navercorp/pinpoint/web/view/AgentEventMarkerSerializer.java
web/src/main/java/com/navercorp/pinpoint/web/vo/DurationalAgentEvent.java
web/src/main/java/com/navercorp/pinpoint/web/vo/timeline/Timeline.java
web/src/main/java/com/navercorp/pinpoint/web/vo/timeline/TimelineSegment.java
web/src/main/java/com/navercorp/pinpoint/web/vo/timeline/inspector/AgentEventMarker.java
web/src/main/java/com/navercorp/pinpoint/web/vo/timeline/inspector/AgentEventTimeline.java
web/src/main/java/com/navercorp/pinpoint/web/vo/timeline/inspector/AgentEventTimelineBuilder.java
web/src/main/java/com/navercorp/pinpoint/web/vo/timeline/inspector/AgentEventTimelineSegment.java
web/src/main/java/com/navercorp/pinpoint/web/vo/timeline/inspector/AgentState.java
web/src/main/java/com/navercorp/pinpoint/web/vo/timeline/inspector/AgentStatusTimeline.java
web/src/main/java/com/navercorp/pinpoint/web/vo/timeline/inspector/AgentStatusTimelineBuilder.java
web/src/main/java/com/navercorp/pinpoint/web/vo/timeline/inspector/AgentStatusTimelineSegment.java
web/src/main/java/com/navercorp/pinpoint/web/vo/timeline/inspector/InspectorTimeline.java
web/src/test/java/com/navercorp/pinpoint/web/vo/timeline/inspector/AgentEventTimelineTest.java
web/src/test/java/com/navercorp/pinpoint/web/vo/timeline/inspector/AgentStatusTimelineTest.java

Inspector view's agent status timeline should render life cycle states correctly on the timeline even if there are multiple agents sharing the same agent id.
To do this, each life cycle is calculated separately using agent's lifecycle event data (such as connected, disconnected, ping, etc) and their respective agent's start timestamp.
These life cycles are then laid on top of a single dimension to form the complete timeline.
Also divides up the timeline into segments to group up agent events that happened in a single segment to
a) prevent rendering too many agent event markers that might crash browsers, and
b) provide an easier way to view events that happened too close to each other that clicking on them proved impossible.

Creates Inspector view agent status timeline server side

---

web/src/main/java/com/navercorp/pinpoint/web/mapper/stat/sampling/sampler/DataSourceSampler.java

1. Limits the number of decimal point for active avg and max avg

[#2496] Add datasource metric collection

---

agent/pom.xml
agent/src/test/resources/thrift/Echo.thrift

Previously, thrift integration tests were compiled by whatever libthrift version inherited from the parent pom.
So when pinpoint's internal thrift version was upgraded to 0.10.0, Thrift IT would be compiled using 0.10.0, but would run on 0.9.x and any changes in API signatures would cause errors at runtime (implementations of `AsyncProcessFunction` for example).
This PR makes it so that thrift ITs are compiled using libthrift version independent of the one used when compiling the agent.
resolves #2522

Makes test-compile libthrift independent from one used by the agent

---

bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/interceptor/CallableStatementBindVariableInterceptor.java
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/interceptor/CallableStatementExecuteQueryInterceptor.java
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/interceptor/CallableStatementRegisterOutParameterInterceptor.java
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/interceptor/ConnectionCloseInterceptor.java
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/interceptor/DriverConnectInterceptor.java
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/interceptor/DriverConnectInterceptorV2.java
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/interceptor/PreparedStatementBindVariableInterceptor.java
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/interceptor/PreparedStatementCreateInterceptor.java
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/interceptor/PreparedStatementExecuteQueryInterceptor.java
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/interceptor/StatementCreateInterceptor.java
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/interceptor/StatementExecuteQueryInterceptor.java
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/interceptor/StatementExecuteUpdateInterceptor.java
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/interceptor/TransactionCommitInterceptor.java
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/interceptor/TransactionRollbackInterceptor.java
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/interceptor/TransactionSetAutoCommitInterceptor.java

- This fix has compatibility issues

[#2862] Remove Annotation of JDBC Interceptor

---

agent/src/test/java/com/navercorp/pinpoint/plugin/jdbc/mariadb/MariaDB_1_4_x_to_1_6_0_IT.java

Integration tests for 1.6.x and 2.x should be added once they are supported by mariadb plugin.

Limits MariaDB integration test to exclude 1.6.x and 2.x

---

commons/src/main/java/com/navercorp/pinpoint/common/trace/ServiceType.java
web/src/main/java/com/navercorp/pinpoint/web/filter/DefaultFilterBuilder.java
web/src/main/java/com/navercorp/pinpoint/web/filter/FilterHint.java
web/src/main/java/com/navercorp/pinpoint/web/filter/LinkFilter.java
web/src/main/java/com/navercorp/pinpoint/web/filter/RpcURLPatternFilter.java
web/src/test/java/com/navercorp/pinpoint/web/filter/LinkFilterTest.java
web/src/test/java/com/navercorp/pinpoint/web/filter/RpcURLPatternFilterTest.java
web/src/test/java/com/navercorp/pinpoint/web/util/ServiceTypeRegistryMockFactory.java

This fixes the following:
1. WAS -> UNKNOWN filtering by request url pattern - resolves #2924 
2. WAS -> WAS filtering when receiving node has receiving spans missing (due to partly installed agents or packet losses) - resolves #2939

Fixes transaction filtering

---

web/src/main/java/com/navercorp/pinpoint/web/controller/MapController.java
web/src/main/java/com/navercorp/pinpoint/web/service/MapServiceImpl.java
web/src/main/java/com/navercorp/pinpoint/web/service/map/ApplicationsMapCreatorFactory.java
web/src/main/java/com/navercorp/pinpoint/web/service/map/DefaultApplicationMapCreator.java
web/src/main/java/com/navercorp/pinpoint/web/service/map/LinkDataMapProcessor.java
web/src/main/java/com/navercorp/pinpoint/web/service/map/LinkDataMapProcessors.java
web/src/main/java/com/navercorp/pinpoint/web/service/map/LinkSelectorFactory.java
web/src/main/java/com/navercorp/pinpoint/web/service/map/RpcCallProcessor.java
web/src/main/java/com/navercorp/pinpoint/web/service/map/WasOnlyProcessor.java
web/src/main/java/com/navercorp/pinpoint/web/vo/SearchOption.java
web/src/test/java/com/navercorp/pinpoint/web/service/map/BidirectionalLinkSelectorTestBase.java
web/src/test/java/com/navercorp/pinpoint/web/service/map/LinkSelectorTestBase.java
web/src/test/java/com/navercorp/pinpoint/web/service/map/RpcCallProcessorTest.java
web/src/test/java/com/navercorp/pinpoint/web/service/map/UnidirectionalLinkSelectorTestBase.java
web/src/test/java/com/navercorp/pinpoint/web/service/map/WasOnlyProcessorTest.java

This adds a query parameter *wasOnly* to main server map queries.
If the parameter is true, `LinkData` to applications with `TERMINAL` service types (calls made to terminal nodes such as database and cache), or `UNKNOWN` service types (rpc calls made to destinations without an agent) are filtered out and the destination nodes will subsequently not be rendered in the server map.
Default value is false to maintain the same query behavior as the current API.

Adds a parameter to filter out terminal and unknown nodes when querying server map

---

web/src/main/java/com/navercorp/pinpoint/web/applicationmap/appender/histogram/DefaultNodeHistogramFactory.java
web/src/main/java/com/navercorp/pinpoint/web/controller/MapController.java
web/src/main/java/com/navercorp/pinpoint/web/service/ResponseTimeHistogramService.java
web/src/main/java/com/navercorp/pinpoint/web/service/ResponseTimeHistogramServiceImpl.java
web/src/main/java/com/navercorp/pinpoint/web/vo/ApplicationPair.java
web/src/main/java/com/navercorp/pinpoint/web/vo/ApplicationPairs.java

Some nodes may have inbound edges from multiple applications. This allows the node histogram API to receive multiple applications for these cases.

Allows specifying multiple source/destination applications when querying for node histograms

---

rpc/src/main/java/com/navercorp/pinpoint/rpc/client/DefaultPinpointClientFactory.java
rpc/src/main/java/com/navercorp/pinpoint/rpc/client/DefaultPinpointClientHandler.java
rpc/src/main/java/com/navercorp/pinpoint/rpc/client/PinpointClientFactory.java

1. remove unused code (since 2015 ~ )
2. use same method as method used elsewhere (ChannelHandlerContext.getChannel() -> ChannelStateEvent.getChannel). result is same.
(http://netty.io/3.5/guide/ netty guide)

[#noissue] cleanup rpc

---

web/src/main/resources/servlet-context.xml

Following changes are applied : 
* Remove explicit wiring of request handler mapping beans - The new support classes are enabled automatically through the MVC namespace
* Remove deprecated HTTP 1.0 cache-related headers, and disables caching all together by adding `Cache-Control : no-store`
* Clean up unused namespace declarations
resolves #3406

Updates deprecated spring mvc configurations for pinpoint web

---

bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/context/Trace.java
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/context/TraceContext.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/AsyncTrace.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultReference.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTrace.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTraceContext.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DisableTrace.java

#2584
- DisableTrace must be closed in 1.7.0 or later

[#2584] Added 'DisableTrace.close() to 'TraceContext.removeTraceObject()' for API compatibility

---

agent/src/test/java/com/navercorp/pinpoint/plugin/hystrix/HystrixCommand_1_4_0_to_1_5_2_IT.java
agent/src/test/java/com/navercorp/pinpoint/plugin/hystrix/HystrixObservableCommand_1_4_0_to_1_5_2_IT.java

Hystrix 1.4.0 - 1.4.2 requires Java 7

Fixes java version for hystrix plugin integration tests

---

profiler/src/main/java/com/navercorp/pinpoint/profiler/context/monitor/DataSourceMonitorWrapper.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/context/monitor/DataSourceMonitorWrapperTest.java

- DataSourceMonitorWrapper.getServiceType() don't return null
- Fixed infer static analysis issue

[#noissue] Fixed NPE for DefaultDataSourceMetric.collectDataSource()

---

agent/src/test/java/com/navercorp/pinpoint/plugin/hikaricp/HikariCpIT.java
plugins/hikaricp/src/main/java/com/navercorp/pinpoint/plugin/hikaricp/HikariCpConstants.java
plugins/hikaricp/src/main/java/com/navercorp/pinpoint/plugin/hikaricp/HikariCpPlugin.java
plugins/hikaricp/src/main/java/com/navercorp/pinpoint/plugin/hikaricp/interceptor/DataSourceConstructorInterceptor.java

1. trace support to create HikaiPool using com.zaxxer.hikari.HikariDataSource.getConnection() method

[#3611] Change HikariCP data source trace scope

---

plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/JettyPlugin.java

In jetty 8.0 env, I found that the jetty plugin doesn't work. so fix it. Jetty 8.2 or Jetty 9.0 is OK.

[bug fix] to support Jetty 8.0

---

agent/src/main/resources-local/pinpoint.config
agent/src/main/resources-release/pinpoint.config

To trace Hystrix commands, rxjava plugin must also be enabled.
Explicitly stating this directly on the configuration file would be the easiest way to let users be aware of this.

Adds additional information on configuring hystrix plugin

---

agent/src/test/java/com/navercorp/pinpoint/plugin/jdk7/rabbitmq/util/RabbitMQTestConstants.java

When AutorecoveringConnection is used, it shuffles the IPs mapped to a domain randomly and uses it. IT connections are made against 'localhost' and this may be resolved to more than 1 IP, which was causing random test failures.

Fixes random RabbitMQ plugin IT failures

---

agent/pom.xml
agent/src/test/java/com/navercorp/pinpoint/plugin/jdk7/rabbitmq/RabbitMQTestRunner.java
agent/src/test/java/com/navercorp/pinpoint/plugin/jdk7/rabbitmq/spring/SpringAmqpRabbitTestRunner.java
agent/src/test/java/com/navercorp/pinpoint/plugin/jdk7/rabbitmq/spring/SpringAmqpRabbit_1_3_3_to_1_4_2_IT.java
agent/src/test/java/com/navercorp/pinpoint/plugin/jdk7/rabbitmq/spring/SpringAmqpRabbit_1_4_2_to_1_7_0_IT.java
agent/src/test/java/com/navercorp/pinpoint/plugin/jdk7/rabbitmq/spring/SpringAmqpRabbit_1_7_0_to_2_0_0_IT.java
agent/src/test/java/com/navercorp/pinpoint/plugin/jdk7/rabbitmq/spring/SpringAmqpRabbit_2_x_IT.java
agent/src/test/java/com/navercorp/pinpoint/plugin/jdk7/rabbitmq/spring/TestApplicationContext.java
agent/src/test/java/com/navercorp/pinpoint/plugin/jdk7/rabbitmq/util/RabbitMQTestConstants.java
agent/src/test/java/com/navercorp/test/pinpoint/plugin/rabbitmq/spring/TestMessageHolder.java
agent/src/test/java/com/navercorp/test/pinpoint/plugin/rabbitmq/spring/config/CommonConfig.java
agent/src/test/java/com/navercorp/test/pinpoint/plugin/rabbitmq/spring/config/MessageListenerConfig_Post_1_4_0.java
agent/src/test/java/com/navercorp/test/pinpoint/plugin/rabbitmq/spring/config/MessageListenerConfig_Pre_1_4_0.java
agent/src/test/java/com/navercorp/test/pinpoint/plugin/rabbitmq/spring/config/ReceiverConfig_Post_1_6_0.java
agent/src/test/java/com/navercorp/test/pinpoint/plugin/rabbitmq/spring/config/ReceiverConfig_Pre_1_6_0.java
agent/src/test/java/com/navercorp/test/pinpoint/plugin/rabbitmq/spring/handler/TestMessageHandler.java
agent/src/test/java/com/navercorp/test/pinpoint/plugin/rabbitmq/spring/listener/TestMessageListener.java
agent/src/test/java/com/navercorp/test/pinpoint/plugin/rabbitmq/spring/receiver/TestReceiver.java
agent/src/test/java/com/navercorp/test/pinpoint/plugin/rabbitmq/spring/receiver/TestReceiver_Post_1_6_0.java
agent/src/test/java/com/navercorp/test/pinpoint/plugin/rabbitmq/spring/receiver/TestReceiver_Pre_1_6_0.java
agent/src/test/java/com/navercorp/test/pinpoint/plugin/rabbitmq/spring/service/TestReceiverService.java
agent/src/test/java/com/navercorp/test/pinpoint/plugin/rabbitmq/spring/service/TestSenderService.java
plugins/rabbitmq/README.md
plugins/rabbitmq/src/main/java/com/navercorp/pinpoint/plugin/rabbitmq/client/RabbitMQClientConstants.java
plugins/rabbitmq/src/main/java/com/navercorp/pinpoint/plugin/rabbitmq/client/RabbitMQClientPlugin.java
profiler-test/src/main/java/com/navercorp/pinpoint/test/PluginTestAgent.java

This adds support for **RabbitTemplate** public APIs and integration tests for rabbitmq plugin on spring-amqp-rabbitmq.
related to #1412

Adds additional trace support for Spring-amqp-rabbitmq

---

web/src/main/java/com/navercorp/pinpoint/web/mapper/MapStatisticsCalleeMapper.java

Since virtual queue nodes are emulated, they do not have an agent id they can use to record statistics. Callee statistics for producer -> virtual queue node therefore must be emulated using producer's message queue span event.
Callee statistics generated this way use the caller span's end point as caller host.
When user-defined entry points are defined and caller spans are generated from this, they will not have an end point, throwing an NPE when querying for the server map.
Since this is a valid use-case, we must handle cases where the caller host is null when a virtual queue node's callee statistics is queried for the server map.
related to #3985

Allows empty caller host for virtual queue nodes

---

agent/src/test/java/com/navercorp/pinpoint/plugin/jdk7/rabbitmq/RabbitMQTestRunner.java
plugins/rabbitmq/src/main/java/com/navercorp/pinpoint/plugin/rabbitmq/client/RabbitMQClientPlugin.java
plugins/rabbitmq/src/main/java/com/navercorp/pinpoint/plugin/rabbitmq/client/interceptor/ConsumerHandleDeliveryInterceptor.java
plugins/rabbitmq/src/main/java/com/navercorp/pinpoint/plugin/rabbitmq/client/interceptor/RabbitMQConsumerDispatchInterceptor.java

Previously, **ConsumerDispatcher** injected async trace context into **Consumer** directly.
However, the same **Consumer** object is shared between different message deliveries, the async trace context may be overwritten, or shared between different transactions.
This fixes so that async trace context is no longer injected into a shared **Consumer** object, and is instead injected into the message envelope which gets created for each message delivery.
resolves #4014

Fixes async trace context lingering in consumer objects

---

plugins/dubbo/src/main/java/com/navercorp/pinpoint/plugin/dubbo/DubboConstants.java
plugins/dubbo/src/main/java/com/navercorp/pinpoint/plugin/dubbo/DubboTraceMetadataProvider.java
plugins/dubbo/src/main/java/com/navercorp/pinpoint/plugin/dubbo/interceptor/DubboProviderInterceptor.java

When dubbo provider try to create trace, there maybe already has a trace in threadlocal. To avoid re-create a new trace, add a scope to trace to indicate not to remove the trace when leaving dubbo provider method.
This should fix issue #3906, #2981 and #3318.
To reproduce the condition I only using injvm call mode of dubbo to verify the fix, but I am not sure this will cover all 3 issues mentions above. The test app is at https://github.com/jiaqifeng/quickdemo.

[#3906] dubbo plugin: already trace exist

---

profiler/src/main/java/com/navercorp/pinpoint/profiler/logging/Slf4jPLoggerAdapter.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/logging/Slf4jPLoggerAdapterTest.java

Avoid getDeclaringClass () calls when enclosing class.

[#noissue] Fix get simple class name of Logger

---

bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/DefaultProfilerConfig.java

pinpoint.config (file line 46)
profiler.jvm.stat.collect.detailed.metrics=true
DefaultProfilerConfig.java fix
stat.jvm --> jvm.stat

Fixed fetching detail metrics.(Fix incorrectly typed values in metrics)

---

profiler/src/main/java/com/navercorp/pinpoint/profiler/AgentInfoSender.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/ResponseMessageFutureListener.java

rename (AgentInfoSenderListener -> ResponseMessageFutureListener)
AgentInfoSenderListener is a structure that can be used when set The ResponseMessage object in Future.
That's why I change the name.

[#noissue] rename AgentInfoSenderListener

---

plugins/dubbo/src/main/java/com/navercorp/pinpoint/plugin/dubbo/interceptor/DubboProviderInterceptor.java

When the profiler.sampling.rate > 1, the DubboProviderInterceptor.before() have too many error log in the logger.warn(). Because the "final SpanRecorder recorder = trace.getSpanRecorder();" alway null when trace.canSampled() is false.

fix error when no sampled in the dubbo

---

.travis.yml

Build throws `java.security.ProviderException`, with root cause: no such provider: SunEC when fetching npm from registry.
May be due to openjdk 7 not having the proper security provider.
Try a potential workaround suggested in https://bugs.launchpad.net/ubuntu/+source/openjdk-6/+bug/1006776

Fixes travis ci security provider error

---

profiler-optional/profiler-optional-jdk9/pom.xml

- Remove maven-failsafe-plugin

[#4214] Improved compatibility of ClassLoader.defineClass() for java9

---

commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/SpanUtils.java
commons-server/src/test/java/com/navercorp/pinpoint/common/server/util/SpanUtilsTest.java
web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseApplicationTraceIndexDao.java

This fixes incorrect byte length used for generating trace index row key.
Trace index row key generated using agent ids have been removed as they are deprecated and no longer used.
resolves #4312

Fixes trace index row key generation

---

agent/src/main/resources-local/pinpoint.config
agent/src/main/resources-release/pinpoint.config
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/DefaultProfilerConfig.java
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/ProfilerConfig.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/PinpointClientFactoryProvider.java

Allows the ClientOption setting in the setup file
```
profiler.tcpdatasender.client.write.timeout=3000
profiler.tcpdatasender.client.request.timeout=3000
profiler.tcpdatasender.client.reconnect.interval=3000
profiler.tcpdatasender.client.ping.interval=300000
profiler.tcpdatasender.client.handshake.interval=60000
```

[4346] Allows the ClientOption setting in the setup file

---

rpc/src/main/java/com/navercorp/pinpoint/rpc/server/DefaultPinpointServer.java

Sometimes the handshake result is not ready to respond.
If return null in handleHandshake method, do not save the result immediately.
Let the client send a handshake packet again.

[#4358] Change the save results policy in handshake

---

pom.xml

This changes hbase shaded client version to 1.2.6.1.
resolves #4385

Ups hbase shaded client version

---

agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/client/AsyncEchoTestClient.java
agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/client/SyncEchoTestClient.java
agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/server/AsyncEchoTestServer.java
agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/server/SyncEchoTestServer.java
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/util/SocketAddressUtils.java
bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/plugin/util/SocketAddressUtilsTest.java
plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/ThriftUtils.java
plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/interceptor/server/TBaseProcessorProcessInterceptor.java
plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/interceptor/tprotocol/server/TProtocolReadMessageEndInterceptor.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/DefaultAgent.java

This solves the issue where the Thrift plugin would attempt a reverse DNS lookup when retrieving the host name if a **TSocket** was created using an address.
Utility methods are also added, which given an **InetSocketAddress**, would retrieve the host name or the address without triggering forward/reverse DNS lookup.
resolves #4389

Fixes hostname retrieval triggering possible DNS lookups for Thrift plugin

---

agent/src/main/resources-local/pinpoint.config
agent/src/main/resources-release/pinpoint.config
plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/interceptor/ConsumerRecordEntryPointInterceptor.java

Avoid creating corrupted stacks if Trace is already active.

[#3835] kafka plugin

---

agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/rabbitmq/RabbitMQClient_2_7_0_to_3_3_0_IT.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/rabbitmq/RabbitMQClient_3_3_0_to_4_0_0_IT.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/rabbitmq/RabbitMQClient_4_x_IT.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/rabbitmq/RabbitMQClient_5_x_IT.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/rabbitmq/spring/SpringAmqpRabbit_1_3_3_to_1_4_2_IT.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/rabbitmq/spring/SpringAmqpRabbit_1_4_2_to_1_7_0_IT.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/rabbitmq/spring/SpringAmqpRabbit_1_7_0_to_1_7_7_IT.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/rabbitmq/spring/SpringAmqpRabbit_1_7_7_to_2_0_0_IT.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/rabbitmq/spring/SpringAmqpRabbit_2_0_0_to_2_0_3_IT.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/rabbitmq/spring/SpringAmqpRabbit_2_0_3_to_2_x_IT.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/rabbitmq/util/DerbyUtil.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/rabbitmq/util/TestBroker.java

This cleans up RabbitMQ integration tests to do the following :
* Set qpid work directory to temp directory
* Suppress generation of derby.log file
* Remove unused JvmArgument

Cleans up rabbitmq integration test

---

web/src/main/java/com/navercorp/pinpoint/web/batch/job/AgentCountReader.java
web/src/main/java/com/navercorp/pinpoint/web/controller/AgentInfoController.java
web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoService.java
web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoServiceImpl.java
web/src/main/java/com/navercorp/pinpoint/web/vo/ApplicationAgentsList.java
web/src/test/java/com/navercorp/pinpoint/web/vo/ApplicationAgentsListTest.java

This removes agents that were shutdown before the time period queried in Inspector view to stop irrelevant agents running in containers from polluting the agent list.
resolves #4560

Filters agents in shutdown containers from agent list

---

agent/src/main/resources-local/pinpoint.config
agent/src/main/resources-release/pinpoint-real-env-lowoverhead-sample.config
agent/src/main/resources-release/pinpoint.config
plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/KafkaConstants.java
plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/KafkaMetadataProvider.java
plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/KafkaPlugin.java
plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/interceptor/ConsumerMultiRecordEntryPointInterceptor.java
plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/interceptor/ConsumerRecordEntryPointInterceptor.java
plugins/kafka/src/test/java/com/navercorp/pinpoint/plugin/kafka/interceptor/ConsumerConstructorInterceptorTest.java
plugins/kafka/src/test/java/com/navercorp/pinpoint/plugin/kafka/interceptor/ConsumerMultiRecordEntryPointInterceptorTest.java
plugins/kafka/src/test/java/com/navercorp/pinpoint/plugin/kafka/interceptor/ConsumerPollInterceptorTest.java
plugins/kafka/src/test/java/com/navercorp/pinpoint/plugin/kafka/interceptor/ConsumerRecordEntryPointInterceptorTest.java
plugins/kafka/src/test/java/com/navercorp/pinpoint/plugin/kafka/interceptor/ProducerConstructorInterceptorTest.java
plugins/kafka/src/test/java/com/navercorp/pinpoint/plugin/kafka/interceptor/ProducerSendInterceptorTest.java

Title: Kafka Plugin Contribution (optimize)
Link: https://github.com/VictorZeng/pinpoint/tree/kafka-plugin/plugins/kafka
Target: pinpoint-kafka-plugin
Supported Version: kafka version 0.11+.
Description: Refactor Kafka Plugin and add ConsumerRecords Interceptor. If you consume from the same topic and want to intercept batch consumption methods.
Add Annotations:
-  (143, "kafka.batch", VIEW_IN_RECORD_SET)

[#4785] Refactor Kafka Plugin and Add ConsumerRecords Interceptor.

---

agent-it/src/test/java/com/navercorp/pinpoint/plugin/hbase/HbaseClientIT.java
plugins/hbase/pom.xml
plugins/hbase/src/main/java/com/navercorp/pinpoint/plugin/hbase/interceptor/HbaseTableMethodInterceptor.java

This removes reflection inside hbase plugin interceptor and replaces them with method dispatch.
Also fixes hbase plugin IT
related to #4367

Cleans up Hbase client plugin and IT

---

agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/rabbitmq/spring/SpringAmqpRabbit_2_1_x_to_2_x_IT.java

2.1.1.RELEASE has spring-xxx 5.1.2.BUILD-SNAPSHOT dependencies that are not in maven central.

Excludes spring-rabbit 2.1.1.RELEASE from integration test

---

web/src/main/webapp/v2/src/app/core/components/server-map/class/server-map-diagram-with-visjs.class.ts

-  Adjust the timing of the click node event for the base node in order to set the right width of the container
- Redraw the diagram to set the size of it only when it's the first rendering

[#4946] Fix: Adjust the timing of the click node event for the base node 

---

agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/rabbitmq/RabbitMQTestRunner.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/rabbitmq/spring/SpringAmqpRabbit_1_3_3_to_1_4_2_IT.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/rabbitmq/spring/SpringAmqpRabbit_1_4_2_to_1_7_0_IT.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/rabbitmq/spring/SpringAmqpRabbit_1_7_0_to_1_7_7_IT.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/rabbitmq/spring/SpringAmqpRabbit_1_7_7_to_2_0_0_IT.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/rabbitmq/spring/SpringAmqpRabbit_2_0_0_to_2_0_3_IT.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/rabbitmq/spring/SpringAmqpRabbit_2_0_3_to_2_1_0_IT.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/rabbitmq/spring/SpringAmqpRabbit_2_1_x_to_2_x_IT.java

Consumer traces would occasionally arrive before producer traces resulting in test failures.
Change so that consumer traces and producer traces are checked separately while still checking for trace ordering within them.

Separates producer/consumer trace verification

---

web/src/main/webapp/v2/src/app/core/components/server-map/server-map-container.component.ts
web/src/main/webapp/v2/src/app/core/components/server-map/server-map-for-filtered-map-container.component.ts
web/src/main/webapp/v2/src/app/core/components/side-bar/side-bar-container.component.ts

- If the node/link is a merged one, isAuthorized property has to be set as true
- Else, isAuthorized property value will be evaluated by the target node state

[#noissue] Fix: Set isAuthorized property on the server map data correctly

---

agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/hbase/HbaseClientIT.java

There was a problem in the IntegrationTests that could not be loaded from jvm6,
so it make not run all of jvm6 integration tests.

[#5071] Move the location of some IntegrationTests

---

web/src/main/java/com/navercorp/pinpoint/web/vo/ApplicationAgentsList.java
web/src/test/java/com/navercorp/pinpoint/web/vo/ApplicationAgentsListTest.java

Agents running in container often have meaningless agent ids, so sorting them by agent ids do not have merit.
Sorting them by their start timestamp (in descending order) would be more useful.
resolves #5026

Sorts agents running in containers by their start timestamp

---

agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdbc/mariadb/MariaDB_2_0_1_to_2_4_0_IT.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdbc/mariadb/MariaDB_2_4_x_IT.java
plugins/mariadb-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/mariadb/MariaDBPlugin.java

Mariadb-connector-j 2.4.0 has been released and with it, class names have been changed.
```
org.mariadb.jdbc.MariaDbPreparedStatementServer -> org.mariadb.jdbc.ServerSidePreparedStatement
org.mariadb.jdbc.MariaDbPreparedStatementClient -> org.mariadb.jdbc.ClientSidePreparedStatement
```

Adds support for mariadb-connector-j 2.4.x

---

agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdbc/mariadb/MariaDB_1_6_x_to_1_8_0_IT.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdbc/mariadb/MariaDB_1_8_0_to_2_0_0_IT.java
plugins/mariadb-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/mariadb/MariaDBPlugin.java

Mariadb-connector-j 1.8.0 has been released and with it, class name changes introduced in 2.4.0 have been backported similar to #5215.
```
org.mariadb.jdbc.MariaDbPreparedStatementServer -> org.mariadb.jdbc.ServerSidePreparedStatement
org.mariadb.jdbc.MariaDbPreparedStatementClient -> org.mariadb.jdbc.ClientSidePreparedStatement
```

Adds support for mariadb-connector-j 1.8.x

---

agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdbc/mariadb/MariaDB_1_6_x_to_1_8_0_IT.java

Wrong dependency version range specified.

Fixes integration test for mariadb 1.6.0 to 1.8.0

---

web/src/main/webapp/v2/src/app/core/components/server-map/class/server-map-diagram-with-visjs.class.ts

- There's no other way to make it work other than setting it curved

[#noissue] Fix: Make the links visible when it's bi-directional between nodes in visjs

---

profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/classloading/JarProfilerPluginClassInjector.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/scanner/ClassScannerFactory.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/scanner/ClassScannerFactoryTest.java

When a plugin calls `Instrumentor.exist(...)` API from inside `TransformerCallback.doInTransform(...)` implementation, the agent creates a scanner to search for the given resource from the same place where the class, which the **Instrumentor** was created for, resides in.
Currently, such scanners are only created when the class resides in a single jar, or a directory.
As such, when the API is invoked inside a transformer callback for a class inside a nested jar (for example, Spring Boot or One-Jar executable jars), the agent throws an **IllegalArgumentException**.
This PR adds a workaround so that in cases for nested jars, a scanner is created to simply search for the resource from the class loader that loaded the initiating class.
This should work as the class loader must have been able …

Adds a workaround for scanning classes in nested jars

---

collector/src/main/java/com/navercorp/pinpoint/collector/cluster/route/AbstractRouteHandler.java
collector/src/main/java/com/navercorp/pinpoint/collector/cluster/route/DefaultRouteHandler.java
collector/src/main/java/com/navercorp/pinpoint/collector/cluster/route/StreamRouteHandler.java
grpc/src/main/thrift/Command.thrift
rpc/src/main/java/com/navercorp/pinpoint/rpc/PinpointSocket.java
rpc/src/main/java/com/navercorp/pinpoint/rpc/client/DefaultPinpointClient.java
rpc/src/main/java/com/navercorp/pinpoint/rpc/client/DefaultPinpointClientHandler.java
rpc/src/main/java/com/navercorp/pinpoint/rpc/client/PinpointClientHandler.java
rpc/src/main/java/com/navercorp/pinpoint/rpc/client/PinpointClientHandlerContext.java
rpc/src/main/java/com/navercorp/pinpoint/rpc/server/DefaultPinpointServer.java
rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/ClientStreamChannelContext.java
rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/StreamChannelManager.java
rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/StreamException.java
rpc/src/test/java/com/navercorp/pinpoint/rpc/stream/StreamChannelManagerTest.java
rpc/src/test/java/com/navercorp/pinpoint/test/client/TestPinpointClient.java
thrift/src/main/java/com/navercorp/pinpoint/thrift/dto/command/TRouteResult.java
thrift/src/main/thrift/Command.thrift
web/src/main/java/com/navercorp/pinpoint/web/cluster/DefaultPinpointRouteResponse.java
web/src/main/java/com/navercorp/pinpoint/web/cluster/FailedPinpointRouteResponse.java
web/src/main/java/com/navercorp/pinpoint/web/cluster/PinpointRouteResponse.java
web/src/main/java/com/navercorp/pinpoint/web/service/AgentService.java
web/src/main/java/com/navercorp/pinpoint/web/service/AgentServiceImpl.java
web/src/main/java/com/navercorp/pinpoint/web/websocket/ActiveThreadCountWorker.java
web/src/test/java/com/navercorp/pinpoint/web/cluster/PinpointRouteResponseTest.java

Delete the FailPacket field in ClientStreamChannelContext.
Through this operation, can simplifies StreamChannelContext class.

[#5384] Cleanup  code related to cluster

---

web/src/main/java/com/navercorp/pinpoint/web/controller/AgentInfoController.java

Currently, running container agents are filtered from the agent list in Inspector View if the search period is set to be in between agent ping times.
This fixes so that container agents are not filtered even if there were no ping events during the search period if their status is running.
resolves #5445

Fixes running container agents not showing up in Inspector View agent list

---

plugins/hystrix/src/main/java/com/navercorp/pinpoint/plugin/hystrix/interceptor/HystrixObservableTimeoutListenerTickInterceptor.java

`getAsyncContext(Object target, Object[] args)` has been added to **AsyncContextSpanEventSimpleAroundInterceptor**, but **HystrixObservableTimeoutListenerTickInterceptor** wasn't overriding it, thus failing to acquire **AsyncContext**.

Fixes Hystrix timeout tracing

---

profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/grpc/GrpcCommandService.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/ExponentialBackoffReconnectJob.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/GrpcDataSender.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/ReconnectJob.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/SpanGrpcDataSender.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/StatGrpcDataSender.java

1. Change the maximum time of the grpc Stream reconnect job and support to modify it. 
(max : 2min -> default : 30s) 
2. Change  connection interval time to initialize if a connection is established in a disconnected situation.
as-is :
```
(connected -> disconnected -> connected -> disconnected -> connected)
1, 2, 4, 8                  16, 32, 64
```
to-be :
```
(connected -> disconnected -> connected -> disconnected -> connected)
1, 2, 4, 8                  1, 2, 4, 8
```
3. Include connectJob in the constructor, remove timing issues

[#4558] enhance grpc reconnect 

---

web/src/main/webapp/v2/src/app/core/components/inspector-chart/inspector-chart-container.component.ts
web/src/main/webapp/v2/src/app/core/components/inspector-chart/inspector-chart.component.ts
web/src/main/webapp/v2/src/app/core/components/inspector-chart/transaction-view-chart-container.component.ts
web/src/main/webapp/v2/src/app/core/components/transaction-view-top-contents/transaction-view-top-contents-container.component.html
web/src/main/webapp/v2/src/app/core/components/transaction-view-top-contents/transaction-view-top-contents-container.component.ts

- Detach and insert the chart instead of removing it in switching the tab

[#noissue] Initialize the chart once when switching the tab on the transaction view page

---

web/src/main/java/com/navercorp/pinpoint/web/vo/SpanHint.java

[#5785] Improve memory usage in 'transactionmetadata' rest api

---

collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/AgentService.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/SpanService.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/StatService.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/command/GrpcCommandService.java
grpc/src/main/java/com/navercorp/pinpoint/grpc/StatusErrors.java

#4558 
~~~
io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
at io.grpc.Status.asRuntimeException(Status.java:517)
at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onCancel(ServerCalls.java:272)
at io.grpc.PartialForwardingServerCallListener.onCancel(PartialForwardingServerCallListener.java:40)
at io.grpc.ForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:23)
at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:40)
at io.grpc.Contexts$ContextualizedServerCallListener.onCancel(Contexts.java:96)
at io.grpc.PartialForwardingServerCallListener.onCancel(PartialForwardingServerCallListener.java:40)
at …

[#4558] Add gRPC StatusError of Collector

---

plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/KafkaPlugin.java

Added & modified 3 lines in KafkaPlugin class.
1. Added RetryingMessageListenerAdapter.
2. Bug fixed RecordMessagingMessageListenerAdapterTransform -> RecordMessagingMessageListenerAdapter. Corrected the class name instead of callback name.
3. Method name changed RecordMessagingMessageListenerAdapterTransform -> AcknowledgingConsumerAwareMessageListenerTransform
I tested it in my development environment, but I honestly don't know how to test it.
Please give me feedback if you need anything

Added RetryingMessageListenerAdapter to KafkaPlugin

---

agent-it/src/test/java/com/navercorp/pinpoint/plugin/dubbo/consumer/DubboConsumerIT.java

After adding `when(rpcInvocation.getInvoker()).thenReturn(abstractClusterInvoker);`, NullPointerException disappeared

[#5891] fix DubboConsumerIT NullPointerException

---

commons/src/main/java/com/navercorp/pinpoint/common/util/AgentUuidUtils.java
commons/src/test/java/com/navercorp/pinpoint/common/util/AgentUuidUtilsTest.java

This adds a utility class for encoding and decoding UUIDs.
Such encoded UUID will result in a 22 character with 2 pad characters. Since the pad character '=' is not a valid character for agent ids, the utility class strips away these and simply returns a 22 character long string.

Adds url and filename safe base64 encoder and decoder for UUID to be used for agent ids

---

plugins/apache-dubbo/pom.xml

Apache Dubbo 2.6.x can run on java 6 and 7, only Apache Dubbo 2.7+ requires java 8
related to #5697

Fixes apache dubbo plugin sniffer version

---

agent-it/pom.xml
agent-it/src/test/java/com/navercorp/pinpoint/plugin/log4j2/Log4j2ForAsyncLoggerIT.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/log4j2/Log4j2IT.java
agent-it/src/test/resources/pinpoint-grpc-plugin-test.config
agent-it/src/test/resources/pinpoint-spring-bean-test.config
agent/src/main/resources-local/pinpoint.config
agent/src/main/resources-release/pinpoint.config
doc/per-request_feature_guide.md
plugins/log4j2/.gitignore
plugins/log4j2/pom.xml
plugins/log4j2/src/main/java/com/navercorp/pinpoint/plugin/log4j2/Log4j2Config.java
plugins/log4j2/src/main/java/com/navercorp/pinpoint/plugin/log4j2/Log4j2Plugin.java
plugins/log4j2/src/main/java/com/navercorp/pinpoint/plugin/log4j2/interceptor/LogEventFactoryInterceptor.java
plugins/log4j2/src/main/resources/META-INF/services/com.navercorp.pinpoint.bootstrap.plugin.ProfilerPlugin
plugins/log4j2/src/test/java/com/navercorp/pinpoint/plugin/log4j2/Log4j2ConfigTest.java
plugins/log4j2/src/test/java/com/navercorp/pinpoint/plugin/log4j2/Log4j2PluginTest.java
plugins/log4j2/src/test/java/com/navercorp/pinpoint/plugin/log4j2/interceptor/LogEventFactoryInterceptorTest.java
plugins/pom.xml

Cherry-picked from the following commits and adapt for pinpoint 1.8.x:
25cf954cc [#5971] fix test code fail
249c5dd03 [#5971] [#5989] add IT for log4j2 async logger
47b75b104 [#5971] add target profiling class when use "Making All
Loggers Asynchronous" function
4e8e81fe7 [#5971] add guide for log4j2 in per request logging doc
f50f73e13 [#5971] add guide for log4j2 in per request logging doc
fb886ae78 [#5971] update agent-it for log4j2
c004a616b [#5971] Log4j2 plugin
a46775750 [#5971] support log4j2

backport log4j2 plugin to 1.8.x

---

web/src/main/java/com/navercorp/pinpoint/web/controller/BusinessTransactionController.java
web/src/main/java/com/navercorp/pinpoint/web/view/TransactionInfoViewModel.java

Now the spanId and applicationName are not exposed to the log.page.url. For the customization implementation for [log controller](https://github.com/naver/pinpoint/blob/master/doc/per-request_feature_guide.md#3-expose-log-in-pinpoint-web).   The @RequestParam("spanId") would always be null.

expose spanId and applicationName to log.page.url for customization

---

thrift/install-thrift-linux.sh

Hello.
I modified the UUOC(useless use of cat)
Pointing out UUOC is a long standing shell programming tradition, and removing them from a short-lived pipeline in a loop can speed it up by 2x. However, it's not necessarily a good use of time in practice, and rarely affects correctness.
what do you think?
Thanks.
Ref: https://en.wikipedia.org/wiki/Cat_(Unix)#Useless_use_of_cat

[#noissue] fix useless use of cat

---

doc/faq.md

Reword the statement about profiler.sampling.rate in faq.md. 
Pinpoint release binary has changed the `profiler.sampling.rate` to 1, but it is still 20 in the document, it might be better to change the doc to a more general statement.

[#6084] reword the statement about profiler.sampling.rate in faq.md

---

collector/src/main/java/com/navercorp/pinpoint/collector/monitor/LoggingRejectedExecutionHandler.java
collector/src/test/java/com/navercorp/pinpoint/collector/monitor/LoggingRejectedExecutionHandlerTest.java

AS-IS
~~~
RejectedExecutionCount=1000
~~~
TO-BE
~~~
The executor uses finite bounds for both maximum threads and work queue capacity, and is saturated. Check the maxPoolSize, queueCapacity, and HBase options in the configuration. maxPoolSize=10, rejectedCount=70
~~~

[#noissue] Improve rejected execution messages of ThreadPoolExecutor

---

agent-it/src/test/java/com/navercorp/pinpoint/plugin/log4j2/Log4j2ForAsyncLoggerIT.java
agent-it8/src/test/java/com/navercorp/pinpoint/plugin/log4j2/Log4j2ForAsyncLoggerIT.java
agent-it8/src/test/java/com/navercorp/pinpoint/plugin/log4j2/Log4j2IT.java
agent-it8/src/test/resources/pinpoint-spring-bean-test.config

Log4j 2.13.0 is the latest release of Log4j. As of Log4j 2.13.0 Log4j 2 requires Java 8 or greater at runtime.

[#noissue] Patch log4j2 testcase

---

plugins/dubbo/src/main/java/com/navercorp/pinpoint/plugin/dubbo/interceptor/DubboProviderInterceptor.java

clear {@link com.alibaba.dubbo.rpc.RpcContext#getAttachments()} trace header.
you should to know,since dubbo 2.6.2 version.
{@link com.alibaba.dubbo.rpc.protocol.AbstractInvoker#invoke(com.alibaba.dubbo.rpc.Invocation)}
will force put {@link com.alibaba.dubbo.rpc.RpcContext#getAttachments()} to current Invocation
replace origin invocation.addAttachmentsIfAbsent(context) method;
to imagine if application(B) methodB called by application(A), application(B) is dubbo provider, methodB call next dubbo application(C).
when application(C) received trace header is overwrite by application(B) received trace header.

fix spanId duplicate in dubbo plugin. since dubbo 2.6.2 it will force will force put RpcContext.attachment to dubbo consumer RpcInvocation

---

flink/src/main/resources/applicationContext-flink.xml

After removing `serverAcceptor`, no thread leak happen.

[#6413] Remove useless `serverAcceptor` in flink job to prevent thread from leaking

---

bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/registry/DefaultInterceptorRegistryAdaptor.java

Fix a log message that occurs when the maximum size of the Interceptor Registry is reached.
~~~
Interceptor registry size exceeded. Check the "profiler.interceptorregistry.size" setting. size=8192 id=8731 
~~~

[#noissue] Fix log message of interceptor-registry

---

agent/src/main/resources/profiles/local/pinpoint-env.config
agent/src/main/resources/profiles/release/pinpoint-env.config
plugins/informix-jdbc/pom.xml
plugins/informix-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/informix/InformixPlugin.java
plugins/informix-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/informix/interceptor/InformixPreparedStatementCreateInterceptor.java
plugins/informix-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/informix/interceptor/InformixStatementCreateInterceptor.java
plugins/informix-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/informix/interceptor/getter/InformixConnectionInfoGetter.java
plugins/informix-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/informix/interceptor/getter/InformixDatabaseNameGetter.java
plugins/informix-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/informix/interceptor/getter/Informix_4_50_ConnectionInfoGetter.java

This is a patch for the [critical issue](https://github.com/naver/pinpoint/pull/6634#issuecomment-611832466) found. 
I've renamed the getters to be more like the others:
DatabaseNameGetter -> InformixDatabaseNameGetter
ConnectionInfoGetter -> InformixConnectionInfoGetter
And created a new getter for the driver 4.50.x:
Informix_4_50_ConnectionInfoGetter
I've patched the interceptors to choose the correct ConnectionInfoGetter and also patched InformixPlugin to create the right getter based on the type of the property. Now the plugin has a dependency on the driver.

[#6634] Added support for driver version 4.50

---

bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/resolver/condition/MainClassConditionTest.java
bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/config/ProfilePropertyLoader.java
bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/config/SimplePropertyLoader.java
bootstrap/src/test/java/com/navercorp/pinpoint/bootstrap/config/ProfilePropertyLoaderTest.java
commons/src/main/java/com/navercorp/pinpoint/common/util/PropertySnapshot.java
commons/src/main/java/com/navercorp/pinpoint/common/util/SimpleProperty.java
commons/src/main/java/com/navercorp/pinpoint/common/util/SystemProperty.java

System property take higher priority than the config file for the specified profile.
From the source code https://github.com/naver/pinpoint/blob/c5e6b7e33343ad8122823600f5977ba8927b6fe6/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/config/ProfilePropertyLoader.java#L76, i see the comment  and the feature not implemented. Should i consider something additional for that?

[#6760] add system property config support

---

web/src/main/angular/src/app/core/components/filter-transaction-wizard-popup/filter-transaction-wizard-popup.component.ts
web/src/main/angular/src/app/core/models/filter.ts

If filtering transactions via "Filter Transaction Wizard" and select "Failed-only" will get failed transaction, and "success-only" will get successful transactions.
From the java source: https://github.com/naver/pinpoint/blob/fce1f86acc6d406ea82174a72a018611aac5d031/web/src/main/java/com/navercorp/pinpoint/web/filter/FilterDescriptor.java#L146-L153
https://github.com/naver/pinpoint/blob/ce0c257122a621f64d578b6258627c7d75c91333/web/src/main/java/com/navercorp/pinpoint/web/filter/LinkFilter.java#L146-L155
So the truth value of the filter.ie means failed-only transactions, false means success-only transactions, and null means all.
From the angular source code:
The filter.ie is from https://github.com/naver/pinpoint/blob/14761a77eac08a3563db6c3f8296ff2bd14d3d4b/web/src/main/angular/src/app/cor …

fix Filter Transaction Wizard transaction result filter

---

agent/src/main/resources/pinpoint.config
agent/src/main/resources/profiles/local/pinpoint-env.config
agent/src/main/resources/profiles/release/pinpoint-env.config
plugins-it/thread-it/src/test/java/com/navercorp/test/pinpoint/plugin/thread/ThreadIT.java
plugins-it/thread-it/src/test/java/com/navercorp/test/pinpoint/plugin/thread/Thread_multiple_base_packages_IT.java
plugins-it/thread-it/src/test/java/com/navercorp/test/pinpoint/plugin/thread/pkg/one/MockCallable.java
plugins-it/thread-it/src/test/java/com/navercorp/test/pinpoint/plugin/thread/pkg/one/MockRunnable.java
plugins-it/thread-it/src/test/java/com/navercorp/test/pinpoint/plugin/thread/pkg/two/MockRunnable.java
plugins-it/thread-it/src/test/resources/pinpoint-thread-test-multiple-pkg.config
plugins/thread/src/main/java/com/navercorp/pinpoint/plugin/thread/ThreadPlugin.java

- Feature
The config profiler.thread.match.package can now be configured with multiple package names, instead of one package name which includes all subpackages.
- Why do we need this feature?
Current profiler.thread.match.package config entity only support one package. If we want to trace com.example.bizA.async and com.example.bizB.async, the config value can only be com.example(which may matches too many packages, com.example.bizC would be included).

Thread plugin support tracing multiple packages.

---

web/src/main/angular/src/app/core/components/filter-transaction-wizard-popup/filter-transaction-wizard-popup.component.html
web/src/main/angular/src/app/core/components/filter-transaction-wizard-popup/filter-transaction-wizard-popup.component.ts
web/src/main/angular/src/app/core/components/server-map/server-map-for-filtered-map-container.component.html
web/src/main/angular/src/app/core/components/server-map/server-map-for-filtered-map-container.component.ts
web/src/main/angular/src/app/core/models/filter.ts

- Parse it as `max` when it sets as the max range
- Correct the comparing filter logic
- Add the missing callback on context clicking on node in filter page

[#6798] Parse max range of response time on filtering

---

doc/proxy-http-header.md

The 10 digit example did not work, and after research found that an epoch in milliseconds is 13 digits, updated the documentation to reflect a 13 digit example

Clarify milliseconds is a 13 digit number

---

profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/grpc/GrpcCommandService.java

I changed to reuse GrpcCommandDispatcher via #6952 issue.
But whenever Grpc's stream is disconnected, I leaved the logic to close GrpcCommandDispatcher.
So the problem occurred after the stream was terminated.
For solving this issue, I am going to change to close GrpcCommandDispatcher only when the agent shutdown.

[#6952] Fixed GrpcCommandDispatcher closing in wrong situation

---

plugins/mysql-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/mysql/MySqlPlugin.java

Added com.mysql.jbdc.ServerPreparedStatement to addPreparedStatementTransformer.
Screenshot shows bind value correctly shown with mysql-connector-java:5.1.36 and useServerPrepStmts=true

[#7012] Add com.mysql.jbdc.ServerPreparedStatement to addPreparedStatementTransformer

---

web/src/main/java/com/navercorp/pinpoint/web/calltree/span/LinkMap.java

Change the nodes to include as duplicates
((bug)currentNode -> existNode)

[#7067] Fix incorrectly selecting node when acquiring CallStack

---

plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/CorePublisherInterceptor.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/SubscribeOrReturnMethodInterceptor.java
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/interceptor/CorePublisherInterceptor.java
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/interceptor/SchedulerAndWorkerScheduleMethodInterceptor.java
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/interceptor/SchedulerAndWorkerTaskRunMethodInterceptor.java
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/interceptor/SubscribeOrReturnMethodInterceptor.java

Fixed a problem where UnsupportedOperationException occurred when outputting a reactor object to the debug log.
~~~
WARN  c.n.p.p.r.i.CorePublisherInterceptor    :228 -- BEFORE. Caused:Although QueueSubscription extends Queue it is purely internal and only guarantees support for poll/clear/size/isEmpty. Instances shouldn't be used/exposed as Queue outside of Reactor operators.
java.lang.UnsupportedOperationException: Although QueueSubscription extends Queue it is purely internal and only guarantees support for poll/clear/size/isEmpty. Instances shouldn't be used/exposed as Queue outside of Reactor operators.
at reactor.core.Fuseable$QueueSubscription.iterator(Fuseable.java:145) ~[reactor-core-3.3.4.RELEASE.jar:3.3.4.RELEASE]
at pinpoint.agent/pinpoint.agent/org.apache.logging.log4j.message …

[#7057] Fix log message of reactor plugin

---

agent/pom.xml

Add log4j2 related libraries to pinpoint-aget-2.1.0-SNAPSHOT.tar.gz.

[#noissue] Fix log4j lib of agent

---

web/src/main/java/com/navercorp/pinpoint/web/alarm/vo/Rule.java
web/src/main/java/com/navercorp/pinpoint/web/dao/memory/MemoryAlarmDao.java

I fix method name in Rule Class
(setuserGroupId -> setUserGroupId)
I think setUserGroupId is more proper than setuserGroupId by the camel case

[#noissue] Fix Typo in Rule

---

collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseAgentEventDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseAgentInfoDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseAgentLifeCycleDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseApplicationTraceIndexDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseHostApplicationMapDao.java
collector/src/test/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseHostApplicationMapDaoTest.java
commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseTableConstants.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/stat/AgentStatRowKeyDecoder.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/stat/AgentStatRowKeyEncoder.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/stat/ApplicationStatRowKeyDecoder.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/stat/ApplicationStatRowKeyEncoder.java
flink/src/main/java/com/navercorp/pinpoint/flink/process/ApplicationCache.java
web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseAgentEventDao.java
web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseAgentInfoDao.java
web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseAgentLifeCycleDao.java
web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseHostApplicationMapDao.java
web/src/main/java/com/navercorp/pinpoint/web/mapper/AgentInfoMapper.java
web/src/main/java/com/navercorp/pinpoint/web/mapper/HostApplicationMapper.java
web/src/main/java/com/navercorp/pinpoint/web/mapper/TraceIndexScatterMapper.java

fix typo : HbaseTableConstatns to HbaseTableConstants and HbaseTableConstatns.java to HbaseTableConstants.java

[#noissue] fix typo : HbaseTableConstatns to HbaseTableConstants

---

plugins/informix-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/informix/interceptor/InformixPreparedStatementCreateInterceptor.java

InformixPreparedStatementCreateInterceptor now tries to access databaseInfo from the previously recorded info, and creating new info when this info is not available. Before the patch, It always tried to create the info from the class, but sometimes the URL was not available, leaving a connection to null:null.

Fix DB URL null:null

---

web/src/main/java/com/navercorp/pinpoint/web/alarm/SpringSmtpMailSender.java
web/src/main/java/com/navercorp/pinpoint/web/alarm/checker/AlarmChecker.java

I fix method name in AlarmChecker class
(getuserGroupId -> getUserGroupId)
I think getUserGroupId is more proper than getUserGroupId by the camel case

[#noissue] fix typo in AlarmChecker

---

profiler-logging/src/main/java/com/navercorp/pinpoint/profiler/logging/EmptyShutdownCallbackRegistry.java
profiler-logging/src/main/java/com/navercorp/pinpoint/profiler/logging/Log4j2ContextFactory.java

- When the application is terminated, unnecessary shutdown processes are executed

[#6826] Remove ShutdownCallbackRegistry

---

web/src/main/java/com/navercorp/pinpoint/web/alarm/AlarmMailTemplate.java
web/src/main/java/com/navercorp/pinpoint/web/alarm/checker/AgentChecker.java
web/src/main/java/com/navercorp/pinpoint/web/alarm/checker/DataSourceConnectionUsageRateChecker.java
web/src/main/java/com/navercorp/pinpoint/web/alarm/checker/DeadlockChecker.java

I added the Scatter Chart Link and Inspector Link to Alarm Mail. Inspector Link is created only when an agent-related alarm occurs.
When Link is clicked, shows the Inspector of the Agent or the Scatter Chart of the Application at the time the alarm occurred.
To use this feature, you must set `pinpoint.url` in the `batch-root.properties` file .
ex) pinpoint.url=http://localhost:8080

[#noissue] Add Scatter Chart Link and Inspector Link to alarm mail

---

web/src/main/java/com/navercorp/pinpoint/web/batch/job/AgentCountReader.java
web/src/main/java/com/navercorp/pinpoint/web/controller/AgentInfoController.java
web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseAgentLifeCycleDao.java
web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoService.java
web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoServiceImpl.java
web/src/main/java/com/navercorp/pinpoint/web/vo/AgentInfoFilter.java
web/src/main/java/com/navercorp/pinpoint/web/vo/AgentInfoFilterChain.java
web/src/main/java/com/navercorp/pinpoint/web/vo/AgentStatus.java
web/src/main/java/com/navercorp/pinpoint/web/vo/ApplicationAgentsList.java
web/src/main/java/com/navercorp/pinpoint/web/vo/DefaultAgentInfoFilter.java
web/src/test/java/com/navercorp/pinpoint/web/applicationmap/ApplicationMapBuilderTest.java
web/src/test/java/com/navercorp/pinpoint/web/vo/AgentInfoFilterChainTest.java
web/src/test/java/com/navercorp/pinpoint/web/vo/ApplicationAgentsListTest.java
web/src/test/java/com/navercorp/pinpoint/web/vo/timeline/inspector/AgentStatusTimelineBuilderTest.java
web/src/test/java/com/navercorp/pinpoint/web/vo/timeline/inspector/AgentStatusTimelineTest.java

The from query parameter is not used to filter agent.
And the default getAgentList API for the agent statistics should use the from/to version for better performance. The current one will return too much data, in our case, 800MB data returned from /getAgentList.pinpoint and unable to be displayed.

Reduce memory usage of getAgentList

---

web/src/test/java/com/navercorp/pinpoint/web/service/AdminServiceImplTest.java

case 1: Constructor requires Non Null.
case 2: Test Remove agent id.
case 3: Test remove application name
case 4: When min duration days for inactivity is less than duration days, Throw IllegalArgumentException.
case 5: When agent stat exists within duration days do not remove the agents.
case 6: When agent stat exists out of duration days, Remove inactive agents.
case 7: When application doesn't have any agent id, getAgentIdMap() returns empty map.
case 8: Test duplicate agent ids map.

[#noissue] Add AdminServiceImpl Test

---

agent/src/main/resources/profiles/release/log4j2.xml

I found out that the version of log2j is 2.3 (log4j-api-2.3 and log4j-core-2.3) from the released agent of version 2.1.0.
> jar tvf log4j-core-2.3.jar|grep SizeBasedTriggeringPolicy
> 4443 Sun May 10 14:13:02 CST 2015 org/apache/logging/log4j/core/appender/rolling/SizeBasedTriggeringPolicy.class

agent, use SizeBasedTriggeringPolicy for logging

---

web/src/main/angular/src/app/core/components/call-tree/call-tree.component.ts
web/src/main/angular/src/app/core/components/transaction-search/transaction-search.component.html

- Added **_exception_** option to search button on call tree component. 
- It is only searched if the node has exceptions.
- before option : Self, Argument, All / after option : Self, Argument, Exception, All
Thank you!

[#7268] Add exception option to call stack search

---

plugins-it/kafka-it/pom.xml
plugins-it/kafka-it/src/test/java/com/navercorp/pinpoint/plugin/kafka/KafkaClientITBase.java
plugins-it/kafka-it/src/test/java/com/navercorp/pinpoint/plugin/kafka/KafkaClient_0_11_x_IT.java
plugins-it/kafka-it/src/test/java/com/navercorp/pinpoint/plugin/kafka/KafkaClient_1_0_x_IT.java
plugins-it/kafka-it/src/test/java/com/navercorp/pinpoint/plugin/kafka/KafkaClient_1_1_x_IT.java
plugins-it/kafka-it/src/test/java/com/navercorp/pinpoint/plugin/kafka/KafkaClient_2_0_x_IT.java
plugins-it/kafka-it/src/test/java/com/navercorp/pinpoint/plugin/kafka/KafkaClient_2_2_x_IT.java
plugins-it/kafka-it/src/test/java/com/navercorp/pinpoint/plugin/kafka/KafkaClient_2_3_0_IT.java
plugins-it/kafka-it/src/test/java/com/navercorp/pinpoint/plugin/kafka/KafkaClient_2_3_1_to_max_IT.java
plugins-it/kafka-it/src/test/java/com/navercorp/pinpoint/plugin/kafka/KafkaClient_2_4_x_IT.java
plugins-it/kafka-it/src/test/java/com/navercorp/pinpoint/plugin/kafka/KafkaClient_2_5_x_IT.java
plugins-it/kafka-it/src/test/java/com/navercorp/pinpoint/plugin/kafka/KafkaClient_2_6_x_IT.java
plugins-it/kafka-it/src/test/java/test/pinpoint/plugin/kafka/KafkaITConstants.java
plugins-it/kafka-it/src/test/java/test/pinpoint/plugin/kafka/KafkaUnitServer.java
plugins-it/kafka-it/src/test/java/test/pinpoint/plugin/kafka/OffsetStore.java
plugins-it/kafka-it/src/test/java/test/pinpoint/plugin/kafka/TestConsumer.java
plugins-it/kafka-it/src/test/java/test/pinpoint/plugin/kafka/TestConsumerRecordEntryPoint.java
plugins-it/kafka-it/src/test/java/test/pinpoint/plugin/kafka/TestProducer.java
plugins-it/kafka-it/src/test/java/test/pinpoint/plugin/kafka/ZookeeperUnitServer.java
plugins-it/kafka-it/src/test/resources/pinpoint-kafka-client.config
plugins-it/pom.xml

issue : #7362 
This PR is kafka client plugin IT module.
KafkaUnitServer.java and ZookeeperUnitServer.java are the copy of https://github.com/chbatey/kafka-unit.
These enables Kafka broker, ZooKeeper to run in unit test.
KafkaUnitServer.java and ZookeeperUnitServer.java have been modified to suit the test environment.

[#7362] Add kafka client plugin IT

---

agent/src/main/resources/pinpoint-root.config
collector/src/test/java/com/navercorp/pinpoint/collector/receiver/grpc/SpanClientMock.java
collector/src/test/java/com/navercorp/pinpoint/collector/receiver/grpc/SpanClientTestMain.java
collector/src/test/java/com/navercorp/pinpoint/collector/receiver/grpc/SpanServerTestMain.java
grpc/src/main/java/com/navercorp/pinpoint/grpc/client/interceptor/DiscardClientCall.java
grpc/src/main/java/com/navercorp/pinpoint/grpc/client/interceptor/DiscardClientInterceptor.java
grpc/src/main/java/com/navercorp/pinpoint/grpc/client/interceptor/DiscardLimiter.java
grpc/src/test/java/com/navercorp/pinpoint/grpc/client/interceptor/DiscardClientInterceptorTest.java
grpc/src/test/java/com/navercorp/pinpoint/grpc/client/interceptor/DiscardLimiterTest.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/grpc/GrpcTransportConfig.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/grpc/SpanGrpcDataSenderProvider.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/ResponseStreamObserver.java

#7375
* Reconnect when the number of discards exceeds the config.
* Reconnect when "not ready" state times out.
~~~
profiler.transport.grpc.span.sender.discardpolicy.discard-count-for-reconnect=1000
profiler.transport.grpc.span.sender.discardpolicy.not-ready-timeout-millis=300000
~~~

[#7375] Add DiscardLimiter

---

grpc/src/main/java/com/navercorp/pinpoint/grpc/server/StreamExecutorRejectedExecutionRequestScheduler.java
grpc/src/main/java/com/navercorp/pinpoint/grpc/server/StreamExecutorServerInterceptor.java

#7375 
Call.request(1) is immediately executed for the RejectedExecution request.
pinpoint-collector-grpc.properties
~~~
collector.receiver.grpc.stat.stream.scheduler.recovery.message.count=-1
~~~

[#7375] Add request immediately of collector

---

agent-testweb/reactor-netty-plugin-testweb/src/main/java/com/pinpoint/test/plugin/ReactorNettyPluginTestController.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/ReactorNettyPlugin.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/HttpClientHandlerConstructorInterceptor.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/HttpClientHandlerRequestWithBodyInterceptor.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/HttpClientOperationsSendInterceptor.java

#7463 
Avoid code that resets HTTP header values.
https://github.com/reactor/reactor-netty/blob/master/reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConnect.java#L494

[#7463] Fix Reactor-Netty HTTP client plugin

---

agent/src/main/resources/profiles/local/pinpoint.config
agent/src/main/resources/profiles/release/pinpoint.config
plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/KafkaConfig.java
plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/interceptor/ProducerAddHeaderInterceptor.java
plugins/kafka/src/test/java/com/navercorp/pinpoint/plugin/kafka/interceptor/ProducerAddHeaderInterceptorTest.java

If your kafka broker version is 0.11+ but the log.message.format.version is overridden by a lower version than 0.11 (e.g. 0.10) which can not be automatically detected.
> kafaka-2.4.1 $ ./bin/kafka-server-start.sh config/server.properties --override log.message.format.version=0.10.2
The Kafka Pinpoint headers will cause the messages delivered to the broker(s) can not be saved and get error:
> [2021-01-19 13:47:36,188] ERROR [ReplicaManager broker=0] Error processing append operation on partition pinpoint-kafka-plugin-check-dev-0 (kafka.server.ReplicaManager)
> java.lang.IllegalArgumentException: Magic v1 does not support record headers
>         at org.apache.kafka.common.record.MemoryRecordsBuilder.appendWithOffset(MemoryRecordsBuilder.java:410)
>         at …

add configuration to disable kafka header

---

commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseTemplate2.java

Collector is doing checkAndPut twice in maxColumnValue.
The first is just in case it doesn't exist.
For above reason, if first operation is success, then second operation do not need.
In the second operation, if the values are the same, it will be changed the operation do not perform.

[#7559] Removes possibility of duplicate puts.

---

rpc/src/main/java/com/navercorp/pinpoint/rpc/server/PinpointServerAcceptor.java

The log is recorded when an event occurs, so even if you set it in `collector.l4.ip', the log is being recorded and its location will be changed.

[#noissue] Change the log location of channelConnected method

---

plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/HttpClientRequestHeaderAdaptor.java

fix #7748 
https://projectreactor.io/docs/netty/release/api/reactor/netty/http/client/HttpClientRequest.html
> addHeader(java.lang.CharSequence name, java.lang.CharSequence value)
>     Add an outbound http header, appending the value if the header is already set.
> header(java.lang.CharSequence name, java.lang.CharSequence value)
>     Set an outbound header, replacing any pre-existing value.

fix pinpoint headers added multiple times in Netty HttpClient

---

web/src/main/angular/src/app/core/components/agent-statistic-list/agent-statistic-list-container.component.ts
web/src/main/angular/src/app/core/components/agent-statistic-list/agent-statistic-list.component.ts
web/src/main/angular/src/app/shared/services/analytics.service.ts

Changes:
1. always show application name in children rows and link to /main/{app_name}@{service_type}
before:
after:
2. the other cells except application cells link to /inspector/ {app_name}@{service_type} /5m/ {start_time + 5m} / {agent_id}

[#7803] Add agent statistics table cell link

---

web/src/main/angular/src/app/core/components/agent-statistic-list/agent-statistic-list-container.component.ts
web/src/main/angular/src/app/core/components/agent-statistic-list/agent-statistic-list.component.ts
web/src/main/angular/src/app/core/components/removable-agent-list/removable-agent-list-container.component.ts
web/src/main/angular/src/app/core/components/removable-agent-list/removable-agent-list.component.ts
web/src/main/angular/src/globals.d.ts

For #7788 and related to #7787 
The updated UI pages are:
1. agent management page:
2. agent statistics page:

[#7788] show agent name in agent statistics & management administration pages

---

plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/HttpClient4Plugin.java
plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/BasicFutureFailedMethodInterceptor.java

`org.apache.http.concurrent.BasicFuture#failed` doesn't throw exception but contains exception as its method argument.

#7527 fix exception info lost when intercepting method `org.apache.http.concurrent.BasicFuture#failed`

---

bootstraps/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/PinpointBootStrap.java

To disable the pinpoint agent, even the agent is set via javaagent.
When the javaagent jvm parameter is set as global to all applications/pods, especially for k8s environments, or set by JAVA_OPTS. Some jvm applications may need to disable the agent for now/ever/emergency.
env PINPOINT_DISABLE=true java -jar /path/to/jar
java -Dpinpoint.disable=true -jar /path/to/jar

[#7868] disable environment/property support

---

test/src/main/java/com/navercorp/pinpoint/test/plugin/AbstractPinpointPluginTestSuite.java
test/src/main/java/com/navercorp/pinpoint/test/plugin/DependencyResolver.java
test/src/main/java/com/navercorp/pinpoint/test/plugin/PluginTestContext.java
test/src/main/java/com/navercorp/pinpoint/test/plugin/shared/ReflectionDependencyResolver.java
test/src/main/java/com/navercorp/pinpoint/test/plugin/shared/SharedPinpointPluginTest.java
test/src/main/java/com/navercorp/pinpoint/test/plugin/shared/SharedPluginTestConstants.java
test/src/main/java/com/navercorp/pinpoint/test/plugin/shared/SharedProcessManager.java
test/src/main/java/com/navercorp/pinpoint/test/plugin/shared/TestInfo.java
test/src/test/java/com/navercorp/pinpoint/test/plugin/shared/ReflectionDependencyResolverTest.java

- Uses dummy repository id in DependencyResolver for maven-resolver plugin to properly scan for required artifacts
- Passes repository urls specified by @Repository in plugin integration tests to SharedPinpointPluginTest

[#7907] Fixes plugin integration tests failing to recognize local maven repositories

---

plugins/bom/pom.xml
plugins/redis/src/main/java/com/navercorp/pinpoint/plugin/redis/jedis/interceptor/SetEndPointInterceptor.java

#7895 
The JedisSocketFactory class is supported from jedis version 3.6, and java 1.8 is required.

[#7895] Fix jedis plugin for java compatibility

---

bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/DefaultProfilerConfig.java

`@Value` annotation is not worked at getter methods.
fix to setter method.
* profiler.http.status.code.errors
* profiler.plugin.disable
fix #6783

[#6783] Fix some agent config properties is not works

---

bootstraps/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/BootLogLevel.java
bootstraps/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/BootLogger.java
bootstraps/bootstrap/src/test/java/com/navercorp/pinpoint/bootstrap/BootLogLevelTest.java

Resolve #8171.
Agent boot logger level can be configured  by
>  -Dpinpoint.agent.bootlogger.loglevel=debug
Supported boot logger levels(case-insensitive) are:
- trace
- debug
- info
- warn
- error

[#8171] agent boot logger level can be configured

---

web/src/main/angular/src/app/core/components/application-list/application-list-data.service.ts
web/src/main/angular/src/app/shared/store/effects/application-list.effect.ts
web/src/main/java/com/navercorp/pinpoint/web/controller/MainController.java
web/src/main/java/com/navercorp/pinpoint/web/service/CacheService.java
web/src/main/java/com/navercorp/pinpoint/web/service/CacheServiceImpl.java
web/src/main/java/com/navercorp/pinpoint/web/service/CommonServiceImpl.java
web/src/main/java/com/navercorp/pinpoint/web/util/etag/ETag.java
web/src/main/java/com/navercorp/pinpoint/web/util/etag/ETagUtils.java
web/src/main/java/com/navercorp/pinpoint/web/view/TagApplications.java
web/src/main/resources/ehcache.xml
web/src/main/resources/pinpoint-web-root.properties
web/src/main/resources/servlet-context-web.xml
web/src/test/http/.gitignore
web/src/test/http/applicationCache.http
web/src/test/http/http-client.env.json
web/src/test/java/com/navercorp/pinpoint/web/util/etag/ETagUtilsTest.java

Resolve #8162 
By default, the application list would be cached by Ehcache for 120 seconds(configured in ehcache.xml) and be cached by browser  for 60 seconds (configured by web.applicationList.cacheTime in pinpoint-web-root.properties). If the request having no "If-Non-Match" header(when it's the first time to request or after expired browser cache time), ehcache would be evicted and retrieve data from hbase. The cache can also be clear by requesting {web_host}/applications.pinpoint?clearCache manually.
**The first time to request for a user, there would be no cache in use.**
You may let the web browser cache for a longer time by setting `-Dweb.applicationList.cacheTime` to a bigger value (in seconds). The following request would get "304 Not Modified response header" and no response …

[#8162] cache applications api on browser/server side

---

plugins-it/log4j2-it/src/test/java/com/navercorp/pinpoint/plugin/log4j2/Log4j2ForAsyncLoggerIT.java
plugins-it/log4j2-it/src/test/java/com/navercorp/pinpoint/plugin/log4j2/Log4j2IT.java
plugins-it/log4j2-it/src/test/java/com/navercorp/pinpoint/plugin/log4j2/Log4j2TestBase.java
plugins-it/log4j2-jdk8-it/src/test/java/com/navercorp/pinpoint/plugin/log4j2/Log4j2ForAsyncLoggerIT.java
plugins-it/log4j2-jdk8-it/src/test/java/com/navercorp/pinpoint/plugin/log4j2/Log4j2IT.java
plugins-it/log4j2-jdk8-it/src/test/java/com/navercorp/pinpoint/plugin/log4j2/Log4j2TestBase.java
testcase/src/main/resources/log4j2-test.xml

Resolve #8246.
This PR also fix another error caused by log4j2-test.xml config.
>   Caused by: java.lang.IllegalArgumentException: No enum constant
>    org.apache.logging.log4j.core.appender.ConsoleAppender.Target.system_out
>        at java.lang.Enum.valueOf(Enum.java:238)
>        at org.apache.logging.log4j.core.appender.ConsoleAppender$Target.valueOf(ConsoleAppender.java:57)

[#8246] fix log4j2 plugin-it

---

agent/src/main/resources/profiles/local/pinpoint.config
plugins-it/jdk-http-it/src/test/java/com/navercorp/pinpoint/plugin/jdk/http/HttpURLConnectionIT.java

Related issue #8159 #7962. A continuation to PR #8161.
Update com.navercorp.pinpoint.plugin.jdk.http.HttpURLConnectionIT#testConnectTwice test.

[#8159] fix failed jdk-plugin-it

---

agent/src/main/resources/profiles/release/pinpoint.config
plugins-it/log4j-it/src/test/java/com/navercorp/pinpoint/plugin/log4j/Log4jIT.java
plugins-it/log4j-it/src/test/resources/log4j.properties
plugins-it/log4j-it/src/test/resources/pinpoint-spring-bean-test.config
plugins-it/log4j2-it/src/test/java/com/navercorp/pinpoint/plugin/log4j2/Log4j2ForAsyncLoggerIT.java
plugins-it/log4j2-it/src/test/java/com/navercorp/pinpoint/plugin/log4j2/Log4j2IT.java
plugins-it/log4j2-it/src/test/java/com/navercorp/pinpoint/plugin/log4j2/Log4j2PatternIT.java
plugins-it/log4j2-it/src/test/java/com/navercorp/pinpoint/plugin/log4j2/Log4j2TestBase.java
plugins-it/log4j2-it/src/test/resources/pinpoint-spring-bean-test.config
plugins-it/log4j2-jdk8-it/src/test/java/com/navercorp/pinpoint/plugin/log4j2/Log4j2ForAsyncLoggerIT.java
plugins-it/log4j2-jdk8-it/src/test/java/com/navercorp/pinpoint/plugin/log4j2/Log4j2IT.java
plugins-it/log4j2-jdk8-it/src/test/java/com/navercorp/pinpoint/plugin/log4j2/Log4j2PatternIT.java
plugins-it/log4j2-jdk8-it/src/test/java/com/navercorp/pinpoint/plugin/log4j2/Log4j2TestBase.java
plugins-it/log4j2-jdk8-it/src/test/resources/pinpoint-spring-bean-test.config
plugins-it/logback-it/src/test/java/com/navercorp/pinpoint/plugin/logback/LogbackIT.java
plugins-it/logback-it/src/test/resources/logback.xml
plugins-it/logback-it/src/test/resources/pinpoint-spring-bean-test.config
plugins-it/plugins-it-utils/src/main/java/com/navercorp/pinpoint/pluginit/utils/StdoutRecorder.java
plugins/log4j/src/main/java/com/navercorp/pinpoint/plugin/log4j/Log4jConfig.java
plugins/log4j/src/main/java/com/navercorp/pinpoint/plugin/log4j/Log4jPlugin.java
plugins/log4j/src/main/java/com/navercorp/pinpoint/plugin/log4j/interceptor/PatternLayoutInterceptor.java
plugins/log4j2/src/main/java/com/navercorp/pinpoint/plugin/log4j2/Log4j2Config.java
plugins/log4j2/src/main/java/com/navercorp/pinpoint/plugin/log4j2/Log4j2Plugin.java
plugins/log4j2/src/main/java/com/navercorp/pinpoint/plugin/log4j2/interceptor/PatternLayoutInterceptor.java
plugins/logback/pom.xml
plugins/logback/src/main/java/com/navercorp/pinpoint/plugin/logback/LogbackConfig.java
plugins/logback/src/main/java/com/navercorp/pinpoint/plugin/logback/LogbackPlugin.java
plugins/logback/src/main/java/com/navercorp/pinpoint/plugin/logback/interceptor/PatternLayoutInterceptor.java
testcase/src/main/resources/log4j2-test.xml

Resolve #8222 and #8246.
Related to #8217.
If you are using logback as the logger, the config is:
> profiler.logback.logging.pattern.replace.enable=true
> profiler.logback.logging.pattern.replace.search=%message,%msg,%m
> profiler.logback.logging.pattern.replace.with="TxId:%X{PtxId} %msg"
and the original logger pattern is:
> %d{yyyy-MM-dd HH:mm:ss} [%p] [%t] %c -- %m%n
then the logger pattern would be updated automatically(no modification to application manually) to:
> %d{yyyy-MM-dd HH:mm:ss} [%p] [%t] %c -- TxId:%X{PtxId} %msg%n
* logback variables/aliases: https://github.com/qos-ch/logback/blob/master/logback-classic/src/main/java/ch/qos/logback/classic/PatternLayout.java#L54-L149
* log4j2 variables/aliases: https://logging.apache.org/log4j/2.x/manual/layouts.html under section …

[#8222] replace logger pattern automatically

---

web/src/main/java/com/navercorp/pinpoint/web/applicationmap/appender/server/StatisticsServerInstanceListFactory.java
web/src/main/java/com/navercorp/pinpoint/web/service/FilteredMapServiceImpl.java
web/src/main/java/com/navercorp/pinpoint/web/service/MapServiceImpl.java
web/src/main/java/com/navercorp/pinpoint/web/service/ResponseTimeHistogramServiceImpl.java

#6821 
When there is no transaction information, agentInfo information is used.

[#6821] Fix servermap instance list factory

---

agent/src/main/resources/profiles/local/pinpoint.config
agent/src/main/resources/profiles/release/pinpoint.config
plugins/kafka/README.md
plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/KafkaConfig.java
plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/interceptor/ConsumerRecordEntryPointInterceptor.java
plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/interceptor/ProducerSendInterceptor.java
plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/recorder/DefaultHeaderRecorder.java
plugins/kafka/src/test/java/com/navercorp/pinpoint/plugin/kafka/interceptor/ConsumerMultiRecordEntryPointInterceptorTest.java
plugins/kafka/src/test/java/com/navercorp/pinpoint/plugin/kafka/interceptor/ConsumerRecordEntryPointInterceptorTest.java
plugins/kafka/src/test/java/com/navercorp/pinpoint/plugin/kafka/interceptor/ProducerSendInterceptorTest.java

- Added null check to kafka header values to prevent NPE
- Added profiler.kafka.header.record property to let users to choose whether they want to collect header values to Pinpoint

[#8313] Add null check to kafka header values to prevent NPE

---

web/src/main/angular/src/app/core/components/call-tree/call-tree.component.ts

[#8374] show date of start time as a tooltip in web call tree

---

commons-server-cluster/src/main/java/com/navercorp/pinpoint/common/server/cluster/zookeeper/CuratorZookeeperConnectionManager.java

Currently zookeeper version 3.4.14 is used in Pinpoint, so explicitly setting zk34CompatibilityMode to true has no effect on Pinpoint while fixes `java.lang.NoSuchMethodError: 'void org.apache.zookeeper.server.quorum.flexible.QuorumMaj.<init>(java.util.Map)'` error (possibly due to environment configuration issue) during initiating flink jobs.

[#noissue] Explicitly set curator zk34CompatibilityMode to true

---

plugins/netty/pom.xml
plugins/resttemplate/pom.xml

ref: #8722 
```
❯ mvn dependency:tree
[INFO] Scanning for projects...
[INFO] 
[INFO] --------< com.navercorp.pinpoint:pinpoint-resttemplate-plugin >---------
[INFO] Building pinpoint-resttemplate-plugin 2.4.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:3.1.2:tree (default-cli) @ pinpoint-resttemplate-plugin ---
[INFO] com.navercorp.pinpoint:pinpoint-resttemplate-plugin:jar:2.4.0-SNAPSHOT
[INFO] +- com.navercorp.pinpoint:pinpoint-bootstrap-core:jar:2.4.0-SNAPSHOT:provided
[INFO] |  +- com.navercorp.pinpoint:pinpoint-annotations:jar:2.4.0-SNAPSHOT:provided
[INFO] |  \- com.navercorp.pinpoint:pinpoint-commons:jar:2.4.0-SNAPSHOT:provided
[INFO] +- org.springframework:spring-web:jar:4.3.30.RELEASE:provided …
```

[#8722] Fix a Spring 5.3 JDK compatibility issue

---

collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcStreamConfiguration.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/StreamExecutorServerInterceptorFactory.java
collector/src/main/resources/profiles/local/pinpoint-collector-grpc.properties
collector/src/main/resources/profiles/release/pinpoint-collector-grpc.properties
collector/src/test/java/com/navercorp/pinpoint/collector/grpc/config/GrpcSpanReceiverConfigurationTest.java
collector/src/test/java/com/navercorp/pinpoint/collector/grpc/config/GrpcStatReceiverConfigurationTest.java
collector/src/test/resources/test-pinpoint-collector.properties
commons-profiler/pom.xml
commons-profiler/src/main/java/com/navercorp/pinpoint/common/profiler/logging/ThrottledLogger.java
commons-profiler/src/test/java/com/navercorp/pinpoint/common/profiler/logging/ThrottledLoggerTest.java
commons-profiler/src/test/resources/log4j2-test.xml
grpc/src/main/java/com/navercorp/pinpoint/grpc/client/interceptor/LoggingDiscardEventListener.java
grpc/src/main/java/com/navercorp/pinpoint/grpc/server/flowcontrol/StreamExecutorServerInterceptor.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/GrpcDataSender.java

throttled logger applied to StreamExecutorServerInterceptor

[#8762] apply throttled logger

---

plugins-it/rabbitmq-it/src/test/java/com/navercorp/pinpoint/plugin/rabbitmq/spring/SpringAmqpRabbit_1_3_3_to_1_4_2_IT.java

JDK8 is supported from Spring Framework version 3.2.9.
https://github.com/spring-projects/spring-framework/issues/16341
https://stackoverflow.com/questions/22526695/java-1-8-asm-classreader-failed-to-parse-class-file-probably-due-to-a-new-java

[#noissue] Update amqp spring-rabbit for jdk8

---

agent-testweb/bom/pom.xml
agent-testweb/pom.xml
agent-testweb/redis-lettuce-plugin-testweb/pom.xml
agent-testweb/redis-lettuce-plugin-testweb/src/main/java/com/pinpoint/test/plugin/HttpClientConfig.java
agent-testweb/redis-lettuce-plugin-testweb/src/main/java/com/pinpoint/test/plugin/RedisLettucePluginTestStarter.java
agent-testweb/redis-lettuce-plugin-testweb/src/main/java/com/pinpoint/test/plugin/RedisRateLimiterConfig.java
agent-testweb/redis-lettuce-plugin-testweb/src/main/java/com/pinpoint/test/plugin/SimpleRoute.java
agent-testweb/redis-lettuce-plugin-testweb/src/main/resources/application.yml
bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/async/AsyncContextAccessorUtils.java
bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/reactor/CoreSubscriberConstructorInterceptor.java
bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/reactor/FluxAndMonoOperatorConstructorInterceptor.java
bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/reactor/FluxAndMonoOperatorSubscribeInterceptor.java
bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/reactor/FluxAndMonoSubscribeInterceptor.java
bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/reactor/ReactorContextAccessorUtils.java
plugins/bom/pom.xml
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/interceptor/ParallelFluxSubscribeInterceptor.java
plugins/redis-lettuce/src/main/java/com/navercorp/pinpoint/plugin/redis/lettuce/LettucePlugin.java
plugins/redis-lettuce/src/main/java/com/navercorp/pinpoint/plugin/redis/lettuce/interceptor/RedisSubscriberInterceptor.java
plugins/redis-lettuce/src/main/java/com/navercorp/pinpoint/plugin/redis/lettuce/interceptor/RunnableNewInstanceInterceptor.java
plugins/redis-lettuce/src/main/java/com/navercorp/pinpoint/plugin/redis/lettuce/interceptor/RunnableRunInterceptor.java

[#8930] Update lettuce reactive

---

web/src/main/java/com/navercorp/pinpoint/web/authorization/controller/AgentInfoController.java
web/src/main/java/com/navercorp/pinpoint/web/vo/AgentInfoFilter.java
web/src/test/java/com/navercorp/pinpoint/web/vo/AgentInfoFilterChainTest.java

Unify the policy for the physical server to the container.

[#8934] Change existing agent list lookup policy in inspector

---

bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/module/Providers.java
bootstraps/bootstrap-java9-internal/src/main/java/com/navercorp/pinpoint/bootstrap/java9/module/InternalModules.java
bootstraps/bootstrap-java9-internal/src/main/java/com/navercorp/pinpoint/bootstrap/java9/module/SingleModuleFinder.java
bootstraps/bootstrap-java9/src/main/java/com/navercorp/pinpoint/bootstrap/java9/module/JarFileAnalyzer.java

In OpenJ9 JDK11, All modules are forced to have `System.bootLayer` as their layer when they are defined by `java.lang.Access::defineModule` [source](https://github.com/eclipse-openj9/openj9/blob/792a28f15e36a2764131ef28154bd38f27cc7619/jcl/src/java.base/share/classes/java/lang/Access.java#L301). This difference between HotSpot and OpenJ9 is currently disrupting `java.util.ServiceLoader` finding service providers in OpenJ9.
This problem can be resolved by binding Java9ClassLoader to System.bootLayer manually, but I'm not sure this is a good idea.

[#8890] ServiceLoader does not work properly in OpenJ9

---

pom.xml

Remove jackson-databind version for security issue.

[#8990] Bump jackson from 2.12.6 to 2.13.3

---

plugins-it/thrift-it/pom.xml
plugins-it/thrift-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/client/AsyncEchoTestClient.java
plugins-it/thrift-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/client/SyncEchoTestClient014.java
plugins-it/thrift-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/client/TTransportInstanceCreator.java
plugins-it/thrift-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/server/AsyncEchoTestServer014.java
plugins-it/thrift-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/server/SyncEchoTestServer014.java
plugins-it/thrift-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/server/ThriftEchoTestServer.java
plugins-it/thrift-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/EchoTestRunner.java
plugins-it/thrift-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/ThriftVersion.java
plugins-it/thrift-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/asynchronous/ThriftHalfSyncHalfAsyncServerAsyncIT.java
plugins-it/thrift-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/asynchronous/ThriftHalfSyncHalfAsyncServerAsyncIT_014.java
plugins-it/thrift-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/asynchronous/ThriftNonblockingServerAsyncIT.java
plugins-it/thrift-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/asynchronous/ThriftNonblockingServerAsyncIT014.java
plugins-it/thrift-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/asynchronous/ThriftThreadedSelectorServerAsyncIT.java
plugins-it/thrift-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/asynchronous/ThriftThreadedSelectorServerAsyncIT014.java
plugins-it/thrift-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/synchronous/ThriftHalfSyncHalfAsyncServerIT.java
plugins-it/thrift-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/synchronous/ThriftHalfSyncHalfAsyncServerIT014.java
plugins-it/thrift-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/synchronous/ThriftNonblockingServerIT014.java
plugins-it/thrift-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/synchronous/ThriftSimpleServerIT.java
plugins-it/thrift-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/synchronous/ThriftThreadPoolServerIT.java
plugins-it/thrift-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/synchronous/ThriftThreadedSelectorServerIT.java
plugins-it/thrift-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/synchronous/ThriftThreadedSelectorServerIT014.java
plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/ThriftPlugin.java
plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/interceptor/transport/TNonblockingSocketConstructInterceptor.java

[#9030] Backport: update thrift plugin for 0.14 or later

---

web/src/main/java/com/navercorp/pinpoint/web/service/UserGroupServiceImpl.java
web/src/test/java/com/navercorp/pinpoint/web/service/UserGroupServiceImplTest.java

Adds null-checking before removing hyphen in phone number

[#noissue] Guard NPE while processing phone number

---

web/src/main/java/com/navercorp/pinpoint/web/service/AlarmServiceImpl.java

this patch is already backported for 2.3.x and master but missing in 2.4.x

[#9000] Backport: Fix incorrect funciton calls when webhook.enable=false

---

batch/src/main/java/com/navercorp/pinpoint/batch/alarm/AlarmProcessor.java
batch/src/main/java/com/navercorp/pinpoint/batch/alarm/AlarmReader.java
batch/src/main/java/com/navercorp/pinpoint/batch/alarm/AlarmWriter.java
batch/src/main/java/com/navercorp/pinpoint/batch/alarm/DataCollectorFactory.java
batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/AgentEventDataCollector.java
batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/AgentStatDataCollector.java
batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/DataSourceDataCollector.java
batch/src/main/java/com/navercorp/pinpoint/batch/alarm/collector/FileDescriptorDataCollector.java
batch/src/main/java/com/navercorp/pinpoint/batch/alarm/vo/AppAlarmChecker.java
batch/src/main/resources/applicationContext-batch-datasource-config.xml
batch/src/main/resources/job/applicationContext-alarmJob.xml
batch/src/test/java/com/navercorp/pinpoint/batch/alarm/AlarmProcessorTest.java
batch/src/test/java/com/navercorp/pinpoint/batch/alarm/AlarmReaderTest.java
batch/src/test/java/com/navercorp/pinpoint/batch/alarm/AlarmWriterIsolationTest.java
batch/src/test/java/com/navercorp/pinpoint/batch/alarm/AlarmWriterTest.java
batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/DataSourceConnectionUsageRateCheckerTest.java
batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/DeadlockCheckerTest.java
batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/HeapUsageRateCheckerTest.java
batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/JvmCpuUsageRateCheckerTest.java
batch/src/test/java/com/navercorp/pinpoint/batch/alarm/collector/FileDescriptorDataCollectorTest.java
web/src/main/java/com/navercorp/pinpoint/web/alarm/DataCollectorCategory.java
web/src/main/java/com/navercorp/pinpoint/web/dao/AlarmDao.java
web/src/main/java/com/navercorp/pinpoint/web/dao/memory/MemoryAlarmDao.java
web/src/main/java/com/navercorp/pinpoint/web/dao/mysql/MysqlAlarmDao.java
web/src/main/java/com/navercorp/pinpoint/web/service/AlarmService.java
web/src/main/java/com/navercorp/pinpoint/web/service/AlarmServiceImpl.java
web/src/main/resources/mapper/AlarmMapper.xml

* DataCollectors do not collect agents themselves, but require to caller
* AlarmProcessor collects required agents instead of DataCollector
* AlarmReader does not initialize DataCollector, and AlarmChecker, but AlarmProcess does
* Chunk of AlarmJob is changed from AlarmChecker into Application, AppAlarmChecker
* AlarmWriter retrieves AppAlarmChecker instead of AlarmChecker
* AlarmDao queries all distinct application ids which has at least one alarm rule
List of AlarmChecker, which is all related to the same application.

[#9052] Improve AlarmJob performance

---

batch/src/main/java/com/navercorp/pinpoint/batch/job/CleanupInactiveAgentsTasklet.java
batch/src/main/resources/job/applicationContext-cleanupInactiveAgentsJob.xml
web/src/main/java/com/navercorp/pinpoint/web/service/AdminService.java
web/src/main/java/com/navercorp/pinpoint/web/service/AdminServiceImpl.java
web/src/test/java/com/navercorp/pinpoint/web/service/AdminServiceImplTest.java

`CleanupInactiveAgentsJob` is enormous, and takes about 10h per execution.
* It collects dead agents by traversing all agents, and frequently delete agents when 100 dead agents are found.
* `CleanupInactiveAgentsTasklet` split chunks more granuly for preventing transaction-timeout-error

[#9078] Stable cleanup

---

batch/src/main/java/com/navercorp/pinpoint/batch/job/AgentCountProcessor.java
batch/src/main/java/com/navercorp/pinpoint/batch/job/AgentCountReader.java
batch/src/main/java/com/navercorp/pinpoint/batch/job/AgentCountWriter.java
batch/src/main/resources/job/applicationContext-agentCountJob.xml
web/src/main/java/com/navercorp/pinpoint/web/controller/AgentStatisticsController.java
web/src/main/java/com/navercorp/pinpoint/web/dao/AgentStatisticsDao.java
web/src/main/java/com/navercorp/pinpoint/web/dao/memory/MemoryAgentStatisticsDao.java
web/src/main/java/com/navercorp/pinpoint/web/dao/mysql/MysqlAgentStatisticsDao.java
web/src/main/java/com/navercorp/pinpoint/web/service/AgentStatisticsService.java
web/src/main/java/com/navercorp/pinpoint/web/service/AgentStatisticsServiceImpl.java
web/src/main/resources/mapper/AgentStaticsMapper.xml
web/src/test/java/com/navercorp/pinpoint/web/dao/memory/MemoryAgentStatisticsDaoTest.java

* AgentCountJob only counts agents, not doing others
* GET /selectLatestAgentCount is added

[#9086] Lightened agentCountJob

---

plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/interceptor/MongoClientConstructorInterceptor.java

[#9120] Backport: fix npe bug in mongo plugin

---

web/src/main/java/com/navercorp/pinpoint/web/websocket/ActiveThreadCountResponseAggregator.java
web/src/test/java/com/navercorp/pinpoint/web/websocket/ActiveThreadCountResponseAggregatorTest.java

[#9157] Prevent initializing active thread workers multiple times

---

thrift/src/main/java/com/navercorp/pinpoint/thrift/io/ProtocolFactory.java

Currently the maximum length of containers in thrift is 128, which can be too small for containing agent info

[#noissue] Increased thrift container max length

---

profiler/src/main/java/com/navercorp/pinpoint/profiler/context/grpc/GrpcSpanMessageConverter.java

[#9187] Fix span dispatch failed

---

agent/src/main/resources/profiles/local/pinpoint.config
agent/src/main/resources/profiles/release/pinpoint.config
bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/AsyncContextSpanEventEndPointInterceptor.java
bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/AsyncContextSpanEventSimpleAroundInterceptor.java
plugins/akka-http/src/main/java/com/navercorp/pinpoint/plugin/akka/http/interceptor/AsyncContextSpanEventEndPointInterceptor.java
plugins/netty/src/main/java/com/navercorp/pinpoint/plugin/netty/interceptor/http/HttpEncoderInterceptor.java
plugins/rabbitmq/src/main/java/com/navercorp/pinpoint/plugin/rabbitmq/client/interceptor/ConsumerHandleDeliveryInterceptor.java
plugins/user/src/main/java/com/navercorp/pinpoint/plugin/user/interceptor/MQExternalClientHandlerInterceptor.java
plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/interceptor/AsyncContextSpanEventEndPointInterceptor.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/AsyncChildTrace.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/CallStack.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/CallStackFactoryV1.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/CallStackFactoryV2.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/CallStackOverflowListener.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultCallStack.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultCallStackOverflowListener.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DepthCompressCallStack.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/ThrottledLogCallStackOverflowListener.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/CallStackFactoryProvider.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/config/DefaultInstrumentConfig.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/config/InstrumentConfig.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/context/CallStackFactoryV1Test.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/context/CallStackFactoryV2Test.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/context/DefaultCallStackOverflowListenerTest.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/context/DefaultTraceTest.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/context/ThrottledLogCallStackOverflowListenerTest.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/context/TraceTest.java

[#9200] Backport: Fix agent callstack overflow log

---

plugins/rabbitmq/src/main/java/com/navercorp/pinpoint/plugin/rabbitmq/client/interceptor/RabbitMQConsumerHandleCompleteInboundCommandInterceptor.java

[#9206] Backport: Fix rabbitMQ consumer handle interceptor

---

collector/src/main/java/com/navercorp/pinpoint/collector/monitor/LoggingRejectedExecutionHandler.java
collector/src/main/resources/applicationContext-collector-grpc.xml

LoggingRejectedExecutionHandler has ignored first exception it ever received, but should accept first in-comer

[#noissue] LoggingRejectedExecutionHandler logs first in-come

---

plugins-it/postgresql-jdbc-it/src/test/java/com/navercorp/pinpoint/plugin/jdbc/postgresql/PostgreSql_Post_9_4_1208_IT.java
plugins-it/postgresql-jdbc-it/src/test/resources/pinpoint-postgresql.config

Fix postgresql IT 
~~~
Cause:Interceptor registry size exceeded. Check the "profiler.interceptorregistry.size" setting. size=8192 id=8193
java.lang.IndexOutOfBoundsException: Interceptor registry size exceeded. Check the "profiler.interceptorregistry.size" setting. size=8192 id=8193
at com.navercorp.pinpoint.bootstrap.interceptor.registry.DefaultInterceptorRegistryAdaptor.addInterceptor(DefaultInterceptorRegistryAdaptor.java:42) ~[?:2.5.0-SNAPSHOT]
~~~

[#noissue] Fix postgresql it 42.50

---

plugins-it/rabbitmq-it/src/test/java/com/navercorp/pinpoint/plugin/rabbitmq/spring/SpringAmqpRabbit_2_1_x_to_2_x_IT.java

`com.navercorp.pinpoint.test.plugin.PinpointPluginTestException: java.lang.NoSuchMethodException: executeListener`
~~~
#####testStarted#####testPush[spring-rabbit-2.1.0.RELEASE:child:8](com.navercorp.pinpoint.plugin.rabbitmq.spring.SpringAmqpRabbit_2_1_x_to_2_x_IT)
10-13 12:51:18.018 [:child:8 Thread] DEBUG c.n.p.p.c.LoggingBaseTraceFactory        -- newTraceObject()
10-13 12:51:18.018 [:child:8 Thread] DEBUG c.n.p.p.c.a.DefaultActiveTraceRepository -- register ActiveTrace key:SampledActiveTrace{traceRoot=DefaultTraceRoot{traceId=DefaultTraceId{agentId='build.test.0', agentStartTime=1665633072568, transactionSequence=3, parentSpanId=-1, spanId=-357831799267100369, flags=0}, agentId='build.test.0', traceStartTime=1665633078432}}
#####testFailure#####testPush[spring-rabbit-2.1.0.RELEASE:chil …

[#noissue] Fix spring-amqp-rabbit it

---

collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/AgentService.java

[#9264] Guarded ping only when stream is ready

---

web/src/main/angular/src/app/core/components/call-tree/call-tree-container.component.ts
web/src/main/angular/src/app/core/components/call-tree/call-tree.component.css
web/src/main/angular/src/app/core/components/call-tree/call-tree.component.ts
web/src/main/angular/src/app/core/components/timeline/timeline.component.css
web/src/main/angular/src/app/core/components/transaction-search/transaction-search-container.component.css
web/src/main/angular/src/app/core/components/transaction-search/transaction-search-container.component.html
web/src/main/angular/src/app/core/components/transaction-search/transaction-search-container.component.ts
web/src/main/angular/src/app/core/components/transaction-search/transaction-search-interaction.service.ts
web/src/main/angular/src/app/core/components/transaction-search/transaction-search.component.css
web/src/main/angular/src/app/core/components/transaction-search/transaction-search.component.html
web/src/main/angular/src/app/core/components/transaction-search/transaction-search.component.ts
web/src/main/angular/src/app/core/components/transaction-table-grid/transaction-table-grid.component.css
web/src/main/angular/src/app/core/components/transaction-timeline/transaction-timeline-container.component.ts
web/src/main/angular/src/app/core/components/transaction-timeline/transaction-timeline.component.css
web/src/main/angular/src/app/core/components/transaction-timeline/transaction-timeline.component.html
web/src/main/angular/src/app/core/components/transaction-timeline/transaction-timeline.component.ts
web/src/main/angular/src/main.css

- Add buttons for users to be able to navigate to the prev/next search-results
- Jump to the first exception row when the user selects the transaction(if it exists)
- Add highlighting for search-target

[#noissue] Enhance calltree search user-experience

---

agent-testweb/kafka-plugin-testweb/pom.xml
agent-testweb/kafka-plugin-testweb/src/main/java/com/pinpoint/test/plugin/KafkaPluginController.java
agent-testweb/kafka-plugin-testweb/src/main/java/com/pinpoint/test/plugin/KafkaPluginTestConstants.java
agent-testweb/kafka-plugin-testweb/src/main/java/com/pinpoint/test/plugin/KafkaPluginTestStarter.java
agent-testweb/kafka-plugin-testweb/src/main/java/com/pinpoint/test/plugin/TestConsumer.java
agent-testweb/kafka-plugin-testweb/src/main/java/com/pinpoint/test/plugin/TestConsumerRecordEntryPoint.java
agent-testweb/kafka-plugin-testweb/src/main/java/com/pinpoint/test/plugin/TestProducer.java
agent-testweb/kafka-plugin-testweb/src/main/resources/application.yml
agent-testweb/kafka-plugin-testweb/src/test/java/com/pinpoint/test/plugin/kafka/KafkaTest.java
agent-testweb/pom.xml
plugins-it/kafka-it/kafka-3-it/pom.xml
plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/plugin/kafka/KafkaClientITBase.java
plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/plugin/kafka/KafkaClient_2_8_x_3_IT.java
plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/plugin/kafka/KafkaClient_3_0_x_3_IT.java
plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/plugin/kafka/KafkaClient_3_1_x_3_IT.java
plugins-it/kafka-it/kafka-3-it/src/test/java/com/navercorp/pinpoint/plugin/kafka/KafkaClient_3_2_x_3_IT.java
plugins-it/kafka-it/kafka-3-it/src/test/java/test/pinpoint/plugin/kafka/Kafka3UnitServer.java
plugins-it/plugins-it-utils/src/main/java/com/navercorp/pinpoint/pluginit/utils/TestcontainersOption.java

Stacktrace
~~~
com.navercorp.pinpoint.test.plugin.PinpointPluginTestException: java.lang.AssertionError: Failed to match 1th expectation: Span(serviceType: 8660, apiId: -4, exception: null, rpc: ExpectedTraceField{expectedType=EQUALS, expected='kafka://topic=kafka-it-topic?batch=1'}, endPoint: ExpectedTraceField{expectedType=ALWAYS_TRUE, expected='null'}, remoteAddr: ExpectedTraceField{expectedType=EQUALS, expected='localhost:25790'}, destinationId: ExpectedTraceField{expectedType=ALWAYS_TRUE, expected='null'}, annotations: [kafka.topic=kafka-it-topic, kafka.batch=1], localAsyncId: null)
~~~

[#noissue] Update kafka IT 3.x

---

plugins-it/netty-it/src/test/java/com/navercorp/pinpoint/plugin/netty/NettyIT.java

Stacktrace
~~~
com.navercorp.pinpoint.test.plugin.PinpointPluginTestException: java.lang.AssertionError: SpanEvent.serviceType expected:[9150] but was:[9151] expected:<SpanEvent(serviceType: 9150, apiId: 18, exception: null, rpc: ExpectedTraceField{expectedType=ALWAYS_TRUE, expected='null'}, endPoint: ExpectedTraceField{expectedType=ALWAYS_TRUE, expected='null'}, remoteAddr: ExpectedTraceField{expectedType=ALWAYS_TRUE, expected='null'}, destinationId: ExpectedTraceField{expectedType=ALWAYS_TRUE, expected='null'}, annotations: [], localAsyncId: null)> but was:<SpanEvent(serviceType: 9151, apiId: -20, exception: null, rpc: null, endPoint: null, destinationId: null, annotations: [], localAsyncId: 26, nextAsyncId: null)>
~~~

[#noissue] Fix netty IT

---

metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/service/SystemMetricDataServiceImpl.java

change metric groupName
* remove whitespace in metric groupName

[#noissue] remove whitespace in metric groupName

---

plugins-it/cassandra-it/pom.xml

There are 2 security vulnerabilities found in com.google.guava:guava 14.0.1
- [CVE-2018-10237](https://www.oscs1024.com/hd/CVE-2018-10237)
- [CVE-2020-8908](https://www.oscs1024.com/hd/CVE-2020-8908)
Upgrade com.google.guava:guava from 14.0.1 to 30.0-jre for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS

[#9322] Remove unnecessary guava dependencies

---

metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/service/SystemMetricHostInfoServiceImpl.java
metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/service/YMLSystemMetricBasicGroupManager.java

sort metric host info
sort collected metric in telegraf-metric.yml order

[#9315] Add order in collected metric info, metric host info

---

bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/instrument/matcher/LambdaExpressionMatcher.java
bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/instrument/matcher/Matchers.java
bootstraps/bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/instrument/matcher/LambdaExpressionMatcherTest.java
plugins/spring-data-r2dbc/src/main/java/com/navercorp/pinpoint/plugin/spring/r2dbc/SpringDataR2dbcPlugin.java

[#9348] Add lambda expression matcher

---

web/src/main/java/com/navercorp/pinpoint/web/authorization/controller/AgentListController.java

[#9317] Change AgentListController api url

---

agent/src/main/resources/pinpoint-root.config
grpc/src/main/java/com/navercorp/pinpoint/grpc/client/DefaultChannelFactory.java
grpc/src/main/java/com/navercorp/pinpoint/grpc/client/config/ClientOption.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/grpc/config/GrpcTransportConfig.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/GrpcModule.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/grpc/SpanGrpcDataSenderProvider.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/SpanGrpcDataSender.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/SubconnectionExpiringLoadBalancer.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/SubconnectionExpiringLoadBalancerProvider.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/sender/grpc/MockLoadBalancerHelper.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/sender/grpc/SubconnectionExpiringLoadBalancerTest.java

[#9371] Add agent load-balancer which periodically change collector server

---

plugins/spring-data-r2dbc/src/main/java/com/navercorp/pinpoint/plugin/spring/r2dbc/interceptor/h2/H2DatabaseInfoParser.java
plugins/spring-data-r2dbc/src/test/java/com/navercorp/pinpoint/plugin/spring/r2dbc/interceptor/h2/H2DatabaseInfoParserTest.java

[#noissue] Add testcase of spring data r2dbc h2 parser

---

bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/AsyncContextSpanEventEndPointInterceptor.java
bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/AsyncContextSpanEventSimpleAroundInterceptor.java
plugins/netty/src/main/java/com/navercorp/pinpoint/plugin/netty/interceptor/http/HttpEncoderInterceptor.java

While analyzing webflux application performance issues, I found that some pinpoint logs use a lot of CPU.
To reduce CPU usage, GuardLogStatement has been applied to classes that execute a lot.
Thanks.  :)

[#noissue] Apply GuardLogStatement for classes that execute a lot

---

collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcPropertiesServerOptionBuilder.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/GrpcReceiver.java
collector/src/main/resources/pinpoint-collector-grpc-root.properties
grpc/src/main/java/com/navercorp/pinpoint/grpc/server/ServerOption.java

[#9482] Await termination of grpc server

---

collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseApiMetaDataDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/handler/grpc/GrpcApiMetaDataHandler.java
collector/src/test/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseApiMetaDataDaoTest.java
collector/src/test/java/com/navercorp/pinpoint/collector/handler/grpc/GrpcApiMetaDataHandlerTest.java
collector/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/AnnotationBo.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/ApiMetaDataBo.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/SpanBo.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/SpanEventBo.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/trace/Api.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/trace/DefaultApiParser.java
commons-server/src/test/java/com/navercorp/pinpoint/common/server/trace/DefaultApiParserTest.java
web/src/main/java/com/navercorp/pinpoint/web/calltree/span/CallTreeNode.java
web/src/main/java/com/navercorp/pinpoint/web/calltree/span/SpanAlign.java
web/src/main/java/com/navercorp/pinpoint/web/calltree/span/SpanEventAlign.java
web/src/main/java/com/navercorp/pinpoint/web/mapper/ApiMetaDataMapper.java
web/src/main/java/com/navercorp/pinpoint/web/view/TransactionInfoCallStackSerializer.java
web/src/main/java/com/navercorp/pinpoint/web/view/TransactionInfoViewModel.java
web/src/main/java/com/navercorp/pinpoint/web/vo/callstacks/BaseRecord.java
web/src/main/java/com/navercorp/pinpoint/web/vo/callstacks/DefaultRecord.java
web/src/main/java/com/navercorp/pinpoint/web/vo/callstacks/Record.java
web/src/main/java/com/navercorp/pinpoint/web/vo/callstacks/RecordFactory.java
web/src/test/java/com/navercorp/pinpoint/web/mapper/ApiMetaDataMapperTest.java
web/src/test/java/com/navercorp/pinpoint/web/vo/callstacks/RecordFactoryTest.java

Add Line number and location in APIMetaDataBO
If Line number is null, value `0`
location value is nullable
ref #9380

[#9380] Supports Line number and location in Callstack

---

batch/src/main/resources/applicationContext-batch-sender.xml
batch/src/main/resources/batch-root.properties

Which module is your feature request related to?
Batch/.../applicationContext-batch-sender.xml
Is your feature request related to a problem?
Cannot use Gmail's SMTP easily cause by default, the sender does not enabled to use 'mail.smtp.ssl.enable' configuration.
Cause a lot of users in pinpoint might using gmail to send mail via pinpoint's batch, this feature will be useful to lots of develpers!
Describe the solution you'd like
Add the below property between line number 30 and 31 in 'pinpoint/batch/src/main/resources/applicationContext-batch-sender.xml'
<prop key="mail.smtp.ssl.enable>${alarm.mail.smtp.ssl.enable:false}</prop>
Update the configuration guide of pinpoint batch with 'Setting the value alarm.mail.smtp.ssl.enable if you needed'.
Describe alternatives you've considered
Nothing …

[#9424] Export the 'mail.smtp.ssl.enable' in the batch. 

---

collector/src/main/resources/applicationContext-collector-grpc.xml
collector/src/main/resources/profiles/local/pinpoint-collector-grpc.properties
collector/src/main/resources/profiles/release/pinpoint-collector-grpc.properties
metric-module/collector-starter/src/main/resources/profiles/local/pinpoint-collector-grpc.properties
metric-module/collector-starter/src/main/resources/profiles/release/pinpoint-collector-grpc.properties

ThreadPoolExecutor calls `offer`, which does not wait receiver, but reject in SynchronousQueue

[#9474] Fix server call executor configs

---

batch/src/main/java/com/navercorp/pinpoint/batch/common/BatchConfiguration.java
batch/src/main/java/com/navercorp/pinpoint/batch/flink/HealthCheckTaskletV2.java
batch/src/main/resources/batch-root.properties
batch/src/test/java/com/navercorp/pinpoint/batch/flink/HealthCheckTaskletV2Test.java

Added `batch.flink.rest.port` property.

[#9558] Configurable flink rest port

---

web/src/main/angular/src/app/core/components/alarm-rule-list/alarm-rule-list-container.component.css
web/src/main/angular/src/app/core/components/main-contents/main-contents-container.component.css
web/src/main/angular/src/app/core/components/side-navigation-bar/side-navigation-item.component.html
web/src/main/angular/src/app/core/components/webhook-list/webhook-list-container.component.css
web/src/main/angular/src/app/core/components/webhook-list/webhook-list.component.css

- fix main page layout: fix no agent massage disappears
- allow side navigation title to routing(if has path)
- fix styles of webhook list https://github.com/pinpoint-apm/pinpoint/pull/8366

[#noissue] fix wrong ui/ux

---

metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/controller/SystemMetricController.java
metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/dao/pinot/PinotSystemMetricHostInfoDao.java
metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/mybatis/typehandler/TagListTypeHandler.java
metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/mybatis/typehandler/TagTypeHandler.java
metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/service/SystemMetricDataServiceImpl.java
metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/util/TagUtils.java
metric-module/metric/src/test/java/com/navercorp/pinpoint/metric/web/utill/metric/TagUtilsTest.java

* TagParser renamed 
* change non-static method to static method
* Apply pre-compile regex pattern

[#9573] Refactor TagParser to TagUtils, Apply regex precompile

---

commons-pinot/src/main/java/com/navercorp/pinpoint/common/pinot/datasource/WrappedPinotPreparedStatement.java

This fix still doesn't handle the case in which query itself has fixed parameters which includes `?`.
To handle that case `fillStatementWithParameters` also has to check if `?` is within `'`.

[#9614] Apply temporary fix to Pinot #9614 issue

---

bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/reactor/CoreSubscriberConstructorInterceptor.java
bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/reactor/FluxAndMonoConstructorInterceptor.java
bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/reactor/FluxAndMonoOperatorConstructorInterceptor.java
bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/reactor/FluxAndMonoOperatorSubscribeInterceptor.java
bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/reactor/FluxAndMonoSubscribeInterceptor.java
bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/reactor/FluxAndMonoSubscribeOrReturnInterceptor.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/AbstractHttpServerHandleInterceptor.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/ChannelOperationsChannelMethodInterceptor.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/ChannelOperationsOnInboundCompleteMethodInterceptor.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/HttpClientHandlerConstructorInterceptor.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/HttpClientHandlerRequestWithBodyInterceptor.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/HttpTcpClientConnectInterceptor.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/SubscribeOrReturnMethodInterceptor.java
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/interceptor/FluxAndMonoPublishOnInterceptor.java
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/interceptor/ParallelFluxSubscribeInterceptor.java
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/interceptor/RunnableCoreSubscriberConstructorInterceptor.java
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/interceptor/RunnableCoreSubscriberInterceptor.java
plugins/redis-lettuce/src/main/java/com/navercorp/pinpoint/plugin/redis/lettuce/interceptor/LettuceMethodInterceptor.java
plugins/redis-lettuce/src/main/java/com/navercorp/pinpoint/plugin/redis/lettuce/interceptor/RunnableNewInstanceInterceptor.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultAsyncContext.java

[#noissue] Add debug log for reactor

---

web/src/main/angular/src/app/core/components/side-navigation-bar/side-navigation-bar-container.component.ts

[#noissue] Change side-menu order

---

profiler/src/main/java/com/navercorp/pinpoint/profiler/context/grpc/GrpcSpanMessageConverter.java

[#9669] Add log to accept event converter

---

agent-testweb/spring-webflux-plugin-testweb/pom.xml
agent-testweb/spring-webflux-plugin-testweb/src/main/java/com/pinpoint/test/plugin/SpringWebfluxPluginController.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/HttpCallContext.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/HttpCallContextAccessor.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/ReactorNettyPlugin.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/AbstractHttpServerHandleInterceptor.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/ChannelOperationsInterceptor.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/HttpIOHandlerObserverConstructorInterceptor.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/HttpIOHandlerObserverOnStateChangeInterceptor.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/HttpServerHandleHttpServerStateInterceptor.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/HttpServerHandleStateInterceptor.java

[#9702] Update reactor-netty plugin

---

test/src/main/java/com/navercorp/pinpoint/test/plugin/AbstractPinpointPluginTestSuite.java
test/src/main/java/com/navercorp/pinpoint/test/plugin/PinpointPluginTestAssumptionViolationRunner.java

skiped tests because of no java 17 installation should not create error log

[#9748] skip java 17 it-test

---

agent/src/main/resources/profiles/local/pinpoint.config
agent/src/main/resources/profiles/release/pinpoint.config
commons/src/main/java/com/navercorp/pinpoint/common/trace/ServiceType.java
plugins/assembly/pom.xml
plugins/kotlin-coroutines/src/main/java/com/navercorp/pinpoint/plugin/kotlinx/coroutines/CoroutinesPlugin.java
plugins/kotlin-coroutines/src/main/java/com/navercorp/pinpoint/plugin/kotlinx/coroutines/interceptor/CoroutinesUtilsInterceptor.java
plugins/kotlin-coroutines/src/main/java/com/navercorp/pinpoint/plugin/kotlinx/coroutines/interceptor/DispatchedContinuationInterceptor.java
plugins/kotlin-coroutines/src/main/java/com/navercorp/pinpoint/plugin/kotlinx/coroutines/interceptor/MonoCoroutineConstructorInterceptor.java
plugins/kotlin-coroutines/src/main/java/com/navercorp/pinpoint/plugin/kotlinx/coroutines/interceptor/SetContextCoroutineConstructorInterceptor.java
plugins/pom.xml
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/ReactorPlugin.java
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/interceptor/SinkConstructorInterceptor.java
plugins/spring-data-r2dbc/src/main/java/com/navercorp/pinpoint/plugin/spring/r2dbc/SpringDataR2dbcPlugin.java
plugins/spring-tx/README.md
plugins/spring-tx/pom.xml
plugins/spring-tx/src/main/java/com/navercorp/pinpoint/plugin/spring/tx/SpringTxConfig.java
plugins/spring-tx/src/main/java/com/navercorp/pinpoint/plugin/spring/tx/SpringTxConstants.java
plugins/spring-tx/src/main/java/com/navercorp/pinpoint/plugin/spring/tx/SpringTxPlugin.java
plugins/spring-tx/src/main/java/com/navercorp/pinpoint/plugin/spring/tx/interceptor/ReactiveTransactionSupportInterceptor.java
plugins/spring-tx/src/main/java/com/navercorp/pinpoint/plugin/spring/tx/interceptor/TransactionAspectSupportInterceptor.java
plugins/spring-tx/src/main/resources/META-INF/pinpoint/type-provider.yml
plugins/spring-tx/src/main/resources/META-INF/services/com.navercorp.pinpoint.bootstrap.plugin.ProfilerPlugin

[#9817] Add spring tx plugin and update kotlin coroutine

---

metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/util/Range.java

fixed：'to' here is mistakenly written as' from'
affected : getServerMapDataV2.pinpoint - range - toDateTime

#9838 Update Range.java

---

flink/src/main/java/com/navercorp/pinpoint/flink/Bootstrap.java
flink/src/main/java/com/navercorp/pinpoint/flink/cluster/FlinkServerRegister.java
flink/src/main/java/com/navercorp/pinpoint/flink/config/FlinkProperties.java
flink/src/main/resources/applicationContext-flink.xml
flink/src/test/java/com/navercorp/pinpoint/flink/config/FlinkPropertiesTest.java

Fixed flink not able to start-up because of bean name mismatching problem
**Bootstrap.java**
```java
flinkConfiguration = applicationContext.getBean("flinkConfiguration", FlinkConfiguration.class);
```
```xml
<bean id="flinkProperties" class="com.navercorp.pinpoint.flink.config.FlinkConfiguration"/>
```

[#9876] Unified naming convention

---

bootstraps/bootstrap-java9/src/main/java/com/navercorp/pinpoint/bootstrap/java9/classloader/Java9ClassLoader.java
bootstraps/bootstrap-java9/src/main/java/com/navercorp/pinpoint/bootstrap/java9/module/ModuleSupport.java
bootstraps/bootstrap-java9/src/main/java/com/navercorp/pinpoint/bootstrap/java9/module/ModuleSupportFactory.java

Removed manually registering providers which occurs duplication

[#8890] Implemented findClass in Java9ClassLoader

---

collector/src/test/java/com/navercorp/pinpoint/collector/handler/grpc/GrpcAgentUriMetricHandlerV2Test.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/AgentInfoBo.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/AgentLifeCycleBo.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/ServerMetaDataBo.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/ServiceInfoBo.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/SpanBo.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/SpanChunkBo.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/SpanEventBo.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/event/AgentEventBo.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/event/DeadlockBo.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/event/DeadlockEventBo.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/event/MonitorInfoBo.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/event/ThreadDumpBo.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/AgentStatBo.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/AgentUriStatBo.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/DataSourceBo.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/DataSourceListBo.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/DeadlockThreadCountBo.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/EachUriStatBo.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/TotalThreadCountBo.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/TransactionBo.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/UriStatHistogram.java

Fix typos, Replace StringBuilder with String

[#noissue] Cleanup

---

commons/src/main/java/com/navercorp/pinpoint/common/trace/ServiceType.java
commons/src/main/java/com/navercorp/pinpoint/common/trace/ServiceTypeCategory.java
web/src/main/java/com/navercorp/pinpoint/web/calltree/span/LinkedCallTree.java
web/src/main/java/com/navercorp/pinpoint/web/calltree/span/SpanAligner.java
web/src/main/java/com/navercorp/pinpoint/web/mapper/SpanMapperV2.java

[#9905] Fix kafka on call tree view

---

commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/AnnotationFactory.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/grpc/GrpcAnnotationHandler.java

Since `bytes` in protobuf model corresponds to `com.google.protobuf.ByteString` instead of `byte[]` in Java, I've added logic to convert `ByteString` to `byte[]` when `ByteString`-typed annotation value is received.

[#noissue] Handle ByteString annotation values of protobuf

---

bootstraps/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/agentdir/AgentDirBaseClassPathResolver.java
bootstraps/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/agentdir/JarDescription.java
bootstraps/bootstrap/src/test/java/com/navercorp/pinpoint/bootstrap/agentdir/AgentVersionTest.java

Hi.
I have checked that an error occurs when running with agent of latest released 2.5.1-p1 version.
(If you build and use the 2.5.1-p1 tag, then you can get following error .)
```
java.lang.IllegalStateException: pinpoint-bootstrap-x.x.x(-SNAPSHOT)(-RCx).jar not found.
at com.navercorp.pinpoint.bootstrap.agentdir.AgentDirBaseClassPathResolver.resolve(AgentDirBaseClassPathResolver.java:73)
at com.navercorp.pinpoint.bootstrap.PinpointBootStrap.resolveAgentDir(PinpointBootStrap.java:132)
at com.navercorp.pinpoint.bootstrap.PinpointBootStrap.start(PinpointBootStrap.java:100)
```
It seems that the version like patch from (-p1) is not supported, I have fixed it.
You can close the PR at any time if your intention is to not support building and using it.
Thanks :)

[#9918] Support version like patch form

---

commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/ConnectionFactoryBean.java
commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HBaseAsyncOperationFactory.java
commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HadoopResourceCleanerRegistry.java
commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/TableMultiplexerAsyncOperation.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/join/JoinApplicationStatBo.java
flink/src/main/java/com/navercorp/pinpoint/flink/Bootstrap.java
flink/src/main/java/com/navercorp/pinpoint/flink/cluster/FlinkServerRegister.java
flink/src/main/java/com/navercorp/pinpoint/flink/receiver/TcpSourceFunction.java
hbase2-module/hbase2-flink/pom.xml
hbase2-module/hbase2-flink/src/main/java/com/navercorp/pinpoint/flink/hbase/Hbase2HadoopResourceCleanerRegistry.java
hbase2-module/hbase2-flink/src/main/java/org/apache/hbase/thirdparty/io/netty/buffer/PoolArenaCleaner.java
hbase2-module/hbase2-flink/src/main/resources/applicationContext-flink-extend.xml
hbase2-module/pom.xml

resolves #9922
* Explicitly closes HTableMultiplexer
* Explicitly shutdown HTableFlushWorkers
* Explicitly shutdown netty idle connection sweeper
* Explicitly closes netty wheel timer
* Explicitly shutdown netty event-loop-group
* Explicitly finalizes direct buffer arenas of netty
* Nullify flink-bootstrap after closing
* Do reachable-test when choosing ip
* Fixed wrong dependencies (hbase-shaded-client)

[#9922] Enhanced resource reclaimation in hbase2 client

---

profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultBaseTraceFactory.java

[#9958] fix duplicated active trace

---

profiler-logging/src/main/java/com/navercorp/pinpoint/profiler/logging/Log4j2LoggingSystem.java

https://logging.apache.org/log4j/2.x/manual/configuration.html#automatic-configuration

[#9893] Align Log4j2 loggingsystem lookup orders

---

realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/activethread/count/dao/ActiveThreadCountFetcherFactory.java
realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/activethread/count/dao/ActiveThreadCountWebDaoConfig.java
realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/activethread/count/dao/OptimisticFetcher.java

When updating flux of activeThreadCount, connection message overrides meaningful payload.
This patch restrict the connection message to be passed only one time per websocket request

[#9666] Fixed realtime to maintain valid value

---

plugins-it/cxf-it/src/test/java/com/navercorp/pinpoint/plugin/cxf/CxfClient_3_6_x_IT.java

com.navercorp.pinpoint.plugin.cxf.CxfClientIT.test[cxf-rt-rs-client-3.6.0:child:8]
~~~
Error Message
java.lang.UnsupportedClassVersionError: org/apache/cxf/jaxrs/client/WebClient has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
~~~

[#noissue] Fix cxf-it test

---

plugins/undertow/src/main/java/com/navercorp/pinpoint/plugin/undertow/interceptor/ConnectorsExecuteRootHandlerInterceptor.java

UnderTow does not collect data, befause 
[com.navercorp.pinpoint.plugin.undertow.interceptor.ConnectorsExecuteRootHandlerInterceptor#handlerPredicate ] return a Predicate， but the Predicate‘s test method always return false.

fix [UnderTow does not collect data] bug

---

redis/src/main/java/com/navercorp/pinpoint/pubsub/endpoint/PubSubFluxClientImpl.java
redis/src/main/java/com/navercorp/pinpoint/pubsub/endpoint/PubSubMonoClientImpl.java

[#10079] Propagate pubsub req cancellation

---

collector/src/main/java/com/navercorp/pinpoint/collector/cluster/ClusterPointRouter.java

This PR introduces a new logging statement to the handleRouteRequest() method in the stream handling logic of our application. The new log statement will record the details of each request being handled, as well as the remote address from which the request originated.
By logging this information, we aim to improve the traceability and debuggability of our request handling procedures. This will be particularly beneficial in instances of unexpected behavior or failures, as it will allow us to pinpoint the exact request and source of any issues.

[#noissue] Added Logs to record route request

---

bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/scope/ScopedInterceptor.java
bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/scope/ScopedInterceptor0.java
bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/scope/ScopedInterceptor1.java
bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/scope/ScopedInterceptor2.java
bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/scope/ScopedInterceptor3.java
bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/scope/ScopedInterceptor4.java
bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/scope/ScopedInterceptor5.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/interceptor/scope/ScopedInterceptorTest.java

[#10246] Fix missing leave() of ScopedInterceptor when an exception occurs

---

agent/src/main/resources/profiles/local/pinpoint.config
agent/src/main/resources/profiles/release/pinpoint.config
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/ReactorPlugin.java
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/ReactorPluginConfig.java
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/interceptor/FluxAndMonoSubscribeOnInterceptor.java

[#10335] Backport: update reactor publishOn, subscribeOn options

---

web/src/main/java/com/navercorp/pinpoint/web/applicationmap/config/ApplicationMapModule.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/map/LinkSelectorFactory.java
web/src/test/java/com/navercorp/pinpoint/web/applicationmap/map/LinkSelectorTestBase.java

if there is implemented serverMapDataFilter
filtering should be done when finding links for serverMap

[#noissue] fix serverMapDataFilter on linkSelector

---

bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/http/HttpStatusCodeRecorder.java
bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/request/ServletRequestListener.java
bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/request/ServletRequestListenerBuilder.java
bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/response/ServletResponseListener.java
bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/response/ServletResponseListenerBuilder.java
bootstraps/bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/plugin/http/HttpStatusCodeRecorderTest.java
plugins/jboss/src/main/java/com/navercorp/pinpoint/plugin/jboss/interceptor/StandardHostValveInvokeInterceptor.java
plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/interceptor/AbstractServerHandleInterceptor.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/HttpServerHandleInterceptor.java
plugins/resin/src/main/java/com/navercorp/pinpoint/plugin/resin/interceptor/ServletInvocationServiceInterceptor.java
plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/jakarta/interceptor/StandardHostValveInvokeInterceptor.java
plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/javax/interceptor/StandardHostValveInvokeInterceptor.java
plugins/undertow/src/main/java/com/navercorp/pinpoint/plugin/undertow/interceptor/ConnectorsExecuteRootHandlerInterceptor.java

[#10355] Fix servlet response http-status-recorder

---

agent-testweb/closed-module-testlib/.gitignore
agent-testweb/closed-module-testlib/pom.xml
agent-testweb/closed-module-testlib/src/main/java/com/navercorp/pinpointdemo/ClosedService.java
agent-testweb/closed-module-testlib/src/main/java/module-info.java
agent-testweb/closed-module-testweb/.gitignore
agent-testweb/closed-module-testweb/pom.xml
agent-testweb/closed-module-testweb/src/main/java/com/navercorp/pinpoint/closedcaller/ClosedClassCallerStarter.java
agent-testweb/closed-module-testweb/src/main/java/com/navercorp/pinpoint/closedcaller/ClosedClassCallingController.java
agent-testweb/closed-module-testweb/src/main/java/module-info.java
agent-testweb/pom.xml
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/javamodule/ClassFileTransformerModuleHandler.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/context/javamodule/ClassFileTransformerModuleHandlerTest.java

[#10358] Ensure className not null for module permission

---

profiler/src/main/java/com/navercorp/pinpoint/profiler/context/ChildTrace.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultBaseTraceFactory.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DisableChildTrace.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/recorder/ChildTraceSpanEventRecorder.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/recorder/DefaultRecorderFactory.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/recorder/DisableChildTraceSpanEventRecorder.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/recorder/RecorderFactory.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/context/AsyncContextTest.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/context/DefaultAsyncTraceContextTest.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/context/id/LocalTraceRootTest.java

[#10371] Update child trace end point guard

---

web-frontend/pom.xml

[#10388] Added frontend forceclean

---

agent/src/main/resources/pinpoint-root.config
bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/DefaultProfilerConfig.java
bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/ProfilerConfig.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/grpc/config/GrpcTransportConfig.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/GrpcModule.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/grpc/SpanGrpcDataSenderProvider.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/metric/ChannelzScheduledReporterBuilder.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/metric/DefaultChannelzReporter.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/metric/DefaultChannelzScheduledReporter.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/sender/grpc/metric/ChannelzScheduledReporterBuilderTest.java

Span gRPC server reports its stats periodically.
- This reports are enabled only if the property `profiler.transport.grpc.span.stats.logging.enable` is `true` (disabled by default)
- `profiler.transport.grpc.stats.logging.period` can configure the period of reports

[#10431] Optional gRPC stat logging in agent

---

exceptiontrace/exceptiontrace-collector/src/main/java/com/navercorp/pinpoint/exceptiontrace/collector/ExceptionTraceCollectorConfig.java
exceptiontrace/exceptiontrace-collector/src/main/java/com/navercorp/pinpoint/exceptiontrace/collector/ExceptionTraceCollectorPropertySources.java
exceptiontrace/exceptiontrace-collector/src/main/java/com/navercorp/pinpoint/exceptiontrace/collector/mapper/ErrorMessageMapper.java
exceptiontrace/exceptiontrace-collector/src/main/java/com/navercorp/pinpoint/exceptiontrace/collector/mapper/ExceptionMetaDataMapper.java
exceptiontrace/exceptiontrace-collector/src/main/resources/pinpoint-collector-exceptiontrace.properties
exceptiontrace/exceptiontrace-collector/src/test/java/com/navercorp/pinpoint/exceptiontrace/collector/mapper/ExceptionMetaDataMapperTest.java
exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/controller/ExceptionTraceController.java
exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/util/ExceptionTraceQueryParameter.java
exceptiontrace/exceptiontrace-web/src/main/resources/exceptiontrace/mapper/ExceptionTraceMapper.xml

This issue is fixed in pinot 0.12.0, BTW add this fallback for more stability and compatibility
ref: github.com/apache/pinot/issues/10061

[#9631] Store errorMessage as the replaced string in the collector

---

exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/controller/ExceptionTraceController.java
exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/dao/ExceptionTraceDao.java
exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/dao/PinotExceptionTraceDao.java
exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/mapper/ExceptionMetaDataEntityMapper.java
exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/service/ExceptionTraceService.java
exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/service/ExceptionTraceServiceImpl.java
exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/view/ExceptionMetaDataView.java
exceptiontrace/exceptiontrace-web/src/test/java/com/navercorp/pinpoint/exceptiontrace/web/mapper/ExceptionMetaDataEntityMapperTest.java

Sometimes, `long` may be rounded by js.
To prevent unwanted rounding, change format long to String of `spanId` and `exceptionId`

[#9631] Change format long to String; spanId, exceptionId

---

agent/src/main/resources/profiles/local/pinpoint.config
agent/src/main/resources/profiles/release/pinpoint.config
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/ReactorNettyPluginConfig.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/ClientTransportSubscriberInterceptor.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/HttpObserverOnUncaughtExceptionInterceptor.java
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/ReactorPluginConfig.java
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/interceptor/OnErrorSubscriberInterceptor.java

[#10492] Update reactor mark error

---

agent-testweb/grpc-plugin-testweb/pom.xml
agent-testweb/ning-asynchttpclient-plugin-testweb/pom.xml
agent-testweb/okhttp-plugin-testweb/pom.xml
commons/src/main/java/com/navercorp/pinpoint/common/Version.java

There are some version numbers errors on the 2.5.x.
Somebody want use this branch but it  can't build success directly after clone.

Fix mismatched version numbers

---

.github/workflows/it-command.yml

`save-state` and `set-output` commands used in GitHub Actions are deprecated and [GitHub recommends using environment files](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/).
This PR updates the usage of `set-output` to `$GITHUB_OUTPUT`
Instructions for envvar usage from GitHub docs:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter

Use GITHUB_OUTPUT envvar instead of set-output command as the latter is deprecated

---

bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/context/SpanEventRecorder.java
bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/interceptor/PreparedStatementCreateInterceptor.java
bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/interceptor/PreparedStatementExecuteQueryInterceptor.java
plugins/cassandra/src/main/java/com/navercorp/pinpoint/plugin/cassandra/interceptor/CassandraPreparedStatementCreateInterceptor.java
plugins/cassandra/src/main/java/com/navercorp/pinpoint/plugin/cassandra/interceptor/CassandraStatementExecuteQueryInterceptor.java
plugins/cassandra4/src/main/java/com/navercorp/pinpoint/plugin/cassandra4/interceptor/DefaultSessionExecuteInterceptor.java
plugins/informix-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/informix/interceptor/InformixPreparedStatementCreateInterceptor.java
plugins/spring-data-r2dbc/src/main/java/com/navercorp/pinpoint/plugin/spring/r2dbc/interceptor/StatementExecuteInterceptor.java
plugins/spring-data-r2dbc/src/main/java/com/navercorp/pinpoint/plugin/spring/r2dbc/interceptor/mssql/MssqlStatementExecuteInterceptor.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultSqlCountService.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DisableSqlCountService.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/SqlCountService.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/id/DefaultShared.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/id/Shared.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/ApplicationContextModule.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/monitor/config/DefaultMonitorConfig.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/monitor/config/MonitorConfig.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/SqlCountServiceProvider.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/recorder/ChildTraceSpanEventRecorder.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/recorder/DefaultRecorderFactory.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/recorder/DisableSpanEventRecorder.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/recorder/WrappedSpanEventRecorder.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/context/DefaultSqlCountServiceTest.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/context/DefaultTraceTest.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/context/TraceTest.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/context/recorder/WrappedSpanEventRecorderTest.java

[#10604] Mark multiple sql executions as error

---

profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/SpanGrpcDataSender.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/StatGrpcDataSender.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/StreamTask.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/stream/DefaultStreamTask.java

[#10614] add steam task check

---

profiler/src/main/java/com/navercorp/pinpoint/profiler/context/AsyncDefaultTrace.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/ChildTrace.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultBaseTraceFactory.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTrace.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/exception/DefaultExceptionRecordingService.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/exception/DefaultExceptionRecordingServiceFactory.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/exception/DisabledExceptionRecordingServiceFactory.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/exception/ExceptionRecordingService.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/exception/ExceptionRecordingServiceFactory.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/exception/model/DefaultExceptionContextFactory.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/DisabledExceptionTraceModule.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/ExceptionTraceModule.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/BaseTraceFactoryProvider.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/exception/DisabledExceptionRecordingServiceFactoryProvider.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/exception/ExceptionRecordingServiceFactoryProvider.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/recorder/DefaultRecorderFactory.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/recorder/WrappedSpanEventRecorder.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/context/DefaultTraceTest.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/context/TraceTest.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/context/recorder/WrappedSpanEventRecorderTest.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/metadata/DefaultExceptionRecordingServiceTest.java

[#9631] Integrate ExceptionContext lifecycle into ExceptionRecordingService

---

batch/src/main/java/com/navercorp/pinpoint/batch/BatchModule.java
batch/src/main/java/com/navercorp/pinpoint/batch/common/BatchJobLauncher.java
batch/src/main/java/com/navercorp/pinpoint/batch/common/BatchProperties.java
batch/src/main/java/com/navercorp/pinpoint/batch/common/StartupJobLauncher.java
batch/src/main/java/com/navercorp/pinpoint/batch/configuration/CleanupInactiveApplicationsJobConfig.java
batch/src/main/java/com/navercorp/pinpoint/batch/job/AgentCountReader.java
batch/src/main/java/com/navercorp/pinpoint/batch/job/ApplicationEmptyFilter.java
batch/src/main/java/com/navercorp/pinpoint/batch/job/ApplicationReader.java
batch/src/main/java/com/navercorp/pinpoint/batch/job/ApplicationRemover.java
batch/src/main/java/com/navercorp/pinpoint/batch/job/EmptyItemWriter.java
batch/src/main/java/com/navercorp/pinpoint/batch/service/ApplicationService.java
batch/src/main/java/com/navercorp/pinpoint/batch/service/ApplicationServiceImpl.java
batch/src/main/resources/applicationContext-batch-schedule.xml
batch/src/main/resources/batch-root.properties
batch/src/main/resources/job/applicationContext-cleanupInactiveApplicationsJob.xml

resolves #10605 
The conditions to clean an application is below
1. Any span about this application does not exist in hbase
2. Any agent is not alive currently
Checking the condition 2 (agent aliveness) might be unstable because of the TCP connection, but I think it would be supplemented by the condition 1. Also cleaning application does not mean to clean other informations like span or metadata of agent

[#10605] Added cleanup inactive applications batch job

---

batch/src/main/java/com/navercorp/pinpoint/batch/job/CleanTargetWriter.java
batch/src/main/java/com/navercorp/pinpoint/batch/job/CleanupInactiveAgentsTasklet.java
web/src/main/java/com/navercorp/pinpoint/web/authorization/controller/AdminController.java
web/src/main/java/com/navercorp/pinpoint/web/service/AdminService.java
web/src/main/java/com/navercorp/pinpoint/web/service/AdminServiceImpl.java
web/src/test/java/com/navercorp/pinpoint/web/service/AdminServiceImplTest.java

[#10605] Deprecated cleanupInactiveAgentsJob

---

agent-testweb/jdk-httpclient-plugin-testweb/README.md
agent-testweb/jdk-httpclient-plugin-testweb/pom.xml
agent-testweb/jdk-httpclient-plugin-testweb/src/main/java/com/pinpoint/test/plugin/JdkHttpClientPluginController.java
agent-testweb/jdk-httpclient-plugin-testweb/src/main/java/com/pinpoint/test/plugin/JdkHttpClientPluginTestStarter.java
agent-testweb/jdk-httpclient-plugin-testweb/src/main/resources/application.yml
agent-testweb/pom.xml
agent/src/main/resources/profiles/local/pinpoint.config
agent/src/main/resources/profiles/release/pinpoint.config
commons/src/main/java/com/navercorp/pinpoint/common/trace/ServiceType.java
plugins/assembly/pom.xml
plugins/jdk-completable-future/src/main/java/com/navercorp/pinpoint/plugin/jdk/completable/JdkCompletableFuturePlugin.java
plugins/jdk-httpclient/README.md
plugins/jdk-httpclient/pom.xml
plugins/jdk-httpclient/src/main/java/com/navercorp/pinpoint/plugin/jdk/httpclient/HttpRequestImplClientHeaderAdaptor.java
plugins/jdk-httpclient/src/main/java/com/navercorp/pinpoint/plugin/jdk/httpclient/HttpRequestImplClientRequestAdaptor.java
plugins/jdk-httpclient/src/main/java/com/navercorp/pinpoint/plugin/jdk/httpclient/HttpRequestImplGetter.java
plugins/jdk-httpclient/src/main/java/com/navercorp/pinpoint/plugin/jdk/httpclient/JdkHttpClientConstants.java
plugins/jdk-httpclient/src/main/java/com/navercorp/pinpoint/plugin/jdk/httpclient/JdkHttpClientCookieExtractor.java
plugins/jdk-httpclient/src/main/java/com/navercorp/pinpoint/plugin/jdk/httpclient/JdkHttpClientEntityExtractor.java
plugins/jdk-httpclient/src/main/java/com/navercorp/pinpoint/plugin/jdk/httpclient/JdkHttpClientPlugin.java
plugins/jdk-httpclient/src/main/java/com/navercorp/pinpoint/plugin/jdk/httpclient/JdkHttpClientPluginConfig.java
plugins/jdk-httpclient/src/main/java/com/navercorp/pinpoint/plugin/jdk/httpclient/ResponseCodeGetter.java
plugins/jdk-httpclient/src/main/java/com/navercorp/pinpoint/plugin/jdk/httpclient/interceptor/HttpClientInterceptor.java
plugins/jdk-httpclient/src/main/java/com/navercorp/pinpoint/plugin/jdk/httpclient/interceptor/HttpResponseImplInterceptor.java
plugins/jdk-httpclient/src/main/java/com/navercorp/pinpoint/plugin/jdk/httpclient/interceptor/MultiExchangeResponseAsyncImplInterceptor.java
plugins/jdk-httpclient/src/main/java/com/navercorp/pinpoint/plugin/jdk/httpclient/interceptor/MultiExchangeResponseAsyncInterceptor.java
plugins/jdk-httpclient/src/main/resources/META-INF/pinpoint/type-provider.yml
plugins/jdk-httpclient/src/main/resources/META-INF/services/com.navercorp.pinpoint.bootstrap.plugin.ProfilerPlugin
plugins/pom.xml

[#10656] Add java 11 httpclient plugin

---

plugins/resttemplate/src/main/java/com/navercorp/pinpoint/plugin/resttemplate/interceptor/ClientHttpResponseInterceptor.java
plugins/resttemplate/src/main/java/com/navercorp/pinpoint/plugin/resttemplate/interceptor/HttpRequestInterceptor.java
plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/interceptor/ClientResponseFunctionInterceptor.java

method `org.springframework.http.client.reactive.ClientHttpResponse.getRawStatusCode()`  was removed in Spring Webflux 6.1. (see: https://github.com/spring-projects/spring-framework/commit/7df2e2a8d2a845984cde806232181da486dcf7bd)
In addition, `org.springframework.http.client.ClientHttpResponse.getRawStatusCode()` will be removed in Spring MVC 6.2.
Instead of using `getRawStatusCode()`, replace it with `getHttpStatusCode().value()`.

[#NotAssigned] Removed getRawStatusCode() method for removal in Spring Webflux 6.1

---

grpc/src/main/java/com/navercorp/pinpoint/grpc/client/ChannelFactoryBuilder.java
grpc/src/main/java/com/navercorp/pinpoint/grpc/client/DefaultChannelFactory.java
grpc/src/main/java/com/navercorp/pinpoint/grpc/client/DefaultChannelFactoryBuilder.java
grpc/src/main/java/com/navercorp/pinpoint/grpc/client/config/ClientRetryOption.java
grpc/src/main/java/com/navercorp/pinpoint/grpc/client/retry/HedgingServiceConfigBuilder.java
grpc/src/main/java/com/navercorp/pinpoint/grpc/client/retry/RetryServiceConfigBuilder.java
grpc/src/main/java/com/navercorp/pinpoint/grpc/client/retry/ServiceConfigBuilder.java
grpc/src/test/java/com/navercorp/pinpoint/grpc/client/config/RetryConfigTest.java
grpc/src/test/resources/client/example/hedging_service_config.json
grpc/src/test/resources/client/example/retry_service_config.json
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/grpc/config/GrpcTransportConfig.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/grpc/MetadataGrpcDataSenderProvider.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/LogResponseStreamObserver.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/MetadataGrpcDataSender.java

[#10693] Add enable option for grpc client reties

---

exceptiontrace/exceptiontrace-common/src/main/java/com/navercorp/pinpoint/exceptiontrace/common/model/ExceptionMetaData.java
exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/dao/PinotExceptionTraceDao.java
exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/mapper/ExceptionMetaDataEntityMapper.java
exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/model/ExceptionTraceSummary.java
exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/model/ExceptionTraceValueView.java
exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/model/Grouped.java
exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/util/ExceptionTraceQueryParameter.java
exceptiontrace/exceptiontrace-web/src/test/java/com/navercorp/pinpoint/exceptiontrace/web/mapper/ExceptionMetaDataEntityMapperTest.java
exceptiontrace/exceptiontrace-web/src/test/java/com/navercorp/pinpoint/exceptiontrace/web/model/ExceptionTraceValueViewTest.java

```java
public class PinotResultSet extends AbstractBaseResultSet {
public static final String NULL_STRING = "null";
...
@Override
public String getString(int columnIndex)
throws SQLException {
validateColumn(columnIndex);
String val = _resultSet.getString(_currentRow, columnIndex - 1);
if (checkIsNull(val)) {
return null;
}
return val;
}
private boolean checkIsNull(String val) {
if (val == null || val.toLowerCase().contentEquals(NULL_STRING)) {
_wasNull = true;
return true;
}
return false;
}
...
```

[#noissue] Handle PinotResultSet implicitly convert "null" to null

---

web-frontend/src/main/v3/packages/constants/src/appSettingKeys.ts
web-frontend/src/main/v3/packages/ui/src/components/Error/index.ts
web-frontend/src/main/v3/packages/ui/src/components/Form/index.ts
web-frontend/src/main/v3/packages/ui/src/components/ui/index.tsx
web-frontend/src/main/v3/packages/ui/src/pages/config/Alarm.tsx
web-frontend/src/main/v3/packages/ui/src/pages/config/Webhook.tsx

[#noissue] Change last-selected app setting key

---

agent-module/plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/MongoPlugin.java
agent-module/plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/interceptor/MongoClientV4ConstructorInterceptor.java

[#10940] Fix mongodb mongodbClient constructor

---

web-frontend/src/main/v3/packages/server-map/src/constants/style/theme.ts
web-frontend/src/main/v3/packages/server-map/src/core/merge.ts
web-frontend/src/main/v3/packages/server-map/src/ui/ServerMap.tsx
web-frontend/src/main/v3/packages/server-map/src/ui/template/node.ts
web-frontend/src/main/v3/packages/ui/src/components/ServerMap/ServerMapCore.tsx

- display 
- node instance count
- unit of average response time (ms)

[#noissue] fix servermap numaric display

---

exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/controller/ExceptionTraceController.java

Fixed because it was incorrect if checked after TimeWindow creation.

[#noissue] Check `Range` with given parameter

---

agent-module/plugins/spring-stub/src/main/java/org/springframework/http/HttpRequest.java
agent-module/plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/SpringWebFluxPlugin.java
agent-module/plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/interceptor/AbstractHandlerMethodMappingInterceptor.java
agent-module/plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/interceptor/AbstractUrlHandlerMappingInterceptor.java
agent-module/plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/interceptor/util/HttpMethodProvider.java
agent-module/plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/interceptor/util/HttpMethodProviderFactory.java
agent-module/plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/interceptor/util/Spring5HttpMethodProvider.java
agent-module/plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/interceptor/util/Spring6HttpMethodProvider.java
agent-module/plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/interceptor/util/UnsupportedHttpMethodProvider.java

[#11005] Update getMethod compatibility of spring-webflux

---

collector/src/main/java/com/navercorp/pinpoint/collector/config/CollectorProperties.java
collector/src/main/java/com/navercorp/pinpoint/collector/sampler/SimpleSpanSamplerFactory.java
collector/src/main/resources/pinpoint-collector-root.properties
collector/src/test/java/com/navercorp/pinpoint/collector/sampler/SamplerTest.java
collector/src/test/java/com/navercorp/pinpoint/collector/sampler/SimpleSpanFactoryTest.java

add span sampling properties to pinpoint banner

[#noissue] refactor collector span sampling

---

web-frontend/src/main/v3/packages/atoms/src/scatter.ts
web-frontend/src/main/v3/packages/utils/src/helper/filteredMap/merge.ts
web-frontend/src/main/v3/packages/utils/src/helper/serverMap.ts

- Pass the previous data if there's no data for the same key(agent) in the merging scatter process
- Match servermap data with timestamp, not with the data index
- Consider unauthorized condition only when there is node-list

[#noissue] Fix filteredMap merge logic

---

agent-module/bootstraps/bootstrap-java9-internal/pom.xml
agent-module/bootstraps/bootstrap-java9/pom.xml

The issue likely occurred during the process of integrating multiple modules under the `agent-module`. While modifying the settings to use standard Maven properties, the javadoc source configuration was removed, leading to the javadoc generation failure.
ref: #8851 #8852

[#8851] Fix javadoc generation failure

---

web/src/main/java/com/navercorp/pinpoint/web/vo/agent/AgentStatusFilters.java

[#11129] Fix `RecentRunningFilter` to include shutdown agents in range

---

agent-module/plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/MongoPlugin.java

[#11155] Fix MongoDB FindPublisherImpl method interceptor

---

web-frontend/src/main/v3/packages/atoms/src/transaction.ts
web-frontend/src/main/v3/packages/ui/src/components/DataTable/VirtualizedDataTable.tsx
web-frontend/src/main/v3/packages/ui/src/components/FlameGraph/FlameGraph.tsx
web-frontend/src/main/v3/packages/ui/src/components/FlameGraph/FlameNode.tsx
web-frontend/src/main/v3/packages/ui/src/components/Transaction/call-tree/CallTree.tsx
web-frontend/src/main/v3/packages/ui/src/components/Transaction/timeline/TimelineDetail.tsx
web-frontend/src/main/v3/packages/ui/src/components/Transaction/timeline/TimelineFetcher.tsx
web-frontend/src/main/v3/packages/ui/src/components/Transaction/transaction-info/TransactionInfoFetcher.tsx
web-frontend/src/main/v3/packages/ui/src/lib/colors.ts

- new features on timeline
- search 
- link to call tree

[#noissue] feat: add search and link func into timeline UI

---

agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/reactor/CoreSubscriberOnNextInterceptor.java
agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/reactor/CoreSubscriberOnSubscribeInterceptor.java
agent-module/plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/ReactorPlugin.java

[#11195] Update reactor onNext

---

agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/DefaultProfilerConfig.java
agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/ProfilerConfig.java
agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/cache/UidCache.java
agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/metadata/SqlMetadataServiceProvider.java
agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/metadata/DefaultSqlMetaDataService.java
agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/metadata/SimpleCachingSqlNormalizer.java
agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/metadata/SqlUidMetaDataService.java
agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/metadata/UidCachingSqlNormalizer.java
agent-module/profiler/src/test/java/com/navercorp/pinpoint/profiler/cache/UidCacheTest.java
agent-module/profiler/src/test/java/com/navercorp/pinpoint/profiler/metadata/SimpleCachingSqlNormalizerTest.java
agent-module/profiler/src/test/java/com/navercorp/pinpoint/profiler/metadata/SqlCacheServiceTest.java
agent-module/profiler/src/test/java/com/navercorp/pinpoint/profiler/metadata/SqlUidMetaDataServiceTest.java

[#11166] Bypass cache for long SQL queries

---

agent-module/plugins/arcus/src/main/java/com/navercorp/pinpoint/plugin/arcus/ArcusPlugin.java

[#11205] Update CacheManager constructor args of arcus plugin

---

collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/SimpleRequestHandlerAdaptor.java
grpc/src/main/java/com/navercorp/pinpoint/grpc/Header.java
grpc/src/main/java/com/navercorp/pinpoint/grpc/client/retry/RetryHeaderFactory.java
grpc/src/main/java/com/navercorp/pinpoint/grpc/server/AgentHeaderReader.java

[#11186] Change retry header key for collector response

---

web-frontend/src/main/v3/packages/ui/src/components/GlobalSearch/GlobalSearch.tsx
web-frontend/src/main/v3/packages/ui/src/components/Inspector/charts/InspectorChart.tsx
web-frontend/src/main/v3/packages/ui/src/components/SystemMetric/charts/SystemMetricChartFetcher.tsx
web-frontend/src/main/v3/packages/ui/src/components/ui/command.tsx

- resize Inspector&SystemMetric's card title
- adjust height of GlobalSearch

[#noissue] fix: GlobalSearch, Inspector styles

---

commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/timewindow/TimeWindowSlotCentricSampler.java
inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/controller/AgentInspectorStatController.java
web/src/main/java/com/navercorp/pinpoint/web/authorization/controller/AgentStatController.java
web/src/main/java/com/navercorp/pinpoint/web/authorization/controller/ApplicationDataSourceController.java
web/src/main/java/com/navercorp/pinpoint/web/authorization/controller/ApplicationStatController.java

Related commits https://github.com/pinpoint-apm/pinpoint/commit/06e48d70590e936728acc45663ee1f0da7f3d40f and https://github.com/pinpoint-apm/pinpoint/commit/5157e235bcc732e465094ce0c6af7b50e9a3984e

[#noissue] change inspector minimal time slot

---

commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/trace/v2/SpanDecoderV0.java

[#noissue] Fix typo bitField

---

collector/src/main/java/com/navercorp/pinpoint/collector/config/CollectorProperties.java
collector/src/main/java/com/navercorp/pinpoint/collector/service/HbaseSqlMetaDataService.java
collector/src/main/java/com/navercorp/pinpoint/collector/service/HbaseSqlUidMetaDataService.java

[#11310] Abbreviate sql in sql metadata if sql is too long

---

agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/DefaultProfilerConfig.java
agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/ProfilerConfig.java
agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/metadata/SqlMetadataServiceProvider.java
agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/metadata/SqlCacheService.java
agent-module/profiler/src/test/java/com/navercorp/pinpoint/profiler/metadata/SqlCacheServiceTest.java
agent-module/profiler/src/test/java/com/navercorp/pinpoint/profiler/metadata/SqlUidMetaDataServiceTest.java

[#11449] Trim long sql from agent

---

web-frontend/src/main/v3/packages/constants/src/types/OtlpMetricData.ts
web-frontend/src/main/v3/packages/ui/src/components/OpenTelemetry/charts/OpenTelemetryMetricFetcher.tsx
web-frontend/src/main/v3/packages/ui/src/components/OpenTelemetry/definition/MeticDefinitionFormFetcher.tsx

- valueList -> values
- areaSpline -> area, spline -> line

[#noissue] Fix otlp chart data property name

---

agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/context/Header.java
commons/src/main/java/com/navercorp/pinpoint/common/util/DelegateEnumeration.java
commons/src/main/java/com/navercorp/pinpoint/common/util/EmptyEnumeration.java
commons/src/main/java/com/navercorp/pinpoint/common/util/Predicates.java
commons/src/test/java/com/navercorp/pinpoint/common/util/DelegateEnumerationTest.java
commons/src/test/java/com/navercorp/pinpoint/common/util/PredicatesTest.java

[#11543] Remove unnecessary EnumerationFilter 

---

agent-module/agent-testweb/mariadb-jdbc-plugin-testweb/README.md
agent-module/agent-testweb/mariadb-jdbc-plugin-testweb/pom.xml
agent-module/agent-testweb/mariadb-jdbc-plugin-testweb/src/main/java/com/pinpoint/test/plugin/MariaDBPluginController.java
agent-module/agent-testweb/mariadb-jdbc-plugin-testweb/src/main/java/com/pinpoint/test/plugin/MariaDBPluginTestStarter.java
agent-module/agent-testweb/mariadb-jdbc-plugin-testweb/src/main/java/com/pinpoint/test/plugin/MariaDBServer.java
agent-module/agent-testweb/mariadb-jdbc-plugin-testweb/src/main/resources/application.yml
agent-module/agent-testweb/mariadb-jdbc-plugin-testweb/src/main/resources/init.sql
agent-module/agent-testweb/mariadb-jdbc-plugin-testweb/src/test/java/com/pinpoint/test/plugin/mongo/MariaDBTest.java
agent-module/agent-testweb/pom.xml
agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/util/InstrumentUtils.java
agent-module/bootstraps/bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/plugin/util/InstrumentUtilsTest.java
agent-module/plugins-it/mariadb-jdbc-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/MariaDB_3_x_DriverClass.java
agent-module/plugins-it/mariadb-jdbc-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/MariaDB_3_x_IT.java
agent-module/plugins/mariadb-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/mariadb/MariaDBPlugin.java
agent-module/plugins/mariadb-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/mariadb/interceptor/PreparedStatementConstructorInterceptor.java

[#11577] Update mariadb-plugin to support mariadb java client 3.x

---

collector-starter/src/main/java/com/navercorp/pinpoint/collector/starter/multi/application/BasicCollectorApp.java
collector-starter/src/main/java/com/navercorp/pinpoint/collector/starter/multi/application/PinpointCollectorStarter.java

Disable OtlpMetricsExportAutoConfiguration. Because it is not used.

[#11589] Disable OtlpMetricsExportAutoConfiguration. 

---

otlpmetric/otlpmetric-collector/src/main/java/com/navercorp/pinpoint/otlp/collector/mapper/OtlpMetricMapper.java

Remove the agentId from the tag data in the oltp data. 
Store the agentId information in a separate column.
Having the agentId information in the tag makes it difficult to pull application statistics data.

[#10776] Remove the agentId from the tag data in the oltp data. 

---

otlpmetric/otlpmetric-collector/src/main/java/com/navercorp/pinpoint/otlp/collector/mapper/GaugeMapper.java
otlpmetric/otlpmetric-collector/src/test/java/com/navercorp/pinpoint/otlp/collector/mapper/GaugeMapperTest.java
otlpmetric/otlpmetric-common/src/main/java/com/navercorp/pinpoint/otlp/common/model/MetricName.java

If metricGroup, metric, and field name are empty string, put the default value. This is to make it easier for users to define and search for metrics.

[#10776] If metricGroup, metric, and field name are empty string, put the default value

---

web-frontend/src/main/v3/packages/datetime-picker/src/components/RichDatetimePicker.tsx
web-frontend/src/main/v3/packages/ui/src/components/DatetimePicker/DatetimePicker.tsx

- Do not update the date state and display a warning if the maxRange is exceeded.
@jihea-park
Can you conduct various tests on this issue?

[#noissue] fix: datepicker's maxrange validation

---

agent-module/agent-testweb/cassandra3-plugin-testweb/src/test/java/com/pinpoint/test/plugin/cassandra/CassandraTest.java
agent-module/agent-testweb/cassandra4-plugin-testweb/src/test/java/com/pinpoint/test/plugin/cassandra/CassandraTest.java
agent-module/plugins-it/activemq-it/activemq-5-15-it/src/test/java/com/navercorp/pinpoint/it/plugin/activemq/client/ActiveMQClientITBase.java
agent-module/plugins-it/activemq-it/activemq-5-17-it/src/test/java/com/navercorp/pinpoint/it/plugin/activemq/client/ActiveMQClientITBase.java
agent-module/plugins-it/cassandra-it/cassandra-2-it/src/test/java/com/navercorp/pinpoint/it/plugin/cassandra/CassandraServer.java
agent-module/plugins-it/clickhouse-jdbc-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/clickhouse/ClickHouseITBase.java
agent-module/plugins-it/gson-it/src/test/java/com/navercorp/pinpoint/it/plugin/gson/GsonIT.java
agent-module/plugins-it/hbase-it/src/test/java/com/navercorp/pinpoint/it/plugin/hbase/HbaseClientIT.java
agent-module/plugins-it/httpclient-it/httpclient-5-it/src/test/java/com/navercorp/pinpoint/it/plugin/httpclient5/ClosableAsyncHttpClientIT.java
agent-module/plugins-it/kafka-it/kafka-2-it/src/test/java/test/pinpoint/plugin/kafka/TestConsumer.java
agent-module/plugins-it/kafka-it/kafka-3-it/src/test/java/test/pinpoint/plugin/kafka/TestConsumer.java
agent-module/plugins-it/netty-it/src/test/java/com/navercorp/pinpoint/it/plugin/netty/NettyIT.java
agent-module/plugins-it/oracledb-it/oracledb-19-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/oracle/Oracle_IT_Base.java
agent-module/plugins-test-module/plugins-it-utils-jdbc/src/main/java/com/navercorp/pinpoint/it/plugin/utils/jdbc/DataBaseTestCase.java
agent-module/plugins/httpclient3/src/main/java/com/navercorp/pinpoint/plugin/httpclient3/HttpClient3EntityExtractor.java
agent-module/plugins/ktor/src/main/java/com/navercorp/pinpoint/plugin/ktor/interceptor/HttpRequestAdaptor.java
agent-module/plugins/ktor/src/main/java/com/navercorp/pinpoint/plugin/ktor/interceptor/MethodFilterExtractor.java
agent-module/plugins/netty/src/main/java/com/navercorp/pinpoint/plugin/netty/NettyClientRequestWrapper.java
agent-module/plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/VertxHttpClientRequestWrapper.java

[#noissue] Fix deprecated API

---

agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/request/util/RealIpHeaderResolver.java
agent-module/plugins/common-servlet/src/test/java/com/navercorp/pinpoint/plugin/common/servlet/RemoteAddressResolverFactoryTest.java

[RFC 7239](https://datatracker.ietf.org/doc/html/rfc7239) Forwarded Header based RealIpHeaderResolver

[#11729] RFC 7239 Forwarded Header based RealIpHeaderResolver

---

agent-module/agent/src/main/resources/profiles/local/pinpoint.config
agent-module/agent/src/main/resources/profiles/release/pinpoint.config
agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/request/util/RealIpHeaderResolver.java
agent-module/plugins/common-servlet/src/test/java/com/navercorp/pinpoint/plugin/common/servlet/RemoteAddressResolverFactoryTest.java

[#11729] Update agent's realipheader value to the list type.

---

quickstart/testapp/pom.xml
quickstart/testapp/src/main/java/com/navercorp/pinpoint/testapp/controller/ApisController.java
quickstart/testapp/src/main/java/com/navercorp/pinpoint/testapp/controller/CallSelfController.java
quickstart/testapp/src/main/java/com/navercorp/pinpoint/testapp/controller/HttpClient4Controller.java
quickstart/testapp/src/main/java/com/navercorp/pinpoint/testapp/controller/SimpleController.java
quickstart/testapp/src/main/java/com/navercorp/pinpoint/testapp/controller/StressController.java
quickstart/testapp/src/main/java/com/navercorp/pinpoint/testapp/service/remote/HttpRemoteService.java

This fixes the compilation of the quickstart app, but doesn't fix the execution (yet).

Fix compilation - execution still fails

---

agent-module/agent/src/main/resources/profiles/local/pinpoint.config
agent-module/agent/src/main/resources/profiles/release/pinpoint.config
agent-module/plugins-it/activemq-it/activemq-5-15-it/src/test/resources/activemq/client/pinpoint-activemq-client.config
agent-module/plugins-it/activemq-it/activemq-5-17-it/src/test/resources/activemq/client/pinpoint-activemq-client.config
agent-module/plugins-it/cxf-it/cxf-3-0-it/src/test/resources/cxf/pinpoint-cxf-test.config
agent-module/plugins-it/cxf-it/cxf-3-6-it/src/test/resources/cxf/pinpoint-cxf-test.config
agent-module/plugins-it/druid-it/src/test/resources/druid/pinpoint-druid-test.config
agent-module/plugins-it/fastjson-it/src/test/resources/fastjson/pinpoint-fastjson-test.config
agent-module/plugins-it/hbase-it/src/test/resources/hbase/pinpoint-hbase-test.config
agent-module/plugins-it/hystrix-it/src/test/resources/hystrix/pinpoint-hystrix.config
agent-module/plugins-it/jtds-it/src/test/resources/pinpoint.config
agent-module/plugins-it/rxjava-it/src/test/resources/rxjava/pinpoint-rxjava.config
agent-module/plugins/akka-http/src/test/resources/pinpoint.config
agent-module/plugins/weblogic/src/test/resources/pinpoint.config
web/src/main/resources/pinpoint-web-root.properties

As indicated in #11911, the links to the feature guides are outdated. This is fixed by this PR, done using:
```
for file in $(fgrep -Rl "https://github.com/naver/pinpoint/blob/master/doc/per-request_feature_guide.md" *)
do     
sed -i 's|https://github.com/naver/pinpoint/blob/master/doc/per-request_feature_guide.md|https://github.com/pinpoint-apm/pinpoint-apm.github.io/blob/main/documents/per-request_feature_guide.md|g' "$file"
done
```

Fix link to feature guide

---

web-frontend/src/main/v3/packages/ui/src/components/FlameGraph/FlameNode.tsx
web-frontend/src/main/v3/packages/ui/src/components/Transaction/timeline/TimelineFetcher.tsx
web-frontend/src/main/v3/packages/ui/src/lib/colors.ts

[#11921] FlameGraph > Set colors for each application name

---

commons-profiler/src/main/java/com/navercorp/pinpoint/common/profiler/sql/OutputParameterParser.java
commons-profiler/src/test/java/com/navercorp/pinpoint/common/profiler/sql/DefaultSqlNormalizerTest.java
commons-profiler/src/test/java/com/navercorp/pinpoint/common/profiler/sql/OutputParameterParserTest.java

Ignore leading space when binding parameters since an extra space is added at the agent side when packing values in `String`.
https://github.com/pinpoint-apm/pinpoint/blob/7c92d5de7d9bafba9e341256608a49eec1922695/agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/jdbc/BindValueUtils.java#L82-L103
Resolves #11967.

[#11967] Skip leading space when binding values

---

agent-module/bootstraps/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/PinpointStarter.java

Related PR: #11797.
There was an issue where the system property was not applied to the agent configuration.
When copying system properties, `new Properties(System.getProperties())` was used. This means that the new `Properties` object only refers to system properties for keys that are not explicitly set, and these default properties will not be included in the iteration like the code below.
https://github.com/pinpoint-apm/pinpoint/blob/f2e771bd4f7688ba3989f9abff3fc6015ec3e406/agent-module/bootstraps/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/config/PropertyLoaderUtils.java#L27-L40

[#noissue] Fix copyJavaSystemProperty()

---

agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/DefaultProfilerConfig.java
agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/ProfilerConfig.java
agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/metadata/SqlMetadataServiceProvider.java
agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/metadata/UidCachingSqlNormalizer.java
agent-module/profiler/src/test/java/com/navercorp/pinpoint/profiler/metadata/SqlUidMetaDataServiceTest.java
commons-profiler/src/main/java/com/navercorp/pinpoint/common/profiler/sql/DefaultSqlNormalizer.java
commons-profiler/src/test/java/com/navercorp/pinpoint/common/profiler/sql/DefaultSqlNormalizerTest.java

Related issue: #12061.
Apply only for sqlUid feature enabled agents.

[#12061] Backport: Remove comments from SQL queries

---

pom.xml

[#12220] Backport: Bump ASM from 9.6 to 9.7.1

---

commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/timewindow/TimeWindow.java
commons-server/src/test/java/com/navercorp/pinpoint/common/server/util/timewindow/TimeWindowTest.java
metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/util/TimeSeriesBuilder.java
metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/util/TimeUtils.java
metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/model/MetricDataSearchKey.java
metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/model/chart/TimeSeriesChartBuilder.java
metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/view/SystemMetricChartSerializer.java
otlpmetric/otlpmetric-common/src/main/java/com/navercorp/pinpoint/otlp/common/util/TimeSeriesBuilder.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/histogram/AgentTimeHistogram.java
web/src/main/java/com/navercorp/pinpoint/web/vo/chart/TimeSeriesChartBuilder.java

This pull request introduces several changes to the `TimeWindow` class and its usage across multiple files to improve performance and accuracy. The changes primarily focus on replacing dynamic calculations of window range count with a precomputed value, simplifying code, and ensuring consistency in type usage.
* Added a new field `windowRangeCount` to store the precomputed window range count. (`commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/timewindow/TimeWindow.java`) [[1]](diffhunk://#diff-9296ccf1f55d882c901e94622e9010a84e1e9a1599336d534b40d8def023da63R39-R40) [[2]](diffhunk://#diff-9296ccf1f55d882c901e94622e9010a84e1e9a1599336d534b40d8def023da63R50-R58)
* Modified the `getWindowRangeCount` method to return the precomputed `windowRangeCount` instead of …

[#12235] Improve windowRangeCount for TimeWindows to be precomputed

---

commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/timewindow/TimeSeriesIterator.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/timewindow/TimeSeriesVirtualList.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/timewindow/TimeWindow.java
commons-server/src/test/java/com/navercorp/pinpoint/common/server/util/timewindow/TimeSeriesVirtualListTest.java
commons-server/src/test/java/com/navercorp/pinpoint/common/server/util/timewindow/TimeWindowTest.java
exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/util/TimeSeriesUtils.java
inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/service/DefaultAgentStatService.java
inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/service/DefaultApplicationStatService.java
metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/util/TimeUtils.java
metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/service/SystemMetricDataServiceImpl.java
metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/view/SystemMetricChartSerializer.java
otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/service/OtlpMetricWebServiceImpl.java
uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/view/UriStatView.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/histogram/AgentTimeHistogram.java
web/src/test/java/com/navercorp/pinpoint/web/vo/ResponseHistogramsTest.java

This pull request includes several changes aimed at improving the handling of time series data in the `commons-server` and related modules. The changes introduce new utility classes, refactor existing classes, and update test cases accordingly.
* [`commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/timewindow/TimeSeriesIterator.java`](diffhunk://#diff-63b4f40db74f33a9114c76d481db3895d1bea9424c53a1414bf6f09fb4bbcb3aR1-R45): Added a new `TimeSeriesIterator` class to iterate over time series data.
* [`commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/timewindow/TimeSeriesVirtualList.java`](diffhunk://#diff-1f54a1524503a25b119dcb85f3db1bd3cc01d64284bda61ef373c4470e6dc7faR1-R41): Added a new `TimeSeriesVirtualList` class to represent a virtual list of …

[#12238] Add virtual TimeseriesWindows to TimeWindow

---

commons-server/src/main/java/com/navercorp/pinpoint/common/server/scatter/OneByteFuzzyRowKeyFactory.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/array/DoubleArray.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/array/IntArray.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/array/LongArray.java
commons-server/src/test/java/com/navercorp/pinpoint/common/server/util/array/DoubleArrayTest.java
commons-server/src/test/java/com/navercorp/pinpoint/common/server/util/array/LongArrayTest.java
exceptiontrace/exceptiontrace-collector/src/main/java/com/navercorp/pinpoint/exceptiontrace/collector/mapper/StackTraceMapper.java
inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/definition/metric/AvgUsingIntervalPostProcessor.java
inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/definition/metric/PercentageScalePostProcessor.java
inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/service/DefaultAgentStatService.java
inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/service/DefaultApdexStatService.java
inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/service/DefaultApplicationStatService.java
otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/view/legacy/OtlpChartViewBuilder.java
otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/vo/MetricData.java
otlpmetric/otlpmetric-web/src/test/java/com/navercorp/pinpoint/otlp/web/view/OtlpChartViewTest.java
uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/model/UriStatGroup.java
uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/view/UriStatView.java
web/src/main/java/com/navercorp/pinpoint/web/view/histogram/TimeHistogramChartBuilder.java

This pull request includes various changes to improve array handling and simplify code by using utility methods from the Guava library. The most significant changes involve refactoring code to utilize `Doubles`, `Ints`, and `Longs` utility classes, and introducing new utility classes for array handling.
Refactoring to use Guava utility methods:
* [`commons-server/src/main/java/com/navercorp/pinpoint/common/server/scatter/OneByteFuzzyRowKeyFactory.java`](diffhunk://#diff-9015fc50bf14a6926f1f93c856cc7118bb39c263fc8533338d64cb05dd394dccL31-L41): Replaced custom `toLongArray` method with `Longs.toArray` for converting a list of `Long` to a primitive array.
Introduction of new utility classes:
* [`commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/array/DoubleArray.java`](di …

[#12241] Apply Primitive Containers to optimize memory usage

---

exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/util/ExceptionTraceQueryParameter.java
metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/util/QueryParameter.java
otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/vo/OtlpMetricChartQueryParameter.java
otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/vo/OtlpMetricDataQueryParameter.java
uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/util/UriStatChartQueryParameter.java
uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/util/UriStatSummaryQueryParameter.java

This pull request includes several changes to various query parameter classes across multiple modules to standardize the handling of limit values and improve type consistency by switching from `long` to `int` for limit-related fields and methods.
Standardizing limit handling and type consistency:
* [`exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/util/ExceptionTraceQueryParameter.java`](diffhunk://#diff-192c0cff0590236540b8cad6521117b6305523e5d90aa36ee8c7686ea91a38e3L154-R155): Updated `setHardLimit` method to use `Ints.constrainToRange` for constraining limit values and changed `useLimitIfSet` and `estimateLimit` methods to return `int` instead of `long`. [[1]](diffhunk://#diff-192c0cff0590236540b8cad6521117b6305523e5d90aa36ee8c7686ea91a38e3L154- …

[#noissue] Refactor QueryParameter

---

agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/UriStatStorageProvider.java
agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/storage/AsyncQueueingUriStatStorage.java
agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/storage/UriMethodTransformer.java
agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/storage/UriOnlyTransformer.java
agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/storage/UriTransformer.java
agent-module/profiler/src/test/java/com/navercorp/pinpoint/profiler/context/storage/AsyncQueueingUriStatStorageTest.java
agent-module/profiler/src/test/java/com/navercorp/pinpoint/profiler/context/storage/UriMethodTransformerTest.java

… for improved URI handling
This pull request includes several changes to the `agent-module/profiler` package to introduce and utilize the `UriTransformer` interface for transforming URIs based on HTTP methods. The most important changes include the addition of new classes implementing the `UriTransformer` interface, modifications to existing classes to use the new interface, and updates to tests to accommodate these changes.
* [`agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/storage/UriTransformer.java`](diffhunk://#diff-67b7f5acf062bd87b31e81c44147f1499730755e64b13d112549ace936e1886eR1-R6): Added a new interface `UriTransformer` with a method `transform` to handle URI transformations.
* [`agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/con …

[#noissue] Refactor AsyncQueueingUriStatStorage to use UriTransformer for improved URI handling

---

commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/timewindow/TimeSeriesVirtualList.java
commons-server/src/test/java/com/navercorp/pinpoint/common/server/util/timewindow/TimeSeriesVirtualListTest.java

This pull request introduces enhancements to the `TimeSeriesVirtualList` class and its corresponding tests. The main changes include adding support for the `toArray` method, implementing unsupported operations, and updating the test cases to cover these new functionalities.
Enhancements to `TimeSeriesVirtualList`:
* Added `toArray` method to convert the list to an array. (`commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/timewindow/TimeSeriesVirtualList.java`)
* Implemented unsupported operations to throw `UnsupportedOperationException`. (`commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/timewindow/TimeSeriesVirtualList.java`)
Updates to test cases:
* Added new test cases to validate the `toArray` method and ensure compatibility with …

[#noisie] Improved debuggability of TimeSeriesVirtualList

---

commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/array/DoubleArray.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/array/IntArray.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/array/LongArray.java

This pull request introduces several changes to the `DoubleArray`, `IntArray`, and `LongArray` utility classes in the `commons-server` module. The main goal of these changes is to improve the conversion of lists to arrays and vice versa by adding new methods and refactoring existing ones.
Key changes include:
* Added `asDoubleArray`, `asIntArray`, and `asLongArray` methods to convert `Collection` objects to arrays for better flexibility. [[1]](diffhunk://#diff-2445ce332ca2a42edd959395415576f9990977d8ad4cd95bc73ca9934f29d493L21-R47) [[2]](diffhunk://#diff-09fd5d4194053d086a13fd4cb36adb510ca232644f16aef2ae9b578ce3f57fcaL14-R39) [[3]](diffhunk://#diff-2a1ab023f79f10e861f8bcedad1551c8b1ebfc69753adcd03d2c358983f47d2bL14-R39)
* Refactored existing `asList` methods to use the new array …

[#noissue] Refactor Array utility

---

uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/config/UriRegistryHandler.java
uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/dao/PinotApdexChartDao.java
uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/dao/PinotFailureCountChartDao.java
uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/dao/PinotLatencyChartDao.java
uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/dao/PinotTotalCountChartDao.java
uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/entity/UriApdexChartEntity.java
uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/entity/UriEntity.java
uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/entity/UriHistogramEntity.java
uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/entity/UriHistogramFailEntity.java
uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/entity/UriLatencyChartEntity.java
uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/entity/UriStatChartEntity.java
uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/entity/UriStatSummaryEntity.java
uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/mapper/EntityToModelMapper.java
uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/mapper/MapperUtils.java
uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/model/UriStatChartValue.java
uristat/uristat-web/src/main/resources/mapper/uristat/UriStatChartMapper.xml
uristat/uristat-web/src/test/java/com/navercorp/pinpoint/uristat/web/mapper/EntityToModelMapperTest.java

This pull request includes several updates to the `uristat` module, focusing on refactoring entity classes and updating DAO classes to use the new entities. The changes aim to improve the structure and functionality of the codebase.
* Added new entity classes: `UriApdexChartEntity`, `UriHistogramEntity`, `UriHistogramFailEntity`, and `UriLatencyChartEntity`, which extend the new base class `UriEntity`. (`[[1]](diffhunk://#diff-bc42c8d5a84a03289d8f7256fcadbdbf2884d7960213ada248e5b84d6e65a4edR1-R47)`, `[[2]](diffhunk://#diff-bdd316e8ec55e7da06505b5aeb750d83c4fb1346adea948e065480c220f36e3aR1-R109)`, `[[3]](diffhunk://#diff-516af0c295e515985480eac024debf7a12859853bbc8d5db0acf70e6397d56c0R1-R95)`, `[[4]](diffhunk://#diff-8fafbf9bb6a9167b58d6982d2dd12d306e89aff6eeb898e4f3c32edc28e50e8fR1-R56)`, …

[#noissue] Refactor UriMetric

---

commons-server/src/main/java/com/navercorp/pinpoint/common/server/metric/dao/TableNameManager.java

This pull request includes changes to the `TableNameManager` class in the `commons-server` module to simplify and optimize string operations.
String operation optimizations:
* [`commons-server/src/main/java/com/navercorp/pinpoint/common/server/metric/dao/TableNameManager.java`](diffhunk://#diff-4d01da3616a88aac0dd9f9fecd62a4f20114995fbcf70d6d5a2fc1c966157bc9L34-R41): Simplified the `numberFormat` initialization by removing an unnecessary conversion to `String.valueOf` and directly concatenating `paddingLength`.
* [`commons-server/src/main/java/com/navercorp/pinpoint/common/server/metric/dao/TableNameManager.java`](diffhunk://#diff-4d01da3616a88aac0dd9f9fecd62a4f20114995fbcf70d6d5a2fc1c966157bc9L34-R41): Replaced the `StringBuilder` usage with the `concat` method for combining …

[#noissue] Cleanup TableNameManager

---

batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/ErrorCountToCalleCheckerTest.java
batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/ErrorRateToCalleCheckerTest.java
batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/SlowCountToCalleCheckerTest.java
batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/SlowRateToCalleCheckerTest.java
batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/TotalCountToCalleeCheckerTest.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/map/VirtualLinkMarker.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/map/processor/RpcCallProcessor.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/rawdata/LinkData.java

This pull request includes several changes aimed at improving the creation and management of `LinkData` objects across various classes and test files. The main change involves replacing the constructor and setter methods with a new static factory method `LinkData.copyOf`. This simplifies the creation of `LinkData` objects and ensures that all necessary fields are properly initialized.
* [`web/src/main/java/com/navercorp/pinpoint/web/applicationmap/rawdata/LinkData.java`](diffhunk://#diff-19d8236941a2aac174642a84d0f2f67eb50e7a671424886babf675fd883b0727R40-R44): Added a new static factory method `LinkData.copyOf` to create `LinkData` objects, ensuring all required fields are initialized. [[1]](diffhunk://#diff-19d8236941a2aac174642a84d0f2f67eb50e7a671424886babf675fd883b0727R40-R44) …

[#noissue] Refactor LinkData

---

web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/ResponseTimeViewModel.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/TimeCount.java

This pull request includes changes to the `ResponseTimeViewModel` and `TimeCount` classes in the `web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view` directory. The main focus of these changes is to move the `TimeCountSerializer` class from `ResponseTimeViewModel` to `TimeCount`.
Codebase refactoring:
* [`web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/ResponseTimeViewModel.java`](diffhunk://#diff-0583550101538bae322268a6f4ca803988fff9722460b572283e58e4b9f951ebL20-L24): Removed the `TimeCountSerializer` class and its associated imports. [[1]](diffhunk://#diff-0583550101538bae322268a6f4ca803988fff9722460b572283e58e4b9f951ebL20-L24) [[2]](diffhunk://#diff-0583550101538bae322268a6f4ca803988fff9722460b572283e58e4b9f951ebL51-L60)
* …

[#noissue] Cleanup TimeCount

---

web/src/main/java/com/navercorp/pinpoint/web/applicationmap/link/Link.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/LinkView.java

This pull request includes changes to the `Link` and `LinkView` classes to improve the handling of the `TimeHistogramFormat` parameter. The most significant changes include removing the `timeHistogramFormat` instance variable from the `Link` class and modifying methods to accept `TimeHistogramFormat` as a parameter.
Improvements to `Link` class:
* [`web/src/main/java/com/navercorp/pinpoint/web/applicationmap/link/Link.java`](diffhunk://#diff-382ee40347acc7118a25c093dd4f1a4bbb9926b7ed06845106a10477baa64267L68): Removed the `timeHistogramFormat` instance variable and the associated setter method. Modified the `getSourceAgentTimeSeriesHistogram` method to accept `TimeHistogramFormat` as a parameter. [[1]](diffhunk://#diff-382ee40347acc7118a25c093dd4f1a4bbb9926b7ed06845106a10477baa64267L68) …

[#noissue] Remove unused TimeHistogramFormat in Link

---

web/src/main/java/com/navercorp/pinpoint/web/applicationmap/histogram/AgentTimeHistogramBuilder.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/histogram/Histogram.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/ResponseTimeViewModelBuilder.java

This pull request includes several changes to the histogram-related classes in the `web/src/main/java/com/navercorp/pinpoint/web/applicationmap/histogram` package. The changes primarily focus on removing the `SlotType` class usage and replacing it with more direct method calls. Additionally, some refactoring has been done to simplify the code and improve readability.
Refactoring and simplification:
* Removed the `getCount` method from `AgentTimeHistogramBuilder` and `Histogram` classes, which used `SlotType` to determine counts. [[1]](diffhunk://#diff-ebd1826dd2f87e5ef6e9b97802b498f67abe764e307cf6c533c05ceb3918d9e6L106-L110) [[2]](diffhunk://#diff-b6796c0a6da03afccc24ff7d41ca98444feb14dbe1cc93c4fe7e4a5bee1dca46L221-L241)
* Replaced `SlotType` usage with direct method references in …

[#noissue] Refactor ResponseTimeViewModelBuilder

---

web-frontend/src/main/v3/packages/ui/package.json
web-frontend/src/main/v3/yarn.lock

Solve this warning.
```
ReferenceLine: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
```

[#noissue] Update rechart version

---

web/src/main/java/com/navercorp/pinpoint/web/applicationmap/ApplicationMapBuilder.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/appender/server/DefaultServerGroupListFactory.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/appender/server/DefaultServerInfoAppender.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/appender/server/EmptyServerGroupListFactory.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/appender/server/ServerGroupListFactory.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/appender/server/StatisticsServerGroupListFactory.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/appender/server/datasource/AgentInfoServerGroupListDataSource.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/appender/server/datasource/ServerGroupListDataSource.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/service/ResponseTimeHistogramServiceImpl.java
web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoServiceImpl.java
web/src/main/java/com/navercorp/pinpoint/web/service/ApplicationAgentListServiceImpl.java
web/src/main/java/com/navercorp/pinpoint/web/vo/agent/AgentStatusQuery.java
web/src/test/java/com/navercorp/pinpoint/web/applicationmap/appender/server/ServerInfoAppenderTest.java
web/src/test/java/com/navercorp/pinpoint/web/applicationmap/service/ResponseTimeHistogramServiceImplTest.java
web/src/test/java/com/navercorp/pinpoint/web/dao/hbase/HbaseAgentLifeCycleDaoTest.java

This pull request includes several changes to the `pinpoint` project, focusing on replacing the use of `Instant` with `long` for timestamp handling across various classes and methods. This change aims to simplify the timestamp management and improve consistency throughout the codebase. The most important changes include modifications to method signatures, imports, and related test cases.
* [`web/src/main/java/com/navercorp/pinpoint/web/applicationmap/ApplicationMapBuilder.java`](diffhunk://#diff-7105bb67aa47b306a56c96658af4d2b98e9066b0f6c419c551e79b5f212dbddcL85-R85): Updated `createWasNodeInstanceList` method to use `long` instead of `Instant` for the timestamp parameter.
* [`web/src/main/java/com/navercorp/pinpoint/web/applicationmap/appender/server/DefaultServerGroupListFactory.java`](d …

[#nouissue] Refactor timestamp handling

---

commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/json/JsonFields.java
web/src/main/java/com/navercorp/pinpoint/web/calltree/span/NodeList.java
web/src/test/java/com/navercorp/pinpoint/web/calltree/span/NodeListTest.java

This pull request updates the `JsonFields` class to improve iterator performance by replacing the stream-based iterator with an array-based iterator.
Performance improvement:
* [`commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/json/JsonFields.java`](diffhunk://#diff-a696fe156632a210dbea72bf06217320b7cf4884dd05b07c0007089a65b891d9L45-R46): Replaced the `iterator` method's implementation to use `Iterators.forArray(fields)` instead of `stream().iterator()` for better performance. This change leverages Guava's `Iterators` utility.
* [`commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/json/JsonFields.java`](diffhunk://#diff-a696fe156632a210dbea72bf06217320b7cf4884dd05b07c0007089a65b891d9R7): Added an import for `com.google.common.collect.Iterators` …

[#noissue] Refactor iterator in JsonFields to use Iterators.forArray

---

web/src/main/java/com/navercorp/pinpoint/web/calltree/span/NodeList.java
web/src/main/java/com/navercorp/pinpoint/web/calltree/span/SpanAligner.java
web/src/test/java/com/navercorp/pinpoint/web/calltree/span/NodeListTest.java

This pull request refactors the `NodeList` class to improve immutability and simplify its usage, updates related logic in `SpanAligner`, and adjusts the corresponding test cases. It also includes a minor import reordering in `SpanAligner`.
* Introduced a static `EMPTY` instance of `NodeList` for representing empty lists, replacing direct instantiation with `Collections.emptyList()` in multiple places. (`[[1]](diffhunk://#diff-e7ca746e462e44b26eed06f0a8f7a43462408ff0c28c6697f28b95b16dc714fcR21-R47)`, `[[2]](diffhunk://#diff-e7ca746e462e44b26eed06f0a8f7a43462408ff0c28c6697f28b95b16dc714fcL78-R87)`)
* Added a new static factory method `NodeList.of()` to create `NodeList` instances, ensuring null checks and reusing the `EMPTY` instance when applicable. …

[#noissue] Improve empty list handling in NodeList

---

commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/ApplicationMapStatisticsUtils.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/UserNodeUtils.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/FilteredMapController.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/mapper/InLinkMapper.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/map/FilteredMapBuilder.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/service/FilteredMapServiceImpl.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/service/FilteredMapServiceOption.java
web/src/main/java/com/navercorp/pinpoint/web/controller/BusinessTransactionController.java
web/src/test/java/com/navercorp/pinpoint/web/TestTraceUtils.java
web/src/test/java/com/navercorp/pinpoint/web/applicationmap/map/FilteredMapBuilderTest.java
web/src/test/java/com/navercorp/pinpoint/web/applicationmap/service/FilteredMapServiceImplTest.java

This pull request introduces several changes aimed at improving code clarity, reducing complexity, and deprecating outdated methods. The most significant updates include the removal of the `viewVersion` parameter across multiple classes, the introduction of the `UserNodeUtils` utility class, and the refactoring of methods to use this new utility. These changes help streamline the codebase and enhance maintainability.
* Added the `UserNodeUtils` utility class with a `newUserNodeName` method to generate user node names by combining application name and service type. This replaces the older logic scattered across the codebase. (`commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/UserNodeUtils.java`)
* Deprecated the `getDestApplicationNameFromColumnNameForUser` method in …

[#noissue] Remove viewVersion from FilteredMap

---

web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/LinkView.java

This pull request refactors the handling of agent histograms in the `LinkView` class to simplify the code and improve maintainability. The changes primarily involve replacing the use of the `AgentHistogramList` wrapper with a direct `Collection<AgentHistogram>` and updating related methods accordingly.
* Removed the unused import for `AgentHistogramList` in `LinkView.java`, as the class is no longer utilized.
* Updated the `serialize` method to replace calls to `AgentHistogramList` methods with direct usage of `Collection<AgentHistogram>`. This change simplifies the logic for handling source and target histograms and response statistics.
* Refactored the `writeAgentResponseStatistics` and `writeAgentHistogram` methods to accept a `Collection<AgentHistogram>` instead of an …

[#noissue] Refactor LinkView

---

web/src/main/java/com/navercorp/pinpoint/web/applicationmap/histogram/ApplicationTimeHistogram.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/histogram/NodeHistogram.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/link/Link.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/LinkHistogramSummaryView.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/LinkView.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/NodeHistogramSummaryView.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/NodeView.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/TimeHistogramBuilder.java
web/src/test/java/com/navercorp/pinpoint/web/applicationmap/histogram/AgentTimeHistogramTest.java
web/src/test/java/com/navercorp/pinpoint/web/applicationmap/histogram/ApplicationTimeHistogramTest.java
web/src/test/java/com/navercorp/pinpoint/web/applicationmap/service/FilteredMapServiceImplTest.java
web/src/test/java/com/navercorp/pinpoint/web/view/LinkViewTest.java

This pull request refactors how `TimeHistogramViewModel` objects are created by removing the `createViewModel` methods from histogram classes and centralizing the logic in the `TimeHistogramBuilder` class. It also updates the codebase to use the new `TimeHistogramBuilder` approach consistently across all relevant components and tests.
* Removed the `createViewModel` methods from `ApplicationTimeHistogram` and `AgentTimeHistogram` classes, and introduced a new `build` method in `TimeHistogramBuilder` to handle the creation of `TimeHistogramViewModel` objects. (`[[1]](diffhunk://#diff-0853178934b25eb0f0aae7bdbcd3d3b3667133360556fa485b8fcd180b968940L43-R42)`, `[[2]](diffhunk://#diff-382ee40347acc7118a25c093dd4f1a4bbb9926b7ed06845106a10477baa64267L206-R196)`, …

[#noissue] Extract HistogramFormat in Link

---

batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/ApdexScoreCheckerTest.java
batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/ErrorCountCheckerTest.java
batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/ErrorRateCheckerTest.java
batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/ResponseCountCheckerTest.java
batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/SlowCountCheckerTest.java
batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/SlowRateCheckerTest.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/mapper/ResponseTimeMapper.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/map/FilteredMapBuilder.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/service/FilteredMapServiceImpl.java
web/src/main/java/com/navercorp/pinpoint/web/vo/ResponseHistograms.java
web/src/main/java/com/navercorp/pinpoint/web/vo/ResponseTime.java
web/src/test/java/com/navercorp/pinpoint/web/applicationmap/ApplicationMapBuilderTest.java
web/src/test/java/com/navercorp/pinpoint/web/applicationmap/dao/mapper/ResponseTimeMapperTest.java
web/src/test/java/com/navercorp/pinpoint/web/applicationmap/histogram/AgentTimeHistogramTest.java
web/src/test/java/com/navercorp/pinpoint/web/applicationmap/histogram/ApplicationTimeHistogramTest.java
web/src/test/java/com/navercorp/pinpoint/web/applicationmap/map/FilteredMapBuilderTest.java
web/src/test/java/com/navercorp/pinpoint/web/applicationmap/service/FilteredMapServiceImplTest.java
web/src/test/java/com/navercorp/pinpoint/web/applicationmap/service/ResponseTimeHistogramServiceImplTest.java
web/src/test/java/com/navercorp/pinpoint/web/service/ApdexScoreServiceImplTest.java
web/src/test/java/com/navercorp/pinpoint/web/service/ApplicationAgentListServiceImplTest.java
web/src/test/java/com/navercorp/pinpoint/web/vo/ResponseHistogramsTest.java

This pull request refactors the handling of time ranges in the application map and response histogram components by replacing the `Range` and `TimeWindowDownSampler` classes with the `TimeWindow` class. The changes improve consistency and simplify the codebase. Additionally, a helper method for error determination was introduced in the `ResponseHistograms.Builder` class.
* **Replaced `Range` and `TimeWindowDownSampler` with `TimeWindow` in constructors and methods:**
- Updated the `FilteredMapBuilder` constructor to accept a `TimeWindow` object instead of a `Range` and removed the use of `TimeWindowDownSampler`. (`FilteredMapBuilder.java`, [web/src/main/java/com/navercorp/pinpoint/web/applicationmap/map/FilteredMapBuilder.javaL80-R84](diffhunk://#diff-391cf5eafd5e0eacd7297befcb97d98db7c673 …

[#noissue] Refactor FilteredMap

---

batch/src/test/java/com/navercorp/pinpoint/batch/alarm/checker/ApdexScoreCheckerTest.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/appender/histogram/datasource/MapApplicationResponseNodeHistogramDataSource.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/config/MapHbaseConfiguration.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/config/MapMapperConfiguration.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/MapResponseDao.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/hbase/HbaseMapResponseTimeDao.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/mapper/ApplicationResponseTimeResultExtractor.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/histogram/ApplicationHistogram.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/histogram/NodeHistogram.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/service/MapServiceImpl.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/NodeView.java

This pull request introduces a new feature for handling application-level response time histograms. It involves adding a new `ApplicationHistogram` data structure and integrating it into the existing system. The changes include updates to data access objects, configuration files, and the addition of a new mapper class for extracting histogram data. Below are the key changes grouped by theme:
* **Addition of `ApplicationHistogram` Support**: Introduced the `ApplicationHistogram` class to represent application-level response time histograms. This includes adding a new method `selectApplicationResponseTime` to the `MapResponseDao` interface and its implementation in `HbaseMapResponseTimeDao`. [[1]](diffhunk://#diff-51b8ca39ea5066a374e18b76f5b8ed5b60f7e6e172ca0ebcadbfb6a62d2fa356R35) …

[#noissue] Reduced memory usage in ResponseTime

---

agent-module/agent/src/main/resources/profiles/local/pinpoint.config
agent-module/agent/src/main/resources/profiles/release/pinpoint.config
agent-module/plugins/aws-sdk-s3/src/main/java/com/navercorp/pinpoint/plugin/aws/sdk/s3/AwsSdkS3PluginConfig.java

[#12455] Update s3 client error mark

---

agent-module/plugins/cubrid-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/cubrid/CubridJdbcUrlParser.java
agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/ClassFileTransformerProvider.java
agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMMethodInsnNodeRemapper.java
agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/jdbc/BindValueUtils.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/HbaseMapInLinkDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/HbaseMapOutLinkDao.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/ApplicationMapStatisticsUtils.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/TransactionIdParser.java
commons/src/main/java/com/navercorp/pinpoint/common/util/StringUtils.java
commons/src/test/java/com/navercorp/pinpoint/common/util/StringUtilsTest.java
exceptiontrace/exceptiontrace-common/src/main/java/com/navercorp/pinpoint/exceptiontrace/common/model/ExceptionMetaData.java
exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/mapper/ExceptionEntityMapper.java
exceptiontrace/exceptiontrace-web/src/main/java/com/navercorp/pinpoint/exceptiontrace/web/view/ExceptionChartValueView.java
inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/definition/MetricDefinition.java
inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/definition/metric/field/Field.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/mapper/InLinkMapper.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/map/FilteredMapBuilder.java
web/src/main/java/com/navercorp/pinpoint/web/vo/activethread/AgentActiveThreadCountList.java
web/src/main/java/com/navercorp/pinpoint/web/vo/callstacks/ExceptionRecord.java
web/src/main/java/com/navercorp/pinpoint/web/vo/callstacks/ParameterRecord.java
web/src/main/java/com/navercorp/pinpoint/web/vo/tree/ApplicationAgentHostList.java

[#noissue] Replace StringUtils.defaultString with Objects.toString for null handling

---

web/src/main/java/com/navercorp/pinpoint/web/applicationmap/service/MapServiceImpl.java

This pull request refactors the `MapServiceImpl` class in `web/src/main/java/com/navercorp/pinpoint/web/applicationmap/service/MapServiceImpl.java` to improve code readability and modularity. Key changes include introducing a new method for handling cases with no request data, simplifying method signatures, and modifying factory methods to accept boolean parameters instead of `MapServiceOption`.
* **Introduced `buildForNoRequest` method**: Added a private method to handle scenarios where no nodes are found in the application map, ensuring the map is still built with the source application. This improves readability and encapsulates logic.
* **Refactored `newNodeHistogramFactory` method**: Changed the method to accept a boolean parameter (`isSimpleResponseHistogram`) instead of the entire …

[#12434] Add Node Interpolation

---

inspector-module/inspector-commons/src/main/java/com/navercorp/pinpoint/common/dao/pinot/MultiValueTagTypeHandler.java
metric-module/metric-commons/src/main/java/com/navercorp/pinpoint/metric/common/util/TagUtils.java

This pull request refactors the handling of JSON and tag processing in the `MultiValueTagTypeHandler` and `TagUtils` classes to improve performance and simplify code. The most important changes include replacing `ObjectMapper` with `ObjectReader` for JSON deserialization, optimizing list initialization, and replacing `Stream`-based operations with more efficient alternatives.
* Replaced `ObjectMapper` with `ObjectReader` in `MultiValueTagTypeHandler` for deserializing lists of strings, reducing overhead and improving performance. (`[[1]](diffhunk://#diff-cec10858ce67887378c3949a9d50d4feab3501b3cb74236188936e6cd5a85215L20-R21)`, `[[2]](diffhunk://#diff-cec10858ce67887378c3949a9d50d4feab3501b3cb74236188936e6cd5a85215L33-R39)`, `[[3]](diffhunk://#diff-cec10858ce67887378c3949a9d50d4feab3501b3c …

[#noissue] Optimize TagUtils

---

metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/collector/controller/TelegrafMetricController.java
metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/collector/model/TelegrafMetric.java
metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/collector/service/SystemMetricDataTypeService.java
metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/collector/service/SystemMetricDataTypeServiceImpl.java
metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/collector/service/SystemMetricService.java
metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/collector/service/SystemMetricTagServiceImpl.java
metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/common/model/DoubleMetric.java
metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/common/model/MetricDataName.java
metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/common/model/MetricTagKey.java
metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/common/model/Metrics.java
metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/common/model/SystemMetric.java
metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/service/SystemMetricDataServiceImpl.java
metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/service/SystemMetricHostInfoServiceImpl.java
metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/util/TagListUtils.java
metric-module/metric/src/test/java/com/navercorp/pinpoint/metric/collector/controller/TelegrafMetricControllerTest.java
metric-module/metric/src/test/java/com/navercorp/pinpoint/metric/collector/service/SystemMetricDataTypeServiceImplTest.java
metric-module/metric/src/test/java/com/navercorp/pinpoint/metric/collector/service/SystemMetricFilterTest.java
metric-module/metric/src/test/java/com/navercorp/pinpoint/metric/collector/service/SystemMetricTagServiceImplTest.java
metric-module/metric/src/test/java/com/navercorp/pinpoint/metric/common/model/validation/TelegrafMetricsValidatorTest.java
metric-module/metric/src/test/java/com/navercorp/pinpoint/metric/web/util/TagListUtilsTest.java

This pull request introduces significant changes to the `TelegrafMetricController` and related classes to improve performance, simplify code, and enhance maintainability. Key updates include replacing `SystemMetric` with `DoubleMetric` as the primary metric type, refactoring stream-based operations into iterative ones, and optimizing tag handling. Additionally, the code now uses Java `record` for the `Field` class and includes other minor improvements.
* Replaced `SystemMetric` with `DoubleMetric` as the primary metric type across the codebase, including updates to `SystemMetricDataTypeService` and `SystemMetricService` to reflect this change. (`[[1]](diffhunk://#diff-e88561a7bde1943722d053bfd071588018635fc24957d5d5e35a9da7c759ca76L19-R26)`, …

[#noissue] Refactor SystemMetric

---

channel/src/main/java/com/navercorp/pinpoint/channel/ChannelSpringConfig.java
channel/src/main/java/com/navercorp/pinpoint/channel/serde/JacksonSerde.java
channel/src/main/java/com/navercorp/pinpoint/channel/serde/JacksonSerdeFactory.java
channel/src/main/java/com/navercorp/pinpoint/channel/serde/JsonSerdeFactory.java
channel/src/test/java/com/navercorp/pinpoint/channel/ChannelSpringConfigTest.java
channel/src/test/java/com/navercorp/pinpoint/channel/serde/JacksonSerdeTest.java
channel/src/test/java/com/navercorp/pinpoint/channel/service/ChannelServiceProtocolTest.java
channel/src/test/java/com/navercorp/pinpoint/channel/service/FluxChannelServiceTest.java
channel/src/test/java/com/navercorp/pinpoint/channel/service/MonoChannelServiceTest.java
log/log-common/src/main/java/com/navercorp/pinpoint/log/LogServiceProtocolConfig.java
log/log-web/src/main/java/com/navercorp/pinpoint/log/web/websocket/LogWebSocketConfig.java
realtime/realtime-common/src/main/java/com/navercorp/pinpoint/realtime/config/ATCServiceProtocolConfig.java
realtime/realtime-common/src/main/java/com/navercorp/pinpoint/realtime/config/ATDServiceProtocolConfig.java
realtime/realtime-common/src/main/java/com/navercorp/pinpoint/realtime/config/EchoServiceProtocolConfig.java
realtime/realtime-common/src/main/java/com/navercorp/pinpoint/realtime/serde/ClusterKeyDeserializer.java
realtime/realtime-common/src/test/java/com/navercorp/pinpoint/realtime/serde/ClusterTest.java
realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/activethread/count/WebActiveThreadCountConfig.java
realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/activethread/count/websocket/RedisActiveThreadCountWebSocketHandler.java

This pull request introduces significant improvements to the serialization and deserialization (serde) infrastructure, replacing the direct use of `ObjectMapper` with a new `JsonSerdeFactory` abstraction. This change enhances modularity, testability, and reusability across the codebase. Key changes include the introduction of `JacksonSerdeFactory` and `JsonSerdeFactory` interfaces, refactoring of the `JacksonSerde` class, and updates to tests and configurations to use the new factory-based approach.
* **Introduction of `JsonSerdeFactory` and `JacksonSerdeFactory`:**
- Added `JsonSerdeFactory` interface to define a contract for serde creation. (`channel/src/main/java/com/navercorp/pinpoint/channel/serde/JsonSerdeFactory.java`)
- Implemented `JacksonSerdeFactory` to encapsulate …

[#noissue] Refactor JacksonSerde

---

web/src/main/java/com/navercorp/pinpoint/web/dao/ApplicationTraceIndexDao.java
web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseApplicationTraceIndexDao.java
web/src/main/java/com/navercorp/pinpoint/web/service/HeatMapService.java
web/src/main/java/com/navercorp/pinpoint/web/service/HeatMapServiceImpl.java

This pull request focuses on removing deprecated methods and improving compatibility handling in the `HeatMapServiceImpl` class. The most significant changes include the removal of outdated methods from multiple interfaces and classes, the introduction of a compatibility filtering mechanism for legacy data, and the replacement of stream-based operations with iterative approaches for better clarity and control.
* Removed the `scanScatterData` method from the `ApplicationTraceIndexDao` interface and its implementation in `HbaseApplicationTraceIndexDao`. This method was marked as deprecated and is no longer needed. [[1]](diffhunk://#diff-fff68d60d2cdc2a35bc9df144d6952b8ef0a135b5749c7428f75abc24164741cL44-L47) [[2]](diffhunk://#diff-8cc454aac6e5632f331fb44261c836529e35a9b92f21ac2452bc277fc110d …

[#noissue] Remove deprecated API in HeatMapService

---

collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/HbaseMapInLinkDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/HbaseMapOutLinkDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/service/HbaseTraceService.java

This pull request includes changes to improve logging consistency and introduce a new constant for queue merging in the `collector` module. The most important changes involve formatting updates to debug logs for better readability and the addition of the `MERGE_QUEUE` constant to enhance queue-related functionality.
* Updated debug log formats in `HbaseMapInLinkDao.java` and `HbaseMapOutLinkDao.java` to use consistent `{}/{}/...` patterns for better readability and uniformity. (`[[1]](diffhunk://#diff-d76d17c39980e928a6f9a494cb5a559f60cd97ff34ab37514663f1858290dacfL75-R75)`, `[[2]](diffhunk://#diff-d76d17c39980e928a6f9a494cb5a559f60cd97ff34ab37514663f1858290dacfL84-R84)`, `[[3]](diffhunk://#diff-4b07ea846dfc607b73cacf60ac8f045ab8ac879a205654de45731ec9f1d2db80L71-R71)`)
* Enhanced debug …

[#12434] Change Queue Link to application stats

---

collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/Vertex.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/HostApplicationMapDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/MapInLinkDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/MapOutLinkDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/MapResponseTimeDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/HbaseHostApplicationMapDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/HbaseMapInLinkDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/HbaseMapOutLinkDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/HbaseMapResponseTimeDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/service/LinkService.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/service/LinkServiceImpl.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/InLinkColumnName.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/LinkRowKey.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/OutLinkColumnName.java
collector/src/main/java/com/navercorp/pinpoint/collector/service/HbaseTraceService.java
collector/src/test/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/HbaseHostApplicationMapDaoTest.java

This pull request introduces a new `Vertex` class to simplify and standardize the representation of application and service type pairs across the codebase. It refactors multiple DAO interfaces and their implementations to use the `Vertex` class, replacing separate parameters for application names and service types. This improves code readability, reduces redundancy, and ensures consistency in handling application-service pairs.
* **Creation of `Vertex` class**: Introduced a new `Vertex` record in `collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/Vertex.java`. This class encapsulates `applicationName` and `serviceType` with validation and utility methods.
* **Refactored DAO interfaces**:
- Updated `HostApplicationMapDao`, `MapInLinkDao`, `MapOutLinkDao`, and …

[#12434] Refactor ServerMap

---

commons-buffer/src/test/java/com/navercorp/pinpoint/common/util/BytesUtilsTest.java
commons/src/main/java/com/navercorp/pinpoint/common/util/BytesUtils.java

This pull request updates the `BytesUtils` utility class and its corresponding test suite to improve exception handling and validation messages. The changes ensure that the exception message for out-of-range errors provides accurate information and adds a test case to verify this behavior.
* [`commons/src/main/java/com/navercorp/pinpoint/common/util/BytesUtils.java`](diffhunk://#diff-7ef761358947bcfc5f43ab6e136ff008a2d69a1da0fbc7b8dfdd59451fc6cbdfL402-R402): Corrected the exception message in the `checkFromIndexSize` method to accurately reflect the out-of-range index by using `(fromIndex + size)` instead of `fromIndex + size`.
* [`commons-buffer/src/test/java/com/navercorp/pinpoint/common/util/BytesUtilsTest.java`](diffhunk://#diff-d8b6c643a0e840b66ca4be6a6bf030d4177b52d7eac8f3f81150e0df9 …

[#noissue] Fix ArrayIndexOutOfBoundsException message in BytesUtils

---

collector/src/main/resources/pinpoint-collector-root.properties
web/src/main/resources/pinpoint-web-root.properties

This pull request updates configuration files to include `server.port` in the `pinpoint.banner.configs` property, improving the visibility of server port settings in both the collector and web modules.
Configuration updates:
* [`collector/src/main/resources/pinpoint-collector-root.properties`](diffhunk://#diff-1dcf31a1cf7f6c97c78434f660ba8086e56a737bc1da37f3c120fd35951f3112R93): Added `server.port` to the `pinpoint.banner.configs` property to enhance configuration clarity for the collector module.
* [`web/src/main/resources/pinpoint-web-root.properties`](diffhunk://#diff-c03bc17fc54b79933f6832f97a718e5b9e4f557abd75c2610ba3e6a68a541c66R110): Added `server.port` to the `pinpoint.banner.configs` property to enhance configuration clarity for the web module.

[#12617] Add server.port to PinpointSpringBanner

---

commons-profiler/src/main/java/com/navercorp/pinpoint/common/profiler/sql/DefaultSqlNormalizer.java
commons-profiler/src/main/java/com/navercorp/pinpoint/common/profiler/sql/OutputParameterParser.java
commons-profiler/src/main/java/com/navercorp/pinpoint/common/profiler/sql/ParameterBuilder.java
commons-profiler/src/main/java/com/navercorp/pinpoint/common/profiler/sql/ParserContext.java
commons-profiler/src/main/java/com/navercorp/pinpoint/common/profiler/sql/Tokens.java
commons-profiler/src/test/java/com/navercorp/pinpoint/common/profiler/sql/DefaultSqlNormalizerTest.java
commons-profiler/src/test/java/com/navercorp/pinpoint/common/profiler/sql/ParameterBuilderTest.java

This pull request refactors the SQL normalization logic in the `DefaultSqlNormalizer` class and its related components to simplify and modularize the code. The key changes include delegating parsing responsibilities to a new `ParserContext` class, removing redundant methods, and improving code readability by reusing helper methods.
* Replaced the manual parsing logic in `DefaultSqlNormalizer` with a new `ParserContext` class, delegating the `normalizeSql` method's parsing responsibilities to `ParserContext.parse()` for cleaner and more maintainable code. (`commons-profiler/src/main/java/com/navercorp/pinpoint/common/profiler/sql/DefaultSqlNormalizer.java`)
* Removed redundant methods like `lookAhead1`, `readLine`, and `appendOutputParam` from `DefaultSqlNormalizer`, as their functionality …

[#12622] Improved maintainability of SqlNormalizer

---

collector/src/main/java/com/navercorp/pinpoint/collector/handler/RequestResponseHandler.java
collector/src/main/java/com/navercorp/pinpoint/collector/handler/grpc/GrpcAgentInfoHandler.java
collector/src/main/java/com/navercorp/pinpoint/collector/handler/grpc/GrpcApiMetaDataHandler.java
collector/src/main/java/com/navercorp/pinpoint/collector/handler/grpc/GrpcExceptionMetaDataHandler.java
collector/src/main/java/com/navercorp/pinpoint/collector/handler/grpc/GrpcSqlMetaDataHandler.java
collector/src/main/java/com/navercorp/pinpoint/collector/handler/grpc/GrpcSqlUidMetaDataHandler.java
collector/src/main/java/com/navercorp/pinpoint/collector/handler/grpc/GrpcStringMetaDataHandler.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/AgentService.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/MetadataService.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/SpanService.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/StatService.java
collector/src/main/java/com/navercorp/pinpoint/io/util/MessageType.java
collector/src/main/java/com/navercorp/pinpoint/io/util/MessageTypes.java
collector/src/test/java/com/navercorp/pinpoint/collector/receiver/grpc/AgentServerTestMain.java
collector/src/test/java/com/navercorp/pinpoint/io/util/MessageTypeTest.java

This pull request refactors the handling of `MessageType` across multiple classes in the `collector` module and updates copyright years. The primary changes involve removing the `type()` method from handler classes and replacing direct references to `MessageType` with `MessageTypes` in service classes.
* Removed the `type()` method from the `RequestResponseHandler` interface and its implementing classes, including `GrpcAgentInfoHandler`, `GrpcApiMetaDataHandler`, `GrpcExceptionMetaDataHandler`, `GrpcSqlMetaDataHandler`, `GrpcSqlUidMetaDataHandler`, and `GrpcStringMetaDataHandler`. These methods previously returned specific `MessageType` values. [[1]](diffhunk://#diff-f0c7312916df544585a34a8d6edbf165c1527f56590b43b345ae734da5130104L21-L30) …

[#noissue] Update enum for MessageType

---

commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseTemplate.java
commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/LazyResultSizeHandler.java
commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/LimitRowMapperResultsExtractor.java
commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/ResultSizeHandlers.java
commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/RowTypeHint.java
commons-hbase/src/test/java/com/navercorp/pinpoint/common/hbase/limit/ResultSizeHandlersTest.java
web/src/main/java/com/navercorp/pinpoint/web/mapper/TraceIndexMetaScatterMapper.java
web/src/main/java/com/navercorp/pinpoint/web/mapper/TraceIndexScatterMapper.java
web/src/main/java/com/navercorp/pinpoint/web/mapper/TransactionIdMapper.java

This pull request introduces several changes to enhance the functionality and maintainability of the HBase-related codebase, focusing on improving result size handling, adding type hints for row mappers, and updating copyright information. The most significant updates include the addition of `ResultSizeHandlers` and `LazyResultSizeHandler` for dynamic result size computation, integration of the `RowTypeHint` interface for type-specific row mapping, and refactoring `LimitRowMapperResultsExtractor` to leverage these new utilities.
* **`commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/ResultSizeHandlers.java`:** Added a utility class to provide dynamic and type-specific result size computation for collections, maps, arrays, and default objects.
* …

[#noissue] Refactor LimitRowMapperResultsExtractor

---

collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/HbaseHostApplicationMapDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/DefaultBulkWriter.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/SyncWriter.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/encode/ApplicationIndexRowKeyEncoder.java
collector/src/test/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/HbaseHostApplicationMapDaoTest.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/RowKeyEncoder.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/metadata/MetadataEncoder.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/metadata/uid/UidMetadataEncoder.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/trace/v2/TraceRowKeyEncoderV2.java

This pull request refactors the usage of the `ByteSaltKey` class across multiple files and replaces it with the more generic `SaltKey` interface. This change aims to improve code consistency and flexibility by standardizing the interface used for salt key operations. The changes primarily affect method signatures, constants, and imports.
* Replaced `ByteSaltKey` with `SaltKey` in constants and method signatures across several classes, including `HbaseHostApplicationMapDao`, `DefaultBulkWriter`, `SyncWriter`, and various row key encoder classes. (`[[1]](diffhunk://#diff-67d647f20220b276cc88a58eac5ed57e1ad56d906395e43b74d5111517c21ab0L56-R57)`, `[[2]](diffhunk://#diff-67d647f20220b276cc88a58eac5ed57e1ad56d906395e43b74d5111517c21ab0L137-R138)`, …

[#noissue] Refactor to replace ByteSaltKey with SaltKey

---

collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/HbaseHostApplicationMapDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/DefaultBulkWriter.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/LinkRowKey.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/RowKey.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/RowKeyMerge.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/SyncWriter.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/encode/ApplicationIndexRowKeyEncoder.java
collector/src/test/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/HbaseHostApplicationMapDaoTest.java
collector/src/test/java/com/navercorp/pinpoint/collector/applicationmap/statistics/BulkIncrementerTestClazz.java
collector/src/test/java/com/navercorp/pinpoint/collector/applicationmap/statistics/SizeLimitedBulkIncrementerTest.java
collector/src/test/java/com/navercorp/pinpoint/collector/dao/hbase/encode/ApplicationIndexRowKeyEncoderTest.java
commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/wd/ByteHasher.java
commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/wd/OneByteSimpleHash.java
commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/wd/RangeDoubleHash.java
commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/wd/RangeOneByteSimpleHash.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/RowKeyEncoder.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/metadata/MetadataEncoder.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/metadata/uid/UidMetadataEncoder.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/trace/v2/TraceRowKeyEncoderV2.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/ApplicationMapStatisticsUtils.java
commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/serializer/metadata/MetadataEncoderTest.java
commons-server/src/test/java/com/navercorp/pinpoint/common/server/util/ApplicationMapStatisticsUtilsTest.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/hbase/MapScanFactory.java

This pull request refactors the handling of row key distribution by replacing the `SaltKey` and `ByteSaltKey` classes with a new `ByteHasher` interface. The changes improve code maintainability and unify the approach to row key hashing across the codebase. Key updates include replacing `SaltKey` with `ByteHasher` in various classes and methods, as well as updating test cases to align with the new implementation.
* Replaced `SaltKey` with `ByteHasher` in the `HbaseHostApplicationMapDao` class, including changes to the `createRowKey` and `createRowKey0` methods to use the `ByteHasher` interface for generating and applying salt keys. (`[[1]](diffhunk://#diff-67d647f20220b276cc88a58eac5ed57e1ad56d906395e43b74d5111517c21ab0L65-R65)`, `[[2]](diffhunk://#diff-67d647f20220b276cc88a58eac5ed57e1ad56 …

[#noissue] Refactor Hasher

---

commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/util/CellUtils.java
commons-hbase/src/test/java/com/navercorp/pinpoint/common/hbase/util/CellUtilsTest.java

This pull request introduces a new utility method for converting a cell qualifier to a `short` in the `CellUtils` class and adds corresponding unit tests. It also includes standard copyright headers for the modified files.
* Added a `qualifierToShort` method in `CellUtils` to convert a cell qualifier to a `short`. This method ensures the input cell is not null and extracts the `short` value from the qualifier array. (`commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/util/CellUtils.java`)
* Added a unit test for the `qualifierToShort` method in `CellUtilsTest` to verify its correctness using a mocked `Cell` object. (`commons-hbase/src/test/java/com/navercorp/pinpoint/common/hbase/util/CellUtilsTest.java`)
* Added Apache 2.0 license headers to `CellUtils.java` and …

[#noissue] Add qualifierToShort to CellUtils

---

commons-buffer/src/main/java/com/navercorp/pinpoint/common/buffer/ByteArrayUtils.java
commons-buffer/src/test/java/com/navercorp/pinpoint/common/buffer/ByteArrayUtilsTest.java
commons-hbase/pom.xml
commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseTemplate.java
commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/async/HbaseAsyncTemplate.java
commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/parallel/ParallelResultScanner.java
commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/parallel/ScanTask.java
commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/parallel/ScanTaskConfig.java
commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/wd/DistributedScanner.java

This pull request introduces enhancements to the `ByteArrayUtils` utility class, updates to the HBase-related components to improve scanning performance, and general maintenance changes. The most significant updates include adding a new `compare` method for byte arrays, replacing `RowKeyDistributor` with `saltKeySize` for distributed scanning, and updating copyright years.
* Added a new `compare` method to compare two byte arrays starting from a specified offset. This method uses `Arrays.compare` for efficient comparison and includes validation for null arrays and index bounds. (`commons-buffer/src/main/java/com/navercorp/pinpoint/common/buffer/ByteArrayUtils.java`, [commons-buffer/src/main/java/com/navercorp/pinpoint/common/buffer/ByteArrayUtils.javaR96-R116](diffhunk://#diff-3876cce0c604 …

[#noissue] Memory Optimization of DistributedScanner

---

commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseTemplate.java
commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/async/HbaseAsyncTemplate.java
commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/parallel/ParallelResultScanner.java
commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/wd/DistributedScanner.java
commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/wd/RowKeyDistributor.java
commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/wd/RowKeyDistributorByHashPrefix.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/metadata/MetadataDecoder.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/metadata/MetadataEncoder.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/metadata/uid/UidMetadataDecoder.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/metadata/uid/UidMetadataEncoder.java
commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/serializer/metadata/MetadataEncoderTest.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/mapper/ApplicationResponseTimeResultExtractor.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/mapper/InLinkMapper.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/mapper/OutLinkMapper.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/mapper/ResponseTimeMapper.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/mapper/ResponseTimeResultExtractor.java
web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseApplicationTraceIndexDao.java
web/src/main/java/com/navercorp/pinpoint/web/mapper/ApiMetaDataMapper.java
web/src/main/java/com/navercorp/pinpoint/web/mapper/SqlMetaDataMapper.java
web/src/main/java/com/navercorp/pinpoint/web/mapper/SqlUidMetaDataMapper.java
web/src/main/java/com/navercorp/pinpoint/web/mapper/StringMetaDataMapper.java
web/src/test/java/com/navercorp/pinpoint/web/mapper/ApiMetaDataMapperTest.java

This pull request refactors the handling of the `saltKeySize` property across multiple components in the codebase to improve clarity, maintainability, and consistency. It introduces a new `getSaltKeySize()` method in the `RowKeyDistributor` interface and updates all relevant usages to rely on this method instead of accessing the `ByteHasher` directly. Additionally, some minor cleanup and copyright updates are included.
* **Centralized `saltKeySize` Access:**
* Added `getSaltKeySize()` to the `RowKeyDistributor` interface and implemented it in `RowKeyDistributorByHashPrefix` to encapsulate access to the salt key size. (`commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/wd/RowKeyDistributor.java` - [[1]](diffhunk://#diff-f0d2576a146dbe2f072134865f7b20164beee46b7e93e73a090de80f3 …

[#noissue] Refactor Rowkey handling

---

commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseTable.java
commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseTableV2.java
commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseTables.java
commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/config/AsyncWarmup.java
commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/config/Warmup.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/hbase/HbaseHostApplicationMapDao.java

This pull request refactors the HBase table definitions in the codebase by replacing the `HbaseTable` enum with a new `HbaseTableV2` enum that implements a simplified `HbaseTable` interface. All usages of the old enum are updated to use the new version, improving code clarity and future extensibility. The changes also update copyright years and related imports.
Refactoring of HBase table definitions:
* Replaced the `HbaseTable` enum with a new `HbaseTableV2` enum implementing a `HbaseTable` interface, moving all table definitions to `HbaseTableV2` and simplifying the interface to only require a `getName()` method. (`commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseTable.java`, `commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseTableV2.java`) …

[#noissue] Extract HbaseTable interface for adding tables

---

collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/config/BulkConfiguration.java
commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/config/DistributorConfiguration.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/config/MapHbaseConfiguration.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/config/MapMapperConfiguration.java

This pull request refactors the row key distributor beans used for mapping in-link and out-link data in the application map modules. The main change is the consolidation of separate distributors for in-link and out-link data into a single `mapLinkRowKeyDistributor` bean, simplifying configuration and reducing redundancy. Additionally, references to the old distributor beans have been updated across the codebase to use the new unified bean.
**Configuration refactoring:**
* Removed the separate `mapInLinkRowKeyDistributor` and `mapOutLinkRowKeyDistributor` beans, replacing them with a single `mapLinkRowKeyDistributor` bean in `DistributorConfiguration.java`.
* Updated all usages of the in-link and out-link row key distributors in `BulkConfiguration.java`, `MapHbaseConfiguration.java`, and …

[#noissue] Remove duplicate mapLinkRowKeyDistributor

---

agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/name/v1/ObjectNameResolverV1.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/config/MapV2Configuration.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/config/MapV3Configuration.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/HbaseHostApplicationMapDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/config/BulkConfiguration.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/config/BulkFactory.java
collector/src/test/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/HbaseHostApplicationMapDaoTest.java
commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/CheckAndMax.java
commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/config/DistributorConfiguration.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/applicationmap/statistics/UidLinkRowKey.java
commons/src/main/java/com/navercorp/pinpoint/common/PinpointConstants.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/config/MapHbaseConfiguration.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/config/MapMapperConfiguration.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/config/MapV3MapperConfiguration.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/v3/InLinkV3Mapper.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/dao/v3/OutLinkV3Mapper.java

This pull request refactors the bulk writer configuration and builder logic to simplify bean creation and improve maintainability. It introduces a builder pattern for constructing `BulkWriter` instances, removes redundant beans, and updates the `CheckAndMax` class to use Java's `record` feature. Additionally, it aligns key constants in the UID mapping configuration with shared definitions.
Bulk writer configuration and builder improvements:
* Refactored `BulkConfiguration.java` to remove separate beans for `BulkIncrementer` and `BulkUpdater`, replacing them with a builder pattern for constructing `BulkWriter` beans. This reduces boilerplate and centralizes configuration logic.
* Updated `BulkFactory.java` to add a `Builder` inner class, allowing for incremental configuration of …

[#noissue] Refactor BulkWriter

---

collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/HbaseMapInLinkDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/HbaseMapOutLinkDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/HbaseMapResponseTimeDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/InLinkFactory.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/InLinkFactoryV2.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/OutLinkFactory.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/OutLinkFactoryV2.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/SelfNodeFactory.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/SelfNodeFactoryV2.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/v3/InLinkFactoryV3.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/v3/InLinkV3ColumnName.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/v3/OutLinkFactoryV3.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/v3/OutLinkV3ColumnName.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/v3/SelfNodeFactoryV3.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/InLinkV2ColumnName.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/OutLinkV2ColumnName.java
collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/statistics/ResponseColumnName.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/MapSlotUtils.java

This pull request refactors how histogram slot information is handled throughout the application map DAO layer, replacing the use of primitive `short` slot numbers with the more expressive `HistogramSlot` type. This change improves type safety, clarity, and future extensibility when dealing with histogram-related operations across various factories and DAOs.
Key changes include:
* Replaced all usages of `short` slot numbers with the `HistogramSlot` type in method signatures and implementations for histogram-related operations in `InLinkFactory`, `OutLinkFactory`, and `SelfNodeFactory` interfaces and their V2/V3 implementations. [[1]](diffhunk://#diff-71174b13dfe6083ad1ec85d15eb25c501d003b551123351468523290d2a729f7R22-R29) [[2]](diffhunk://#diff-d68a7ce0e9c4a531aa4c30cf011e93e618e53984ade84 …

[#noissue] Refactor to use HistogramSlot in application map data handling

---

collector/src/main/java/com/navercorp/pinpoint/collector/event/SpanStorePublisherImpl.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/event/ContextData.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/event/SpanChunkInsertEvent.java

This pull request refactors how span and span chunk events are handled by introducing a new `ContextData` record to encapsulate shared context information. The changes simplify event construction and decouple event classes from direct dependencies on `SpanBo` and `SpanChunkBo`. Additionally, copyright years are updated.
Core refactoring to event handling:
**Event Data Abstraction:**
* Introduced a new `ContextData` record for holding `applicationName`, `agentId`, and `startTime`, used in event classes to represent context information.
* Refactored `SpanInsertEvent` and `SpanChunkInsertEvent` to store a `ContextData` instance instead of `SpanBo` or `SpanChunkBo`, and updated their constructors and getters accordingly. [[1]](diffhunk://#diff-05e974477cc4e46127e10075918cccf22b23b872c493851129 …

[#noissue] Refactor EventPublisher
