plugins/akka-http/src/main/java/com/navercorp/pinpoint/plugin/akka/http/HttpRequestAdaptor.java

Change how acquire some variables.(rpcName, endPoint)

[#4360] Add akka-http plugin

---

collector/src/main/resources/applicationContext-collector.xml

fix executor config in collector's applicationContext

[#noissue] Fix executor config

---

collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/JvmGcDetailedBoMapper.java

fix AgentStat.jvmGcDetailed.gcNewTime error

---

agent/src/main/resources-local/pinpoint.config
agent/src/main/resources-release/pinpoint.config
agent/src/main/resources/pinpoint-real-env-lowoverhead-sample.config
commons/src/main/java/com/navercorp/pinpoint/common/trace/ServiceType.java
plugins/spring/src/main/java/com/navercorp/pinpoint/plugin/spring/async/SpringAsyncConfig.java
plugins/spring/src/main/java/com/navercorp/pinpoint/plugin/spring/async/SpringAsyncConstants.java
plugins/spring/src/main/java/com/navercorp/pinpoint/plugin/spring/async/SpringAsyncPlugin.java
plugins/spring/src/main/java/com/navercorp/pinpoint/plugin/spring/async/SpringAsyncTraceMetadataProvider.java
plugins/spring/src/main/java/com/navercorp/pinpoint/plugin/spring/async/interceptor/AsyncTaskExecutorSubmitInterceptor.java
plugins/spring/src/main/java/com/navercorp/pinpoint/plugin/spring/async/interceptor/TaskCallInterceptor.java
plugins/spring/src/main/resources/META-INF/services/com.navercorp.pinpoint.bootstrap.plugin.ProfilerPlugin
plugins/spring/src/main/resources/META-INF/services/com.navercorp.pinpoint.common.trace.TraceMetadataProvider
quickstart/agent/src/main/resources/pinpoint.config

[#4419] Add Spring Async Plugin

---

doc/installation.md
quickstart/README.Win.en.md
quickstart/README.Win.ko.md
quickstart/README.md

-Dmaven.test.skip=true -> -DskipTests=true

[#update_install_guide] Update install guide

---

agent/src/test/java/com/navercorp/pinpoint/plugin/netty/NettyIT.java

Change test java version for NettyIT

[#change_jvm7_for_test]

---

agent/src/main/resources-local/pinpoint.config
agent/src/main/resources-release/pinpoint-real-env-lowoverhead-sample.config
agent/src/main/resources-release/pinpoint.config
commons/src/main/java/com/navercorp/pinpoint/common/trace/ServiceType.java
plugins/bom/pom.xml
plugins/pom.xml
plugins/undertow/.gitignore
plugins/undertow/pom.xml
plugins/undertow/src/main/java/com/navercorp/pinpoint/plugin/undertow/HttpServerExchangeParameterExtractor.java
plugins/undertow/src/main/java/com/navercorp/pinpoint/plugin/undertow/MethodFilterExtractor.java
plugins/undertow/src/main/java/com/navercorp/pinpoint/plugin/undertow/ParameterRecorderFactory.java
plugins/undertow/src/main/java/com/navercorp/pinpoint/plugin/undertow/UndertowAsyncListener.java
plugins/undertow/src/main/java/com/navercorp/pinpoint/plugin/undertow/UndertowConfig.java
plugins/undertow/src/main/java/com/navercorp/pinpoint/plugin/undertow/UndertowConstants.java
plugins/undertow/src/main/java/com/navercorp/pinpoint/plugin/undertow/UndertowHttpHeaderFilter.java
plugins/undertow/src/main/java/com/navercorp/pinpoint/plugin/undertow/UndertowPlugin.java
plugins/undertow/src/main/java/com/navercorp/pinpoint/plugin/undertow/UndertowTypeProvider.java
plugins/undertow/src/main/java/com/navercorp/pinpoint/plugin/undertow/interceptor/ConnectorsExecuteRootHandlerInterceptor.java
plugins/undertow/src/main/java/com/navercorp/pinpoint/plugin/undertow/interceptor/HttpServerExchangeAdaptor.java
plugins/undertow/src/main/java/com/navercorp/pinpoint/plugin/undertow/interceptor/HttpServletRequestImplStartAsyncInterceptor.java
plugins/undertow/src/main/resources/META-INF/services/com.navercorp.pinpoint.bootstrap.plugin.ProfilerPlugin
plugins/undertow/src/main/resources/META-INF/services/com.navercorp.pinpoint.common.trace.TraceMetadataProvider

[#1563] Add undertow plugin

---

plugins/spring/src/main/java/com/navercorp/pinpoint/plugin/spring/async/SpringAsyncConfig.java

Remove duplicated async task executor

[#noissue] Fix Spring async config

---

plugins/pom.xml

[#noissue] cleanup pom

---

plugins/undertow/src/main/java/com/navercorp/pinpoint/plugin/undertow/interceptor/ConnectorsExecuteRootHandlerInterceptor.java

[#1563] Fix undertow plugin

---

bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/SpanRecursiveAroundInterceptor.java

[#4474] Fix dubbo recursive invoke case

---

plugins/akka-http/clover.license
plugins/kafka/clover.license

[#noissue] cleanup clover license

---

profiler/src/test/java/com/navercorp/pinpoint/profiler/AgentInfoSenderTest.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/sender/TcpDataSenderReconnectTest.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/sender/TcpDataSenderTest.java
rpc/src/test/java/com/navercorp/pinpoint/rpc/client/ClientMessageListenerTest.java
rpc/src/test/java/com/navercorp/pinpoint/rpc/client/HealthCheckTest.java
rpc/src/test/java/com/navercorp/pinpoint/rpc/client/PinpointClientFactoryTest.java
rpc/src/test/java/com/navercorp/pinpoint/rpc/client/PinpointClientStateTest.java
rpc/src/test/java/com/navercorp/pinpoint/rpc/client/ReconnectTest.java
rpc/src/test/java/com/navercorp/pinpoint/rpc/server/ControlPacketServerTest.java
rpc/src/test/java/com/navercorp/pinpoint/rpc/server/EventHandlerTest.java
rpc/src/test/java/com/navercorp/pinpoint/rpc/server/HandshakeTest.java
rpc/src/test/java/com/navercorp/pinpoint/rpc/server/PinpointServerSocketTest.java
rpc/src/test/java/com/navercorp/pinpoint/rpc/server/PinpointServerStateTest.java
rpc/src/test/java/com/navercorp/pinpoint/rpc/server/PipelineFactoryTest.java
rpc/src/test/java/com/navercorp/pinpoint/rpc/stream/StreamChannelManagerTest.java
rpc/src/test/java/com/navercorp/pinpoint/rpc/util/PinpointRPCTestUtils.java
rpc/src/test/java/com/navercorp/pinpoint/test/client/TestPinpointClient.java
rpc/src/test/java/com/navercorp/pinpoint/test/client/TestRawSocket.java
rpc/src/test/java/com/navercorp/pinpoint/test/server/TestPinpointServerAcceptor.java
web/src/test/java/com/navercorp/pinpoint/web/cluster/ClusterTest.java

[#cleanup test] cleanup

---

_config.yml
_data/sidebars/mydoc_sidebar.yml
_includes/reference.html
_includes/sidebar.html
_includes/topnav.html
_layouts/firstdefault.html
_layouts/firstpage.html
index.md
version.json

Update Homepage to support version control

Versioned homepage

---

plugins/akka-http/src/main/java/com/navercorp/pinpoint/plugin/akka/http/interceptor/AsyncContextSpanEventEndPointInterceptor.java
plugins/akka-http/src/main/java/com/navercorp/pinpoint/plugin/akka/http/interceptor/DirectivesInterceptor.java

cleanup import
1. remove unused import
2. cleanup import

[#3829] akka http plugin

---

agent/src/main/resources-local/pinpoint.config
agent/src/main/resources-release/pinpoint.config

[#3829] Change default akka_http enable option

---

plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/interceptor/ConsumerRecordEntryPointInterceptor.java
plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/interceptor/ProducerSendInterceptor.java

Fixed error when  headers method not exists.

[#3835] Fixed NoClassDefFoundError error

---

collector/src/main/resources/applicationContext-hbase.xml
collector/src/main/resources/hbase.properties
commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HBaseAsyncOperationFactory.java
flink/src/main/resources/applicationContext-hbase.xml
quickstart/collector/src/main/resources/hbase.properties
web/src/main/resources/applicationContext-hbase.xml

hbase.client.async.max.retries.in.queue
(10 -> 10000)

[#4557] Change default hbase option

---

web/src/main/webapp/common/services/server-map-dao.service.js
web/src/main/webapp/features/serverMap/server-map.directive.js
web/src/main/webapp/features/serverMap/serverMap.html

- add service-type property when compare node.

[#4574] bug fix.

---

thrift/src/main/java/com/navercorp/pinpoint/io/util/HeaderFactoryV2.java
thrift/src/main/java/com/navercorp/pinpoint/thrift/io/HeaderTBaseSerializer.java

1. Add HeaderFactory for V2
2. Add method to serialize HeaderEntity

[#4027] Support HeaderV2

---

plugins/spring/src/main/java/com/navercorp/pinpoint/plugin/spring/async/SpringAsyncPlugin.java

[#4582] Add Lambda transform for spring framework  Async 5.0.x

---

hbase/scripts/hbase-drop.hbase

Can not drop 'ApplicationStatAggre' if not disable it.

add disable table for 'ApplicationStatAggre'

---

_config.yml
index.md

Adjust for Thumbnail of external sites

[#noissue] change for Thumbnail

---

quickstart/web/src/main/resources/pinpoint-web.properties
web/src/main/java/com/navercorp/pinpoint/web/config/ConfigProperties.java
web/src/main/java/com/navercorp/pinpoint/web/controller/ConfigController.java
web/src/main/java/com/navercorp/pinpoint/web/controller/ControllerExceptionHandler.java
web/src/main/resources/pinpoint-web.properties

Adds an option to hide stack trace on web server error

---

thrift/install-thrift-linux.sh

spelling error fix of install-thrift-linux.sh

spelling error fix of install-thrift-linux.sh

---

grpc/.gitignore
grpc/README.md
grpc/pom.xml
grpc/src/main/proto/Trace.proto
grpc/src/main/thrift/Command.thrift
grpc/src/main/thrift/Flink.thrift
grpc/src/main/thrift/Pinpoint.thrift
grpc/src/main/thrift/Trace.thrift
pom.xml
profiler/pom.xml

[#4558] Add grpc transport

---

collector/src/main/java/com/navercorp/pinpoint/collector/cluster/route/filter/AgentEventHandlingFilter.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/thrift/tcp/AgentEventHandler.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/thrift/tcp/AgentLifeCycleEventHandler.java
collector/src/main/java/com/navercorp/pinpoint/collector/service/AgentEventService.java
collector/src/main/java/com/navercorp/pinpoint/collector/service/AgentLifeCycleService.java
collector/src/main/java/com/navercorp/pinpoint/collector/service/StringMetaDataService.java
collector/src/test/java/com/navercorp/pinpoint/collector/cluster/route/filter/AgentEventHandlingFilterTest.java
collector/src/test/java/com/navercorp/pinpoint/collector/receiver/thrift/tcp/AgentEventHandlerTest.java
collector/src/test/java/com/navercorp/pinpoint/collector/receiver/thrift/tcp/AgentLifeCycleEventHandlerTest.java

[#4677] Fix collector namespace

---

web/src/main/webapp/v2/package-lock.json
web/src/main/webapp/v2/src/app/core/components/real-time/real-time-agent-chart.component.css
web/src/main/webapp/v2/src/app/core/components/real-time/real-time-agent-chart.component.html
web/src/main/webapp/v2/src/app/core/components/real-time/real-time-container.component.css

- Set max-height to the wrapper
- Adjust layout
- Resolve chartjs dependency issue

[#noissue][bugfix] Make real-time chart area scrollable

---

doc/per-request_feature_guide.md

Correct typo and grammer error.
Fixes: #4698
Signed-off-by: bbvch13531 <bbvch13531@gmail.com>

Correct typo in per-request_feature_guide.md

---

bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/classloader/BootLoaderFactory.java
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/classloader/J9BootLoader.java
commons/src/main/java/com/navercorp/pinpoint/common/util/JvmType.java
profiler-optional/profiler-optional-jdk6/src/main/java/com/navercorp/pinpoint/profiler/monitor/metric/cpu/JvmCpuUsageCalculator.java
profiler-optional/profiler-optional-jdk6/src/main/java/com/navercorp/pinpoint/profiler/monitor/metric/cpu/ibm/Java6CpuLoadMetric.java
profiler-optional/profiler-optional-jdk6/src/main/java/com/navercorp/pinpoint/profiler/monitor/metric/cpu/oracle/Java6CpuLoadMetric.java
profiler-optional/profiler-optional-jdk7/src/main/java/com/navercorp/pinpoint/profiler/monitor/metric/cpu/ibm/DefaultCpuLoadMetric.java
profiler-optional/profiler-optional-jdk7/src/main/java/com/navercorp/pinpoint/profiler/monitor/metric/cpu/oracle/DefaultCpuLoadMetric.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/stat/cpu/CpuLoadMetricProvider.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/monitor/metric/cpu/CpuUsageProvider.java

Fixes agent startup issues on certain J9 JVM versions

---

agent-it/pom.xml
agent-it/src/test/java/com/navercorp/pinpoint/plugin/cxf/CxfClientIT.java
agent-it/src/test/resources/cxf/pinpoint-cxf-test.config
agent/src/main/resources-local/pinpoint.config
agent/src/main/resources-release/pinpoint-real-env-lowoverhead-sample.config
agent/src/main/resources-release/pinpoint.config
commons/src/main/java/com/navercorp/pinpoint/common/trace/AnnotationKey.java
commons/src/main/java/com/navercorp/pinpoint/common/trace/ServiceType.java
plugins/bom/pom.xml
plugins/cxf/pom.xml
plugins/cxf/src/main/java/com/navercorp/pinpoint/plugin/cxf/CxfPlugin.java
plugins/cxf/src/main/java/com/navercorp/pinpoint/plugin/cxf/CxfPluginConfig.java
plugins/cxf/src/main/java/com/navercorp/pinpoint/plugin/cxf/CxfPluginConstants.java
plugins/cxf/src/main/java/com/navercorp/pinpoint/plugin/cxf/CxfPluginTraceMetadataProvider.java
plugins/cxf/src/main/java/com/navercorp/pinpoint/plugin/cxf/interceptor/CxfClientHandleMessageMethodInterceptor.java
plugins/cxf/src/main/java/com/navercorp/pinpoint/plugin/cxf/interceptor/CxfClientInvokeSyncMethodInterceptor.java
plugins/cxf/src/main/java/com/navercorp/pinpoint/plugin/cxf/interceptor/CxfLoggingInMessageMethodInterceptor.java
plugins/cxf/src/main/java/com/navercorp/pinpoint/plugin/cxf/interceptor/CxfLoggingMessageMethodInterceptor.java
plugins/cxf/src/main/java/com/navercorp/pinpoint/plugin/cxf/interceptor/CxfLoggingOutMessageMethodInterceptor.java
plugins/cxf/src/test/java/com/navercorp/pinpoint/plugin/cxf/interceptor/CxfClientHandleMessageMethodInterceptorTest.java
plugins/cxf/src/test/java/com/navercorp/pinpoint/plugin/cxf/interceptor/CxfClientInvokeSyncMethodInterceptorTest.java
plugins/cxf/src/test/java/com/navercorp/pinpoint/plugin/cxf/interceptor/CxfLoggingInMessageMethodInterceptorTest.java
plugins/cxf/src/test/java/com/navercorp/pinpoint/plugin/cxf/interceptor/CxfLoggingMessageTest.java
plugins/cxf/src/test/java/com/navercorp/pinpoint/plugin/cxf/interceptor/CxfLoggingOutMessageMethodInterceptorTest.java

Title: Cxf Plugin Contribution
Link: https://github.com/VictorZeng/pinpoint/tree/cxf-plugin/plugins/cxf
Target: pinpoint-cxf-plugin
Supported Version: CXF 3.0.0+.
Description: Upgrade cxf version and refactor cxf plugin.
ServiceTypes: 
-   (9081, "CXF_SERVICE_INVOKER");
-   (9082, "CXF_MESSAGE_SENDER");
-   (9083, "CXF_LOGGING_IN");
-   (9084, "CXF_LOGGING_OUT");
Annotations:
-   (202, "cxf.log.id", AnnotationKeyProperty.VIEW_IN_RECORD_SET);
-   (203, "cxf.address", AnnotationKeyProperty.VIEW_IN_RECORD_SET);
-   (204, "cxf.response.code", AnnotationKeyProperty.VIEW_IN_RECORD_SET);
-   (205, "cxf.encoding", AnnotationKeyProperty.VIEW_IN_RECORD_SET);
-   (206, "cxf.http.method", AnnotationKeyProperty.VIEW_IN_RECORD_SET);
-   (207, "cxf.content.type", …

[#4596] Refactor CXF Plugin

---

web/src/main/webapp/v2/src/app/routes/filtered-map-page/filtered-map-page.component.html
web/src/main/webapp/v2/src/app/routes/filtered-map-page/filtered-map-page.routing.ts
web/src/main/webapp/v2/src/app/routes/main-page/main-page.component.html
web/src/main/webapp/v2/src/app/routes/main-page/main-page.routing.ts
web/src/main/webapp/v2/src/app/routes/transaction-list-page/transaction-list-page.component.html
web/src/main/webapp/v2/src/app/routes/transaction-list-page/transaction-list-page.routing.ts
web/src/main/webapp/v2/src/app/routes/transaction-view-page/transaction-view-page.component.html
web/src/main/webapp/v2/src/app/routes/transaction-view-page/transaction-view-page.routing.ts

- Fix incorrect router secondary outlet usage.

[#noissue] refactoring angular router setting

---

agent-it/src/test/java/com/navercorp/pinpoint/plugin/cxf/CxfClientIT.java

Fixes CXF plugin integration test failure

---

web/src/main/webapp/v2/src/app/core/components/agent-info/agent-info-container.component.css
web/src/main/webapp/v2/src/app/core/components/agent-info/agent-info-container.component.html
web/src/main/webapp/v2/src/app/core/components/agent-info/agent-info-container.component.ts
web/src/main/webapp/v2/src/app/core/components/agent-info/agent-info-data.service.ts
web/src/main/webapp/v2/src/app/core/components/agent-manager/agent-manager-data.service.ts
web/src/main/webapp/v2/src/app/core/components/server-and-agent-list/index.ts
web/src/main/webapp/v2/src/app/core/components/server-and-agent-list/server-and-agent-list-container.component.ts
web/src/main/webapp/v2/src/app/core/components/server-and-agent-list/server-and-agent-list-data.service.ts
web/src/main/webapp/v2/src/app/core/components/server-error-popup/server-error-popup.component.html
web/src/main/webapp/v2/src/app/core/components/timeline/agent-inspector-timeline-container.component.ts
web/src/main/webapp/v2/src/app/core/components/timeline/agent-timeline-data.service.ts
web/src/main/webapp/v2/src/app/core/httpInterceptor/marking-interceptor.ts
web/src/main/webapp/v2/src/app/shared/services/url-route-manager.service.ts
web/src/main/webapp/v2/src/globals.d.ts

- getAgentInfo
- getAgentList
- getAgentStatusTimeline

[#4718] Add ajax error handling

---

agent-it/src/test/java/com/navercorp/pinpoint/plugin/dubbo/provider/DubboProviderIT.java
plugins/dubbo/src/test/java/com/navercorp/pinpoint/plugin/dubbo/DubboConfigurationTest.java
plugins/dubbo/src/test/java/com/navercorp/pinpoint/plugin/dubbo/DubboConstantsTest.java
plugins/dubbo/src/test/java/com/navercorp/pinpoint/plugin/dubbo/DubboProviderDetectorTest.java
plugins/dubbo/src/test/java/com/navercorp/pinpoint/plugin/dubbo/DubboProviderMethodDescriptorTest.java
plugins/dubbo/src/test/java/com/navercorp/pinpoint/plugin/dubbo/DubboTraceMetadataProviderTest.java

[#noissue] Fix Dubbo Plugin IT

---

profiler-optional/profiler-optional-jdk7/src/main/java/com/navercorp/pinpoint/profiler/monitor/metric/buffer/DefaultBufferMetric.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/stat/buffer/BufferMetricProvider.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/context/provider/stat/buffer/BufferMetricProviderTest.java

[#noissue] BufferMetric cleanup

---

collector/src/main/java/com/navercorp/pinpoint/collector/cluster/ClusterPointRouter.java
commons/src/main/java/com/navercorp/pinpoint/common/util/apache/IntHashMapUtils.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/AgentInfoSender.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/HeaderTBaseSerializerProvider.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/CommandDispatcher.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/CommandSerializer.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/DefaultProfilerCommandServiceLocator.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/ProfilerCommandLocatorBuilder.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/ProfilerCommandService.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/ProfilerCommandServiceLocator.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/ProfilerRequestCommandService.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/ProfilerSimpleCommandService.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/ProfilerStreamCommandService.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/service/ActiveThreadCountService.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/service/ActiveThreadDumpService.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/service/ActiveThreadLightDumpService.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/service/EchoService.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/service/ThreadDumpService.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/receiver/ProfilerCommandServiceLocatorTest.java
thrift/src/main/java/com/navercorp/pinpoint/io/header/HeaderEntity.java
thrift/src/main/java/com/navercorp/pinpoint/io/request/DefaultMessage.java
thrift/src/main/java/com/navercorp/pinpoint/io/request/EmptyMessage.java
thrift/src/main/java/com/navercorp/pinpoint/thrift/io/TCommandType.java
web/src/main/java/com/navercorp/pinpoint/web/cluster/DefaultPinpointRouteResponse.java
web/src/main/java/com/navercorp/pinpoint/web/service/AgentServiceImpl.java
web/src/main/java/com/navercorp/pinpoint/web/websocket/ActiveThreadCountWorker.java

- Reduce thrift dependency in CommandService

[#4661] Isolate domain model and transport model

---

pom.xml

[#4702] ASM version update

---

pom.xml

- thrift 0.10.0 -> 011.0
- spring 4.3.8 -> 4.3.20
- spring batch 3.0.7 -> 3.0.9
- spring security 4.2.2 -> 4.2.8
- spotbug 3.1.3 -> 3.1.8
- pmd 3.9.0 ->3.10.0

[#4751] Update library

---

commons/src/main/java/com/navercorp/pinpoint/common/util/DefaultSqlParser.java
commons/src/test/java/com/navercorp/pinpoint/common/util/DefaultSqlParserTest.java

[#4746] Fix SqlParser.combindBindValues operation

---

agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/rabbitmq/spring/SpringAmqpRabbit_2_0_3_to_2_1_0_IT.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/rabbitmq/spring/SpringAmqpRabbit_2_1_x_to_2_x_IT.java
plugins/rabbitmq/src/main/java/com/navercorp/pinpoint/plugin/rabbitmq/client/RabbitMQClientPlugin.java

Adds support for spring-amqp-rabbit 2.1.x

---

commons/src/main/java/com/navercorp/pinpoint/common/util/JvmVersion.java

[#4676] Java 11 support

---

web/src/main/webapp/v2/src/app/routes/error-page/error-page.component.ts
web/src/main/webapp/v2/src/app/shared/services/system-configuration-data.service.ts
web/src/main/webapp/v2/src/app/shared/services/system-configuration-resolver.service.ts
web/src/main/webapp/v2/src/globals.d.ts

- move interface declare statement to globals.d.ts

[#noissue] refactoring

---

agent-it/pom.xml
agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/cassandra/CassandraDatastaxITBase.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/cassandra/CassandraDatastax_2_0_x_IT.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/cassandra/CassandraDatastax_2_1_x_IT.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/cassandra/CassandraDatastax_2_2_x_IT.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/cassandra/CassandraDatastax_3_0_x_IT.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/cassandra/CassandraTestHelper.java
plugins/cassandra/src/main/java/com/navercorp/pinpoint/plugin/cassandra/CassandraPlugin.java
plugins/cassandra/src/main/java/com/navercorp/pinpoint/plugin/cassandra/field/WrappedStatementGetter.java
plugins/cassandra/src/main/java/com/navercorp/pinpoint/plugin/cassandra/interceptor/CassandraStatementExecuteQueryInterceptor.java

This replaces embedded Cassandra with stubbed Cassandra for integration tests and widens supported Datastax java driver versions for pinpoint agent.
resolves #4798

Cassandra Datastax plugin and IT improvements

---

agent/src/main/resources-local/pinpoint.config
agent/src/main/resources-release/pinpoint-real-env-lowoverhead-sample.config
agent/src/main/resources-release/pinpoint.config

Exist in code but it does not exist in config file.

 Missing to exclude methods for tomcat

---

collector/src/main/java/com/navercorp/pinpoint/collector/handler/thrift/ThriftAgentEventHandler.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/AgentEventMessageSerializerV1.java

[#4677] Fix findbug issue

---

plugins/bom/pom.xml
plugins/kafka/pom.xml

[#noissue] Refactor kafka plugin dependency.

---

plugins/druid/pom.xml
plugins/druid/src/main/java/com/navercorp/pinpoint/plugin/druid/DruidDataSourceMonitor.java
plugins/druid/src/test/java/com/navercorp/pinpoint/plugin/druid/DruidDataSourceMonitorTest.java

[#noissue] Optimize druid plugin.

---

plugins/bom/pom.xml

next step should be an update to 3.2.7

update CXF minor version

---

pom.xml

Change the version of hbase client library due to performance issues

[#4841] Change the version of hbase client library

---

commons/src/main/java/com/navercorp/pinpoint/common/util/IOUtils.java
commons/src/main/java/com/navercorp/pinpoint/common/util/PropertyUtils.java
profiler-test/src/main/java/com/navercorp/pinpoint/test/classloader/TransformClassLoader.java
profiler-test/src/main/java/com/navercorp/pinpoint/test/util/BytecodeUtils.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMClassNodeAdapter.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMClassWriter.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/classreading/ClassReaderWrapper.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/NioUDPDataSender.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/SpanStreamUdpSender.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/util/JarReader.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/ASMAspectWeaverTest.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/ASMClassNodeLoader.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/sender/NioUdpDataSenderTest.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/sender/UdpSocketTest.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/util/BytecodeUtils.java
rpc/src/test/java/com/navercorp/pinpoint/rpc/server/PipelineFactoryTest.java
rpc/src/test/java/com/navercorp/pinpoint/rpc/util/IOUtils.java
rpc/src/test/java/com/navercorp/pinpoint/test/client/TestRawSocket.java

[#noissue] Add IOUtils

---

plugins/bom/pom.xml
plugins/redis/pom.xml
plugins/redis/src/main/java/com/navercorp/pinpoint/plugin/redis/LettuceMethodNameFilter.java
plugins/redis/src/main/java/com/navercorp/pinpoint/plugin/redis/jedis/JedisMethodNameFilter.java
plugins/redis/src/main/java/com/navercorp/pinpoint/plugin/redis/jedis/RedisPlugin.java
plugins/redis/src/main/java/com/navercorp/pinpoint/plugin/redis/jedis/interceptor/AttachEndPointInterceptor.java
plugins/redis/src/main/java/com/navercorp/pinpoint/plugin/redis/jedis/interceptor/JedisMethodInterceptor.java
plugins/redis/src/main/java/com/navercorp/pinpoint/plugin/redis/jedis/interceptor/ProtocolSendCommandAndReadMethodInterceptor.java
plugins/redis/src/main/java/com/navercorp/pinpoint/plugin/redis/jedis/interceptor/SetEndPointInterceptor.java
plugins/redis/src/main/java/com/navercorp/pinpoint/plugin/redis/lettuce/LettucePlugin.java
plugins/redis/src/main/java/com/navercorp/pinpoint/plugin/redis/lettuce/StatefulConnectionGetter.java
plugins/redis/src/main/java/com/navercorp/pinpoint/plugin/redis/lettuce/interceptor/AttachEndPointInterceptor.java
plugins/redis/src/main/java/com/navercorp/pinpoint/plugin/redis/lettuce/interceptor/LettuceMethodInterceptor.java
plugins/redis/src/main/java/com/navercorp/pinpoint/plugin/redis/lettuce/interceptor/RedisClientConstructorInterceptor.java
plugins/redis/src/main/resources/META-INF/services/com.navercorp.pinpoint.bootstrap.plugin.ProfilerPlugin

[#4843] Add LettucePlugin

---

web/src/main/java/com/navercorp/pinpoint/web/controller/BusinessTransactionController.java

mongo plugin, take care of indentation from front.
refactor binding logic in to one API

[#4849] mongo plugin, remove indentation pass job to front

---

web/src/main/webapp/v2/package-lock.json
web/src/main/webapp/v2/package.json
web/src/main/webapp/v2/src/app/core/components/syntax-highlight-popup/syntax-highlight-popup.component.html
web/src/main/webapp/v2/src/app/core/components/syntax-highlight-popup/syntax-highlight-popup.component.ts

[#noissue] Update code formatting library

---

agent-it/pom.xml
agent-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/TestEnvironment.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/client/AsyncEchoTestClient.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/client/HttpEchoTestClient.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/client/SyncEchoTestClient.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/server/AsyncEchoTestServer.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/server/EchoTestServer.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/server/HttpEchoTestServer.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/server/SyncEchoTestServer.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/server/ThriftEchoTestServer.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/EchoTestRunner.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/asynchronous/ThriftHalfSyncHalfAsyncServerAsyncIT.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/asynchronous/ThriftNonblockingServerAsyncIT.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/asynchronous/ThriftThreadedSelectorServerAsyncIT.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/http/ThriftHttpIT.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/synchronous/ThriftHalfSyncHalfAsyncServerIT.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/synchronous/ThriftNonblockingServerIT.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/synchronous/ThriftSimpleServerIT.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/synchronous/ThriftThreadedSelectorServerIT.java
plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/ThriftClientCallContext.java
plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/ThriftConstants.java
plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/ThriftPlugin.java
plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/ThriftTypeProvider.java
plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/ThriftUtils.java
plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/field/getter/UrlFieldGetter.java
plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/interceptor/client/TServiceClientSendBaseInterceptor.java
plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/interceptor/server/TBaseProcessorProcessInterceptor.java
plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/interceptor/tprotocol/server/TProtocolReadMessageEndInterceptor.java

Adds trace support for Thrift over HTTP

---

pom.xml
profiler-optional/profiler-optional-jdk7/pom.xml
profiler-test/pom.xml
profiler/pom.xml

#4702 ASM version update

---

bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/classloader/BootLoaderTest.java
bootstrap-java9/src/test/java/com/navercorp/pinpoint/bootstrap/java9/classloader/Java9BootLoaderTest.java
profiler-optional/profiler-optional-jdk8/src/test/java/com/navercorp/test/pinpoint/jdk8/interfaces/MethodInterfaceTest.java
profiler-optional/profiler-optional-jdk9/src/test/java/com/navercorp/pinpoint/profiler/instrument/classloading/Java9DefineClassTest.java
profiler-test/src/main/java/com/navercorp/pinpoint/test/ProjectPathResolver.java
profiler-test/src/main/java/com/navercorp/pinpoint/test/classloader/TransformClassLoader.java
profiler-test/src/main/java/com/navercorp/pinpoint/test/util/BytecodeUtils.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMClassNodeAdapter.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMClassWriter.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/classreading/ClassReaderWrapper.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/PluginInstrumentContext.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/util/JavaAssistUtils.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/ASMAspectWeaverTest.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/ASMClassNodeLoader.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/scanner/ClassScannerFactoryTest.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/util/BytecodeUtils.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/util/JavaAssistUtilsTest.java

- Add javaClassNameToJvmResourceName() api

[#noissue] Reduce memory usage

---

plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/MongoUtil.java

- decimal128Enabled variable is not assigned

[#4737] code cleanup & bug fix

---

pom.xml
profiler/pom.xml

[#4702] Add asm-analysis

---

plugins/netty/src/main/java/com/navercorp/pinpoint/plugin/netty/NettyPlugin.java

If do not have the method that netty plugin wanted, change recording exception to recording simple log.
(Netty does not support all versions, so if the exception is written to the log, user might think there is a problem.)

[#noissue] Change handling method if method is not available

---

agent-it/src/test/java/com/navercorp/pinpoint/plugin/mongodb/MongoDBBase.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/mongodb/MongoDB_3_2_x.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/mongodb/MongoDB_3_5_x.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/mongodb/MongoDB_3_7_x.java
plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/MongoUtil.java
plugins/mongodb/src/test/java/com/navercorp/pinpoint/plugin/mongo/MongoUtilTest.java
web/src/main/java/com/navercorp/pinpoint/web/controller/BusinessTransactionController.java
web/src/main/java/com/navercorp/pinpoint/web/service/SpanServiceImpl.java
web/src/test/java/com/navercorp/pinpoint/web/util/MongoJsonCombineTest.java

matching output format to default format of JsonWriter(JsonMode.STRICT)

[#4737] match format of JsonWriter

---

agent/src/main/resources-local/pinpoint.config
agent/src/main/resources-release/pinpoint.config
plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/KafkaConfig.java
plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/KafkaConstants.java
plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/KafkaPlugin.java
plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/interceptor/ConsumerMultiRecordEntryPointInterceptor.java
plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/interceptor/ConsumerRecordEntryPointInterceptor.java
plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/interceptor/ConsumerRecordsDesc.java
plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/interceptor/ProducerSendInterceptor.java
plugins/kafka/src/test/java/com/navercorp/pinpoint/plugin/kafka/interceptor/ConsumerMultiRecordEntryPointInterceptorTest.java
plugins/kafka/src/test/java/com/navercorp/pinpoint/plugin/kafka/interceptor/ConsumerRecordEntryPointInterceptorTest.java
plugins/kafka/src/test/java/com/navercorp/pinpoint/plugin/kafka/interceptor/ProducerSendInterceptorTest.java

Supports spring-kafka via option within the kafka plugin

[#4939] Supports spring-kafka via option within the kafka plugin

---

agent-it/src/test/resources/pinpoint-grpc-plugin-test.config
agent/src/main/resources-local/pinpoint.config
agent/src/main/resources-release/pinpoint.config
plugins/grpc/src/main/java/com/navercorp/pinpoint/plugin/grpc/GrpcConfig.java
plugins/grpc/src/main/java/com/navercorp/pinpoint/plugin/grpc/GrpcConstants.java
plugins/grpc/src/main/java/com/navercorp/pinpoint/plugin/grpc/GrpcServerPlugin.java
plugins/grpc/src/main/java/com/navercorp/pinpoint/plugin/grpc/descriptor/GrpcServerCallMethodDescritpro.java
plugins/grpc/src/main/java/com/navercorp/pinpoint/plugin/grpc/descriptor/GrpcStreamListenerResultMethodDescriptor.java

add streaming server enable option

[#4897] Support grpc-java plugin

---

web/src/main/webapp/v2/src/app/core/components/info-per-server/info-per-server-container.component.css
web/src/main/webapp/v2/src/app/core/components/info-per-server/info-per-server-for-filtered-map-container.component.css
web/src/main/webapp/v2/src/app/core/components/real-time-new/new-real-time-container.component.ts
web/src/main/webapp/v2/src/app/core/components/server-map/class/server-map-diagram-with-visjs.class.ts
web/src/main/webapp/v2/src/app/core/components/server-map/server-map-container.component.css
web/src/main/webapp/v2/src/app/core/components/server-map/server-map-container.component.html
web/src/main/webapp/v2/src/app/core/components/server-map/server-map-container.component.ts
web/src/main/webapp/v2/src/app/core/components/side-bar/side-bar-container.component.css
web/src/main/webapp/v2/src/app/core/components/side-bar/side-bar-for-filtered-map-container.component.css

- Hide realtime template
- Remove server map

[#4955] Fix: Handle the no agent case in main page

---

rpc/src/main/java/com/navercorp/pinpoint/rpc/client/DefaultPinpointClientFactory.java

Fix incorrect parameter verification

[#noissue] Fix incorrect parameter verification

---

web/src/main/webapp/v2/src/app/core/components/real-time-new/new-real-time-websocket.service.ts

- If timeout error occurs, deliver the previous data unless the error occurs 5 times in a row

[#noissue] Handle the timeout response on realtime

---

plugins/mysql-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/mysql/MySqlPlugin.java

Adds support for MySQL java driver 8.x

---

web/src/main/webapp/v2/src/app/core/components/scatter-chart/class/scatter-chart-data-block.class.ts
web/src/main/webapp/v2/src/app/core/components/scatter-chart/class/scatter-chart.class.ts
web/src/main/webapp/v2/src/app/core/components/scatter-chart/scatter-chart.component.ts

- increase count speed by dividing datablock smaller
- remove a function that is invoked in duplicate

[#noissue] refactoring scatter-chart

---

profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/service/ActiveThreadCountService.java

Make the data delivery cycle more precise

[#4971] Make the data delivery cycle more precise

---

web/src/main/webapp/v2/src/app/core/components/agent-search-input/agent-search-input-container.component.css
web/src/main/webapp/v2/src/app/core/components/application-inspector-title/application-inspector-title-container.component.css
web/src/main/webapp/v2/src/app/core/components/server-and-agent-list/server-and-agent-list-container.component.css
web/src/main/webapp/v2/src/app/core/components/server-and-agent-list/server-and-agent-list.component.css

- Set the height of the wrapper considering the height of the agent search input

[#noissue] Fix: Fix the vertical scroll when the agent list is overflow

---

web/src/main/webapp/v2/src/app/core/components/server-map/server-map-container.component.ts
web/src/main/webapp/v2/src/app/core/components/server-map/server-map-for-filtered-map-container.component.ts

- before: target node's auth -> after: derived node's auth

[#noissue] Fix: Change the checking auth logic for links on the server map

---

agent/src/main/resources-local/pinpoint.config
agent/src/main/resources-release/pinpoint.config

[#noissue] change comment characters to sharp at pinpoint.config

---

agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/grpc/Grpc_1_8_0_to_IT.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/grpc/HelloWorldClient.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/grpc/HelloWorldServer.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/grpc/HelloWorldSimpleClient.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/grpc/HelloWorldSimpleServer.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/grpc/HelloWorldStreamClient.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/grpc/HelloWorldStreamServer.java

[#noissue] fix grpc integration test

---

web/src/main/webapp/v2/src/app/core/components/configuration-icon/configuration-icon-container.component.ts
web/src/main/webapp/v2/src/app/core/components/configuration-popup/configuration-popup-container.component.html
web/src/main/webapp/v2/src/app/core/components/configuration-popup/configuration-popup-container.component.ts
web/src/main/webapp/v2/src/app/core/components/configuration-popup/configuration-popup.component.html
web/src/main/webapp/v2/src/app/core/components/configuration-popup/configuration-popup.component.ts
web/src/main/webapp/v2/src/app/core/components/state-button/state-button-for-transaction-list-container.component.ts
web/src/main/webapp/v2/src/app/core/components/timeline/agent-inspector-timeline-container.component.ts
web/src/main/webapp/v2/src/app/routes/config-page/config-page.component.css
web/src/main/webapp/v2/src/app/routes/config-page/config-page.component.html
web/src/main/webapp/v2/src/app/routes/config-page/config-page.component.ts
web/src/main/webapp/v2/src/app/routes/transaction-detail-page/transaction-detail-page.routing.ts
web/src/main/webapp/v2/src/app/shared/services/store-helper.service.ts
web/src/main/webapp/v2/src/app/shared/store/index.ts
web/src/main/webapp/v2/src/app/shared/store/url-path.reducer.ts

- Keep the previous URL path state in the store
- Take the latest URL path state and navigate to it when clicking the exit button on the config page

[#noissue] Fix: Navigate to the previous page when clicking the exit button on the config page

---

web/src/main/webapp/v2/src/app/shared/store/url-path.reducer.ts

- Navigate to the main page when clicking the exit button

[#noissue] Fix: Handle the case the user enters the config page directly

---

web/src/main/webapp/features/distributedCallFlow/distributed-call-flow.directive.js

[#5087] bug fix

---

agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/activemq/client/ActiveMQClientMultipleBrokersIT.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/activemq/client/ActiveMQClientMultipleBrokers_5_15_x_IT.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/activemq/client/ActiveMQClientSingleBroker_5_15_x_IT.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/jackson/ObjectMapperIT.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/jackson/ObjectReaderIT.java
agent-it/src/test/java/com/navercorp/test/pinpoint/plugin/spring/beans/AbstractAutowireCapableBeanFactoryModifier_5_x_IT.java

Apply the appropriate jvm version of the some integration tests.

[#noissue] fix integration test

---

test/src/main/java/com/navercorp/pinpoint/test/plugin/DelegateSupportedPinpointPluginTestInstance.java
test/src/main/java/com/navercorp/pinpoint/test/plugin/PinpointPluginTestSuite.java

[#5118] Change method of create process in IT

---

agent/src/main/resources-local/pinpoint.config
agent/src/main/resources-release/pinpoint.config
plugins/pom.xml
plugins/undertow-servlet/src/main/resources/META-INF/services/com.navercorp.pinpoint.common.trace.TraceMetadataProvider
plugins/undertow/src/main/java/com/navercorp/pinpoint/plugin/undertow/UndertowConfig.java
plugins/undertow/src/main/java/com/navercorp/pinpoint/plugin/undertow/UndertowPlugin.java
plugins/undertow/src/main/java/com/navercorp/pinpoint/plugin/undertow/interceptor/ConnectorsExecuteRootHandlerInterceptor.java

#5114
Add Undertow Servlet.
~~~
profiler.undertow.deploy.servlet=true
~~~

[#5114] Fix UndertowPlugin for Spring Boot & Wildfly

---

agent/pom.xml
plugins/pom.xml
pom.xml
quickstart/agent/pom.xml

- update maven-assembly-plugin 3.1.0 -> 3.1.1

[#5173] Update dependency

---

web/src/main/webapp/features/serverMap/server-map.directive.js
web/src/main/webapp/features/sidebar/title/sidebar-title.directive.js
web/src/main/webapp/v2/src/app/core/components/server-map/class/server-map-data.class.ts

- remove 'isQueue' option when check mergeable node.

[#noissue] Update merge condition of server-map

---

bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/DefaultProfilerConfig.java
bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/config/DefaultProfilerConfigTest.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/AsyncChildTrace.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/CallStack.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultCallStack.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTrace.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/SpanEventFactory.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/context/DefaultTraceTest.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/context/SpanEventElementFactoryTest.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/context/SpanEventFactoryTest.java

[#5217] Fix CallStack max depth

---

profiler/src/main/java/com/navercorp/pinpoint/profiler/context/SpanEventFactory.java

[#5217] Fix CallStackFactory dummy

---

profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/DefaultApplicationContext.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/ModuleLifeCycle.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/RpcModule.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/RpcModuleLifeCycle.java

[#noissue] Refactor the life cycle of RpcModule

---

web/src/main/webapp/v2/src/app/core/components/alarm-rule-list/alarm-rule-list-container.component.css
web/src/main/webapp/v2/src/app/core/components/alarm-rule-list/alarm-rule-list-container.component.html
web/src/main/webapp/v2/src/app/core/components/alarm-rule-list/alarm-rule-list-container.component.ts
web/src/main/webapp/v2/src/app/core/components/group-member/group-member-container.component.css
web/src/main/webapp/v2/src/app/core/components/group-member/group-member-container.component.html
web/src/main/webapp/v2/src/app/core/components/group-member/group-member-container.component.ts
web/src/main/webapp/v2/src/app/core/components/group-member/group-member.component.css
web/src/main/webapp/v2/src/app/core/components/pinpoint-user/pinpoint-user-container.component.css
web/src/main/webapp/v2/src/app/core/components/pinpoint-user/pinpoint-user-container.component.html
web/src/main/webapp/v2/src/app/core/components/pinpoint-user/pinpoint-user-container.component.ts
web/src/main/webapp/v2/src/app/core/components/user-group/user-group-container.component.css
web/src/main/webapp/v2/src/app/core/components/user-group/user-group-container.component.html
web/src/main/webapp/v2/src/app/core/components/user-group/user-group-container.component.ts
web/src/main/webapp/v2/src/app/shared/components/server-error-message/index.ts
web/src/main/webapp/v2/src/app/shared/components/server-error-message/server-error-message.component.css
web/src/main/webapp/v2/src/app/shared/components/server-error-message/server-error-message.component.html
web/src/main/webapp/v2/src/app/shared/components/server-error-message/server-error-message.component.ts
web/src/main/webapp/v2/src/app/shared/index.ts

- Extract the displaying server error message template into a shared component

[#noissue] Implement ServerErrorMessage component

---

web/src/main/webapp/v2/src/app/core/components/alarm-rule-list/alarm-rule-create-and-update.component.css
web/src/main/webapp/v2/src/app/core/components/alarm-rule-list/alarm-rule-create-and-update.component.html
web/src/main/webapp/v2/src/app/core/components/alarm-rule-list/alarm-rule-create-and-update.component.ts
web/src/main/webapp/v2/src/app/core/components/alarm-rule-list/alarm-rule-list-container.component.ts
web/src/main/webapp/v2/src/app/core/components/pinpoint-user/pinpoint-user-container.component.ts
web/src/main/webapp/v2/src/app/core/components/pinpoint-user/pinpoint-user-create-and-update.component.css
web/src/main/webapp/v2/src/app/core/components/pinpoint-user/pinpoint-user-create-and-update.component.html
web/src/main/webapp/v2/src/app/core/components/pinpoint-user/pinpoint-user-create-and-update.component.ts
web/src/main/webapp/v2/src/app/core/components/user-group/user-group-container.component.html
web/src/main/webapp/v2/src/app/core/components/user-group/user-group-container.component.ts
web/src/main/webapp/v2/src/app/core/components/user-group/user-group-create-and-update.component.css
web/src/main/webapp/v2/src/app/core/components/user-group/user-group-create-and-update.component.html
web/src/main/webapp/v2/src/app/core/components/user-group/user-group-create-and-update.component.ts
web/src/main/webapp/v2/src/app/shared/components/form-field-error-message/form-field-error-message.component.css
web/src/main/webapp/v2/src/app/shared/components/form-field-error-message/form-field-error-message.component.html
web/src/main/webapp/v2/src/app/shared/components/form-field-error-message/form-field-error-message.component.ts
web/src/main/webapp/v2/src/app/shared/components/form-field-error-message/index.ts
web/src/main/webapp/v2/src/app/shared/index.ts
web/src/main/webapp/v2/src/globals.d.ts

- Extract the displaying form field error message template into a shared component

[#noissue] Implement FormFieldErrorMessage component

---

web/src/main/webapp/v2/src/app/core/components/pinpoint-user/index.ts
web/src/main/webapp/v2/src/app/core/components/pinpoint-user/pinpoint-user-container.component.css
web/src/main/webapp/v2/src/app/core/components/pinpoint-user/pinpoint-user-container.component.html
web/src/main/webapp/v2/src/app/core/components/pinpoint-user/pinpoint-user-container.component.ts
web/src/main/webapp/v2/src/app/core/components/pinpoint-user/pinpoint-user.component.css
web/src/main/webapp/v2/src/app/core/components/user-group/user-group-container.component.css
web/src/main/webapp/v2/src/app/core/components/user-group/user-group-container.component.html
web/src/main/webapp/v2/src/app/core/components/user-group/user-group-container.component.ts
web/src/main/webapp/v2/src/app/core/components/user-group/user-group.component.css

- Call the api whenever the user searches
- Adjust the style

[#noissue] Fix: Fetch the data every time the user searches

---

bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/request/DefaultRequestTraceWriter.java

Fixes application namespace propagation

---

web/src/main/webapp/v2/src/app/core/components/configuration-icon/configuration-icon-container.component.ts
web/src/main/webapp/v2/src/app/core/components/configuration-popup/configuration-popup-container.component.ts
web/src/main/webapp/v2/src/app/shared/components/form-field-error-message/form-field-error-message.component.css
web/src/main/webapp/v2/src/app/shared/services/url-route-manager.service.ts

- Filter the base href on navigation when it's spotted in the delivered url

[#noissue] Fix: Handle when it has a certain base href other than empty string

---

web/src/main/webapp/v2/src/app/shared/services/application-list-resolver.service.ts

- Navigate them to the main page if the provided application key is non-existent

[#5321] Operate a guard for the provided application key from the url

---

web/src/main/webapp/v2/src/app/core/components/alarm-rule-list/alarm-rule-data.service.ts
web/src/main/webapp/v2/src/app/core/components/alarm-rule-list/alarm-rule-list-container.component.ts

- add application id parameter when remove alarm.

[#noissue] add request parameter

---

doc/modules.md

This pull request has automatically created by PinpointAutoBot
Updated Item : [spring-rabbit] has been updated
`*Updated item list may differ if this PR is updated*`

[Doc] Modules Update

---

profiler/src/main/java/com/navercorp/pinpoint/profiler/context/compress/SpanProcessorV1.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/compress/SpanProcessorV2.java

[#5334] Fix SpanProcessor - NPE

---

collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/AgentServer.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/CurrentTimeSocketIdProvider.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/KeepAliveService.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/ServerRequestFactory.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/SocketIdProvider.java
collector/src/main/resources/applicationContext-collector.xml
grpc/src/main/java/com/navercorp/pinpoint/grpc/server/ServerContext.java
grpc/src/main/java/com/navercorp/pinpoint/grpc/server/ServerFactory.java
grpc/src/main/java/com/navercorp/pinpoint/grpc/server/TransportMetadataFactory.java
grpc/src/main/java/com/navercorp/pinpoint/grpc/server/TransportMetadataServerInterceptor.java
grpc/src/test/java/com/navercorp/pinpoint/grpc/ChannelFactoryTest.java

[#4558] Refactor grpc

---

profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/scanner/ClassScannerFactory.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/scanner/ClassScannerFactoryTest.java

Applies #5362 to 1.8.x branch.

Backport workaround for scanning classes in nested jars

---

agent/src/main/resources-local/pinpoint.config
agent/src/main/resources-release/pinpoint.config
commons/src/main/java/com/navercorp/pinpoint/common/trace/ServiceType.java
plugins/assembly/pom.xml
plugins/bom/pom.xml
plugins/pom.xml
plugins/redis-redisson/.gitignore
plugins/redis-redisson/README.md
plugins/redis-redisson/pom.xml
plugins/redis-redisson/src/main/java/com/navercorp/pinpoint/plugin/redis/redisson/RedissonConstants.java
plugins/redis-redisson/src/main/java/com/navercorp/pinpoint/plugin/redis/redisson/RedissonMethodNameFilters.java
plugins/redis-redisson/src/main/java/com/navercorp/pinpoint/plugin/redis/redisson/RedissonPlugin.java
plugins/redis-redisson/src/main/java/com/navercorp/pinpoint/plugin/redis/redisson/RedissonPluginConfig.java
plugins/redis-redisson/src/main/java/com/navercorp/pinpoint/plugin/redis/redisson/interceptor/CommandAsyncServiceMethodInterceptor.java
plugins/redis-redisson/src/main/java/com/navercorp/pinpoint/plugin/redis/redisson/interceptor/RedissonMethodInterceptor.java
plugins/redis-redisson/src/main/resources/META-INF/pinpoint/type-provider.yml
plugins/redis-redisson/src/main/resources/META-INF/services/com.navercorp.pinpoint.bootstrap.plugin.ProfilerPlugin

[#5378] Add redisson plugin

---

collector/src/main/java/com/navercorp/pinpoint/collector/handler/thrift/ThriftSpanChunkHandler.java
collector/src/main/java/com/navercorp/pinpoint/collector/handler/thrift/ThriftSpanHandler.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/AnnotationBo.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/AnnotationFactory.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/AnnotationTranscoder.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/grpc/GrpcAnnotationHandler.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/grpc/GrpcSpanFactory.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/trace/v2/SpanDecoderV0.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/trace/v2/SpanEncoderV0.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/thrift/SpanFactory.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/thrift/ThriftAnnotationHandler.java
commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/AnnotationTranscoderTest.java
commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/grpc/GrpcAnnotationHandlerTest.java
commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/serializer/trace/v2/SpanEncoderTest.java
commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/serializer/trace/v2/bitfield/SpanEventBitFieldTest.java
commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/thrift/SpanFactoryTest.java
grpc/pom.xml
grpc/src/main/proto/Trace.proto
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/compress/SpanProcessorProtoV2.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/proto/SpanProtoMessageConverter.java
web/src/main/java/com/navercorp/pinpoint/web/calltree/span/MetaSpanCallTreeFactory.java
web/src/main/java/com/navercorp/pinpoint/web/service/SpanServiceImpl.java
web/src/test/java/com/navercorp/pinpoint/web/filter/LinkFilterTest.java
web/src/test/java/com/navercorp/pinpoint/web/filter/RpcURLPatternFilterTest.java
web/src/test/java/com/navercorp/pinpoint/web/mapper/SpanMapperV2Test.java

[#4558] Refactor annotaion 

---

rpc/src/main/java/com/navercorp/pinpoint/rpc/packet/stream/StreamCode.java
rpc/src/main/java/com/navercorp/pinpoint/rpc/server/DefaultPinpointServer.java
rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/ClientStreamChannel.java
rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/ServerStreamChannel.java
rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/StreamChannel.java
rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/StreamChannelManager.java
rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/StreamChannelRepository.java

Removes the callback access for StreamChannelManger from some classes.

[#5384] Cleanup  code related to cluster

---

agent/src/main/resources-local/pinpoint.config
agent/src/main/resources-release/pinpoint.config
plugins/undertow/src/main/java/com/navercorp/pinpoint/plugin/undertow/UndertowConfig.java
plugins/undertow/src/main/java/com/navercorp/pinpoint/plugin/undertow/interceptor/ConnectorsExecuteRootHandlerInterceptor.java

[#5442] Add HttpHandler option of undertow plugin

---

web/src/main/webapp/v2/src/app/core/components/agent-inspector-contents/agent-inspector-contents-container.component.html
web/src/main/webapp/v2/src/app/core/components/application-inspector-contents/application-inspector-contents-container.component.html
web/src/main/webapp/v2/src/app/core/components/inspector-chart/agent-data-source-chart-container.component.css
web/src/main/webapp/v2/src/app/core/components/inspector-chart/agent-data-source-chart-container.component.html
web/src/main/webapp/v2/src/app/core/components/inspector-chart/agent-data-source-chart-select-source.component.css
web/src/main/webapp/v2/src/app/core/components/inspector-chart/agent-data-source-chart-select-source.component.html
web/src/main/webapp/v2/src/app/shared/services/component-default-setting-data.service.ts

- Change the default chart number per row from 2 to 3
- Move the data source chart to the last
- Change the style of the select source button on the agent data source chart

[#noissue] few changes on the inspector chart layout

---

collector/src/main/java/com/navercorp/pinpoint/collector/cluster/GrpcAgentConnection.java
collector/src/main/java/com/navercorp/pinpoint/collector/cluster/route/DefaultRouteHandler.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/AgentServer.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/PinpointGrpcServer.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/PinpointGrpcServerRepository.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/GrpcCommandService.java
collector/src/test/java/com/navercorp/pinpoint/collector/cluster/route/GrpcAgentConnectionTest.java
collector/src/test/java/com/navercorp/pinpoint/collector/receiver/grpc/PinpointGrpcServerTest.java
grpc/src/main/proto/Command.proto
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/thrift/CommandGrpcToThriftMessageConverter.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/thrift/CommandThriftToGrpcMessageConverter.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/grpc/GrpcCommandDispatcher.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/grpc/GrpcEchoService.java

1. add grpcAgentConnection class for cluster management
2. add PinpointGrpcServer for profiler command service

[#4558] add grpcAgentConnection

---

rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/AbstractStreamChannel.java
rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/ClientStreamChannel.java
rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/NettyClientStreamChannel.java
rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/ServerStreamChannel.java
rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/StreamChannel.java
rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/StreamChannelManager.java
rpc/src/test/java/com/navercorp/pinpoint/rpc/stream/StreamChannelTest.java

Create a StreamChannel interface to enhance scalability.

[#5384] Cleanup code related to cluster

---

rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/StreamChannelManager.java

Fix to send data using invalid objects

[#5384] Fix to send data using invalid objects

---

agent/src/main/resources-local/pinpoint.config
agent/src/main/resources-release/pinpoint.config
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/AsyncContextSpanEventEndPointInterceptor.java
commons/src/main/java/com/navercorp/pinpoint/common/trace/ServiceType.java
plugins/assembly/pom.xml
plugins/pom.xml
plugins/spring-webflux/.gitignore
plugins/spring-webflux/pom.xml
plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/SpringWebFluxConstants.java
plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/SpringWebFluxPlugin.java
plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/SpringWebFluxPluginConfig.java
plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/interceptor/BodyInserterRequestBuilderConstructorInterceptor.java
plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/interceptor/BodyInserterRequestBuilderWriteToInterceptor.java
plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/interceptor/ClientHttpRequestClientHeaderAdaptor.java
plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/interceptor/ClientHttpRequestCookieExtractor.java
plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/interceptor/DispatchHandlerHandleMethodInterceptor.java
plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/interceptor/DispatchHandlerInvokeHandlerMethodInterceptor.java
plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/interceptor/ExchangeFunctionMethodInterceptor.java
plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/interceptor/HttpHeadersClientHeaderAdaptor.java
plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/interceptor/WebClientRequestWrapper.java
plugins/spring-webflux/src/main/resources/META-INF/pinpoint/type-provider.yml
plugins/spring-webflux/src/main/resources/META-INF/services/com.navercorp.pinpoint.bootstrap.plugin.ProfilerPlugin

[#5482] Add Spring WebFlux Plugin

---

web/src/main/webapp/v2/src/app/core/components/call-tree/call-tree-container.component.ts
web/src/main/webapp/v2/src/app/core/components/load-chart/load-chart-for-side-bar-container.component.ts
web/src/main/webapp/v2/src/app/core/components/load-chart/load-chart.component.ts
web/src/main/webapp/v2/src/app/core/components/response-summary-chart/response-summary-chart-for-filtered-map-side-bar-container.component.ts
web/src/main/webapp/v2/src/app/core/components/response-summary-chart/response-summary-chart-for-side-bar-container.component.ts
web/src/main/webapp/v2/src/app/core/components/response-summary-chart/response-summary-chart.component.ts
web/src/main/webapp/v2/src/app/core/components/server-map-search-result-viewer/server-map-search-result-viewer-container.component.ts
web/src/main/webapp/v2/src/app/core/components/server-map/class/server-map-data.class.ts
web/src/main/webapp/v2/src/app/core/components/server-map/class/server-map-template-with-gojs.class.ts
web/src/main/webapp/v2/src/app/core/components/server-map/server-map.component.css
web/src/main/webapp/v2/src/app/core/components/side-bar-title/index.ts
web/src/main/webapp/v2/src/app/core/components/side-bar-title/side-bar-title-container.component.html
web/src/main/webapp/v2/src/app/core/components/side-bar-title/side-bar-title-container.component.ts
web/src/main/webapp/v2/src/app/core/components/side-bar-title/side-bar-title.component.css
web/src/main/webapp/v2/src/app/core/components/side-bar-title/side-bar-title.component.html
web/src/main/webapp/v2/src/app/core/components/side-bar-title/side-bar-title.component.ts
web/src/main/webapp/v2/src/app/core/components/side-bar/side-bar-container.component.css
web/src/main/webapp/v2/src/app/core/components/target-list/index.ts
web/src/main/webapp/v2/src/app/core/components/target-list/target-list-container.component.css
web/src/main/webapp/v2/src/app/core/components/target-list/target-list-container.component.html
web/src/main/webapp/v2/src/app/core/components/target-list/target-list-container.component.ts
web/src/main/webapp/v2/src/app/core/components/target-list/target-list.component.css
web/src/main/webapp/v2/src/app/core/components/target-list/target-list.component.html
web/src/main/webapp/v2/src/app/core/components/target-list/target-list.component.ts
web/src/main/webapp/v2/src/app/routes/filtered-map-page/filtered-map-page.component.css
web/src/main/webapp/v2/src/app/routes/main-page/main-page.component.css
web/src/main/webapp/v2/src/app/shared/directives/search-input.directive.ts
web/src/main/webapp/v2/src/assets/i18n/en.json
web/src/main/webapp/v2/src/assets/i18n/ko.json
web/src/main/webapp/v2/src/globals.d.ts

 [#5493] Making selectable all of the list on the sidebar.

---

web/src/main/webapp/features/distributedCallFlow/distributed-call-flow.directive.js

[#5502] bug fix.

---

web/src/main/webapp/v2/src/app/core/components/application-list/application-list-for-configuration-container.component.css
web/src/main/webapp/v2/src/app/core/components/application-list/application-list-for-configuration-container.component.html
web/src/main/webapp/v2/src/app/core/components/application-list/application-list-for-configuration-container.component.ts
web/src/main/webapp/v2/src/app/core/components/application-list/favorite-application-list-for-configuration-container.component.css
web/src/main/webapp/v2/src/app/core/components/application-list/favorite-application-list-for-configuration-container.component.html
web/src/main/webapp/v2/src/app/core/components/application-list/favorite-application-list-for-configuration-container.component.ts

- Display loading progress when add or remove application to favorite list

[#noissue] Add loading progress to favorite list.

---

agent/src/test/java/com/navercorp/pinpoint/plugin/trace/TraceMetadataVerifier.java
collector/src/main/java/com/navercorp/pinpoint/collector/service/TraceService.java
commons/src/main/java/com/navercorp/pinpoint/common/trace/DefaultServiceType.java
commons/src/main/java/com/navercorp/pinpoint/common/trace/ServiceType.java
commons/src/main/java/com/navercorp/pinpoint/common/trace/ServiceTypeBuilder.java
commons/src/main/java/com/navercorp/pinpoint/common/trace/ServiceTypeProperty.java
plugins-loader/src/main/java/com/navercorp/pinpoint/loader/plugins/trace/yaml/ParsedServiceType.java
plugins-loader/src/main/java/com/navercorp/pinpoint/loader/plugins/trace/yaml/ParsedServiceTypeProperty.java
plugins-loader/src/main/java/com/navercorp/pinpoint/loader/trace/ServiceTypeRegistry.java
plugins-loader/src/main/java/com/navercorp/pinpoint/loader/trace/TraceMetadataLoader.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/link/LinkListFactory.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/nodes/NodeListFactory.java
web/src/main/java/com/navercorp/pinpoint/web/service/map/FilteredMapBuilder.java
web/src/main/java/com/navercorp/pinpoint/web/service/map/processor/RpcCallProcessor.java
web/src/test/java/com/navercorp/pinpoint/web/service/map/processor/RpcCallProcessorTest.java

To take care of servermap displayed when embedded library exists.
Such as HTTP4 library embedded in Elasticsearch client library
Only for RPC libraries. (Feature unnecessary for others)
Following terminal node may or may not exist (has to cover both cases)

Alias feature

---

profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/SpanDataSenderProvider.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/StatDataSenderProvider.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/TcpDataSender.java

Fixes span serialization when sending over TCP

---

collector/src/main/java/com/navercorp/pinpoint/collector/mapper/grpc/stat/GrpcAgentStatBatchMapper.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/StatServer.java
collector/src/main/resources/applicationContext-collector.xml

[#4558] Fix StatServer of Collector

---

grpc/src/main/proto/Stat.proto
grpc/src/main/proto/ThreadDump.proto

[#4558] Change gRPC enum

---

web/src/main/webapp/v2/src/app/app.routing.ts
web/src/main/webapp/v2/src/app/core/components/server-and-agent-list/server-and-agent-list-container.component.ts
web/src/main/webapp/v2/src/app/shared/components/url-redirector/url-redirector.component.ts
web/src/main/webapp/v2/src/app/shared/services/application-list-resolver.service.ts
web/src/main/webapp/v2/src/app/shared/services/route-info-collector.service.ts
web/src/main/webapp/v2/src/app/shared/services/server-time-resolver.service.ts
web/src/main/webapp/v2/src/app/shared/services/system-configuration-resolver.service.ts

- Move error page route out of the resolve affected route list

[#noissue] Fix: Restructure the app routing

---

web/src/main/webapp/v2/src/app/core/components/application-list/application-list-for-configuration.component.html
web/src/main/webapp/v2/src/app/core/components/application-list/favorite-application-list-for-configuration.component.html
web/src/main/webapp/v2/src/app/core/components/configuration-favorite/configuration-favorite-container.component.css
web/src/main/webapp/v2/src/app/core/components/configuration-favorite/configuration-favorite-container.component.html
web/src/main/webapp/v2/src/app/core/components/configuration-favorite/configuration-favorite-container.component.ts
web/src/main/webapp/v2/src/app/core/components/configuration-favorite/index.ts
web/src/main/webapp/v2/src/app/core/components/configuration-general/configuration-general-container.component.css
web/src/main/webapp/v2/src/app/core/components/configuration-general/configuration-general-container.component.html
web/src/main/webapp/v2/src/app/core/components/configuration-popup/configuration-popup.component.css
web/src/main/webapp/v2/src/app/core/components/configuration-popup/configuration-popup.component.html
web/src/main/webapp/v2/src/app/core/components/configuration-popup/configuration-popup.component.ts
web/src/main/webapp/v2/src/app/routes/config-page/config-page.component.css
web/src/main/webapp/v2/src/app/routes/config-page/config-page.component.html
web/src/main/webapp/v2/src/app/routes/config-page/config-page.component.ts
web/src/main/webapp/v2/src/app/routes/config-page/config-page.routing.ts
web/src/main/webapp/v2/src/app/routes/config-page/index.ts
web/src/main/webapp/v2/src/app/shared/models/url-path-id.ts

- divide the general menu into two submenus.

[#noissue] Split configuration-general menu

---

grpc/src/main/proto/Cmd.proto
grpc/src/main/proto/Service.proto
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/thrift/CommandGrpcToThriftMessageConverter.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/thrift/CommandThriftToGrpcMessageConverter.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/grpc/ActiveThreadCountStreamSocket.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/grpc/GrpcActiveThreadCountService.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/grpc/GrpcCommandDispatcher.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/grpc/GrpcProfilerStreamSocket.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/grpc/GrpcStreamService.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/grpc/PinpointClientResponseObserver.java

Add Stream function in profiler module using grpc.

[#4558] Add Stream function in profiler module using grpc

---

collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/GrpcClientStreamChannel.java
collector/src/test/java/com/navercorp/pinpoint/collector/receiver/grpc/GrpcClientStreamChannelTest.java
rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/AbstractStreamChannel.java
rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/NettyClientStreamChannel.java
rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/ServerStreamChannel.java
rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/StreamChannelManager.java
rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/StreamChannelState.java

Add ClientStreamChannel for grpc

[#4558] Add ClientStreamChannel for grpc

---

profiler/src/main/java/com/navercorp/pinpoint/profiler/AgentInfoSender.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/GrpcModule.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/ResultConverter.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/ThriftModule.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/AgentInfoSenderProvider.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/thrift/MetadataMessageConverter.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/thrift/ThriftMessageToResultConverter.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/thrift/ThriftMessageToResultConverterProvider.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/metadata/AgentInfo.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/ResultResponse.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/util/AgentInfoFactory.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/AgentInfoSenderTest.java

[#4558] Change AgentInfo type of Agent

---

collector/src/main/java/com/navercorp/pinpoint/collector/cluster/GrpcAgentConnection.java
collector/src/main/java/com/navercorp/pinpoint/collector/cluster/route/StreamRouteHandler.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/PinpointGrpcServer.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/command/ActiveThreadCountService.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/command/EchoService.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/command/GrpcCommandService.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/command/GrpcSimpleCommandService.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/command/GrpcStreamCommandService.java
collector/src/test/java/com/navercorp/pinpoint/collector/cluster/zookeeper/InMemoryZookeeperClient.java
collector/src/test/java/com/navercorp/pinpoint/collector/cluster/zookeeper/ZookeeperJobWorkerTest.java
collector/src/test/java/com/navercorp/pinpoint/collector/receiver/grpc/GrpcClientStreamChannelTest.java
collector/src/test/java/com/navercorp/pinpoint/collector/receiver/grpc/PinpointGrpcServerTest.java
collector/src/test/java/com/navercorp/pinpoint/collector/receiver/grpc/RecordedStreamObserver.java
collector/src/test/java/com/navercorp/pinpoint/collector/receiver/grpc/command/GrpcCommandServiceTest.java
rpc/src/main/java/com/navercorp/pinpoint/rpc/common/SocketState.java
rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/StreamChannelManager.java
rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/StreamChannelRepository.java

enhance collector's grpc command handler

[#4558] enhance grpc handler

---

plugins/hystrix/src/main/java/com/navercorp/pinpoint/plugin/hystrix/descriptor/HystrixCircuitBreakerMethodDescriptor.java
plugins/hystrix/src/main/java/com/navercorp/pinpoint/plugin/hystrix/descriptor/HystrixCollapserMetricsMethodDescriptor.java
plugins/hystrix/src/main/java/com/navercorp/pinpoint/plugin/hystrix/descriptor/HystrixCommandMetricsMethodDescriptor.java
plugins/hystrix/src/main/java/com/navercorp/pinpoint/plugin/hystrix/descriptor/HystrixCommandTimeoutTimerMethodDescriptor.java
plugins/hystrix/src/main/java/com/navercorp/pinpoint/plugin/hystrix/descriptor/HystrixThreadPoolMetricsMethodDescriptor.java

[#noissue] Fix hystrix api type

---

web/src/main/webapp/v2/src/app/core/components/server-map/server-map-for-transaction-list-container.component.ts
web/src/main/webapp/v2/src/app/core/components/server-map/server-map-for-transaction-view-container.component.html
web/src/main/webapp/v2/src/app/core/components/server-map/server-map-for-transaction-view-container.component.ts

- add context popup to server-map to transactionList and transactionView.

[#5565] bug fix.

---

profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/grpc/GrpcCommandService.java

Change handshake to run after stream is ready.

[#4558] grpc command

---

collector/src/main/java/com/navercorp/pinpoint/collector/handler/grpc/GrpcSpanChunkHandler.java

[#4558] Fix SpanChunk handle of Collector

---

collector/src/main/java/com/navercorp/pinpoint/collector/config/SpanReceiverConfiguration.java
collector/src/main/java/com/navercorp/pinpoint/collector/config/StatReceiverConfiguration.java
collector/src/main/java/com/navercorp/pinpoint/collector/monitor/aggregate/Aggregate.java
collector/src/main/java/com/navercorp/pinpoint/collector/monitor/aggregate/AggregateDataSource.java
collector/src/main/java/com/navercorp/pinpoint/collector/monitor/aggregate/AggregateReport.java
collector/src/main/java/com/navercorp/pinpoint/collector/monitor/aggregate/AggregateReportFormatter.java
collector/src/main/java/com/navercorp/pinpoint/collector/monitor/aggregate/AggregateReporter.java
collector/src/main/java/com/navercorp/pinpoint/collector/monitor/aggregate/CollectorAggregateMonitor.java
collector/src/main/java/com/navercorp/pinpoint/collector/monitor/aggregate/IpPortPacketCountAggregateDataSource.java
collector/src/main/java/com/navercorp/pinpoint/collector/monitor/aggregate/IpPortPacketCountAggregator.java
collector/src/main/java/com/navercorp/pinpoint/collector/monitor/aggregate/Slf4jAggregateReporter.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/InetSocketAddressPacketCounter.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/PacketCounter.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/ServerRequestPacketCounter.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/thrift/SpanDispatchHandler.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/thrift/StatDispatchHandler.java
collector/src/main/resources-local/log4j.xml
collector/src/main/resources-release/log4j.xml
collector/src/main/resources/applicationContext-collector.xml
collector/src/main/resources/pinpoint-collector.properties
collector/src/test/java/com/navercorp/pinpoint/collector/config/ConfigTest.java
collector/src/test/java/com/navercorp/pinpoint/collector/monitor/aggregate/IpPortPacketCountAggregatorTest.java
collector/src/test/java/com/navercorp/pinpoint/collector/receiver/DataReceiverGroupTest.java
collector/src/test/resources/test-pinpoint-collector.properties
quickstart/collector/src/main/resources/log4j.xml
quickstart/collector/src/main/resources/pinpoint-collector.properties

This logs the number of span/stat packets received by the collector every minute.
resolves #5522

Allows collector to log received span/stat packet count

---

profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/grpc/AgentGrpcDataSenderProvider.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/AgentGrpcDataSender.java

[#4558] add grpc command

---

web/src/main/java/com/navercorp/pinpoint/web/applicationmap/appender/histogram/DefaultNodeHistogramAppender.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/appender/histogram/DefaultNodeHistogramFactory.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/appender/server/DefaultServerInfoAppender.java
web/src/main/java/com/navercorp/pinpoint/web/service/ResponseTimeHistogramServiceImpl.java
web/src/main/java/com/navercorp/pinpoint/web/view/NodeSerializer.java
web/src/test/java/com/navercorp/pinpoint/web/util/ServiceTypeRegistryMockFactory.java

Add histogram data for As_Alias option.
This PR is to fix https://github.com/naver/pinpoint/pull/5546#issuecomment-488020654
@Xylus please review when you have time. Love to hear if there is any potential problem that I'm not ware of.

[#5411] Add histogram for Alias

---

collector/src/test/java/com/navercorp/pinpoint/collector/receiver/thrift/tcp/AgentEventAsyncTaskServiceTest.java
collector/src/test/java/com/navercorp/pinpoint/collector/receiver/thrift/tcp/AgentLifeCycleAsyncTaskServiceTest.java

[#test] fix test

---

profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/grpc/GrpcCommandService.java

Adjust the reconnection interval to CommandStream

[#4558] Adjust the reconnection interval

---

web/src/main/webapp/v2/src/app/core/components/transaction-detail-contents/transaction-detail-contents-container.component.html
web/src/main/webapp/v2/src/app/core/components/transaction-detail-contents/transaction-detail-contents-container.component.ts

- remove server-map-for-transaction-list-container tag

[#noissue] refactoring server-map code.

---

collector/src/main/java/com/navercorp/pinpoint/collector/cluster/GrpcAgentConnection.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/PinpointGrpcServer.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/command/ActiveThreadLightDumpService.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/command/GrpcCommandService.java
grpc/src/main/proto/Cmd.proto
grpc/src/main/proto/Service.proto
grpc/src/main/proto/ThreadDump.proto
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/grpc/CommandThriftToGrpcMessageConverter.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/thrift/CommandGrpcToThriftMessageConverter.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/grpc/EmptyStreamObserver.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/grpc/GrpcActiveThreadLightDumpService.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/grpc/GrpcCommandDispatcher.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/grpc/GrpcEchoService.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/service/ThreadDumpRequest.java

[#4558] add lightDumpService command

---

collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/PinpointGrpcServer.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/command/ActiveThreadDumpService.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/command/GrpcCommandService.java
grpc/src/main/proto/Cmd.proto
grpc/src/main/proto/Service.proto
grpc/src/main/proto/ThreadDump.proto
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/grpc/CommandThriftToGrpcMessageConverter.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/grpc/GrpcThreadDumpMessageConverter.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/thrift/CommandGrpcToThriftMessageConverter.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/grpc/GrpcActiveThreadDumpService.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/grpc/GrpcCommandDispatcher.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/service/ThreadDumpRequest.java

[#4558] add grpc threaddump service

---

collector/src/main/java/com/navercorp/pinpoint/collector/mapper/grpc/GrpcJvmInfoBoMapper.java
collector/src/main/java/com/navercorp/pinpoint/collector/mapper/grpc/event/GrpcAgentEventBatchMapper.java
collector/src/main/java/com/navercorp/pinpoint/collector/mapper/grpc/event/GrpcAgentEventMapper.java
collector/src/main/java/com/navercorp/pinpoint/collector/mapper/grpc/event/GrpcDeadlockBoMapper.java
collector/src/main/java/com/navercorp/pinpoint/collector/mapper/grpc/event/GrpcThreadDumpBoMapper.java
collector/src/main/java/com/navercorp/pinpoint/collector/mapper/grpc/event/GrpcThreadStateMapper.java
collector/src/main/java/com/navercorp/pinpoint/collector/mapper/grpc/stat/GrpcJvmGcBoMapper.java
collector/src/main/java/com/navercorp/pinpoint/collector/mapper/grpc/stat/GrpcJvmGcTypeMapper.java
collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/ThriftJvmInfoBoMapper.java
collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/event/ThriftThreadDumpBoMapper.java
collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/event/ThriftThreadStateMapper.java
collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/ThriftJvmGcBoMapper.java
collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/ThriftJvmGcTypeMapper.java

[#4558] Add mapper for JvmGcType & ThreadState

---

agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/grpc/GrpcITBase.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/grpc/Grpc_1_21_0_to_IT.java
agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/grpc/Grpc_1_8_0_to_IT.java

[#noissue] fix test

---

profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/TcpDataSender.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/WriteFailFutureListener.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/AgentGrpcDataSender.java
rpc/src/main/java/com/navercorp/pinpoint/rpc/util/ClientFactoryUtils.java

Fix some invalid information when using writeFailFutureListener

[#noissue] fix writeFailFutureListener log

---

web/src/main/webapp/v2/src/app/core/components/scatter-chart/scatter-chart-container.component.css
web/src/main/webapp/v2/src/app/core/components/scatter-chart/scatter-chart-container.component.html
web/src/main/webapp/v2/src/app/core/components/scatter-chart/scatter-chart-container.component.ts
web/src/main/webapp/v2/src/app/core/components/scatter-chart/scatter-chart-for-filtered-map-info-per-server-container.component.css
web/src/main/webapp/v2/src/app/core/components/scatter-chart/scatter-chart-for-filtered-map-info-per-server-container.component.html
web/src/main/webapp/v2/src/app/core/components/scatter-chart/scatter-chart-for-filtered-map-info-per-server-container.component.ts
web/src/main/webapp/v2/src/app/core/components/scatter-chart/scatter-chart-for-filtered-map-side-bar-container.component.css
web/src/main/webapp/v2/src/app/core/components/scatter-chart/scatter-chart-for-filtered-map-side-bar-container.component.html
web/src/main/webapp/v2/src/app/core/components/scatter-chart/scatter-chart-for-filtered-map-side-bar-container.component.ts
web/src/main/webapp/v2/src/app/core/components/scatter-chart/scatter-chart-for-full-screen-mode-container.component.css
web/src/main/webapp/v2/src/app/core/components/scatter-chart/scatter-chart-for-full-screen-mode-container.component.html
web/src/main/webapp/v2/src/app/core/components/scatter-chart/scatter-chart-for-full-screen-mode-container.component.ts
web/src/main/webapp/v2/src/app/core/components/scatter-chart/scatter-chart-for-info-per-server-container.component.css
web/src/main/webapp/v2/src/app/core/components/scatter-chart/scatter-chart-for-info-per-server-container.component.html
web/src/main/webapp/v2/src/app/core/components/scatter-chart/scatter-chart-for-info-per-server-container.component.ts
web/src/main/webapp/v2/src/app/shared/services/url-route-manager.service.ts
web/src/main/webapp/v2/src/assets/i18n/en.json
web/src/main/webapp/v2/src/assets/i18n/ko.json

- If scatter-chart can not open the transaction list page

[#noissue] Show pop-up blocking message.

---

web/src/main/webapp/v2/src/app/core/components/filter-transaction-wizard-popup/filter-transaction-wizard-popup-container.component.ts

- fix application name of filtered-map url

[#5658] bug fix.

---

agent/src/main/resources-local/pinpoint.config
agent/src/main/resources-release/pinpoint-real-env-lowoverhead-sample.config
agent/src/main/resources-release/pinpoint.config
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/DefaultProfilerConfig.java
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/ProfilerConfig.java
commons/src/main/java/com/navercorp/pinpoint/common/util/ByteSizeUnit.java
commons/src/test/java/com/navercorp/pinpoint/common/util/ByteSizeUnitTest.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/DefaultApplicationContext.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/RpcModule.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/SpanClientFactory.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/SpanStatChannelFactory.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/SpanStatConnectTimer.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/StatClientFactory.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/AbstractClientFactoryProvider.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/PinpointClientFactoryProvider.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/SpanClientFactoryProvider.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/SpanDataSenderProvider.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/SpanStatChannelFactoryProvider.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/SpanStatConnectTimerProvider.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/StatClientFactoryProvider.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/StatDataSenderProvider.java
rpc/src/main/java/com/navercorp/pinpoint/rpc/client/DefaultPinpointClientFactory.java
rpc/src/main/java/com/navercorp/pinpoint/rpc/client/DefaultPinpointClientHandler.java
rpc/src/main/java/com/navercorp/pinpoint/rpc/client/PinpointClientFactory.java
rpc/src/main/java/com/navercorp/pinpoint/rpc/client/SocketOption.java

[#5651] Avoid storing excessive buffers when using the TcpDataSender

---

agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/okhttp/OkHttpClient_3_4_0_to_3_x_IT.java

backport #5634 for 1.8.x branch

[#noissue] Fix okhttp test version

---

collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/AbstractHbaseDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseAgentEventDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseAgentInfoDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseAgentLifeCycleDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseApiMetaDataDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseApplicationIndexDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseApplicationTraceIndexDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseHostApplicationMapDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseMapResponseTimeDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseMapStatisticsCalleeDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseMapStatisticsCallerDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseSqlMetaDataDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseStringMetaDataDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseTraceDaoV2.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/stat/HbaseActiveTraceDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/stat/HbaseCpuLoadDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/stat/HbaseDataSourceListDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/stat/HbaseDeadlockThreadCountDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/stat/HbaseDirectBufferDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/stat/HbaseFileDescriptorDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/stat/HbaseJvmGcDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/stat/HbaseJvmGcDetailedDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/stat/HbaseResponseTimeDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/stat/HbaseTransactionDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/statistics/RowKeyMerge.java
collector/src/main/resources/applicationContext-collector.xml
collector/src/test/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseHostApplicationMapDaoTest.java
commons-hbase/src/test/java/com/navercorp/pinpoint/common/hbase/HbaseTableTest.java

[#5669] Cleanup HBaseTables class

---

agent/src/main/resources-local/pinpoint.config
grpc/src/main/java/com/navercorp/pinpoint/grpc/client/ChannelFactory.java
grpc/src/main/java/com/navercorp/pinpoint/grpc/client/ChannelFactoryOption.java
grpc/src/main/java/com/navercorp/pinpoint/grpc/client/UnaryCallDeadlineInterceptor.java
grpc/src/test/java/com/navercorp/pinpoint/grpc/ChannelFactoryTest.java
grpc/src/test/java/com/navercorp/pinpoint/grpc/client/UnaryCallDeadlineInterceptorTest.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/grpc/GrpcTransportConfig.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/grpc/AgentGrpcDataSenderProvider.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/grpc/SpanGrpcDataSenderProvider.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/grpc/StatGrpcDataSenderProvider.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/AgentGrpcDataSender.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/GrpcDataSender.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/SpanGrpcDataSender.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/StatGrpcDataSender.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/sender/grpc/AgentGrpcDataSenderTestMain.java

support deadline option for unary message

[#4558] support deadline option for unary message

---

web/pom.xml
web/src/main/webapp/v2/src/app/core/components/agent-list/agent-list.component.ts
web/src/main/webapp/v2/src/app/core/components/call-tree/call-tree.component.html
web/src/main/webapp/v2/src/app/core/components/transaction-table-grid/transaction-table-grid.component.html

- Fix the callback function accordingly

[#noissue] Fix build configuration

---

grpc/src/main/java/com/navercorp/pinpoint/grpc/client/ChannelFactory.java
grpc/src/main/java/com/navercorp/pinpoint/grpc/client/ClientOption.java
grpc/src/test/java/com/navercorp/pinpoint/grpc/client/ClientOptionTest.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/grpc/GrpcTransportConfig.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/grpc/AgentGrpcDataSenderProvider.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/grpc/SpanGrpcDataSenderProvider.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/grpc/StatGrpcDataSenderProvider.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/context/grpc/GrpcTransportConfigTest.java
profiler/src/test/resources/pinpoint.config

[#4558] Change gRPC transport config

---

collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/SpanService.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/StatService.java
collector/src/test/java/com/navercorp/pinpoint/collector/receiver/grpc/SpanClientMock.java
collector/src/test/java/com/navercorp/pinpoint/collector/receiver/grpc/StatClientMock.java
grpc/src/main/proto/Service.proto
grpc/src/main/proto/Span.proto
grpc/src/main/proto/Stat.proto
grpc/src/test/java/com/navercorp/pinpoint/grpc/ChannelFactoryTest.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/AgentGrpcDataSender.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/SpanGrpcDataSender.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/StatGrpcDataSender.java

[#4558] Add protocol buffers message

---

collector/src/main/java/com/navercorp/pinpoint/collector/cluster/zookeeper/ZookeeperJobWorker.java
collector/src/test/java/com/navercorp/pinpoint/collector/cluster/zookeeper/InMemoryZookeeperClient.java
collector/src/test/java/com/navercorp/pinpoint/collector/cluster/zookeeper/ZookeeperJobWorkerTest.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/cluster/zookeeper/CreateNodeMessage.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/cluster/zookeeper/CuratorZookeeperClient.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/cluster/zookeeper/ZookeeperClient.java
commons-server/src/test/java/com/navercorp/pinpoint/common/server/cluster/zookeeper/CuratorZookeeperClientTest.java
flink/src/main/java/com/navercorp/pinpoint/flink/cluster/FlinkServerRegister.java
web/src/main/java/com/navercorp/pinpoint/web/cluster/zookeeper/PushZnodeJob.java
web/src/main/java/com/navercorp/pinpoint/web/cluster/zookeeper/ZookeeperClusterDataManager.java
web/src/main/java/com/navercorp/pinpoint/web/cluster/zookeeper/ZookeeperClusterDataManagerHelper.java

change zookeeper client's parameter to CreateNodeMessage class

[#cleanup] cleanup zookeeper code

---

commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/SpanBo.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/SpanEventBo.java

Remove unnecessary variable in toString method.

[#cleanup] cleanup log

---

collector/src/main/java/com/navercorp/pinpoint/collector/config/GrpcPropertiesServerOptionBuilder.java
collector/src/test/java/com/navercorp/pinpoint/collector/config/AgentBaseDataReceiverConfigurationTest.java
collector/src/test/java/com/navercorp/pinpoint/collector/config/SpanReceiverConfigurationTest.java
collector/src/test/java/com/navercorp/pinpoint/collector/config/StatReceiverConfigurationTest.java
collector/src/test/resources/test-pinpoint-collector.properties
grpc/src/main/java/com/navercorp/pinpoint/grpc/client/ClientOption.java
grpc/src/main/java/com/navercorp/pinpoint/grpc/server/ServerFactory.java
grpc/src/main/java/com/navercorp/pinpoint/grpc/server/ServerOption.java
grpc/src/test/java/com/navercorp/pinpoint/grpc/client/ClientOptionTest.java
grpc/src/test/java/com/navercorp/pinpoint/grpc/server/ServerOptionTest.java

[#4558] Change gRPC client/server options

---

collector/src/test/java/com/navercorp/pinpoint/collector/receiver/grpc/AgentServerTestMain.java
collector/src/test/java/com/navercorp/pinpoint/collector/receiver/grpc/MetadataClientMock.java
collector/src/test/java/com/navercorp/pinpoint/collector/receiver/grpc/MetadataClientTestMain.java
grpc/src/main/java/com/navercorp/pinpoint/grpc/client/ChannelFactory.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/grpc/GrpcTransportConfig.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/AgentDataSender.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/GrpcModule.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/GrpcModuleLifeCycle.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/MetadataDataSender.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/ThriftModule.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/ThriftModuleLifeCycle.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/AgentInfoSenderProvider.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/ApiMetaDataServiceProvider.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/grpc/MetadataGrpcDataSenderProvider.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/metadata/DefaultSqlMetaDataService.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/metadata/DefaultStringMetaDataService.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/AgentGrpcDataSender.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/GrpcDataSender.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/MetadataGrpcDataSender.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/context/module/DefaultApplicationContextTest.java

[#4558] Add metdata gRPC data sender

---

profiler/src/main/java/com/navercorp/pinpoint/profiler/AgentInfoSender.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/grpc/AgentGrpcDataSenderProvider.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/AgentGrpcDataSender.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/GrpcDataSender.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/PingStreamContext.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/StatGrpcDataSender.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/sender/grpc/AgentGrpcDataSenderTestMain.java

[#4558] Fit agentGrpcDataSender

---

doc/faq.md
quickstart/web/src/main/webapp/scripts/extra/google-analytics.js
web/src/main/webapp/scripts/extra/google-analytics.js

Change the http protocol in the access url from http to https for Google Analytics

[#5815] Change the http protocol for Google Analytics

---

pom.xml

- spotbug  3.1.7-> 3.1.12
- pmd 3.9.0->3.12.0

[#5818] Update maven-plugin

---

web/src/main/webapp/features/configuration/application/alarm-rule.directive.js
web/src/main/webapp/v2/src/app/core/components/alarm-rule-list/alarm-rule-create-and-update.component.css
web/src/main/webapp/v2/src/app/core/components/alarm-rule-list/alarm-rule-create-and-update.component.html
web/src/main/webapp/v2/src/app/core/components/alarm-rule-list/alarm-rule-create-and-update.component.ts
web/src/main/webapp/v2/src/app/core/components/alarm-rule-list/alarm-rule-data.service.ts
web/src/main/webapp/v2/src/app/core/components/alarm-rule-list/alarm-rule-list-container.component.css
web/src/main/webapp/v2/src/app/core/components/alarm-rule-list/alarm-rule-list-container.component.html
web/src/main/webapp/v2/src/app/core/components/alarm-rule-list/alarm-rule-list-container.component.ts
web/src/main/webapp/v2/src/app/core/components/alarm-rule-list/alarm-rule-list.component.css
web/src/main/webapp/v2/src/app/core/components/alarm-rule-list/alarm-rule-list.component.html
web/src/main/webapp/v2/src/app/core/components/alarm-rule-list/alarm-rule-list.component.ts
web/src/main/webapp/v2/src/app/core/components/application-list/application-list-for-configuration-alarm-container.component.css
web/src/main/webapp/v2/src/app/core/components/application-list/application-list-for-configuration-alarm-container.component.ts
web/src/main/webapp/v2/src/app/core/components/application-list/application-list-for-header-container.component.ts
web/src/main/webapp/v2/src/app/core/components/application-list/application-list-interaction-for-configuration.service.ts
web/src/main/webapp/v2/src/app/core/components/call-tree/call-tree.component.ts
web/src/main/webapp/v2/src/app/core/components/configuration-alarm/configuration-alarm-container.component.css
web/src/main/webapp/v2/src/app/core/components/configuration-alarm/configuration-alarm-container.component.ts
web/src/main/webapp/v2/src/app/core/components/empty-inspector-contents/empty-inspector-contents-container.component.ts
web/src/main/webapp/v2/src/app/core/components/pinpoint-user/pinpoint-user-create-and-update.component.css
web/src/main/webapp/v2/src/app/core/components/user-group/user-group-create-and-update.component.css
web/src/main/webapp/v2/src/app/core/models/application.ts
web/src/main/webapp/v2/src/app/shared/components/form-field-error-message/form-field-error-message.component.css
web/src/main/webapp/v2/src/assets/i18n/en.json
web/src/main/webapp/v2/src/assets/i18n/ko.json
web/src/main/webapp/v2/src/styles.css

- Refactor the V2 alarm code
- Change style

[#noissue] Remove the duplication check on alarm registration

---

grpc/src/main/java/com/navercorp/pinpoint/grpc/StatusError.java
grpc/src/main/java/com/navercorp/pinpoint/grpc/StatusErrors.java
grpc/src/test/java/com/navercorp/pinpoint/grpc/StatusErrorsTest.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/grpc/GrpcCommandService.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/PingStreamContext.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/ResponseStreamObserver.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/RetryResponseStreamObserver.java

[#4558] Add gRPC StatusError

---

web/src/main/webapp/common/help/help-content-en.js
web/src/main/webapp/common/help/help-content-ko.js
web/src/main/webapp/common/services/tps-chart-dao.service.js
web/src/main/webapp/v2/src/app/core/components/inspector-chart/agent-tps-chart-container.component.ts
web/src/main/webapp/v2/src/assets/i18n/en.json
web/src/main/webapp/v2/src/assets/i18n/ko.json

- Add "Skipped New", "Skipped Continuation" types

[#noissue] Add new types on TPS inspector chart

---

collector/src/main/java/com/navercorp/pinpoint/collector/cluster/route/filter/LoggingFilter.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/PinpointGrpcServer.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/command/GrpcCommandService.java
collector/src/main/java/com/navercorp/pinpoint/collector/service/async/AgentLifeCycleAsyncTaskService.java
web/src/main/java/com/navercorp/pinpoint/web/controller/ScatterChartController.java
web/src/main/java/com/navercorp/pinpoint/web/websocket/ActiveThreadCountHandler.java
web/src/main/java/com/navercorp/pinpoint/web/websocket/ActiveThreadCountWorker.java
web/src/main/java/com/navercorp/pinpoint/web/websocket/WorkerActiveManager.java

[#4558] Fix log format of gRPC message

---

collector/src/main/java/com/navercorp/pinpoint/collector/config/AgentBaseDataReceiverConfiguration.java
collector/src/main/java/com/navercorp/pinpoint/collector/config/GrpcPropertiesServerOptionBuilder.java
collector/src/main/java/com/navercorp/pinpoint/collector/config/SpanReceiverConfiguration.java
collector/src/main/java/com/navercorp/pinpoint/collector/config/StatReceiverConfiguration.java
collector/src/main/resources/pinpoint-collector.properties
collector/src/test/java/com/navercorp/pinpoint/collector/config/AgentBaseDataReceiverConfigurationTest.java
collector/src/test/java/com/navercorp/pinpoint/collector/config/SpanReceiverConfigurationTest.java
collector/src/test/java/com/navercorp/pinpoint/collector/config/StatReceiverConfigurationTest.java
collector/src/test/resources/test-pinpoint-collector.properties
grpc/src/main/java/com/navercorp/pinpoint/grpc/server/ServerOption.java

[#4558] Change collector gRPC options for byte unit

---

bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/classloader/LauncherBootLoader.java
collector/src/main/resources/applicationContext-collector.xml
collector/src/main/resources/applicationContext-hbase.xml
commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/PinpointThreadPoolExecutorFactoryBean.java
flink/src/main/resources/applicationContext-hbase.xml
web/src/main/resources/applicationContext-hbase.xml

- Fix high priority issue in the findbugs

[#noissue] Fix static analysis issues

---

grpc/pom.xml

- Remove unnecessary dependency

[#3094] dependency cleanup

---

profiler/src/main/java/com/navercorp/pinpoint/profiler/context/grpc/GrpcAnnotationValueMapper.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/context/grpc/GrpcAnnotationValueMapperTest.java
web/src/main/java/com/navercorp/pinpoint/web/vo/callstacks/AnnotationRecordFormatter.java

[#4558] Fix annotation value mapper of gRPC

---

web/src/main/webapp/v2/package-lock.json
web/src/main/webapp/v2/package.json
web/src/main/webapp/v2/src/app/core/components/info-per-server/info-per-server-container.component.css
web/src/main/webapp/v2/src/app/core/components/info-per-server/info-per-server-for-filtered-map-container.component.css
web/src/main/webapp/v2/src/app/core/components/server-list/server-list.component.css

[#noissue] Update dependency

---

bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/util/spring/AntPathMatcher.java
bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/util/spring/AntPathMatcherTest.java

- this bug does not affect the pinpoint

[#noissue] Fix potential bug in AntPathMatcher

---

hbase/hbase-schema/src/main/java/com/navercorp/pinpoint/hbase/schema/reader/xml/XmlHbaseSchemaParser.java

Fixes resource leak when reading pinpoint hbase schema definition file

---

web/src/main/webapp/v2/src/app/core/components/inspector-chart/inspector-chart.component.ts
web/src/main/webapp/v2/src/app/core/components/load-chart/load-chart.component.ts
web/src/main/webapp/v2/src/app/core/components/response-summary-chart/response-summary-chart-container.component.ts
web/src/main/webapp/v2/src/app/core/components/response-summary-chart/response-summary-chart.component.ts
web/src/main/webapp/v2/src/app/core/components/side-bar/side-bar-container.component.html
web/src/main/webapp/v2/src/app/core/components/side-bar/side-bar-for-filtered-map-container.component.html
web/src/main/webapp/v2/src/app/core/components/target-list/target-list.component.ts

- Use config api instead of set method in order not to cause the redraw immediately

[#noissue] Fix: Set the y axis max correctly

---

collector/src/main/java/com/navercorp/pinpoint/collector/cluster/ClusterPointStateChangedEventHandler.java
collector/src/main/java/com/navercorp/pinpoint/collector/cluster/DisabledProfilerClusterManager.java
collector/src/main/java/com/navercorp/pinpoint/collector/cluster/ProfilerClusterManager.java
collector/src/main/java/com/navercorp/pinpoint/collector/cluster/zookeeper/ZookeeperClusterService.java
collector/src/main/java/com/navercorp/pinpoint/collector/cluster/zookeeper/ZookeeperProfilerClusterManager.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/command/GrpcCommandService.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/thrift/tcp/AgentBaseDataReceiver.java
collector/src/test/java/com/navercorp/pinpoint/collector/cluster/zookeeper/ZookeeperJobWorkerTest.java

Fixes that the Collector is not running when the cluster setting is disabled.

[#4558] Fixes that the Collector is not running

---

pom.xml

Now adds the following entries to all pinpoint jar manifest files after maven build:
Implementation-Title
Implementation-Vendor
Implementation-Vendor-Id
Implementation-Version

Adds default implementation entries to pinpoint jar manifests

---

agent-it/src/test/java/com/navercorp/pinpoint/plugin/log4j2/Log4j2IT.java
agent-it/src/test/resources/pinpoint-grpc-plugin-test.config
agent-it/src/test/resources/pinpoint-spring-bean-test.config
agent/src/main/resources-local/pinpoint.config
agent/src/main/resources-release/pinpoint.config
plugins/assembly/pom.xml
plugins/log4j2/.gitignore
plugins/log4j2/pom.xml
plugins/log4j2/src/main/java/com/navercorp/pinpoint/plugin/log4j2/Log4j2Config.java
plugins/log4j2/src/main/java/com/navercorp/pinpoint/plugin/log4j2/Log4j2Plugin.java
plugins/log4j2/src/main/java/com/navercorp/pinpoint/plugin/log4j2/interceptor/LogEventFactoryInterceptor.java
plugins/log4j2/src/main/java/com/navercorp/pinpoint/plugin/log4j2/interceptor/LoggingEventOfLog4j2Interceptor.java
plugins/log4j2/src/main/resources/META-INF/services/com.navercorp.pinpoint.bootstrap.plugin.ProfilerPlugin
plugins/log4j2/src/test/java/com/navercorp/pinpoint/plugin/log4j2/Log4j2ConfigTest.java
plugins/log4j2/src/test/java/com/navercorp/pinpoint/plugin/log4j2/Log4j2PluginTest.java
plugins/log4j2/src/test/java/com/navercorp/pinpoint/plugin/log4j2/interceptor/LogEventFactoryInterceptorTest.java
plugins/pom.xml

log4j2 plugin local self test~~

[#5971] support log4j2.1~2.11

---

agent-it/pom.xml
agent-it/src/test/java/com/navercorp/pinpoint/plugin/log4j2/Log4j2IT.java

see #5971
Include log4j2 version 2.0.

update agent-it for log4j2

---

profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/SpanGrpcDataSender.java

[#4558] Add grpc client interceptor of SpanGrpcDataSender

---

plugins/log4j2/src/main/java/com/navercorp/pinpoint/plugin/log4j2/Log4j2Plugin.java

add target profiling class when use "Making All Loggers Asynchronous" function

[#5971] add target profiling class

---

profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/SpanGrpcDataSender.java

[#4558] Fix grpc client interceptor of SpanGrpcDataSender

---

agent-it/src/test/java/com/navercorp/pinpoint/plugin/log4j2/Log4j2ForAsyncLoggerIT.java

add IT for log4j2 async logger

---

collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/SpanService.java
collector/src/main/resources/applicationContext-collector.xml
collector/src/test/java/com/navercorp/pinpoint/collector/receiver/grpc/SpanClientMock.java
collector/src/test/java/com/navercorp/pinpoint/collector/receiver/grpc/SpanClientTestMain.java
collector/src/test/java/com/navercorp/pinpoint/collector/receiver/grpc/SpanServerTestMain.java
grpc/src/main/java/com/navercorp/pinpoint/grpc/client/ChannelFactory.java
grpc/src/main/java/com/navercorp/pinpoint/grpc/client/ClientOption.java
grpc/src/test/java/com/navercorp/pinpoint/grpc/client/ClientOptionTest.java

[#4558] Add grpc context executor of collector - IT

---

collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/GrpcReceiver.java

Allows to set the ServerInterceptor in GrpcReceiver using spring configuration

[#4558] Allows to set the ServerInterceptor using spring configuration

---

web/src/main/webapp/v2/src/app/core/components/server-map/class/server-map-diagram-with-gojs.class.ts

- Since the previous scale(1.3) was not really noticeable, increase it to 2

[#noissue] Increase the scale on double click

---

collector/src/test/java/com/navercorp/pinpoint/collector/receiver/grpc/SpanClientMock.java
grpc/pom.xml
profiler/src/test/java/com/navercorp/pinpoint/profiler/sender/grpc/DiscardClientInterceptorTest.java
web/src/main/java/com/navercorp/pinpoint/web/cluster/zookeeper/ZookeeperClusterDataManager.java

- Remove jsr305, error_prone_annotations

[#4558] Dependency cleanup

---

collector/src/main/java/com/navercorp/pinpoint/collector/config/AgentBaseDataReceiverConfiguration.java
collector/src/main/java/com/navercorp/pinpoint/collector/config/SpanReceiverConfiguration.java
collector/src/main/java/com/navercorp/pinpoint/collector/config/StatReceiverConfiguration.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/AgentService.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/MetadataService.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/ServerRequestFactory.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/SpanService.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/StatService.java
collector/src/main/resources/applicationContext-collector.xml
collector/src/main/resources/pinpoint-collector.properties
collector/src/test/java/com/navercorp/pinpoint/collector/config/AgentBaseDataReceiverConfigurationTest.java
collector/src/test/java/com/navercorp/pinpoint/collector/config/SpanReceiverConfigurationTest.java
collector/src/test/java/com/navercorp/pinpoint/collector/config/StatReceiverConfigurationTest.java
collector/src/test/java/com/navercorp/pinpoint/collector/receiver/grpc/AgentServerTestMain.java
collector/src/test/java/com/navercorp/pinpoint/collector/receiver/grpc/StatServerTestMain.java
collector/src/test/resources/test-pinpoint-collector.properties

#4558 
~~~
collector.receiver.grpc.span.server.executor.thread.size=8
collector.receiver.grpc.span.server.executor.queue.size=256
collector.receiver.grpc.span.server.executor.monitor.enable=true
collector.receiver.grpc.span.worker.executor.thread.size=32
collector.receiver.grpc.span.worker.executor.queue.size=1024
collector.receiver.grpc.span.worker.executor.monitor.enable=true
~~~

[#4558] Add grpc server executor of collector

---

collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/command/ActiveThreadCountService.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/command/GrpcCommandService.java

[#4558] cleanup unnecessary code

---

agent-it/src/test/java/com/navercorp/pinpoint/plugin/jdk7/rabbitmq/spring/SpringAmqpRabbit_2_1_x_to_2_x_IT.java

remove v2.1.9.RELEASE test (related issue https://github.com/spring-projects/spring-amqp/issues/1082)
support method for greater than v2.2.0 RELEASE

[#fixtest] fix plugin test

---

web/src/main/webapp/v2/src/app/core/components/configuration-popup/configuration-popup-container.component.html
web/src/main/webapp/v2/src/app/core/components/configuration-popup/configuration-popup-container.component.ts
web/src/main/webapp/v2/src/app/core/components/configuration-popup/configuration-popup.component.html
web/src/main/webapp/v2/src/app/core/components/configuration-popup/configuration-popup.component.ts
web/src/main/webapp/v2/src/app/shared/services/dynamic-popup.service.ts

Adding a menu for navigation to V1 on V2

[#noissue] Add a menu for navigation to V1

---

web/src/main/webapp/v2/src/app/core/components/server-map/class/server-map-template-with-gojs.class.ts
web/src/main/webapp/v2/src/app/core/components/server-map/class/server-map-theme.ts
web/src/main/webapp/v2/src/app/core/components/server-map/server-map.component.html
web/src/main/webapp/v2/src/app/routes/filtered-map-page/filtered-map-page.component.css
web/src/main/webapp/v2/src/app/routes/main-page/main-page.component.css
web/src/main/webapp/v2/src/app/routes/transaction-detail-page/transaction-detail-page.component.css
web/src/main/webapp/v2/src/styles.css

- Set the background color of it according to the color around

[#noissue] Change the background color of link text on server map

---

agent/src/main/resources-local/pinpoint.config
agent/src/main/resources-release/pinpoint.config

Slash style comment is not compatible with jdk property utility.

fix agent config comment error

---

web/src/main/webapp/v2/src/app/core/components/server-map/class/server-map-template-with-gojs.class.ts

- Locate it above the pointed node

[#noissue] Fix self pointing link position on servermap

---

collector/src/main/java/com/navercorp/pinpoint/collector/config/SpanReceiverConfiguration.java
collector/src/main/java/com/navercorp/pinpoint/collector/config/StatReceiverConfiguration.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/GrpcReceiver.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/SpanService.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/StatService.java
collector/src/main/resources/applicationContext-collector.xml
collector/src/main/resources/pinpoint-collector.properties
collector/src/test/java/com/navercorp/pinpoint/collector/config/SpanReceiverConfigurationTest.java
collector/src/test/java/com/navercorp/pinpoint/collector/config/StatReceiverConfigurationTest.java
collector/src/test/java/com/navercorp/pinpoint/collector/receiver/grpc/SpanClientMock.java
collector/src/test/java/com/navercorp/pinpoint/collector/receiver/grpc/SpanServerTestMain.java
collector/src/test/java/com/navercorp/pinpoint/collector/receiver/grpc/StatServerTestMain.java
collector/src/test/resources/test-pinpoint-collector.properties
grpc/src/main/java/com/navercorp/pinpoint/grpc/server/ServerFactory.java
grpc/src/main/java/com/navercorp/pinpoint/grpc/server/StreamExecutorRejectedExecutionRequestScheduler.java
grpc/src/main/java/com/navercorp/pinpoint/grpc/server/StreamExecutorServerInterceptor.java
grpc/src/main/java/com/navercorp/pinpoint/grpc/server/StreamExecutorService.java
grpc/src/test/java/com/navercorp/pinpoint/grpc/server/StreamExecutorRejectedExecutionRequestSchedulerTest.java

[#4558] Add grpc stream executor server interceptor

---

agent-it8/src/test/java/com/navercorp/pinpoint/plugin/elasticsearchbboss/ElasticsearchExecutorIT.java
agent-it8/src/test/java/com/navercorp/pinpoint/plugin/elasticsearchbboss/ElasticsearchExecutorIT569.java
agent/src/main/resources-local/pinpoint.config
agent/src/main/resources-release/pinpoint-real-env-lowoverhead-sample.config
agent/src/main/resources-release/pinpoint.config

Enable Elasticsearch bboss plugin to fix bug #6048

Enable Elasticsearch bboss plugin to fix bug #6048

---

collector/src/test/java/com/navercorp/pinpoint/collector/receiver/grpc/SpanServerTestMain.java
grpc/pom.xml

[#4558] Upgrade grpc-java netty version to 4.1.42

---

web/src/main/webapp/features/distributedCallFlow/distributed-call-flow.directive.js
web/src/main/webapp/v2/src/app/core/components/call-tree/call-tree.component.css
web/src/main/webapp/v2/src/app/core/components/call-tree/call-tree.component.ts
web/src/main/webapp/v2/src/app/core/components/transaction-table-grid/transaction-table-grid.component.css
web/src/main/webapp/v2/src/app/core/components/transaction-table-grid/transaction-table-grid.component.ts

- Replace `&nbsp;` with padding and margin

[#6130] Handle no-break space issue

---

collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/filter/SequenceSpanEventFilter.java

Try to fix https://github.com/naver/pinpoint/issues/6124

#6124 SpanEvents with negative sequence should be filtered at collector side

---

web/src/main/webapp/v2/src/app/core/components/filter-transaction-wizard-popup/filter-transaction-wizard-popup-container.component.ts
web/src/main/webapp/v2/src/app/core/components/link-context-popup/link-context-popup-container.component.ts
web/src/main/webapp/v2/src/app/core/components/scatter-chart/scatter-chart-for-filtered-map-info-per-server-container.component.html
web/src/main/webapp/v2/src/app/core/components/scatter-chart/scatter-chart-for-filtered-map-info-per-server-container.component.ts
web/src/main/webapp/v2/src/app/core/components/scatter-chart/scatter-chart-for-filtered-map-side-bar-container.component.html
web/src/main/webapp/v2/src/app/core/components/scatter-chart/scatter-chart-for-filtered-map-side-bar-container.component.ts
web/src/main/webapp/v2/src/app/core/components/scatter-chart/scatter-chart-for-full-screen-mode-container.component.html
web/src/main/webapp/v2/src/app/core/components/scatter-chart/scatter-chart-for-full-screen-mode-container.component.ts
web/src/main/webapp/v2/src/app/core/components/scatter-chart/scatter-chart-for-info-per-server-container.component.html
web/src/main/webapp/v2/src/app/core/components/scatter-chart/scatter-chart-for-info-per-server-container.component.ts
web/src/main/webapp/v2/src/app/core/components/server-map/server-map-for-filtered-map-container.component.ts
web/src/main/webapp/v2/src/app/core/components/target-list/target-list-container.component.ts
web/src/main/webapp/v2/src/app/core/components/target-list/target-list.component.css
web/src/main/webapp/v2/src/app/core/utils/hint-param-maker.ts

- Give proper parameters on clicking the filter button on the sidebar

[#noissue] Fix: Navigate to the filtered page on the sidebar

---

plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/interceptor/ConsumerRecordEntryPointInterceptor.java

Fix problems that are not traced in the kafka under specific environment

[#fix] Fix problems that are not traced

---

plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/interceptor/ConsumerRecordEntryPointInterceptor.java

backport #6149 to 1.8.x
related issue #6148

[#backport] Fix problems that are not traced

---

plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/KafkaPlugin.java
plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/interceptor/ProducerConstructorInterceptor.java

[#backport] Adds support Kafka 2.2.0+

---

profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/SpanDataSenderProvider.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/StatDataSenderProvider.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/TcpDataSender.java

[#backport] Allows to set queueSize in the TcpDataSender

---

web/src/main/webapp/v2/src/app/core/components/server-map/class/server-map-data.class.ts
web/src/main/webapp/v2/src/app/core/components/server-map/server-map-for-filtered-map-data.service.ts

- Filter-target node/link won't be included in merging on filtered servermap any longer
- Add exception response handling in filtered data request

[#noissue] Exclude the filter-target node/link in merge on servermap

---

collector/src/main/resources/applicationContext-collector.xml
web/src/main/resources/applicationContext-web.xml

- Pinpoint-Web and Pinpoint-Collector now support `SYSTEM_PROPERTIES_MODE_OVERRIDE` mode
eg) Add VM options : -Dhbase.client.host=${YOUR_HBASE_HOST}

[#6156] Support SYSTEM_PROPERTIES_MODE_OVERRIDE mode

---

web/src/main/webapp/v2/src/app/core/components/scatter-chart/scatter-chart-container.component.ts
web/src/main/webapp/v2/src/app/core/components/scatter-chart/scatter-chart-for-filtered-map-side-bar-container.component.ts
web/src/main/webapp/v2/src/app/core/components/scatter-chart/scatter-chart-interaction.service.ts
web/src/main/webapp/v2/src/app/core/components/scatter-chart/scatter-chart.component.ts
web/src/main/webapp/v2/src/app/core/components/server-map/class/server-map-diagram-with-gojs.class.ts
web/src/main/webapp/v2/src/app/core/components/server-map/class/server-map-template-with-gojs.class.ts
web/src/main/webapp/v2/src/app/core/components/server-map/server-map-container.component.ts
web/src/main/webapp/v2/src/app/core/components/server-map/server-map-for-filtered-map-container.component.ts
web/src/main/webapp/v2/src/app/core/components/server-status/server-status-container.component.ts
web/src/main/webapp/v2/src/globals.d.ts

- Clicking instance number and clicking request circle used to provide some advanced features but decided to remove it because it could confuse users and unlikely to be used

[#noissue] Remove extra servermap features

---

web/src/main/webapp/v2/src/app/core/components/server-map/class/server-map-diagram-with-gojs.class.ts

- Add 1px as an adjustment for the different behavior on different environments(os * browser)

[#noissue] Handle contextmenu on servermap

---

collector/src/main/java/com/navercorp/pinpoint/collector/config/AgentBaseDataReceiverConfiguration.java
collector/src/main/java/com/navercorp/pinpoint/collector/config/CollectorConfiguration.java
collector/src/main/java/com/navercorp/pinpoint/collector/config/FlinkConfiguration.java
collector/src/main/java/com/navercorp/pinpoint/collector/config/GrpcAgentDataReceiverConfiguration.java
collector/src/main/java/com/navercorp/pinpoint/collector/config/GrpcPropertiesServerOptionBuilder.java
collector/src/main/java/com/navercorp/pinpoint/collector/config/GrpcSpanReceiverConfiguration.java
collector/src/main/java/com/navercorp/pinpoint/collector/config/GrpcStatReceiverConfiguration.java
collector/src/main/java/com/navercorp/pinpoint/collector/config/SpanReceiverConfiguration.java
collector/src/main/java/com/navercorp/pinpoint/collector/config/StatReceiverConfiguration.java
collector/src/main/resources/applicationContext-collector.xml
collector/src/test/java/com/navercorp/pinpoint/collector/config/AnnotationVisitorTest.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/config/AnnotationVisitor.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/config/ConfigurationUtils.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/config/LoggingEvent.java
flink/src/main/java/com/navercorp/pinpoint/flink/config/FlinkConfiguration.java
web/src/main/java/com/navercorp/pinpoint/web/config/ConfigProperties.java
web/src/main/java/com/navercorp/pinpoint/web/config/LogConfiguration.java
web/src/main/java/com/navercorp/pinpoint/web/config/WebConfig.java
web/src/main/resources/applicationContext-web.xml

- web : -Dpinpoint.web.config.location=YOUR_PROPERTY_PATH
- collector : -Dpinpoint.collector.config.location=YOUR_PROPERTY_PATH

#6156 Add external property support

---

web/src/main/webapp/v2/src/app/core/components/server-map/class/server-map-diagram-with-gojs.class.ts

- Bind timeout instead of the adjust value on Y coordinate because there could be a misposition

[#noissue] Fix contextmenu event on servermap

---

profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/ReconnectExecutor.java

Enhance missing exception handling

[#4558] Enhance missing exception handling

---

doc/alarm.md

[#6263] update batch doc for how to execute batch and setting value of properties

---

bootstrap-java9/src/main/java/com/navercorp/pinpoint/bootstrap/java9/module/ModuleSupport.java
commons/src/main/java/com/navercorp/pinpoint/common/util/JvmVersion.java
pom.xml
profiler-optional/profiler-optional-jdk9/pom.xml
profiler-optional/profiler-optional-jdk9/src/main/java/com/navercorp/pinpoint/profiler/instrument/classloading/Java9DefineClass.java
profiler-optional/profiler-optional-jdk9/src/main/java/com/navercorp/pinpoint/profiler/instrument/classloading/JavaLangAccessHelper.java
profiler-optional/profiler-optional-jdk9/src/main/java/com/navercorp/pinpoint/profiler/shutdown/Java9ShutdownHookRegister.java
profiler-optional/profiler-optional-jdk9/src/test/java/com/navercorp/pinpoint/profiler/instrument/classloading/JavaLangAccessHelperTest.java
profiler-optional/profiler-optional-jdk9/src/test/java/com/navercorp/pinpoint/profiler/shutdown/Java9ShutdownHookRegisterTest.java

[#6260] Update ASM version 7.1 to 7.2

---

agent/src/main/resources/pinpoint.config
commons/src/main/java/com/navercorp/pinpoint/common/trace/ServiceType.java
plugins/assembly/pom.xml
plugins/jdk-completable-future/pom.xml
plugins/jdk-completable-future/src/main/java/com/navercorp/pinpoint/plugin/jdk/completable/JdkCompletableFutureConstants.java
plugins/jdk-completable-future/src/main/java/com/navercorp/pinpoint/plugin/jdk/completable/JdkCompletableFuturePlugin.java
plugins/jdk-completable-future/src/main/java/com/navercorp/pinpoint/plugin/jdk/completable/JdkCompletableFuturePluginConfig.java
plugins/jdk-completable-future/src/main/java/com/navercorp/pinpoint/plugin/jdk/completable/interceptor/CompletableFutureMethodInterceptor.java
plugins/jdk-completable-future/src/main/resources/META-INF/pinpoint/type-provider.yml
plugins/jdk-completable-future/src/main/resources/META-INF/services/com.navercorp.pinpoint.bootstrap.plugin.ProfilerPlugin
plugins/pom.xml
profiler/src/main/java/com/navercorp/pinpoint/profiler/UnmodifiableClassFilter.java

[#6244] Add CompletableFuture Plugin

---

collector/src/main/java/com/navercorp/pinpoint/collector/handler/grpc/GrpcAgentEventHandler.java
collector/src/main/java/com/navercorp/pinpoint/collector/handler/grpc/GrpcAgentStatHandlerV2.java
collector/src/main/java/com/navercorp/pinpoint/collector/handler/thrift/ThriftAgentEventHandler.java
collector/src/main/java/com/navercorp/pinpoint/collector/handler/thrift/ThriftAgentInfoHandler.java
collector/src/main/java/com/navercorp/pinpoint/collector/handler/thrift/ThriftAgentStatHandlerV2.java
collector/src/main/java/com/navercorp/pinpoint/collector/handler/thrift/ThriftApiMetaDataHandler.java
collector/src/main/java/com/navercorp/pinpoint/collector/handler/thrift/ThriftSpanChunkHandler.java
collector/src/main/java/com/navercorp/pinpoint/collector/handler/thrift/ThriftSpanHandler.java
collector/src/main/java/com/navercorp/pinpoint/collector/handler/thrift/ThriftSqlMetaDataHandler.java
collector/src/main/java/com/navercorp/pinpoint/collector/handler/thrift/ThriftStringMetaDataHandler.java

* AgentEventHandler
* AgentInfoHandler
* AgentStatHandlerV2
* ApiMetaDataHandler
* SpanChunkHandler
* SpanHandler
* SqlMetaDataHandler
* StringMetaDataHandler

[#noissue] Improve handler logs on collector

---

agent/src/main/resources/pinpoint.config
plugins/reactor/README.md
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/ReactorPluginConfig.java
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/interceptor/CoreSubscriberInterceptor.java

Trace reactor subscriber onError.

[#noissue] Update error event of reactor

---

pom.xml

[#noissue] Remove unused maven plugin

---

plugins/elasticsearch/src/main/java/com/navercorp/pinpoint/plugin/elasticsearch/ElasticsearchPlugin.java

[#noissue] Update transform condition of elasticsearch plugin

---

plugins/redis-lettuce/src/main/java/com/navercorp/pinpoint/plugin/redis/lettuce/LettucePlugin.java
plugins/redis-lettuce/src/main/java/com/navercorp/pinpoint/plugin/redis/lettuce/interceptor/LettuceMethodInterceptor.java

#4843
Trace async/reactive methods.
* io.lettuce.core.RedisAsyncCommandsImpl
* io.lettuce.core.cluster.RedisAdvancedClusterAsyncCommandsImpl
* io.lettuce.core.cluster.RedisClusterPubSubAsyncCommandsImpl
* io.lettuce.core.pubsub.RedisPubSubAsyncCommandsImpl
* io.lettuce.core.AbstractRedisReactiveCommands
* io.lettuce.core.cluster.RedisAdvancedClusterReactiveCommandsImpl
* io.lettuce.core.cluster.RedisClusterPubSubReactiveCommandsImpl
* io.lettuce.core.pubsub.RedisPubSubReactiveCommandsImpl
* io.lettuce.core.RedisReactiveCommandsImpl
* io.lettuce.core.sentinel.RedisSentinelReactiveCommandsImpl

[#4843] Add async/reactive of lettuce plugin

---

plugins/redis-redisson/src/main/java/com/navercorp/pinpoint/plugin/redis/redisson/RedissonConstants.java
plugins/redis-redisson/src/main/java/com/navercorp/pinpoint/plugin/redis/redisson/RedissonPlugin.java
plugins/redis-redisson/src/main/java/com/navercorp/pinpoint/plugin/redis/redisson/interceptor/ReactiveMethodInterceptor.java
plugins/redis-redisson/src/main/resources/META-INF/pinpoint/type-provider.yml

#5378
* org.redisson.RedissonReactive

[#5378] Update async and reactive of redission plugin

---

plugins/rabbitmq/src/main/java/com/navercorp/pinpoint/plugin/rabbitmq/client/aspect/BasicPropertiesHelper.java
plugins/rabbitmq/src/main/java/com/navercorp/pinpoint/plugin/rabbitmq/client/aspect/ChannelAspect.java

#6260 
Changed ChannelAspect code of RabbitMQ Plugin.
Move code to a separate class file, leaving only the call part.
Fixed due to changes in [ASM 7.2](https://asm.ow2.io/versions.html)
* 317872: Throw an exception if visitFrame used incorrectly

[#6260] Update rabbitmq transform for ASM 7.2

---

agent/src/assembly/component/core.xml
agent/src/main/resources/profiles/local/log4j.xml
agent/src/main/resources/profiles/release/log4j.xml
bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/agentdir/AgentDirectory.java

[#6253] Changing Agent log policy

---

plugins/apache-dubbo/src/main/java/com/navercorp/pinpoint/plugin/apache/dubbo/interceptor/ApacheDubboProviderInterceptor.java

[#6321] Fix spanid duplicate in dubbo

---

web/src/main/webapp/v2/src/app/core/components/inspector-chart/agent-jvm-heap-chart-container.ts
web/src/main/webapp/v2/src/app/core/components/inspector-chart/agent-jvm-non-heap-chart-container.ts

- Change the type of it from "Line" to "Bar" because of the visualization difficulty

[#noissue] Show Major GC data as bar chart on inspector

---

pom.xml

[#6359] Rollback Node.js version

---

pom.xml
web/pom.xml

- Delete all frontend build files

[#6359] Add forceclean option for frontend-build

---

web/src/main/angular/package-lock.json
web/src/main/angular/package.json

- Update it because of the memory issue when running UI build

[#noissue] Update angular cli dependency

---

collector/src/main/java/com/navercorp/pinpoint/collector/cluster/ClusterPointRepository.java
collector/src/main/java/com/navercorp/pinpoint/collector/cluster/GrpcAgentConnection.java

Fix missing inserting grpc cluster information when collector reconnected zookeeper.

[#4558] Fix missing inserting information

---

test/src/main/java/com/navercorp/pinpoint/test/plugin/DependencyResolver.java

- http://central.maven.org inaccessible

[#6369] Change maven repo

---

agent/src/main/resources/profiles/local/pinpoint-env.config
agent/src/main/resources/profiles/release/pinpoint-env.config
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/ReactorConstants.java
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/ReactorPeriodicSchedulerMethodDescriptor.java
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/ReactorPlugin.java
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/ReactorPluginConfig.java
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/interceptor/PeriodicSchedulerTaskRunMethodInterceptor.java
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/interceptor/SchedulerAndWorkerScheduleMethodInterceptor.java
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/interceptor/SchedulerAndWorkerTaskRunMethodInterceptor.java
plugins/reactor/src/main/resources/META-INF/pinpoint/type-provider.yml

[#6456] Update reactor plugin for scheduler

---

agent-it8/src/test/java/com/navercorp/pinpoint/plugin/jdbc/mssql/MSSSqlConnectionIT.java
profiler-test/src/main/java/com/navercorp/pinpoint/test/junit4/JunitAgentConfigPath.java
profiler-test/src/main/java/com/navercorp/pinpoint/test/junit4/TestClassWrapper.java

- @PinpointConfig -> @JunitAgentConfigPath

[#6369] Rename @PinpointConfig

---

agent/src/main/resources/profiles/local/pinpoint-env.config
agent/src/main/resources/profiles/release/pinpoint-env.config
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/ReactorPlugin.java
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/ReactorPluginConfig.java
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/interceptor/CoreSubscriberInterceptor.java

[#6456] Add onError () error filtering of ReactorPlugin

---

plugins/mssql-jdbc/src/main/resources/META-INF/pinpoint/type-provider.yml

MSSQL_JDBC_QUERY -> MSSQLSERVER

[#6369] Change mssql plugin's service type description

---

plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/MongoPlugin.java
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/ReactorPlugin.java

[#noissue] Fix transform of MongoPlugin & ReactorPlugin

---

plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/KafkaPlugin.java

Fix NullPointerException of KafkaPlugin
~~~
java.lang.NullPointerException
at com.navercorp.pinpoint.plugin.kafka.KafkaPlugin$1.doInTransform(KafkaPlugin.java:67)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerGuardDelegate.transform(MatchableClassFileTransformerGuardDelegate.java:75)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.BaseClassFileTransformer.transform(BaseClassFileTransformer.java:56)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.DefaultClassFileTransformerDispatcher.transform(DefaultClassFileTransformerDispatcher.java:95)
at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.context.javamodule.ClassFileTransformerModuleHandler.transform(ClassFileTransformerModuleHandler.java …

[#noissue] Fix NPE of KafkaPlugin

---

profiler/src/main/java/com/navercorp/pinpoint/profiler/context/grpc/GrpcSpanMessageConverter.java

Change the Span.acceptorHost value to be saved even if there is no parentApplicationName value.

[#noissue] Change the Span.acceptorHost value to be saved

---

plugins/rabbitmq/src/main/java/com/navercorp/pinpoint/plugin/rabbitmq/client/interceptor/ChannelBasicPublishInterceptor.java

#6507 
The same code exists in RabbitMQ Plugin, and it is modified.

[#noissue] Fix destinationId of rabbitmq plugin

---

commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseTemplate2.java

Improves existing "count 0" log messages.

[#noissue] Fix waiting asyn operations message of collector

---

commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/codec/stat/TestAgentStatDataPointFactory.java

before : createValue(10, 20) -> can to create value (1 ~ 9)

[#noissue] fix creating invalid random value

---

collector/src/main/java/com/navercorp/pinpoint/collector/receiver/thrift/udp/ReusePortSocketOptionHolder.java
collector/src/main/resources/applicationContext-collector.xml

[#6564] Supports REUSE_PORT option in UDP

---

doc/powered-by.md

Add Echemi

---

web/src/main/resources/batch.properties
web/src/main/resources/batch/applicationContext-batch-sender.xml
web/src/main/resources/batch/applicationContext-batch.xml

set default properties since the default feature are not functional in XML.

Alarm properties

---

agent/src/main/resources/profiles/local/pinpoint-env.config
agent/src/main/resources/profiles/release/pinpoint-env.config
plugins/netty/src/main/java/com/navercorp/pinpoint/plugin/netty/NettyConfig.java
plugins/netty/src/main/java/com/navercorp/pinpoint/plugin/netty/NettyPlugin.java
plugins/netty/src/main/java/com/navercorp/pinpoint/plugin/netty/interceptor/ChannelCloseMethodInterceptor.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/ReactorNettyPlugin.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/ReactorNettyPluginConfig.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/AbstractHttpServerHandleInterceptor.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/ChannelOperationsChannelMethodInterceptor.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/HttpServerHandleHttpServerStateInterceptor.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/HttpServerHandleStateInterceptor.java
plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/interceptor/DispatchHandlerHandleMethodInterceptor.java

[#6656] Add end-point methods of Reactor Netty Plugin

---

commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/ServerTraceMetadataLoaderService.java
commons/src/main/java/com/navercorp/pinpoint/common/util/Filter.java
plugins-loader/src/main/java/com/navercorp/pinpoint/loader/plugins/trace/TraceMetadataProviderLoader.java

Remove the use of inaccessible classes when the agent is not applied

[#6683] Fixing a plugin version conflict problem in a web module

---

plugins/jboss/src/main/java/com/navercorp/pinpoint/plugin/jboss/interceptor/StandardHostValveInvokeInterceptor.java
plugins/jboss/src/main/java/com/navercorp/pinpoint/plugin/jboss/util/Servlet2ApiHelper.java
plugins/jboss/src/main/java/com/navercorp/pinpoint/plugin/jboss/util/Servlet3ApiHelper.java
plugins/jboss/src/main/java/com/navercorp/pinpoint/plugin/jboss/util/ServletApiHelper.java

Patch to support JBoss EAP 4.X (Servlet 2.X)

[#6682] JBoss 4 support patch

---

plugins/websphere/src/main/java/com/navercorp/pinpoint/plugin/websphere/IRequestParameterExtractor.java

[#6696] Fix parameter extractor of WebSpherePlugin

---

collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseAgentEventDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseAgentInfoDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseAgentLifeCycleDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseApiMetaDataDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseApplicationIndexDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseApplicationTraceIndexDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseHostApplicationMapDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseMapResponseTimeDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseSqlMetaDataDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseStringMetaDataDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseTraceDaoV2.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/stat/HbaseActiveTraceDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/stat/HbaseCpuLoadDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/stat/HbaseDataSourceListDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/stat/HbaseDeadlockThreadCountDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/stat/HbaseDirectBufferDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/stat/HbaseFileDescriptorDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/stat/HbaseJvmGcDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/stat/HbaseJvmGcDetailedDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/stat/HbaseResponseTimeDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/stat/HbaseTransactionDao.java
collector/src/main/java/com/navercorp/pinpoint/collector/handler/thrift/ThriftAgentEventHandler.java
collector/src/main/java/com/navercorp/pinpoint/collector/util/CollectorUtils.java

[#6704] Add agentId and applicationName inspection logic

---

collector/src/main/java/com/navercorp/pinpoint/collector/cluster/ClusterAddressProvider.java
collector/src/main/java/com/navercorp/pinpoint/collector/cluster/connection/CollectorClusterConnector.java
collector/src/main/java/com/navercorp/pinpoint/collector/cluster/zookeeper/ZookeeperClusterManager.java
collector/src/main/java/com/navercorp/pinpoint/collector/util/AddressParser.java
collector/src/main/java/com/navercorp/pinpoint/collector/util/MultipleAddress.java
collector/src/test/java/com/navercorp/pinpoint/collector/cluster/ClusterAddressProviderTest.java
rpc/src/main/java/com/navercorp/pinpoint/rpc/util/ClientFactoryUtils.java

Collector try to connect to web with representative address.
If web's address is multiple and representative address can not access from outside, then Collector can not connect to Web.
If the collector fails to connect, it attempts to connect sequentially to all addresses on the web to resolve them.

[#6712] collector support to connect multiple address

---

rpc/src/main/java/com/navercorp/pinpoint/rpc/server/ChannelPropertiesFactory.java

[#noissue] fix logging object

---

bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/ContainerResolver.java
bootstrap/src/test/java/com/navercorp/pinpoint/bootstrap/ContainerResolverTest.java

If System Property pinpoint.container.auto is set to true, enable group agent feature automatically when running in docker/container environment.

[#6759] auto group agent if pinpoint.container.auto is set

---

collector/src/main/java/com/navercorp/pinpoint/collector/cluster/ClusterAddressProvider.java
commons/src/main/java/com/navercorp/pinpoint/common/util/AgentUuidUtils.java

[#noissue] Remove system.out.println()

---

web/src/main/angular/src/app/core/components/transaction-short-info/transaction-short-info-container.component.css

- In web ui transaction detail view, put application name to the first column by default for quicker navigation.
before:
after:
- Update style for transaction short info container to show some hide characters.
before:
after:

Update transaction detail view in web.

---

web/src/main/java/com/navercorp/pinpoint/web/view/TransactionInfoViewModel.java
web/src/main/java/com/navercorp/pinpoint/web/vo/callstacks/RecordFactory.java

Remove escape json logic of call tree

[#noissue] Escape call-tree title of web

---

commons/src/main/java/com/navercorp/pinpoint/common/trace/AnnotationKey.java
commons/src/main/java/com/navercorp/pinpoint/common/trace/ServiceType.java
plugins-it/pom.xml
plugins-it/process-it/pom.xml
plugins-it/process-it/src/test/java/com/navercorp/pinpoint/plugin/process/ProcessIT.java
plugins-it/process-it/src/test/resources/pinpoint-process-test.config
plugins/assembly/pom.xml
plugins/pom.xml
plugins/process/pom.xml
plugins/process/src/main/java/com/navercorp/pinpoint/plugin/process/ProcessPlugin.java
plugins/process/src/main/java/com/navercorp/pinpoint/plugin/process/ProcessPluginConfig.java
plugins/process/src/main/java/com/navercorp/pinpoint/plugin/process/ProcessPluginConstants.java
plugins/process/src/main/java/com/navercorp/pinpoint/plugin/process/ProcessPluginTypeProvider.java
plugins/process/src/main/java/com/navercorp/pinpoint/plugin/process/interceptor/Java9PidProvider.java
plugins/process/src/main/java/com/navercorp/pinpoint/plugin/process/interceptor/PidProvider.java
plugins/process/src/main/java/com/navercorp/pinpoint/plugin/process/interceptor/PidProviderFactory.java
plugins/process/src/main/java/com/navercorp/pinpoint/plugin/process/interceptor/ProcessExecuteInterceptor.java
plugins/process/src/main/java/com/navercorp/pinpoint/plugin/process/interceptor/ProcessImplProvider.java
plugins/process/src/main/java/com/navercorp/pinpoint/plugin/process/interceptor/UNIXProcessPidProvider.java
plugins/process/src/main/java/com/navercorp/pinpoint/plugin/process/interceptor/UnsupportPidProvider.java
plugins/process/src/main/resources/META-INF/services/com.navercorp.pinpoint.bootstrap.plugin.ProfilerPlugin
plugins/process/src/main/resources/META-INF/services/com.navercorp.pinpoint.common.trace.TraceMetadataProvider
plugins/process/src/test/java/com/navercorp/pinpoint/plugin/process/interceptor/MockProcess.java
plugins/process/src/test/java/com/navercorp/pinpoint/plugin/process/interceptor/PidProviderFactoryTest.java
plugins/process/src/test/java/com/navercorp/pinpoint/plugin/process/interceptor/UNIXProcessPidProviderTest.java
plugins/process/src/test/java/com/navercorp/pinpoint/plugin/process/interceptor/UnsupportPidProviderTest.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/UnmodifiableClassFilter.java

Added ServiceTypes, Annotations, and Configurations
ServiceTypes: 
PROCESS - 6005
Annotations: 
process.command - 180
Configurations: 
profiler.process.tracing.enabled=true or false

[#6762] Add Process Fork Plugin

---

web/src/main/angular/src/app/core/components/configuration-installation/configuration-installation-jvm-argument-info.component.css
web/src/main/angular/src/app/core/components/configuration-installation/configuration-installation-jvm-argument-info.component.html
web/src/main/angular/src/app/core/components/duplication-check/duplication-check.component.css

- Red colored text on duplication check error message
- Change the jvm argument info copy icon
- Locate the copied notification text below the copy icon

[#noissue] Change some styles on installation page

---

web/src/main/java/com/navercorp/pinpoint/web/service/TransactionInfoServiceImpl.java

[#noissue] Add ENDPOINT-Record to TransactionInfo

---

web/src/main/java/com/navercorp/pinpoint/web/dao/ApplicationIndexDao.java
web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseApplicationIndexDao.java
web/src/main/java/com/navercorp/pinpoint/web/service/ApplicationServiceImpl.java
web/src/test/java/com/navercorp/pinpoint/web/alarm/AlarmReaderTest.java
web/src/test/java/com/navercorp/pinpoint/web/alarm/checker/GcCountCheckerTest.java
web/src/test/java/com/navercorp/pinpoint/web/alarm/checker/HeapUsageRateCheckerTest.java
web/src/test/java/com/navercorp/pinpoint/web/alarm/checker/JvmCpuUsageRateCheckerTest.java

[#noissue] Performance optimization isAvailableApplicationName

---

web/src/main/angular/src/app/core/components/agent-search-input/agent-search-input-container.component.css
web/src/main/angular/src/app/core/components/application-list/application-list-for-agent-management-container.component.css
web/src/main/angular/src/app/core/components/application-list/application-list-for-configuration-alarm-container.component.css
web/src/main/angular/src/app/core/components/application-list/application-list-for-configuration-container.component.css
web/src/main/angular/src/app/core/components/pinpoint-user/pinpoint-user-container.component.css
web/src/main/angular/src/app/core/components/server-map-search-result-viewer/server-map-search-result-viewer-container.component.css
web/src/main/angular/src/app/core/components/target-list/target-list-container.component.css
web/src/main/angular/src/app/core/components/user-group/user-group-container.component.css

- Apply text-overflow ellipsis if it's necessary

[#noissue] Apply consistent style for search inputs

---

web/src/main/angular/src/app/core/components/transaction-id-search/index.ts
web/src/main/angular/src/app/core/components/transaction-id-search/transaction-id-search-container.component.css
web/src/main/angular/src/app/core/components/transaction-id-search/transaction-id-search-container.component.html
web/src/main/angular/src/app/core/components/transaction-id-search/transaction-id-search-container.component.ts
web/src/main/angular/src/app/routes/main-page/index.ts
web/src/main/angular/src/app/routes/main-page/main-page.component.html

Add search pTxId feature. 
An input box & a search icon are put on the header. 
Type or paste pTxId which may be found from application log and _press the "Enter" key or click on the search icon_, a new page which shows the transaction detail would be open.

update UI, add search pTxId

---

web/src/main/angular/src/app/core/components/transaction-id-search/index.ts
web/src/main/angular/src/app/core/components/transaction-id-search/transaction-id-search-container.component.css
web/src/main/angular/src/app/core/components/transaction-id-search/transaction-id-search-container.component.html
web/src/main/angular/src/app/core/components/transaction-id-search/transaction-id-search-container.component.ts
web/src/main/angular/src/app/routes/main-page/main-page.component.css
web/src/main/angular/src/app/routes/main-page/main-page.component.html
web/src/main/angular/src/app/routes/main-page/main-page.component.ts
web/src/main/angular/src/app/shared/services/dynamic-popup.service.ts

- Shows only search icon and display the search input as popup if clicked

[#noissue] Handle ptxid search input display on small screen

---

bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/monitor/metric/CustomMetric.java
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/monitor/metric/CustomMetricRegistry.java
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/monitor/metric/IntCounter.java
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/monitor/metric/LongCounter.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/monitor/metric/CustomMetricRegistryAdaptor.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/monitor/metric/CustomMetricRegistryService.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/monitor/metric/CustomMetricWrapperFactory.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/monitor/metric/DefaultCustomMetricRegistryFilter.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/monitor/metric/DefaultCustomMetricRegistryService.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/monitor/metric/DisabledCustomMetricRegistryService.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/monitor/metric/IntCounterWrapper.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/monitor/metric/LongCounterWrapper.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/monitor/metric/custom/IntCountMetricVo.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/monitor/metric/custom/LongCountMetricVo.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/context/monitor/metric/CustomMetricRegistryServiceTest.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/monitor/metric/CustomMetricRegistryFilterTest.java

IntCount -> IntCounter
LongCount -> LongCounter

[#6809] Change classname

---

doc/quickstart.md
quickstart/README.Win.en.md
quickstart/README.Win.ko.md

In windows environment, update the way to run cmd in relative path.

[document] update quickstart's README for windows

---

commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/util/CellUtils.java
commons-hbase/src/test/java/com/navercorp/pinpoint/common/hbase/util/CellUtilsTest.java
web/src/main/java/com/navercorp/pinpoint/web/mapper/AgentEventMapper.java
web/src/main/java/com/navercorp/pinpoint/web/mapper/AgentIdMapper.java
web/src/main/java/com/navercorp/pinpoint/web/mapper/ApplicationNameMapper.java

[#noissue] Add CellUtils

---

doc/alarm.md
web/src/main/java/com/navercorp/pinpoint/web/batch/BatchConfiguration.java
web/src/main/resources/applicationContext-web-profile.xml
web/src/main/resources/batch.properties
web/src/test/java/com/navercorp/pinpoint/web/batch/BatchConfigurationTest.java

it is determined that there is some overlap between the setting and the batch profile, so we have decided to delete this setting.

[#6871] Remove unnecessary batch.enable setting

---

web/src/main/angular/src/app/core/components/transaction-table-grid/transaction-table-grid-container.component.ts
web/src/main/angular/src/app/core/components/transaction-table-grid/transaction-table-grid.component.ts

show endpoint in transaction list table

---

collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/KeepAliveService.java

Change the access modifier from private to protected for that user can pass the data with the what user want to pass.

[#noissue] Change access modifier in KeepAliveService

---

collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/KeepAliveService.java
collector/src/main/resources/applicationContext-collector-grpc.xml
grpc/src/main/java/com/navercorp/pinpoint/grpc/Header.java
grpc/src/main/java/com/navercorp/pinpoint/grpc/server/AgentHeaderReader.java
grpc/src/main/java/com/navercorp/pinpoint/grpc/server/HeaderPropagationInterceptor.java
grpc/src/main/java/com/navercorp/pinpoint/grpc/server/ServerFactory.java

1. Add properties field for Header class
2. Change headerPropagationInterceptor to be configurable with Spring

[#noissue] Add properties field for Header class

---

web/src/main/angular/src/app/core/components/server-map/server-map-for-filtered-map-data.service.ts

- Refactor the recursive request logic

[#noissue] Cancel progressing request on pause in the filter page

---

web/src/main/angular/src/app/core/components/inspector-chart/agent-cpu-chart-container.ts
web/src/main/angular/src/app/core/components/inspector-chart/agent-jvm-heap-chart-container.ts
web/src/main/angular/src/app/core/components/inspector-chart/agent-jvm-non-heap-chart-container.ts

- Fill the below area item
- Switch the color between some items

[#noissue] Change inspector chart style

---

web/src/main/angular/src/app/core/components/server-map/class/server-map-diagram-with-cytoscapejs.class.ts

- Add text-wrap option to break the line under the max-width condtion

[#noissue] Handle long endpoint name

---

web/src/main/angular/src/app/core/components/filter-app-transaction-wizard-popup/filter-app-transaction-wizard-popup-container.component.ts
web/src/main/angular/src/app/core/components/filter-transaction-wizard-popup/filter-transaction-wizard-popup-container.component.ts
web/src/main/angular/src/app/core/components/inbound-outbound-range-selector/inbound-outbound-range-selector-container.component.ts
web/src/main/angular/src/app/core/components/link-context-popup/link-context-popup-container.component.ts
web/src/main/angular/src/app/core/components/real-time/real-time-container.component.ts
web/src/main/angular/src/app/core/components/real-time/real-time-paging-container.component.ts
web/src/main/angular/src/app/core/components/server-map-options/server-map-options-container.component.ts
web/src/main/angular/src/app/core/components/server-map/server-map-for-filtered-map-container.component.ts
web/src/main/angular/src/app/core/components/server-map/server-map-for-filtered-map-data.service.ts
web/src/main/angular/src/app/core/components/side-bar/side-bar-for-filtered-map-container.component.ts
web/src/main/angular/src/app/core/components/target-list/target-list-container.component.ts
web/src/main/angular/src/app/core/utils/url-utils.ts
web/src/main/angular/src/app/routes/config-page/config-page.component.ts
web/src/main/angular/src/app/shared/services/url-route-manager.service.ts

- Rename the queryParam as queryParams

[#noissue] Fix: Release the loading when data is empty in the filterpage

---

plugins/redis-lettuce/src/main/java/com/navercorp/pinpoint/plugin/redis/lettuce/LettucePlugin.java
plugins/redis-lettuce/src/main/java/com/navercorp/pinpoint/plugin/redis/lettuce/interceptor/LettuceMethodInterceptor.java
plugins/redis-lettuce/src/main/java/com/navercorp/pinpoint/plugin/redis/lettuce/interceptor/RedisClusterClientConstructorInterceptor.java

lettuce plugin support redis cluster.

lettuce plugin support redis cluster.

---

collector/src/main/resources/profiles/local/log4j2.xml
collector/src/main/resources/profiles/release/log4j2.xml
web/src/main/resources/profiles/local/log4j2.xml
web/src/main/resources/profiles/release/log4j2.xml

change hours log format (hh -> HH)

[#6826] Change hours log format

---

agent/src/main/resources/profiles/local/pinpoint.config
agent/src/main/resources/profiles/release/pinpoint.config
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/ReactorNettyPlugin.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/ReactorNettyPluginConfig.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/AbstractHttpServerHandleInterceptor.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/CorePublisherInterceptor.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/CoreSubscriberInterceptor.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/MethodFilterExtractor.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/SubscribeOrReturnMethodInterceptor.java

[#7057] Update WebFlux(Reactor-Netty) Plugin

---

web/src/main/java/com/navercorp/pinpoint/web/WebApp.java

Fix UnsatisfiedDependencyException in Pinpoint web when using batch profile
close #7091

[#7091] Fix batch auto configuration error

---

doc/application-inspector.md

fix broken link in docs/application-inspector.md : 
https://github.com/naver/pinpoint/blob/master/web/src/main/resources/pinpoint-web.properties -> https://github.com/naver/pinpoint/blob/master/web/src/main/resources/pinpoint-web-root.properties
and some typo fix : porperties -> properties
Signed-off-by: sim manseop <tlqaksqhr@naver.com>

[#noissue] fix broken link in docs/application-inspector.md

---

collector/src/main/resources/pinpoint-collector-root.properties
collector/src/test/resources/test-pinpoint-collector.properties
flink/src/main/resources/profiles/local/pinpoint-flink.properties
flink/src/main/resources/profiles/release/pinpoint-flink.properties

`statistics.flushPeriod` configuration removed since 1.7.2 version

[#cleanup] remove unused configuration

---

collector/src/main/java/com/navercorp/pinpoint/collector/config/CollectorConfiguration.java
collector/src/main/java/com/navercorp/pinpoint/collector/monitor/CollectorMetric.java
collector/src/main/resources/pinpoint-collector-root.properties
collector/src/test/resources/test-pinpoint-collector.properties

add option to set jmx domain name

[#7149] Add CollectorMetric information to JMX

---

pom.xml

Upgrade ASM version from 7.2 to 8.0.1

[#noissue] Upgrade ASM version 8.0.1

---

agent/src/main/resources/pinpoint-root.config
agent/src/main/resources/profiles/local/pinpoint.config
agent/src/main/resources/profiles/release/pinpoint.config
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/ServerConfig.java
bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/config/ServerConfigTest.java
plugins/akka-http/src/main/java/com/navercorp/pinpoint/plugin/akka/http/AkkaHttpConfig.java
plugins/jboss/src/main/java/com/navercorp/pinpoint/plugin/jboss/JbossConfig.java
plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/JettyConfiguration.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/ReactorNettyPluginConfig.java
plugins/resin/src/main/java/com/navercorp/pinpoint/plugin/resin/ResinConfig.java
plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/TomcatConfig.java
plugins/undertow/src/main/java/com/navercorp/pinpoint/plugin/undertow/UndertowConfig.java
plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/VertxHttpServerConfig.java
plugins/vertx/src/test/java/com/navercorp/pinpoint/plugin/vertx/VertxHttpServerConfigTest.java
plugins/weblogic/src/main/java/com/navercorp/pinpoint/plugin/weblogic/WeblogicConfiguration.java
plugins/websphere/src/main/java/com/navercorp/pinpoint/plugin/websphere/WebsphereConfiguration.java

[#7161] Add server config

---

agent/src/main/resources/profiles/local/pinpoint.config
agent/src/main/resources/profiles/release/pinpoint.config

- implicit default values are now written exclusively
- deleted unused values

[#noissue] Update agent plugin configuration texts

---

collector/src/main/java/com/navercorp/pinpoint/collector/cluster/zookeeper/ZookeeperClusterManager.java
collector/src/main/java/com/navercorp/pinpoint/collector/util/AddressParser.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/join/JoinApplicationStatBo.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/join/JoinTransactionBo.java
commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/stat/join/JoinApplicationStatBoTest.java
commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/stat/join/JoinTransactionBoTest.java
commons/src/main/java/com/navercorp/pinpoint/common/util/NetUtils.java
web/src/main/java/com/navercorp/pinpoint/web/mapper/stat/sampling/sampler/JoinTransactionSampler.java

Maybe some of you like `LIst` instead of `List` 😁

[#noissue] typofix (LIst -> List)

---

plugins/grpc/src/main/java/com/navercorp/pinpoint/plugin/grpc/descriptor/GrpcServerCallMethodDescriptor.java
plugins/grpc/src/main/java/com/navercorp/pinpoint/plugin/grpc/interceptor/server/ServerStreamCreatedInterceptor.java

`GrpcServerCallMethodDescritpro` -> `GrpcServerCallMethodDescriptor`

[#noissue] Fix class name

---

plugins-it/plugins-it-utils/src/test/java/com/navercorp/pinpoint/pluginit/utils/SocketUtilsTest.java
plugins-it/plugins-it-utils/src/test/java/com/navercorp/pinpoint/pluginit/utils/WebServerTest.java

Add test for `plugins-it/plugins-it-utils`

[#noissue] Add test for `plugins-it/plugins-it-utils`

---

web/src/test/java/com/navercorp/pinpoint/web/alarm/AlarmWriterIsolationTest.java

case 1 : when SequenceCount is less than TimingCount, Send alarm
case 2 : when SequenceCount is equal to TimingCount, Don't send alarm

[#noissue] Add AlarmWriter Isolation Test

---

plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/interceptor/ConsumerRecordEntryPointInterceptor.java

Fix typo createTrace.createTrace() -> traceFactory.createTrace()

[#noissue] Fix typo createTrace.createTrace() -> traceFactory.createTrace()

---

rpc/src/main/java/com/navercorp/pinpoint/rpc/client/PinpointClientHandshaker.java
rpc/src/main/java/com/navercorp/pinpoint/rpc/server/DefaultPinpointServer.java

Null pointer dereference of '(List)cluster.get(...)' where null is returned from a map or a collection.

[#noissue] Fix klocwork critical level

---

.travis.yml

Remove deprecated key `sudo`

---

collector/src/main/resources/profiles/local/log4j2.xml

Include month in log filename.

collector, update local stat log filename format

---

web/src/main/angular/src/app/core/components/load-chart/load-chart-container.component.ts
web/src/main/angular/src/app/core/components/response-summary-chart/response-summary-chart-container.component.ts
web/src/main/angular/src/app/core/components/server-status/server-status-container.component.ts

- Initialize some properties on switching app

[#noissue] Fix: Switching app on selecting an agent

---

bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/request/AsyncListenerInterceptor.java
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/request/AsyncListenerInterceptorHelper.java
plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/TomcatAsyncListener.java
plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/TomcatConstants.java
plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/interceptor/RequestStartAsyncInterceptor.java
plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/interceptor/StandardHostValveInvokeInterceptor.java

[#7333] Fix asyncListener of tomcat plugin

---

web/src/main/java/com/navercorp/pinpoint/web/applicationmap/ApplicationMapBuilder.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/appender/histogram/DefaultNodeHistogramAppender.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/appender/histogram/NodeHistogramAppender.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/appender/server/DefaultServerInfoAppender.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/appender/server/ServerInfoAppender.java
web/src/main/java/com/navercorp/pinpoint/web/service/FilteredMapServiceImpl.java
web/src/main/java/com/navercorp/pinpoint/web/service/LinkDataLimiter.java
web/src/main/java/com/navercorp/pinpoint/web/service/MapServiceImpl.java
web/src/main/resources/pinpoint-web-root.properties
web/src/test/java/com/navercorp/pinpoint/web/applicationmap/ApplicationMapBuilderTest.java
web/src/test/java/com/navercorp/pinpoint/web/applicationmap/appender/histogram/NodeHistogramAppenderTest.java
web/src/test/java/com/navercorp/pinpoint/web/applicationmap/appender/server/ServerInfoAppenderTest.java
web/src/test/java/com/navercorp/pinpoint/web/service/LinkDataLimiterTest.java

[#7313] Add limiter on the number of link data and on build time

---

web/src/main/angular/src/app/core/components/scatter-chart/class/scatter-chart-renderer-manager.class.ts

- Fix state change (success & fail) view issue as well.

[#noissue] Fix: Cover empty area in scatter chart in realtime

---

web/src/test/java/com/navercorp/pinpoint/web/alarm/SpringSmtpMailSenderTest.java

case 1 : Constructor requireNonNull Test.
case 2 : When Sender Email Address is not configured, Constructor throw NullPointerException.
case 3 : When Sender Email Address is wrong, Constructor throw RuntimeException.
case 4 : When receiver does not exist, do not send email
case 5 : When receiver is wrong, do not send email
case 6 : send Email with AlarmChecker
case 7 : send Email with AgentChecker

[#noissue] Add SpringSmtpMailSender Unit Test

---

web/src/main/angular/src/app/core/components/scatter-chart/class/scatter-chart-renderer-manager.class.ts
web/src/main/angular/src/app/core/components/scatter-chart/scatter-chart-container.component.ts
web/src/main/angular/src/app/core/components/scatter-chart/scatter-chart-for-full-screen-mode-container.component.ts
web/src/main/angular/src/app/core/components/scatter-chart/scatter-chart.component.css

- Reset chart when back to the screen
- Add missing handler when dragging the chart in full-mode
- Change vertical style for the message in scatter

[#noissue] Fix missing handlers in scatter

---

collector/src/main/resources/profiles/local/pinpoint-collector-grpc.properties
collector/src/main/resources/profiles/release/pinpoint-collector-grpc.properties

#7375 
Add collector.receiver.grpc.stat.stream.scheduler.recovery.message.count setting.

[#7375] Add recovery.message.count config of collector

---

commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/AsyncPutHbaseTemplate2.java
commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseOperations2.java
commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseTemplate2.java
web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseTraceDaoV2.java

[#7395] Polishing

---

commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/AsyncPutHbaseTemplate2.java
commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseOperations2.java
commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseTemplate2.java

[#noissue] Polishing

---

bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/DefaultProfilerConfig.java
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/ProfilerConfig.java
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/request/ServletRequestListener.java
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/uri/DisabledUriStatRecorder.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/ApplicationContextModule.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/UriStatRecorderFactoryProvider.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/UriStatStorageProvider.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/recorder/DefaultUriStatRecorder.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/recorder/DefaultUriStatRecorderFactory.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/storage/DisabledUriStatStorage.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/storage/UriStatStorage.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/monitor/metric/uri/UriStatInfo.java

- Add UriStorageProvider
- Add uriStatEnable configuration

[#6609] Add UriStorageProvider

---

bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/DefaultProfilerConfig.java
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/ProfilerConfig.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/UriStatStorageProvider.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/recorder/DefaultUriStatRecorder.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/storage/AsyncQueueingUriStatStorage.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/storage/DisabledUriStatStorage.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/storage/UriStatStorage.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/monitor/metric/uri/AgentUriStatData.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/monitor/metric/uri/EachUriStatData.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/monitor/metric/uri/UriStatHistogram.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/monitor/metric/uri/UriStatHistogramSchema.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/AsyncQueueingExecutor.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/context/monitor/metric/uri/UriStatHistogramSchemaTest.java

- Add Schema
- Add AsyncQueueingStorage

[#6609] Add UriStatHistogramSchema

---

grpc/src/main/proto/Stat.proto
profiler-test/src/test/java/com/navercorp/pinpoint/test/monitor/AgentStatMonitorTest.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/grpc/GrpcStatMessageConverter.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/grpc/GrpcUriStatMessageConverter.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/storage/AsyncQueueingUriStatStorage.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/storage/DisabledUriStatStorage.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/storage/UriStatStorage.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/monitor/DefaultAgentStatMonitor.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/monitor/StatMonitorJob.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/monitor/UriStatCollectingJob.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/StatGrpcDataSender.java

- Implement data send side
- Add proto

[#6609] Implement data send side

---

agent-testweb/pom.xml
agent-testweb/reactor-netty-plugin-testweb/README.md
agent-testweb/reactor-netty-plugin-testweb/pom.xml
agent-testweb/reactor-netty-plugin-testweb/src/main/java/com/pinpoint/test/plugin/ReactorNettyPluginTestController.java
agent-testweb/reactor-netty-plugin-testweb/src/main/java/com/pinpoint/test/plugin/ReactorNettyPluginTestStarter.java
agent-testweb/reactor-netty-plugin-testweb/src/main/resources/application.yml
agent/src/main/resources/profiles/local/pinpoint.config
agent/src/main/resources/profiles/release/pinpoint.config
bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/AsyncContextSpanEventSimpleAroundInterceptor.java
commons/src/main/java/com/navercorp/pinpoint/common/trace/ServiceType.java
plugins/grpc/src/main/java/com/navercorp/pinpoint/plugin/grpc/interceptor/server/GrpcAsyncContextSpanEventEndPointInterceptor.java
plugins/grpc/src/main/java/com/navercorp/pinpoint/plugin/grpc/interceptor/server/ServerListenerInterceptor.java
plugins/hystrix/src/main/java/com/navercorp/pinpoint/plugin/hystrix/interceptor/HystrixObservableTimeoutListenerTickInterceptor.java
plugins/reactor-netty/README.md
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/ReactorNettyConstants.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/ReactorNettyPlugin.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/ReactorNettyPluginConfig.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/HttpClientHandlerConstructorInterceptor.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/HttpClientHandlerRequestWithBodyInterceptor.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/HttpClientOperationsOnInboundNextInterceptor.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/HttpClientOperationsOnOutboundCompleteInterceptor.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/HttpClientOperationsOnOutboundErrorInterceptor.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/HttpClientRequestCookieExtractor.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/HttpClientRequestHeaderAdaptor.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/HttpClientRequestWrapper.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/HttpTcpClientConnectInterceptor.java
plugins/reactor-netty/src/main/resources/META-INF/pinpoint/type-provider.yml
plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/SpringWebFluxPlugin.java
plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/SpringWebFluxPluginConfig.java
plugins/undertow/src/main/java/com/navercorp/pinpoint/plugin/undertow/interceptor/HttpServerExchangeAdaptor.java

#7463 
~~~
profiler.reactor-netty.client.enable=true
profiler.reactor-netty.client.param=true
~~~

[#7463] Add Reactor-Netty HTTP client plugin

---

commons/src/main/java/com/navercorp/pinpoint/common/trace/AnnotationKey.java

feat: show memory.usage when available

---

web/src/main/java/com/navercorp/pinpoint/web/alarm/checker/AgentChecker.java
web/src/main/java/com/navercorp/pinpoint/web/alarm/checker/DataSourceConnectionUsageRateChecker.java
web/src/main/java/com/navercorp/pinpoint/web/alarm/checker/DeadlockChecker.java

Add @Override annotation to getSmsMessage method in checker

[#7258] Add @Override annotation in checker

---

plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/ReactorNettyPlugin.java

[#7463] Fix Reactor-Netty HTTP client plugin

---

bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/AgentIdResolver.java
bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/AgentIdResolverBuilder.java
bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/AgentIdSourceType.java
bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/PinpointStarter.java
bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/config/ProfilePropertyLoader.java
bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/config/PropertyLoaderFactory.java
bootstrap/src/test/java/com/navercorp/pinpoint/bootstrap/config/ProfilePropertyLoaderTest.java
commons/src/main/java/com/navercorp/pinpoint/common/util/OsEnvSimpleProperty.java
commons/src/test/java/com/navercorp/pinpoint/common/util/OsEnvSimplePropertyTest.java
commons/src/test/java/com/navercorp/pinpoint/common/util/PropertyUtilsTest.java

Agent adds environment variable support of configuration file. It can set the configuration parameters needed by agent by setting system environment variable. System attribute (- D) has the highest priority, environment variable has the lowest priority, and configuration file has the lowest priority

Agent adds configuration parameters to support environment variables

---

agent-testweb/pinpoint-spring-cloud-gateway-plugin-testweb/pom.xml
agent-testweb/pinpoint-spring-cloud-gateway-plugin-testweb/src/main/java/com/pinpoint/test/plugin/SpringCloudGatewayPluginTestStarter.java
agent-testweb/pinpoint-spring-cloud-gateway-plugin-testweb/src/main/resources/application.yml
agent-testweb/spring-webflux-plugin-testweb/pom.xml
agent-testweb/spring-webflux-plugin-testweb/src/main/java/com/pinpoint/test/plugin/SpringWebfluxPluginController.java
agent-testweb/spring-webflux-plugin-testweb/src/main/java/com/pinpoint/test/plugin/SpringWebfluxPluginTestStarter.java
agent-testweb/spring-webflux-plugin-testweb/src/main/resources/application.yml
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/ReactorNettyPlugin.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/AbstractHttpServerHandleInterceptor.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/HttpClientRequestWrapper.java

#7463 
This is a patch for class changes in [Reactor-Netty](https://github.com/reactor/reactor-netty) 1.0.x version.

[#7463] Update Reactor-Netty HTTP client plugin

---

collector/src/test/java/com/navercorp/pinpoint/collector/handler/grpc/GrpcAgentUriStatHandlerV2Test.java
collector/src/test/java/com/navercorp/pinpoint/collector/receiver/grpc/AgentClientMock.java
collector/src/test/java/com/navercorp/pinpoint/collector/receiver/grpc/MetadataClientMock.java
collector/src/test/java/com/navercorp/pinpoint/collector/receiver/grpc/SpanClientMock.java
collector/src/test/java/com/navercorp/pinpoint/collector/receiver/grpc/StatClientMock.java
collector/src/test/java/com/navercorp/pinpoint/collector/receiver/grpc/command/GrpcCommandServiceTest.java
commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/grpc/CollectorGrpcSpanFactoryTest.java
grpc/src/main/java/com/navercorp/pinpoint/grpc/AgentHeaderFactory.java
grpc/src/main/java/com/navercorp/pinpoint/grpc/Header.java
grpc/src/main/java/com/navercorp/pinpoint/grpc/server/AgentHeaderReader.java
grpc/src/test/java/com/navercorp/pinpoint/grpc/ChannelFactoryTest.java
grpc/src/test/java/com/navercorp/pinpoint/grpc/server/AgentHeaderReaderTest.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/grpc/AgentHeaderFactoryProvider.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/sender/grpc/AgentGrpcDataSenderTestMain.java

[#7102] Add service type to grpc header

---

bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/DefaultProfilerConfig.java

fix the bug of config profile.include not worked

---

commons/src/main/java/com/navercorp/pinpoint/common/trace/ServiceType.java
plugins/external/src/main/resources/META-INF/pinpoint/type-providers/cpp-type-provider.yml

[#7462] Add C/C++ servertype

---

bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/DefaultProfilerConfig.java

[#7462] fix the bug of config profile.include not worked

---

plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/HttpRequestAdaptor.java

#7659 
Use server host information for endpoint.

[#7659] Fix endpoint of reactor-netty plugin

---

profiler/src/main/java/com/navercorp/pinpoint/profiler/transformer/DynamicTransformService.java

[#7679] Fix assert class of retransform

---

plugins/oracle-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/oracle/OraclePlugin.java

[#7666] New connect method is now instrumented if present.

---

commons/src/main/java/com/navercorp/pinpoint/common/util/JvmVersion.java
pom.xml

Apply asm version 9.1
* JDK 17 support

[#7746] Apply asm version 9.1

---

plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/ReactorNettyPlugin.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/ChannelOperationsOnInboundCompleteMethodInterceptor.java

#7758 
Added points for tracking reactor netty 1.x.
reactor.netty.channel.ChannelOperations
~~~
/**
* React on inbound completion (last packet)
*/
protected void onInboundComplete() {
inbound.onInboundComplete();
}
~~~

[#7758] Update for reactor netty 1.x

---

profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/transformer/MatchableTransformerRegistry.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/transformer/DefaultHierarchyCachesTest.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/transformer/MatchableTransformerRegistryTest.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/sender/Bar.java

[#7756] Fix agent transform register

---

plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/SpringWebFluxPlugin.java
plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/interceptor/InvocableHandlerMethodInterceptor.java

[#7770] Add spring webflux invoke method trace

---

plugins-it/oracledb-it/pom.xml
plugins-it/oracledb-it/src/test/java/com/navercorp/pinpoint/plugin/jdbc/oracle/Oracle11_Ojdbc6_IT.java
plugins-it/oracledb-it/src/test/java/com/navercorp/pinpoint/plugin/jdbc/oracle/Oracle12_18_Ojdbc8_IT.java
plugins-it/oracledb-it/src/test/java/com/navercorp/pinpoint/plugin/jdbc/oracle/Oracle19_Ojdbc10_IT.java
plugins-it/oracledb-it/src/test/java/com/navercorp/pinpoint/plugin/jdbc/oracle/Oracle19_Ojdbc10_IT_ConnectWithGssCredential_IT.java
plugins-it/oracledb-it/src/test/java/com/navercorp/pinpoint/plugin/jdbc/oracle/Oracle19_Ojdbc8_ConnectWithGssCredential_IT.java
plugins-it/oracledb-it/src/test/java/com/navercorp/pinpoint/plugin/jdbc/oracle/Oracle19_Ojdbc8_IT.java
plugins-it/oracledb-it/src/test/java/com/navercorp/pinpoint/plugin/jdbc/oracle/OracleContainerWithWait.java
plugins-it/oracledb-it/src/test/java/com/navercorp/pinpoint/plugin/jdbc/oracle/Oracle_IT_Base.java

Applied the work-around code suggested in https://github.com/testcontainers/testcontainers-java/issues/1292

[#7666] Added oracle container wait strategy

---

web/src/main/angular/src/app/core/components/server-map/class/merge-server-map-data.class.ts

[#7791] fix filtered map show incomplete list of agent on link filter-wizard

---

bootstraps/bootstrap-java9/src/main/java/com/navercorp/pinpoint/bootstrap/java9/module/ModuleSupport.java
plugins-it/oracledb-it/src/test/java/com/navercorp/pinpoint/plugin/jdbc/oracle/OracleITConstants.java
plugins-it/oracledb-it/src/test/java/com/navercorp/pinpoint/plugin/jdbc/oracle/Oracle_IT_Base.java

+  fixed typo on ModuleSupport.java

[#7666] Changed oracle-xe-12c docker image and added environment variables

---

web/src/test/java/com/navercorp/pinpoint/web/cluster/ClusterTest.java

Reduces time interval between finding and binding an available port.

[#noissue] Fixes test

---

plugins/spring/pom.xml
plugins/spring/src/main/java/com/navercorp/pinpoint/plugin/spring/web/SpringWebMvcPlugin.java
plugins/spring/src/main/java/com/navercorp/pinpoint/plugin/spring/web/interceptor/InvocableHandlerMethodInvokeForRequestMethodInterceptor.java
plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/TomcatPlugin.java
plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/interceptor/ApplicationHttpRequestConstructor.java
plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/interceptor/RequestStartAsyncInterceptor.java

[#7821] Update spring web and tomcat plugin

---

web/src/main/angular/src/app/core/components/agent-statistic-list/agent-statistic-list.component.ts

add cell link style to agent name column & small refactoring.

[#7803] update cell style in statistics table

---

doc/faq.md

Update FAQ documentation.
1. prefer mvnw over mvn.
2. use the latest version of web server to remove gojs.

[#noissue] Update doc/faq

---

plugins/spring/src/main/java/com/navercorp/pinpoint/plugin/spring/web/SpringWebMvcPlugin.java
plugins/spring/src/main/java/com/navercorp/pinpoint/plugin/spring/web/interceptor/InvocableHandlerMethodInvokeForRequestMethodInterceptor.java
plugins/spring/src/main/java/com/navercorp/pinpoint/plugin/spring/web/interceptor/StrictHttpFirewallGetFirewalledRequestInterceptor.java

[#7821] Update spring security

---

web/src/main/angular/src/app/core/components/server-map/class/server-map-diagram-with-cytoscapejs.class.ts
web/src/main/angular/src/app/core/components/server-map/class/server-map-template.ts
web/src/main/angular/src/app/core/components/server-map/server-map.component.ts

- Use multiple image in background instead of using data-url

[#noissue] Tune background-image process in servermap

---

agent/src/main/resources/profiles/local/pinpoint.config
agent/src/main/resources/profiles/release/pinpoint.config
plugins/spring/src/main/java/com/navercorp/pinpoint/plugin/spring/async/SpringAsyncConfig.java
plugins/spring/src/main/java/com/navercorp/pinpoint/plugin/spring/async/SpringAsyncPlugin.java

[#7825] spring plugin, async task to be traced can be configured

---

plugins/spring/src/main/java/com/navercorp/pinpoint/plugin/spring/async/SpringAsyncPlugin.java

Trace asyncTaskExecutor.submitListenable(Callable).

[#noissue] spring plugin, trace async task executor submitListenable

---

plugins/spring/src/main/java/com/navercorp/pinpoint/plugin/spring/async/SpringAsyncPlugin.java

[#7885] Fix default async task of spring async plugin.

---

web/src/main/angular/src/app/core/components/transaction-table-grid/transaction-meta-data.service.ts
web/src/main/angular/src/app/core/components/transaction-table-grid/transaction-table-grid-container.component.html
web/src/main/angular/src/app/core/components/transaction-table-grid/transaction-table-grid-container.component.ts
web/src/main/angular/src/app/core/components/transaction-table-grid/transaction-table-grid.component.ts
web/src/main/angular/src/app/shared/models/url-query.ts

- Combine txId and collectorAcceptTime

[#noissue] Set transaction-key differently

---

web/src/main/angular/src/app/core/components/transaction-list-bottom-contents/transaction-list-bottom-contents-container.component.ts
web/src/main/angular/src/app/core/components/transaction-table-grid/transaction-meta-data.service.ts
web/src/main/angular/src/app/core/components/transaction-table-grid/transaction-table-grid-container.component.ts
web/src/main/angular/src/app/core/components/transaction-table-grid/transaction-table-grid.component.ts
web/src/main/angular/src/app/shared/services/transaction-detail-data.service.ts
web/src/main/angular/src/app/shared/services/url-route-manager.service.ts
web/src/main/angular/src/app/shared/store/transaction-detail-data.reducer.ts
web/src/main/angular/src/app/shared/store/transaction-info.reducer.ts

- Combine agentId, spanId, txId and. collectorAcceptTime as key

[#noissue] Handle duplicated txId

---

web/src/main/java/com/navercorp/pinpoint/web/calltree/span/SpanAlign.java
web/src/main/java/com/navercorp/pinpoint/web/calltree/span/SpanAligner.java
web/src/main/java/com/navercorp/pinpoint/web/calltree/span/SpanEventAlign.java
web/src/test/java/com/navercorp/pinpoint/web/calltree/span/SpanAlignerTest.java

[#7963] Fix nextSpanId is duplicated.

---

batch/src/main/java/com/navercorp/pinpoint/batch/web/EmptyClusterManager.java
rpc/src/main/java/com/navercorp/pinpoint/rpc/packet/stream/StreamCode.java
web/src/main/java/com/navercorp/pinpoint/web/cluster/ClusterManager.java
web/src/main/java/com/navercorp/pinpoint/web/service/AgentServiceImpl.java
web/src/main/java/com/navercorp/pinpoint/web/websocket/ActiveThreadCountErrorType.java

ClusterManager was changed whole contents because of file encoding (crlf -> lf)

[#8003] Clarify the error message on RealtimeService

---

web/src/main/angular/src/app/core/components/agent-statistic-chart/agent-statistic-chart.component.css
web/src/main/angular/src/app/core/components/alarm-rule-list/alarm-rule-create-and-update.component.css
web/src/main/angular/src/app/core/components/call-tree/call-tree.component.css
web/src/main/angular/src/app/core/components/date-format/date-format.component.css
web/src/main/angular/src/app/core/components/language-setting/language-setting.component.css
web/src/main/angular/src/app/core/components/pinpoint-user/pinpoint-user-create-and-update.component.css
web/src/main/angular/src/app/core/components/search-period/search-period.component.css
web/src/main/angular/src/app/core/components/side-bar-title/side-bar-title.component.css
web/src/main/angular/src/app/core/components/thread-dump-list/thread-dump-list.component.css
web/src/main/angular/src/app/core/components/timezone/timezone-select.component.css
web/src/main/angular/src/app/core/components/transaction-table-grid/transaction-table-grid.component.css
web/src/main/angular/src/app/core/components/user-group/user-group-create-and-update.component.css
web/src/main/angular/src/app/routes/thread-dump-page/thread-dump-page.component.css

cc. @binDongKim 
- fix ThreadDump page 
- fix agent-list select 
- fix agent statistic table

[#7990] fix some missed css

---

commons/src/main/java/com/navercorp/pinpoint/common/trace/AnnotationKey.java
plugins/hbase/src/main/java/com/navercorp/pinpoint/plugin/hbase/HbasePlugin.java
plugins/hbase/src/main/java/com/navercorp/pinpoint/plugin/hbase/HbasePluginConfig.java
plugins/hbase/src/main/java/com/navercorp/pinpoint/plugin/hbase/HbasePluginConstants.java
plugins/hbase/src/main/java/com/navercorp/pinpoint/plugin/hbase/HbasePluginMetadataProvider.java
plugins/hbase/src/main/java/com/navercorp/pinpoint/plugin/hbase/interceptor/HbaseTableMethodInterceptor.java
plugins/hbase/src/test/java/com/navercorp/pinpoint/plugin/hbase/HbasePluginConfigTest.java
plugins/hbase/src/test/java/com/navercorp/pinpoint/plugin/hbase/interceptor/HbaseTableMethodInterceptorTest.java

Rebase & Cleanup
https://github.com/pinpoint-apm/pinpoint/pull/8087

[#8103] Add hbase tableName to hbase plugin

---

web/src/main/java/com/navercorp/pinpoint/web/applicationmap/FilterMapWrap.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/MapWrap.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/histogram/AgentTimeHistogram.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/histogram/ApplicationTimeHistogram.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/histogram/LoadHistogram.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/histogram/NodeHistogram.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/histogram/TimeHistogramFormat.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/link/Link.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/link/LinkHistogramSummary.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/nodes/Node.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/nodes/NodeHistogramSummary.java
web/src/main/java/com/navercorp/pinpoint/web/controller/BusinessTransactionController.java
web/src/main/java/com/navercorp/pinpoint/web/controller/FilteredMapController.java
web/src/main/java/com/navercorp/pinpoint/web/controller/MapController.java
web/src/main/java/com/navercorp/pinpoint/web/view/AgentResponseTimeViewModel.java
web/src/main/java/com/navercorp/pinpoint/web/view/ApplicationTimeHistogramViewModel.java
web/src/main/java/com/navercorp/pinpoint/web/view/LinkHistogramSummarySerializer.java
web/src/main/java/com/navercorp/pinpoint/web/view/LinkSerializer.java
web/src/main/java/com/navercorp/pinpoint/web/view/LoadHistogramSerializer.java
web/src/main/java/com/navercorp/pinpoint/web/view/LoadTimeViewModel.java
web/src/main/java/com/navercorp/pinpoint/web/view/NodeHistogramSummarySerializer.java
web/src/main/java/com/navercorp/pinpoint/web/view/NodeSerializer.java
web/src/main/java/com/navercorp/pinpoint/web/view/ResponseTimeViewModel.java
web/src/main/java/com/navercorp/pinpoint/web/view/TimeViewModel.java
web/src/main/java/com/navercorp/pinpoint/web/view/TransactionInfoViewModel.java
web/src/test/java/com/navercorp/pinpoint/web/applicationmap/histogram/AgentTimeHistogramTest.java
web/src/test/java/com/navercorp/pinpoint/web/applicationmap/histogram/ApplicationTimeHistogramTest.java
web/src/test/java/com/navercorp/pinpoint/web/service/FilteredMapServiceImplTest.java

[#8109] Change the time histogram format

---

agent-plugins/pom.xml
agent-plugins/proxy-app/src/main/java/com/navercorp/pinpoint/agent/plugin/proxy/app/AppRequestParser.java
agent-plugins/proxy-app/src/main/java/com/navercorp/pinpoint/agent/plugin/proxy/app/AppRequestType.java
agent-plugins/proxy-common/src/main/java/com/navercorp/pinpoint/agent/plugin/proxy/common/ProxyRequestType.java
agent-plugins/proxy-nginx/src/main/java/com/navercorp/pinpoint/agent/plugin/proxy/nginx/NginxRequestParser.java
agent-plugins/proxy-nginx/src/main/java/com/navercorp/pinpoint/agent/plugin/proxy/nginx/NginxRequestType.java
agent-plugins/proxy-user/pom.xml
agent-plugins/proxy-user/src/main/java/com/navercorp/pinpoint/agent/plugin/proxy/user/UserRequestConstants.java
agent-plugins/proxy-user/src/main/java/com/navercorp/pinpoint/agent/plugin/proxy/user/UserRequestMetadataProvider.java
agent-plugins/proxy-user/src/main/java/com/navercorp/pinpoint/agent/plugin/proxy/user/UserRequestParser.java
agent-plugins/proxy-user/src/main/java/com/navercorp/pinpoint/agent/plugin/proxy/user/UserRequestParserProvider.java
agent-plugins/proxy-user/src/main/java/com/navercorp/pinpoint/agent/plugin/proxy/user/UserRequestType.java
agent-plugins/proxy-user/src/main/resources/META-INF/services/com.navercorp.pinpoint.agent.plugin.proxy.common.ProxyRequestMetadataProvider
agent-plugins/proxy-user/src/main/resources/META-INF/services/com.navercorp.pinpoint.profiler.context.recorder.proxy.ProxyRequestParserProvider
agent-plugins/proxy-user/src/test/java/com/navercorp/pinpoint/agent/plugin/proxy/user/UserRequestParserTest.java
agent/src/main/resources/profiles/local/pinpoint.config
agent/src/main/resources/profiles/release/pinpoint.config
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/plugin/ProxyRequestParserLoaderServiceProvider.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/recorder/proxy/DefaultProxyRequestParserLoaderService.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/recorder/proxy/DefaultProxyRequestRecorder.java
web/src/main/java/com/navercorp/pinpoint/web/service/ProxyRequestTypeRegistryServiceImpl.java
web/src/main/java/com/navercorp/pinpoint/web/vo/callstacks/AnnotationRecordFormatter.java

[#8122] Add user proxy plugin

---

plugins/redis-lettuce/src/main/java/com/navercorp/pinpoint/plugin/redis/lettuce/interceptor/AttachEndPointInterceptor.java

fix redisLettuce asyn connection

---

web/src/main/angular/src/app/core/components/server-map/class/server-map-diagram-with-cytoscapejs.class.ts

Resolve #8133.
In main server map:
In transaction server map:

[#8133] show Avg&Max Response summary info on ServerMap edge

---

collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcSslConfiguration.java
collector/src/test/java/com/navercorp/pinpoint/collector/grpc/config/GrpcAgentDataSslReceiverConfigurationTest.java
collector/src/test/java/com/navercorp/pinpoint/collector/grpc/config/GrpcSpanSslReceiverConfigurationTest.java
collector/src/test/java/com/navercorp/pinpoint/collector/grpc/config/GrpcStatSslReceiverConfigurationTest.java
grpc/src/main/java/com/navercorp/pinpoint/grpc/security/SslContextFactory.java
grpc/src/main/java/com/navercorp/pinpoint/grpc/security/SslServerConfig.java

If there is a file in the jar, the FIle class cannot be loaded, so it changes to a URL.

[#8128] TLS for server side

---

web/src/main/angular/src/app/core/components/side-bar-title/side-bar-title-container.component.ts
web/src/main/angular/src/app/core/components/side-bar-title/side-bar-title.component.html
web/src/main/angular/src/app/core/components/side-bar-title/side-bar-title.component.ts

Related feature #7788.
Resolve #8155.

[#8155] show agent name in instance dropdown list

---

web/src/main/angular/src/app/core/components/server-and-agent-list/server-and-agent-list-container.component.ts

The agent list in inspector pages can be filtered by agent name.
Resolve #8179.
Related to #7788 #8155.

[#8179] instance be filtered by agent name in the inspector page.

---

README.md

issued by #8148 `The page of the Latest updates on Pinpoint in README.md link is no longer maintained. so I have deleted it.`

[#8188] Fix strong markdown syntax

---

plugins-it/paho-mqtt-it/src/test/java/com/navercorp/pinpoint/plugin/paho/mqtt/PahoMqttV3ClientIT.java
plugins-it/paho-mqtt-it/src/test/java/com/navercorp/pinpoint/plugin/paho/mqtt/PahoMqttV5ClientIT.java
plugins-it/plugins-it-utils/src/main/java/com/navercorp/pinpoint/pluginit/utils/TestcontainersOption.java

To solve this issue( https://github.com/testcontainers/testcontainers-java/issues/3574)

[#noissue] Update testcontainers version

---

agent-testweb/pom.xml
agent-testweb/vertx-3-plugin-testweb/README.md
agent-testweb/vertx-3-plugin-testweb/pom.xml
agent-testweb/vertx-3-plugin-testweb/src/main/java/com/pinpoint/test/plugin/VertxPluginTestStarter.java
plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/VertxPlugin.java
plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/interceptor/Http1xClientConnectionCreateRequestInterceptor.java

[#8196] Supports vert.x version 3.9.x

---

web/src/main/angular/src/app/core/components/configuration-experimental/configuration-experimental-container.component.html
web/src/main/angular/src/app/core/components/configuration-experimental/configuration-experimental-container.component.ts
web/src/main/angular/src/app/core/components/server-map/class/server-map-diagram-with-cytoscapejs.class.ts
web/src/main/angular/src/app/core/components/server-map/server-map-container.component.html
web/src/main/angular/src/app/core/components/server-map/server-map-container.component.ts
web/src/main/angular/src/app/core/components/server-map/server-map.component.ts

- Update layout only when nodes are added
- Provide realtime in server-map as a experimental option

[#6980] Enhance real-time update in server-map

---

web/src/main/angular/src/app/core/components/server-map/server-map.component.ts

- Either with enable flag true or with url-derived refresh flag

[#noissue] Fix server-map update condition

---

web/src/main/angular/src/app/core/components/message-popup/message-popup-container.component.ts
web/src/main/angular/src/app/core/components/message-popup/message-popup.component.ts
web/src/main/angular/src/app/core/components/real-time/real-time-container.component.ts
web/src/main/angular/src/app/core/components/scatter-chart/scatter-chart-container.component.ts
web/src/main/angular/src/app/core/components/server-map/server-map-container.component.ts
web/src/main/angular/src/app/routes/main-page/index.ts
web/src/main/angular/src/app/routes/main-page/main-page.component.ts
web/src/main/angular/src/assets/i18n/en.json
web/src/main/angular/src/assets/i18n/ko.json
web/src/main/angular/src/globals.d.ts

- Deactivate the page if the user is away over 10seconds

[#noissue] Stop fetching data in realtime when the user is away from the page

---

bootstraps/bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/util/AntPathMatcherTest.java
test/src/main/java/com/navercorp/pinpoint/test/plugin/AbstractPinpointPluginTestSuite.java
test/src/main/java/com/navercorp/pinpoint/test/plugin/PluginClassLoading.java

1. Supports Ant-path matcher
2. Supports plugin classpath that is formed jar

[#8236] Supports plugins classpath in IT

---

web/src/main/angular/src/app/core/components/webhook-list/webhook-list-container.component.html
web/src/main/angular/src/app/core/components/webhook-list/webhook-list-container.component.ts

[#noissue] fix webhook wrong authority

---

web/src/main/angular/package-lock.json

perfetto version (1.0.4 -> 1.1.0)

[noissue] update package-lock.json

---

plugins-it/google-grpc-it/src/test/java/com/navercorp/pinpoint/plugin/grpc/HelloWorldSimpleServer.java
plugins-it/google-grpc-it/src/test/java/com/navercorp/pinpoint/plugin/grpc/HelloWorldStreamServer.java

[#noissue] Fix grpc it

---

web/src/main/angular/src/app/core/components/call-tree/call-tree.component.css

[#8376] web ui, highlight exception rows in call tree

---

web/src/main/angular/src/app/core/components/configuration-experimental/configuration-experimental-container.component.ts
web/src/main/angular/src/app/core/components/scatter-chart/scatter-chart-container.component.ts
web/src/main/angular/src/app/core/components/scatter-chart/scatter-chart-for-filtered-map-info-per-server-container.component.ts
web/src/main/angular/src/app/core/components/scatter-chart/scatter-chart-for-filtered-map-side-bar-container.component.ts
web/src/main/angular/src/app/core/components/scatter-chart/scatter-chart-for-full-screen-mode-container.component.ts
web/src/main/angular/src/app/core/components/scatter-chart/scatter-chart-for-info-per-server-container.component.ts
web/src/main/angular/src/app/core/components/scatter-chart/scatter-chart.component.ts
web/src/main/angular/src/app/core/components/server-map/server-map-container.component.ts
web/src/main/angular/src/app/core/components/server-map/server-map-data.service.ts
web/src/main/angular/src/app/core/components/server-map/server-map-for-filtered-map-data.service.ts
web/src/main/angular/src/app/core/components/state-button/state-button-for-transaction-list-container.component.ts
web/src/main/angular/src/app/core/components/transaction-table-grid/transaction-meta-data.service.ts
web/src/main/angular/src/app/shared/services/transaction-detail-data.service.ts
web/src/main/angular/src/app/shared/services/web-app-setting-data.service.ts

- Target options: servermap-realtime, scatter-sampling

[#noissue] Set default as true some experimental options

---

web/src/main/angular/src/app/core/components/configuration-experimental/configuration-experimental-container.component.ts
web/src/main/angular/src/app/core/components/scatter-chart/scatter-chart-container.component.ts
web/src/main/angular/src/app/core/components/scatter-chart/scatter-chart-for-filtered-map-info-per-server-container.component.ts
web/src/main/angular/src/app/core/components/scatter-chart/scatter-chart-for-filtered-map-side-bar-container.component.ts
web/src/main/angular/src/app/core/components/scatter-chart/scatter-chart-for-full-screen-mode-container.component.ts
web/src/main/angular/src/app/core/components/scatter-chart/scatter-chart-for-info-per-server-container.component.ts
web/src/main/angular/src/app/core/components/server-map/server-map-data.service.ts
web/src/main/angular/src/app/core/components/server-map/server-map-for-filtered-map-data.service.ts
web/src/main/angular/src/app/core/components/state-button/state-button-for-transaction-list-container.component.ts
web/src/main/angular/src/app/core/components/transaction-table-grid/transaction-meta-data.service.ts
web/src/main/angular/src/app/shared/services/transaction-detail-data.service.ts

- Target: ScatterServerSideScan, useStatisticsAgentState

[#noissue] Set default as true for other options

---

collector/src/main/resources/hbase-root.properties

[#8372] Disable BufferedMutator

---

batch/pom.xml
collector/pom.xml
commons-hbase/pom.xml
commons-server/pom.xml
flink/pom.xml
plugins/hbase/pom.xml
pom.xml
web/pom.xml

- Duplicate with spring-jcl in server module

[#noissue] Cleanup commons-logging dependency

---

agent-testweb/pom.xml

Remove vertx-3-plugin-testweb of pom

[#noissue] Fix testweb pom

---

agent-testweb/jdk-http-plugin-testweb/src/main/java/com/pinpointest/plugin/controller/JdkHttpPluginController.java
agent-testweb/jdk-http-plugin-testweb/src/main/java/com/pinpointest/plugin/controller/JdkPostUtils.java
plugins/jdk-http/src/main/java/com/navercorp/pinpoint/plugin/jdk/http/DelegateGetter.java
plugins/jdk-http/src/main/java/com/navercorp/pinpoint/plugin/jdk/http/JdkHttpPlugin.java
plugins/jdk-http/src/main/java/com/navercorp/pinpoint/plugin/jdk/http/interceptor/AbstractHttpURLConnectionInterceptor.java
plugins/jdk-http/src/main/java/com/navercorp/pinpoint/plugin/jdk/http/interceptor/HttpsURLConnectionImplInterceptor.java

[#8513] Fix https in jdk-http-plugin

---

web/src/main/angular/src/app/core/components/webhook-list/webhook-list-container.component.ts
web/src/main/angular/src/app/core/components/webhook-list/webhook-list-create-and-update.component.html
web/src/main/angular/src/app/core/components/webhook-list/webhook-list-create-and-update.component.ts
web/src/main/angular/src/assets/i18n/en.json
web/src/main/angular/src/assets/i18n/ko.json

@binDongKim @ga-ram 
Limit the number of characters in the webbook url & alias to 256

[#noissue] [WEB/UI] add webhook url & alias validation; max length

---

agent-plugins/proxy-app/src/main/java/com/navercorp/pinpoint/agent/plugin/proxy/app/AppRequestParser.java
agent-plugins/proxy-app/src/test/java/com/navercorp/pinpoint/agent/plugin/proxy/app/AppRequestParserTest.java

[#8543] Fix app proxy header

---

agent-plugins/proxy-app/src/main/java/com/navercorp/pinpoint/agent/plugin/proxy/app/AppRequestParser.java
agent-plugins/proxy-app/src/test/java/com/navercorp/pinpoint/agent/plugin/proxy/app/AppRequestParserTest.java

[#8547] Backport fix app proxy header

---

bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/instrument/InstrumentClass.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMClass.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMNestedClass.java

[#8699] Add getLambda method

---

web/src/main/angular/package-lock.json
web/src/main/angular/src/app/core/components/scatter-chart/scatter-chart-container.component.ts
web/src/main/angular/src/app/core/components/scatter-chart/scatter-chart-for-filtered-map-info-per-server-container.component.ts
web/src/main/angular/src/app/core/components/scatter-chart/scatter-chart-for-filtered-map-side-bar-container.component.ts
web/src/main/angular/src/app/core/components/scatter-chart/scatter-chart-for-full-screen-mode-container.component.ts
web/src/main/angular/src/app/core/components/scatter-chart/scatter-chart-for-info-per-server-container.component.ts
web/src/main/angular/src/app/core/components/scatter-chart/scatter-chart.component.ts
web/src/main/angular/src/app/core/components/server-map/server-map-container.component.ts
web/src/main/angular/src/app/core/components/state-button/state-button-for-transaction-list-container.component.ts
web/src/main/angular/src/app/core/components/transaction-table-grid/transaction-meta-data.service.ts

[#noissue] [WEB/UI] Fix scatter chart bug

---

plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/interceptor/tprotocol/server/TProtocolReadMessageEndInterceptor.java

[#8622] Fix thrift methodUri

---

web/src/main/angular/src/app/core/components/apdex-score/apdex-score.component.ts

[#noissue] fix apdex decimal places 3 to 2

---

agent-testweb/elasticsearch-plugin-testweb/pom.xml
agent-testweb/elasticsearch-plugin-testweb/src/main/java/com/pinpoint/test/plugin/ElasticSearchPluginController.java
agent-testweb/elasticsearch-plugin-testweb/src/main/java/com/pinpoint/test/plugin/ElasticSearchPluginTestStarter.java
agent-testweb/elasticsearch-plugin-testweb/src/main/resources/application.yml
agent-testweb/pom.xml
plugins-it/elasticsearch-7.16-it/pom.xml
plugins-it/elasticsearch-7.16-it/src/test/java/com/navercorp/pinpoint/plugin/elasticsearch/ElasticsearchITBase.java
plugins-it/elasticsearch-7.16-it/src/test/java/com/navercorp/pinpoint/plugin/elasticsearch/ElasticsearchIT_7_16_x_IT.java
plugins-it/elasticsearch-it/src/test/java/com/navercorp/pinpoint/plugin/elasticsearch/ElasticsearchIT_7_0_x_IT.java
plugins-it/pom.xml
plugins/elasticsearch/src/main/java/com/navercorp/pinpoint/plugin/elasticsearch/ElasticsearchPlugin.java

[#8726] Update elasticsearch plugin

---

agent-testweb/pom.xml
agent-testweb/postgresql-plugin-testweb/pom.xml
agent-testweb/postgresql-plugin-testweb/src/main/java/com/pinpoint/test/plugin/PostgresqlPluginController.java
agent-testweb/postgresql-plugin-testweb/src/main/java/com/pinpoint/test/plugin/PostgresqlPluginTestStarter.java
agent-testweb/postgresql-plugin-testweb/src/main/resources/application.yml
plugins/postgresql-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/postgresql/PostgreSqlPlugin.java
plugins/postgresql-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/postgresql/interceptor/PostgreSQLConnectionCreateInterceptor.java

[#8730] Update postgresql plugin

---

agent-testweb/elasticsearch-8-plugin-testweb/pom.xml
agent-testweb/elasticsearch-8-plugin-testweb/src/main/java/com/pinpoint/test/plugin/ElasticSearch8PluginController.java
agent-testweb/elasticsearch-8-plugin-testweb/src/main/java/com/pinpoint/test/plugin/ElasticSearch8PluginTestStarter.java
agent-testweb/elasticsearch-8-plugin-testweb/src/main/resources/application.yml
agent-testweb/pom.xml
commons/src/main/java/com/navercorp/pinpoint/common/trace/AnnotationKey.java
commons/src/main/java/com/navercorp/pinpoint/common/trace/ServiceType.java
plugins/assembly/pom.xml
plugins/bom/pom.xml
plugins/elasticsearch8/README.md
plugins/elasticsearch8/pom.xml
plugins/elasticsearch8/src/main/java/com/navercorp/pinpoint/plugin/elasticsearch8/Elasticsearch8Constants.java
plugins/elasticsearch8/src/main/java/com/navercorp/pinpoint/plugin/elasticsearch8/Elasticsearch8Plugin.java
plugins/elasticsearch8/src/main/java/com/navercorp/pinpoint/plugin/elasticsearch8/Elasticsearch8PluginConfig.java
plugins/elasticsearch8/src/main/java/com/navercorp/pinpoint/plugin/elasticsearch8/accessor/ClusterInfoAccessor.java
plugins/elasticsearch8/src/main/java/com/navercorp/pinpoint/plugin/elasticsearch8/accessor/EndPointAccessor.java
plugins/elasticsearch8/src/main/java/com/navercorp/pinpoint/plugin/elasticsearch8/interceptor/ElasticsearchClientConstructorInterceptor.java
plugins/elasticsearch8/src/main/java/com/navercorp/pinpoint/plugin/elasticsearch8/interceptor/ElasticsearchClientMethodInterceptor.java
plugins/elasticsearch8/src/main/resources/META-INF/pinpoint/type-provider.yml
plugins/elasticsearch8/src/main/resources/META-INF/services/com.navercorp.pinpoint.bootstrap.plugin.ProfilerPlugin
plugins/pom.xml

[#8726] Add elasticsearch8 plugin

---

web/src/main/angular/src/app/core/components/apdex-score/apdex-score.component.css

fix margin and color @binDongKim 
- before 
- after

[#noissue] fix apdex style

---

pom.xml

javax.transaction:jta 1.1 -> jakarta.transaction:jakarta.transaction-api:1.3.3

[#8795] Bump javax.transaction from to 1.1 to 1.3.3

---

web/src/main/java/com/navercorp/pinpoint/web/dao/UserGroupDao.java
web/src/main/java/com/navercorp/pinpoint/web/dao/memory/MemoryUserGroupDao.java
web/src/main/java/com/navercorp/pinpoint/web/dao/mysql/MysqlUserGroupDao.java
web/src/main/resources/mapper/UserGroupMapper.xml

Added `boolean isExistUserGroupMember(String userGroupId, String memberId)` in UserGroupDao.

[#noissue] add isExistUserGroupMember

---

hbase2-module/hbase2-batch/pom.xml
web/src/main/java/com/navercorp/pinpoint/web/AuthorizationConfig.java

Backport for issue 8909, 8908

---

web/src/main/web-frontend/apps/web/.storybook/.babelrc
web/src/main/web-frontend/apps/web/.storybook/main.js
web/src/main/web-frontend/apps/web/.storybook/preview.js
web/src/main/web-frontend/package.json
web/src/main/web-frontend/packages/common/.storybook/.babelrc
web/src/main/web-frontend/packages/common/.storybook/main.js
web/src/main/web-frontend/packages/common/components/ButtonGroup/ButtonGroup.stories.tsx
web/src/main/web-frontend/packages/common/components/Dropdown/Dropdown.stories.tsx
web/src/main/web-frontend/packages/common/components/Dropdown/Dropdown.test.tsx
web/src/main/web-frontend/packages/common/components/Dropdown/Dropdown.tsx
web/src/main/web-frontend/packages/common/components/Dropdown/DropdownContent.tsx
web/src/main/web-frontend/packages/common/components/Dropdown/DropdownContext.tsx
web/src/main/web-frontend/packages/common/components/Dropdown/DropdownTrigger.tsx
web/src/main/web-frontend/packages/common/components/Styled/GlobalStyle.tsx
web/src/main/web-frontend/packages/common/hooks/interaction.ts
web/src/main/web-frontend/packages/common/tsconfig.json
web/src/main/web-frontend/yarn.lock

Add: ButtonGroup, Dropdown, fix storybook settings

---

bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/reactor/FluxAndMonoConstructorInterceptor.java
bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/reactor/FluxAndMonoSubscribeOrReturnInterceptor.java
bootstraps/bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/plugin/reactor/CoreSubscriberConstructorInterceptorTest.java
bootstraps/bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/plugin/reactor/FluxAndMonoConstructorInterceptorTest.java
bootstraps/bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/plugin/reactor/FluxAndMonoOperatorConstructorInterceptorTest.java
bootstraps/bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/plugin/reactor/FluxAndMonoOperatorSubscribeInterceptorTest.java
bootstraps/bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/plugin/reactor/FluxAndMonoSubscribeInterceptorTest.java
bootstraps/bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/plugin/reactor/FluxAndMonoSubscribeOrReturnInterceptorTest.java
bootstraps/bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/plugin/reactor/MockAsyncContextAndReactorContextImpl.java
bootstraps/bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/plugin/reactor/ReactorContextAccessorUtilsTest.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/ReactorNettyPlugin.java
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/ReactorPlugin.java

[#8941] Update reactor plugin for subscribeOrReturn method.

---

agent-testweb/jetty-plugin-testweb/README.md
agent-testweb/jetty-plugin-testweb/pom.xml
agent-testweb/jetty-plugin-testweb/src/main/java/com/pinpoint/test/plugin/AsyncServlet.java
agent-testweb/jetty-plugin-testweb/src/main/java/com/pinpoint/test/plugin/BlockingServlet.java
agent-testweb/jetty-plugin-testweb/src/main/java/com/pinpoint/test/plugin/JettyServerStarterMain.java
agent-testweb/pom.xml

[#noissue] Add jetty plugin testweb

---

agent-testweb/bom/pom.xml
agent-testweb/pom.xml
agent-testweb/redis-lettuce-plugin-testweb/pom.xml
agent-testweb/redis-lettuce-plugin-testweb/src/main/java/com/pinpoint/test/plugin/HttpClientConfig.java
agent-testweb/redis-lettuce-plugin-testweb/src/main/java/com/pinpoint/test/plugin/RedisLettucePluginTestStarter.java
agent-testweb/redis-lettuce-plugin-testweb/src/main/java/com/pinpoint/test/plugin/RedisRateLimiterConfig.java
agent-testweb/redis-lettuce-plugin-testweb/src/main/java/com/pinpoint/test/plugin/SimpleRoute.java
agent-testweb/redis-lettuce-plugin-testweb/src/main/resources/application.yml
bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/async/AsyncContextAccessorUtils.java
bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/reactor/CoreSubscriberConstructorInterceptor.java
bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/reactor/FluxAndMonoOperatorConstructorInterceptor.java
bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/reactor/FluxAndMonoOperatorSubscribeInterceptor.java
bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/reactor/FluxAndMonoSubscribeInterceptor.java
bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/reactor/ReactorContextAccessorUtils.java
plugins/bom/pom.xml
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/interceptor/ParallelFluxSubscribeInterceptor.java
plugins/redis-lettuce/src/main/java/com/navercorp/pinpoint/plugin/redis/lettuce/LettucePlugin.java
plugins/redis-lettuce/src/main/java/com/navercorp/pinpoint/plugin/redis/lettuce/interceptor/RedisSubscriberInterceptor.java
plugins/redis-lettuce/src/main/java/com/navercorp/pinpoint/plugin/redis/lettuce/interceptor/RunnableNewInstanceInterceptor.java
plugins/redis-lettuce/src/main/java/com/navercorp/pinpoint/plugin/redis/lettuce/interceptor/RunnableRunInterceptor.java

[#8954] Backport: Update lettuce plugin

---

plugins-it/thrift-it/pom.xml
plugins-it/thrift-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/client/AsyncEchoTestClient.java
plugins-it/thrift-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/client/SyncEchoTestClient014.java
plugins-it/thrift-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/client/TTransportInstanceCreator.java
plugins-it/thrift-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/server/AsyncEchoTestServer014.java
plugins-it/thrift-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/server/SyncEchoTestServer014.java
plugins-it/thrift-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/server/ThriftEchoTestServer.java
plugins-it/thrift-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/EchoTestRunner.java
plugins-it/thrift-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/ThriftVersion.java
plugins-it/thrift-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/asynchronous/ThriftHalfSyncHalfAsyncServerAsyncIT.java
plugins-it/thrift-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/asynchronous/ThriftHalfSyncHalfAsyncServerAsyncIT_014.java
plugins-it/thrift-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/asynchronous/ThriftNonblockingServerAsyncIT.java
plugins-it/thrift-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/asynchronous/ThriftNonblockingServerAsyncIT014.java
plugins-it/thrift-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/asynchronous/ThriftThreadedSelectorServerAsyncIT.java
plugins-it/thrift-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/asynchronous/ThriftThreadedSelectorServerAsyncIT014.java
plugins-it/thrift-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/synchronous/ThriftHalfSyncHalfAsyncServerIT.java
plugins-it/thrift-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/synchronous/ThriftHalfSyncHalfAsyncServerIT014.java
plugins-it/thrift-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/synchronous/ThriftNonblockingServerIT014.java
plugins-it/thrift-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/synchronous/ThriftSimpleServerIT.java
plugins-it/thrift-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/synchronous/ThriftThreadPoolServerIT.java
plugins-it/thrift-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/synchronous/ThriftThreadedSelectorServerIT.java
plugins-it/thrift-it/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/synchronous/ThriftThreadedSelectorServerIT014.java
plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/ThriftPlugin.java
plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/interceptor/transport/TNonblockingSocketConstructInterceptor.java

[#9025] Update thrift plugin for 0.14 or later

---

flink/src/main/resources/applicationContext-hbase.xml

[#9038][backport]Added property to set "zookeeper.znode.parent" of hbase

---

plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/interceptor/MongoClientConstructorInterceptor.java

[#9111] Fix NPE bug in mongo-plugin

---

web/src/main/java/com/navercorp/pinpoint/web/websocket/ActiveThreadCountResponseAggregator.java

[#9148] activeThreadCountWorkerRepository uses ClusterKey as key type

---

profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/ResponseStreamObserver.java

[#9181] Change agent's gRPC stream log level

---

plugins/rabbitmq/src/main/java/com/navercorp/pinpoint/plugin/rabbitmq/client/interceptor/RabbitMQConsumerHandleCompleteInboundCommandInterceptor.java

[#9183] Fix rabbitmq consumer handle

---

profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMMethod.java

[#9185] Fix log level of abstract method transform

---

web/src/main/angular/src/app/core/components/main-contents/main-contents-container.component.css
web/src/main/angular/src/app/core/components/real-time/real-time-container.component.ts

fix realtime container height and default height
cc.. @binDongKim

[#noissue] fix realtime container height

---

profiler/src/main/java/com/navercorp/pinpoint/profiler/context/grpc/GrpcSpanMessageConverter.java

[#9202] Backport: Fix span dispatch failed

---

profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMMethod.java

[#9204] Backport: Fix log level of abstract method transform

---

profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/ResponseStreamObserver.java

[#9208] Backport: Change the agent's gRPC stream log level

---

collector/src/main/java/com/navercorp/pinpoint/collector/mapper/flink/TFActiveTraceMapper.java
collector/src/main/java/com/navercorp/pinpoint/collector/mapper/flink/TFAgentStatBatchMapper.java

[#9210] Beaned TFActiveTraceMapper

---

collector/src/main/java/com/navercorp/pinpoint/collector/mapper/flink/TFAgentStatBatchMapper.java

Removed useless method `getStartTimestamp`

[#9210] Removed getStartTimestamp

---

flink/src/main/java/com/navercorp/pinpoint/flink/process/TBaseFlatMapper.java
profiler-optional/profiler-optional-jdk8/src/main/java/com/navercorp/pinpoint/profiler/monitor/metric/buffer/DefaultBufferMetric.java
profiler-optional/profiler-optional-jdk8/src/main/java/com/navercorp/pinpoint/profiler/monitor/metric/cpu/ibm/DefaultCpuLoadMetric.java
profiler-optional/profiler-optional-jdk8/src/main/java/com/navercorp/pinpoint/profiler/monitor/metric/cpu/oracle/DefaultCpuLoadMetric.java
profiler-optional/profiler-optional-jdk8/src/main/java/com/navercorp/pinpoint/profiler/monitor/metric/filedescriptor/oracle/OracleFileDescriptorMetric.java

[#9215] Fixed positions of metric measurers

---

metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/controller/SystemMetricController.java
metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/model/MetricDataSearchKey.java
metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/util/QueryParameter.java

metric module
* use TimeWindowSlotCentricSampler
* use window range(refined timeStamp)

[#noissue] Change TimeWindowSampler, window range in metric module

---

collector/src/main/java/com/navercorp/pinpoint/collector/cluster/ClusterPointRepository.java
collector/src/main/java/com/navercorp/pinpoint/collector/cluster/GrpcAgentConnection.java
collector/src/main/java/com/navercorp/pinpoint/collector/cluster/zookeeper/ZookeeperClusterService.java
collector/src/main/java/com/navercorp/pinpoint/collector/cluster/zookeeper/ZookeeperProfilerClusterManager.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/PinpointGrpcServer.java

Added more loggings for analyzing transitions of state of grpc server in collector

[#noissue] Add more logs for collector grpc server

---

pom.xml

[#9238] Bump grpc from 1.43.2 to 1.49.1

---

web/src/main/java/com/navercorp/pinpoint/web/applicationmap/appender/server/datasource/AgentInfoServerGroupListDataSource.java

[#9270] Fix a bug in constructing servermap agents list

---

plugins-it/plugins-it-utils/src/main/java/com/navercorp/pinpoint/pluginit/utils/TestcontainersOption.java
plugins-it/rabbitmq-it/pom.xml
plugins-it/rabbitmq-it/src/test/java/com/navercorp/pinpoint/plugin/rabbitmq/RabbitMQClientITBase.java
plugins-it/rabbitmq-it/src/test/java/com/navercorp/pinpoint/plugin/rabbitmq/RabbitMQClient_2_7_0_to_3_3_0_IT.java
plugins-it/rabbitmq-it/src/test/java/com/navercorp/pinpoint/plugin/rabbitmq/RabbitMQClient_3_3_0_to_4_0_0_IT.java
plugins-it/rabbitmq-it/src/test/java/com/navercorp/pinpoint/plugin/rabbitmq/RabbitMQClient_4_x_IT.java
plugins-it/rabbitmq-it/src/test/java/com/navercorp/pinpoint/plugin/rabbitmq/RabbitMQClient_5_x_IT.java
plugins-it/rabbitmq-it/src/test/java/com/navercorp/pinpoint/plugin/rabbitmq/TestBrokerServer.java
plugins-it/rabbitmq-it/src/test/java/com/navercorp/pinpoint/plugin/rabbitmq/spring/SpringAmqpRabbit_1_3_3_to_1_4_2_IT.java
plugins-it/rabbitmq-it/src/test/java/com/navercorp/pinpoint/plugin/rabbitmq/spring/SpringAmqpRabbit_1_4_2_to_1_7_0_IT.java
plugins-it/rabbitmq-it/src/test/java/com/navercorp/pinpoint/plugin/rabbitmq/spring/SpringAmqpRabbit_1_7_0_to_1_7_7_IT.java
plugins-it/rabbitmq-it/src/test/java/com/navercorp/pinpoint/plugin/rabbitmq/spring/SpringAmqpRabbit_1_7_7_to_2_0_0_IT.java
plugins-it/rabbitmq-it/src/test/java/com/navercorp/pinpoint/plugin/rabbitmq/spring/SpringAmqpRabbit_2_0_0_to_2_0_3_IT.java
plugins-it/rabbitmq-it/src/test/java/com/navercorp/pinpoint/plugin/rabbitmq/spring/SpringAmqpRabbit_2_0_3_to_2_1_0_IT.java
plugins-it/rabbitmq-it/src/test/java/com/navercorp/pinpoint/plugin/rabbitmq/spring/SpringAmqpRabbit_2_1_x_to_2_x_IT.java
plugins-it/rabbitmq-it/src/test/java/com/navercorp/test/pinpoint/plugin/rabbitmq/spring/config/CommonConfig.java

Stacktrace
~~~
com.navercorp.pinpoint.test.plugin.PinpointPluginTestException: org.springframework.amqp.AmqpConnectException: java.net.ConnectException: Connection refused (Connection refused)
Caused by: com.navercorp.pinpoint.test.plugin.PinpointPluginTestException: java.net.ConnectException: Connection refused (Connection refused)
~~~

[#noissue] Update rabbitmq IT

---

metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/web/service/SystemMetricDataServiceImpl.java

* remove '[', ']' from metric groupName
* add non empty groupName when tagList is empty

[#noissue] Change metric groupName

---

collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/GrpcReceiver.java
collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/SimpleServerCallExecutorSupplier.java
collector/src/main/resources/applicationContext-collector-grpc.xml
grpc/src/main/java/com/navercorp/pinpoint/grpc/server/ServerFactory.java
grpc/src/test/java/com/navercorp/pinpoint/grpc/ChannelFactoryTest.java

[#9323] GRPC server utilize call executor

---

commons/src/main/java/com/navercorp/pinpoint/common/util/JvmVersion.java
commons/src/test/java/com/navercorp/pinpoint/common/util/JvmVersionTest.java
pom.xml
profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMVersion.java

[#9346] Bump asm to 9.4

---

web/src/main/angular/src/app/routes/browser-support-page/browser-support-page.component.html
web/src/main/angular/src/app/routes/browser-support-page/browser-support-page.component.ts

- Following the user agent freeze policy

[#noissue] Change the way of getting user agent info

---

profiler-test/src/main/java/com/navercorp/pinpoint/test/classloader/TestClassList.java
test/src/main/java/com/navercorp/pinpoint/test/plugin/PluginClassLoading.java

not sure but those are very likely to seen to the reason of malfunction of IT

[#9389] Re-include hamcrest for test

---

agent/src/main/resources/profiles/local/pinpoint.config
agent/src/main/resources/profiles/release/pinpoint.config
plugins/google-httpclient/src/main/java/com/navercorp/pinpoint/plugin/google/httpclient/HttpClientPlugin.java
plugins/google-httpclient/src/main/java/com/navercorp/pinpoint/plugin/google/httpclient/HttpClientPluginConfig.java

[#9438] Update google httpclient plugin enable option

---

agent/src/main/resources/profiles/local/pinpoint.config
agent/src/main/resources/profiles/release/pinpoint.config
plugins/agentsdk-async/src/main/java/com/navercorp/pinpoint/plugin/sdk/AgentSdkAsyncPlugin.java
plugins/arcus/src/main/java/com/navercorp/pinpoint/plugin/arcus/ArcusPlugin.java
plugins/cxf/src/main/java/com/navercorp/pinpoint/plugin/cxf/CxfPlugin.java
plugins/cxf/src/main/java/com/navercorp/pinpoint/plugin/cxf/CxfPluginConfig.java
plugins/elasticsearch/src/main/java/com/navercorp/pinpoint/plugin/elasticsearch/ElasticsearchPlugin.java
plugins/elasticsearch8/src/main/java/com/navercorp/pinpoint/plugin/elasticsearch8/Elasticsearch8Plugin.java
plugins/httpclient3/src/main/java/com/navercorp/pinpoint/plugin/httpclient3/HttpClient3Plugin.java
plugins/httpclient3/src/main/java/com/navercorp/pinpoint/plugin/httpclient3/HttpClient3PluginConfig.java
plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/HttpClient4Plugin.java
plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/HttpClient4PluginConfig.java
plugins/ibatis/src/main/java/com/navercorp/pinpoint/plugin/ibatis/IBatisPlugin.java
plugins/jsp/src/main/java/com/navercorp/pinpoint/plugin/jsp/JspPlugin.java
plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/KafkaConfig.java
plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/KafkaPlugin.java
plugins/log4j2/src/main/java/com/navercorp/pinpoint/plugin/log4j2/Log4j2Plugin.java
plugins/paho-mqtt/src/main/java/com/navercorp/pinpoint/plugin/paho/mqtt/PahoMqttPlugin.java
plugins/redis-lettuce/src/main/java/com/navercorp/pinpoint/plugin/redis/lettuce/LettucePlugin.java
plugins/redis-redisson/src/main/java/com/navercorp/pinpoint/plugin/redis/redisson/RedissonPlugin.java
plugins/redis/src/main/java/com/navercorp/pinpoint/plugin/redis/jedis/JedisPlugin.java
plugins/rocketmq/src/main/java/com/navercorp/pinpoint/plugin/rocketmq/RocketMQConfig.java
plugins/rocketmq/src/main/java/com/navercorp/pinpoint/plugin/rocketmq/RocketMQPlugin.java
plugins/spring-boot/src/main/java/com/navercorp/pinpoint/plugin/spring/boot/SpringBootPlugin.java
plugins/spring/src/main/java/com/navercorp/pinpoint/plugin/spring/web/SpringWebMvcConfig.java
plugins/spring/src/main/java/com/navercorp/pinpoint/plugin/spring/web/SpringWebMvcPlugin.java
plugins/thread/src/main/java/com/navercorp/pinpoint/plugin/thread/ThreadConfig.java
plugins/thread/src/main/java/com/navercorp/pinpoint/plugin/thread/ThreadPlugin.java
plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/ThriftPlugin.java
plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/ThriftPluginConfig.java

﻿[#9445] Update plugin enable option

---

commons-server/src/main/java/com/navercorp/pinpoint/common/server/env/AdditionalProfileListener.java
metric-module/collector-starter/src/main/java/com/navercorp/pinpoint/collector/starter/multi/application/MultiApplication.java
metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/collector/CollectorType.java
metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/collector/CollectorTypeParser.java
metric-module/metric/src/main/java/com/navercorp/pinpoint/metric/collector/TypeSet.java
metric-module/metric/src/test/java/com/navercorp/pinpoint/metric/collector/CollectorTypeParserTest.java

[#9453] Refactor Command-line Arguments of MultipleApplications to SpringBoot style

---

collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcAgentDataReceiverConfiguration.java
collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcAgentDataReceiverConfigurationFactory.java
collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcReceiverConfiguration.java
collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcSpanReceiverConfiguration.java
collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcSpanReceiverConfigurationFactory.java
collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcStatReceiverConfiguration.java
collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcStatReceiverConfigurationFactory.java
collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcStreamReceiverConfiguration.java
collector/src/main/resources/applicationContext-collector-grpc.xml
collector/src/main/resources/profiles/local/pinpoint-collector-grpc.properties
collector/src/main/resources/profiles/release/pinpoint-collector-grpc.properties
metric-module/collector-starter/src/main/resources/profiles/local/pinpoint-collector-grpc.properties
metric-module/collector-starter/src/main/resources/profiles/release/pinpoint-collector-grpc.properties

[#9474] Add serverCallExecutor in grpcReceiverConfiguration

---

agent-testweb/reactor-netty-plugin-testweb/src/main/java/com/pinpoint/test/plugin/ReactorNettyPluginTestController.java
agent-testweb/spring-webflux-plugin-testweb/src/main/java/com/pinpoint/test/plugin/SpringWebfluxPluginController.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/HttpRequestAdaptor.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/HttpServerParameterExtractor.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/UriUtils.java
plugins/reactor-netty/src/test/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/UriUtilsTest.java

[#9502] Backport: Fix path of reactor-netty server

---

bootstraps/bootstrap-java15/pom.xml
bootstraps/bootstrap-java16/pom.xml
plugins/jetty/pom.xml
plugins/resin/pom.xml
plugins/weblogic/pom.xml
plugins/websphere/pom.xml
pom.xml
profiler-optional/profiler-optional-jdk9/pom.xml

[#9608] Bump build-helper-maven-plugin from 1.10 to 3.3.0

---

agent-testweb/bom/pom.xml
agent-testweb/mongodb-plugin-testweb/pom.xml
agent-testweb/mongodb-plugin-testweb/src/main/java/com/pinpoint/test/plugin/MongoPluginController.java
agent-testweb/mongodb-plugin-testweb/src/main/java/com/pinpoint/test/plugin/MongoServer.java
agent-testweb/mongodb-plugin-testweb/src/test/java/com/pinpoint/test/plugin/mongo/MongodbTest.java
agent-testweb/mongodb-reactive-plugin-testweb/pom.xml
agent-testweb/mongodb-reactive-plugin-testweb/src/main/java/com/pinpoint/test/plugin/ApiLinkPage.java
agent-testweb/mongodb-reactive-plugin-testweb/src/main/java/com/pinpoint/test/plugin/Demo.java
agent-testweb/mongodb-reactive-plugin-testweb/src/main/java/com/pinpoint/test/plugin/MongoConfig.java
agent-testweb/mongodb-reactive-plugin-testweb/src/main/java/com/pinpoint/test/plugin/MongoReactivePluginController.java
agent-testweb/mongodb-reactive-plugin-testweb/src/main/java/com/pinpoint/test/plugin/MongoServer.java
agent-testweb/mongodb-reactive-plugin-testweb/src/main/java/com/pinpoint/test/plugin/ReactiveMongoConfig.java
agent-testweb/mongodb-reactive-plugin-testweb/src/test/java/com/pinpoint/test/plugin/mongo/MongodbTest.java
plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/MongoPlugin.java
plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/ReactiveMongoClientImplGetter.java
plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/interceptor/AsyncOperationExecuteAsyncInterceptor.java
plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/interceptor/MongoClientConstructorInterceptor.java
plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/interceptor/MongoClientImplConstructorInterceptor.java
plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/interceptor/MongoClientsInterceptor.java
plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/interceptor/MongoCollectionImplConstructorInterceptor.java
plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/interceptor/MongoCollectionImplReadOperationInterceptor.java
plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/interceptor/MongoCollectionImplWriteOperationInterceptor.java
plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/interceptor/OperationExecutorImplExecuteInterceptor.java
plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/interceptor/OperationExecutorImplLambdaOnResultInterceptor.java
plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/interceptor/ReactiveMongoClientImplConstructorInterceptor.java
plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/interceptor/ReactiveMongoCollectionImplConstructorInterceptor.java
plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/interceptor/ReactiveMongoOperationPublisherConstructorInterceptor.java
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/interceptor/ParallelFluxSubscribeInterceptor.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/recorder/WrappedSpanEventRecorder.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/transformer/DefaultClassFileTransformerDispatcher.java

[#9610] Improvements to spring-data-mongodb-reactive

---

plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/interceptor/AbstractHandlerMethodMappingInterceptor.java
plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/interceptor/AbstractUrlHandlerMappingInterceptor.java
plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/interceptor/DispatchHandlerInvokeHandlerMethodInterceptor.java
plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/interceptor/ServerWebExchangeAttributeUtils.java
plugins/spring/src/main/java/com/navercorp/pinpoint/plugin/spring/web/interceptor/ExposePathWithinMappingInterceptor.java
plugins/spring/src/main/java/com/navercorp/pinpoint/plugin/spring/web/interceptor/LookupHandlerMethodInterceptor.java
plugins/spring/src/main/java/com/navercorp/pinpoint/plugin/spring/web/interceptor/ProcessRequestInterceptor.java
plugins/spring/src/main/java/com/navercorp/pinpoint/plugin/spring/web/interceptor/ServletRequestAttributeUtils.java
plugins/spring/src/test/java/com/navercorp/pinpoint/plugin/spring/web/interceptor/ServletRequestAttributeUtilsTest.java
plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/interceptor/RouteStateInterceptor.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/id/DefaultShared.java

[#9522] Polishing

---

profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/classloading/PlainClassLoaderHandler.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/ClassNameFilter.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/ClassNameFilterChain.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/PinpointProfilerPackageFilter.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/PinpointProfilerPackageSkipFilter.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/PluginPackageClassRequirementFilter.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/PluginPackageFilter.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/classloading/PlainClassLoaderHandlerTest.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/plugin/ClassNameFilterChainTest.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/plugin/PinpointProfilerPackageSkipFilterTest.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/plugin/PluginPackageFilterTest.java
profiler/src/test/java/com/navercorp/pinpoint/profiler/plugin/PluginPackageRequirementFilterTest.java

[#noissue] fix plugin package class requirement filter

---

web/src/main/web-frontend/packages/scatter-chart/package.json
web/src/main/web-frontend/packages/scatter-chart/src/ui/Legend.ts
web/src/main/web-frontend/packages/scatter-chart/tsconfig.json
web/src/main/web-frontend/packages/scatter-chart/tsup.config.dev.ts
web/src/main/web-frontend/packages/scatter-chart/tsup.config.production.ts
web/src/main/web-frontend/yarn.lock

- set build target to ES5
- move tsup build configuration to `tsup.config.**.ts`

refactor and fix  tsup configuration

---

web/src/main/web-frontend/packages/scatter-chart/README.md
web/src/main/web-frontend/packages/scatter-chart/package.json
web/src/main/web-frontend/packages/scatter-chart/src/constants/options.ts
web/src/main/web-frontend/packages/scatter-chart/src/constants/ui.ts
web/src/main/web-frontend/packages/scatter-chart/src/stories/index.stories.ts
web/src/main/web-frontend/packages/scatter-chart/src/stories/templates/createPinpointTheme.ts
web/src/main/web-frontend/packages/scatter-chart/src/types/types.ts
web/src/main/web-frontend/packages/scatter-chart/src/ui/Axis.ts
web/src/main/web-frontend/packages/scatter-chart/src/ui/Legend.ts
web/src/main/web-frontend/packages/scatter-chart/src/ui/ScatterChart.ts
web/src/main/web-frontend/packages/scatter-chart/src/ui/XAxis.ts
web/src/main/web-frontend/packages/scatter-chart/src/ui/YAxis.ts
web/src/main/web-frontend/packages/scatter-chart/src/utils/draw.ts
web/src/main/web-frontend/yarn.lock

- add `strokeColor` to `AxisOption`
- add `radius`, `opacity` to `DataOption`
- add `opacity` to `PointOptions`

[UI/UX][frontend-v3] feat: scatter-chart v1.1.0

---

plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/jakarta/interceptor/RequestStartAsyncInterceptor.java
plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/javax/interceptor/RequestStartAsyncInterceptor.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultBaseTraceFactory.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/active/ActiveTraceRepository.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/active/DefaultActiveTraceRepository.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/active/EmptyActiveTraceRepository.java

[#9595] Fix an issue where metric values in non sampling state were incorrect

---

web/src/main/angular/src/app/core/components/server-and-agent-list/server-and-agent-list.component.css
web/src/main/angular/src/app/core/components/server-and-agent-list/server-and-agent-list.component.html
web/src/main/angular/src/app/core/components/server-and-agent-list/server-and-agent-list.component.ts
web/src/main/angular/src/app/core/components/server-list/server-list.component.css
web/src/main/angular/src/app/core/components/server-list/server-list.component.html
web/src/main/angular/src/app/core/components/server-list/server-list.component.ts
web/src/main/angular/src/app/shared/services/browser-support-check.service.ts

- Update supported browser version info for the clipboard api usage

[#noissue] Add copy & paste interface on agent-list

---

uristat/uristat-collector/src/main/java/com/navercorp/pinpoint/uristat/collector/dao/PinotUriStatDao.java
uristat/uristat-collector/src/main/java/com/navercorp/pinpoint/uristat/collector/dao/UriStatDao.java
uristat/uristat-collector/src/main/java/com/navercorp/pinpoint/uristat/collector/model/UriStat.java
uristat/uristat-collector/src/main/java/com/navercorp/pinpoint/uristat/collector/service/PinotAgentUriStatService.java
uristat/uristat-collector/src/main/java/com/navercorp/pinpoint/uristat/collector/util/StringPrecondition.java
uristat/uristat-common/src/main/java/com/navercorp/pinpoint/uristat/common/model/UriStat.java
uristat/uristat-common/src/main/pinot/pinot-uriStat-schema.json
uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/controller/UriStatController.java
uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/dao/PinotUriStatDao.java
uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/dao/UriStatDao.java
uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/model/UriStatGroup.java
uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/model/UriStatHistogram.java
uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/model/UriStatSummary.java
uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/service/UriStatService.java
uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/service/UriStatServiceImpl.java
uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/util/UriStatQueryParameter.java
uristat/uristat-web/src/main/java/com/navercorp/pinpoint/uristat/web/view/UriStatView.java
uristat/uristat-web/src/main/resources/mapper/uristat/UriStatMapper.xml
uristat/uristat-web/src/main/resources/mybatis-pinot-web-config-uristat.xml

https://github.com/pinpoint-apm/pinpoint/pull/9719

[#9712] Add more data for uri statistics

---

web/src/main/web-frontend/packages/scatter-chart/README.md
web/src/main/web-frontend/packages/scatter-chart/package.json
web/src/main/web-frontend/packages/scatter-chart/src/constants/options.ts
web/src/main/web-frontend/packages/scatter-chart/src/constants/ui.ts
web/src/main/web-frontend/packages/scatter-chart/src/stories/index.stories.ts
web/src/main/web-frontend/packages/scatter-chart/src/stories/templates/createCustomizeTheme.ts
web/src/main/web-frontend/packages/scatter-chart/src/stories/templates/createInteractions.ts
web/src/main/web-frontend/packages/scatter-chart/src/types/types.ts
web/src/main/web-frontend/packages/scatter-chart/src/ui/Guide.ts
web/src/main/web-frontend/packages/scatter-chart/src/ui/Layer.ts
web/src/main/web-frontend/packages/scatter-chart/src/ui/Legend.ts
web/src/main/web-frontend/packages/scatter-chart/src/ui/ScatterChart.ts
web/src/main/web-frontend/packages/scatter-chart/src/ui/XAxis.ts
web/src/main/web-frontend/packages/scatter-chart/src/ui/YAxis.ts
web/src/main/web-frontend/packages/scatter-chart/test/helper.ts
web/src/main/web-frontend/packages/scatter-chart/test/scatter.test.ts

- to make `\n` recognized in the tick label
- Zero is displayed when data is not present in the legend
- add `clear()` method
- add `clickLegend` event type
- add `tick.padding` option

[#noissue][frontend-v3] feat: scatter-chart v1.2.0

---

plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/VertxPlugin.java

[#9734] Update to support vertx client versions 3.4 to 3.7

---

web/src/main/angular/src/app/core/components/url-statistic-info/url-statistic-info.component.css
web/src/main/angular/src/app/core/components/url-statistic-info/url-statistic-info.component.html

- Change total-count cell expression

[#noissue] Widen url-info and total-count column

---

web/src/main/web-frontend/packages/scatter-chart/README.md
web/src/main/web-frontend/packages/scatter-chart/package.json
web/src/main/web-frontend/packages/scatter-chart/src/constants/ui.ts
web/src/main/web-frontend/packages/scatter-chart/src/index.ts
web/src/main/web-frontend/packages/scatter-chart/src/ui/Guide.ts
web/src/main/web-frontend/packages/scatter-chart/src/ui/Layer.ts
web/src/main/web-frontend/packages/scatter-chart/src/ui/Viewport.ts
web/src/main/web-frontend/packages/scatter-chart/src/ui/index.ts
web/src/main/web-frontend/packages/scatter-chart/src/utils/helper.ts

- fix cross browser issue
- export declared types

[#noissue][UI/UX][frontend-v3] ScatterChart v1.3.4

---

agent-testweb/spring-data-r2dbc-plugin-testweb/src/main/java/com/pinpoint/test/plugin/MysqlR2dbcDatabase.java
agent-testweb/spring-data-r2dbc-plugin-testweb/src/main/java/com/pinpoint/test/plugin/SpringDataR2dbcPluginController.java
agent-testweb/spring-data-r2dbc-plugin-testweb/src/test/java/com/pinpoint/test/plugin/spring/data/r2dbc/R2dbcMysqlTest.java
plugins/spring-data-r2dbc/src/main/java/com/navercorp/pinpoint/plugin/spring/r2dbc/SpringDataR2dbcPlugin.java
plugins/spring-data-r2dbc/src/main/java/com/navercorp/pinpoint/plugin/spring/r2dbc/interceptor/DefaultGenericExecuteSpecStatementFunctionGetLambdaInterceptor.java
plugins/spring-data-r2dbc/src/main/java/com/navercorp/pinpoint/plugin/spring/r2dbc/interceptor/SetDatabaseInfoConstructorInterceptor.java

[#9799] Add connection factory to spring r2dbc plugin

---

.github/workflows/it-command.yml
.github/workflows/it-schedule.yml
.github/workflows/maven-central-deploy.yml
.github/workflows/maven.yml

Update actions/checkout, codecov/codecov-action, actions/setup-java
remove codecov/codecov-action files option

[#noissue] update github action

---

plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/VertxDetector.java
plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/interceptor/ContextImplExecuteBlockingInterceptor.java
plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/interceptor/ContextImplRunOnContextInterceptor.java
plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/interceptor/Http1xClientConnectionCreateRequestInterceptor.java
plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/interceptor/HttpClientImplDoRequestInterceptor.java
plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/interceptor/HttpClientImplDoRequestInterceptorV4.java
plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/interceptor/HttpClientRequestImplConstructorInterceptor.java
plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/interceptor/HttpClientRequestImplDoHandleResponseInterceptor.java
plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/interceptor/HttpClientRequestImplInterceptor.java
plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/interceptor/HttpClientStreamInterceptor.java
plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/interceptor/HttpServerRequestAdaptor.java
plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/interceptor/HttpServerRequestImplHandleEndInterceptor.java
plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/interceptor/ServerConnectionHandleRequestInterceptor.java

[#9822] Fix service type detector for vertx 4.x

---

agent-plugins/proxy-user/src/main/java/com/navercorp/pinpoint/agent/plugin/proxy/user/UserRequestParser.java
agent-plugins/proxy-user/src/test/java/com/navercorp/pinpoint/agent/plugin/proxy/user/UserRequestParserTest.java

Fix nginx variable t=$msec parse in Proxy-User module #9784

[#9784] Fix nginx variable t=$msec parse in Proxy-User module

---

web-frontend/src/main/v3/packages/scatter-chart/README.md
web-frontend/src/main/v3/packages/scatter-chart/jest.config.js
web-frontend/src/main/v3/packages/scatter-chart/package.json
web-frontend/src/main/v3/packages/scatter-chart/src/ui/ScatterChart.ts
web-frontend/src/main/v3/packages/scatter-chart/test/axis.test.ts
web-frontend/src/main/v3/packages/scatter-chart/test/helper.ts

- rename `getOption` api
- remove useless config file

[#8929][UI/UX/V3] fix api name, clean up config file

---

bootstraps/bootstrap-java9/src/main/java/com/navercorp/pinpoint/bootstrap/java9/classloader/Java9ClassLoader.java
bootstraps/bootstrap-java9/src/main/java/com/navercorp/pinpoint/bootstrap/java9/module/ModuleSupport.java
bootstraps/bootstrap-java9/src/main/java/com/navercorp/pinpoint/bootstrap/java9/module/ModuleSupportFactory.java

Removed manually registering providers which occurs duplication

[#8890] Backport: Implemented findClass in Java9ClassLoader

---

profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultBaseTraceFactory.java

[#9962] backport: fix duplicated active trace

---

metric-module/metric/src/main/pinot/pinot-double-offline-table.json
uristat/uristat-common/src/main/pinot/pinot-uriStat-offline-table.json

[#10003] backport: add pinot offline table ingestionConfig

---

bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/Profiles.java
bootstraps/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/config/ProfilePropertyLoader.java
redis/pom.xml
tools/src/main/java/com/navercorp/pinpoint/tools/NetworkAvailabilityChecker.java

[#10018] Suggest dynamic list of available agent profiles

---

plugins/undertow/src/main/java/com/navercorp/pinpoint/plugin/undertow/interceptor/ConnectorsExecuteRootHandlerInterceptor.java

[#10010] backport: fix undertow plugin

---

web-frontend/src/main/angular/src/app/core/components/server-map/class/server-map-diagram-with-cytoscapejs.class.ts
web-frontend/src/main/angular/src/app/core/components/server-map/class/server-map-diagram.class.ts
web-frontend/src/main/angular/src/app/core/components/server-map/server-map-container.component.html
web-frontend/src/main/angular/src/app/core/components/server-map/server-map-container.component.ts
web-frontend/src/main/angular/src/app/core/components/server-map/server-map.component.ts
web-frontend/src/main/angular/src/app/shared/services/system-configuration-data.service.ts

- Optimize data update
- Enhance layout update
- Provide it as an experimental option temporarily

[#noissue] Enhance server-map update in realtime

---

realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/activethread/count/websocket/ActiveThreadCountHandlerImpl.java
realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/service/AgentLookupService.java
realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/service/AgentLookupServiceImpl.java
realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/service/RealtimeWebServiceConfig.java

[#10035] Fixed agent list in active request

---

web-frontend/src/main/v3/packages/scatter-chart/README.md
web-frontend/src/main/v3/packages/scatter-chart/package.json
web-frontend/src/main/v3/packages/scatter-chart/src/stories/index.stories.ts
web-frontend/src/main/v3/packages/scatter-chart/src/stories/mock/realtimeData.json
web-frontend/src/main/v3/packages/scatter-chart/src/stories/templates/createAppendDatas.ts
web-frontend/src/main/v3/packages/scatter-chart/src/stories/templates/createCaptureImage.ts
web-frontend/src/main/v3/packages/scatter-chart/src/stories/templates/createCustomizeTheme.ts
web-frontend/src/main/v3/packages/scatter-chart/src/stories/templates/createDefault.ts
web-frontend/src/main/v3/packages/scatter-chart/src/stories/templates/createDestroy.ts
web-frontend/src/main/v3/packages/scatter-chart/src/stories/templates/createHideLegend.ts
web-frontend/src/main/v3/packages/scatter-chart/src/stories/templates/createInteractions.ts
web-frontend/src/main/v3/packages/scatter-chart/src/stories/templates/createMultipleCharts.ts
web-frontend/src/main/v3/packages/scatter-chart/src/stories/templates/createPinpointTheme.ts
web-frontend/src/main/v3/packages/scatter-chart/src/stories/templates/createRealtime.ts
web-frontend/src/main/v3/packages/scatter-chart/src/stories/templates/createResizable.ts
web-frontend/src/main/v3/packages/scatter-chart/src/stories/templates/createSetOption.ts
web-frontend/src/main/v3/packages/scatter-chart/src/style/index.css
web-frontend/src/main/v3/packages/scatter-chart/src/types/types.ts
web-frontend/src/main/v3/packages/scatter-chart/src/ui/Axis.ts
web-frontend/src/main/v3/packages/scatter-chart/src/ui/GridAxis.ts
web-frontend/src/main/v3/packages/scatter-chart/src/ui/Legend.ts
web-frontend/src/main/v3/packages/scatter-chart/src/ui/ScatterChart.ts
web-frontend/src/main/v3/packages/scatter-chart/src/utils/draw.ts
web-frontend/src/main/v3/packages/scatter-chart/src/utils/helper.ts
web-frontend/src/main/v3/packages/scatter-chart/test/scatter.test.ts
web-frontend/src/main/v3/packages/scatter-chart/tsconfig.json

- isRealtime: Getter that returns a boolean value indicating whether the current chart is in realtime mode.
- LegendOption
- hidden: Hide the legend if `true`
- GuideOption
- hidden: Hide guide when hidden is `true`. In addition, `click` and `dragEnd` events do not work.
- Fixed a case where clicking the legend when there are multiple scatter charts behaves incorrectly
https://www.npmjs.com/package/@pinpoint-fe/scatter-chart/v/1.5.0?activeTab=versions

[#8929][Frontend v3] Scatter chart v1.5.0

---

web/src/main/java/com/navercorp/pinpoint/web/websocket/PinpointWebSocketConfigurer.java

[#10046] Removed unnecessary ws own prefix

---

web/src/main/java/com/navercorp/pinpoint/web/authorization/controller/ScatterChartController.java

[#10081] Added annotative param validations

---

web-frontend/src/main/angular/src/app/core/components/metric/metric-container.component.ts
web-frontend/src/main/angular/src/app/core/components/url-statistic-chart/index.ts
web-frontend/src/main/angular/src/app/core/components/url-statistic-chart/url-statistic-bar-chart.component.ts
web-frontend/src/main/angular/src/app/core/components/url-statistic-chart/url-statistic-chart-container.component.html
web-frontend/src/main/angular/src/app/core/components/url-statistic-chart/url-statistic-chart-container.component.ts
web-frontend/src/main/angular/src/app/core/components/url-statistic-chart/url-statistic-chart-default-chart.component.ts
web-frontend/src/main/angular/src/app/core/components/url-statistic-chart/url-statistic-chart.component.css
web-frontend/src/main/angular/src/app/core/components/url-statistic-chart/url-statistic-chart.component.ts
web-frontend/src/main/angular/src/app/core/components/url-statistic-chart/url-statistic-line-chart.component.ts
web-frontend/src/main/angular/src/globals.d.ts
web-frontend/src/main/angular/src/styles.css

[#9942] Add charts in url stat page

---

web-frontend/src/main/v3/packages/server-map/package.json
web-frontend/src/main/v3/packages/server-map/src/core/merge.ts
web-frontend/src/main/v3/packages/server-map/src/types/index.ts
web-frontend/src/main/v3/packages/server-map/src/ui/ServerMap.tsx
web-frontend/src/main/v3/yarn.lock

- new feature
- onDataMerged
- `onDataMerged?: (mergeInfo: MergeInfo) => void;` 
- execute callback when merge logic finished.
- fix
- wrong event callback data  
- mouse cursor styles

[#8929][Frontend v3] feat: onDataMerged, fix some bugs

---

collector/src/main/java/com/navercorp/pinpoint/collector/service/HbaseTraceService.java
collector/src/main/java/com/navercorp/pinpoint/collector/service/SpanEventPublisherService.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/event/SpanChunkInsertionEvent.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/event/SpanInsertionEvent.java

[#10123] Publish an event when inserting spans

---

realtime/realtime-common/src/main/java/com/navercorp/pinpoint/realtime/dto/mapper/ThriftToGrpcConverter.java
realtime/realtime-common/src/main/java/com/navercorp/pinpoint/realtime/dto/mapper/grpc/ATDSupplyMapper.java
realtime/realtime-common/src/main/java/com/navercorp/pinpoint/realtime/dto/mapper/grpc/ActiveThreadDumpMapper.java
realtime/realtime-common/src/main/java/com/navercorp/pinpoint/realtime/dto/mapper/grpc/ThreadDumpMapper.java

[#9666] Added null-check before converting thrift to grpc

---

web-frontend/src/main/v3/packages/server-map/package.json

- Update package.json with version update

[#8929] Add dist

---

web-frontend/src/main/v3/packages/scatter-chart/README.md
web-frontend/src/main/v3/packages/scatter-chart/package.json
web-frontend/src/main/v3/packages/scatter-chart/src/stories/templates/createCustomizeTheme.ts
web-frontend/src/main/v3/packages/scatter-chart/src/types/types.ts
web-frontend/src/main/v3/packages/scatter-chart/src/ui/Axis.ts
web-frontend/src/main/v3/packages/scatter-chart/src/ui/Guide.ts
web-frontend/src/main/v3/packages/scatter-chart/src/ui/Layer.ts
web-frontend/src/main/v3/packages/scatter-chart/src/ui/ScatterChart.ts
web-frontend/src/main/v3/packages/scatter-chart/src/ui/Viewport.ts
web-frontend/src/main/v3/packages/scatter-chart/src/ui/XAxis.ts
web-frontend/src/main/v3/packages/scatter-chart/src/ui/YAxis.ts

- fix: Resolving the initialization of the context.font style when calling `resize()` api
- feat: `font` option for Guide

[#8929][Frontend-v3] feat guide font option, fix resize bug

---

plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/HttpIOHandlerObserverOnStateChangeInterceptor.java

[#10187] Fix NPE in the reactor-netty plugin

---

web-frontend/src/main/v3/packages/server-map/package.json
web-frontend/src/main/v3/packages/server-map/src/ui/ServerMap.tsx

[#8929] Provide servermap ref

---

realtime/realtime-web/src/main/java/com/navercorp/pinpoint/web/realtime/activethread/count/websocket/RedisActiveThreadCountWebSocketHandler.java

[#10218] Realtime ATC on redis can switch application

---

web/src/main/java/com/navercorp/pinpoint/web/servlet/RewriteForV2Filter.java
web/src/test/java/com/navercorp/pinpoint/web/servlet/RewriteForV2FilterTest.java

[#10256] Removed rule of finalizing path for API with .pinpoint

---

agent-testweb/spring-webflux-plugin-testweb/src/main/java/com/pinpoint/test/plugin/SpringWebfluxPluginController.java
agent/src/main/resources/profiles/local/pinpoint.config
agent/src/main/resources/profiles/release/pinpoint.config
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/ReactorNettyPlugin.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/ReactorNettyPluginConfig.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/ClientTransportSubscriberInterceptor.java
plugins/reactor-netty/src/main/java/com/navercorp/pinpoint/plugin/reactor/netty/interceptor/HttpObserverOnUncaughtExceptionInterceptor.java
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/ReactorConstants.java
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/ReactorPlugin.java
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/ReactorPluginConfig.java
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/interceptor/OnErrorSubscriberInterceptor.java

[#10329] Backport: update reactor error handler

---

agent/src/main/resources/profiles/local/pinpoint.config
agent/src/main/resources/profiles/release/pinpoint.config
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/ReactorPlugin.java
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/ReactorPluginConfig.java
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/interceptor/FluxAndMonoSubscribeOnInterceptor.java

[#10333] Update reactor publishOn, subscribeOn options

---

web-frontend/src/main/v3/packages/server-map/package.json
web-frontend/src/main/v3/packages/server-map/src/ui/ServerMap.tsx

- Trigger tap event on the baseNode when the selectedElement has been removed

[#8929] Set selectedElement state

---

pom.xml

[#10352] Bump maven failsafe plugin from 2.22.2 to  3.1.2

---

web-frontend/src/main/v3/packages/server-map/package.json
web-frontend/src/main/v3/packages/server-map/src/core/merge.ts

- Prevent potential duplicated id

[#8929] Fix server-map merged elements id

---

agent-testweb/reactor-plugin-testweb/pom.xml
agent-testweb/reactor-plugin-testweb/src/main/java/com/pinpoint/test/plugin/ReactorPluginController.java
agent/src/main/resources/profiles/local/pinpoint.config
agent/src/main/resources/profiles/release/pinpoint.config
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/ReactorPlugin.java
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/ReactorPluginConfig.java
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/interceptor/FluxAndMonoDelayInterceptor.java
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/interceptor/FluxAndMonoIntervalInterceptor.java

[#10418] Update reactor threading

---

agent/src/main/resources/profiles/local/pinpoint.config
agent/src/main/resources/profiles/release/pinpoint.config
plugins/spring-tx/src/main/java/com/navercorp/pinpoint/plugin/spring/tx/SpringTxConfig.java
plugins/spring-tx/src/main/java/com/navercorp/pinpoint/plugin/spring/tx/interceptor/ReactiveTransactionSupportInterceptor.java
plugins/spring-tx/src/main/java/com/navercorp/pinpoint/plugin/spring/tx/interceptor/TransactionAspectSupportInterceptor.java

[#10437] Update mark error of spring tx plugin

---

bootstraps/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/agentdir/AgentDirBaseClassPathResolver.java
bootstraps/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/agentdir/JarDescription.java
bootstraps/bootstrap/src/test/java/com/navercorp/pinpoint/bootstrap/agentdir/AgentVersionTest.java

[#10462] Allow more pattern for version postfix

---

agent/src/main/resources/profiles/local/pinpoint.config
agent/src/main/resources/profiles/release/pinpoint.config
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/ReactorPluginConfig.java
plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/interceptor/RetryWhenMainSubscriberInterceptor.java

[#10454] update reactor retry when

---

agent/src/main/resources/profiles/local/pinpoint.config
agent/src/main/resources/profiles/release/pinpoint.config
plugins/resilience4j/src/main/java/com/navercorp/pinpoint/plugin/resilience4j/Resilience4JPluginConfig.java
plugins/resilience4j/src/main/java/com/navercorp/pinpoint/plugin/resilience4j/interceptor/CircuitBreakerSubscriberInterceptor.java

[#10454] Update resilience4j hook on error

---

web/src/main/java/com/navercorp/pinpoint/web/calltree/span/CallTreeIterator.java
web/src/main/java/com/navercorp/pinpoint/web/view/TransactionInfoViewModel.java
web/src/test/java/com/navercorp/pinpoint/web/calltree/span/CallTreeIteratorTest.java

[#10517] Fix nodes is null in transaction info request

---

agent-testweb/vertx-4-plugin-testweb/pom.xml
agent-testweb/vertx-4-plugin-testweb/src/main/java/com/pinpoint/test/plugin/Vertx4PluginTestStarter.java
plugins/vertx/README.md
plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/VertxPlugin.java
plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/interceptor/HttpClientImplCreateRequestInterceptor.java
plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/interceptor/HttpClientImplDoRequestInterceptorV4.java

[#10534] Update vertx plugin to support vert.x 4.5.0 version

---

commons/src/main/java/com/navercorp/pinpoint/common/util/JvmVersion.java
commons/src/test/java/com/navercorp/pinpoint/common/util/JvmVersionTest.java
pom.xml

[#10543] bump asm from 9.5 to 9.6

---

collector/src/main/java/com/navercorp/pinpoint/collector/mapper/grpc/stat/GrpcJvmGcTypeMapper.java
collector/src/test/java/com/navercorp/pinpoint/collector/mapper/grpc/stat/GrpcJvmGcTypeMapperTest.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/JvmGcType.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/context/grpc/GrpcJvmGcTypeMessageConverter.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/monitor/metric/gc/GarbageCollectorType.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/monitor/metric/gc/JvmGcType.java

[#10547] add zgc(java gc) type to the agent

---

bootstraps/bootstrap-java9/src/main/java/com/navercorp/pinpoint/bootstrap/java9/module/ModuleLogLevel.java
bootstraps/bootstrap-java9/src/main/java/com/navercorp/pinpoint/bootstrap/java9/module/ModuleLogger.java

[#10566] Set the log level of ModuleBoot using system env

---

redis/src/main/java/com/navercorp/pinpoint/redis/RedisBasicConfig.java
redis/src/main/resources/redis/redis-root.properties

[#10557] disable lettuce native kqueue transport

---

pinot/pinot-datasource/pom.xml
pom.xml

[#10582] Bump pinot jdbc client from 0.11.0 to 1.0.0

---

plugins/kotlin-coroutines/src/main/java/com/navercorp/pinpoint/plugin/kotlinx/coroutines/interceptor/DispatchInterceptor.java

[#10612] Fix kotlin coroutines dispatch interceptor

---

plugins/kotlin-coroutines/src/main/java/com/navercorp/pinpoint/plugin/kotlinx/coroutines/interceptor/DispatchInterceptor.java

[#10630] Backport: Fix kotlin coroutines dispatch interceptor

---

profiler/src/main/java/com/navercorp/pinpoint/profiler/context/grpc/GrpcSpanMessageConverter.java

[#10549] Fix grpc async span chunk converter

---

profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/SpanGrpcDataSender.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/StatGrpcDataSender.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/StreamTask.java
profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/grpc/stream/DefaultStreamTask.java

[#10614]  Fix stream task check

---

bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/instrument/transformer/TransformCallbackParameter.java
bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/instrument/transformer/TransformCallbackParameters.java
bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/instrument/transformer/TransformCallbackParametersBuilder.java
bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/instrument/transformer/TransformOperations.java
bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/instrument/transformer/TransformTemplate.java
bootstraps/bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/instrument/transformer/TransformCallbackParameterTest.java
plugins/redis-lettuce/src/main/java/com/navercorp/pinpoint/plugin/redis/lettuce/LettucePlugin.java
plugins/rxjava/src/main/java/com/navercorp/pinpoint/plugin/rxjava/RxJavaPlugin.java
plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/SpringWebFluxPlugin.java
plugins/spring/src/main/java/com/navercorp/pinpoint/plugin/spring/web/SpringWebMvcPlugin.java
plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/ThriftPlugin.java
plugins/user/src/main/java/com/navercorp/pinpoint/plugin/user/UserPlugin.java
plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/VertxPlugin.java

[#10651] Changed transform api for plugin

---

collector/src/main/java/com/navercorp/pinpoint/collector/config/CollectorConfiguration.java
collector/src/main/java/com/navercorp/pinpoint/collector/config/CollectorProperties.java
collector/src/main/java/com/navercorp/pinpoint/collector/handler/grpc/GrpcSpanChunkHandler.java
collector/src/main/java/com/navercorp/pinpoint/collector/handler/grpc/GrpcSpanHandler.java
collector/src/main/java/com/navercorp/pinpoint/collector/sampler/FalseSampler.java
collector/src/main/java/com/navercorp/pinpoint/collector/sampler/ModSampler.java
collector/src/main/java/com/navercorp/pinpoint/collector/sampler/PercentRateSampler.java
collector/src/main/java/com/navercorp/pinpoint/collector/sampler/Sampler.java
collector/src/main/java/com/navercorp/pinpoint/collector/sampler/SamplerType.java
collector/src/main/java/com/navercorp/pinpoint/collector/sampler/SimpleSpanSamplerFactory.java
collector/src/main/java/com/navercorp/pinpoint/collector/sampler/SpanSamplerFactory.java
collector/src/main/java/com/navercorp/pinpoint/collector/sampler/TrueSampler.java
collector/src/main/resources/pinpoint-collector-root.properties
collector/src/test/java/com/navercorp/pinpoint/collector/sampler/SamplerTest.java
collector/src/test/java/com/navercorp/pinpoint/collector/sampler/SimpleSpanFactoryTest.java

[#10666] add span sampler for collector

---

collector/pom.xml
log/log-collector/pom.xml
metric-module/collector-starter/pom.xml
metric-module/web-starter/pom.xml
web/pom.xml
webhook/pom.xml

[#10667] Removed 'boot' word from executable JAR

---

inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/service/DefaultAgentStatService.java
inspector-module/inspector-web/src/main/java/com/navercorp/pinpoint/inspector/web/service/DefaultApplicationStatService.java
inspector-module/inspector-web/src/main/resources/inspector/web/inspector-definition-for-agent.yml
inspector-module/inspector-web/src/main/resources/inspector/web/inspector-definition-for-application.yml

[#9597] Enable alias operation for field name. Max data of nonHeap is also returned.

[#9597] Enable alias operation for field name. Max data of nonHeap is also returned.

---

plugins/jetty/pom.xml
plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/JettyPlugin.java
plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/jakarta/JettyAsyncListener.java
plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/jakarta/interceptor/AbstractServerHandleInterceptor.java
plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/jakarta/interceptor/Jetty11xServerHandleInterceptor.java
plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/jakarta/interceptor/RequestStartAsyncInterceptor.java
plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/javax/JettyAsyncListener.java
plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/javax/interceptor/AbstractServerHandleInterceptor.java
plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/javax/interceptor/Jetty80ServerHandleInterceptor.java
plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/javax/interceptor/Jetty8xServerHandleInterceptor.java
plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/javax/interceptor/Jetty9xServerHandleInterceptor.java
plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/javax/interceptor/RequestStartAsyncInterceptor.java

Support for Jetty Using Jakarta Servlet. 
With this, PINPOINT can track data in Spring Boot 3.x when using Jetty, just as before.
Thank 😄

[#NotAssigned] Support for Jetty Using Jakarta Servlet

---

agent/src/main/resources/profiles/local/pinpoint.config
agent/src/main/resources/profiles/release/pinpoint.config
commons/src/main/java/com/navercorp/pinpoint/common/trace/ServiceType.java
plugins/assembly/pom.xml
plugins/pom.xml
plugins/spring-cloud-sleuth/README.md
plugins/spring-cloud-sleuth/pom.xml
plugins/spring-cloud-sleuth/src/main/java/com/navercorp/pinpoint/plugin/spring/cloud/sleuth/SpringCloudSleuthConstants.java
plugins/spring-cloud-sleuth/src/main/java/com/navercorp/pinpoint/plugin/spring/cloud/sleuth/SpringCloudSleuthPlugin.java
plugins/spring-cloud-sleuth/src/main/java/com/navercorp/pinpoint/plugin/spring/cloud/sleuth/SpringCloudSleuthPluginConfig.java
plugins/spring-cloud-sleuth/src/main/resources/META-INF/pinpoint/type-provider.yml
plugins/spring-cloud-sleuth/src/main/resources/META-INF/services/com.navercorp.pinpoint.bootstrap.plugin.ProfilerPlugin

[#10708] Add spring cloud sleuth

---

agent-module/plugins/resttemplate/src/main/java/com/navercorp/pinpoint/plugin/resttemplate/RestTemplatePlugin.java
agent-module/plugins/resttemplate/src/main/java/com/navercorp/pinpoint/plugin/resttemplate/interceptor/ListenableFutureInterceptor.java

[#10772] Fix interceptor option in resttemplate plugin

---

agent-module/plugins/spring-boot/src/main/java/com/navercorp/pinpoint/plugin/spring/boot/SpringBootPlugin.java
agent-module/plugins/spring-boot/src/main/java/com/navercorp/pinpoint/plugin/spring/boot/interceptor/LauncherLaunchInterceptor.java

1. location 
- spring-boot < 3.2
- `org.springframework.boot.loader.Launcher `
- spring-boot >= 3.2
- `org.springframework.boot.loader.launch.Launcher`
2. method signature 
- spring-boot < 3.2
- `protected void launch(String[] args, String mainClass, ClassLoader classLoader) throws Exception`
- spring-boot >= 3.2
- `protected void launch(ClassLoader classLoader, String mainClassName, String[] args) throws Exception`

[#NotAssigned] Resolve issue for rewritten launcher on spring-boot 3.2

---

web-frontend/src/main/v3/packages/ui/src/lib/charts/useDataSourceChartTooltip.ts

- Match data based on the name, not the index

[#noissue] Fix inspector agent-datasource chart

---

web-frontend/src/main/v3/packages/ui/src/pages/Inspector.tsx
web-frontend/src/main/v3/packages/utils/src/helper/route.ts

- Keep only date range when switching pages

[#noissue] Fix route query in switching pages

---

plugins/spring-boot/src/main/java/com/navercorp/pinpoint/plugin/spring/boot/SpringBootPlugin.java
plugins/spring-boot/src/main/java/com/navercorp/pinpoint/plugin/spring/boot/interceptor/LauncherLaunchInterceptor.java

[#10828] Backport: Resolve issue for rewritten launcher on spring-boot 3.2

---

agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/registry/DefaultInterceptorRegistryAdaptor.java
agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/registry/EmptyRegistryAdaptor.java
agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/registry/InterceptorRegistry.java
agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/registry/InterceptorRegistryAdaptor.java
agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMMethod.java
agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMMethodVariables.java

[#10859] Fix interceptorHolder on bootstrap classloader

---

web-frontend/src/main/v3/apps/web/src/components/Layout/LayoutWithSideNavigation.tsx
web-frontend/src/main/v3/apps/web/src/components/ServerList/ServerListFetcher.tsx
web-frontend/src/main/v3/packages/ui/src/components/Inspector/agent-info/InspectorAgentInfoFetcher.tsx
web-frontend/src/main/v3/packages/ui/src/pages/Inspector.tsx

- Expose inspector menu in side-navigation
- Bind v3 inspector page on the server-list in server-map page

[#noissue] Add inspector menu in v3

---

web-frontend/src/main/v3/packages/ui/src/components/Agent/AgentListFetcher.tsx
web-frontend/src/main/v3/packages/ui/src/components/Agent/AgentSearchList.tsx
web-frontend/src/main/v3/packages/ui/src/components/ErrorAnalysis/sidebar/ErrorAnalysisSidebar.tsx
web-frontend/src/main/v3/packages/ui/src/components/Host/HostListFetcher.tsx
web-frontend/src/main/v3/packages/ui/src/components/Host/HostSearchList.tsx
web-frontend/src/main/v3/packages/ui/src/components/Inspector/sidebar/InspectorSidebar.tsx
web-frontend/src/main/v3/packages/ui/src/components/Sidebar/Sidebar.tsx
web-frontend/src/main/v3/packages/ui/src/components/URL/sidebar/UrlSidebar.tsx
web-frontend/src/main/v3/packages/ui/src/pages/ErrorAnalysis.tsx
web-frontend/src/main/v3/packages/ui/src/pages/Inspector.tsx
web-frontend/src/main/v3/packages/ui/src/pages/ScatterFullScreen.tsx
web-frontend/src/main/v3/packages/ui/src/pages/SystemMetric.tsx
web-frontend/src/main/v3/packages/ui/src/pages/UrlStatistic.tsx

- Displayed on top of the selected agent
- Fix height

[#noissue] chore: fix agent list UI

---

agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMMethod.java

[#10859] Fix interceptor holder log NPE

---

web-frontend/src/main/v3/packages/ui/src/pages/ErrorAnalysis.tsx
web-frontend/src/main/v3/packages/ui/src/pages/Inspector.tsx
web-frontend/src/main/v3/packages/ui/src/pages/UrlStatistic.tsx

- add `ApplicationList ` interface for few pages(ErrorAnalysis, Inspector, UrlStatistic)

[#noissue] feat: add applicationList interface for few pages

---

web-frontend/src/main/v3/apps/web/src/routes/loader/inspector.ts

- Change merging query param order

[#noissue] Fix inspector route loader

---

.github/workflows/create-dockerfiles.yml

on release -> on workflow_dispatch

Modify create-dockerfiles.yml

---

agent-module/agent-testweb/mongodb-plugin-testweb/pom.xml
agent-module/agent-testweb/mongodb-plugin-testweb/src/main/java/com/pinpoint/test/plugin/MongoConfig.java
agent-module/agent-testweb/mongodb-plugin-testweb/src/main/java/com/pinpoint/test/plugin/MongoPluginController.java
agent-module/agent-testweb/mongodb-plugin-testweb/src/test/java/com/pinpoint/test/plugin/mongo/MongodbTest.java
agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/UnKnownDatabaseInfo.java
agent-module/plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/MongoConstants.java
agent-module/plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/MongoPlugin.java
agent-module/plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/interceptor/DatabaseInfoUtils.java
agent-module/plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/interceptor/MongoClientConstructorInterceptor.java
agent-module/plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/interceptor/MongoCollectionImplReadOperationInterceptor.java
agent-module/plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/interceptor/MongoCollectionImplWriteOperationInterceptor.java
agent-module/plugins/mongodb/src/test/java/com/navercorp/pinpoint/plugin/mongo/interceptor/DatabaseInfoUtilsTest.java

[#10940] Fix mongodb reactive streams driver interceptor

---

web-frontend/src/main/v3/packages/ui/src/components/Error/ErrorBoundary.tsx

- Fixing the issue of not re-rendering the component when there is no error.

[#noissue] fix error boundary

---

bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/UnKnownDatabaseInfo.java
plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/MongoConstants.java
plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/MongoPlugin.java
plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/interceptor/DatabaseInfoUtils.java
plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/interceptor/MongoClientConstructorInterceptor.java
plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/interceptor/MongoCollectionImplReadOperationInterceptor.java
plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/interceptor/MongoCollectionImplWriteOperationInterceptor.java
plugins/mongodb/src/test/java/com/navercorp/pinpoint/plugin/mongo/interceptor/DatabaseInfoUtilsTest.java

[#10948] Backport: Fix mongodb reactive streams driver interceptor

---

bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/MongoDatabaseInfo.java
plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/MongoConstants.java
plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/MongoPlugin.java
plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/interceptor/MongoClientV4ConstructorInterceptor.java
plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/interceptor/MongoCollectionImplReadOperationInterceptor.java
plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/interceptor/MongoCollectionImplWriteOperationInterceptor.java
plugins/mongodb/src/test/java/com/navercorp/pinpoint/plugin/mongo/interceptor/DatabaseInfoUtilsTest.java

Backport fix mongodb mongoclient

---

web-frontend/src/main/v3/apps/web/src/routes/loader/inspector.ts
web-frontend/src/main/v3/packages/constants/src/date.ts
web-frontend/src/main/v3/packages/ui/src/pages/Inspector.tsx

[#noissue] Change inspector max date-range

---

web-frontend/pom.xml
web-frontend/src/assembly/frontend.xml
web-frontend/src/main/v3/packages/datetime-picker/package.json
web-frontend/src/main/v3/packages/scatter-chart/package.json
web-frontend/src/main/v3/packages/server-map/package.json

- Add v3 build script
- Package the common module

[#noissue] Add v3 build script

---

agent/src/main/resources/profiles/local/pinpoint.config
agent/src/main/resources/profiles/release/pinpoint.config
plugins/spring-tx/src/main/java/com/navercorp/pinpoint/plugin/spring/tx/SpringTxConfig.java
plugins/spring-tx/src/main/java/com/navercorp/pinpoint/plugin/spring/tx/interceptor/ReactiveTransactionSupportInterceptor.java
plugins/spring-tx/src/main/java/com/navercorp/pinpoint/plugin/spring/tx/interceptor/TransactionAspectSupportInterceptor.java

[#10974] Backport: Update mark error of spring tx plugin

---

web-angular/src/main/angular/src/app/core/components/info-per-server/info-per-server-container.component.ts
web-angular/src/main/angular/src/app/core/components/info-per-server/info-per-server-for-filtered-map-container.component.ts
web-angular/src/main/angular/src/app/core/components/server-and-agent-list/server-and-agent-list-container.component.ts
web-angular/src/main/angular/src/app/core/components/server-and-agent-list/server-and-agent-list-data.service.ts
web-angular/src/main/angular/src/app/core/components/server-list/server-list-container.component.ts

- Pass applicationPairs and serviceTypeCode info

[#10966] Pass additional params for agent-list api

---

batch/src/main/java/com/navercorp/pinpoint/batch/alarm/AlarmWriter.java
batch/src/main/java/com/navercorp/pinpoint/batch/job/AgentCountWriter.java
batch/src/main/java/com/navercorp/pinpoint/batch/job/AgentRemover.java
batch/src/main/java/com/navercorp/pinpoint/batch/job/ApplicationRemover.java
batch/src/main/java/com/navercorp/pinpoint/batch/job/CleanTargetWriter.java
batch/src/main/java/com/navercorp/pinpoint/batch/job/EmptyItemWriter.java
batch/src/main/java/com/navercorp/pinpoint/batch/job/ItemListWriter.java
batch/src/test/java/com/navercorp/pinpoint/batch/alarm/AlarmJobTest.java
batch/src/test/java/com/navercorp/pinpoint/batch/alarm/AlarmWriterIsolationTest.java
batch/src/test/java/com/navercorp/pinpoint/batch/alarm/AlarmWriterTest.java
pom.xml
uristat/uristat-batch/src/main/java/com/navercorp/pinpoint/batch/alarm/UriStatAlarmWriter.java

https://github.com/spring-projects/spring-batch/wiki/Spring-Batch-5.0-Migration-Guide
**Database schema needs to be updated**
https://github.com/spring-projects/spring-batch/tree/main/spring-batch-core/src/main/resources/org/springframework/batch/core/migration

 [#10900] Bump spring-batch from 4.3.7 to 5.1.1

---

web-frontend/src/main/v3/packages/ui/src/components/Agent/AgentSearchList.tsx
web-frontend/src/main/v3/packages/ui/src/components/Button/ApplicationLinkButton.tsx
web-frontend/src/main/v3/packages/ui/src/components/ErrorAnalysis/sidebar/ErrorAnalysisGroupBySkeleton.tsx
web-frontend/src/main/v3/packages/ui/src/components/ErrorAnalysis/sidebar/ErrorAnalysisSidebar.tsx
web-frontend/src/main/v3/packages/ui/src/components/Inspector/sidebar/InspectorSidebar.tsx
web-frontend/src/main/v3/packages/ui/src/components/Layout/LayoutWithContentSidebar.tsx
web-frontend/src/main/v3/packages/ui/src/components/URL/sidebar/UrlSidebar.tsx

Add application link button for sidebar of below pages
- Error Analysis
- Inspector
- Url Statistic

[#noissue] feat: application link button for sidebar of Error, Inspector, Url page

---

web-frontend/src/main/v3/packages/ui/src/lib/charts/useDataSourceChartConfig.ts
web-frontend/src/main/v3/packages/ui/src/lib/charts/useDataSourceChartTooltip.ts

- serviceTypeCode -> serviceType
- Handle duplicated databaseName

[#noissue] Change data-source chart data key

---

agent-module/agent/src/main/resources/profiles/local/pinpoint.config
agent-module/agent/src/main/resources/profiles/release/pinpoint.config
agent-module/plugins/akka-http/src/test/resources/pinpoint.config
agent-module/plugins/google-httpclient/src/test/resources/pinpoint.config
agent-module/plugins/httpclient3/src/test/resources/pinpoint.config
agent-module/plugins/jsp/src/test/resources/pinpoint.config
agent-module/plugins/redis/src/test/resources/pinpoint.config
agent-module/plugins/tomcat/src/test/resources/pinpoint.config
agent-module/plugins/user/src/test/resources/pinpoint.config
agent-module/plugins/weblogic/src/test/resources/pinpoint.config

(#11055) refactor: remove space

---

commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/async/ConcurrencyLimiterHelper.java
commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/async/RateLimiterPutWriter.java
commons-hbase/src/test/java/com/navercorp/pinpoint/common/hbase/async/ConcurrencyLimiterHelperTest.java
commons-hbase/src/test/java/com/navercorp/pinpoint/common/hbase/async/RateLimiterPutWriterTest.java

[#10976] Replace AtomicInteger in ConcurrencyLimiterHelper with Semaphore

---

web-angular/src/main/angular/src/app/core/components/configuration-help/configuration-help-container.component.html
web-frontend/src/main/v3/packages/ui/src/components/Config/help/HelpDocument.tsx

This Document Page Link `Pinpoint 개발자가 작성한 Pinpoint 기술문서` Link was changed
`http://helloworld.naver.com/helloworld/1194202` → `https://d2.naver.com/helloworld/1194202` 
so Change Commit PR, 
And I read guidelines and build, test tried, but failed... so cant test and build... maybe merge this pr, need test. :)

[#noissue] document page wrong url edit

---

web-frontend/src/main/v3/apps/web/src/routes/index.tsx
web-frontend/src/main/v3/apps/web/src/routes/loader/handleV2.ts
web-frontend/src/main/v3/packages/utils/src/date.ts

- Convert it to v3 url format and redirect

[#noissue] Handle v2 url format

---

web/src/main/java/com/navercorp/pinpoint/web/websocket/ActiveThreadCountHandler.java

Also add '/api' to ActiveThreadCountHandler
#11123

[#11123] Add '/api' explicitly

---

agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/interceptor/InterceptorLazyLoadingSupplier.java

[#11153] Fix interceptor holder lazyloading

---

web-frontend/src/main/v3/packages/ui/src/components/Inspector/charts/ChartCore.tsx

- Handle data-key change as well

[#noissue] Update tooltip contents on data update

---

redis/src/main/java/com/navercorp/pinpoint/redis/RedisBasicConfig.java

[#11168] Update qualifier of redis connection factory

---

web/src/main/java/com/navercorp/pinpoint/web/controller/ApplicationController.java

add limts for checking active agents

[#noissue] add max duration days

---

web-frontend/src/main/v3/packages/ui/src/components/Transaction/timeline/TimelineDetail.tsx
web-frontend/src/main/v3/packages/ui/src/components/Transaction/transaction-info/TransactionInfoFetcher.tsx

- change the name of Timeline to "Flame Graph"
- fix wrong data of Flame Graph

[#noissue] fix: flame graph

---

agent-module/plugins/spring-webflux/src/main/java/com/navercorp/pinpoint/plugin/spring/webflux/SpringWebFluxPlugin.java

[#11210] Update DispatcherHandler.handleResult() of spring webflux 6

---

agent-module/plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/jakarta/interceptor/StandardHostValveInvokeInterceptor.java
agent-module/plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/javax/interceptor/StandardHostValveInvokeInterceptor.java
agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/recorder/DefaultSpanRecorder.java
agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/recorder/DisableSpanRecorder.java
agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/recorder/TraceRootSpanRecorder.java
agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/recorder/uri/UriTemplateFilter.java
agent-module/profiler/src/test/java/com/navercorp/pinpoint/profiler/context/recorder/uri/UriTemplateFilterTest.java

[#11217] Update NULL pattern of uri template

---

pom.xml

[#11219] Bump netty.io from 4.1.100.Final to 4.1.111.Final

---

web-frontend/src/main/v3/packages/ui/src/components/Layout/LayoutWithSideNavigation.tsx
web-frontend/src/main/v3/packages/ui/tailwind.config.js

[#noissue] fix: tailwind config

---

web-frontend/src/main/v3/packages/hooks/src/api/useGetHeatmapDrag.ts

- fix wrong api param of transactionList drag api

[#noissue] fix: transaction lint api param

---

commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/time/BackwardRangeSplitter.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/time/RangeSplitter.java
commons-server/src/test/java/com/navercorp/pinpoint/common/server/util/time/RangeSplitterTest.java
web/src/main/java/com/navercorp/pinpoint/web/controller/ApplicationController.java
web/src/main/java/com/navercorp/pinpoint/web/controller/MainController.java
web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoService.java
web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoServiceImpl.java
web/src/main/java/com/navercorp/pinpoint/web/util/TagApplicationsUtils.java
web/src/main/java/com/navercorp/pinpoint/web/vo/agent/AgentInfoFilters.java

Temporarily create the /getApplicationHostinfoV2 API, which will replace the /getApplicationHostinfo API.

[#11328] improve getApplicationHostinfo api

---

agent-module/plugins/spring-cloud-sleuth/src/main/java/com/navercorp/pinpoint/plugin/spring/cloud/sleuth/SpringCloudSleuthPlugin.java
agent-module/plugins/spring-cloud-sleuth/src/main/java/com/navercorp/pinpoint/plugin/spring/cloud/sleuth/interceptor/ParallelFluxSubscribeInterceptor.java

[#11390] Update reactor lift of spring-cloud-sleuth plugin

---

web-frontend/src/main/v3/packages/ui/src/components/Application/ApplicationCombinedList.tsx

-  Add favorite button into the input of application list

[#noissue] feat: add favorite btn into app list input

---

web-frontend/src/main/v3/packages/ui/src/components/DataTable/DataTableCountOfRows.tsx
web-frontend/src/main/v3/packages/ui/src/components/ErrorAnalysis/table/ErrorAnalysisGroupedTableFetcher.tsx
web-frontend/src/main/v3/packages/ui/src/components/ErrorAnalysis/table/ErrorAnalysisTableFetcher.tsx
web-frontend/src/main/v3/packages/ui/src/components/Inspector/agent-info/InspectorAgentInfoFetcher.tsx
web-frontend/src/main/v3/packages/ui/src/components/Inspector/status-timeline/agent/InspectorAgentStatusTimelineFetcher.tsx
web-frontend/src/main/v3/packages/ui/src/components/Inspector/status-timeline/application/InspectorApplicationStatusTimelineFetcher.tsx
web-frontend/src/main/v3/packages/ui/src/components/URL/charts/UrlStatChart.tsx
web-frontend/src/main/v3/packages/ui/src/components/URL/summary/UrlSummaryFetcher.tsx
web-frontend/src/main/v3/packages/ui/src/pages/ErrorAnalysis.tsx

[#noissue] fix: background color

---

web-frontend/src/main/v3/packages/utils/src/helper/charts.ts

- Handle bytes and byte equally

[#noissue] Fix chart format handler

---

web-frontend/src/main/v3/packages/ui/src/components/ApdexScore/ApdexScoreFetcher.tsx
web-frontend/src/main/v3/packages/ui/src/components/DatetimePicker/DatetimePicker.tsx
web-frontend/src/main/v3/packages/ui/src/components/ServerMap/ServerMapCore.tsx
web-frontend/src/main/v3/packages/ui/src/components/ServerMapQueryOptions/ServerMapQueryOption.tsx
web-frontend/src/main/v3/packages/ui/src/components/ServerMapSearchList/ServerMapSearchList.tsx

[#noissue] Servermap > button cannot appear as a descedant of button

---

agent-module/plugins/mongodb/src/main/java/com/navercorp/pinpoint/plugin/mongo/MongoPlugin.java

[#11553] Update mongodb-plugin backward compatibility for 5.2.x

---

agent-module/agent-testweb/httpclient5-plugin-testweb/src/main/java/com/pinpoint/test/plugin/HttpClient5PluginController.java
agent-module/agent/src/main/resources/profiles/local/pinpoint.config
agent-module/agent/src/main/resources/profiles/release/pinpoint.config
agent-module/plugins/httpclient5/src/main/java/com/navercorp/pinpoint/plugin/httpclient5/HttpClient5Plugin.java
agent-module/plugins/httpclient5/src/main/java/com/navercorp/pinpoint/plugin/httpclient5/HttpClient5PluginConfig.java
agent-module/plugins/httpclient5/src/main/java/com/navercorp/pinpoint/plugin/httpclient5/interceptor/AsyncClientConnectionManagerConnectInterceptor.java
agent-module/plugins/httpclient5/src/main/java/com/navercorp/pinpoint/plugin/httpclient5/interceptor/AsyncExecCallbackHandleResponseInterceptor.java
agent-module/plugins/httpclient5/src/main/java/com/navercorp/pinpoint/plugin/httpclient5/interceptor/BasicClientExchangeHandlerConsumeResponseInterceptor.java
agent-module/plugins/httpclient5/src/main/java/com/navercorp/pinpoint/plugin/httpclient5/interceptor/ClientConnectionManagerConnectInterceptor.java
agent-module/plugins/httpclient5/src/main/java/com/navercorp/pinpoint/plugin/httpclient5/interceptor/CloseableHttpAsyncClientDoExecuteInterceptor.java
agent-module/plugins/httpclient5/src/main/java/com/navercorp/pinpoint/plugin/httpclient5/interceptor/CloseableHttpAsyncClientExecuteImmediateMethodInterceptor.java
agent-module/plugins/httpclient5/src/main/java/com/navercorp/pinpoint/plugin/httpclient5/interceptor/DefaultAsyncClientConnectionOperatorConnectInterceptor.java
agent-module/plugins/httpclient5/src/main/java/com/navercorp/pinpoint/plugin/httpclient5/interceptor/DefaultHttpClientConnectionOperatorConnectInterceptor.java
agent-module/plugins/httpclient5/src/main/java/com/navercorp/pinpoint/plugin/httpclient5/interceptor/FutureCancelInterceptor.java
agent-module/plugins/httpclient5/src/main/java/com/navercorp/pinpoint/plugin/httpclient5/interceptor/FutureCompletedInterceptor.java
agent-module/plugins/httpclient5/src/main/java/com/navercorp/pinpoint/plugin/httpclient5/interceptor/FutureFailedInterceptor.java
agent-module/plugins/httpclient5/src/main/java/com/navercorp/pinpoint/plugin/httpclient5/interceptor/InternalHttpClientDoExecuteInterceptor.java
agent-module/plugins/httpclient5/src/main/java/com/navercorp/pinpoint/plugin/httpclient5/interceptor/MinimalHttpAsyncClientExecuteInterceptor.java

[#11579] Update httpclient5 plugin option - mark.error

---

agent-module/agent-testweb/arcus-plugin-testweb/pom.xml
agent-module/agent-testweb/arcus-plugin-testweb/src/main/java/com/pinpoint/test/plugin/ArcusClientConfiguration.java
agent-module/agent-testweb/arcus-plugin-testweb/src/main/java/com/pinpoint/test/plugin/ArcusPluginController.java
agent-module/agent-testweb/arcus-plugin-testweb/src/main/java/com/pinpoint/test/plugin/ArcusPluginTestStarter.java
agent-module/agent-testweb/arcus-plugin-testweb/src/main/resources/application.yml
agent-module/agent-testweb/pom.xml
agent-module/plugins/arcus/src/main/java/com/navercorp/pinpoint/plugin/arcus/ArcusPlugin.java
agent-module/plugins/arcus/src/main/java/com/navercorp/pinpoint/plugin/arcus/ServiceCodeGetter.java
agent-module/plugins/arcus/src/main/java/com/navercorp/pinpoint/plugin/arcus/interceptor/FrontCacheGetFutureConstructInterceptor.java
agent-module/plugins/arcus/src/main/java/com/navercorp/pinpoint/plugin/arcus/interceptor/LocalCacheManagerConstructorInterceptor.java
agent-module/plugins/arcus/src/main/java/com/navercorp/pinpoint/plugin/arcus/interceptor/SetCacheManagerInterceptor.java

[#11592] Update arcus-plugin to support arcus java client 1.13.4

---

agent-module/agent-testweb/mysql-jdbc-plugin-testweb/README.md
agent-module/agent-testweb/mysql-jdbc-plugin-testweb/pom.xml
agent-module/agent-testweb/mysql-jdbc-plugin-testweb/src/main/java/com/pinpoint/test/plugin/MysqlDBPluginController.java
agent-module/agent-testweb/mysql-jdbc-plugin-testweb/src/main/java/com/pinpoint/test/plugin/MysqlDBPluginTestStarter.java
agent-module/agent-testweb/mysql-jdbc-plugin-testweb/src/main/java/com/pinpoint/test/plugin/MysqlDBServer.java
agent-module/agent-testweb/mysql-jdbc-plugin-testweb/src/main/resources/application.yml
agent-module/agent-testweb/mysql-jdbc-plugin-testweb/src/main/resources/init.sql
agent-module/agent-testweb/mysql-jdbc-plugin-testweb/src/test/java/com/pinpoint/test/plugin/mongo/MysqlDBTest.java
agent-module/agent-testweb/pom.xml
agent-module/plugins-it/mysql-jdbc-driver-plugin-it/pom.xml
agent-module/plugins-it/mysql-jdbc-driver-plugin-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/mysql/MySql_9_X_IT.java
agent-module/plugins/mysql-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/mysql/MySqlPlugin.java

[#11611] Update mysql-jdbc-plugin support to mysql-connector-j 9.x

---

agent-module/agent-testweb/httpclient5-plugin-testweb/pom.xml
agent-module/agent-testweb/pom.xml
agent-module/agent-testweb/spring-restclient-plugin-testweb/pom.xml
agent-module/agent-testweb/spring-restclient-plugin-testweb/src/main/java/com/pinpoint/test/plugin/SpringRestClientPluginController.java
agent-module/agent-testweb/spring-restclient-plugin-testweb/src/main/java/com/pinpoint/test/plugin/SpringRestClientPluginTestStarter.java
agent-module/agent-testweb/spring-restclient-plugin-testweb/src/main/resources/application.yml
agent-module/plugins-it/httpclient-it/httpclient-5-it/pom.xml
agent-module/plugins-it/httpclient-it/httpclient-5-it/src/test/java/com/navercorp/pinpoint/it/plugin/httpclient5/CloaeableHttpClientIT.java
agent-module/plugins-it/httpclient-it/httpclient-5-it/src/test/java/com/navercorp/pinpoint/it/plugin/httpclient5/CloaeableHttpClient_5_2_IT.java
agent-module/plugins-it/httpclient-it/httpclient-5-it/src/test/java/com/navercorp/pinpoint/it/plugin/httpclient5/CloaeableHttpClient_5_4_IT.java
agent-module/plugins-it/httpclient-it/httpclient-5-it/src/test/java/com/navercorp/pinpoint/it/plugin/httpclient5/ClosableAsyncHttpClientIT.java
agent-module/plugins-it/httpclient-it/httpclient-5-it/src/test/java/com/navercorp/pinpoint/it/plugin/httpclient5/HttpClientITBase.java
agent-module/plugins-it/httpclient-it/pom.xml
agent-module/plugins/httpclient5/src/main/java/com/navercorp/pinpoint/plugin/httpclient5/HttpClient5Plugin.java
agent-module/plugins/httpclient5/src/main/java/com/navercorp/pinpoint/plugin/httpclient5/interceptor/CloseableHttpAsyncClientExecuteImmediateMethodInterceptor.java

[#11647] Update httpclient5-plugin support to httpclient5 5.4

---

web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/MapController.java
web/src/main/java/com/navercorp/pinpoint/web/authorization/controller/AgentListController.java
web/src/main/java/com/navercorp/pinpoint/web/realtime/AgentLookupServiceImpl.java
web/src/main/java/com/navercorp/pinpoint/web/realtime/RealtimeConfig.java
web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoService.java
web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoServiceImpl.java
web/src/main/java/com/navercorp/pinpoint/web/service/ApplicationAgentInfoMapServiceImpl.java
web/src/main/java/com/navercorp/pinpoint/web/service/ApplicationAgentListQueryRule.java
web/src/main/java/com/navercorp/pinpoint/web/service/ApplicationAgentListService.java
web/src/main/java/com/navercorp/pinpoint/web/service/ApplicationAgentListServiceImpl.java
web/src/test/java/com/navercorp/pinpoint/web/service/ApplicationAgentListServiceImplTest.java

- servermap server list
- realtime agent list

[#11433] Change servermap agent list condition

---

pom.xml

https://github.com/oshi/oshi/blob/oshi-parent-6.6.5/pom.xml#L96

[#noissue] Bump jna from 5.14.0 to 5.15.0

---

agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/metadata/SimpleCacheFactory.java
agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/metadata/SimpleCacheFactoryProvider.java
agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/metadata/SqlMetadataServiceProvider.java

[#11503] Delegate cache creation to SimpleCacheFactory

---

web-frontend/src/main/v3/packages/ui/src/components/OpenTelemetry/dashboard/OpenTelemteryDashboardFetcher.tsx
web-frontend/src/main/v3/packages/ui/src/pages/OpenTelemetry.tsx

[#7722] OpenTelemetryMetric > Change title & icon

---

web-frontend/src/main/v3/packages/ui/src/components/OpenTelemetry/dashboard/OpenTelemteryDashboardFetcher.tsx

https://github.com/pinpoint-apm/pinpoint/pull/11791/files

[#noissue] Revert #11791

---

agent-module/plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/ReactorPlugin.java

[#11805] Fix reactor-plugin empty mono and flux

---

agent-module/plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/ReactorPlugin.java

[#11807] Backport: Fix reactor-plugin empty mono and flux

---

web-frontend/src/main/v3/apps/web/tsconfig.json
web-frontend/src/main/v3/packages/ui/src/components/FlameGraph/FlameGraph.tsx
web-frontend/src/main/v3/packages/ui/src/components/FlameGraph/FlameNode.tsx

- Text rendering error when graph width is very small
- Problem with left scroll not initializing
- Add zoom in/out button with tooltip

[#noissue] FlameGraph > fix bug & add zoom in/out button'

---

agent-module/plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/KafkaPlugin.java

[#11924] Update kafka plugin for compatibility with kafka 3.x version

---

agent-module/agent-testweb/spring-data-r2dbc-plugin-testweb/pom.xml
agent-module/agent-testweb/spring-data-r2dbc-plugin-testweb/src/main/java/com/pinpoint/test/plugin/MysqlR2dbcDatabase.java
agent-module/agent-testweb/spring-data-r2dbc-plugin-testweb/src/main/java/com/pinpoint/test/plugin/SpringDataR2dbcPluginController.java
agent-module/plugins/spring-data-r2dbc/src/main/java/com/navercorp/pinpoint/plugin/spring/r2dbc/SpringDataR2dbcPlugin.java

[#11953] Update io.asyncer:r2dbc-mysql of spring r2dbc plugin

---

agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/context/Trace.java
agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/AsyncContextSpanEventNestedApiIdAwareAroundInterceptor.java
agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/reactor/CoreSubscriberOnNextInterceptor.java
agent-module/plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/ReactorPlugin.java
agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/ChildTrace.java
agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTrace.java
agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DisableChildTrace.java
agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DisableTrace.java
agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/scope/BoundaryTraceScope.java
agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/scope/DefaultTraceScopePool.java

[#11980] Add async nested of reactor plugin

---

batch/pom.xml

Resolves pinpoint-apm/pinpoint-docker#231.
Related issue: #11337.

[#noissue] Add missing dependency

---

web-frontend/src/main/v3/packages/ui/src/components/Transaction/timeline/TimelineFetcher.tsx
web-frontend/src/main/v3/packages/ui/src/components/Transaction/timeline/TimelineInfo.tsx

[#noissue] FlameGraph > Application name info

---

web-frontend/src/main/v3/packages/ui/src/components/CollapsibleCodeViewer/CollapsibleCodeViewer.tsx
web-frontend/src/main/v3/packages/ui/src/components/Transaction/call-tree/CallTree.tsx

[#noissue] Console for debugging

---

web-frontend/src/main/v3/packages/ui/src/components/Dashboard/Widget.tsx
web-frontend/src/main/v3/packages/ui/src/components/OpenTelemetry/charts/OpenTelemetryMetricFetcher.tsx
web-frontend/src/main/v3/packages/ui/src/components/OpenTelemetry/dashboard/OpenTelemteryDashboardFetcher.tsx
web-frontend/src/main/v3/packages/ui/src/constants/types/OtlpMetricData.ts

[#12019] Show message with popover when metricData has message

---

agent-module/profiler-test/src/main/java/com/navercorp/pinpoint/profiler/test/CallSteps.java
agent-module/profiler-test/src/main/java/com/navercorp/pinpoint/profiler/test/PluginVerifierExternalAdaptor.java

[#12046] Update plugin it verifier

---

web-frontend/src/main/v3/packages/ui/src/components/ScatterChart/ScatterChartFetcher.tsx
web-frontend/src/main/v3/packages/ui/src/components/ScatterChart/ScatterChartRealtimeFetcher.tsx
web-frontend/src/main/v3/packages/ui/src/hooks/api/useGetScatterData.ts
web-frontend/src/main/v3/packages/ui/src/hooks/api/useGetScatterRealtimeData.ts
web-frontend/src/main/v3/packages/ui/src/hooks/searchParameters/useServerMapSearchParameters.ts

Fix missing data bug in realtime.

[#noissue] Fix realtime scatter chart bug (missing data)

---

web-frontend/src/main/v3/packages/ui/src/components/AgentActiveThread/AgentActiveThreadFetcher.tsx
web-frontend/src/main/v3/packages/ui/src/components/Realtime/Realtime.tsx

[#noissue] Realtime > Remove "Active Request" header

---

web-frontend/src/main/v3/README.md

update fix text
Pcakages -> Packages

[#noissue] Fix text in README.md

---

agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/context/Trace.java
agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/AsyncContextSpanEventNestedApiIdAwareAroundInterceptor.java
agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/reactor/CoreSubscriberOnNextInterceptor.java
agent-module/plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/ReactorPlugin.java
agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/ChildTrace.java
agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTrace.java
agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DisableChildTrace.java
agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DisableTrace.java
agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/scope/BoundaryTraceScope.java
agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/scope/DefaultTraceScopePool.java

[#12075] Backport: Add async nested of reactor plugin

---

agent-module/plugins-it/clickhouse-jdbc-it/pom.xml
agent-module/plugins-it/clickhouse-jdbc-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/clickhouse/ClickHouse_0_8_0_ITHelper.java
agent-module/plugins-it/clickhouse-jdbc-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/clickhouse/ClickHouse_0_8_x_IT.java
agent-module/plugins-it/clickhouse-jdbc-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/clickhouse/ClickHouse_0_8_x_ITBase.java
agent-module/plugins-it/clickhouse-jdbc-it/src/test/java/com/navercorp/pinpoint/it/plugin/jdbc/clickhouse/ClickHouse_0_8_x_JDBCDriverClass.java
agent-module/plugins/clickhouse-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/clickhouse/ClickHousePlugin.java

[#12100] Update clickhouse plugins for compatibility with 0.8.0

---

agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/DefaultJdbcOption.java
agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/JdbcOption.java
agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/metadata/SqlMetadataServiceProvider.java
agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/metadata/DefaultCachingSqlNormalizer.java
agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/metadata/SqlCacheService.java
agent-module/profiler/src/test/java/com/navercorp/pinpoint/profiler/metadata/DefaultCachingSqlNormalizerTest.java
agent-module/profiler/src/test/java/com/navercorp/pinpoint/profiler/metadata/SqlCacheServiceTest.java
agent-module/profiler/src/test/java/com/navercorp/pinpoint/profiler/metadata/SqlUidMetaDataServiceTest.java
commons-profiler/src/main/java/com/navercorp/pinpoint/common/profiler/sql/DefaultSqlNormalizer.java
commons-profiler/src/test/java/com/navercorp/pinpoint/common/profiler/sql/DefaultSqlNormalizerTest.java

Resolves #12061.
property: `profiler.jdbc.removecomments`

[#12061] Remove comments from SQL queries

---

web-frontend/src/main/v3/packages/ui/src/components/Agent/AgentSearchList.tsx

[#noissue] AgentSearchList style

---

inspector-module/inspector-collector/src/main/pinot/pinot-inspector-stat-application-realtime-table.json

- #12048
- https://docs.pinot.apache.org/release-1.2.0/for-developers/advanced/ingestion-level-aggregations#requirements

[#12048] Fix datetime/time columns config for Ingestion Aggregations

---

agent-module/plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/interceptor/FluxAndMonoSubscribeMethodInterceptor.java

[#12149] Update avoid tracking unnecessary subscribe method of reactor

---

feature-flag/src/main/java/com/navercorp/pinpoint/featureflag/config/FeatureFlagProperties.java
feature-flag/src/main/java/com/navercorp/pinpoint/featureflag/service/FeatureFlagServiceFactory.java
feature-flag/src/test/java/com/navercorp/pinpoint/featureflag/service/FeatureFlagServiceFactoryTest.java

[#12092] Change type of FeatureFlagProperties from Map to List

---

pom.xml

[#12193] Bump ASM from 9.6 to 9.7.1

---

agent-module/agent/src/main/resources/log4j2-agent.yaml

[#11906] Fix log4j2 configuration YAML

---

agent-module/agent/src/main/resources/log4j2-agent.xml
agent-module/agent/src/main/resources/log4j2-agent.yaml

[#12210] Add size, lastmodified, rollover-strategy-max to logging opt

---

web/src/main/java/com/navercorp/pinpoint/web/authorization/controller/HeatmapChartController.java

…Provider parameter. It is because TenantProvider is not being used

[#12159] Refactor HeatmapChartController constructor to remove TenantProvider parameter.

---

agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/grpc/GrpcSpanMessageConverterProvider.java

[#noissue] Remove unused SpanUriGetter from GrpcSpanMessageConverterProvider

---

agent-module/agent-testweb/spring-kafka-plugin-testweb/pom.xml
agent-module/agent-testweb/spring-kafka-plugin-testweb/src/main/java/com/pinpoint/test/plugin/KafkaStreamsConfig.java
agent-module/agent-testweb/spring-kafka-plugin-testweb/src/main/java/com/pinpoint/test/plugin/SpringKafkaApplication.java
agent-module/agent-testweb/spring-kafka-plugin-testweb/src/main/java/com/pinpoint/test/plugin/SpringKafkaPluginController.java
agent-module/agent-testweb/spring-kafka-plugin-testweb/src/main/java/com/pinpoint/test/plugin/SpringKafkaPluginTestConstants.java
agent-module/agent-testweb/spring-kafka-plugin-testweb/src/main/java/com/pinpoint/test/plugin/SpringKafkaStreamConsumer.java
agent-module/agent/src/main/resources/profiles/local/pinpoint.config
agent-module/agent/src/main/resources/profiles/release/pinpoint.config
agent-module/plugins/kafka/README.md
agent-module/plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/KafkaConfig.java
agent-module/plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/KafkaPlugin.java
agent-module/plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/field/getter/StampedRecordGetter.java
agent-module/plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/interceptor/RecordDeserializerInterceptor.java
agent-module/plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/interceptor/StreamTaskDoProcessInterceptor.java
agent-module/plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/util/KafkaRequestAdaptor.java

[#12265] Update the entry point for kafka stream

---

otlpmetric/otlpmetric-web/src/main/java/com/navercorp/pinpoint/otlp/web/dao/pinot/PinotMetricMetaDataDao.java

This pull request includes changes to the `PinotMetricMetaDataDao` class in the `otlpmetric-web` module to improve the handling and sorting of metric groups. The most important changes include replacing `TreeMap` with `HashMap` for storing metric groups and introducing a custom comparator for sorting the metric groups by name.
Improvements to metric group handling:
* [`PinotMetricMetaDataDao.java`](diffhunk://#diff-f9ac2640a2c281fdbac17ece111f9bb20f720cc4a5860933edf68eda6de63a06L49-R63): Replaced `TreeMap` with `HashMap` for storing metric groups to improve performance.
* [`PinotMetricMetaDataDao.java`](diffhunk://#diff-f9ac2640a2c281fdbac17ece111f9bb20f720cc4a5860933edf68eda6de63a06R27-R44): Introduced a custom `Comparator` for sorting `MetricGroup` instances by their names in the …

[#noissue] Cleanup PinotMetricMetaDataDao

---

.github/workflows/validate-commit.yml

Adds a workflow to examine the commit message format.
Regex: ^\[#(noissue|[0-9]+?)\].*
~~~
[#issue-number] messge
Examples:
[#1001] Refactor servermap
[#noissue] Update README.md
~~~

[#noissue] Add validate commit messgae workflow

---

agent-module/agent-testweb/ning-asynchttpclient-plugin-testweb/pom.xml
agent-module/agent-testweb/ning-asynchttpclient-plugin-testweb/src/main/java/com/pinpoint/test/plugin/NingAsyncHttpClientPluginController.java
agent-module/plugins/ning-asynchttpclient/src/main/java/com/navercorp/pinpoint/plugin/ning/asynchttpclient/NingAsyncHttpClientPlugin.java
agent-module/plugins/ning-asynchttpclient/src/main/java/com/navercorp/pinpoint/plugin/ning/asynchttpclient/NingAsyncHttpClientPluginConfig.java
agent-module/plugins/ning-asynchttpclient/src/main/java/com/navercorp/pinpoint/plugin/ning/asynchttpclient/interceptor/AsyncHandlerOnCompletedInterceptor.java
agent-module/plugins/ning-asynchttpclient/src/main/java/com/navercorp/pinpoint/plugin/ning/asynchttpclient/interceptor/AsyncHandlerOnStatusReceivedInterceptor.java
agent-module/plugins/ning-asynchttpclient/src/main/java/com/navercorp/pinpoint/plugin/ning/asynchttpclient/interceptor/AsyncHandlerOnThrowableInterceptor.java
agent-module/plugins/ning-asynchttpclient/src/main/java/com/navercorp/pinpoint/plugin/ning/asynchttpclient/interceptor/ExecuteInterceptor.java

[#12285] Update 3.x to async-http-client plugin

---

web/src/main/java/com/navercorp/pinpoint/web/applicationmap/ApplicationMapView.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/MapView.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/MapController.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/histogram/TimeHistogramFormat.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/NodeHistogramSummaryView.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/TimeHistogramBuilder.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/TimeseriesHistogramViewModel.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/TimeseriesHistogramViewModelBuilder.java

This pull request includes several changes to enhance the `ApplicationMapView` and `MapController` classes, as well as updates to the histogram format and related classes. The most important changes include adding support for `TimeWindow` in `ApplicationMapView` and `MapView`, updating the `MapController` endpoints to handle new parameters, and introducing a new histogram format.
Enhancements to `ApplicationMapView` and `MapView`:
* Added `TimeWindow` support to `ApplicationMapView` and `MapView` classes, including new constructors and methods to handle `TimeWindow` and return timestamp data. (`web/src/main/java/com/navercorp/pinpoint/web/applicationmap/ApplicationMapView.java`: [[1]](diffhunk://#diff-a516961c89737f44c166457ec9589e8548d46a26847ee266dee720196a40427cR7) …

 [#12315] Optimize servermap json

---

commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/DefaultDataPoint.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/FileDescriptorBo.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/LoadedClassBo.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/ResponseTimeBo.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/TotalThreadCountBo.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/TransactionBo.java
inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/model/kafka/AgentStat.java
inspector-module/inspector-collector/src/main/java/com/navercorp/pinpoint/inspector/collector/service/PinotAgentStatService.java

This pull request introduces several changes to improve the consistency and functionality of the `toString` methods across various classes and refactors the `PinotAgentStatService` class for better readability and maintainability. The most important changes include adding `toString` methods to several classes and refactoring the `PinotAgentStatService` class to use a timeout constant and improve the `validateTime` method.
Enhancements to `toString` methods:
* [`commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/DefaultDataPoint.java`](diffhunk://#diff-ce9cd197ec2c9e2daf5ccda2e8d72d5eb3cd0b1ce5f1c786bcda1a06405a5cd5R58-R65): Added a `toString` method to provide a string representation of the `DefaultDataPoint` object.
* …

[#noissue] Cleanup AgentStat

---

agent-module/plugins-loader/src/main/java/com/navercorp/pinpoint/loader/service/DefaultServiceTypeRegistryService.java
agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/plugin/ServiceTypeRegistryServiceProvider.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/config/TypeLoaderConfiguration.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/config/ApplicationMapModule.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/ApplicationForm.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/FilteredMapController.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/MapController.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/MapHistogramController.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/RangeForm.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/SearchDepthForm.java
web/src/main/java/com/navercorp/pinpoint/web/component/config/ComponentConfiguration.java
web/src/main/java/com/navercorp/pinpoint/web/util/ApplicationValidator.java
web/src/test/java/com/navercorp/pinpoint/web/applicationmap/controller/MapControllerTest.java
web/src/test/java/com/navercorp/pinpoint/web/util/ApplicationValidatorTest.java

This pull request focuses on refactoring the `ServiceTypeRegistryService` and updating the `FilteredMapController` to improve the codebase and functionality. The most important changes include modifying constructors and dependency injection, removing unnecessary service type registry references, and adding new classes for form validation.
* Modified the constructor of `DefaultServiceTypeRegistryService` to accept `ServiceTypeLocator` directly instead of `TraceMetadataLoaderService`. (`[agent-module/plugins-loader/src/main/java/com/navercorp/pinpoint/loader/service/DefaultServiceTypeRegistryService.javaL33-R34](diffhunk://#diff-b4835714a2131202955d769f3ab862bd0dc641d990c87d219de36b00b42990f6L33-R34)`)
* Updated `ServiceTypeRegistryServiceProvider` to use `ServiceTypeLocator` from …

[#noissue] Remove duplicate paths in MapModule

---

web-frontend/src/main/v3/packages/ui/src/components/Heatmap/HeatmapFetcher.tsx
web-frontend/src/main/v3/packages/ui/src/components/Heatmap/core/HeatmapChart.tsx
web-frontend/src/main/v3/packages/ui/src/components/Heatmap/core/HeatmapChartCore.tsx
web-frontend/src/main/v3/packages/ui/src/pages/ServerMap.tsx

[#12328] Heatmap > Change drag rect style

---

web-frontend/src/main/v3/packages/ui/src/hooks/utility/useLocalStorage.ts
web-frontend/src/main/v3/packages/ui/src/pages/ServerMap.tsx
web-frontend/src/main/v3/packages/ui/src/utils/localStorage.ts

https://github.com/pinpoint-apm/pinpoint/pull/12349/files#r2045854846

[#noissue] Change localStorage value check condition

---

web-frontend/src/main/v3/packages/ui/src/hooks/utility/useLocalStorage.ts

Reverts https://github.com/pinpoint-apm/pinpoint/pull/12352

[#noissue] Revert #12352

---

web/src/main/java/com/navercorp/pinpoint/web/applicationmap/ApplicationMapBuilder.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/DefaultApplicationMap.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/link/LinkList.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/link/LinkListFactory.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/nodes/NodeList.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/nodes/NodeListFactory.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/nodes/ServerGroup.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/nodes/ServerGroupList.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/service/ResponseTimeHistogramServiceImpl.java
web/src/test/java/com/navercorp/pinpoint/web/applicationmap/ApplicationMapTest.java
web/src/test/java/com/navercorp/pinpoint/web/applicationmap/LinkListTest.java
web/src/test/java/com/navercorp/pinpoint/web/applicationmap/ServerGroupListTest.java
web/src/test/java/com/navercorp/pinpoint/web/applicationmap/appender/histogram/NodeHistogramAppenderTest.java
web/src/test/java/com/navercorp/pinpoint/web/applicationmap/appender/server/ServerInfoAppenderTest.java
web/src/test/java/com/navercorp/pinpoint/web/applicationmap/nodes/NodeListTest.java

This pull request introduces significant refactoring and improvements to the application map components, focusing on simplifying object creation, improving immutability, and enhancing code readability. The changes primarily involve replacing mutable lists with builder patterns, introducing static factory methods for creating immutable instances, and optimizing existing logic.
* Introduced static factory methods `NodeList.of()` and `LinkList.of()` for creating empty or single-element immutable instances, replacing direct instantiation. (`[[1]](diffhunk://#diff-21c6bb75b76a8f9f362474794f2317cca385a5c1c725e9832c825fa90d19a383L21-R104)`, `[[2]](diffhunk://#diff-b387f379f984c73124ee45a27366545396a8c80782a29a0e7b7ee6d0688d98b1L35-R53)`)
* Replaced mutable `addNode` and `addLink` methods with …

[#noissue] Refactor LinkList and NodeList

---

web/src/main/java/com/navercorp/pinpoint/web/calltree/span/CallTree.java
web/src/main/java/com/navercorp/pinpoint/web/calltree/span/CallTreeNodeNonProductiveFilter.java
web/src/main/java/com/navercorp/pinpoint/web/calltree/span/LinkedCallTree.java
web/src/main/java/com/navercorp/pinpoint/web/calltree/span/SpanAligner.java
web/src/main/java/com/navercorp/pinpoint/web/calltree/span/SpanCallTree.java
web/src/test/java/com/navercorp/pinpoint/web/calltree/span/CallTreeTest.java

[#12368] Clear unnecessary branches in CallTree

---

web/src/main/java/com/navercorp/pinpoint/web/applicationmap/ApplicationMapView.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/FilterMapViewV3.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/MapViewV3.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/SimpleApplicationMap.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/FilteredMapController.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/FilteredHistogramView.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/ScatterDataMapView.java

This pull request introduces significant refactoring and enhancements to various classes in the `web/applicationmap` package, focusing on simplifying data structures, improving maintainability, and optimizing serialization. Key changes include refactoring `FilterMapView` and adding a new `FilterMapViewV3` class, enhancing serialization for `ScatterDataMapView`, and replacing list-based data handling with iterator-based transformations in `FilteredHistogramView`.
* **`FilterMapView` Refactoring**: Simplified the class by removing redundant fields and methods (e.g., `scatterDataMap` and `filteredHistogramView`) and replacing them with dependencies on `ApplicationMapView` and `ScatterDataMapView`. This reduces complexity and improves separation of concerns. …

[#noissue] Refactor FilteredMap

---

agent-module/plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/interceptor/ProducerAddHeaderInterceptor.java

[#12376] Backport: Update kafka plugin for compatibility with kafka 4.x

---

agent-module/agent/src/main/resources/profiles/local/pinpoint.config
agent-module/agent/src/main/resources/profiles/release/pinpoint.config
agent-module/plugins/kafka/README.md
agent-module/plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/KafkaConfig.java
agent-module/plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/KafkaPlugin.java
agent-module/plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/field/getter/StampedRecordGetter.java
agent-module/plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/interceptor/RecordDeserializerInterceptor.java
agent-module/plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/interceptor/StreamTaskDoProcessInterceptor.java
agent-module/plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/util/KafkaRequestAdaptor.java

[#12378] Backport: Update the entry point for kafka stream

---

web/src/main/java/com/navercorp/pinpoint/web/applicationmap/FilterMapViewV3.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/controller/FilteredMapController.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/FilteredHistogramView.java
web/src/main/java/com/navercorp/pinpoint/web/view/TimeSeries/TimeSeriesView.java
web/src/main/java/com/navercorp/pinpoint/web/view/histogram/HistogramView.java
web/src/main/java/com/navercorp/pinpoint/web/view/histogram/TimeHistogramChart.java
web/src/main/java/com/navercorp/pinpoint/web/view/histogram/TimeHistogramChartBuilder.java

This pull request introduces several changes to improve the handling of time series data, refactor the `FilteredHistogramView` class, and enhance flexibility in histogram-related views. The most significant updates involve adding support for optional timestamps in histogram views, modifying constructors and methods to accommodate this change, and renaming methods for better clarity.
* Added a new `includeTimestamp` flag to `HistogramView` and updated its constructors to allow optional inclusion of timestamps in histogram data. This change is reflected in methods like `getLoadChart` and `getLoadStatisticsChart`, which now skip timestamps if the flag is set to `false`. (`web/src/main/java/com/navercorp/pinpoint/web/view/histogram/HistogramView.java`, …

[#noissue] Refactor FilterMap

---

web/src/main/java/com/navercorp/pinpoint/web/applicationmap/histogram/TimeHistogramFormat.java
web/src/main/java/com/navercorp/pinpoint/web/controller/BusinessTransactionController.java
web/src/main/java/com/navercorp/pinpoint/web/view/TransactionInfoViewModel.java

This pull request introduces enhancements to the `TimeHistogramFormat` and `BusinessTransactionController` classes, alongside modifications to the `TransactionInfoViewModel` to improve flexibility and maintainability. The changes include adding support for default versions in histogram format parsing, extending the controller's functionality with a new endpoint, and refactoring the transaction view model to use a unified application map view.
* Added a new `VERSIONS` set to hold all enum values for easier lookup.
* Introduced overloaded `format` methods to support parsing from both integer and string inputs, with an optional default version fallback.
* Added a new endpoint `/api/trace/transaction` to retrieve transaction details using `TimeHistogramFormat.V3` by default.
* Refactored the …

[#noissue] Refactor TransactionController

---

web/src/main/java/com/navercorp/pinpoint/web/applicationmap/histogram/AgentTimeHistogramBuilder.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/link/Link.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/nodes/ServerBuilder.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/rawdata/AgentHistogram.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/rawdata/AgentHistogramList.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/rawdata/LinkCallDataMap.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/service/ResponseTimeHistogramServiceImpl.java
web/src/main/java/com/navercorp/pinpoint/web/applicationmap/view/LinkView.java
web/src/test/java/com/navercorp/pinpoint/web/view/LinkViewTest.java

This pull request refactors the `AgentHistogramList` class and its usage across the codebase to improve maintainability and consistency. The changes introduce a builder pattern for constructing `AgentHistogramList` objects, replace direct instantiations with the new builder, and update related methods to align with the new structure. Additionally, minor improvements to code readability and functionality are included.
* Introduced a builder pattern for `AgentHistogramList` by adding a nested `Builder` class, which simplifies the creation and population of `AgentHistogramList` objects. (`web/src/main/java/com/navercorp/pinpoint/web/applicationmap/rawdata/AgentHistogramList.java`) [[1]](diffhunk://#diff-8b18c4596f7a1b8d10a61b54566d2787aa7fabc19886ab6f1d1b9fa3cd3a72acL38-R80) …

[#noissue] Refactor AgentHistogramList

---

agent-module/plugins/elasticsearch/src/main/java/com/navercorp/pinpoint/plugin/elasticsearch/interceptor/ElasticsearchExecutorInterceptor.java
agent-module/plugins/elasticsearch/src/main/java/com/navercorp/pinpoint/plugin/elasticsearch/interceptor/HighLevelConnectInterceptor.java
agent-module/plugins/elasticsearch/src/main/java/com/navercorp/pinpoint/plugin/elasticsearch/interceptor/RestClientConnectInterceptor.java
agent-module/plugins/elasticsearch8/src/main/java/com/navercorp/pinpoint/plugin/elasticsearch8/interceptor/ElasticsearchClientConstructorInterceptor.java
agent-module/plugins/elasticsearch8/src/main/java/com/navercorp/pinpoint/plugin/elasticsearch8/interceptor/ElasticsearchClientMethodInterceptor.java

[#12410] Fix NPE of elasticsearch plugin

---

agent-module/plugins/elasticsearch/src/main/java/com/navercorp/pinpoint/plugin/elasticsearch/interceptor/ElasticsearchExecutorInterceptor.java
agent-module/plugins/elasticsearch/src/main/java/com/navercorp/pinpoint/plugin/elasticsearch/interceptor/HighLevelConnectInterceptor.java
agent-module/plugins/elasticsearch/src/main/java/com/navercorp/pinpoint/plugin/elasticsearch/interceptor/RestClientConnectInterceptor.java
agent-module/plugins/elasticsearch8/src/main/java/com/navercorp/pinpoint/plugin/elasticsearch8/interceptor/ElasticsearchClientConstructorInterceptor.java
agent-module/plugins/elasticsearch8/src/main/java/com/navercorp/pinpoint/plugin/elasticsearch8/interceptor/ElasticsearchClientMethodInterceptor.java

[#12413] Backport: Fix NPE of elasticsearch plugin

---

web-frontend/src/main/v3/packages/ui/src/components/Heatmap/core/HeatmapChart.tsx
web-frontend/src/main/v3/packages/ui/src/components/Heatmap/core/HeatmapChartCore.tsx
web-frontend/src/main/v3/packages/ui/src/components/HelpPopover/HeatmapVisualMapIcon.tsx
web-frontend/src/main/v3/packages/ui/src/components/HelpPopover/HelpPopover.tsx
web-frontend/src/main/v3/packages/ui/src/components/Realtime/Realtime.tsx
web-frontend/src/main/v3/packages/ui/src/constants/locales/en.json
web-frontend/src/main/v3/packages/ui/src/constants/locales/ko.json
web-frontend/src/main/v3/packages/ui/src/pages/ServerMap.tsx

[#12240] Heatmap > Show Apdex & HelpPopover

---

web-frontend/src/main/v3/packages/ui/src/components/ServerMap/ChartTypeButtons.tsx

[#12240] Apply tooltip to ChartTypeButton

---

web-frontend/src/main/v3/packages/ui/src/components/Heatmap/HeatmapFetcher.tsx
web-frontend/src/main/v3/packages/ui/src/components/Heatmap/core/HeatmapChart.tsx
web-frontend/src/main/v3/packages/ui/src/constants/locales/en.json
web-frontend/src/main/v3/packages/ui/src/constants/locales/ko.json
web-frontend/src/main/v3/packages/ui/src/hooks/api/useGetHeatmapAppData.ts

[#12240] Display message when heatmap API error occurs

---

pom.xml

[#12466] Upgrade spring boot from 3.3.7 to 3.3.11

---

agent-module/agent/src/main/resources/profiles/local/pinpoint.config
agent-module/agent/src/main/resources/profiles/release/pinpoint.config
agent-module/plugins/aws-sdk-s3/src/main/java/com/navercorp/pinpoint/plugin/aws/sdk/s3/AwsSdkS3PluginConfig.java

[#12457] Backport: Update s3 client error mark

---

pinot/pinot-kafka/src/main/java/com/navercorp/pinpoint/pinot/kafka/KafkaConfiguration.java
pinot/pinot-kafka/src/main/java/com/navercorp/pinpoint/pinot/kafka/KafkaProperties.java

Reverts pinpoint-apm/pinpoint#12512

Revert "[#12511] Remove partitioner class config"

---

web/src/main/java/com/navercorp/pinpoint/web/WebMvcConfig.java
web/src/main/java/com/navercorp/pinpoint/web/vo/ApplicationPairsConverter.java

This pull request introduces changes to improve dependency injection and enhance error handling in the `WebMvcConfig` and `ApplicationPairsConverter` classes. The most significant updates include injecting an `ObjectMapper` instance via Spring's dependency injection, improving the `ApplicationPairsConverter` to use an `ObjectReader` for better configurability, and refining error handling with a custom exception.
* [`web/src/main/java/com/navercorp/pinpoint/web/WebMvcConfig.java`](diffhunk://#diff-fe509e965fcddb02d1079407ac0c54e1b2c79dda699de1421f77d763fc0df07fR19-R23): Added an `ObjectMapper` field and setter method annotated with `@Autowired` to inject the mapper. This allows the `WebMvcConfig` class to use a shared `ObjectMapper` instance. …

[#noissue] Refactor ApplicationPairsConverter

---

pinot/pinot-kafka/src/main/java/com/navercorp/pinpoint/pinot/kafka/KafkaConfiguration.java
pinot/pinot-kafka/src/main/java/com/navercorp/pinpoint/pinot/kafka/KafkaProperties.java

Uses BuiltInPartitioner when the config is not set

[#12511] Add `pinpoint.metric.kafka.partitionerClass` config

---

agent-module/agent/src/main/resources/profiles/local/pinpoint.config
agent-module/agent/src/main/resources/profiles/release/pinpoint.config
agent-module/bootstraps/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/AgentBootLoader.java
agent-module/bootstraps/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/config/SystemPropertyManager.java
agent-module/bootstraps/bootstrap/src/test/java/com/navercorp/pinpoint/bootstrap/config/SystemPropertyManagerTest.java

[#12554] Add isolate system properties

---

agent-module/plugins/grpc/src/main/java/com/navercorp/pinpoint/plugin/grpc/interceptor/server/CopyAsyncContextInterceptor.java

[#12561] Update forwarding server call tracking in grpc plugin

---

agent-module/plugins/grpc/src/main/java/com/navercorp/pinpoint/plugin/grpc/interceptor/server/CopyAsyncContextInterceptor.java

[#12564] Backport: Update forwarding server call tracking in grpc plugin

---

agent-module/agent-testweb/reactor-plugin-testweb/src/main/java/com/pinpoint/test/plugin/AsyncStorageService.java
agent-module/agent-testweb/reactor-plugin-testweb/src/main/java/com/pinpoint/test/plugin/ReactorPluginController.java
agent-module/plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/interceptor/CoreSubscriberRunInterceptor.java

[#12571] Update mono runnable interceptor of reactor pulgin

---

web/src/main/java/com/navercorp/pinpoint/web/service/TransactionInfoServiceImpl.java
web/src/main/java/com/navercorp/pinpoint/web/view/TransactionInfoViewModel.java
web/src/main/java/com/navercorp/pinpoint/web/vo/callstacks/RecordSet.java

[#12575] Fix Call Tree focus of Web

---

web/src/main/java/com/navercorp/pinpoint/web/applicationmap/map/FilteredMapBuilder.java

[#12606] Fix CallStack NPE of web

---

commons-profiler/src/main/java/com/navercorp/pinpoint/common/profiler/sql/ParserContext.java

…ability
This pull request refactors the comment parsing logic in the `ParserContext` class to simplify the code and improve maintainability. The main changes include consolidating duplicate methods, introducing helper methods for handling comments, and renaming parameters for clarity.
* Consolidated the `skipLine`, `readLine`, `skipComment`, and `readComment` methods into a single `readComment` method to reduce code duplication. This new method handles both single-line and multi-line comments based on the provided tokens.
* Introduced two new helper methods, `readComment(String token, int i)` and `readLine(String token, int i)`, to abstract the logic for processing comments. These methods internally call the consolidated `readComment` method and handle the `removeComments` flag.
* …

[#12622] Refactor comment handling in ParserContext for improved readability

---

agent-module/plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor/interceptor/CoreSubscriberRunInterceptor.java

[#12657] Backport: Update mono runnable interceptor of reactor pulgin

---

agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/scanner/ClassScannerFactory.java

[#12664] Backport: Fix nested jar loading of instrument class scanner

---

agent-module/plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/interceptor/StreamTaskDoProcessInterceptor.java
agent-module/plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/recorder/QueueServerRequestRecorder.java

[#12667] Backport: Fix kafka plugin streams interceptor

---

web/src/main/java/com/navercorp/pinpoint/web/controller/TransactionController.java
web/src/main/java/com/navercorp/pinpoint/web/view/TransactionCallTreeCallStackSerializer.java
web/src/main/java/com/navercorp/pinpoint/web/view/TransactionCallTreeViewModel.java
web/src/main/java/com/navercorp/pinpoint/web/view/TransactionServerMapViewModel.java

[#12692] Update separate API the CallTree and ServerMap

---

web/src/main/java/com/navercorp/pinpoint/web/view/TransactionInfoViewModel.java

[#12692] Fix web transaction trace serviceType

---

web-frontend/src/main/v3/packages/ui/src/components/FilterMap/FilterWizard.tsx

- Set FilterWizard scrollY
- Fix style of ResponseTime
- as-is
- <img width="383" height="159" alt="스크린샷 2025-07-29 오후 4 07 00" src="https://github.com/user-attachments/assets/e6cbbad4-cfce-47fb-87bc-807a3bfe3f02" />
- to-be
- <img width="327" height="152" alt="스크린샷 2025-07-29 오후 4 07 07" src="https://github.com/user-attachments/assets/6537b3b1-34c7-4802-95bb-164dad9369a6" />

[#noissue] Set FilterWizard scrollY & Fix style of Response Time

---

commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/wd/RangeDoubleHash.java
commons-hbase/src/test/java/com/navercorp/pinpoint/common/hbase/wd/RangeDoubleHashTest.java

This pull request introduces significant enhancements to the `RangeDoubleHash` class, focusing on improving hashing functionality and test coverage. The changes include the addition of new secondary hash function implementations, factory methods for creating instances with different hashing strategies, and updates to the test suite to validate these enhancements.
* Added two new secondary hash function implementations: `SecondaryRandomHashFunction` for random distribution and `SecondaryRangeHashFunction` for range-based hashing. These are encapsulated in a new `SecondaryHashFunction` interface. (`commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/wd/RangeDoubleHash.java`, [commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/wd/RangeDoubleHash.javaL82-R168](diffhunk …

[#noissue] Enhance RangeDoubleHash with SecondaryHashFunction

---

pinot/pinot-kafka/src/main/java/com/navercorp/pinpoint/pinot/kafka/KafkaConfiguration.java
pinot/pinot-kafka/src/main/java/com/navercorp/pinpoint/pinot/kafka/KafkaProperties.java
pinot/pinot-kafka/src/main/resources/profiles/local/kafka-producer-factory.properties
pinot/pinot-kafka/src/test/java/com/navercorp/pinpoint/pinot/kafka/KafkaConfigurationTest.java

[#12711] Update collector kafka max.block.ms option

---

collector/src/main/java/com/navercorp/pinpoint/collector/service/HbaseTraceService.java

[#12764] Fix collector parent application name NPE

---

collector/src/main/java/com/navercorp/pinpoint/collector/grpc/CollectorGrpcConfiguration.java
collector/src/main/java/com/navercorp/pinpoint/collector/grpc/config/GrpcErrorHandleConfiguration.java

[#12811] Update collector reactor hook onErrorDropped

---

agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/grpc/mapper/AnnotationValueMapper.java
agent-module/profiler/src/test/java/com/navercorp/pinpoint/profiler/context/grpc/mapper/AnnotationValueMapperTest.java

[#12814] Rollback agent NPE in annotation value mapper

---

agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/ChildTrace.java
agent-module/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTrace.java

[#12905] Backport: Update agent "not matched stack id" error log

---

agent-module/agent/src/assembly/component/core.xml
agent-module/bootstraps/bootstrap-core/pom.xml
agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/holder/InterceptorHolderAnnotationProcessor.java
agent-module/bootstraps/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/holder/InterceptorHolderBootstrap.java
agent-module/bootstraps/bootstrap-interceptor/pom.xml
agent-module/bootstraps/bootstrap-interceptor/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/holder/InterceptorHolderGenerator.java
agent-module/bootstraps/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/agentdir/AgentDirBaseClassPathResolver.java
agent-module/bootstraps/pom.xml
annotations/pom.xml
annotations/src/main/resources/META-INF/services/javax.annotation.processing.Processor

[#12923] Update agent interceptorHolder generated class module

---

collector-starter/src/main/java/com/navercorp/pinpoint/collector/starter/multi/application/BasicCollectorApp.java
collector/src/main/java/com/navercorp/pinpoint/collector/CollectorApp.java
collector/src/main/java/com/navercorp/pinpoint/collector/PinpointCollectorModule.java
collector/src/main/java/com/navercorp/pinpoint/collector/event/SpanStorePublisherImpl.java
collector/src/main/java/com/navercorp/pinpoint/collector/event/config/CollectorEventConfiguration.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/event/ContextSupplier.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/event/InsertEvent.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/event/SimpleContextSupplier.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/event/SpanChunkInsertEvent.java
commons-server/src/main/java/com/navercorp/pinpoint/common/server/event/SpanInsertEvent.java

This pull request refactors and extends the event publishing infrastructure in the collector module, focusing on making context handling more flexible and extensible. The changes introduce a new `ContextSupplier` abstraction, update event data structures, and improve configuration for dependency injection. Additionally, some Spring configuration is reorganized for better modularity.
**Core infrastructure improvements:**
* Introduced the `ContextSupplier` interface and a default implementation `SimpleContextSupplier` to provide context data for events, enabling more flexible and testable context creation. (`commons-server/src/main/java/com/navercorp/pinpoint/common/server/event/ContextSupplier.java` [[1]](diffhunk://#diff-89215b7306924a64895912ef2bbb8c93adbac15eb1689a5e4c08b38004f10267R1-R2 …

[#noissue] Enhance SpanStorePublisher to support ContextSupplier

---

collector/src/main/java/com/navercorp/pinpoint/collector/applicationmap/dao/hbase/HbaseHostApplicationMapDao.java

[#noissue] Refactor CacheKey to use record for improved readability and conciseness

---

collector/src/main/java/com/navercorp/pinpoint/collector/CollectorHbaseModule.java

[#noissue] Remove unnecessary `collector.scatter.serverside-scan` property
