- README.md
>  added supported jdk 

- web/src/main/java/com/navercorp/pinpoint/web/view/ApplicationAgentListSerializer.java
- web/src/main/webapp/views/agentInfoMain.html
> [#94] Change position and url Monitor site link in inspector page

- rpc/src/main/java/com/navercorp/pinpoint/rpc/client/PinpointClientSocketHandshaker.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/client/PinpointSocketHandler.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/packet/HandshakeResponseCode.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/server/PinpointServerSocket.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/server/PinpointServerSocketHandshaker.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/server/ServerMessageListener.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/server/handler/HandshakerHandler.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/util/ClassUtils.java
- rpc/src/test/java/com/navercorp/pinpoint/rpc/client/ClientMessageListenerTest.java
- rpc/src/test/java/com/navercorp/pinpoint/rpc/server/HandshakeTest.java
Spllit socket class according to purpose.( initialization and transportation)
> Spllit socket class according to purpose.( initialization and transportation)

- doc/installation.md
added guide on how to build Pinpoint following a git clone.
> Added build section for installation guide.

- collector/src/main/java/com/navercorp/pinpoint/collector/cluster/zookeeper/ZookeeperProfilerClusterManager.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/client/PinpointSocketHandler.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/client/State.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/server/ChannelContext.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/server/PinpointServerSocket.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/server/PinpointServerSocketState.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/server/PinpointServerSocketStateCode.java
- rpc/src/test/java/com/navercorp/pinpoint/rpc/server/EventHandlerTest.java
- rpc/src/test/java/com/navercorp/pinpoint/rpc/server/HandshakeTest.java
- rpc/src/test/java/com/navercorp/pinpoint/rpc/server/PinpointServerSocketStateTest.java
1. changed return type of change state code method from boolean to PinpointServerSocketStateCode.
2. cleand up PinpointServerSocket class. (Channel's event. )
3. RUN_SIMPLEX state added to PinpointServerSocketStateCode.
> Add an extra server socket state code for handshake packet #83

- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/instrument/Attachment.java
- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/instrument/AttachmentFactory.java
- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/instrument/InstrumentClass.java
- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/instrument/ScopeDefinition.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/interceptor/bci/DefaultScopeDefinition.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/interceptor/bci/JavaAssistByteCodeInstrumentor.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/interceptor/bci/JavaAssistClass.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/util/AttachmentSimpleScope.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/util/AttachmentSimpleScopeFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/util/ScopePool.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/util/SimpleScope.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/util/AttachmentSimpleScopeTest.java
> Scope api refactoring

- profiler/src/test/java/com/navercorp/pinpoint/profiler/util/ThreadLocalScopePoolTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/util/ThreadLocalScopeTest.java
scope api refactoring
- add testcase
> scope api refactoring  - add testcase

- rpc/src/main/java/com/navercorp/pinpoint/rpc/client/PinpointSocketHandler.java
- rpc/src/test/java/com/navercorp/pinpoint/rpc/client/ReconnectTest.java
Modifications:
- execute releaseResource method everytime when channelClosed method
executed.
> Timer thread leak when client reconnect to server. #140

- .travis.yml
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/DefaultServerMetaDataHolderTest.java
- web/src/test/java/com/navercorp/pinpoint/web/cluster/ClusterTest.java
- web/src/test/java/com/navercorp/pinpoint/web/cluster/zookeeper/ZookeeperClusterTest.java
- web/src/test/java/com/navercorp/pinpoint/web/util/PinpointWebTestUtils.java
Modifications:
- add .travis.yml.
- clean up test case for travis ci.
> Integrate travis ci into pinpoint #147

- profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/connector/httpclient4/interceptor/AbstractHttpRequestExecuteWithDivergence.java
> #76_httpclient4_codereivew

- thrift/src/main/java/com/navercorp/pinpoint/thrift/io/TCommandTypeVersion.java
> 1.0.4 release #154

- agent/pom.xml
- bootstrap-core/pom.xml
- bootstrap/pom.xml
- collector/pom.xml
- commons/pom.xml
- pom.xml
- profiler-optional/pom.xml
- profiler/pom.xml
- rpc/pom.xml
- test/pom.xml
- thrift/pom.xml
- web/pom.xml
> prepare 1.1.0-SNAPSHOT

- test/clover.license
> added clover license

- rpc/src/main/java/com/navercorp/pinpoint/rpc/client/ConnectFuture.java
#136 Improve state synchronization between server and client.
- code review
> #136 Improve state synchronization between server and client.  - code review

- commons/src/main/java/com/navercorp/pinpoint/common/ServiceType.java
- commons/src/main/java/com/navercorp/pinpoint/common/plugin/ServiceTypeSetupContext.java
- commons/src/main/java/com/navercorp/pinpoint/common/util/AnnotationUtils.java
reduce coupling of AnnotationKeyMatcher
> reduce coupling of AnnotationKeyMatcher

- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/context/RecordableTrace.java
- bootstrap/src/test/java/com/navercorp/pinpoint/bootstrap/interceptor/MockTrace.java
- commons/src/main/java/com/navercorp/pinpoint/common/AnnotationKey.java
- commons/src/main/java/com/navercorp/pinpoint/common/TypeProviderLoader.java
- commons/src/main/java/com/navercorp/pinpoint/common/util/StaticFieldLookUp.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/AgentInfoSender.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/AgentInformation.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/AgentInformationFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/DefaultAgent.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTrace.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTraceContext.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DisableTrace.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/MetricTrace.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/RootStackFrame.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/SpanEventStackFrame.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/StackFrame.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/connector/httpclient4/interceptor/AbstractHttpRequestExecuteWithDivergence.java
- profiler/src/main/java/com/navercorp/pinpoint/test/MockAgent.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/AgentInfoSenderTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/DefaultTraceContextTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/DefaultTraceTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/SpanChunkFactoryTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/ThreadLocalTraceFactoryTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/TraceTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/storage/BufferedStorageTest.java
- web/src/main/java/com/navercorp/pinpoint/web/service/AnnotationKeyMatcherService.java
- web/src/main/java/com/navercorp/pinpoint/web/service/TransactionInfoServiceImpl.java
refactoring ServiceType dependency
> refactoring ServiceType dependency

- web/src/main/webapp/index.html
- web/src/main/webapp/scripts/app.js
- web/src/main/webapp/scripts/extra/helpContent-en.js
- web/src/main/webapp/scripts/extra/helpContent-ko.js
Detects browser/OS language and displays the HelpContent accordingly.
Added Korean help content.
> Added rudimentary support for multilingual helpContent.

- collector/src/main/java/com/navercorp/pinpoint/collector/cluster/zookeeper/ZookeeperClient.java
- collector/src/main/java/com/navercorp/pinpoint/collector/cluster/zookeeper/ZookeeperClusterService.java
- web/src/main/java/com/navercorp/pinpoint/web/cluster/zookeeper/ZookeeperClient.java
- web/src/main/java/com/navercorp/pinpoint/web/cluster/zookeeper/ZookeeperClusterManager.java
Modifications:
- execute to create zookeeper instance when zookeeper session has
expired.
> Zookeeper does not reconnect when session expired. #191

- collector/src/main/java/com/navercorp/pinpoint/collector/cluster/zookeeper/ZookeeperClient.java
- web/src/main/java/com/navercorp/pinpoint/web/cluster/zookeeper/ZookeeperClient.java
> fix klocwork issue

- scripts/hbase-create-snappy.hbase
- scripts/hbase-create.hbase
- scripts/hbase-drop.hbase
- scripts/hbase-flush-table.hbase
- scripts/hbase-major-compact-htable.hbase
> cleanup hbase script

- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/context/TraceContext.java
- bootstrap/src/test/java/com/navercorp/pinpoint/bootstrap/interceptor/MockTraceContext.java
- commons/src/main/java/com/navercorp/pinpoint/common/util/DefaultParsingResult.java
- commons/src/test/java/com/navercorp/pinpoint/common/util/DefaultParsingResultTest.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTrace.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTraceContext.java
> #208 Improvement sql cache logic -1.0.x backport

- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/context/TraceContext.java
- bootstrap/src/test/java/com/navercorp/pinpoint/bootstrap/interceptor/MockTraceContext.java
- commons/src/main/java/com/navercorp/pinpoint/common/util/DefaultParsingResult.java
- commons/src/test/java/com/navercorp/pinpoint/common/util/DefaultParsingResultTest.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTrace.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTraceContext.java
- test/src/main/java/com/navercorp/pinpoint/test/mock/MockTraceContext.java
#208 Improvement sql cache logic
> #208 Improvement sql cache logic

- web/src/test/java/com/navercorp/pinpoint/web/view/ServerInstanceListSerializerTest.java
> fix testcase fail

- collector/src/main/webapp/WEB-INF/web.xml
- web/src/main/webapp/WEB-INF/web.xml
refactoring ServiceType dependency
- remove ServiceTypeLoader
> refactoring ServiceType dependency  - remove ServiceTypeLoader

- web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseApplicationIndexDao.java
- web/src/main/java/com/navercorp/pinpoint/web/mapper/ApplicationNameMapper.java
The application list is now generates additional applications for each
service type registered under the same application name.
> change how the application list is generated - #214

- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/config/ProfilerConfig.java
- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/instrument/ByteCodeInstrumentor.java
- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/ProfilerPluginContext.java
- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/ProfilerPluginSetupContext.java
- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/editor/ClassEditorBuilder.java
- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/test/PluginTestVerifier.java
- commons/src/main/java/com/navercorp/pinpoint/common/service/DefaultTypeLoaderService.java
- commons/src/test/java/com/navercorp/pinpoint/common/AnnotationKeyTest.java
- plugins/redis/src/main/java/com/navercorp/pinpoint/plugin/redis/RedisPlugin.java
- plugins/servlet/src/main/java/com/navercorp/pinpoint/plugin/servlet/ServletPlugin.java
- plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/TomcatPlugin.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/ClassFileRetransformer.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/ClassFileTransformerDispatcher.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/DefaultAgent.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/interceptor/bci/JavaAssistByteCodeInstrumentor.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/ClassEditorAdaptor.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/ClassEditorExecutor.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/DefaultProfilerPluginContext.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/editor/DefaultClassEditorBuilder.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/editor/FilteringMethodEditor.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/interceptor/AnnotatedInterceptorFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/interceptor/AnnotatedInterceptorInjector.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/interceptor/TargetAnnotatedInterceptorInjector.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/objectfactory/AutoBindingObjectFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/objectfactory/PinpointTypeResolver.java
- profiler/src/main/java/com/navercorp/pinpoint/test/PluginTestAgent.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/plugin/DefaultClassEditorBuilderTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/plugin/DefaultInterceptorFactoryTest.java
- test/src/main/java/com/navercorp/pinpoint/test/plugin/PinpointPluginTestStatement.java
> [#117] Added ProfilerPluginSetupContext.addClassEditor().

- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/PinpointBootStrap.java
- commons/src/main/java/com/navercorp/pinpoint/common/buffer/FixedBuffer.java
- commons/src/test/java/com/navercorp/pinpoint/common/buffer/FixedBufferTest.java
add thread name of shutdownhook
improvement buffer offset handling
> add thread name of shutdownhook, improvement buffer offset handling

- agent/src/assembly/distribution.xml
add script dir to distribution.xml
> add script dir to distribution.xml

- quickstart/bin/stop-hbase.sh
- quickstart/conf/quickstart.properties
Updated quickstart.version to 1.0.5-SNAPSHOT
> Fixed bug in stop-hbase.sh

- profiler/src/main/java/com/navercorp/pinpoint/profiler/interceptor/bci/JavaAssistClass.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/connector/jdkhttpconnector/HttpURLConnectionModifier.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/connector/jdkhttpconnector/interceptor/ConnectMethodInterceptor.java
getOUtputStream()
ConnectMethodInterceptor will check 'connected' before setting request
headers.
> [#235] intercept not only connect() but also getInputStream() and

- profiler/src/main/java/com/navercorp/pinpoint/profiler/util/ApplicationServerTypeResolver.java
fixed ineffective conditional check - `if (registeredDetectors.containsKey(orderedDetector));`
> fixed a bug regarding missing conditional check.

- commons/src/main/java/com/navercorp/pinpoint/common/bo/SpanEventBo.java
- web/src/main/java/com/navercorp/pinpoint/web/service/SpanServiceImpl.java
> patch web annotation logic bug

- profiler/src/main/java/com/navercorp/pinpoint/profiler/interceptor/bci/IsolateMultipleClassPool.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/interceptor/bci/JavaAssistByteCodeInstrumentor.java
> #88_multiple_classLoader_support

- rpc/src/main/java/com/navercorp/pinpoint/rpc/client/PinpointSocketFactory.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/client/PinpointSocketHandler.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/codec/PacketDecoder.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/common/CyclicStateChecker.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/common/SocketState.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/common/SocketStateCode.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/packet/PingPacket.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/server/DefaultPinpointServer.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/server/DefaultPinpointServerState.java
- rpc/src/test/java/com/navercorp/pinpoint/rpc/common/CyclicStateCheckerTest.java
inclue socket's info in ping packet.
> Improve state synchronization between server and client.

- commons/src/main/java/com/navercorp/pinpoint/common/util/ClassLoaderUtils.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/interceptor/bci/ClassLoadChecker.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/interceptor/bci/HierarchyMultipleClassPool.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/interceptor/bci/IsolateMultipleClassPool.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/interceptor/bci/SingleClassPool.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/interceptor/bci/ClassLoadCheckerTest.java
#88 support multiple classLoader
> #88 support multiple classLoader

- pom.xml
backport 1.0.x. cdh versionup.
> #271 CDH minor version up   CDH 4.5.0 -> CDH 4.7.1

- profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/UdpDataSender.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/sender/UdpDataSenderTest.java
- thrift/src/main/java/com/navercorp/pinpoint/thrift/io/BufferOverflowException.java
- thrift/src/main/java/com/navercorp/pinpoint/thrift/io/ChunkHeaderBufferedTBaseSerializerFactory.java
- thrift/src/main/java/com/navercorp/pinpoint/thrift/io/HeaderTBaseSerializerFactory.java
- thrift/src/main/java/com/navercorp/pinpoint/thrift/io/PinpointByteArrayOutputStream.java
- thrift/src/main/java/com/navercorp/pinpoint/thrift/io/UnsafeByteArrayOutputStream.java
- thrift/src/test/java/com/navercorp/pinpoint/thrift/io/PinpointByteArrayOutputStreamTest.java
- thrift/src/test/java/com/navercorp/pinpoint/thrift/io/UnsafeByteArrayOutputStreamTest.java
Serializer of UdpDataSender makes excpetion when input data size over
than max size.
> Change serializer rule. #269

- profiler/src/test/java/com/navercorp/pinpoint/profiler/interceptor/bci/ClassLoadCheckerTest.java
#88 support multiple classLoader
- fix testcase
> #88 support multiple classLoader  - fix testcase

- profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/connector/httpclient4/HttpClient4Modifier.java
> [#281] backport Improved logic for checking if http client class can be

- agent/src/main/resources/pinpoint.config
- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/config/ProfilerConfig.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/ClassFileTransformerDispatcher.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/DefaultModifierRegistry.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/log/MdcKey.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/log/log4j/LoggingEventOfLog4jModifier.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/log/log4j/interceptor/LoggingEventOfLog4jInterceptor.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/log/logback/LoggingEventOfLogbackModifier.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/log/logback/interceptor/LoggingEventOfLogbackInterceptor.java
- web/src/main/java/com/navercorp/pinpoint/web/controller/ScatterChartController.java
- web/src/main/resources/pinpoint-web.properties
- web/src/main/webapp/WEB-INF/views/transactionmetadata.jsp
- web/src/main/webapp/views/transactionTable.html
Backport.
[#143] Add logging profiler to log containing transaction information. 
[#234] Add feature to see log of application using
pinpoint agent
> [#143][#234] Backport. Add logging feature

- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/SpanSimpleAroundInterceptor.java
- plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/interceptor/StandardHostValveInvokeInterceptor.java
> remove extra traceBlockBegin() & traceBlockEnd()

- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/SpanSimpleAroundInterceptor.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/tomcat/interceptor/StandardHostValveInvokeInterceptor.java
> change abstract to concrete method

- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/instrument/InstrumentClass.java
- commons/src/main/java/com/navercorp/pinpoint/common/util/ClassLoaderUtils.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/DefaultAgent.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/interceptor/bci/ClassLoadChecker.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/interceptor/bci/IsolateMultipleClassPool.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/interceptor/bci/JavaAssistByteCodeInstrumentor.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/interceptor/bci/JavaAssistClass.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/interceptor/bci/MultipleClassPool.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/tomcat/RequestFacadeModifier.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/util/JavaAssistUtils.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/util/Maps.java
- profiler/src/main/java/com/navercorp/pinpoint/test/TestClassLoader.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/sender/UdpSocketTest.java
> #88 backport 1.0.x. support multiple classLoader

- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/context/RecordableTrace.java
- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/context/StackOperation.java
- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/instrument/Scope.java
- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/group/ExecutionPoint.java
- bootstrap/src/test/java/com/navercorp/pinpoint/bootstrap/interceptor/MockTrace.java
- plugins/jdk-http/src/main/java/com/navercorp/pinpoint/plugin/jdk/http/interceptor/HttpURLConnectionInterceptor.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTrace.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DisableTrace.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/MetricTrace.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/interceptor/DebugScopeDelegateSimpleInterceptor.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/interceptor/DebugScopeDelegateStaticInterceptor.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/interceptor/ScopeDelegateSimpleInterceptor.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/interceptor/ScopeDelegateStaticInterceptor.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/connector/httpclient4/interceptor/AbstractHttpRequestExecuteWithDivergence.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/db/interceptor/DriverConnectInterceptor.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/DefaultScope.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/interceptor/ScopedSimpleAroundInterceptor.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/interceptor/ScopedStaticAroundInterceptor.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/util/ThreadLocalScope.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/util/DefaultScopeTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/util/ThreadLocalScopePoolTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/util/ThreadLocalScopeTest.java
- Removed trace block attachment
- Removed trace attribute
- Refined Scope APIs
> Let HttpURLConnectionInterceptor use scope attachment rather than trace block attachment

- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/PinpointBootStrap.java
- improving testability of PinpointBootStrap
> #117 plugin system refactoring

- commons/src/main/java/com/navercorp/pinpoint/common/hbase/PooledHTableFactory.java
`HTablePool`  is deprecated in hbase 0.94.15. Based on https://issues.apache.org/jira/browse/HBASE-6580, I added `HConnection` and `HConnectionManager`.
But I'm not sure about exception handling.
> change deprecated HTablePool api to HConnection

- commons/src/main/java/com/navercorp/pinpoint/common/hbase/PooledHTableFactory.java
#320 change deprecated HTablePool api to HConnection
> #320 change deprecated HTablePool api to HConnection

- web/src/main/java/com/navercorp/pinpoint/web/controller/FilteredMapController.java
- web/src/main/java/com/navercorp/pinpoint/web/controller/MapController.java
Conflicts:
web/src/main/java/com/navercorp/pinpoint/web/controller/MapController.java
> added request mappings to support serviceTypeName parameters

- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/config/ExcludeUrlFilter.java
- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/util/AntPathMatcher.java
- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/util/EqualsPathMatcher.java
- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/util/PathMatcher.java
- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/util/spring/AntPathMatcher.java
- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/util/spring/PathMatcher.java
- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/util/spring/StringUtils.java
- bootstrap/src/test/java/com/navercorp/pinpoint/bootstrap/config/ExcludeUrlFilterTest.java
- bootstrap/src/test/java/com/navercorp/pinpoint/bootstrap/util/AntPathMatcherTest.java
> #138_use_antstyle_matcher_to_exclude_url

- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/config/ExcludeUrlFilter.java
- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/util/AntPathMatcher.java
- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/util/EqualsPathMatcher.java
- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/util/PathMatcher.java
- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/util/spring/AntPathMatcher.java
- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/util/spring/PathMatcher.java
- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/util/spring/StringUtils.java
- bootstrap/src/test/java/com/navercorp/pinpoint/bootstrap/config/ExcludeUrlFilterTest.java
- bootstrap/src/test/java/com/navercorp/pinpoint/bootstrap/util/AntPathMatcherTest.java
backport 1.0.x #138 support antsyle url excludepatten
> #138_backport_antstyle_url

- filefilter.txt
> #138 added klocwork exclude

- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/util/AntPathMatcher.java
- bootstrap/src/test/java/com/navercorp/pinpoint/bootstrap/config/ExcludeUrlFilterTest.java
- bootstrap/src/test/java/com/navercorp/pinpoint/bootstrap/util/EqualsPathMatcherTest.java
> #138 add testcase

- web/src/main/java/com/navercorp/pinpoint/web/config/ConfigProperties.java
- web/src/main/java/com/navercorp/pinpoint/web/controller/ConfigController.java
- web/src/main/resources/pinpoint-web.properties
> added controller for serving user configuration.

- profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/DefaultModifierRegistry.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/orm/ibatis/SqlMapModifier.java
- profiler/src/main/java/com/navercorp/pinpoint/test/InstrumentTranslator.java
- profiler/src/main/java/com/navercorp/pinpoint/test/TestClassLoader.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/interceptor/bci/JavaAssistClassTest.java
> #360 improved matching api

- web/src/main/java/com/navercorp/pinpoint/web/controller/MapController.java
- web/src/main/java/com/navercorp/pinpoint/web/service/LinkDataSelector.java
- web/src/main/java/com/navercorp/pinpoint/web/service/MapService.java
- web/src/main/java/com/navercorp/pinpoint/web/service/MapServiceImpl.java
- web/src/main/java/com/navercorp/pinpoint/web/service/SearchDepth.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/SearchOption.java
- web/src/test/java/com/navercorp/pinpoint/web/service/SearchDepthTest.java
-add testcase
-rename SearchRange-> SearchOption, SearchLevel->SearchDepth
> #377 support depth-limited search

- collector/src/main/java/com/navercorp/pinpoint/collector/handler/AgentStatHandler.java
- collector/src/main/java/com/navercorp/pinpoint/collector/handler/Handler.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/AbstractDispatchHandler.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/DispatchHandler.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/tcp/TCPReceiver.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/udp/BaseUDPReceiver.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/udp/ChunkedUDPReceiver.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/udp/SpanStreamUDPReceiver.java
- collector/src/test/java/com/navercorp/pinpoint/collector/handler/AgentStatHandlerTest.java
- collector/src/test/java/com/navercorp/pinpoint/collector/receiver/udp/UDPReceiverTest.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/SpanStreamSendData.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/SpanStreamSendDataSerializer.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/sender/planer/SpanStreamSendDataPlanerTest.java
- thrift/src/main/java/com/navercorp/pinpoint/thrift/io/SpanStreamConstants.java
1. remove unused paramter of handler
2. implements collector's span stream receiver
> Optimize udp efficiency.

- web/src/main/java/com/navercorp/pinpoint/web/service/BFSLinkSelector.java
- web/src/main/java/com/navercorp/pinpoint/web/service/DFSLinkSelector.java
- web/src/main/java/com/navercorp/pinpoint/web/service/LinkSelector.java
- web/src/main/java/com/navercorp/pinpoint/web/service/LinkVisitChecker.java
- web/src/main/java/com/navercorp/pinpoint/web/service/MapServiceImpl.java
- web/src/main/java/com/navercorp/pinpoint/web/service/SearchDepth.java
- web/src/main/resources/log4j.xml
- add bfs search
- remove deprecated api
> #377 support depth limited search

- docker/pinpoint-collector/Dockerfile
- docker/pinpoint-collector/hbase.properties
- docker/pinpoint-collector/pinpoint-collector.properties
- docker/pinpoint-collector/start.sh
- docker/pinpoint-hbase/Dockerfile
- docker/pinpoint-hbase/hbase-site.xml
- docker/pinpoint-web/Dockerfile
- docker/pinpoint-web/hbase.properties
- docker/pinpoint-web/pinpoint-web.properties
- docker/pinpoint-web/start.sh
Initial attempt at Dockerizing pinpoint, per Issue #246.
> Dockerize HBase, Collector and Web

- profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/SpanStreamUdpSender.java
> Optimize udp efficiency. #286

- web/src/main/java/com/navercorp/pinpoint/web/calltree/span/CallTreeIterator.java
- web/src/main/java/com/navercorp/pinpoint/web/calltree/span/SpanAlign.java
- web/src/main/java/com/navercorp/pinpoint/web/service/TransactionInfoServiceImpl.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/callstacks/Record.java
- web/src/test/java/com/navercorp/pinpoint/web/calltree/span/CallTreeIteratorTest.java
> Execution milliseconds

- web/src/test/java/com/navercorp/pinpoint/web/calltree/span/CallTreeIteratorTest.java
> fix testcase - ignored root node.gap()

- web/src/main/webapp/scripts/directives/navbar.js
- web/src/main/webapp/scripts/directives/serverMap.js
- web/src/main/webapp/styles/navbar.css
- web/src/main/webapp/views/navbar.html
- web/src/main/webapp/views/serverMap.html
> Change to 24 hour time display

- web/src/main/java/com/navercorp/pinpoint/web/calltree/span/SpanAligner2.java
> add NPE check logic

- agent/pom.xml
- bootstrap-core/pom.xml
- bootstrap/pom.xml
- collector/pom.xml
- commons/pom.xml
- commons/src/main/java/com/navercorp/pinpoint/common/Version.java
- plugins/httpclient4/pom.xml
- plugins/jdbc-driver/pom.xml
- plugins/jdk-http/pom.xml
- plugins/pom.xml
- plugins/redis/pom.xml
- plugins/servlet/pom.xml
- plugins/tomcat/pom.xml
- pom.xml
- profiler-optional/pom.xml
- profiler/pom.xml
- quickstart/conf/quickstart.properties
- rpc/pom.xml
- test/pom.xml
- thrift/pom.xml
- web/pom.xml
- version 1.1.0-SNAPSHOT->1.5.0-SNAPSHOT
> #382 upgrade hbase version 

- pom.xml
Change maven plugin repository becuase Codehaus services will be
terminated.
> change maven plugin repository #417

- agent/pom.xml
- bootstrap-core/pom.xml
- bootstrap/pom.xml
- collector/pom.xml
- commons/pom.xml
- commons/src/main/java/com/navercorp/pinpoint/common/Version.java
- pom.xml
- profiler-optional/pom.xml
- profiler/pom.xml
- quickstart/conf/quickstart.properties
- rpc/pom.xml
- thrift/pom.xml
- thrift/src/main/java/com/navercorp/pinpoint/thrift/io/TCommandTypeVersion.java
- web/pom.xml
changed version. (1.0.5-SNAPSHOT -> 1.0.5)
> 1.0.5 release #423

- plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/ServletAsyncMethodDescriptor.java
- plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/ServletSyncMethodDescriptor.java
> apply web request method type

- plugins/jdk-http/src/main/java/com/navercorp/pinpoint/plugin/jdk/http/interceptor/HttpURLConnectionInterceptor.java
> add Pinpoint-Host HTTP header

- web/src/main/webapp/common/services/progress-bar.service.js
- web/src/main/webapp/features/scatter/jquery.BigScatterChart.js
- web/src/main/webapp/index.html
- web/src/main/webapp/pages/transactionDetail/transactionDetail.html
Rename : Distributed Call Flow -> Call Tree
Rename : RPC Timeline -> Timeline
Remove loading help
Remove "Drag me!" help
> Rename title and remove feature

- collector/src/main/resources/applicationContext-hbase.xml
- collector/src/main/resources/hbase.properties
- collector/src/main/resources/pinpoint-collector.properties
- commons/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseTemplate2.java
- commons/src/main/java/com/navercorp/pinpoint/common/hbase/PooledHTableFactory.java
- web/src/main/resources/applicationContext-hbase.xml
- web/src/main/resources/hbase.properties
- web/src/main/resources/log4j.xml
change htablePool api
- added hBase timeout option
- added hConnection thread pool option
> #320 change deprecated h table pool api to hconnection

- web/src/main/java/com/navercorp/pinpoint/web/filter/FilterHint.java
- web/src/main/java/com/navercorp/pinpoint/web/filter/FromToResponseFilter.java
> added checks to filtering for NPE fix and RPC internal methods

- collector/src/main/resources/applicationContext-hbase.xml
- collector/src/main/resources/hbase.properties
- collector/src/main/resources/pinpoint-collector.properties
- commons/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseTemplate2.java
- commons/src/main/java/com/navercorp/pinpoint/common/hbase/PooledHTableFactory.java
- web/src/main/resources/applicationContext-hbase.xml
- web/src/main/resources/hbase.properties
- web/src/main/resources/log4j.xml
- added hbase 1.0 timeout option
- added thread pool option
> #320_backport_change_htable_api

- quickstart/collector/src/main/resources/log4j.xml
- quickstart/web/src/main/resources/log4j.xml
remove unused appender
add console appender to quickstart-web
> #320 cleanup hbase option

- quickstart/collector/src/main/resources/hbase.properties
- quickstart/collector/src/main/resources/log4j.xml
- quickstart/collector/src/main/resources/pinpoint-collector.properties
- quickstart/web/src/main/resources/hbase.properties
- quickstart/web/src/main/resources/log4j.xml
change quickstart hbase option
remove unused appender
add console appender to quickstart-web
> #320 cleanup hbase option, log4j.xml

- web/src/main/webapp/common/help/help-content-en.js
- web/src/main/webapp/common/help/help-content-ko.js
- web/src/main/webapp/common/help/help-content-template.js
- web/src/main/webapp/features/agentList/agent-list.directive.js
- web/src/main/webapp/features/navbar/navbar.directive.js
- web/src/main/webapp/features/nodeInfoDetails/node-info-details.directive.js
- web/src/main/webapp/features/scatter/jquery.BigScatterChart.js
- web/src/main/webapp/features/scatter/scatter.directive.js
- web/src/main/webapp/features/serverMap/server-map.directive.js
- web/src/main/webapp/features/transactionTable/transaction-table.directive.js
- web/src/main/webapp/index.html
- web/src/main/webapp/pages/main/main.controller.js
- web/src/main/webapp/pages/transactionDetail/transaction-detail.controller.js
https://github.com/naver/pinpoint/issues/497
> Remove duplicated help template code.

- profiler/src/main/java/com/navercorp/pinpoint/test/PluginTestAgent.java
- test/src/main/java/com/navercorp/pinpoint/test/plugin/AbstractPinpointPluginTestSuite.java
- Cannot find jvm executable when @JvmVersion is not specified
- verifyTraceBlock() throws NPE when there is no trace
> Fixed plugin test tool bugs

- agent/src/test/java/com/navercorp/pinpoint/plugin/json_lib/JsonLibJSONArrayIT.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/json_lib/JsonLibJSONObjectIT.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/json_lib/JsonLibJSONSerializerIT.java
- plugins/json-lib/pom.xml
- plugins/json-lib/src/main/java/com/navercorp/pinpoint/plugin/json/lib/interceptor/JsonLibMethodInterceptor.java
[JsonLibMethodInterceptor]
1. add json length check interceptor
2. add json length check interceptor test
> add json length check interceptor and test json length check in agent/test

- agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/client/AsyncEchoTestClient.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/client/SyncEchoTestClient.java
Applied hostname retrieval modification to Annotations checks in Thrift integration tests.
> #329 added hostname modification to Annotation checks

- pom.xml
- web/pom.xml
- change tomcat plugin version
> modify pom.xml for CI

- README.md
- doc/installation.md
removed HBase 0.96.x compatibility (EOL)
added HBase 1.1.x compatibility
> updated HBase compatibility table

- web/src/main/webapp/components/pinpoint-scatter/jquery.BigScatterChart.js
- web/src/main/webapp/scripts/services/ProgressBar.js
> Remove loading help

- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/InterceptorRegistry.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/Locker.java
- bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/interceptor/AtomicMaxUpdater.java
- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/AgentClassLoader.java
- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/PinpointBootStrap.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/tcp/TCPReceiver.java
- plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/HttpClient4Constants.java
- plugins/redis/src/main/java/com/navercorp/pinpoint/plugin/redis/interceptor/JedisPipelineSetClientMethodInterceptor.java
- plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/interceptor/CoyoteAdapterInterceptor.java
- plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/interceptor/RequestRecycleInterceptor.java
- plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/interceptor/RequestStartAsyncInterceptor.java
Remove unused imports, Add suppress warnings, close resources not closed.
> Remove compile warning.

- web/src/main/webapp/common/services/alerts.service.js
- web/src/main/webapp/features/serverMap/server-map.directive.js
- web/src/main/webapp/index.html
> Update error display format

- web/src/main/webapp/features/agentInfo/agent-info.directive.js
- web/src/main/webapp/pages/transactionDetail/transaction-detail.controller.js
- web/src/main/webapp/pages/transactionView/transaction-view.controller.js
>  Update error display format (2)

- web/src/main/java/com/navercorp/pinpoint/web/applicationmap/rawdata/LinkCallData.java
- web/src/main/java/com/navercorp/pinpoint/web/applicationmap/rawdata/LinkData.java
- web/src/main/java/com/navercorp/pinpoint/web/applicationmap/rawdata/LinkDataDuplexMap.java
- web/src/main/java/com/navercorp/pinpoint/web/applicationmap/rawdata/LinkDataMap.java
- web/src/test/java/com/navercorp/pinpoint/web/service/BFSLinkSelectorTest.java
> #523 backport Improvement graph traverse algorithm of ServerMap

- rpc/src/main/java/com/navercorp/pinpoint/rpc/client/PinpointSocketHandler.java
insert socket id to handshakedata.
> Add lifecycle support for agents #84

- agent/src/main/resources/pinpoint.config
- plugins/user/src/main/java/com/navercorp/pinpoint/plugin/user/interceptor/UserIncludeMethodInterceptor.java
> User include

- commons-hbase/pom.xml
> #588 Extract commons-hbase module

- web/src/main/java/com/navercorp/pinpoint/web/controller/ControllerExceptionHandler.java
fix method with missing return statement.
> #535 Shows detail error message when web controller meets any exception.

- commons-hbase/pom.xml
- commons/src/main/java/com/navercorp/pinpoint/common/util/DateUtils.java
- pom.xml
> #567 Extract commons-hbase module

- profiler/src/main/java/com/navercorp/pinpoint/profiler/interceptor/bci/JavaAssistByteCodeInstrumentor.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/JarProfilerPluginClassLoader.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/SpanStreamUdpSender.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/util/ListUtils.java
- test/src/main/java/com/navercorp/pinpoint/test/plugin/StreamRedirector.java
> fix static analysis warning

- collector/src/main/java/com/navercorp/pinpoint/collector/manage/AbstractPinpointCollectorMBean.java
- collector/src/main/java/com/navercorp/pinpoint/collector/manage/PinpointCollectorMBean.java
- collector/src/main/java/com/navercorp/pinpoint/collector/manage/PinpointCollectorManager.java
- collector/src/main/java/com/navercorp/pinpoint/collector/manage/PinpointMBeanServer.java
- collector/src/main/resources/applicationContext-collector.xml
Managing server's resources with JMX.
> [collector] Managing server's resources with JMX. #582

- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/udp/BaseUDPHandlerFactory.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/udp/ChunkedUDPPacketHandlerFactory.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/udp/PacketHandler.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/udp/PacketHandlerFactory.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/udp/PooledPacketWrap.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/udp/SpanStreamUDPPacketHandlerFactory.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/udp/TimingWrap.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/udp/UDPReceiver.java
- collector/src/main/java/com/navercorp/pinpoint/collector/util/ByteBufferFactory.java
- collector/src/main/java/com/navercorp/pinpoint/collector/util/DefaultObjectPool.java
- collector/src/main/java/com/navercorp/pinpoint/collector/util/PooledObject.java
- collector/src/main/resources/applicationContext-collector.xml
- collector/src/test/java/com/navercorp/pinpoint/collector/receiver/udp/UDPReceiverTest.java
> refactoring collector

- collector/src/main/java/com/navercorp/pinpoint/collector/handler/AgentInfoHandler.java
- collector/src/main/java/com/navercorp/pinpoint/collector/handler/ApiMetaDataHandler.java
- collector/src/main/java/com/navercorp/pinpoint/collector/handler/HandlerUtils.java
- collector/src/main/java/com/navercorp/pinpoint/collector/handler/SpanChunkHandler.java
- collector/src/main/java/com/navercorp/pinpoint/collector/handler/SpanHandler.java
- collector/src/main/java/com/navercorp/pinpoint/collector/handler/SqlMetaDataHandler.java
- collector/src/main/java/com/navercorp/pinpoint/collector/handler/StringMetaDataHandler.java
- collector/src/main/java/com/navercorp/pinpoint/collector/manage/DBAccessControl.java
- collector/src/main/java/com/navercorp/pinpoint/collector/manage/DBAccessControlMBean.java
- collector/src/main/java/com/navercorp/pinpoint/collector/manage/PinpointCollectorManager.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/tcp/TCPReceiver.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/udp/BaseUDPHandlerFactory.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/udp/ChunkedUDPPacketHandlerFactory.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/udp/SpanStreamUDPPacketHandlerFactory.java
- collector/src/main/resources/applicationContext-hbase.xml
- commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/AccessControlHBaseTemplate.java
- commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/AccessControlOperations.java
- commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/AccessDeniedHBaseOperations.java
- commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/exception/HBaseAccessDeniedException.java
Add db access contoroller using JMX
> [collector] Add db access contoroller. #588

- web/src/main/webapp/common/filters/icon-url.filter.js
- web/src/main/webapp/features/linkInfoDetails/link-info-details.directive.js
- web/src/main/webapp/features/linkInfoDetails/linkInfoDetails.html
- web/src/main/webapp/features/loadChart/load-chart.directive.js
- web/src/main/webapp/features/navbar/navbar.html
- web/src/main/webapp/features/nodeInfoDetails/node-info-details.directive.js
- web/src/main/webapp/features/nodeInfoDetails/nodeInfoDetails.html
- web/src/main/webapp/features/scatter/jquery.BigScatterChart.js
- web/src/main/webapp/features/serverList/server-list.directive.js
- web/src/main/webapp/index.html
Add date in x-axis of scatter chart and load chart
#593
> Improvement Servers UI

- collector/src/main/java/com/navercorp/pinpoint/collector/manage/HandlerManager.java
- collector/src/main/java/com/navercorp/pinpoint/collector/manage/HandlerManagerMBean.java
- collector/src/main/java/com/navercorp/pinpoint/collector/manage/PinpointCollectorManager.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/AbstractDispatchHandler.java
- collector/src/main/resources/applicationContext-collector.xml
[collector] Add handler access contoroller.
> [collector] Add handler access contoroller. #588

- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/util/NumberUtils.java
- bootstrap/src/test/java/com/navercorp/pinpoint/bootstrap/util/NumberUtilsTest.java
- bootstrap/src/test/java/com/navercorp/pinpoint/bootstrap/util/StringUtilsTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/util/NameValueListTest.java
[NumberUtils](https://github.com/naver/pinpoint/blob/master/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/util/NumberUtils.java), [StringUtils](https://github.com/naver/pinpoint/blob/master/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/util/StringUtils.java), [NameValueList](https://github.com/naver/pinpoint/blob/master/profiler/src/main/java/com/navercorp/pinpoint/profiler/util/NameValueList.java)에 대한 Test class를 생성하였습니다
각각 [NumberUtilsTest](https://github.com/poap/pinpoint/blob/master/bootstrap/src/test/java/com/navercorp/pinpoint/bootstrap/util/StringUtilsTest.java), [StringUtilsTest](https://github.com/poap/pinpoint/blob/master/bootstrap/src/test/java/com/navercorp/pinpoint/bootstrap/util/StringUtilsTest.java), …
> Test of 3 classes

- web/src/main/webapp/features/serverMap/server-map.directive.js
- web/src/main/webapp/features/serverMap/serverMap.html
- web/src/main/webapp/styles/serverMap.css
> Improvement search UI in servermap

- collector/src/main/java/com/navercorp/pinpoint/collector/config/CollectorConfiguration.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/tcp/TCPReceiver.java
- collector/src/main/resources/applicationContext-collector.xml
- collector/src/main/resources/pinpoint-collector.properties
- collector/src/test/java/com/navercorp/pinpoint/collector/receiver/tcp/TCPReceiverTest.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/server/DefaultPinpointServer.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/server/PinpointServerAcceptor.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/server/PinpointServerConfig.java
- rpc/src/test/java/com/navercorp/pinpoint/rpc/server/EventHandlerTest.java
ChannelStateChangeEventHandlers beans should now be able to be wired into TCPReceiver.
> #84 refactored to allow wiring of ChannelStateChangeEvent handlers

- collector/src/main/java/com/navercorp/pinpoint/collector/monitor/CollectorMetric.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/udp/BaseUDPHandlerFactory.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/udp/ChunkedUDPPacketHandlerFactory.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/udp/L4PacketFilter.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/udp/NetworkAvailabilityCheckPacketFilter.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/udp/SpanStreamUDPPacketHandlerFactory.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/udp/TBaseFilter.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/udp/TBaseFilterChain.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/udp/UDPReceiver.java
- collector/src/main/java/com/navercorp/pinpoint/collector/util/CollectorUtils.java
- collector/src/main/java/com/navercorp/pinpoint/collector/util/LoggerUtils.java
- collector/src/main/resources/applicationContext-collector.xml
- collector/src/main/resources/log4j.xml
- collector/src/test/java/com/navercorp/pinpoint/collector/receiver/udp/NetworkAvailabilityCheckPacketFilterTest.java
- collector/src/test/java/com/navercorp/pinpoint/collector/receiver/udp/UDPReceiverTest.java
- collector/src/test/java/com/navercorp/pinpoint/collector/util/LoggerUtilsTest.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/util/RuntimeMXBeanUtils.java
- UDPReceiver
- extract L4CheckFilter, NetworkAvailabilityCheckPacketFilter
> Udpreceiver refactoring

- web/src/main/webapp/common/help/help-content-en.js
- web/src/main/webapp/common/help/help-content-ko.js
- web/src/main/webapp/features/scatter/jquery.BigScatterChart.js
- web/src/main/webapp/styles/main.css
> Change tooltip style

- commons/src/main/java/com/navercorp/pinpoint/common/util/ApplicationMapStatisticsUtils.java
- web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseApplicationIndexDao.java
- web/src/main/java/com/navercorp/pinpoint/web/mapper/ApplicationNameMapper.java
- web/src/main/java/com/navercorp/pinpoint/web/mapper/MapStatisticsCalleeMapper.java
> Fix issues when applications have the same name but different service types

- agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/asynchronous/ThriftHalfSyncHalfAsyncServerAsyncIT.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/asynchronous/ThriftNonblockingServerAsyncIT.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/asynchronous/ThriftThreadedSelectorServerAsyncIT.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/synchronous/ThriftHalfSyncHalfAsyncServerIT.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/synchronous/ThriftNonblockingServerIT.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/synchronous/ThriftSimpleServerIT.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/synchronous/ThriftThreadPoolServerIT.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/synchronous/ThriftThreadedSelectorServerIT.java
- plugins/thrift/pom.xml
- plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/ThriftUtils.java
Removed apache commons-lang3 dependency, which is removed from libthrift 0.9.2+
should fix #623
> removed commons-lang3 dependency

- commons/src/test/java/com/navercorp/pinpoint/common/BytesUtilTest.java
- profiler/src/main/java/com/navercorp/pinpoint/test/TestArrayUtil.java
- profiler/src/main/java/com/navercorp/pinpoint/test/TestQueryString.java
common/util/BytesUtil (some method did not covered)
profiler/util/ArrayUtil
profiler/util/QueryStringUtil
> Test for 3 modules

- collector/pom.xml
- commons/pom.xml
- pom.xml
- thrift/pom.xml
- web/pom.xml
> #645 thrift versionup

- pom.xml
- javaassit update 3.18.0-GA -> 3.19.0-GA
> #644 jdk8 support

- web/src/main/webapp/features/serverMap/jquery.ServerMap2.js
- web/src/main/webapp/features/timeline/timeline.directive.js
- web/src/main/webapp/features/timeline/timeline.html
- web/src/main/webapp/pages/transactionDetail/transaction-detail.controller.js
- web/src/main/webapp/pages/transactionDetail/transactionDetail.html
add infinite circular scroll
#672
> Improvement timeline UI

- web/src/main/webapp/components/infiniteCircularScroll/InfiniteCircularScroll.js
- web/src/main/webapp/features/distributedCallFlow/distributed-call-flow.directive.js
- web/src/main/webapp/features/timeline/timeline.directive.js
- web/src/main/webapp/index.html
- web/src/main/webapp/pages/transactionDetail/transaction-detail.controller.js
- web/src/main/webapp/pages/transactionDetail/transactionDetail.html
Infinite circular scroll bug fix.
Add timeline self execution time search field
#673
> Change timeline ui to infinite circular scroll

- web/src/main/webapp/components/infiniteCircularScroll/InfiniteCircularScroll.js
- web/src/main/webapp/features/timeline/timeline.directive.js
timeline click event bug fix.
#673
> Infinite circular scroll performance improvements.

- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/context/RecordableTrace.java
- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/context/TraceContext.java
- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/context/TraceType.java
- bootstrap/src/test/java/com/navercorp/pinpoint/bootstrap/interceptor/MockTrace.java
- bootstrap/src/test/java/com/navercorp/pinpoint/bootstrap/interceptor/MockTraceContext.java
- plugins/user/src/main/java/com/navercorp/pinpoint/plugin/user/interceptor/UserIncludeMethodInterceptor.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/AsyncTrace.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTrace.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTraceContext.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DisableTrace.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/MetricTrace.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/ThreadLocalTraceFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/TraceFactory.java
- test/src/main/java/com/navercorp/pinpoint/test/mock/MockTraceContext.java
> Fix User include close condition

- web/src/main/webapp/features/navbar/navbar.directive.js
Use select box instead of slider
> Change DateTimePicker component option in Navigation Bar

- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTrace.java
> fix return TraceType.DEFAULT.

- agent/pom.xml
- bootstrap-core/pom.xml
- bootstrap/pom.xml
- collector/pom.xml
- commons-hbase/pom.xml
- commons/pom.xml
- commons/src/main/java/com/navercorp/pinpoint/common/Version.java
- pom.xml
- profiler-optional/pom.xml
- profiler/pom.xml
- quickstart/conf/quickstart.properties
- rpc/pom.xml
- thrift/pom.xml
- thrift/src/main/java/com/navercorp/pinpoint/thrift/io/TCommandTypeVersion.java
- web/pom.xml
changed version. (1.1.0 -> 1.1.1-SNAPSHOT)
> 1.1.0 release #692

- web/src/main/webapp/features/transactionTable/transactionTable.html
- web/src/main/webapp/index.html
- web/src/main/webapp/pages/transactionDetail/transaction-detail.controller.js
- web/src/main/webapp/pages/transactionDetail/transactionDetail.html
> improvement logic for logging button

- web/src/main/webapp/index.html
- web/src/main/webapp/pages/transactionDetail/transaction-detail.controller.js
> add alert message when click disabled button

- agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/TestEnvironment.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/client/AsyncEchoTestClient.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/client/SyncEchoTestClient.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/common/server/AsyncEchoTestServer.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/EchoTestRunner.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/asynchronous/ThriftHalfSyncHalfAsyncServerAsyncIT.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/asynchronous/ThriftNonblockingServerAsyncIT.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/asynchronous/ThriftThreadedSelectorServerAsyncIT.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/synchronous/ThriftHalfSyncHalfAsyncServerIT.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/synchronous/ThriftNonblockingServerIT.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/synchronous/ThriftSimpleServerIT.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/synchronous/ThriftThreadPoolServerIT.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/thrift/it/synchronous/ThriftThreadedSelectorServerIT.java
- plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/interceptor/tprotocol/server/TProtocolReadMessageEndInterceptor.java
* Fix an issue where Thrift Processors would generate an extra span event
* Add integration tests for asynchronous client calls
> Fix extra span event generation and add tests

- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/CallStack.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTrace.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTraceId.java
> Trace.close() 

- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/config/ProfilerConfig.java
> add to property is profiler.callstack.max.depth.

- profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/db/interceptor/BindValueUtils.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/db/interceptor/PreparedStatementExecuteQueryInterceptor.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/modifier/db/interceptor/BindValueUtilsTest.java
> #740 backport. bindValue array index bug fix.

- agent/src/main/resources/pinpoint.config
- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/config/ProfilerConfig.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/CallStack.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultSpanRecorder.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTrace.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/Span.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/SpanEvent.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/CallStackTest.java
> add callstack.maxDepth.

- web/src/main/java/com/navercorp/pinpoint/web/applicationmap/ApplicationMapBuilder.java
- web/src/main/java/com/navercorp/pinpoint/web/applicationmap/Node.java
- web/src/main/java/com/navercorp/pinpoint/web/applicationmap/ServerBuilder.java
- web/src/main/java/com/navercorp/pinpoint/web/applicationmap/ServerInstanceList.java
- web/src/main/java/com/navercorp/pinpoint/web/controller/BusinessTransactionController.java
- web/src/main/java/com/navercorp/pinpoint/web/controller/ControllerExceptionHandler.java
- web/src/main/java/com/navercorp/pinpoint/web/view/LinkSerializer.java
- web/src/test/java/com/navercorp/pinpoint/web/applicationmap/ServerInstanceListTest.java
- web/src/test/java/com/navercorp/pinpoint/web/view/ServerInstanceListSerializerTest.java
- added json filed : fromAgent, toAgent
> #732 filter wizard incorrect agent mapping

- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/context/TraceContext.java
- bootstrap/src/test/java/com/navercorp/pinpoint/bootstrap/interceptor/MockTraceContext.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/ActiveTrace.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/ActiveTraceFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/ActiveTraceInfo.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/ActiveTraceLifeCycleEventListener.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/ActiveTraceRepository.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTraceContext.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTraceFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/ThreadLocalTraceRepositoy.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/TraceRepository.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/ThreadLocalTraceFactoryTest.java
> Trace current active requests info. #751

- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/context/TraceContext.java
- bootstrap/src/test/java/com/navercorp/pinpoint/bootstrap/interceptor/MockTraceContext.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/ActiveTraceFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTraceContext.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DisableTrace.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/MetricTraceFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/ThreadLocalTraceFactory.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/ThreadLocalTraceFactoryTest.java
- test/src/main/java/com/navercorp/pinpoint/test/mock/MockTraceContext.java
- extract class stats class (MetricTraceFactory)
> #751  activeThreadInfo refactoring

- pom.xml
- quickstart/testapp/pom.xml
- quickstart/testapp/src/main/resources/servlet-context.xml
upgrade spring version (3.2.3.RELEASE -> 4.1.7.RELEASE)
> pgrade to spring framework 4.1.7 #765

- pom.xml
- quickstart/testapp/pom.xml
- quickstart/testapp/src/main/resources/servlet-context.xml
upgrade spring version (3.2.3.RELEASE -> 4.1.7.RELEASE) for 1.1.x
branch.
> Upgrade to spring framework 4.1.7 #765

- plugins/user/src/main/java/com/navercorp/pinpoint/plugin/user/interceptor/UserIncludeMethodInterceptor.java
> fix bug of UserIncludePlugin.

- agent/src/main/resources/pinpoint-real-env-lowoverhead-sample.config
This is a sample configuration file to be used for real time profiling. Low overhead compared to the default configuration.
> Sample configuration with low overhead for real time.

- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultCachingSqlNormalizer.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/DefaultCachingSqlNormalizerTest.java
> #798 improve sql trace performance

- web/src/main/java/com/navercorp/pinpoint/web/calltree/span/SpanAlign.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/callstacks/RecordFactory.java
> fix SpanEvent Record ApiType(serviceType + destinationId)

- agent/pom.xml
- agent/src/main/resources/pinpoint.config
- agent/src/test/java/com/navercorp/pinpoint/plugin/google/httpclient/HttpRequestIT.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/httpclient3/HttpClientIT.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/httpclient4/CloaeableHttpClientIT.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/httpclient4/HttpClientIT.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/ProfilerConfig.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/http/HttpCallContext.java
- commons/src/main/java/com/navercorp/pinpoint/common/trace/AnnotationKey.java
- commons/src/main/java/com/navercorp/pinpoint/common/util/DefaultDisplayArgument.java
- plugins/httpclient3/src/main/java/com/navercorp/pinpoint/plugin/httpclient3/HttpClient3CallContext.java
- plugins/httpclient3/src/main/java/com/navercorp/pinpoint/plugin/httpclient3/HttpClient3Constants.java
- plugins/httpclient3/src/main/java/com/navercorp/pinpoint/plugin/httpclient3/HttpClient3Plugin.java
- plugins/httpclient3/src/main/java/com/navercorp/pinpoint/plugin/httpclient3/HttpClient3PluginConfig.java
- plugins/httpclient3/src/main/java/com/navercorp/pinpoint/plugin/httpclient3/interceptor/ExecuteInterceptor.java
- plugins/httpclient3/src/main/java/com/navercorp/pinpoint/plugin/httpclient3/interceptor/HttpConnectionOpenMethodInterceptor.java
- plugins/httpclient3/src/main/java/com/navercorp/pinpoint/plugin/httpclient3/interceptor/HttpMethodBaseExecuteMethodInterceptor.java
- plugins/httpclient3/src/main/java/com/navercorp/pinpoint/plugin/httpclient3/interceptor/HttpMethodBaseRequestAndResponseMethodInterceptor.java
- plugins/httpclient3/src/main/java/com/navercorp/pinpoint/plugin/httpclient3/interceptor/RetryMethodInterceptor.java
- plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/HttpClient4Constants.java
- plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/HttpClient4Plugin.java
- plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/DefaultHttpRequestRetryHandlerRetryRequestMethodInterceptor.java
- plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/HttpClientConnectionManagerConnectMethodInterceptor.java
- plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/HttpRequestExecutorDoSendRequestAndDoReceiveResponseMethodInterceptor.java
- plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/HttpRequestExecutorExecuteMethodInterceptor.java
- plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/ManagedClientConnectionOpenMethodInterceptor.java
> fix Httpclient.retry

- web/src/main/java/com/navercorp/pinpoint/web/filter/FilterHint.java
- web/src/main/java/com/navercorp/pinpoint/web/filter/deserializer/RpcHintJsonDeserializer.java
- web/src/test/java/com/navercorp/pinpoint/web/filter/FilterHintTest.java
- bug fix RpcHint : json array is empty
> #818 redesign memory-based span filter algorithm

- web/src/main/webapp/common/services/alarm-ajax.service.js
- web/src/main/webapp/features/configuration/alarm/alarm-group-member.controller.js
- web/src/main/webapp/features/configuration/alarm/alarm-pinpoint-user.controller.js
- web/src/main/webapp/features/configuration/alarm/alarm-rule.controller.js
- web/src/main/webapp/features/configuration/alarm/alarm-user-group.controller.js
- web/src/main/webapp/features/configuration/configuration.controller.js
- web/src/main/webapp/features/configuration/general/general.controller.js
- web/src/main/webapp/features/navbar/navbar.directive.js
- web/src/main/webapp/features/navbar/navbar.html
- web/src/main/webapp/features/serverMap/server-map.directive.js
- web/src/main/webapp/index.html
- web/src/main/webapp/styles/configuration.css
- web/src/main/webapp/styles/timer.css
Complete basic implementation of alarm UI.
#762
> Add alarm UI

- web/src/main/webapp/features/configuration/alarm/alarm-rule.controller.js
> modify alarm rule filter

- plugins/jackson/src/main/java/com/navercorp/pinpoint/plugin/jackson/JacksonPlugin.java
changed to skip transformation when class does not have target constructor or method.
> Modified jackson plugin to use new plugin api.

- plugins/json-lib/src/main/java/com/navercorp/pinpoint/plugin/json_lib/JsonLibPlugin.java
changed to skip transformation when class does not have target constructor or method.
> Modified json-lib plugin to use new plugin api.

- web/src/main/webapp/common/services/alarm-util.service.js
- web/src/main/webapp/features/configuration/alarm/alarm-group-member.directive.js
- web/src/main/webapp/features/configuration/alarm/alarm-pinpoint-user.directive.js
- web/src/main/webapp/features/configuration/alarm/alarm-rule.directive.js
- web/src/main/webapp/features/configuration/alarm/alarm-user-group.directive.js
- web/src/main/webapp/features/configuration/alarm/alarmPinpointUser.html
- web/src/main/webapp/features/configuration/configuration.controller.js
- web/src/main/webapp/features/navbar/navbar.html
- web/src/main/webapp/scripts/extra/event-analytics.js
> Add analytics code.

- web/src/main/java/com/navercorp/pinpoint/web/alarm/CheckerCategory.java
- web/src/main/java/com/navercorp/pinpoint/web/controller/AlarmController.java
- web/src/main/java/com/navercorp/pinpoint/web/controller/UserController.java
- web/src/main/java/com/navercorp/pinpoint/web/controller/UserGroupController.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/User.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/UserGroupMember.java
- web/src/main/resources/mapper/UserMapper.xml
- web/src/main/resources/sql/CreateTableStatement.sql
- web/src/test/java/com/navercorp/pinpoint/web/controller/UserControllerTest.java
And create PK column(auto increment) All table
> [#762] standardize the error message format when exception occured.

- web/src/main/resources/mapper/UserGroupMapper.xml
- web/src/main/resources/mapper/UserMapper.xml
- web/src/main/resources/sql/CreateTableStatement.sql
> [#762] edit user table name because 'user' string is usually used

- .travis.yml
added JAVA_8_HOME environment variable.
> [no issue] travis

- profiler/src/main/java/com/navercorp/pinpoint/profiler/monitor/codahale/cpu/CpuLoadCollector.java
> Add NaN check when retrieving cpu load

- commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/RowReducer.java
- web/src/main/java/com/navercorp/pinpoint/web/applicationmap/rawdata/LinkCallData.java
- web/src/main/java/com/navercorp/pinpoint/web/applicationmap/rawdata/LinkCallDataMap.java
- web/src/main/java/com/navercorp/pinpoint/web/applicationmap/rawdata/LinkData.java
- web/src/main/java/com/navercorp/pinpoint/web/applicationmap/rawdata/LinkDataMap.java
- web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseMapStatisticsCalleeDao.java
- web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseMapStatisticsCallerDao.java
- web/src/main/java/com/navercorp/pinpoint/web/mapper/MapStatisticsTimeWindowReducer.java
- web/src/main/java/com/navercorp/pinpoint/web/mapper/RowMapReduceResultExtractor.java
- web/src/main/java/com/navercorp/pinpoint/web/service/BFSLinkSelector.java
- web/src/main/java/com/navercorp/pinpoint/web/service/DFSLinkSelector.java
- web/src/test/java/com/navercorp/pinpoint/web/alarm/checker/ErrorCountToCalleCheckerTest.java
- web/src/test/java/com/navercorp/pinpoint/web/alarm/checker/ErrorRateToCalleCheckerTest.java
- web/src/test/java/com/navercorp/pinpoint/web/alarm/checker/SlowCountToCalleCheckerTest.java
- web/src/test/java/com/navercorp/pinpoint/web/alarm/checker/SlowRateToCalleCheckerTest.java
- web/src/test/java/com/navercorp/pinpoint/web/alarm/checker/TotalCountToCalleCheckerTest.java
- web/src/test/java/com/navercorp/pinpoint/web/applicationmap/rawdata/LinkCallDataTest.java
> Apply TimeWindow of TimeHistogram,

- web/src/main/resources/applicationContext-web.xml
> [#762] comment batch configuration file because we need to add batch

- web/src/main/java/com/navercorp/pinpoint/web/controller/ScatterChartController.java
> apply scatterChart format of version 3.

- doc/alarm.md
Add English documentation regarding #762
> Add English alarm guide

- web/src/main/webapp/common/services/alarm-broadcast.service.js
- web/src/main/webapp/features/configuration/alarm/alarm-group-member.directive.js
- web/src/main/webapp/features/configuration/alarm/alarm-pinpoint-user.directive.js
- web/src/main/webapp/features/configuration/alarm/alarm-user-group.directive.js
> Load information in advance when a user does have authority

- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/resolver/condition/MainClassCondition.java
> Allow main class detection for all valid executables

- agent/pom.xml
- agent/src/main/resources/pinpoint.config
- agent/src/test/java/com/navercorp/pinpoint/plugin/okhttp/OkHttpClientIT.java
- plugins/okhttp/.gitignore
- plugins/okhttp/clover.license
- plugins/okhttp/pom.xml
- plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/ConnectionGetter.java
- plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/HttpUrlGetter.java
- plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/OkHttpConstants.java
- plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/OkHttpPlugin.java
- plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/OkHttpPluginConfig.java
- plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/OkHttpTypeProvider.java
- plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/UserRequestGetter.java
- plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/UserRequestSetter.java
- plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/UserResponseGetter.java
- plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/interceptor/AsyncCallExecuteMethodInterceptor.java
- plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/interceptor/CallMethodInterceptor.java
- plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/interceptor/DispatcherEnqueueMethodInterceptor.java
- plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/interceptor/HttpEngineConnectMethodInterceptor.java
- plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/interceptor/HttpEngineReadResponseMethodInterceptor.java
- plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/interceptor/HttpEngineSendRequestMethodInterceptor.java
- plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/interceptor/RequestBuilderBuildMethodInterceptor.java
- plugins/pom.xml
- pom.xml
> Ok httpclient

- plugins/okhttp/src/main/resources/META-INF/services/com.navercorp.pinpoint.bootstrap.plugin.ProfilerPlugin
- plugins/okhttp/src/main/resources/META-INF/services/com.navercorp.pinpoint.common.trace.TraceMetadataProvider
> add type properties.

- plugins/httpclient3/src/main/java/com/navercorp/pinpoint/plugin/httpclient3/interceptor/HttpMethodBaseExecuteMethodInterceptor.java
- plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/DefaultClientExchangeHandlerImplStartMethodInterceptor.java
- plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/HttpRequestExecutorExecuteMethodInterceptor.java
- plugins/jdk-http/src/main/java/com/navercorp/pinpoint/plugin/jdk/http/interceptor/HttpURLConnectionInterceptor.java
- plugins/ning-asynchttpclient/src/main/java/com/navercorp/pinpoint/plugin/ning/asynchttpclient/interceptor/ExecuteRequestInterceptor.java
> Adds port number to "Pinpoint-Host" header when http clients make a rpc call.

- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/config/ExcludeMethodFilter.java
- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/config/ProfilerConfig.java
- bootstrap/src/test/java/com/navercorp/pinpoint/bootstrap/config/ExcludeMethodFilterTest.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/servlet/interceptor/HttpServletInterceptor.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/tomcat/interceptor/StandardHostValveInvokeInterceptor.java
- profiler/src/test/resources/pinpoint.config
> backport #978 The tomcat parameter provides an option for the profile.

- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/config/ExcludeMethodFilter.java
- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/config/ExcludeUrlFilter.java
- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/util/StringUtils.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/util/StringUtilsTest.java
add StringUtils.isEmpty()
add StringUtils.splitAndTrim()
> #977 extract duplicated code

- collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseMapResponseTimeDao.java
- collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseMapStatisticsCalleeDao.java
- collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseMapStatisticsCallerDao.java
- collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/statistics/RowKeyMerge.java
- collector/src/main/resources/applicationContext-hbase.xml
- web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseMapStatisticsCalleeDao.java
- web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseMapStatisticsCallerDao.java
- web/src/main/java/com/navercorp/pinpoint/web/mapper/MapStatisticsCalleeMapperBackwardCompatibility.java
- web/src/main/java/com/navercorp/pinpoint/web/mapper/MapStatisticsCallerMapperBackwardCompatibility.java
- web/src/main/resources/applicationContext-hbase.xml
> Hbase linkdata distribution

- plugins/arcus/src/main/java/com/navercorp/pinpoint/plugin/arcus/ArcusConstants.java
- plugins/arcus/src/main/java/com/navercorp/pinpoint/plugin/arcus/ArcusPlugin.java
- plugins/arcus/src/main/java/com/navercorp/pinpoint/plugin/arcus/ArcusTypeProvider.java
- plugins/arcus/src/main/java/com/navercorp/pinpoint/plugin/arcus/CacheKeyAccessor.java
- plugins/arcus/src/main/java/com/navercorp/pinpoint/plugin/arcus/CacheNameAccessor.java
- plugins/arcus/src/main/java/com/navercorp/pinpoint/plugin/arcus/OperationAccessor.java
- plugins/arcus/src/main/java/com/navercorp/pinpoint/plugin/arcus/ServiceCodeAccessor.java
- plugins/arcus/src/main/java/com/navercorp/pinpoint/plugin/arcus/interceptor/ApiInterceptor.java
- plugins/arcus/src/main/java/com/navercorp/pinpoint/plugin/arcus/interceptor/CacheManagerConstructInterceptor.java
- plugins/arcus/src/main/java/com/navercorp/pinpoint/plugin/arcus/interceptor/FrontCacheGetFutureConstructInterceptor.java
- plugins/arcus/src/main/java/com/navercorp/pinpoint/plugin/arcus/interceptor/FrontCacheGetFutureGetInterceptor.java
- plugins/arcus/src/main/java/com/navercorp/pinpoint/plugin/arcus/interceptor/FutureGetInterceptor.java
- plugins/arcus/src/main/java/com/navercorp/pinpoint/plugin/arcus/interceptor/FutureInternalMethodInterceptor.java
- plugins/arcus/src/main/java/com/navercorp/pinpoint/plugin/arcus/interceptor/FutureSetOperationInterceptor.java
- plugins/arcus/src/main/java/com/navercorp/pinpoint/plugin/arcus/interceptor/SetCacheManagerInterceptor.java
remove interface constants type
> remove interface constants

- web/src/main/webapp/features/realtimeChart/realtime-chart.directive.js
- web/src/main/webapp/pages/main/main.html
> Update realtime active thread chart css

- commons/src/main/java/com/navercorp/pinpoint/common/trace/AnnotationKey.java
- web/src/main/webapp/components/bootstrap-datepicker/tests/assets/qunit.js
- web/src/main/webapp/components/bootstrap-timepicker/spec/js/libs/bootstrap/js/tests/vendor/qunit.js
- web/src/main/webapp/components/bootstrap/js/tests/vendor/qunit.js
- web/src/main/webapp/components/slickgrid/lib/qunit.js
annotaion -> annotation
Have a good weekend.
> Fix typos in comments

- profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/connector/asynchttpclient/interceptor/ExecuteRequestInterceptor.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/connector/httpclient3/interceptor/ExecuteInterceptor.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/connector/httpclient4/interceptor/AbstractHttpRequestExecute.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/connector/httpclient4/interceptor/AbstractHttpRequestExecuteWithDivergence.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/connector/jdkhttpconnector/interceptor/ConnectMethodInterceptor.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/tomcat/interceptor/StandardHostValveInvokeInterceptor.java
> #1015 Add "Pinpoint-Host" header to HttpClients and Tomcat acceptor.

- web/src/main/java/com/navercorp/pinpoint/web/applicationmap/ServerInstance.java
- web/src/main/java/com/navercorp/pinpoint/web/applicationmap/ServerInstanceList.java
> Remove serialization of AgentInfoBo when creating ServerInstance

- plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/DefaultClientExchangeHandlerImplStartMethodInterceptor.java
- plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/HttpClientConnectionManagerConnectMethodInterceptor.java
- plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/HttpRequestExecutorExecuteMethodInterceptor.java
- plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/ManagedClientConnectionOpenMethodInterceptor.java
> Httpclient4 connect host patch

- plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/interceptor/HttpEngineSendRequestMethodInterceptor.java
- plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/interceptor/RequestBuilderBuildMethodInterceptor.java
> Okhttp host patch

- agent/src/test/java/com/navercorp/pinpoint/plugin/httpclient4/HttpClientIT.java
> fix testcase.

- collector/src/main/java/com/navercorp/pinpoint/collector/cluster/route/StreamRouteHandler.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/PinpointSocket.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/client/DefaultPinpointClientHandler.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/client/PinpointClient.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/client/PinpointClientHandler.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/client/PinpointClientHandlerContext.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/client/PinpointClientHandlerState.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/client/ReconnectStateClientHandler.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/common/SocketState.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/server/DefaultPinpointServer.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/server/DefaultPinpointServerState.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/server/PinpointServer.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/LoggingStreamChannelStateChangeEventHandler.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/StreamChannel.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/StreamChannelManager.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/StreamChannelState.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/StreamChannelStateChangeEventHandler.java
- rpc/src/test/java/com/navercorp/pinpoint/rpc/stream/StreamChannelManagerTest.java
- rpc/src/test/java/com/navercorp/pinpoint/rpc/stream/StreamChannelStateTest.java
- rpc/src/test/java/com/navercorp/pinpoint/rpc/stream/StreamChannelTest.java
- web/src/main/java/com/navercorp/pinpoint/web/service/AgentService.java
- web/src/main/java/com/navercorp/pinpoint/web/service/AgentServiceImpl.java
supported  openStream api for AgentService class and PinpointSocket class.
> Implement realtime span delivery service. #560

- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/interceptor/InvokeAfterCodeGenerator.java
- fix testcase fail
- modify after() bytecode generation
> change method signature

- plugins/httpclient3/src/main/java/com/navercorp/pinpoint/plugin/httpclient3/HttpClient3CallContextFactory.java
- plugins/httpclient3/src/main/java/com/navercorp/pinpoint/plugin/httpclient3/interceptor/HttpMethodBaseExecuteMethodInterceptor.java
- plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/HttpCallContext.java
- plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/HttpCallContextFactory.java
- plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/AbstractHttpClientExecuteMethodInterceptor.java
- plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/HttpClientExecuteMethodInternalInterceptor.java
- plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/HttpRequestExecutorDoSendRequestAndDoReceiveResponseMethodInterceptor.java
- plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/HttpRequestExecutorExecuteMethodInterceptor.java
- plugins/redis/src/main/java/com/navercorp/pinpoint/plugin/redis/CommandContextFactory.java
- plugins/redis/src/main/java/com/navercorp/pinpoint/plugin/redis/interceptor/JedisMethodInterceptor.java
- plugins/redis/src/main/java/com/navercorp/pinpoint/plugin/redis/interceptor/JedisPipelineMethodInterceptor.java
> code clean up

- web/src/main/webapp/common/services/navbar-vo.service.js
- web/src/main/webapp/common/services/preference.service.js
- web/src/main/webapp/common/services/server-map-dao.service.js
- web/src/main/webapp/features/navbar/navbar.directive.js
- web/src/main/webapp/features/realtimeChart/realtime-chart.controller.js
- web/src/main/webapp/features/realtimeChart/realtime-chart.directive.js
- web/src/main/webapp/index.html
- web/src/main/webapp/pages/main/main.html
- web/src/main/webapp/pages/scatterFullScreenMode/scatter-full-screen-mode.controller.js
- web/src/main/webapp/styles/main.css
Working Preference feature.
Modify scatter full screen mode bug.
- do not work dragging
> Working realtime chart UI.

- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/instrument/InstrumentClass.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/instrument/InstrumentMethod.java
- plugins/cubrid-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/cubrid/CubridPlugin.java
- plugins/gson/src/main/java/com/navercorp/pinpoint/plugin/gson/GsonPlugin.java
- plugins/ibatis/src/main/java/com/navercorp/pinpoint/plugin/ibatis/IBatisPlugin.java
- plugins/jackson/src/main/java/com/navercorp/pinpoint/plugin/jackson/JacksonPlugin.java
- plugins/json-lib/src/main/java/com/navercorp/pinpoint/plugin/json_lib/JsonLibPlugin.java
- plugins/jtds/src/main/java/com/navercorp/pinpoint/plugin/jdbc/jtds/JtdsPlugin.java
- plugins/mybatis/src/main/java/com/navercorp/pinpoint/plugin/mybatis/MyBatisPlugin.java
- plugins/mysql-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/mysql/MySqlPlugin.java
- plugins/oracle-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/oracle/OraclePlugin.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/JavassistClass.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/JavassistMethod.java
refactoring InstrumentClass, InstrumentMethod
> #117 refactoring plugin api

- web/src/main/java/com/navercorp/pinpoint/web/controller/ScatterChartController.java
Add average, min, max data for ScatterChart.
> Diff agent

- web/src/main/webapp/common/services/preference.service.js
- web/src/main/webapp/features/configuration/alarm/alarm-user-group.directive.js
- web/src/main/webapp/features/navbar/navbar.directive.js
- web/src/main/webapp/features/realtimeChart/realtime-chart.controller.js
- web/src/main/webapp/features/realtimeChart/realtime-chart.directive.js
- web/src/main/webapp/pages/main/main.html
- web/src/main/webapp/pages/transactionDetail/transaction-detail.controller.js
- web/src/main/webapp/styles/main.css
Support Windows/Chrome bug	
Add grid ui to realtime chart
Add period to perference
> Add feature and fix bug

- web/src/main/webapp/features/realtimeChart/realtime-chart.controller.js
- web/src/main/webapp/features/realtimeChart/realtime-chart.directive.js
- web/src/main/webapp/styles/main.css
not display connection message.
> fix realtime chart bug.

- web/src/main/java/com/navercorp/pinpoint/web/calltree/span/SpanCallTree.java
- web/src/test/java/com/navercorp/pinpoint/web/calltree/span/CallTreeTest.java
> enhancement of call tree sort.

- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/instrument/GuardInstrumentor.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/instrument/Instrumentor.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/ProfilerPluginSetupContext.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/ClassFileTransformerGuardDelegate.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/DefaultProfilerPluginContext.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/GuardProfilerPluginContext.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/MatchableClassFileTransformerGuardDelegate.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/ProfilerPluginLoader.java
- profiler/src/main/java/com/navercorp/pinpoint/test/MockAgent.java
- profiler/src/main/java/com/navercorp/pinpoint/test/TestClassLoader.java
- ProfilerPluginSetupContext, Instrumentor
> plugin api protection

- web/src/main/webapp/features/nodeInfoDetails/nodeInfoDetails.html
- web/src/main/webapp/features/realtimeChart/realtime-chart.controller.js
- web/src/main/webapp/styles/serverMap.css
> update websocket data format.

- agent/src/main/resources/pinpoint.config
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/InterceptorInvokerHelper.java
- plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/HttpRequestExecutorExecuteMethodInterceptor.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/JavassistMethod.java
- web/src/main/java/com/navercorp/pinpoint/web/controller/AlarmController.java
- web/src/main/java/com/navercorp/pinpoint/web/controller/UserController.java
- web/src/main/java/com/navercorp/pinpoint/web/controller/UserGroupController.java
- web/src/main/webapp/features/navbar/navbar.directive.js
just fixing typos in Comments and Log messages
> just fixing typos in Comments and Log messages

- web/src/main/webapp/features/linkInfoDetails/linkInfoDetails.html
- web/src/main/webapp/features/navbar/navbar.html
- web/src/main/webapp/features/realtimeChart/realtime-chart.controller.js
- web/src/main/webapp/features/realtimeChart/realtime-chart.directive.js
- web/src/main/webapp/styles/navbar.css
- web/src/main/webapp/styles/serverMap.css
> update realtime ui and text.

- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTransactionCounter.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/IdGenerator.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/DefaultTransactionCounterTest.java
> Change how internal trace ids are generated

- web/src/main/webapp/common/help/help-content-en.js
- web/src/main/webapp/common/help/help-content-ko.js
- web/src/main/webapp/common/services/agent-dao.service.js
- web/src/main/webapp/features/agentInfo/agent-info.directive.js
- web/src/main/webapp/features/agentInfo/agentInfoMain.html
- web/src/main/webapp/features/tpsChart/tps-chart.directive.js
- web/src/main/webapp/index.html
> Add TPS chart to Inspector View

- web/src/main/webapp/features/configuration/general/general.controller.js
- web/src/main/webapp/features/realtimeChart/realtime-chart.controller.js
- web/src/main/webapp/features/realtimeChart/realtime-chart.directive.js
- web/src/main/webapp/features/serverMap/serverMap.html
- web/src/main/webapp/styles/serverMap.css
display message when comes 10 times in a row timeout response
> change realtime error message color.

- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/JavassistMethod.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/interceptor/DefaultInterceptorDefinition.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/interceptor/InterceptorDefinition.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/interceptor/InterceptorDefinitionFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/interceptor/InvokeAfterCodeGenerator.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/interceptor/InvokeBeforeCodeGenerator.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/interceptor/InvokeCodeGenerator.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/interceptor/InterceptorDefinitionFactoryTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/interceptor/InvokeAfterCodeGeneratorTest.java
> refactoring plugin api

- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/DefaultProfilerConfig.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/ProfilerConfig.java
- bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/config/ProfilerConfigTest.java
- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/PinpointStarter.java
- bootstrap/src/test/java/com/navercorp/pinpoint/bootstrap/AgentClassLoaderTest.java
- plugins/spring/src/test/java/com/navercorp/pinpoint/plugin/spring/beans/interceptor/TargetBeanFilterTest.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/tools/NetworkAvailabilityChecker.java
- profiler/src/main/java/com/navercorp/pinpoint/test/MockAgent.java
- profiler/src/main/java/com/navercorp/pinpoint/test/MockTraceContextFactory.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/interceptor/bci/JavassistClassTest.java
- test/src/main/java/com/navercorp/pinpoint/test/mock/MockTraceContext.java
- extract interface from ProfilerConfig
> extract interface

- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/ObjectFactory.java
- plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/OkHttpPlugin.java
- plugins/spring/src/main/java/com/navercorp/pinpoint/plugin/spring/beans/SpringBeansPlugin.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/JavassistClass.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/interceptor/factory/AnnotatedInterceptorFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/objectfactory/AutoBindingObjectFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/objectfactory/OrderedValueProvider.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/xml/interceptor/TargetAnnotatedInterceptorInjector.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/plugin/AnnotatedInterceptorFactoryTest.java
- ObjectRecipe-> ObjectFactory
> refactoring

- profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/arcus/interceptor/ApiInterceptor.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/modifier/arcus/interceptor/FutureGetInterceptor.java
- modify dns lookup api
InetSocketAddress.getHostName() -> InetAddress.getHostAddress()
> #1171 Fixed a side effect of Arcus interceptor

- plugins/arcus/src/main/java/com/navercorp/pinpoint/plugin/arcus/interceptor/ApiInterceptor.java
- plugins/arcus/src/main/java/com/navercorp/pinpoint/plugin/arcus/interceptor/FutureGetInterceptor.java
- modify dns lookup api
InetSocketAddress.getHostName() -> InetAddress.getHostAddress()
#1171 porting
> #1174 Fixed a side effect of Arcus interceptor

- web/src/main/java/com/navercorp/pinpoint/web/controller/AdminController.java
- web/src/main/java/com/navercorp/pinpoint/web/controller/AgentStatController.java
- web/src/main/java/com/navercorp/pinpoint/web/service/AdminService.java
- web/src/main/java/com/navercorp/pinpoint/web/service/AdminServiceImpl.java
- web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoService.java
- web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoServiceImpl.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/ApplicationAgentList.java
Add API for querying agent information for various uses such as grouping them by agent version in Web UI.
> Add API for querying AgentInfo

- plugins/arcus/src/main/java/com/navercorp/pinpoint/plugin/arcus/ArcusPlugin.java
- plugins/google-httpclient/src/main/java/com/navercorp/pinpoint/plugin/google/httpclient/HttpClientConstants.java
- plugins/google-httpclient/src/main/java/com/navercorp/pinpoint/plugin/google/httpclient/interceptor/HttpRequestExecuteAsyncMethodInnerClassConstructorInterceptor.java
- plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/TomcatConstants.java
- plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/TomcatPlugin.java
- plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/interceptor/RequestStartAsyncInterceptor.java
Fix AsyncTraceIdAccessor class name.
> Fix tomcat asynchronous processor

- web/src/main/webapp/stat.html
bug fix of array sort in safari.
> update statistic page.

- web/src/main/java/com/navercorp/pinpoint/web/controller/AdminController.java
- web/src/main/java/com/navercorp/pinpoint/web/controller/AgentStatController.java
- web/src/main/java/com/navercorp/pinpoint/web/service/AdminService.java
- web/src/main/java/com/navercorp/pinpoint/web/service/AdminServiceImpl.java
- web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoService.java
- web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoServiceImpl.java
Makes AgentInfo query API public.
> Move AgentInfo query API out of AdminController

- web/src/main/webapp/features/navbar/navbar.directive.js
- web/src/main/webapp/features/realtimeChart/realtime-chart.controller.js
- web/src/main/webapp/features/realtimeChart/realtime-chart.directive.js
Set focus to application name selectbox when load page without application name.
> Add minimum y axis value to realtime chart.

- web/src/main/webapp/common/help/help-content-en.js
- web/src/main/webapp/common/help/help-content-ko.js
- web/src/main/webapp/features/configuration/general/general.controller.js
- web/src/main/webapp/index.html
- web/src/main/webapp/styles/configuration.css
- User configuration is stored in browser cache. Server-side storage will be supported in a future release.
> Add guide message in general configuration.

- web/src/main/java/org/apache/hadoop/util/ShutdownHookManagerProxy.java
- web/src/test/java/com/navercorp/pinpoint/web/alarm/MainCategoryTest.java
- web/src/test/java/com/navercorp/pinpoint/web/alarm/ReaderTest.java
- web/src/test/java/com/navercorp/pinpoint/web/applicationmap/rawdata/LinkCallDataTest.java
- web/src/test/java/com/navercorp/pinpoint/web/calltree/span/CallTreeTest.java
- web/src/test/java/com/navercorp/pinpoint/web/cluster/ClusterTest.java
- web/src/test/java/com/navercorp/pinpoint/web/cluster/PinpointRouteResponseTest.java
- web/src/test/java/com/navercorp/pinpoint/web/cluster/zookeeper/ZookeeperClusterTest.java
- web/src/test/java/com/navercorp/pinpoint/web/controller/AlarmControllerTest.java
- web/src/test/java/com/navercorp/pinpoint/web/controller/UserControllerTest.java
- web/src/test/java/com/navercorp/pinpoint/web/filter/FilterHintTest.java
- web/src/test/java/com/navercorp/pinpoint/web/filter/LinkFilterTest.java
- web/src/test/java/com/navercorp/pinpoint/web/mapper/AgentStatMapperTest.java
- web/src/test/java/com/navercorp/pinpoint/web/service/BFSLinkSelectorTest.java
- web/src/test/java/com/navercorp/pinpoint/web/util/DateLimiterTest.java
- web/src/test/java/com/navercorp/pinpoint/web/util/LimitUtilsTest.java
- web/src/test/java/com/navercorp/pinpoint/web/util/TimeWindowTest.java
- web/src/test/java/com/navercorp/pinpoint/web/vo/RangeTest.java
- java 7 style generic
- remove unused import
> code cleanup

- test/src/main/java/com/navercorp/pinpoint/test/plugin/PinpointPluginTestRunListener.java
> fix findbug

- web/src/main/webapp/features/realtimeChart/realtime-chart.controller.js
- web/src/main/webapp/features/serverMap/serverMap.html
- web/src/main/webapp/styles/configuration.css
- can pin realtime chart.
Update favorite list ui.
> Add feature.

- web/src/main/webapp/features/configuration/general/general.controller.js
- web/src/main/webapp/index.html
bug fix.
- double invoke add logic when select favorite application.
> remove "a" tag that has meaningless href attribute.

- plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/HttpClient4Plugin.java
- plugins/spring/src/main/java/com/navercorp/pinpoint/plugin/spring/beans/BeanMethodTransformer.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/DefaultDynamicTransformerRegistry.java
- remove unused local variable
- synchronization warning JLM_JSR166_UTILCONCURRENT_MONITORENTER
- fix NPE
> fix find bug

- web/src/main/webapp/features/realtimeChart/realtime-chart.controller.js
- web/src/main/webapp/features/serverMap/server-map.directive.js
- web/src/main/webapp/features/tpsChart/tps-chart.directive.js
- web/src/main/webapp/index.html
- web/src/main/webapp/styles/configuration.css
bug fix.
- can not change tab in alarm ui.
> Update default pin option.(true)

- collector/src/test/java/com/navercorp/pinpoint/collector/receiver/udp/UDPReceiverTest.java
> Fix compilation error

- web/src/main/java/com/navercorp/pinpoint/web/vo/AgentActiveThreadCountList.java
- web/src/main/java/com/navercorp/pinpoint/web/websocket/ActiveThreadCountResponseAggregator.java
- web/src/test/java/com/navercorp/pinpoint/web/vo/AgentActiveThreadCountListTest.java
hot fix : active thread concurrency issue
> #1244 active thread concurrency issue

- web/src/main/java/com/navercorp/pinpoint/web/websocket/ActiveThreadCountHandler.java
hot fix : active thread concurrency issue
> [PinpiontWeb] fix a ActiveThread concurrency problem #1244

- agent/pom.xml
- bootstrap-core/pom.xml
- bootstrap/pom.xml
- collector/pom.xml
- commons-hbase/pom.xml
- commons/pom.xml
- commons/src/main/java/com/navercorp/pinpoint/common/Version.java
- pom.xml
- profiler-optional/pom.xml
- profiler/pom.xml
- quickstart/conf/quickstart.properties
- rpc/pom.xml
- thrift/pom.xml
- thrift/src/main/java/com/navercorp/pinpoint/thrift/io/TCommandTypeVersion.java
- web/pom.xml
version changed (1.1.2-SNAPSHOT -> 1.1.2)
> 1.1.2 release #1250

- quickstart/conf/quickstart.properties
quickstart.version in quickstart.properties changed. (1.5.0-SNAPSHOT -> 1.5.1-SNAPSHOT)
> 1.5.0 release #1240

- pom.xml
> #1264 spring versionup

- pom.xml
- requireJavaVersion : 1.7
- requireMavenVersion : 3.2
> added build requirements

- pom.xml
> findbugs plugin versionup

- plugins/arcus/src/main/java/com/navercorp/pinpoint/plugin/arcus/interceptor/AddOpInterceptor.java
- plugins/arcus/src/main/java/com/navercorp/pinpoint/plugin/arcus/interceptor/CacheManagerConstructInterceptor.java
- plugins/arcus/src/main/java/com/navercorp/pinpoint/plugin/arcus/interceptor/FrontCacheGetFutureGetInterceptor.java
- plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/DefaultClientExchangeHandlerImplStartMethodInterceptor.java
- plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/HttpRequestExecutorDoSendRequestAndDoReceiveResponseMethodInterceptor.java
- plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/interceptor/ServerHandleInterceptor.java
- plugins/json-lib/src/main/java/com/navercorp/pinpoint/plugin/json_lib/interceptor/ParsingInterceptor.java
- plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/interceptor/RequestBuilderBuildMethodBackwardCompatibilityInterceptor.java
- plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/interceptor/RequestBuilderBuildMethodInterceptor.java
- plugins/postgresql-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/postgresql/interceptor/PostgreSQLConnectionCreateInterceptor.java
- plugins/postgresql-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/postgresql/interceptor/PostgreSqlPreparedStatementCreateInterceptor1.java
- plugins/postgresql-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/postgresql/interceptor/PostgreSqlPreparedStatementCreateInterceptor2.java
- plugins/postgresql-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/postgresql/interceptor/PostgreSqlPreparedStatementCreateInterceptor3.java
- plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/interceptor/ConnectorInitializeInterceptor.java
> #1276 Tighten up type checking of Interceptor

- quickstart/agent/src/main/resources/pinpoint.config
> add profiler.entrypoint

- plugins/spring/src/main/java/com/navercorp/pinpoint/plugin/spring/beans/interceptor/CreateBeanInstanceInterceptor.java
Method caching to improve performance.
> Improve spring plugins performacne. #1292

- plugins/httpclient3/src/main/java/com/navercorp/pinpoint/plugin/httpclient3/interceptor/HttpMethodBaseExecuteMethodInterceptor.java
- plugins/httpclient3/src/main/java/com/navercorp/pinpoint/plugin/httpclient3/interceptor/HttpMethodBaseRequestAndResponseMethodInterceptor.java
- plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/HttpCallContext.java
- plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/AbstractHttpClientExecuteMethodInterceptor.java
- plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/DefaultClientExchangeHandlerImplStartMethodInterceptor.java
- plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/HttpClientConnectionManagerConnectMethodInterceptor.java
- plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/HttpClientExecuteMethodInternalInterceptor.java
- plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/HttpClientExecuteMethodWithHttpRequestInterceptor.java
- plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/HttpClientExecuteMethodWithHttpUriRequestInterceptor.java
- plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/HttpRequestExecutorDoSendRequestAndDoReceiveResponseMethodInterceptor.java
- plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/HttpRequestExecutorExecuteMethodInterceptor.java
- plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/ManagedClientConnectionOpenMethodInterceptor.java
> Null check  HttpClient3 ~ 4 plugn.

- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/LoggingInterceptor.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/registry/DefaultInterceptorRegistryAdaptor.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/registry/EmptyRegistryAdaptor.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/registry/InterceptorRegistry.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/DefaultAgent.java
- profiler/src/main/java/com/navercorp/pinpoint/test/junit4/TestContext.java
> #1298 fix unsafe resource cleanup of profiler

- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/SpanAsyncEventSimpleAroundInterceptor.java
> apply TraceScope.

- agent/src/main/resources/lib/log4j.xml
- quickstart/agent/src/main/resources/lib/log4j.xml
> change log4j fileAppender

- web/src/main/webapp/features/serverMap/server-map.directive.js
- web/src/main/webapp/features/transactionTable/transaction-table.directive.js
- web/src/main/webapp/pages/transactionDetail/transactionDetail.html
- web/src/main/webapp/pages/transactionView/transactionView.html
change transaction completeState glyphicon.
> Remove "Technical Preview" mark

- web/src/test/java/com/navercorp/pinpoint/web/cluster/ClusterTest.java
> Redesign Collector's ZookeeperCluster logic. #1305

- agent/src/test/java/com/navercorp/pinpoint/plugin/httpclient3/HttpClientIT.java
- plugins/httpclient3/src/main/java/com/navercorp/pinpoint/plugin/httpclient3/interceptor/HttpMethodBaseExecuteMethodInterceptor.java
> Fix destination is UnknownHttpClient.

- commons/src/main/java/com/navercorp/pinpoint/common/util/AgentEventType.java
- commons/src/main/java/com/navercorp/pinpoint/common/util/AgentEventTypeCategory.java
- web/src/main/java/com/navercorp/pinpoint/web/service/AgentEventServiceImpl.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/AgentEvent.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/DurationalAgentEvent.java
> Add duration fields to agent start/shutdown events

- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/interceptor/DriverConnectInterceptor.java
- bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/interceptor/DriverConnectInterceptorTest.java
> add testcase

- web/src/main/java/com/navercorp/pinpoint/web/calltree/span/CorruptedSpanAlignFactory.java
- web/src/main/java/com/navercorp/pinpoint/web/calltree/span/CorruptedSpanCallTreeNodeException.java
- web/src/main/java/com/navercorp/pinpoint/web/calltree/span/SpanAligner2.java
- web/src/main/java/com/navercorp/pinpoint/web/calltree/span/SpanCallTree.java
> Add corrupted case for sequence overflow.

- commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/AbstractDistributedScannerTableCallback.java
- commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/DistributedScannerTableCallback.java
- commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseOperations2.java
- commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseTemplate2.java
- commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/ParallelDistributedScannerTableCallback.java
- commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/ParallelResultScanner.java
- web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseApplicationTraceIndexDao.java
- web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseMapResponseTimeDao.java
- web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseMapStatisticsCalleeDao.java
- web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseMapStatisticsCallerDao.java
- web/src/main/resources/applicationContext-hbase.xml
- web/src/main/resources/hbase.properties
This pull request adds a parallel scanner for scanning distributed rows.
Resolves #1362
> Add parallel result scanner

- web/src/main/java/com/navercorp/pinpoint/web/vo/callstacks/RecordFactory.java
> Improve CallTree error

- collector/src/main/java/com/navercorp/pinpoint/collector/manage/ClusterManager.java
- plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/JettyPlugin.java
- plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/interceptor/Jetty8ServerHandleInterceptor.java
- plugins/postgresql-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/postgresql/PostgreSqlConfig.java
- quickstart/testapp/src/main/java/com/navercorp/pinpoint/testapp/service/remote/RemoteService.java
This pull request is focused on resolving occurrences of Sonar rule squid:EmptyStatementUsageCheck - Empty statements should be removed
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=squid:EmptyStatementUsageCheck
Please let me know if you have any questions.
Kirill Vlasov
> Empty statements should be removed

- plugins/user/src/main/java/com/navercorp/pinpoint/plugin/user/UserPlugin.java
> merge entry points class.

- collector/src/main/java/com/navercorp/pinpoint/collector/cluster/zookeeper/PinpointServerRepository.java
- collector/src/main/java/com/navercorp/pinpoint/collector/cluster/zookeeper/ZookeeperJobWorker.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/udp/SpanStreamUDPPacketHandlerFactory.java
- commons/src/main/java/com/navercorp/pinpoint/common/util/DefaultSqlParser.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/service/ActiveThreadCountService.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/CompositeSpanStreamData.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/util/ListUtils.java
- rpc/src/test/java/com/navercorp/pinpoint/rpc/server/HandshakeTest.java
- thrift/src/main/java/com/navercorp/pinpoint/thrift/io/ChunkHeaderBufferedTBaseSerializer.java
- thrift/src/main/java/com/navercorp/pinpoint/thrift/io/TBaseStream.java
- thrift/src/main/java/com/navercorp/pinpoint/thrift/io/TReplaceListProtocol.java
- web/src/main/java/com/navercorp/pinpoint/web/applicationmap/ApplicationMapBuilder.java
- web/src/main/java/com/navercorp/pinpoint/web/calltree/span/SpanAligner2.java
- web/src/main/java/com/navercorp/pinpoint/web/calltree/span/SpanCallTree.java
- web/src/main/java/com/navercorp/pinpoint/web/calltree/span/SpanIdMatcher.java
- web/src/main/java/com/navercorp/pinpoint/web/cluster/ClusterManager.java
- web/src/main/java/com/navercorp/pinpoint/web/cluster/connection/ClusterConnectionManager.java
- web/src/main/java/com/navercorp/pinpoint/web/controller/CommandController.java
- web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseMapResponseTimeDao.java
- web/src/main/java/com/navercorp/pinpoint/web/service/AlarmServiceImpl.java
- web/src/main/java/com/navercorp/pinpoint/web/service/FilteredMapServiceImpl.java
- web/src/main/java/com/navercorp/pinpoint/web/service/ScatterChartServiceImpl.java
- web/src/main/java/com/navercorp/pinpoint/web/service/TransactionInfoServiceImpl.java
- web/src/main/java/com/navercorp/pinpoint/web/websocket/ActiveThreadCountHandler.java
- web/src/main/java/com/navercorp/pinpoint/web/websocket/ActiveThreadCountResponseAggregator.java
- web/src/test/java/com/navercorp/pinpoint/web/util/PinpointWebTestUtils.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1155 - Collection.isEmpty() should be used to test for emptiness
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=squid:S1155
Please let me know if you have any questions.
Kirill Vlasov
> Collection.isEmpty() should be used to test for emptiness

- web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseTraceDao.java
- web/src/main/resources/pinpoint-web.properties
…a large volume of Span Data. #1397
To depend possibility of OOME when selecting TransactionId that with a large volume of Span Data.
> To defend against possible OOME when selecting Transaction Id that with a large volume of Span Data.

- collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseTraceDao.java
- collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/filter/SequenceSpanEventFilter.java
- collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/filter/SpanEventFilter.java
- collector/src/main/resources/applicationContext-collector.xml
- collector/src/main/resources/pinpoint-collector.properties
- collector/src/test/java/com/navercorp/pinpoint/collector/dao/hbase/filter/SequenceSpanEventFilterTest.java
- commons/src/main/java/com/navercorp/pinpoint/common/util/BytesUtils.java
- commons/src/test/java/com/navercorp/pinpoint/common/util/BytesUtilsTest.java
- prevent OOM
- filter too many trace
> add spanevent filter #1396

- web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseHostApplicationMapDao.java
> Apply parallel scan when finding accept applications

- web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoServiceImpl.java
- web/src/main/java/com/navercorp/pinpoint/web/view/AgentInfoSerializer.java
- web/src/main/java/com/navercorp/pinpoint/web/view/ApplicationAgentListSerializer.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/AgentInfo.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/AgentStatus.java
for #1402 - 1. Homogenize /getAgentList, /getAgentInfo responses
> Homogenize AgentInfo JSON serialization

- web/src/main/java/com/navercorp/pinpoint/web/websocket/ActiveThreadCountHandler.java
- web/src/main/java/com/navercorp/pinpoint/web/websocket/ActiveThreadCountResponseAggregator.java
- web/src/main/java/com/navercorp/pinpoint/web/websocket/WorkerActiveManager.java
Improve Realtime Active Thread Chart smoother.
> Improve Realtime Active Thread Chart smoother. #1430

- commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseOperations2.java
- commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseTemplate2.java
- web/src/main/java/com/navercorp/pinpoint/web/dao/AgentInfoDao.java
- web/src/main/java/com/navercorp/pinpoint/web/dao/AgentLifeCycleDao.java
- web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseAgentInfoDao.java
- web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseAgentLifeCycleDao.java
- web/src/main/java/com/navercorp/pinpoint/web/mapper/AgentInfoMapper.java
- web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoServiceImpl.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/AgentInfo.java
- web/src/test/java/com/navercorp/pinpoint/web/dao/hbase/HbaseAgentLifeCycleDaoTest.java
Allows parallel execution for scans that ca be run in parallel. Utilizing this, makes fetching AgentInfos registered under the same application name run in parallel (part of #1432)
ping @emeroad @koo-taejin
> Adds APIs for running multiple scans in parallel

- web/src/main/java/com/navercorp/pinpoint/web/service/AgentEventServiceImpl.java
Fix for cases when agent event list is empty.
> Check for empty list when creating priority queue for agent events

- web/src/main/java/com/navercorp/pinpoint/web/controller/ApplicationController.java
- web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoService.java
- web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoServiceImpl.java
- web/src/main/java/com/navercorp/pinpoint/web/view/ApplicationAgentHostListSerializer.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/ApplicationAgentHostList.java
Add api for getting application's host information
ping @emeroad @Xylus
> Add api for getting application's host information. #1444

- web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoServiceImpl.java
> add null check for querying deleted agent infos

- rpc/src/test/java/com/navercorp/pinpoint/rpc/TestAwaitTaskUtils.java
- rpc/src/test/java/com/navercorp/pinpoint/rpc/TestAwaitUtils.java
- rpc/src/test/java/com/navercorp/pinpoint/rpc/client/ClientMessageListenerTest.java
- rpc/src/test/java/com/navercorp/pinpoint/rpc/client/PinpointClientStateTest.java
- rpc/src/test/java/com/navercorp/pinpoint/rpc/client/ReconnectTest.java
- rpc/src/test/java/com/navercorp/pinpoint/rpc/client/RequestManagerTest.java
- rpc/src/test/java/com/navercorp/pinpoint/rpc/server/PinpointServerStateTest.java
pinpoint rpc test execution times (42.449s -> 21.249s)
ping @jaehong-kim
> Reduce test execution time. #1452

- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/AgentOption.java
- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/DefaultAgentOption.java
- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/PinpointStarter.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/DefaultAgent.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/DefaultDynamicTransformerRegistry.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/JarProfilerPluginClassInjector.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/JavassistClass.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/ClassLoadingChecker.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/ClassNameFilter.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/PinpointProfilerPackageFilter.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/PluginConfig.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/PluginPackageFilter.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/ProfilerPluginLoader.java
- support spring aspectj weaving
ping @lioolli  @jaehong-kim
> fix invalid classLoading

- web/src/main/java/com/navercorp/pinpoint/web/controller/AgentStatController.java
- web/src/main/java/com/navercorp/pinpoint/web/dao/AgentEventDao.java
- web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseAgentEventDao.java
- web/src/main/java/com/navercorp/pinpoint/web/service/AgentEventService.java
- web/src/main/java/com/navercorp/pinpoint/web/service/AgentEventServiceImpl.java
for #1402 - 3. Add exclusion parameter to /getAgentEvents API
`exclude` parameter is optional.
> Add exclude parameters for querying agent events

- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/PinpointStarter.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/JarProfilerPluginClassInjector.java
#1443 fix unused parameter, log level
> #1443 fix invalid classLoading

- web/src/main/java/com/navercorp/pinpoint/web/controller/AdminController.java
- web/src/main/java/com/navercorp/pinpoint/web/service/AdminService.java
- web/src/main/java/com/navercorp/pinpoint/web/service/AdminServiceImpl.java
- web/src/main/java/com/navercorp/pinpoint/web/view/ApplicationSerializer.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/Application.java
Modifies response of admin APIs that return application names to return serialized `Application`, similar to the response of `/applications`.
ping @koo-taejin
> Homogenize JSON serialization for Application

- web/src/main/java/com/navercorp/pinpoint/web/applicationmap/ApplicationMapBuilder.java
- web/src/main/java/com/navercorp/pinpoint/web/dao/AgentLifeCycleDao.java
- web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseAgentLifeCycleDao.java
- web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoService.java
- web/src/main/java/com/navercorp/pinpoint/web/service/AgentInfoServiceImpl.java
- web/src/main/java/com/navercorp/pinpoint/web/service/AgentServiceImpl.java
Removes agent status queries for agents that have call statistics.
Resolves #1469 
ping @koo-taejin @emeroad
> Remove unnecessary agent status queries when drawing the server map

- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/instrument/InstrumentClass.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/JavassistClass.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/SetterAnalyzer.java
> Add addSetter method to InstrumentClass

- rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/LoggingStreamChannelMessageListener.java
- web/src/main/java/com/navercorp/pinpoint/web/websocket/ActiveThreadCountHandler.java
- web/src/main/java/com/navercorp/pinpoint/web/websocket/ActiveThreadCountResponseAggregator.java
1. changed to catched Excpetion Type in to throw WebSocketSession . (IOException -> Exception)
2. changed log level.
> [PinpiontWeb] fix a ActiveThread concurrency problem #1482

- agent/src/main/resources/pinpoint-real-env-lowoverhead-sample.config
- agent/src/main/resources/pinpoint.config
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/DefaultProfilerConfig.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/ProfilerConfig.java
- plugins/spring/src/main/java/com/navercorp/pinpoint/plugin/spring/beans/SpringBeansConfig.java
- plugins/spring/src/main/java/com/navercorp/pinpoint/plugin/spring/beans/SpringBeansTarget.java
- plugins/spring/src/main/java/com/navercorp/pinpoint/plugin/spring/beans/interceptor/TargetBeanFilter.java
- plugins/spring/src/test/java/com/navercorp/pinpoint/plugin/spring/beans/SpringBeansConfigTest.java
- plugins/spring/src/test/java/com/navercorp/pinpoint/plugin/spring/beans/interceptor/TargetBeanFilterTest.java
- quickstart/agent/src/main/resources/pinpoint.config
- quickstart/conf/pinpoint.config
> Add filters for spring beans plugin.

- web/src/main/java/com/navercorp/pinpoint/web/service/BFSLinkSelector.java
> Fix link data emulation when drawing edges

- web/src/main/java/com/navercorp/pinpoint/web/controller/ScatterChartController.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/scatter/ScatterScanResult.java
> add filteredServerMap.

- web/src/main/java/com/navercorp/pinpoint/web/controller/AdminController.java
- web/src/main/java/com/navercorp/pinpoint/web/dao/ApplicationIndexDao.java
- web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseApplicationIndexDao.java
- web/src/main/java/com/navercorp/pinpoint/web/service/AdminService.java
- web/src/main/java/com/navercorp/pinpoint/web/service/AdminServiceImpl.java
- web/src/test/java/com/navercorp/pinpoint/web/alarm/AlarmPartitionerTest.java
- web/src/test/java/com/navercorp/pinpoint/web/alarm/ReaderTest.java
- web/src/test/java/com/navercorp/pinpoint/web/alarm/checker/GcCountCheckerTest.java
- web/src/test/java/com/navercorp/pinpoint/web/alarm/checker/HeapUsageRateCheckerTest.java
- web/src/test/java/com/navercorp/pinpoint/web/alarm/checker/JvmCpuUsageRateCheckerTest.java
Adds API for removing agents that were inactive for more than 30 days (default) from index.
ping @emeroad 
fixes #1462
> Add API for deleting inactive agents

- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/BootstrapClassLoaderHandler.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/JarProfilerPluginClassInjector.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/PlainClassLoaderHandler.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/URLClassLoaderHandler.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/ClassNameFilterChain.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/PinpointProfilerPackageSkipFilter.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/PluginConfig.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/ProfilerPluginLoader.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/JarProfilerPluginClassInjectorTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/plugin/ClassNameFilterChainTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/plugin/PinpointProfilerPackageSkipFilterTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/plugin/PluginPackageFilterTest.java
#1443 
- refactoring api
- add testcase
> Fixed invalid classloading when using the AspectJ + Spring AOP #1443 

- web/src/main/webapp/features/linkInfoDetails/link-info-details.directive.js
- web/src/main/webapp/features/loadChart/load-chart.directive.js
- web/src/main/webapp/features/nodeInfoDetails/node-info-details.directive.js
- web/src/main/webapp/features/responseTimeChart/response-time-chart.directive.js
- web/src/main/webapp/features/scatter/jquery.BigScatterChart.js
- web/src/main/webapp/features/scatter/scatter.directive.js
- web/src/main/webapp/features/serverMap/serverMap.html
- web/src/main/webapp/features/sidebar/title/sidebar-title.directive.js
- web/src/main/webapp/features/sidebar/title/sidebarTitle.html
- web/src/main/webapp/pages/main/main.controller.js
- web/src/main/webapp/scripts/app.js
modify scatter chart and response summary chart and load chart when change agent option.
add comma at success value in scatter chart.
remove not used config.
change default view option of server map search.
> update some feature.

- web/src/main/webapp/features/realtimeChart/realtime-chart.controller.js
- web/src/main/webapp/features/scatter/jquery.BigScatterChart.js
sort dragged data on scatter chart.
> modify timeout time of realtime chart when invoke visibilitychange event

- web/src/main/java/com/navercorp/pinpoint/web/calltree/span/CallTree.java
- web/src/main/java/com/navercorp/pinpoint/web/calltree/span/CallTreeIterator.java
- web/src/main/java/com/navercorp/pinpoint/web/calltree/span/SpanAsyncCallTree.java
- web/src/main/java/com/navercorp/pinpoint/web/calltree/span/SpanCallTree.java
- web/src/test/java/com/navercorp/pinpoint/web/calltree/span/CallStackMock.java
- web/src/test/java/com/navercorp/pinpoint/web/calltree/span/CallTreeFactory.java
- web/src/test/java/com/navercorp/pinpoint/web/calltree/span/CallTreeIteratorTest.java
> fix gap of async&sibling node.

- plugins/spring/src/main/java/com/navercorp/pinpoint/plugin/spring/beans/SpringBeansConfig.java
- plugins/spring/src/main/java/com/navercorp/pinpoint/plugin/spring/beans/SpringBeansPlugin.java
> add profiler.spring.beans option.

- commons/src/main/java/com/navercorp/pinpoint/common/buffer/Buffer.java
- commons/src/main/java/com/navercorp/pinpoint/common/buffer/FixedBuffer.java
- commons/src/main/java/com/navercorp/pinpoint/common/util/BytesUtils.java
- commons/src/test/java/com/navercorp/pinpoint/common/buffer/FixedBufferTest.java
- thrift/src/main/java/com/navercorp/pinpoint/thrift/io/UnsafeByteArrayOutputStream.java
1. remove jdk Logger
2. fix try-catch block for UnsupportedEncodingException
> remove jdk Logger

- web/src/main/java/com/navercorp/pinpoint/web/applicationmap/ApplicationMap.java
- web/src/main/java/com/navercorp/pinpoint/web/applicationmap/ApplicationMapBuilder.java
- web/src/main/java/com/navercorp/pinpoint/web/applicationmap/ApplicationMapWithScatterData.java
- web/src/main/java/com/navercorp/pinpoint/web/applicationmap/ApplicationMapWithScatterScanResult.java
- web/src/main/java/com/navercorp/pinpoint/web/applicationmap/DefaultApplicationMap.java
- web/src/main/java/com/navercorp/pinpoint/web/applicationmap/FilterMapWrap.java
- web/src/main/java/com/navercorp/pinpoint/web/controller/FilteredMapController.java
- web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseApplicationTraceIndexDao.java
- web/src/main/java/com/navercorp/pinpoint/web/mapper/TraceIndexScatterMapper3.java
- web/src/main/java/com/navercorp/pinpoint/web/scatter/ScatterData.java
- web/src/main/java/com/navercorp/pinpoint/web/service/DotExtractor.java
- web/src/main/java/com/navercorp/pinpoint/web/service/FilteredMapService.java
- web/src/main/java/com/navercorp/pinpoint/web/service/FilteredMapServiceImpl.java
- web/src/main/java/com/navercorp/pinpoint/web/view/FilterMapWrapSerializer.java
- web/src/test/java/com/navercorp/pinpoint/web/applicationmap/ApplicationMapTest.java
- web/src/test/java/com/navercorp/pinpoint/web/scatter/ScatterDataTest.java
added getFilteredServerMapDataMadeOfDotGroup method.
> Add method, that get scatter data made of dot group . #1518

- web/src/main/java/com/navercorp/pinpoint/web/applicationmap/Link.java
- web/src/main/java/com/navercorp/pinpoint/web/applicationmap/Node.java
- web/src/main/java/com/navercorp/pinpoint/web/controller/MapController.java
> #1561 remove unused code

- web/src/main/java/com/navercorp/pinpoint/web/controller/ScatterChartController.java
- web/src/main/java/com/navercorp/pinpoint/web/dao/ApplicationTraceIndexDao.java
- web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseApplicationTraceIndexDao.java
- web/src/main/java/com/navercorp/pinpoint/web/service/FilteredMapService.java
- web/src/main/java/com/navercorp/pinpoint/web/service/FilteredMapServiceImpl.java
- web/src/main/java/com/navercorp/pinpoint/web/service/ScatterChartService.java
- web/src/main/java/com/navercorp/pinpoint/web/service/ScatterChartServiceImpl.java
added backwardDirection option.
> Add direction option to rest apis that getting ScatterData. #1573

- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/PlainClassLoaderHandler.java
> change position of filter and loading checker.

- commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HBaseAdminTemplate.java
> [#1587] improve using hbase deprecated api

- pom.xml
Follow-up #1378 bump docker-maven-plugin version that add volumes support
> Follow-up #1378 bump docker-maven-plugin

- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/context/ServerMetaDataHolder.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/resolver/condition/MainClassCondition.java
- plugins/spring-boot/src/main/java/com/navercorp/pinpoint/plugin/spring/boot/SpringBootConstants.java
- plugins/spring-boot/src/main/java/com/navercorp/pinpoint/plugin/spring/boot/SpringBootPlugin.java
- plugins/spring-boot/src/main/java/com/navercorp/pinpoint/plugin/spring/boot/interceptor/LauncherLaunchInterceptor.java
- plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/TomcatPlugin.java
- plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/interceptor/ConnectorInitializeInterceptor.java
- plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/interceptor/StandardServiceStartInterceptor.java
- plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/interceptor/WebappLoaderStartInterceptor.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultServerMetaDataHolder.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/AgentInfoSenderTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/DefaultServerMetaDataHolderTest.java
This adds collection for libraries loaded by `JarLauncher`, `WarLauncher`, and `PropertiesLauncher` when starting Spring Boot applications.
ping @emeroad
> Adds service information collection for Spring Boot applications

- collector/start-collector.sh
- docker-compose.yml
- quickstart/bin/start-hbase.sh
- web/start-web.sh
1. modified configurations for docker to show realtime active thread chart correctly using docker compose.
2. modified hbase version of quickstart app.
> modified configurations for docker to show realtime active thread chart correctly

- docker-compose.yml
change version (1.5.2-SNAPSHOT -> 1.5.2)
> 1.5.2 release #1668

- web/src/main/java/com/navercorp/pinpoint/web/applicationmap/ApplicationMapBuilder.java
> skip throw exception.

- commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/DisabledHBaseAsyncOperation.java
- commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HBaseAsyncOperation.java
- commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HBaseAsyncTemplate.java
- commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HBaseTables.java
- commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseAccessor.java
- commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseOperations2.java
- commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseTemplate2.java
- commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/parallel/ParallelResultScanner.java
- commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/parallel/ScanTask.java
- commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/parallel/ScanTaskConfig.java
- commons-hbase/src/test/java/com/navercorp/pinpoint/common/hbase/HbaseTemplate2IT.java
- web/src/test/java/com/navercorp/pinpoint/web/dao/hbase/HbaseAgentLifeCycleDaoTest.java
completed review by @Kang-heesuk
> [#1613] change code using hbase api

- agent/src/test/java/com/navercorp/pinpoint/plugin/mybatis/SqlSessionTemplateITBase.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/mybatis/SqlSessionTemplate_1_1_x_IT.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/mybatis/SqlSessionTemplate_1_2_x_IT.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/mybatis/SqlSessionTemplate_1_3_x_IT.java
Fix incomplete commit done previously.
> Fix integration tests to support mybatis-spring v1.3.x

- rpc/src/main/java/com/navercorp/pinpoint/rpc/buffer/ByteBufferFactory.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/buffer/ByteBufferFactoryLocator.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/buffer/ByteBufferType.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/buffer/DirectByteBufferFactory.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/buffer/HeapByteBufferFactory.java
- rpc/src/test/java/com/navercorp/pinpoint/rpc/buffer/ByteBufferFactoryTest.java
added a factory for bytebuffer.
> Added UdpDataSender using NIO #1711

- commons/src/main/java/com/navercorp/pinpoint/common/util/AnnotationTranscoder.java
- commons/src/main/java/com/navercorp/pinpoint/common/util/IntStringStringValue.java
- commons/src/main/java/com/navercorp/pinpoint/common/util/IntStringValue.java
- commons/src/test/java/com/navercorp/pinpoint/common/util/AnnotationTranscoderTest.java
- web/src/main/java/com/navercorp/pinpoint/web/service/SpanServiceImpl.java
- remove com.navercorp.pinpoint.common.bo package
> #1720 Package name change of the server module

- collector/src/main/resources/applicationContext-collector.xml
- collector/src/main/resources/applicationContext-hbase.xml
- collector/src/main/resources/servlet-context.xml
- web/src/main/resources/applicationContext-cache.xml
- web/src/main/resources/applicationContext-dao-config.xml
- web/src/main/resources/applicationContext-datasource.xml
- web/src/main/resources/applicationContext-web.xml
- web/src/main/resources/applicationContext-websocket.xml
- web/src/main/resources/servlet-context.xml
> spring configuration cleanup

- collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseApplicationTraceIndexDao.java
- collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseHostApplicationMapDao.java
- collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseMapResponseTimeDao.java
- collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseMapStatisticsCalleeDao.java
- collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseMapStatisticsCallerDao.java
- collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseTraceDao.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/AbstractDispatchHandler.java
- collector/src/main/resources/applicationContext-collector.xml
- commons-server/pom.xml
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/SpanBo.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/HbaseSerializer.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/SerializationContext.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/SpanSerializer.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/AcceptedTimeService.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/ThreadLocalAcceptedTimeService.java
- commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/serializer/SpanBoTest.java
> #1734 Extract Seralization in XxxBo

- collector/src/main/java/com/navercorp/pinpoint/collector/handler/SpanHandler.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/SpanBo.java
- commons/src/main/java/com/navercorp/pinpoint/common/trace/AnnotationKey.java
- commons/src/main/java/com/navercorp/pinpoint/common/trace/DefaultServiceType.java
- commons/src/main/java/com/navercorp/pinpoint/common/trace/ServiceType.java
- commons/src/main/java/com/navercorp/pinpoint/common/trace/ServiceTypeProperty.java
- web/src/main/java/com/navercorp/pinpoint/web/applicationmap/ApplicationMapBuilder.java
- web/src/main/java/com/navercorp/pinpoint/web/applicationmap/Link.java
- web/src/main/java/com/navercorp/pinpoint/web/filter/LinkFilter.java
- web/src/main/java/com/navercorp/pinpoint/web/service/BFSLinkSelector.java
- web/src/main/java/com/navercorp/pinpoint/web/service/FilteredMapServiceImpl.java
- web/src/main/java/com/navercorp/pinpoint/web/view/NodeSerializer.java
- web/src/main/webapp/features/serverMap/server-map.directive.js
> Adds handling of queue service types

- collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseTraceDao.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/AnnotationBo.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/AnnotationBoList.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/SpanBo.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/SpanEventBo.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/AnnotationSerializer.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/SpanEventSerializer.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/SpanSerializer.java
- commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/AnnotationBoTest.java
- commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/SpanEventBoTest.java
> #1732_extract_serializer

- collector/pom.xml
- collector/src/test/java/com/navercorp/pinpoint/collector/rpc/handler/AgentEventHandlerTest.java
- collector/src/test/java/com/navercorp/pinpoint/collector/rpc/handler/AgentLifeCycleHandlerTest.java
- collector/src/test/java/com/navercorp/pinpoint/collector/rpc/handler/DirectExecutor.java
- commons-hbase/pom.xml
- pom.xml
- quickstart/testapp/pom.xml
- test/pom.xml
- web/pom.xml
spring 4.1.8->4.1.9
guava
12.0.1 -> 16.0.1
17.0.0 18.0.0 -> 19.0.0
jackson 2.3.1 -> 2.6.6
slf4j 1.7.5->1.7.21
commons-lang3 3.3.2->3.4
commons-logging 1.1.2->1.2
org.aspectj.aspectjweaver 1.6.12->1.8.9
remove org.aspectj.aspectjrt
mockito 1.8.4 -> 1.10.19
maven plugin
compiler-plugin 3.0->3.5.1
maven-war-plugin 2.4->2.6
maven-jar-plugin 2.4->2.6
maven-resources-plugin 2.6->2.7
maven-surefire-plugin 2.17->2.19.1
maven-jxr-plugin 2.3->2.5
> #1749 lib version upgrade

- pom.xml
> clover maven plugin version upgrade #1757

- docker-compose.yml
- web/start-web.sh
This pull request depends on https://github.com/naver/pinpoint/pull/1767
To be honest I had issue to make it work with current configuration and failed back to use in memory database for pinpoint web. Anyway it only introduce new docker container with mysql and ability to reconfigure db settings from environments.
> Mysql docker

- agent/pom.xml
- agent/src/assembly/distribution.xml
- agent/src/main/script/networktest.sh
- pom.xml
- tools/.gitignore
- tools/README.md
- tools/clover.license
- tools/pom.xml
- tools/src/main/java/com/navercorp/pinpoint/tools/NetworkAvailabilityChecker.java
- tools/src/main/java/com/navercorp/pinpoint/tools/PinpointTools.java
- tools/src/main/script/networktest.sh
> extract tools module #1774

- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/interceptor/InterceptorDefinitionFactory.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/interceptor/InterceptorDefinitionFactoryTest.java
#1792 Invalid CaptureType detection
> #1792 Invalid CaptureType detection

- pom.xml
- change artifactId : pom -> pinpoint
> change artifactId of main pom.xml

- agent/src/main/resources/pinpoint-real-env-lowoverhead-sample.config
- agent/src/main/resources/pinpoint.config
I add default postgres configuration, related to #1678 .
> Added postgres agent default configuration

- agent/src/main/resources/pinpoint-real-env-lowoverhead-sample.config
- agent/src/main/resources/pinpoint.config
- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/ProfilerLibClass.java
- pom.xml
- profiler/pom.xml
- profiler/src/main/java/com/navercorp/pinpoint/profiler/DefaultAgent.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMBytecodeDisassembler.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMBytecodeDumpService.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/BytecodeDumpService.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/BytecodeDumpTransformer.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/BytecodeDumpServiceTest.java
- add bytecodedump option to agent
> #1811 add bytecodedump option

- java8-test/pom.xml
- java8-test/src/test/java/bug_regression_jdk7/javassist/CustomURLClassLoader.java
- java8-test/src/test/java/bug_regression_jdk7/javassist/InvalidStackMapFrame.java
- java8-test/src/test/java/bug_regression_jdk7/javassist/JavassistVerifyErrorTest.java
- java8-test/src/test/java/bug_regression_jdk7/javassist/asm/AddIntVariableMethodAdapter.java
- java8-test/src/test/java/bug_regression_jdk7/javassist/asm/BytecodeVerifyTestClassVisitor.java
- java8-test/src/test/resources/log4j.xml
- profiler/src/main/java/com/navercorp/pinpoint/test/util/BytecodeUtils.java
> #1807 Javassist bug : Incorrect StackMap Frame generation

- web/src/main/java/com/navercorp/pinpoint/web/service/TransactionInfoServiceImpl.java
> change focus condition.

- web/src/main/webapp/common/services/agent-dao.service.js
- web/src/main/webapp/common/services/common-util.service.js
- web/src/main/webapp/common/services/progress-bar.service.js
- web/src/main/webapp/features/agentInfo/agentInfo.html
> change date format of chart in inspector page

- commons/src/main/java/com/navercorp/pinpoint/common/util/BitFieldUtils.java
- commons/src/test/java/com/navercorp/pinpoint/common/util/BitFieldUtilsTest.java
> #1819 add BitFieldUtils

- commons/src/main/java/com/navercorp/pinpoint/common/buffer/Buffer.java
- commons/src/main/java/com/navercorp/pinpoint/common/buffer/FixedBuffer.java
- commons/src/main/java/com/navercorp/pinpoint/common/buffer/OffsetAutomaticBuffer.java
- commons/src/main/java/com/navercorp/pinpoint/common/buffer/OffsetFixedBuffer.java
- commons/src/test/java/com/navercorp/pinpoint/common/buffer/FixedBufferTest.java
- commons/src/test/java/com/navercorp/pinpoint/common/buffer/OffsetAutomaticBufferTest.java
- commons/src/test/java/com/navercorp/pinpoint/common/buffer/OffsetFixedBufferTest.java
#1838
- add remaining()
- add hasRemaining()
- deprecated limit()
> #1838 Buffer API enhancement

- commons/src/main/java/com/navercorp/pinpoint/common/buffer/FixedBuffer.java
#1838
- infinite recursive loop
> #1838 fix incorrect api call

- collector/src/test/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseApplicationTraceIndexColumnTest.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/SpanBo.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/SpanEventBo.java
- commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/serializer/SpanBoTest.java
- commons/src/main/java/com/navercorp/pinpoint/common/buffer/AutomaticBuffer.java
- commons/src/main/java/com/navercorp/pinpoint/common/buffer/OffsetAutomaticBuffer.java
- commons/src/main/java/com/navercorp/pinpoint/common/buffer/OffsetFixedBuffer.java
- commons/src/test/java/com/navercorp/pinpoint/common/buffer/AutomaticBufferTest.java
- commons/src/test/java/com/navercorp/pinpoint/common/buffer/OffsetAutomaticBufferTest.java
- commons/src/test/java/com/navercorp/pinpoint/common/buffer/OffsetFixedBufferTest.java
- web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/HbaseApplicationTraceIndexDao.java
- web/src/main/java/com/navercorp/pinpoint/web/mapper/AnnotationMapper.java
- web/src/main/java/com/navercorp/pinpoint/web/mapper/HostApplicationMapperVer2.java
- web/src/main/java/com/navercorp/pinpoint/web/mapper/MapStatisticsCallerMapper.java
- web/src/main/java/com/navercorp/pinpoint/web/mapper/SpanMapper.java
- web/src/main/java/com/navercorp/pinpoint/web/mapper/TraceIndexScatterMapper.java
- web/src/main/java/com/navercorp/pinpoint/web/mapper/TraceIndexScatterMapper2.java
- web/src/main/java/com/navercorp/pinpoint/web/mapper/TraceIndexScatterMapper3.java
- web/src/main/java/com/navercorp/pinpoint/web/mapper/TransactionIdMapper.java
#1838  deprecated unsafe constructor
- deprecated OffsetAutomaticBuffer(byte[], int)
- deprecated OffsetFixedBuffer(byte[], int)
> #1838 deprecated unsafe constructor

- web/src/main/webapp/common/services/url-vo.service.js
- web/src/main/webapp/features/navbar/navbar.directive.js
- will refactoring navbar.directive.js.
> fix scatter chart error in realtime state.

- collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseTraceDao.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/AnnotationBoDecoder.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/AnnotationBoList.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/SpanBo.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/SpanEventBo.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/AnnotationSerializer.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/SpanEventSerializer.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/SpanSerializer.java
- commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/AnnotationBoTest.java
- commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/SpanEventBoTest.java
- commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/serializer/SpanBoTest.java
- commons-server/src/test/resources/log4j.xml
- commons/src/main/java/com/navercorp/pinpoint/common/util/BytesUtils.java
- web/src/main/java/com/navercorp/pinpoint/web/mapper/AnnotationMapper.java
- web/src/main/java/com/navercorp/pinpoint/web/mapper/SpanMapper.java
#1819 extract deserializer
- extract deserializer
- reduce array copy
> #1819 extract deserializer

- commons/src/main/java/com/navercorp/pinpoint/common/buffer/AutomaticBuffer.java
- commons/src/test/java/com/navercorp/pinpoint/common/buffer/AutomaticBufferTest.java
#1838 fixed incorrect buffer expend multiplier 
- multiplier 4 -> multiplier 2
> #1838 fixed incorrect buffer expend multiplier 

- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/JavassistClass.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/util/JavaAssistUtils.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/interceptor/bci/IntArrayGetter.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/interceptor/bci/IntArraySetter.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/interceptor/bci/IntArrayTraceValue.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/interceptor/bci/IntSetter.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/interceptor/bci/IntegerArrayGetter.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/interceptor/bci/IntegerArraySetter.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/interceptor/bci/IntegerArrayTraceValue.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/interceptor/bci/JavassistClassTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/interceptor/bci/TestObject4.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/util/JavaAssistUtilsTest.java
> Fix type checking for arrays

- quickstart/agent/pom.xml
- quickstart/agent/src/assembly/distribution.xml
> Fix quickstart agent distribution setting for packaging optional modules

- collector/src/main/resources/pinpoint-collector.properties
Regression introduced with commit "added executor made of disruptor. #1804"
> Regression introduced with #1804

- web/src/main/webapp/common/services/alarm-ajax.service.js
- web/src/main/webapp/features/configuration/application/alarm-rule.directive.js
- web/src/main/webapp/features/configuration/application/alarmRule.html
- web/src/main/webapp/features/configuration/application/application-config.directive.js
- web/src/main/webapp/features/configuration/userGroup/group-member.directive.js
- web/src/main/webapp/features/configuration/userGroup/pinpoint-user.directive.js
- web/src/main/webapp/features/configuration/userGroup/pinpointUser.html
- web/src/main/webapp/features/configuration/userGroup/user-group-container.directive.js
> update alarm setting ui of configuration.

- web/src/main/java/com/navercorp/pinpoint/web/dao/memory/MemoryAgentStatisticsDao.java
- web/src/test/java/com/navercorp/pinpoint/web/dao/memory/MemoryAgentStatisticsDaoTest.java
> added to insert a number of agent into rdb periodically. #1883

- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/trace/v2/SpanEncoder.java
- temporary bug fix
- incorrect Comparing logic
> #1819 trace format v2

- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/transformer/DebugTransformer.java
> change target.addInterceptor() to method.addInterceptor().

- web/src/main/java/com/navercorp/pinpoint/web/batch/job/AgentCountProcessor.java
- web/src/main/java/com/navercorp/pinpoint/web/batch/job/AgentCountReader.java
- web/src/main/java/com/navercorp/pinpoint/web/batch/job/AgentCountWriter.java
- web/src/main/java/com/navercorp/pinpoint/web/controller/AgentStatisticsController.java
- web/src/main/java/com/navercorp/pinpoint/web/dao/AgentStatisticsDao.java
- web/src/main/java/com/navercorp/pinpoint/web/dao/memory/MemoryAgentStatisticsDao.java
- web/src/main/java/com/navercorp/pinpoint/web/dao/mysql/MysqlAgentStatisticsDao.java
- web/src/main/java/com/navercorp/pinpoint/web/service/AgentStatisticsService.java
- web/src/main/java/com/navercorp/pinpoint/web/service/AgentStatisticsServiceImpl.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/AgentCountStatistics.java
- web/src/test/java/com/navercorp/pinpoint/web/dao/memory/MemoryAgentStatisticsDaoTest.java
> added license  #1883

- web/src/main/java/com/navercorp/pinpoint/web/controller/BusinessTransactionController.java
- web/src/main/java/com/navercorp/pinpoint/web/controller/ScatterChartController.java
- remove unused variable
- remove HttpServlet API
> Controller source cleanup

- commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/concurrent/DisruptorExecutorService.java
- commons-server/src/test/java/com/navercorp/pinpoint/common/server/util/DisruptorExecutorTest.java
changed FatalExceptionHandler to IgnoreExceptionHandler ( To make Same operation with ExecutorService)
> #1804 added executor made of disruptor

- collector/src/main/java/com/navercorp/pinpoint/collector/handler/AgentStatHandlerV2.java
- collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/AgentStatBatchMapper.java
- collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/AgentStatMapper.java
Additional minor change - populate agentId for stat bos (not used but for completeness).
related to #1533
> Improve agent stat handler logging

- plugins/cxf/.gitignore
- plugins/cxf/clover.license
- plugins/cxf/pom.xml
- plugins/cxf/src/main/java/com/navercorp/pinpoint/plugin/cxf/CxfPlugin.java
- plugins/cxf/src/main/java/com/navercorp/pinpoint/plugin/cxf/CxfPluginConfig.java
- plugins/cxf/src/main/java/com/navercorp/pinpoint/plugin/cxf/CxfPluginConstants.java
- plugins/cxf/src/main/java/com/navercorp/pinpoint/plugin/cxf/CxfPluginTraceMetadataProvider.java
- plugins/cxf/src/main/java/com/navercorp/pinpoint/plugin/cxf/interceptor/CxfClientInvokeSyncMethodInterceptor.java
- plugins/cxf/src/main/resources/META-INF/services/com.navercorp.pinpoint.bootstrap.plugin.ProfilerPlugin
- plugins/cxf/src/main/resources/META-INF/services/com.navercorp.pinpoint.common.trace.TraceMetadataProvider
- plugins/cxf/src/test/java/com/navercorp/pinpoint/plugin/cxf/interceptor/CxfClientInvokeSyncMethodInterceptorTest.java
- plugins/pom.xml
- pom.xml
- quickstart/agent/src/main/resources/pinpoint.config
- quickstart/testapp/pom.xml
- quickstart/testapp/src/main/java/com/navercorp/pinpoint/testapp/controller/CxfClientController.java
#142 apache cxf plugin for client
> apache cxf plugin for client

- commons/src/main/java/com/navercorp/pinpoint/common/trace/AnnotationKey.java
- commons/src/main/java/com/navercorp/pinpoint/common/trace/ServiceType.java
- added ServiceType and AnnotationKey comment
> #142 apache cxf

- README.md
> change required Java version

- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/udp/UDPReceiver.java
- plugins/cxf/src/main/java/com/navercorp/pinpoint/plugin/cxf/interceptor/CxfClientInvokeSyncMethodInterceptor.java
- web/src/main/java/com/navercorp/pinpoint/web/mapper/stat/AgentStatMapperV2.java
> fixed FindBugs Warnings

- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/SpanAsyncEventSimpleAroundInterceptor.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/ApiMetaDataBo.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/MethodTypeEnum.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/AnnotationUtils.java
- commons/src/main/java/com/navercorp/pinpoint/common/trace/AnnotationKey.java
- web/src/main/java/com/navercorp/pinpoint/web/calltree/span/CorruptedSpanAlignFactory.java
- web/src/main/java/com/navercorp/pinpoint/web/mapper/ApiMetaDataMapper.java
- web/src/main/java/com/navercorp/pinpoint/web/service/SpanServiceImpl.java
- web/src/main/java/com/navercorp/pinpoint/web/view/TransactionInfoViewModel.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/callstacks/Record.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/callstacks/RecordFactory.java
> #2018 Support Annotation base API metadata

- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/ASMMethodNodeAdapterAddInterceptorTest.java
> ignored testcase for 4k log.

- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMBytecodeDisassembler.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/ASMBytecodeDisassemblerTest.java
> change default options.

- profiler/src/main/java/com/navercorp/pinpoint/profiler/PinpointClassFilter.java
> include pinpoint-web package.

- thirdparty/google-guava/pom.xml
> #2038 repackaging guava

- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/BootLogger.java
- commons/src/main/java/com/navercorp/pinpoint/common/util/logger/StdoutCommonLogger.java
- commons/src/test/java/com/navercorp/pinpoint/common/util/logger/StdoutCommonLoggerTest.java
- thirdparty/google-guava/src/main/java-logging/com/google/common/logging/Logger.java
> #2026 remove JDK logger dependency

- pom.xml
> #2060 modify coverage option

- findbugs-exclude.xml
>  #2038_fixed_findbugs-exclude

- plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/TomcatConfiguration.java
> Fix incorrect conditional check

- collector/src/main/java/com/navercorp/pinpoint/collector/cluster/connection/CollectorClusterConnectionRepository.java
> fixed jdk 8 KeySetView compatibility

- web/src/main/java/com/navercorp/pinpoint/web/vo/chart/Point.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/chart/TimeSeriesChartBuilder.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/chart/TitledPoint.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/chart/UncollectedPoint.java
> Allows nulls to be set to point's y-value

- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/JavassistClassPool.java
> #2117 support JBoss CL

- agent/src/main/resources-local/pinpoint.config
- agent/src/main/resources-release/pinpoint.config
- agent/src/main/resources/pinpoint-real-env-lowoverhead-sample.config
- agent/src/test/resources/pinpoint-disabled-plugin-test.config
- agent/src/test/resources/pinpoint-spring-bean-test.config
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/DefaultProfilerConfig.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/ProfilerConfig.java
- bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/config/DefaultProfilerConfigTest.java
- plugins/httpclient3/src/main/java/com/navercorp/pinpoint/plugin/httpclient3/HttpClient3Plugin.java
- plugins/httpclient3/src/main/java/com/navercorp/pinpoint/plugin/httpclient3/HttpClient3PluginConfig.java
- plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/HttpClient4Plugin.java
- plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/HttpClient4PluginConfig.java
- plugins/ibatis/src/main/java/com/navercorp/pinpoint/plugin/ibatis/IBatisPlugin.java
- plugins/ibatis/src/main/java/com/navercorp/pinpoint/plugin/ibatis/IBatisPluginConfig.java
- plugins/mybatis/src/main/java/com/navercorp/pinpoint/plugin/mybatis/MyBatisPlugin.java
- plugins/mybatis/src/main/java/com/navercorp/pinpoint/plugin/mybatis/MyBatisPluginConfig.java
- plugins/redis/src/main/java/com/navercorp/pinpoint/plugin/redis/RedisPlugin.java
- plugins/redis/src/main/java/com/navercorp/pinpoint/plugin/redis/RedisPluginConfig.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/DefaultAgent.java
- profiler/src/main/java/com/navercorp/pinpoint/test/MockAgent.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/interceptor/bci/JavassistClassTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/monitor/codahale/gc/GarbageCollectorFactoryTest.java
> cleanup ProfilerConfig

- hbase/pom.xml
Changing hbase version because link of version1.2.1 doesn't exists more.
> Changing hbase version in hbase/pom.xml

- plugins/jboss/.gitignore
- plugins/jboss/clover.license
- add .gitignore & clover.license
> #2001 jboss plugin

- agent/src/main/resources/pinpoint-real-env-lowoverhead-sample.config
- agent/src/test/resources/activemq/client/pinpoint-activemq-client.config
- agent/src/test/resources/pinpoint-disabled-plugin-test.config
- agent/src/test/resources/pinpoint-spring-bean-test.config
- plugins/jboss/pom.xml
> #2001 jboss temporary fix

- agent/src/main/resources-local/pinpoint.config
- agent/src/main/resources-release/pinpoint.config
- agent/src/main/resources/pinpoint-real-env-lowoverhead-sample.config
- agent/src/test/resources/activemq/client/pinpoint-activemq-client.config
- agent/src/test/resources/pinpoint-disabled-plugin-test.config
- agent/src/test/resources/pinpoint-spring-bean-test.config
- plugins/dubbo/src/main/java/com/navercorp/pinpoint/plugin/dubbo/DubboConfiguration.java
- plugins/dubbo/src/main/java/com/navercorp/pinpoint/plugin/dubbo/DubboPlugin.java
- plugins/google-httpclient/src/test/resources/pinpoint.config
- plugins/httpclient3/src/test/resources/pinpoint.config
- plugins/httpclient4/src/test/resources/pinpoint.config
- plugins/jboss/src/test/resources/pinpoint.config
- plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/JettyConfiguration.java
- plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/JettyPlugin.java
- plugins/redis/src/test/resources/pinpoint.config
- plugins/spring-boot/src/main/java/com/navercorp/pinpoint/plugin/spring/boot/SpringBootConfiguration.java
- plugins/spring-boot/src/main/java/com/navercorp/pinpoint/plugin/spring/boot/SpringBootPlugin.java
- plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/TomcatConfiguration.java
- plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/TomcatPlugin.java
- plugins/tomcat/src/test/resources/pinpoint.config
- plugins/user/src/test/resources/pinpoint.config
- profiler-optional/profiler-optional-jdk8/src/test/resources/pinpoint-lambda-test.config
- profiler/src/test/resources/pinpoint-spring-bean-test.config
- profiler/src/test/resources/pinpoint.config
- quickstart/agent/src/main/resources/pinpoint.config
- quickstart/conf/pinpoint.config
This adds enable/disable options for bootstrap application plugins : 
* Tomcat
* Jetty
* Dubbo
* SpringBoot
> Adds enable/disable configuration options for bootstrap application plugins

- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/util/jdk/ThreadLocalRandomUtils.java
- plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/interceptor/StandardHostValveInvokeInterceptor.java
- plugins/tomcat/src/test/java/com/navercorp/pinpoint/plugin/tomcat/InvokeMethodInterceptorTest.java
- profiler/src/main/java/com/navercorp/pinpoint/test/MockTraceContextFactory.java
- more safe & general type cast
- complement testcase
> Polish Tomcat Plugin

- plugins/jboss/src/main/java/com/navercorp/pinpoint/plugin/jboss/interceptor/StandardHostValveInvokeInterceptor.java
- plugins/jboss/src/test/java/com/navercorp/pinpoint/plugin/jboss/InvokeMethodInterceptorTest.java
- more safe & general type cast
- complement testcase
> Polish JBoss Plugin

- quickstart/agent/src/main/resources/pinpoint.config
- quickstart/collector/src/main/resources/pinpoint-collector.properties
- quickstart/conf/pinpoint.config
- quickstart/web/src/main/resources/pinpoint-web.properties
Updates quickstart configuration.
Collector - Adds missing configuration options
Web - Adds missing configuration options
Agent - Disables conditional transformer registration, and disables Jboss plugin (related to #2178)
> Updates quickstart configuration

- profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/RetryMessage.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/RetryQueue.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/TcpDataSender.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/sender/RetryMessageTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/sender/RetryQueueTest.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/client/PinpointClientFactory.java
1. Fixed retry policy in TCPDataSender is not working properly.
2. Changed log level
> Fixed send retry policy in TCPDataSender #2198

- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/AgentDirBaseClassPathResolver.java
- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/PinpointStarter.java
- bootstrap/src/test/java/com/navercorp/pinpoint/bootstrap/AgentDirBaseClassPathResolverTest.java
- bootstrap/src/test/java/com/navercorp/pinpoint/bootstrap/AgentVersionTest.java
- add RC version to VERSION_PATTERN
> refactoring bootstrap

- pom.xml
- profiler-optional/profiler-optional-jdk7/src/test/java/bug_regression_jdk7/javassist/JavassistVerifyErrorTest.java
- #1807
- Incorrect StackMap Frame fix
- javassist version up
- 3.20.0-GA -> 3.21.0-GA
> #1807 Javassist bug fix

- profiler/src/main/java/com/navercorp/pinpoint/profiler/util/ApiUtils.java
- profiler/src/main/java/com/navercorp/pinpoint/test/PluginTestAgent.java
- profiler/src/main/java/com/navercorp/pinpoint/test/TestTcpDataSender.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/util/ApiUtilsTest.java
> fix key of api descriptor.

- profiler/src/main/java/com/navercorp/pinpoint/profiler/util/ApiUtils.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/util/ApiUtilsTest.java
> fix multi argument parsing fail in ApiUtils

- collector/src/main/java/com/navercorp/pinpoint/collector/cluster/connection/CollectorClusterAcceptor.java
- collector/src/main/java/com/navercorp/pinpoint/collector/cluster/connection/CollectorClusterConnectionFactory.java
- collector/src/main/java/com/navercorp/pinpoint/collector/cluster/connection/CollectorClusterConnectionManager.java
- collector/src/main/java/com/navercorp/pinpoint/collector/cluster/connection/CollectorClusterConnectionOption.java
- collector/src/main/java/com/navercorp/pinpoint/collector/cluster/connection/CollectorClusterConnectionProvider.java
- collector/src/main/java/com/navercorp/pinpoint/collector/cluster/connection/CollectorClusterConnectionRepository.java
- collector/src/main/java/com/navercorp/pinpoint/collector/cluster/connection/CollectorClusterConnector.java
- collector/src/main/java/com/navercorp/pinpoint/collector/manage/ClusterManager.java
- collector/src/main/java/com/navercorp/pinpoint/collector/manage/ClusterManagerMBean.java
- collector/src/test/java/com/navercorp/pinpoint/collector/cluster/route/DefaultRouteHandlerTest.java
Example (  *  * Copyright 2016 NAVER Corp. -> * Copyright 2016 NAVER Corp. )
> Fixed badly formatted license

- profiler/src/main/java/com/navercorp/pinpoint/test/classloader/TestClassLoaderFactory.java
- test/src/main/java/com/navercorp/pinpoint/test/plugin/ForkedPinpointPluginTest.java
- test/src/main/java/com/navercorp/pinpoint/test/plugin/PluginTestClassLoader.java
- test/src/main/java/com/navercorp/pinpoint/test/plugin/PluginTestLogger.java
> polishing profiler-test

- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMClass.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMClassNodeAdapter.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMClassPool.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMMethod.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMMethodNodeAdapter.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMMethodVariables.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/JavassistClass.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/util/JavaAssistUtils.java
- profiler/src/main/java/com/navercorp/pinpoint/test/classloader/TransformClassLoader.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/ASMAspectWeaverTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/ASMClassNodeAdapterTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/ASMClassNodeLoader.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/ASMClassWriterTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/ASMMethodNodeAdapterAddDelegatorTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/ASMMethodNodeAdapterAddInterceptorTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/ASMMethodNodeAdapterRemapMethodInsnNodeTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/ASMMethodNodeAdapterRenameTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/ASMMethodNodeAdapterTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/ASMMethodNodeAdapterTestMain.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/ASMMethodVariablesTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/mock/DelegatorClass.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/mock/DelegatorSuperClass.java
#2264
* change INVOKESPECAIL class name.
* add local variables.
> #2264 fix ASMClass.addDelegatorMethod()

- web/src/main/java/com/navercorp/pinpoint/web/vo/AgentCountStatistics.java
- web/src/main/resources/batch/applicationContext-batch-schedule.xml
- web/src/main/resources/mapper/AgentStaticsMapper.xml
- web/src/main/resources/sql/CreateTableStatement-mysql.sql
> Fixed bad field name in AgentStaticsMapper.xml #2279

- web/src/main/java/com/navercorp/pinpoint/web/controller/ScatterChartController.java
Fixed scatter chart stuck when the ms value per pixel is less than 1 ms
> Fixed scatter chart stuck #2299

- commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/serializer/trace/v1/AnnotationBoDecoderTest.java
- plugins/jboss/pom.xml
- plugins/jboss/src/test/java/com/navercorp/pinpoint/plugin/jboss/StandardHostValveInvokeModifierTest.java
- pom.xml
#2321
- commons-io : 1.4 -> 2.5
- commons-lang3 : 3.4 -> 3.5
> #2321 Update library

- web/src/main/webapp/common/services/agent-ajax.service.js
- web/src/main/webapp/common/services/agent-dao.service.js
- web/src/main/webapp/common/services/analytics.service.js
- web/src/main/webapp/features/agentInfo/agent-info.directive.js
bug fix.
- do not throw error when block google analytics js.
> split ajax request for agent-chart.

- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/udp/BaseUDPHandlerFactory.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/udp/ChunkedUDPPacketHandlerFactory.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/udp/NetworkAvailabilityCheckPacketFilter.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/udp/PacketHandler.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/udp/PooledPacketWrap.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/udp/SpanStreamUDPPacketHandlerFactory.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/udp/TBaseFilter.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/udp/TBaseFilterChain.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/udp/UDPReceiver.java
- collector/src/test/java/com/navercorp/pinpoint/collector/receiver/udp/NetworkAvailabilityCheckPacketFilterTest.java
- collector/src/test/java/com/navercorp/pinpoint/collector/receiver/udp/SpanStreamUDPSenderTest.java
- collector/src/test/java/com/navercorp/pinpoint/collector/receiver/udp/TestUDPReceiver.java
Sometimes "icmp port unreachble error" occurs when executing networktest script.
> Fix executing fail networktest script #2334

- collector/src/main/resources/applicationContext-collector.xml
- profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/CommandSerializer.java
- thrift/src/main/java/com/navercorp/pinpoint/thrift/io/CommandHeaderTBaseDeserializerFactory.java
- thrift/src/main/java/com/navercorp/pinpoint/thrift/io/CommandHeaderTBaseSerializerFactory.java
- web/src/main/resources/applicationContext-web.xml
- web/src/test/resources/applicationContext-test.xml
Change the cluster api management method.
> Change the cluster api management method. #2262

- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/instrument/GuardInstrumentContext.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/instrument/InstrumentContext.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMClass.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMClassNodeAdapter.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMClassPool.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMClassWriter.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/BootstrapClassLoaderHandler.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ClassInjector.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ClassPoolBase_PlainClassLoaderHandler.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/JarProfilerPluginClassInjector.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/LegacyProfilerPluginClassInjector.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/PlainClassLoaderHandler.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/URLClassLoaderHandler.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/classreading/DefaultSimpleClassMetadata.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/classreading/SimpleClassMetadata.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/DefaultProfilerPluginContext.java
- profiler/src/main/java/com/navercorp/pinpoint/test/TestProfilerPluginClassLoader.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/ASMAspectWeaverTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/ASMClassNodeAdapterTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/ASMClassNodeLoader.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/ASMClassTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/ASMClassWriterTest.java
> add ClassInjector.getResourceAsStream().

- web/src/main/java/com/navercorp/pinpoint/web/view/TransactionMetaDataViewModel.java
> add spanId parameter.

- web/src/main/java/com/navercorp/pinpoint/web/controller/BusinessTransactionController.java
- web/src/main/java/com/navercorp/pinpoint/web/service/TransactionInfoService.java
- web/src/main/java/com/navercorp/pinpoint/web/service/TransactionInfoServiceImpl.java
> add agentId, spanId parameters for the /transactionInfo request.

- web/src/main/java/com/navercorp/pinpoint/web/controller/AgentCommandController.java
1. remove startTimeStamp requestParam
> #2286 Add function of getting thread dump from agent

- web/src/main/java/com/navercorp/pinpoint/web/vo/LinkKey.java
> Fixes hash function for LinkKey

- agent/src/main/resources-local/pinpoint.config
- agent/src/main/resources-release/pinpoint.config
- agent/src/main/resources/pinpoint-real-env-lowoverhead-sample.config
- agent/src/test/resources/activemq/client/pinpoint-activemq-client.config
- agent/src/test/resources/pinpoint-disabled-plugin-test.config
- agent/src/test/resources/pinpoint-spring-bean-test.config
- plugins/dbcp2/.gitignore
- plugins/dbcp2/clover.license
- plugins/dbcp2/pom.xml
- plugins/dbcp2/src/main/java/com/navercorp/pinpoint/plugin/commons/dbcp2/CommonsDbcp2Config.java
- plugins/dbcp2/src/main/java/com/navercorp/pinpoint/plugin/commons/dbcp2/CommonsDbcp2MetadataProvider.java
- plugins/dbcp2/src/main/java/com/navercorp/pinpoint/plugin/commons/dbcp2/CommonsDbcp2Plugin.java
- plugins/dbcp2/src/main/java/com/navercorp/pinpoint/plugin/commons/dbcp2/interceptor/DataSourceCloseInterceptor.java
- plugins/dbcp2/src/main/java/com/navercorp/pinpoint/plugin/commons/dbcp2/interceptor/DataSourceGetConnectionInterceptor.java
- plugins/dbcp2/src/main/resources/META-INF/services/com.navercorp.pinpoint.bootstrap.plugin.ProfilerPlugin
- plugins/dbcp2/src/main/resources/META-INF/services/com.navercorp.pinpoint.common.trace.TraceMetadataProvider
- plugins/dbcp2/src/test/java/com/navercorp/pinpoint/plugin/commons/dbcp2/CommonsDbcp2ConfigTest.java
- plugins/google-httpclient/src/test/resources/pinpoint.config
- plugins/jboss/src/test/resources/pinpoint.config
- plugins/pom.xml
- plugins/redis/src/test/resources/pinpoint.config
- plugins/tomcat/src/test/resources/pinpoint.config
- profiler-optional/profiler-optional-jdk8/src/test/resources/pinpoint-lambda-test.config
- profiler/src/test/resources/pinpoint-spring-bean-test.config
- profiler/src/test/resources/pinpoint.config
- quickstart/agent/src/main/resources/pinpoint.config
- quickstart/conf/pinpoint.config
>  #2396 add commons dbcp2 plugin

- web/src/main/java/com/navercorp/pinpoint/web/view/TransactionMetaDataViewModel.java
> change type.

- plugins/mariadb-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/mariadb/MariaDBPlugin.java
> Adds support for class name change in MariaDB java client 1.5.6

- web/src/main/java/com/navercorp/pinpoint/web/controller/BusinessTransactionController.java
> add xss filter.

- web/src/test/java/com/navercorp/pinpoint/web/view/AgentActiveThreadDumpListSerializerTest.java
> [no issue] fix test

- profiler-test/src/test/java/com/navercorp/pinpoint/test/javasssit/mock/TestObject.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/ASMClassNodeLoader.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/ASMMethodNodeAdapterAddDelegatorTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/ASMMethodNodeAdapterRemapMethodInsnNodeTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/ASMMethodNodeAdapterTestMain.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/mock/ApiIdAwareInterceptor.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/mock/ArgsArrayInterceptor.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/mock/ArgsClass.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/mock/AspectInterceptorClass.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/mock/AspectInterceptorExtendSubClass.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/mock/AspectInterceptorNoExtendClass.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/mock/AspectOriginalClass.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/mock/AspectOriginalSubClass.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/mock/BaseAnnotationInterceptor.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/mock/BaseClass.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/mock/BasicInterceptor.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/mock/ConstructorChildClass.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/mock/ConstructorExceptionClass.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/mock/ConstructorParentClass.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/mock/DelegatorSuperClass.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/mock/ExceptionInterceptor.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/mock/ExtendedClass.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/mock/NormalClass.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/mock/StaticInterceptor.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/interceptor/JavaAssistTestObject.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/interceptor/bci/TestObjectContextClassLoader.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/interceptor/bci/mock/Original.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/util/JavaAssistUtilsTest.java
- web/src/test/java/com/navercorp/pinpoint/web/controller/UserGroupControllerTest.java
Remove System.out.println() in test.
> remove System.out.

- web/src/main/java/com/navercorp/pinpoint/web/controller/AgentCommandController.java
- web/src/main/java/com/navercorp/pinpoint/web/service/AgentServiceImpl.java
- web/src/main/java/com/navercorp/pinpoint/web/view/AgentActiveThreadCountListSerializer.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/AgentActiveThreadCount.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/AgentActiveThreadCountFactory.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/AgentActiveThreadCountList.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/AgentActiveThreadDump.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/AgentActiveThreadDumpFactory.java
- web/src/main/java/com/navercorp/pinpoint/web/websocket/ActiveThreadCountErrorType.java
- web/src/main/java/com/navercorp/pinpoint/web/websocket/ActiveThreadCountResponseAggregator.java
- web/src/main/java/com/navercorp/pinpoint/web/websocket/ActiveThreadCountWorker.java
- web/src/test/java/com/navercorp/pinpoint/web/view/AgentActiveThreadDumpListSerializerTest.java
- web/src/test/java/com/navercorp/pinpoint/web/vo/AgentActiveThreadCountFactoryTest.java
- web/src/test/java/com/navercorp/pinpoint/web/vo/AgentActiveThreadCountListTest.java
- web/src/test/java/com/navercorp/pinpoint/web/vo/AgentActiveThreadDumpListTest.java
1. Use the constructor to change the object creation to use the factory and builder (AgentActiveThreadDump, AgentActiveThreadCount).
2. Changes some variable names.
> [no issue] code cleanup

- profiler/src/main/java/com/navercorp/pinpoint/profiler/monitor/codahale/cpu/CpuLoadMetricSetSelector.java
> Adds Cpu usage collection when running on OpenJDK

- tools/src/main/java/com/navercorp/pinpoint/tools/network/UDPChecker.java
Corrects failures when invoking a collector configured with a load balancer.
> #2436 Fix execution failed networktest.sh script

- web/src/main/webapp/features/threadDumpInfoLayer/thread-dump-info-layer.directive.js
- web/src/main/webapp/features/threadDumpInfoLayer/threadDumpInfoLayer.html
- web/src/main/webapp/styles/main.css
update thread-dump popup window ui
> change column order of thread-dump-info list

- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/ThreadLocalTraceFactory.java
> separate of storage.

- plugins/vertx/pom.xml
- plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/interceptor/HttpClientImplGetConnectionForRequest.java
- plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/interceptor/HttpClientStreamInterceptor.java
> change jdk version of  compiler & refactoring.

- plugins/jetty/README.md
> add read me

- annotations/.gitignore
- annotations/clover.license
- annotations/pom.xml
- annotations/src/main/java/com/navercorp/pinpoint/common/annotations/InterfaceAudience.java
- annotations/src/main/java/com/navercorp/pinpoint/common/annotations/InterfaceStability.java
- annotations/src/main/java/com/navercorp/pinpoint/common/annotations/VisibleForTesting.java
- pom.xml
#2477
- `@InterfaceStability`, `@InterfaceAudience`, `@VisibleForTesting`
> #2477 Added annotation for stability & visibility

- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/CloseableAsyncTraceId.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultAsyncTraceId.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/DefaultAsyncTraceIdTest.java
- profiler/src/test/resources/log4j.xml
#2481
- Change synchronized block to AtomicIntegerFieldUpdater
> #2481 Reduce synchronization of AsyncTraceId

- agent/src/main/resources-local/pinpoint.config
- agent/src/main/resources-release/pinpoint.config
- agent/src/main/resources/pinpoint-real-env-lowoverhead-sample.config
- agent/src/test/resources/pinpoint-disabled-plugin-test.config
- agent/src/test/resources/pinpoint-spring-bean-test.config
- quickstart/agent/src/main/resources/pinpoint.config
- quickstart/conf/pinpoint.config
Modify profiler.spring.beans.1.name.scope to profiler.spring.beans.1.scope.
> change invalid config name.

- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/monitor/DataSourceMonitor.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/monitor/DataSourceMonitorRegistry.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/monitor/DataSourceMonitorWrapper.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/monitor/DataSourceMonitorWrapperFactory.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/monitor/DefaultPluginMonitorContext.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/monitor/PluginMonitorContext.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/monitor/PluginMonitorWrapper.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/monitor/PluginMonitorWrapperLocator.java
- bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/plugin/monitor/DefaultPluginMonitorContextTest.java
1. Create classes related to support plugin monitor.
> [#2496] Add datasource metric collection

- commons/src/main/java/com/navercorp/pinpoint/common/trace/LoggingInfo.java
- remove Autoboxing & Unboxing
> [no issue] reduce memory usage

- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/strategy/UnsignedIntegerEncodingStrategy.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/strategy/UnsignedLongEncodingStrategy.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/strategy/UnsignedShortEncodingStrategy.java
Goes from throwing null pointer exception to illegal argument exception with a message.
> Throws explicit exception when encoding header code is unknown

- bootstrap-core/pom.xml
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/context/AsyncTraceCloseable.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/context/Trace.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/context/TraceContext.java
- profiler/pom.xml
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/CloseableAsyncTraceId.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTraceContext.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/ThreadLocalTraceFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/TraceFactory.java
#1417
- added @InterfaceAudience.LimitedPrivate
> #1417 add vert.x plugin

- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/AsyncTraceCloser.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/CloseableAsyncTraceId.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/SpanCompletionCallback.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/ThreadLocalTraceFactory.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/AsyncTraceCloserTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/SpanCompletionCallbackTest.java
> #2524 refatoring async propagation API

- agent/pom.xml
- agent/src/assembly/distribution.xml
- annotations/src/main/java/com/navercorp/pinpoint/common/annotations/InterfaceAudience.java
- annotations/src/main/java/com/navercorp/pinpoint/common/annotations/InterfaceStability.java
- annotations/src/main/java/com/navercorp/pinpoint/common/annotations/VisibleForTesting.java
- bootstrap/pom.xml
- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/AgentDirBaseClassPathResolver.java
- bootstrap/src/test/java/com/navercorp/pinpoint/bootstrap/AgentDirBaseClassPathResolverTest.java
- bootstrap/src/test/java/com/navercorp/pinpoint/bootstrap/AgentDirGenerator.java
#2477
- RetentionPolicy.SOURCE -> RetentionPolicy.RUNTIME
> #2477 change RetentionPolicy

- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/context/AsyncState.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/context/AsyncStateSupport.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/SpanAsyncEventSimpleAroundInterceptor.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/AsyncTrace.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/ListenableAsyncState.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/SpanAsyncStateListener.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/StatefulAsyncTraceId.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/ThreadLocalTraceFactory.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/ListenableAsyncStateTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/SpanAsyncStateListenerTest.java
> #2524 refactoring async api

- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/SpanAsyncEventSimpleAroundInterceptor.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTrace.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/ThreadLocalTraceFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/storage/LogStorageFactory.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/DefaultTraceTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/TraceTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/receiver/service/ActiveThreadServiceTest.java
#2524
- remove setter of DefaultTrace
> #2524 Improved immutability of Trace

- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTrace.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/ThreadLocalTraceFactory.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/DefaultTraceTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/receiver/service/ActiveThreadServiceTest.java
#2524 
- remove duplicate constructor
> #2524 remove duplicate constructor

- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/BaseTraceFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultBaseTraceFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTraceContext.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/LoggingBaseTraceFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/MetricTraceFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/ThreadLocalTraceFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/TraceFactory.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/ThreadLocalTraceFactoryTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/receiver/service/ActiveThreadServiceTest.java
- extract BaseTraceFactory
- add testcase
> #2524 TraceFactory refactoring

- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/DefaultProfilerConfig.java
- plugins/tomcat/src/test/java/com/navercorp/pinpoint/plugin/tomcat/InvokeMethodInterceptorTest.java
- profiler-test/src/main/java/com/navercorp/pinpoint/test/MockTraceContextFactory.java
- profiler-test/src/test/java/com/navercorp/pinpoint/test/monitor/AgentStatMonitorTest.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/DefaultAgent.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/AsyncIdGenerator.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTraceContext.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTraceFactoryBuilder.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/PluginMonitorContextBuilder.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/SystemPropertyDumper.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/TraceFactoryBuilder.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/active/ActiveTraceFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/monitor/codahale/AgentStatCollectorFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/service/ActiveThreadService.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/DefaultTraceContextTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/DefaultTraceTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/MockTraceContextFactory.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/TraceTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/active/ActiveTraceRepositoryTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/monitor/codahale/gc/GarbageCollectorFactoryTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/receiver/service/ActiveThreadServiceTest.java
> #2524 refactoring object wiring codebase

- plugins/jboss/src/test/java/com/navercorp/pinpoint/plugin/jboss/InvokeMethodInterceptorTest.java
- profiler-test/src/main/java/com/navercorp/pinpoint/test/MockTraceContextFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/DefaultAgent.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTraceContext.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/metadata/ApiMetaDataCacheService.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/metadata/ApiMetaDataService.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/metadata/SqlMetaDataCacheService.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/metadata/SqlMetaDataService.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/metadata/SqlNormalizer.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/metadata/StringMetaDataCacheService.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/metadata/StringMetaDataService.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/DefaultTraceContextTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/MockTraceContextFactory.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/TraceTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/active/ActiveTraceRepositoryTest.java
#2524
- extract MetaDataService
- remove setter
> #2524 refactoring TraceContext

- plugins/tomcat/src/test/java/com/navercorp/pinpoint/plugin/tomcat/InvokeMethodInterceptorTest.java
> #2524 fix testcase fail

- web/src/main/webapp/common/help/help-content-en.js
- web/src/main/webapp/common/help/help-content-ko.js
- web/src/main/webapp/common/services/agent-dao.service.js
- web/src/main/webapp/common/services/tooltip.service.js
- web/src/main/webapp/features/agentInfo/agent-info.directive.js
- web/src/main/webapp/features/agentInfo/agentInfoMain.html
- web/src/main/webapp/features/dataSourceChart/data-source-chart.directive.js
change y axis-value of datasource-chart.
update detail info ui.
add tooltip of datasource-chart.
> update datasource-chart features

- web/src/main/webapp/common/services/agent-dao.service.js
- web/src/main/webapp/features/activeTraceChart/active-trace-chart.directive.js
- web/src/main/webapp/features/agentInfo/agent-info.directive.js
- web/src/main/webapp/features/agentInfo/agentInfoMain.html
- web/src/main/webapp/features/cpuLoadChart/cpu-load-chart.directive.js
- web/src/main/webapp/features/dataSourceChart/data-source-chart.directive.js
- web/src/main/webapp/features/jvmMemoryChart/jvm-memory-chart.directive.js
- web/src/main/webapp/features/realtimeChart/realtime-chart.controller.js
- web/src/main/webapp/features/threadDumpInfoLayer/thread-dump-info-layer.directive.js
- web/src/main/webapp/features/threadDumpInfoLayer/threadDumpInfoLayer.html
- web/src/main/webapp/features/tpsChart/tps-chart.directive.js
update detail-info ui of data-source
bug fix.
- can't update chart data.
- display wrong option in select box .
> update data-source chart features.

- web/src/main/webapp/features/dataSourceChart/data-source-chart.directive.js
- web/src/main/webapp/features/navbar/navbar.html
- web/src/main/webapp/pages/transactionList/transaction-list.controller.js
remove max-connection field color.
> attempt 3 times when there is no response to the request(transaction-list)

- web/src/main/webapp/common/services/agent-dao.service.js
- web/src/main/webapp/features/agentInfo/agent-info.directive.js
- web/src/main/webapp/features/agentInfo/agentInfoMain.html
- web/src/main/webapp/features/realtimeChart/realtime-chart.controller.js
- web/src/main/webapp/features/threadDumpInfoLayer/thread-dump-info-layer.directive.js
display "NOT FOUND" when data-source-chart result has "-1".
> add configuration for use of thread-dump-layer and data-source-chart.

- web/src/main/java/com/navercorp/pinpoint/web/config/ConfigProperties.java
- web/src/main/java/com/navercorp/pinpoint/web/controller/AgentCommandController.java
- web/src/main/java/com/navercorp/pinpoint/web/controller/ConfigController.java
- web/src/main/resources/pinpoint-web.properties
Adds the enable / disable option for some features of the web module.
1. config.show.activeThreadDump
2. config.show.inspector.dataSource
3. config.enable.activeThreadDump
> [#2581] Adds the enable / disable option for web module

- web/pom.xml
Change the default option to not use lint.
> [no issue] change the grunt build default option

- profiler-test/src/main/java/com/navercorp/pinpoint/test/MockPluginContextLoadResult.java
- profiler-test/src/main/java/com/navercorp/pinpoint/test/MockPluginContextLoadResultProvider.java
- profiler-test/src/main/java/com/navercorp/pinpoint/test/MockPluginSetup.java
- profiler-test/src/main/java/com/navercorp/pinpoint/test/classloader/TestClassLoader.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/ClassFileTransformerDispatcher.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/DefaultClassFileTransformerDispatcher.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/ApplicationContextModule.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/ClassFileTransformerDispatcherProvider.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/DynamicTransformTriggerProvider.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/PluginContextLoadResultProvider.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/ClassFileTransformerLoader.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/DefaultPluginContextLoadResult.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/DefaultPluginSetup.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/DefaultProfilerPluginContext.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/PluginInstrumentContext.java
[#2524]
- reduce cycle dependency
- reduce dependencies on DynamicTransformTrigger
> [#2524] refatoring profiler

- profiler/pom.xml
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/graph/DependencyGraph.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/graph/Grapher.java
[#2524]
-  add guice dependency graph
> [#2524] add guice dependency graph

- plugins/jboss/README.md
> [#2612] add jboss logmanager setting

- web/src/main/java/com/navercorp/pinpoint/web/cluster/DefaultPinpointRouteResponse.java
- web/src/main/java/com/navercorp/pinpoint/web/controller/AgentCommandController.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/AgentActiveThreadDumpFactory.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/AgentActiveThreadDumpList.java
- web/src/test/java/com/navercorp/pinpoint/web/cluster/PinpointRouteResponseTest.java
- web/src/test/java/com/navercorp/pinpoint/web/view/AgentActiveThreadDumpListSerializerTest.java
- web/src/test/java/com/navercorp/pinpoint/web/vo/AgentActiveThreadDumpListTest.java
add message for failed response
> [#2286] Add function of getting thread dump from agent

- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTrace.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTransactionCounter.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/TransactionCounter.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/monitor/codahale/tps/metric/TransactionMetricSet.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/DefaultTraceContextTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/DefaultTransactionCounterTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/MockTraceContextFactory.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/TestableTransactionCounter.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/active/ActiveTraceRepositoryTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/monitor/codahale/tps/metric/TransactionMetricSetTest.java
> [#2524] Refactor TransactionCounter

- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/DefaultProfilerConfig.java
- profiler-test/src/main/java/com/navercorp/pinpoint/test/MockTraceContextFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/ApplicationContextModule.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/CallStackFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultBaseTraceFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultCallStackFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultRecorderFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultSpanFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultSpanRecorder.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTrace.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTraceContext.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTraceId.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTraceIdFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/RecorderFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/SpanFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/TraceIdFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/StorageFactoryProvider.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/TraceContextProvider.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/TraceFactoryProvider.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/DefaultSpanRecorderTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/DefaultTraceTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/MockTraceContextFactory.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/TraceTest.java
> [#2524] Refactor Trace

- web/src/main/webapp/common/help/help-content-en.js
- web/src/main/webapp/common/help/help-content-ko.js
- web/src/main/webapp/features/threadDumpInfoLayer/thread-dump-info-layer.directive.js
update datasource help script.
> add parameter when open transaction-list window in thread-dump window.

- collector/src/main/resources/applicationContext-hbase.xml
- collector/src/main/resources/hbase.properties
- quickstart/collector/src/main/resources/hbase.properties
- web/src/main/resources/applicationContext-hbase.xml
- web/src/main/resources/hbase.properties
Signed-off-by: Jacarri Chan <772929989@qq.com>
> add  hbase  Configuration about Root ZNode for HBase in ZooKeeper

- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/instrument/InstrumentEngine.java
- profiler-test/src/test/java/com/navercorp/pinpoint/test/javasssit/JavassistClassTest.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/InstrumentEngineProvider.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/PluginContextLoadResultProvider.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMEngine.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/BootstrapClassLoaderHandler.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/JarProfilerPluginClassInjector.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/JavassistClass.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/JavassistEngine.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/PlainClassLoaderHandler.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/DefaultPluginContextLoadResult.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/plugin/ProfilerPluginLoader.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/JarProfilerPluginClassInjectorTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/JavassistClassPoolTest.java
[#2524] 
- cleanup InstrumentEngine
> [#2524] cleanup InstrumentEngine

- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/resolver/condition/MainClassCondition.java
> Adds guide log for when application main cannot be detected

- plugins/vertx/pom.xml
- plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/VertxPlugin.java
> add annotation.

- agent/src/main/resources-local/pinpoint.config
- agent/src/main/resources-release/pinpoint.config
- agent/src/main/resources/pinpoint-real-env-lowoverhead-sample.config
- plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/VertxConfig.java
- quickstart/agent/src/main/resources/pinpoint.config
- quickstart/conf/pinpoint.config
> Change the vertx default setting to disable.

- agent/src/main/resources-local/pinpoint.config
- agent/src/main/resources-release/pinpoint.config
- agent/src/main/resources/pinpoint-real-env-lowoverhead-sample.config
- plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/VertxPlugin.java
- quickstart/agent/src/main/resources/pinpoint.config
- quickstart/conf/pinpoint.config
> add a warning document.

- commons-server/src/test/java/com/navercorp/pinpoint/common/server/util/AgentEventMessageSerDesTest.java
> [#noissue] fix_test

- collector/pom.xml
update collector's animal-sniffer configuration to java17
> [#noissue] update animal-sniffer configuration

- web/src/main/java/com/navercorp/pinpoint/web/controller/ConfigController.java
added version field to configuration rest api result .
> [#noissue] added version field to configuration rest api result

- agent/pom.xml
- agent/src/test/java/com/navercorp/pinpoint/plugin/SocketUtils.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/WebServer.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/google/httpclient/HttpRequestIT.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/httpclient3/HttpClientIT.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/httpclient4/CloaeableHttpClientIT.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/httpclient4/ClosableAsyncHttpClientIT.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/httpclient4/HttpClientIT.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/jdk/http/HttpURLConnectionIT.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/jdk7/okhttp/OkHttpClientBackwardCompatibilityIT.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/jdk7/okhttp/OkHttpClientIT.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/ning/asynchttpclient/NingAsyncHttpClientIT.java
> [#2762] Improved remote call testcase.

- bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/interceptor/DriverConnectInterceptorTest.java
- collector/src/test/java/com/navercorp/pinpoint/collector/rpc/handler/AgentEventHandlerTest.java
- collector/src/test/java/com/navercorp/pinpoint/collector/rpc/handler/AgentLifeCycleHandlerTest.java
- commons/src/test/java/com/navercorp/pinpoint/common/util/DelegateEnumerationTest.java
- plugins/cxf/src/test/java/com/navercorp/pinpoint/plugin/cxf/interceptor/CxfClientInvokeSyncMethodInterceptorTest.java
- plugins/jboss/src/test/java/com/navercorp/pinpoint/plugin/jboss/InvokeMethodInterceptorTest.java
- plugins/spring/src/test/java/com/navercorp/pinpoint/plugin/spring/beans/interceptor/BeanMethodInterceptorTest.java
- plugins/tomcat/src/test/java/com/navercorp/pinpoint/plugin/tomcat/InvokeMethodInterceptorTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/ListenableAsyncStateTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/SpanAsyncStateListenerTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/BytecodeDumpServiceTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/metadata/DefaultApiMetaDataServiceTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/metadata/DefaultSqlMetaDataServiceTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/metadata/DefaultStringMetaDataServiceTest.java
- times(1) -> only()
- times(0) -> never()
> [#noissue] cleanup testcase

- collector/src/test/java/com/navercorp/pinpoint/collector/manage/jmx/PinpointMBeanServerTest.java
> [#noissue] fix testcase compatibility for java8

- collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseMapResponseTimeDao.java
- collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseMapStatisticsCalleeDao.java
- collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseMapStatisticsCallerDao.java
- collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/statistics/RowKeyMerge.java
- collector/src/main/java/com/navercorp/pinpoint/collector/util/AtomicLongMapUtils.java
- collector/src/main/java/com/navercorp/pinpoint/collector/util/ConcurrentCounterMap.java
- collector/src/test/java/com/navercorp/pinpoint/collector/util/AtomicLongMapTest.java
- collector/src/test/java/com/navercorp/pinpoint/collector/util/ConcurrentCounterMapTest.java
> [#2784] Replace with AtomicLongMap

- collector/src/main/java/com/navercorp/pinpoint/collector/cluster/zookeeper/ZookeeperJobWorker.java
- collector/src/main/java/com/navercorp/pinpoint/collector/cluster/zookeeper/job/ZookeeperJob.java
- collector/src/test/java/com/navercorp/pinpoint/collector/TestAwaitUtils.java
- collector/src/test/java/com/navercorp/pinpoint/collector/cluster/zookeeper/ZookeeperJobWorkerTest.java
- web/src/main/java/com/navercorp/pinpoint/web/cluster/zookeeper/ZookeeperClusterDataManager.java
handling per event -> handling bulk
> [#2793] Change ZOOKEEPER event registration method.

- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/AgentDirBaseClassPathResolver.java
- collector/src/main/java/com/navercorp/pinpoint/collector/cluster/route/DefaultRouteHandler.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/AgentEventType.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/ApiDescriptionParser.java
- commons/src/main/java/com/navercorp/pinpoint/common/util/ArrayUtils.java
- commons/src/main/java/com/navercorp/pinpoint/common/util/DefaultApiDescription.java
- plugins/cxf/src/main/java/com/navercorp/pinpoint/plugin/cxf/interceptor/CxfClientInvokeSyncMethodInterceptor.java
- profiler-test/src/main/java/com/navercorp/pinpoint/test/MethodDescriptionUtils.java
- profiler-test/src/main/java/com/navercorp/pinpoint/test/PluginTestAgent.java
- profiler-test/src/test/java/com/navercorp/pinpoint/test/javasssit/JavassistClassTest.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/JavassistClass.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/logging/Slf4jPLoggerAdapter.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/SpanStreamSendData.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/util/ByteBufferUtils.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/util/JavaAssistUtils.java
- web/src/main/java/com/navercorp/pinpoint/web/cluster/DefaultPinpointRouteResponse.java
> #2800 Add isEmpty() to ArrayUtils

- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/storage/BufferedStorage.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/storage/BufferedStorageTest.java
> [#2726] Reduce memory usage in BufferedStorage

- README.md
- collector/pom.xml
- commons-hbase/pom.xml
- commons-server/pom.xml
- doc/installation.md
- web/pom.xml
Bumping JDK versions of any modules not related to agent to 8.
> Bumps collector/web jdk versions to 8

- commons/src/main/java/com/navercorp/pinpoint/common/buffer/AutomaticBuffer.java
- commons/src/main/java/com/navercorp/pinpoint/common/buffer/Buffer.java
- commons/src/main/java/com/navercorp/pinpoint/common/buffer/FixedBuffer.java
- commons/src/main/java/com/navercorp/pinpoint/common/buffer/OffsetAutomaticBuffer.java
- commons/src/main/java/com/navercorp/pinpoint/common/buffer/OffsetFixedBuffer.java
- Remove deprecated Buffer APIs
> [##2823] Cleanup deprecated APIs

- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/context/TraceContext.java
- plugins/arcus/src/main/java/com/navercorp/pinpoint/plugin/arcus/interceptor/ApiInterceptor.java
> [#2826] Deprecate TraceContext.getAsyncId()

- web/src/main/java/com/navercorp/pinpoint/web/vo/timeline/inspector/AgentEventTimelineBuilder.java
- web/src/main/webapp/common/services/tooltip.service.js
- web/src/main/webapp/components/big-scatter-chart/BigScatterChart2.DataLoadManager.js
- web/src/main/webapp/components/big-scatter-chart/BigScatterChart2.js
- web/src/main/webapp/components/server-map2/jquery.ServerMap2.js
- web/src/main/webapp/components/time-slider/time-slider.events.js
- web/src/main/webapp/features/agentInfo/agentInfoMain.html
- web/src/main/webapp/features/realtimeChart/realtime-chart.directive.js
- web/src/main/webapp/features/serverList/server-list.directive.js
- web/src/main/webapp/features/serverMap/server-map.directive.js
- web/src/main/webapp/features/serverMap/serverMap.html
update default agent event count.
> update server-map realtime code for test.

- test/src/main/java/com/navercorp/pinpoint/test/plugin/PinpointPluginTestStatement.java
> trim if line end with \\r.

- agent/src/test/java/com/navercorp/pinpoint/plugin/jdk7/activemq/client/ActiveMQClientITBase.java
Protocol is now collected when tracing end points and remote address #2740 
Should fix the integration tests accordingly.
resolves #2702
> Fixes ActiveMQ integration tests

- profiler-test/src/main/java/com/navercorp/pinpoint/test/CompressingStorageDecorator.java
- profiler-test/src/main/java/com/navercorp/pinpoint/test/OrderedSpanRecorder.java
- profiler-test/src/main/java/com/navercorp/pinpoint/test/PluginApplicationContextModule.java
- profiler-test/src/main/java/com/navercorp/pinpoint/test/SimpleSpanStorageFactory.java
- profiler-test/src/test/java/com/navercorp/pinpoint/test/OrderedSpanRecorderTest.java
related to #2853 
resolves #2858
> Fixes asynchronous span event verification issues

- plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/interceptor/Jetty8ServerHandleInterceptor.java
- plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/interceptor/ServerHandleInterceptor.java
- plugins/log4j/src/main/java/com/navercorp/pinpoint/plugin/log4j/Log4jPlugin.java
- plugins/log4j/src/main/java/com/navercorp/pinpoint/plugin/log4j/interceptor/LoggingEventOfLog4jInterceptor.java
- plugins/logback/src/main/java/com/navercorp/pinpoint/plugin/logback/LogbackPlugin.java
- plugins/logback/src/main/java/com/navercorp/pinpoint/plugin/logback/interceptor/LoggingEventOfLogbackInterceptor.java
- plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/TomcatPlugin.java
- plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/interceptor/AsyncContextImplDispatchMethodInterceptor.java
> Remove code using annotation logic

- plugins/cxf/src/main/java/com/navercorp/pinpoint/plugin/cxf/CxfPlugin.java
- plugins/cxf/src/main/java/com/navercorp/pinpoint/plugin/cxf/interceptor/CxfClientInvokeSyncMethodInterceptor.java
- plugins/dbcp/src/main/java/com/navercorp/pinpoint/plugin/commons/dbcp/CommonsDbcpPlugin.java
- plugins/dbcp/src/main/java/com/navercorp/pinpoint/plugin/commons/dbcp/interceptor/DataSourceCloseConnectionInterceptor.java
- plugins/dbcp/src/main/java/com/navercorp/pinpoint/plugin/commons/dbcp/interceptor/DataSourceCloseInterceptor.java
- plugins/dbcp/src/main/java/com/navercorp/pinpoint/plugin/commons/dbcp/interceptor/DataSourceConstructorInterceptor.java
- plugins/dbcp/src/main/java/com/navercorp/pinpoint/plugin/commons/dbcp/interceptor/DataSourceGetConnectionInterceptor.java
- plugins/dbcp2/src/main/java/com/navercorp/pinpoint/plugin/commons/dbcp2/CommonsDbcp2Plugin.java
- plugins/dbcp2/src/main/java/com/navercorp/pinpoint/plugin/commons/dbcp2/interceptor/DataSourceCloseConnectionInterceptor.java
- plugins/dbcp2/src/main/java/com/navercorp/pinpoint/plugin/commons/dbcp2/interceptor/DataSourceCloseInterceptor.java
- plugins/dbcp2/src/main/java/com/navercorp/pinpoint/plugin/commons/dbcp2/interceptor/DataSourceConstructorInterceptor.java
- plugins/dbcp2/src/main/java/com/navercorp/pinpoint/plugin/commons/dbcp2/interceptor/DataSourceGetConnectionInterceptor.java
> [#2862] remove annotation

- plugins/activemq-client/src/main/java/com/navercorp/pinpoint/plugin/activemq/client/ActiveMQClientPlugin.java
- plugins/activemq-client/src/main/java/com/navercorp/pinpoint/plugin/activemq/client/interceptor/ActiveMQMessageConsumerDispatchInterceptor.java
- plugins/activemq-client/src/main/java/com/navercorp/pinpoint/plugin/activemq/client/interceptor/ActiveMQMessageConsumerReceiveInterceptor.java
- plugins/activemq-client/src/main/java/com/navercorp/pinpoint/plugin/activemq/client/interceptor/ActiveMQMessageProducerSendInterceptor.java
- plugins/activemq-client/src/main/java/com/navercorp/pinpoint/plugin/activemq/client/interceptor/MessageDispatchChannelDequeueInterceptor.java
- plugins/activemq-client/src/main/java/com/navercorp/pinpoint/plugin/activemq/client/interceptor/MessageDispatchChannelEnqueueInterceptor.java
- plugins/cassandra/src/main/java/com/navercorp/pinpoint/plugin/cassandra/CassandraPlugin.java
- plugins/cassandra/src/main/java/com/navercorp/pinpoint/plugin/cassandra/interceptor/CassandraConnectionCloseInterceptor.java
- plugins/cassandra/src/main/java/com/navercorp/pinpoint/plugin/cassandra/interceptor/CassandraDriverConnectInterceptor.java
- plugins/cassandra/src/main/java/com/navercorp/pinpoint/plugin/cassandra/interceptor/CassandraPreparedStatementCreateInterceptor.java
- plugins/cassandra/src/main/java/com/navercorp/pinpoint/plugin/cassandra/interceptor/CassandraStatementExecuteQueryInterceptor.java
- plugins/hystrix/src/main/java/com/navercorp/pinpoint/plugin/hystrix/interceptor/HystrixCommandExecuteCommandInterceptor.java
- plugins/hystrix/src/main/java/com/navercorp/pinpoint/plugin/hystrix/interceptor/HystrixCommandGetFallbackOrThrowExceptionInterceptor.java
- plugins/hystrix/src/main/java/com/navercorp/pinpoint/plugin/hystrix/transformer/HystrixCommandTransformer.java
- plugins/resin/src/main/java/com/navercorp/pinpoint/plugin/resin/ResinPlugin.java
- plugins/resin/src/main/java/com/navercorp/pinpoint/plugin/resin/interceptor/AsyncContextImplDispatchMethodInterceptor.java
- plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/ThriftPlugin.java
- plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/interceptor/client/TServiceClientSendBaseInterceptor.java
- plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/interceptor/client/async/TAsyncClientManagerCallInterceptor.java
- plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/interceptor/server/ProcessFunctionProcessInterceptor.java
- plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/interceptor/server/TBaseProcessorProcessInterceptor.java
- plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/interceptor/server/async/TBaseAsyncProcessorProcessInterceptor.java
- plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/interceptor/tprotocol/client/TProtocolWriteFieldStopInterceptor.java
- plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/interceptor/tprotocol/server/TProtocolReadFieldBeginInterceptor.java
- plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/interceptor/tprotocol/server/TProtocolReadMessageBeginInterceptor.java
- plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/interceptor/tprotocol/server/TProtocolReadMessageEndInterceptor.java
- plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/interceptor/tprotocol/server/TProtocolReadTTypeInterceptor.java
Removes annotations from interceptors in : 
Activemq-client plugin
Thrift plugin
Cassandra driver plugin
Hystrix plugin
Resin plugin
related to #2862
> Removes annotations from interceptors in various plugins

- plugins/cubrid-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/cubrid/CubridPlugin.java
> [#2862] remove code using annotation logic in cubrid plugin

- profiler/src/main/java/com/navercorp/pinpoint/profiler/monitor/CollectJob.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/monitor/DefaultAgentStatMonitor.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/EmptyDataSender.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/monitor/CollectJobTest.java
> [#2881] dead lock workaround

- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/interceptor/CallableStatementBindVariableInterceptor.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/interceptor/CallableStatementExecuteQueryInterceptor.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/interceptor/CallableStatementRegisterOutParameterInterceptor.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/interceptor/ConnectionCloseInterceptor.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/interceptor/DriverConnectInterceptor.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/interceptor/DriverConnectInterceptorV2.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/interceptor/PreparedStatementBindVariableInterceptor.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/interceptor/PreparedStatementCreateInterceptor.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/interceptor/PreparedStatementExecuteQueryInterceptor.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/interceptor/StatementCreateInterceptor.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/interceptor/StatementExecuteQueryInterceptor.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/interceptor/StatementExecuteUpdateInterceptor.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/interceptor/TransactionCommitInterceptor.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/interceptor/TransactionRollbackInterceptor.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/interceptor/TransactionSetAutoCommitInterceptor.java
- plugins/mysql-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/mysql/interceptor/MySQLConnectionCreateInterceptor.java
- plugins/ning-asynchttpclient/src/main/java/com/navercorp/pinpoint/plugin/ning/asynchttpclient/interceptor/ExecuteRequestInterceptor.java
- plugins/postgresql-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/postgresql/interceptor/PostgreSQLConnectionCreateInterceptor.java
- plugins/postgresql-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/postgresql/interceptor/PostgreSqlPreparedStatementCreateInterceptor1.java
- plugins/postgresql-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/postgresql/interceptor/PostgreSqlPreparedStatementCreateInterceptor2.java
- plugins/postgresql-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/postgresql/interceptor/PostgreSqlPreparedStatementCreateInterceptor3.java
> [#2862] Remove @IgnoreMethod

- profiler/src/main/java/com/navercorp/pinpoint/profiler/monitor/CollectJob.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/monitor/DefaultAgentStatMonitor.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/sender/EmptyDataSender.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/monitor/CollectJobTest.java
#2920 
- #2881 backport
- pre-load CollectJob
> [#2920] dead lock workaround

- collector/src/main/java/com/navercorp/pinpoint/collector/cluster/zookeeper/ZookeeperJobWorker.java
- collector/src/main/java/com/navercorp/pinpoint/collector/cluster/zookeeper/ZookeeperProfilerClusterManager.java
- web/src/main/java/com/navercorp/pinpoint/web/cluster/CollectorClusterInfoRepository.java
- web/src/main/java/com/navercorp/pinpoint/web/cluster/connection/ClusterConnector.java
- web/src/test/java/com/navercorp/pinpoint/web/cluster/connection/ClusterConnectorTest.java
- Reduce dependency of common module
> [#noissue] code cleanup

- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/monitor/DefaultJdbcUrlParsingService.java
> fix jdbc parser.

- pom.xml
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMClassNodeAdapter.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/ASMClassNodeAdapterTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/ASMClassWriterTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/monitor/CollectJobTest.java
* ASM : 5.1 -> 5.2
* Guava : 19.0 -> 20.0
* Mockito : mockito-all 1.10.19 -> mockito-core 2.7.22
* commons-beanutils : 1.8.3 -> 1.9.3
* aspectjweaver : 1.8.9 -> 1.8.10
* Spring : 4.1.9.RELEASE -> 4.3.8.RELEASE
* Spring Batch : 2.2.7.RELEASE -> 3.0.7.RELEASE
* Spring Security : 4.0.4.RELEASE -> 4.2.2.RELEASE
resolve #2789
> Updates various libraries

- agent/src/main/resources-local/pinpoint.config
- agent/src/main/resources-release/pinpoint.config
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/DefaultProfilerConfig.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/ProfilerConfig.java
- commons/src/main/java/com/navercorp/pinpoint/common/util/ThreadMXBeanUtils.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/ApplicationContextModule.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/DefaultApplicationContext.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/DeadlockMonitorProvider.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/DeadlockThreadRegistryProvider.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/monitor/DeadlockMonitor.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/monitor/DeadlockMonitorTask.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/monitor/DeadlockMonitorThread.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/monitor/DeadlockThreadLocator.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/monitor/DeadlockThreadRegistry.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/monitor/DefaultDeadlockMonitor.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/monitor/DisabledDeadlockMonitor.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/monitor/DeadlockMonitorJobTest.java
deadlock information to the local log.
> [#2941] Add function of checking if deadlock occurred in agent

- web/src/main/java/com/navercorp/pinpoint/web/filter/LinkFilter.java
Previous conditional statement was too confusing and hard to follow.
> Refactors rpc hint filter logic

- collector/src/main/java/com/navercorp/pinpoint/collector/cluster/zookeeper/PinpointServerRepository.java
- collector/src/main/java/com/navercorp/pinpoint/collector/cluster/zookeeper/ZookeeperClient.java
- collector/src/main/java/com/navercorp/pinpoint/collector/cluster/zookeeper/ZookeeperJobWorker.java
- collector/src/main/java/com/navercorp/pinpoint/collector/cluster/zookeeper/ZookeeperProfilerClusterManager.java
- collector/src/main/java/com/navercorp/pinpoint/collector/cluster/zookeeper/job/ZookeeperJob.java
- collector/src/test/java/com/navercorp/pinpoint/collector/cluster/zookeeper/ZookeeperJobWorkerTest.java
- reduce synchronized block
- missing synchronized block
- remove unused code
- code cleanup
> [#noissue] Refactor ZK code

- flink/.gitignore
- flink/clover.license
> [#2970] Add clover license & gitignore

- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/udp/UDPReceiver.java
- collector/src/test/java/com/navercorp/pinpoint/collector/receiver/udp/TestUDPReceiver.java
- commons/src/main/java/com/navercorp/pinpoint/common/util/CpuUtils.java
- profiler-optional/profiler-optional-jdk6/src/main/java/com/navercorp/pinpoint/profiler/monitor/metric/cpu/ibm/Java6CpuLoadMetric.java
- profiler-optional/profiler-optional-jdk6/src/main/java/com/navercorp/pinpoint/profiler/monitor/metric/cpu/oracle/Java6CpuLoadMetric.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/monitor/DefaultAgentStatMonitor.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/server/PinpointServerAcceptor.java
- web/src/main/java/com/navercorp/pinpoint/web/websocket/ActiveThreadCountHandler.java
(cherry picked from commit f96ba8f)
> [#2957] Use preload to avoid deadlocks.

- web/src/main/webapp/features/serverList/server-list.directive.js
> [#noissue] bug fix.

- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultServerMetaDataHolder.java
use synchronized to prevent race condition
> [#2993] Server metadata listener notification has a race condition

- agent/src/main/resources-local/pinpoint.config
- agent/src/main/resources-release/pinpoint.config
- agent/src/main/resources/pinpoint-real-env-lowoverhead-sample.config
- commons/src/main/java/com/navercorp/pinpoint/common/trace/ServiceType.java
- plugins/jsp/.gitignore
- plugins/jsp/clover.license
- plugins/jsp/pom.xml
- plugins/jsp/src/main/java/com/navercorp/pinpoint/plugin/jsp/JspConstants.java
- plugins/jsp/src/main/java/com/navercorp/pinpoint/plugin/jsp/JspPlugin.java
- plugins/jsp/src/main/java/com/navercorp/pinpoint/plugin/jsp/JspPluginConfig.java
- plugins/jsp/src/main/java/com/navercorp/pinpoint/plugin/jsp/JspTypeProvider.java
- plugins/jsp/src/main/java/com/navercorp/pinpoint/plugin/jsp/interceptor/HttpJspBaseServiceMethodInterceptor.java
- plugins/jsp/src/main/resources/META-INF/services/com.navercorp.pinpoint.bootstrap.plugin.ProfilerPlugin
- plugins/jsp/src/main/resources/META-INF/services/com.navercorp.pinpoint.common.trace.TraceMetadataProvider
- plugins/jsp/src/test/java/com/navercorp/pinpoint/plugin/jsp/interceptor/HttpJspBaseServiceMethodInterceptorTest.java
- plugins/jsp/src/test/resources/pinpoint.config
- plugins/pom.xml
> [#2987] add JSP plugin.

- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTraceContext.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/ThreadLocalTraceFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/TraceFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/active/ActiveTraceFactory.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/ThreadLocalTraceFactoryTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/monitor/metric/rpc/MetricTraceFactory.java
- Remove TraceContext#currentRpcTraceObject API
> [#noissue] Remove unused api

- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/BaseTraceFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultBaseTraceFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTraceContext.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/LoggingBaseTraceFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/ThreadLocalTraceFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/active/ActiveTraceFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/id/DefaultAsyncTraceId.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/id/DefaultTraceRootFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/id/StatefulAsyncTraceId.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/id/TraceRootSupport.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/monitor/metric/rpc/MetricTraceFactory.java
> [#2584] Refactor TraceFactory

- plugins/dubbo/src/main/java/com/navercorp/pinpoint/plugin/dubbo/interceptor/DubboConsumerInterceptor.java
- plugins/dubbo/src/main/java/com/navercorp/pinpoint/plugin/dubbo/interceptor/DubboProviderInterceptor.java
> Fixes Dubbo consumer interceptor to propagate disable flags

- profiler-test/src/main/java/com/navercorp/pinpoint/test/MockTraceContextFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/ThreadLocalBinder.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/ThreadLocalReference.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/ThreadLocalReferenceFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/ThreadLocalTraceReference.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/TraceFactoryProvider.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/MockTraceContextFactory.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/ThreadLocalFactoryAbstractTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/ThreadLocalReferenceFactoryTest.java
#3014
- Reduce ThreadLocal access
- Reduce ThreadLocalMap#Entry creation
> [#3014] Improved ThreadLocal performance

- plugins/redis/src/main/java/com/navercorp/pinpoint/plugin/redis/CommandContextFormatter.java
- plugins/redis/src/main/java/com/navercorp/pinpoint/plugin/redis/EndPointUtils.java
- plugins/redis/src/main/java/com/navercorp/pinpoint/plugin/redis/RedisPlugin.java
- plugins/redis/src/main/java/com/navercorp/pinpoint/plugin/redis/interceptor/JedisClientConstructorInterceptor.java
- plugins/redis/src/main/java/com/navercorp/pinpoint/plugin/redis/interceptor/JedisConstructorInterceptor.java
- plugins/redis/src/main/java/com/navercorp/pinpoint/plugin/redis/interceptor/JedisMethodInterceptor.java
- plugins/redis/src/main/java/com/navercorp/pinpoint/plugin/redis/interceptor/JedisPipelineMethodInterceptor.java
- plugins/redis/src/main/java/com/navercorp/pinpoint/plugin/redis/interceptor/ProtocolSendCommandAndReadMethodInterceptor.java
- Remove duplicate code
- code cleanup
> [#noissue] Refactor Jedis

- commons/src/main/java/com/navercorp/pinpoint/common/util/StringUtils.java
- plugins/httpclient3/src/main/java/com/navercorp/pinpoint/plugin/httpclient3/interceptor/HttpMethodBaseExecuteMethodInterceptor.java
- plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/HttpRequestExecutorExecuteMethodInterceptor.java
- plugins/jboss/src/main/java/com/navercorp/pinpoint/plugin/jboss/interceptor/StandardHostValveInvokeInterceptor.java
- plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/interceptor/AbstractServerHandleInterceptor.java
- plugins/resin/src/main/java/com/navercorp/pinpoint/plugin/resin/ResinDetector.java
- plugins/resin/src/main/java/com/navercorp/pinpoint/plugin/resin/interceptor/ServletInvocationInterceptor.java
- plugins/spring/src/main/java/com/navercorp/pinpoint/plugin/spring/beans/SpringBeansConfig.java
- plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/interceptor/StandardHostValveInvokeInterceptor.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/Span.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/SpanEvent.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/recorder/WrappedSpanEventRecorder.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/client/PinpointClientHandshaker.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/server/DefaultPinpointServer.java
#2815
- isNotEmpty(String) -> hasLength(String)
> [#2815] Change StringUtils API

- collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/stat/HbaseDataSourceListDao.java
- commons/src/main/java/com/navercorp/pinpoint/common/util/CollectionUtils.java
- commons/src/test/java/com/navercorp/pinpoint/common/util/CollectionUtilsTest.java
- plugins/ning-asynchttpclient/src/main/java/com/navercorp/pinpoint/plugin/ning/asynchttpclient/interceptor/ExecuteRequestInterceptor.java
- plugins/spring/src/main/java/com/navercorp/pinpoint/plugin/spring/beans/SpringBeansTarget.java
- plugins/spring/src/main/java/com/navercorp/pinpoint/plugin/spring/beans/interceptor/TargetBeanFilter.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/storage/BufferedStorage.java
- web/src/test/java/com/navercorp/pinpoint/web/view/AgentActiveThreadDumpListSerializerTest.java
> [#3031] Add hasLength() to CollectionUtils

- commons/src/main/java/com/navercorp/pinpoint/common/util/ArrayUtils.java
- isNotEmpty(String) -> hasLength(String)
> [#2800] change ArrayUtils API

- commons/src/main/java/com/navercorp/pinpoint/common/plugin/util/HostAndPort.java
- commons/src/main/java/com/navercorp/pinpoint/common/util/StringUtils.java
- commons/src/test/java/com/navercorp/pinpoint/common/util/StringUtilsTest.java
- plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/HttpRequestExecutorExecuteMethodInterceptor.java
> [#3044] Apply HostAndPort

- web/src/test/java/com/navercorp/pinpoint/web/vo/stat/chart/DataSourceChartGroupTest.java
- web/src/test/java/com/navercorp/pinpoint/web/vo/stat/chart/ResponseTimeChartGroupTest.java
(junit.framework.Assert -> org.junit.Assert)
> [#noissue] Change use of deprecated packages

- collector/src/test/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/ActiveTraceBoMapperTest.java
- collector/src/test/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/CpuLoadBoMapperTest.java
- collector/src/test/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/DeadlockBoMapperTest.java
- collector/src/test/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/ResponseTimeBoMapperTest.java
- collector/src/test/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/ThriftBoMapperTestBase.java
add testcase for collector.mapper.thrift.stat
> [#noissue] add testcase

- web/src/main/webapp/common/services/agent-ajax.service.js
- web/src/main/webapp/common/services/agent-dao.service.js
- web/src/main/webapp/features/agentChartGroup/agent-chart-group.directive.js
- web/src/main/webapp/features/navbar/navbar.html
[#2995] add readonly attribute to calendar input
> [#noissue] change chart api url.

- rpc/src/test/java/com/navercorp/pinpoint/rpc/server/ControlPacketServerTest.java
- rpc/src/test/java/com/navercorp/pinpoint/rpc/server/EventHandlerTest.java
- rpc/src/test/java/com/navercorp/pinpoint/rpc/util/IOUtils.java
> [#noissue] fix testcase

- quickstart/bin/start-collector.sh
- quickstart/bin/start-testapp.sh
- quickstart/bin/start-web.sh
[bugfix about quickstart control scripts]
(https://github.com/naver/pinpoint/issues/3062)
> fix bash scripts about quickstart

- web/src/main/java/com/navercorp/pinpoint/web/applicationmap/ApplicationMapWithScatterData.java
- web/src/main/java/com/navercorp/pinpoint/web/applicationmap/ApplicationMapWithScatterScanResult.java
- web/src/main/webapp/common/services/sidebar-title-vo.service.js
- web/src/main/webapp/features/loadChart/load-chart.directive.js
- web/src/main/webapp/features/responseTimeSummaryChart/response-time-summary-chart.directive.js
- do not update x-axis text of response summary and label of load chart when update chart.
- error when parse icon name at side-bar
- remove not used data
> [#noissue] bug fix

- plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/VertxPlugin.java
- plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/interceptor/ContextImplExecuteBlockingInterceptor.java
- plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/interceptor/ContextImplRunOnContextInterceptor.java
#1417 
ContextImpl runOnContext() & executeBlocking().
* io.vertx.core.impl.ContextImpl
* io.vertx.core.impl.EventLoopContext
* io.vertx.core.impl.MultiThreadedWorkerContext
* io.vertx.core.impl.EventLoopContext
> [#1417] add ContextImpl.runOnContext() & executeBlocking().

- agent/src/main/resources-local/pinpoint.config
- agent/src/main/resources-release/pinpoint.config
- agent/src/main/resources/pinpoint-real-env-lowoverhead-sample.config
- plugins/arcus/src/main/java/com/navercorp/pinpoint/plugin/arcus/ArcusPlugin.java
- plugins/arcus/src/main/java/com/navercorp/pinpoint/plugin/arcus/ArcusPluginConfig.java
- quickstart/agent/src/main/resources/pinpoint.config
> [#3096] Add arcus/memcached async on/off options

- plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/VertxConstants.java
- plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/VertxPlugin.java
- plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/interceptor/HttpClientImplGetConnectionForRequest.java
> [#1417] add support for vertx httpclient 3.4.0, 3.4.1, 3.4.2 versions.

- agent/src/main/resources-local/pinpoint.config
- agent/src/main/resources-release/pinpoint.config
- agent/src/main/resources/pinpoint-real-env-lowoverhead-sample.config
- agent/src/test/java/com/navercorp/pinpoint/plugin/ning/asynchttpclient/NingAsyncHttpClientIT.java
- plugins/ning-asynchttpclient/pom.xml
- plugins/ning-asynchttpclient/src/main/java/com/navercorp/pinpoint/plugin/ning/asynchttpclient/EndPointUtils.java
- plugins/ning-asynchttpclient/src/main/java/com/navercorp/pinpoint/plugin/ning/asynchttpclient/NingAsyncHttpClientMetadataProvider.java
- plugins/ning-asynchttpclient/src/main/java/com/navercorp/pinpoint/plugin/ning/asynchttpclient/NingAsyncHttpClientPlugin.java
- plugins/ning-asynchttpclient/src/main/java/com/navercorp/pinpoint/plugin/ning/asynchttpclient/NingAsyncHttpClientPluginConfig.java
- plugins/ning-asynchttpclient/src/main/java/com/navercorp/pinpoint/plugin/ning/asynchttpclient/interceptor/ExecuteInterceptor.java
- plugins/ning-asynchttpclient/src/test/java/com/navercorp/pinpoint/plugin/ning/asynchttpclient/EndPointUtilsTest.java
- pom.xml
- quickstart/agent/src/main/resources/pinpoint.config
> [#3036] Add support for ning asynchttpclient 1.9.x and 2.x versions.

- agent/src/test/java/com/navercorp/pinpoint/plugin/jdk7/cassandra/CassandraDatastaxITBase.java
- plugins/cassandra/src/main/java/com/navercorp/pinpoint/plugin/cassandra/interceptor/CassandraStatementExecuteQueryInterceptor.java
This fixes `ClassCastException` from being thrown by `CassandraStatementExecuteQueryInterceptor` when `BatchStatement` or `StatementWrapper` are used.
There is currently no way apart from using reflection to get the wrapped sql so we do not record these for `StatementWrapper`.
For `BatchStatement`s, we could unroll all the statements inside to retrieve the sqls and trace them, but for now, we do not record these as well.
Both of the above could be changed if the need arises.
fixes #3090
> Fixes casting when batch statements or statement wrappers are used

- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/async/AsyncContextAccessor.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/async/AsyncContextAccessorUtils.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/context/AsyncContext.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/context/SpanEventRecorder.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/AsyncContextSpanEventSimpleAroundInterceptor.java
- bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/interceptor/AsyncContextSpanEventSimpleAroundInterceptorTest.java
- bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/interceptor/SpanAsyncEventSimpleAroundInterceptorTest.java
- plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/interceptor/SpanAsyncEventEndPointInterceptor.java
- profiler-test/src/main/java/com/navercorp/pinpoint/test/MockTraceContextFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/AsyncContextFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/AsyncTrace.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultAsyncContext.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultAsyncContextFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultBaseTraceFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTrace.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/id/DefaultTraceId.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/id/DefaultTraceRoot.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/ApplicationContextModule.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/AsyncContextFactoryProvider.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/TraceFactoryProvider.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/recorder/DefaultRecorderFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/recorder/WrappedSpanEventRecorder.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/scope/DefaultTraceScope.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/DefaultTraceTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/MockTraceContextFactory.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/TraceTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/recorder/WrappedSpanEventRecorderTest.java
> [#2584] Add AsyncContext

- plugins/arcus/src/main/java/com/navercorp/pinpoint/plugin/arcus/ArcusConstants.java
- plugins/arcus/src/main/java/com/navercorp/pinpoint/plugin/arcus/ArcusPlugin.java
- plugins/arcus/src/main/java/com/navercorp/pinpoint/plugin/arcus/interceptor/ApiInterceptor.java
- plugins/arcus/src/main/java/com/navercorp/pinpoint/plugin/arcus/interceptor/FutureGetInterceptor.java
- plugins/arcus/src/main/java/com/navercorp/pinpoint/plugin/arcus/interceptor/FutureInternalMethodInterceptor.java
- plugins/google-httpclient/src/main/java/com/navercorp/pinpoint/plugin/google/httpclient/HttpClientPlugin.java
- plugins/google-httpclient/src/main/java/com/navercorp/pinpoint/plugin/google/httpclient/interceptor/HttpRequestExecuteAsyncMethodInnerClassCallMethodInterceptor.java
- plugins/google-httpclient/src/main/java/com/navercorp/pinpoint/plugin/google/httpclient/interceptor/HttpRequestExecuteAsyncMethodInnerClassConstructorInterceptor.java
- plugins/google-httpclient/src/main/java/com/navercorp/pinpoint/plugin/google/httpclient/interceptor/HttpRequestExecuteAsyncMethodInterceptor.java
- plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/HttpClient4Constants.java
- plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/HttpClient4Plugin.java
- plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/BasicFutureMethodInterceptor.java
- plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/DefaultClientExchangeHandlerImplStartMethodInterceptor.java
- plugins/hystrix/src/main/java/com/navercorp/pinpoint/plugin/hystrix/interceptor/HystrixCommandExecuteCommandInterceptor.java
- plugins/hystrix/src/main/java/com/navercorp/pinpoint/plugin/hystrix/interceptor/HystrixCommandQueueInterceptor.java
- plugins/hystrix/src/main/java/com/navercorp/pinpoint/plugin/hystrix/interceptor/HystrixObservableCallInterceptor.java
- plugins/hystrix/src/main/java/com/navercorp/pinpoint/plugin/hystrix/transformer/HystrixCommandTransformer.java
- plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/OkHttpPlugin.java
- plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/interceptor/DispatcherEnqueueMethodInterceptor.java
- plugins/resin/src/main/java/com/navercorp/pinpoint/plugin/resin/ResinPlugin.java
- plugins/resin/src/main/java/com/navercorp/pinpoint/plugin/resin/interceptor/HttpServletRequestImplInterceptor.java
- plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/ThriftPlugin.java
- plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/interceptor/client/async/TAsyncClientManagerCallInterceptor.java
- plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/interceptor/client/async/TAsyncMethodCallCleanUpAndFireCallbackInterceptor.java
- plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/interceptor/client/async/TAsyncMethodCallOnErrorInterceptor.java
- plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/TomcatPlugin.java
- plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/interceptor/RequestStartAsyncInterceptor.java
> [#2584] Apply AsyncContext

- profiler-test/src/main/java/com/navercorp/pinpoint/test/MockTraceContextFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultAsyncContext.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultAsyncContextFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/method/AsyncMethodDescriptor.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/method/DefaultPredefinedMethodDescriptorRegistry.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/method/PredefinedMethodDescriptorRegistry.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/ApplicationContextModule.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/AsyncContextFactoryProvider.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/MockTraceContextFactory.java
> [#2584] Remove cache lock contention

- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/AsyncContextFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/AsyncTrace.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultAsyncContextFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultBaseTraceFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/id/StatefulAsyncTraceId.java
> [#2584] Refactor AsyncTraceId

- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/instrument/matcher/operand/AbstractMatcherOperand.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/instrument/matcher/operand/InterfaceInternalNameMatcherOperand.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/instrument/matcher/operand/SuperClassInternalNameMatcherOperand.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/instrument/matcher/operator/AndMatcherOperator.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/instrument/matcher/operator/BracketMatcherOperator.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/instrument/matcher/operator/MatcherOperator.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/instrument/matcher/operator/NotMatcherOperator.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/instrument/matcher/operator/OrMatcherOperator.java
- bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/instrument/matcher/operator/AndMatcherOperatorTest.java
- bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/instrument/matcher/operator/BracketMatcherOperatorTest.java
- bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/instrument/matcher/operator/NotMatcherOperatorTest.java
- bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/instrument/matcher/operator/OrMatcherOperatorTest.java
- profiler-optional/profiler-optional-jdk8/src/test/java/com/navercorp/test/pinpoint/jdk8/lambda/LambdaIT.java
> [#2983] fix operator.

- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMClassNodeAdapter.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMClassWriter.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/ASMClassNodeLoader.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/ASMClassWriterTest.java
> [#3109] fix getCommonSuperClass().

- doc/alarm.md
- web/src/main/java/com/navercorp/pinpoint/web/alarm/CheckerCategory.java
- web/src/main/java/com/navercorp/pinpoint/web/alarm/DataCollectorFactory.java
- web/src/main/java/com/navercorp/pinpoint/web/alarm/checker/AgentChecker.java
- web/src/main/java/com/navercorp/pinpoint/web/alarm/checker/AlarmChecker.java
- web/src/main/java/com/navercorp/pinpoint/web/alarm/checker/DataSourceConnectionUsageRateChecker.java
- web/src/main/java/com/navercorp/pinpoint/web/alarm/checker/ErrorCountChecker.java
- web/src/main/java/com/navercorp/pinpoint/web/alarm/checker/ErrorCountToCalleeChecker.java
- web/src/main/java/com/navercorp/pinpoint/web/alarm/checker/ErrorRateChecker.java
- web/src/main/java/com/navercorp/pinpoint/web/alarm/checker/ErrorRateToCalleeChecker.java
- web/src/main/java/com/navercorp/pinpoint/web/alarm/checker/GcCountChecker.java
- web/src/main/java/com/navercorp/pinpoint/web/alarm/checker/JvmCpuUsageRateChecker.java
- web/src/main/java/com/navercorp/pinpoint/web/alarm/checker/LongValueAlarmChecker.java
- web/src/main/java/com/navercorp/pinpoint/web/alarm/checker/ResponseCountChecker.java
- web/src/main/java/com/navercorp/pinpoint/web/alarm/checker/SlowCountChecker.java
- web/src/main/java/com/navercorp/pinpoint/web/alarm/checker/SlowCountToCalleeChecker.java
- web/src/main/java/com/navercorp/pinpoint/web/alarm/checker/SlowRateChecker.java
- web/src/main/java/com/navercorp/pinpoint/web/alarm/checker/SlowRateToCalleeChecker.java
- web/src/main/java/com/navercorp/pinpoint/web/alarm/checker/TotalCountToCalleeChecker.java
- web/src/main/java/com/navercorp/pinpoint/web/alarm/collector/AgentStatDataCollector.java
- web/src/main/java/com/navercorp/pinpoint/web/alarm/collector/DataCollector.java
- web/src/main/java/com/navercorp/pinpoint/web/alarm/collector/DataSourceDataCollector.java
- web/src/main/java/com/navercorp/pinpoint/web/alarm/collector/MapStatisticsCallerDataCollector.java
- web/src/main/java/com/navercorp/pinpoint/web/alarm/vo/DataSourceAlarmVO.java
- web/src/main/webapp/common/help/help-content-en.js
- web/src/main/webapp/common/help/help-content-ko.js
- web/src/test/java/com/navercorp/pinpoint/web/alarm/WriterTest.java
- web/src/test/java/com/navercorp/pinpoint/web/alarm/checker/DataSourceConnectionUsageRateCheckerTest.java
Add alarm for datasource connection usage rate
> [#3114] Add alarm for datasource connection usage rate

- plugins/mysql-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/mysql/MySqlPlugin.java
- plugins/mysql-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/mysql/interceptor/MySQL_6_X_ConnectionCreateInterceptor.java
- plugins/mysql-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/mysql/interceptor/getter/DatabaseGetter.java
- plugins/mysql-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/mysql/interceptor/getter/OrigHostToConnectToGetter.java
- plugins/mysql-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/mysql/interceptor/getter/OrigPortToConnectToGetter.java
> Adds trace support for MySql java connector 6.x

- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/context/AsyncContext.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/context/SpanEventRecorder.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/context/Trace.java
- plugins/arcus/src/main/java/com/navercorp/pinpoint/plugin/arcus/interceptor/ApiInterceptor.java
- plugins/google-httpclient/src/main/java/com/navercorp/pinpoint/plugin/google/httpclient/interceptor/HttpRequestExecuteAsyncMethodInterceptor.java
- plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/DefaultClientExchangeHandlerImplStartMethodInterceptor.java
- plugins/hystrix/src/main/java/com/navercorp/pinpoint/plugin/hystrix/interceptor/HystrixCommandQueueInterceptor.java
- plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/interceptor/DispatcherEnqueueMethodInterceptor.java
- plugins/resin/src/main/java/com/navercorp/pinpoint/plugin/resin/interceptor/HttpServletRequestImplInterceptor.java
- plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/interceptor/client/async/TAsyncClientManagerCallInterceptor.java
- plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/interceptor/RequestStartAsyncInterceptor.java
- plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/interceptor/ContextImplExecuteBlockingInterceptor.java
- plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/interceptor/ContextImplRunOnContextInterceptor.java
- plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/interceptor/HttpClientImplDoRequestInterceptor.java
- plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/interceptor/ServerConnectionHandleRequestInterceptor.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/recorder/WrappedSpanEventRecorder.java
- SpanEventRecorder#newAsyncContext() -> SpanEventRecorder#recordNextAsyncContext()
> [#2584] Change API

- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/AsyncContextFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultAsyncContext.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultAsyncContextFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/InternalAsyncContext.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/recorder/WrappedSpanEventRecorder.java
> [#2584] Hide getAsyncId() from AsyncContext

- web/src/main/java/com/navercorp/pinpoint/web/alarm/CheckerCategory.java
- web/src/main/java/com/navercorp/pinpoint/web/alarm/DataCollectorFactory.java
- web/src/main/java/com/navercorp/pinpoint/web/alarm/checker/DeadlockChecker.java
- web/src/main/java/com/navercorp/pinpoint/web/alarm/collector/AgentEventDataCollector.java
- web/src/main/webapp/common/help/help-content-en.js
- web/src/main/webapp/common/help/help-content-ko.js
- web/src/test/java/com/navercorp/pinpoint/web/alarm/checker/DataSourceConnectionUsageRateCheckerTest.java
- web/src/test/java/com/navercorp/pinpoint/web/alarm/checker/DeadlockCheckerTest.java
Add alarm for deadlock occurrence
> [#3131] Add alarm for deadlock occurrence

- agent/src/test/java/com/navercorp/pinpoint/plugin/jdbc/mariadb/MariaDB_1_3_x_IT.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/jdbc/mariadb/MariaDB_1_6_x_to_2_0_0_IT.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/jdbc/mariadb/MariaDB_2_x_IT.java
- plugins/mariadb-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/mariadb/MariaDBPlugin.java
> Adds support for MariaDB java connector 1.6.x and 2.x

- web/src/main/webapp/common/help/help-content-en.js
- web/src/main/webapp/common/help/help-content-ko.js
- web/src/main/webapp/common/services/agent-ajax.service.js
- web/src/main/webapp/features/activeTraceChart/active-trace-chart.directive.js
- web/src/main/webapp/features/applicationStatistic/application-statistic.directive.js
- web/src/main/webapp/features/cpuLoadChart/cpu-load-chart.directive.js
- web/src/main/webapp/features/jvmMemoryChart/jvm-memory-chart.directive.js
- web/src/main/webapp/features/responseTimeChart/response-time-chart.directive.js
- web/src/main/webapp/features/statisticChart/statistic-chart.directive.js
- web/src/main/webapp/features/tpsChart/tps-chart.directive.js
- do not execute mouseOver event on chart at inspector page
> [#2970] bug fix.

- collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/TFAgentStatMapper.java
- collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/TFTransactionMapper.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/join/JoinAgentStatBo.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/join/JoinApplicationStatBo.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/join/JoinCpuLoadBo.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/join/JoinMemoryBo.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/join/JoinTransactionBo.java
- commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/stat/join/JoinApplicationStatBoTest.java
- commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/stat/join/JoinTransactionBoTest.java
- flink/src/main/java/com/navercorp/pinpoint/flink/function/ApplicationStatBoWindow.java
- flink/src/main/java/com/navercorp/pinpoint/flink/mapper/thrift/stat/JoinAgentStatBoMapper.java
- flink/src/main/java/com/navercorp/pinpoint/flink/mapper/thrift/stat/JoinTransactionBoMapper.java
- flink/src/main/java/com/navercorp/pinpoint/flink/process/TbaseFlatMapper.java
- flink/src/test/java/com/navercorp/pinpoint/flink/mapper/thrift/stat/JoinAgentStatBoMapperTest.java
- flink/src/test/java/com/navercorp/pinpoint/flink/mapper/thrift/stat/JoinTransactionBoMapperTest.java
- flink/src/test/java/flink/process/TbaseFlatMapperTest.java
aggregate agent's transaction data to show application's transaction data
>  aggregate agent's transaction data to show application's transaction data

- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/JvmGcType.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/MethodTypeEnum.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/strategy/StringEncodingStrategy.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/strategy/UnsignedIntegerEncodingStrategy.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/strategy/UnsignedLongEncodingStrategy.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/strategy/UnsignedShortEncodingStrategy.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/AgentStatType.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/join/StatType.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/AgentEventType.java
- commons-server/src/test/java/com/navercorp/pinpoint/common/server/util/AgentEventTypeTest.java
- commons/src/main/java/com/navercorp/pinpoint/common/trace/LoggingInfo.java
- commons/src/main/java/com/navercorp/pinpoint/common/trace/ServiceTypeCategory.java
- commons/src/main/java/com/navercorp/pinpoint/common/util/JvmVersion.java
- commons/src/test/java/com/navercorp/pinpoint/common/util/JvmVersionTest.java
- plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/ThriftHeader.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/util/ThreadDumpUtils.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/util/ThreadDumpUtilsTest.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/common/SocketStateCode.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/packet/HandshakePropertyType.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/packet/HandshakeResponseCode.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/packet/stream/StreamCode.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/stream/StreamChannelStateCode.java
- rpc/src/test/java/com/navercorp/pinpoint/rpc/cluster/RoleTest.java
- rpc/src/test/java/com/navercorp/pinpoint/rpc/packet/HandshakeResponseCodeTest.java
- rpc/src/test/java/com/navercorp/pinpoint/rpc/stream/StreamChannelStateCodeTest.java
- web/src/main/java/com/navercorp/pinpoint/web/alarm/CheckerCategory.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/timeline/inspector/AgentState.java
- web/src/main/java/com/navercorp/pinpoint/web/websocket/ActiveThreadCountErrorType.java
- web/src/main/java/com/navercorp/pinpoint/web/websocket/message/PinpointWebSocketMessageType.java
- Reduce Memory footprint
- Remove Array copy of enum.values()
> [#3167] Enum optimization

- plugins/resin/src/main/java/com/navercorp/pinpoint/plugin/resin/interceptor/AsyncContextImplDispatchMethodInterceptor.java
- plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/interceptor/AsyncContextImplDispatchMethodInterceptor.java
> [#2584] Deprecated SpanAsyncEventSimpleAroundInterceptor.

- .travis.yml
> [#noissue] change travis confi g

- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultBaseTraceFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTraceContext.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/SpanAsyncStateListener.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/SpanAsyncStateListenerTest.java
> [#3167] Lazy instantiation of storage object

- web/src/main/java/com/navercorp/pinpoint/web/calltree/span/CallTreeIterator.java
- web/src/main/java/com/navercorp/pinpoint/web/service/TransactionInfoServiceImpl.java
> [#3194] Improved performance of Call Tree logic.

- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/active/ActiveTraceHistogram.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/active/ActiveTraceHistogramFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/active/DefaultActiveTraceHistogram.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/active/DefaultActiveTraceRepository.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/active/EmptyActiveTraceHistogram.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/monitor/metric/activethread/DefaultActiveTraceMetric.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/service/ActiveThreadCountService.java
- memory usage
- object size
- cpu cycle
> [#3196] ActiveTrace optimization

- web/src/main/java/com/navercorp/pinpoint/web/vo/callstacks/RecordFactory.java
- web/src/test/java/com/navercorp/pinpoint/web/vo/callstacks/RecordFactoryTest.java
> [#3203] Fixed an error where exception message is null.

- collector/src/test/java/com/navercorp/pinpoint/collector/receiver/udp/SpanStreamUDPSenderTest.java
- profiler-test/src/main/java/com/navercorp/pinpoint/test/PluginTestAgent.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/AsyncTrace.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultAsyncContext.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultTrace.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/Span.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/SpanChunkFactoryV1.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/SpanChunkFactoryV2.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/SpanEvent.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/id/DefaultShared.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/id/DefaultTraceRoot.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/id/Shared.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/recorder/DefaultSpanRecorder.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/DefaultTraceTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/recorder/DefaultSpanRecorderTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/recorder/WrappedSpanEventRecorderTest.java
> [#3167] Extract shared object for the active thread of vert.x

- agent/src/main/resources-local/pinpoint.config
- agent/src/main/resources-release/pinpoint.config
- agent/src/main/resources/pinpoint-real-env-lowoverhead-sample.config
- agent/src/test/resources/activemq/client/pinpoint-activemq-client.config
- agent/src/test/resources/pinpoint-disabled-plugin-test.config
- agent/src/test/resources/pinpoint-netty-plugin-test.config
- agent/src/test/resources/pinpoint-spring-bean-test.config
- plugins/google-httpclient/src/test/resources/pinpoint.config
- plugins/httpclient4/src/test/resources/pinpoint.config
- plugins/jboss/src/test/resources/pinpoint.config
- plugins/jsp/src/test/resources/pinpoint.config
- plugins/redis/src/test/resources/pinpoint.config
- plugins/tomcat/src/test/resources/pinpoint.config
- plugins/user/src/test/resources/pinpoint.config
- plugins/vertx/src/test/resources/pinpoint.config
- profiler-optional/profiler-optional-jdk8/src/test/resources/pinpoint-lambda-test.config
- profiler/src/test/resources/pinpoint-spring-bean-test.config
- profiler/src/test/resources/pinpoint.config
- quickstart/agent/src/main/resources/pinpoint.config
> [#3211] add Netty plugin (support only 4.1.x.Final version)

- web/src/main/webapp/common/help/help-content-en.js
- web/src/main/webapp/common/help/help-content-ko.js
- web/src/main/webapp/common/services/agent-ajax.service.js
- web/src/main/webapp/common/services/tooltip.service.js
- web/src/main/webapp/components/time-slider/time-slider.js
- web/src/main/webapp/components/time-slider/time-slider.position-manager.js
- web/src/main/webapp/components/time-slider/time-slider.selection-manager.js
- web/src/main/webapp/features/agentInfo/agent-info.directive.js
- web/src/main/webapp/features/agentList/agent-list.directive.js
- web/src/main/webapp/features/applicationStatistic/application-statistic.directive.js
- web/src/main/webapp/features/applicationStatistic/applicationStatistic.html
- web/src/main/webapp/pages/inspector/inspector.controller.js
- web/src/main/webapp/styles/main.css
bug fix.
- do not sync time of application inspector and agent inspector.
> [#2970] add tps chart for application inspector.

- collector/src/main/java/com/navercorp/pinpoint/collector/cluster/connection/CollectorClusterAcceptor.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/tcp/TCPReceiver.java
- flink/src/main/java/com/navercorp/pinpoint/flink/receiver/TCPReceiver.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/AgentInfoSenderTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/sender/TcpDataSenderReconnectTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/sender/TcpDataSenderTest.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/client/DefaultPinpointClientHandler.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/codec/PacketDecoder.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/codec/ServerPacketDecoder.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/packet/PacketType.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/packet/PingPacket.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/packet/PingPayloadPacket.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/packet/PingSimplePacket.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/server/DefaultPinpointServer.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/server/HealthCheckManager.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/server/HealthCheckState.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/server/HealthCheckStateContext.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/server/PinpointServer.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/server/PinpointServerAcceptor.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/server/PinpointServerConfig.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/server/ServerPipelineFactory.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/server/SimpleServerMessageListener.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/server/handler/PingHandler.java
- rpc/src/test/java/com/navercorp/pinpoint/rpc/client/HealthCheckTest.java
- rpc/src/test/java/com/navercorp/pinpoint/rpc/client/PinpointClientFactoryTest.java
- rpc/src/test/java/com/navercorp/pinpoint/rpc/server/ControlPacketServerTest.java
- rpc/src/test/java/com/navercorp/pinpoint/rpc/server/HealthCheckManagerTest.java
- rpc/src/test/java/com/navercorp/pinpoint/rpc/util/IOUtils.java
- rpc/src/test/java/com/navercorp/pinpoint/rpc/util/PinpointRPCTestUtils.java
- web/src/main/java/com/navercorp/pinpoint/web/cluster/connection/ClusterAcceptor.java
1. create new PingPacket
2. client use new Pingpacket
3. Change the healthcheck to match the client's ping packet
> [#3217] Create a new PingPacket

- rpc/src/main/java/com/navercorp/pinpoint/rpc/packet/stream/BasicStreamPacket.java
> [#3256] Fix BasicStreamPacket.toString()

- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/udp/UDPReceiver.java
- collector/src/test/java/com/navercorp/pinpoint/collector/receiver/udp/UDPReceiverTest.java
> [#3261] Fix wrong packet.getLength()==0 logic

- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/udp/UDPReceiver.java
- collector/src/test/java/com/navercorp/pinpoint/collector/receiver/udp/UDPReceiverTest.java
> [#3261] Fix PooledObject<DatagramPacket> leak

- web/src/main/java/com/navercorp/pinpoint/web/vo/callstacks/RecordFactory.java
> [#3252] Fix proxy HTTP header.

- quickstart/collector/src/main/resources/pinpoint-collector.properties
> [#3275] Supports TCP transport type for Span and Stat data

- agent/src/main/resources-local/pinpoint.config
- agent/src/main/resources-release/pinpoint.config
- agent/src/main/resources/pinpoint-real-env-lowoverhead-sample.config
- quickstart/agent/src/main/resources/pinpoint.config
> [#1417] add hide pinpoint header.

- .travis.yml
- profiler/src/test/java/com/navercorp/pinpoint/profiler/receiver/service/ActiveThreadLightDumpServiceTest.java
> [#noissue] update travis dist

- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/proxy/ProxyHttpHeaderParser.java
- bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/plugin/proxy/ProxyHttpHeaderParserTest.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/callstacks/AnnotationRecordFormatter.java
> [#3252] change proxy http header format.

- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/trace/v2/SpanChunkSerializerV2.java
> [#noissue] fix SpanChunkSerializerV2.

- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/strategy/impl/StringAlwaysSameValueEncodingStrategy.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/strategy/impl/StringRepeatCountEncodingStrategy.java
1. remove unnecessary method
2. prevent NullPointerException
> [#noissue] cleanup

- plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/interceptor/AsyncContextSpanEventEndPointInterceptor.java
> [#1417] fix async context operation of after method.

- web/src/grunt/concat.js
- web/src/main/webapp/features/nodeInfoDetails/node-info-details.directive.js
- web/src/main/webapp/features/nodeInfoDetails/nodeInfoDetails.html
- web/src/main/webapp/pages/filteredMap/filteredMap.html
wrong namespace setting in filtered-map page.
> [#3178] bug fix. 

- profiler/src/main/java/com/navercorp/pinpoint/profiler/monitor/metric/memory/DefaultDetailedMemoryMetric.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/monitor/metric/memory/DefaultDetailedMemoryMetricTest.java
> Fixes long division when calculating detailed memory usage

- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/AgentStatCodec.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v1/AbstractAgentStatCodecV1.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v1/JvmGcCodecV1.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v2/AbstractAgentStatCodecV2.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v2/ActiveTraceCodecV2.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v2/CpuLoadCodecV2.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v2/DeadlockCodecV2.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v2/JvmGcCodecV2.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v2/JvmGcDetailedCodecV2.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v2/ResponseTimeCodecV2.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v2/TransactionCodecV2.java
1. remove duplicated code
2. remove unnecessary field
> [#cleanup] cleanup stat codec code

- quickstart/web/src/main/resources/pinpoint-web.properties
- web/src/main/java/com/navercorp/pinpoint/web/config/ConfigProperties.java
- web/src/main/java/com/navercorp/pinpoint/web/controller/ConfigController.java
- web/src/main/resources/pinpoint-web.properties
remove `config.show.inspector.dataSource` option
> [#3388] remove unused option

- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/AgentStatCodec.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/CodecFactory.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v1/ActiveTraceCodecV1.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v1/AgentStatCodecV1.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v1/CpuLoadCodecV1.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v1/JvmGcDetailedCodecV1.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v1/TransactionCodecV1.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v2/ActiveTraceCodecV2.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v2/AgentStatCodecV2.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v2/CpuLoadCodecV2.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v2/DeadlockCodecV2.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v2/JvmGcCodecV2.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v2/JvmGcDetailedCodecV2.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v2/ResponseTimeCodecV2.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v2/TransactionCodecV2.java
- Remove inheritance and change to composition
> [#noissue] Refactor AgentStatCodec

- agent/src/main/resources-local/pinpoint.config
- agent/src/main/resources-release/pinpoint.config
- agent/src/main/resources/pinpoint-real-env-lowoverhead-sample.config
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/DefaultProfilerConfig.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/ProfilerConfig.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/context/SpanRecorder.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/http/HttpStatusCodeRecorder.java
- bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/plugin/http/HttpStatusCodeRecorderTest.java
- plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/interceptor/StandardHostValveInvokeInterceptor.java
- plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/ResponseGetter.java
- plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/VertxPlugin.java
- plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/interceptor/HttpServerResponseImplInterceptor.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/Span.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/SpanEvent.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/id/DefaultShared.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/recorder/AbstractRecorder.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/recorder/DefaultSpanRecorder.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/recorder/WrappedSpanEventRecorder.java
> [#3399] Add HTTP status code

- commons/src/main/java/com/navercorp/pinpoint/common/trace/AnnotationKeyFactory.java
- commons/src/main/java/com/navercorp/pinpoint/common/trace/DefaultAnnotationKeyFactory.java
- commons/src/main/java/com/navercorp/pinpoint/common/trace/DefaultServiceTypeFactory.java
- commons/src/main/java/com/navercorp/pinpoint/common/trace/ServiceTypeFactory.java
- avoid superclass-subclass deadlock
> [#noissue] Deadlock prevent

- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/http/HttpStatusCodeRecorder.java
> [#3399]  Add HTTP status code

- agent/src/main/resources-local/pinpoint.config
- agent/src/main/resources-release/pinpoint.config
- agent/src/main/resources/pinpoint-real-env-lowoverhead-sample.config
- quickstart/agent/src/main/resources/pinpoint.config
> [#3252] add guide url.

- agent/src/test/java/com/navercorp/pinpoint/plugin/spring/web/SpringWebMvc_3_x_to_4_x_IT.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/spring/web/SpringWebMvc_5_x_IT.java
> Runs Spring 5.x integration tests on Java 8

- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/AsyncContextFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/AsyncId.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultAsyncContext.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultAsyncContextFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultAsyncId.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/SpanEvent.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/StatefulAsyncContext.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/id/AsyncIdGenerator.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/id/DefaultAsyncIdGenerator.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/id/DefaultAsyncTraceId.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/recorder/WrappedSpanEventRecorder.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/storage/BufferedStorage.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/id/DefaultAsyncTraceIdTest.java
> [#3436] Support for multiple async events

- web/src/main/webapp/common/help/help-content-en.js
- web/src/main/webapp/common/help/help-content-ko.js
- web/src/main/webapp/common/services/agent-ajax.service.js
- web/src/main/webapp/common/services/tooltip.service.js
- web/src/main/webapp/features/activeTraceChart/active-trace-chart.directive.js
- web/src/main/webapp/features/agentInfo/agentInfoMain.html
- web/src/main/webapp/features/applicationStatistic/application-statistic.directive.js
- web/src/main/webapp/features/applicationStatistic/applicationStatistic.html
- web/src/main/webapp/features/cpuLoadChart/cpu-load-chart.directive.js
- web/src/main/webapp/features/dataSourceChart/data-source-chart.directive.js
- web/src/main/webapp/features/responseTimeChart/response-time-chart.directive.js
- web/src/main/webapp/features/statisticChart/statistic-chart.directive.js
- web/src/main/webapp/features/tpsChart/tps-chart.directive.js
- web/src/main/webapp/styles/inspector.css
[#noissue] add guide message when there is no chart data
> [#2970] add data-source chart on application inspector

- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/AsyncChildTrace.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultBaseTraceFactory.java
#2584
- Extract AsyncChildTrace from AsyncTrace
> [#2584] Refactor AsyncTrace

- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/proxy/ProxyHttpHeader.java
> [#3252] fix format.

- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/context/SpanRecorder.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultBaseTraceFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/recorder/DefaultRecorderFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/recorder/DefaultSpanRecorder.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/recorder/RecorderFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/recorder/TraceRootSpanRecorder.java
> [#2584] Refactor SpanRecorder

- web/src/main/webapp/features/agentInfo/agent-info.directive.js
- web/src/main/webapp/features/agentInspectorChart/agent-inspector-chart.directive.js
- web/src/main/webapp/features/agentList/agent-list.directive.js
- web/src/main/webapp/features/applicationStatistic/application-statistic.directive.js
- web/src/main/webapp/features/navbar2/navbar2.directive.js
- web/src/main/webapp/features/periodSelector/period-selector.directive.js
- web/src/main/webapp/features/statisticChart/statistic-chart.directive.js
- web/src/main/webapp/pages/inspector/inspector.controller.js
- web/src/main/webapp/pages/inspector/inspector.html
- web/src/main/webapp/styles/inspector.css
- add loading indicator to chart on inspector page
- not initialized sometime period calendar.
> [#noissue] bug fix and add loading indicator.

- agent/src/test/java/com/navercorp/pinpoint/plugin/hystrix/HystrixCommand_1_4_0_to_1_5_2_IT.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/hystrix/HystrixCommand_1_5_3_to_1_5_x_IT.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/hystrix/HystrixObservableCommand_1_4_0_to_1_5_2_IT.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/hystrix/HystrixObservableCommand_1_5_3_to_1_5_x_IT.java
- plugins/hystrix/src/main/java/com/navercorp/pinpoint/plugin/hystrix/HystrixPlugin.java
> Fixes Hystrix getFallbackObservable method tracing

- plugins/jboss/src/test/java/com/navercorp/pinpoint/plugin/jboss/InvokeMethodInterceptorTest.java
- plugins/tomcat/src/test/java/com/navercorp/pinpoint/plugin/tomcat/InvokeMethodInterceptorTest.java
- profiler-test/src/main/java/com/navercorp/pinpoint/test/MockApplicationContextFactory.java
- profiler-test/src/main/java/com/navercorp/pinpoint/test/MockApplicationContextModule.java
- profiler-test/src/main/java/com/navercorp/pinpoint/test/MockTraceContextFactory.java
- profiler-test/src/main/java/com/navercorp/pinpoint/test/PluginTestAgent.java
- profiler-test/src/main/java/com/navercorp/pinpoint/test/classloader/TestClassLoader.java
- profiler-test/src/main/java/com/navercorp/pinpoint/test/junit4/TestContext.java
- profiler-test/src/test/java/com/navercorp/pinpoint/test/MockApplicationContextModuleTest.java
- profiler-test/src/test/java/com/navercorp/pinpoint/test/javasssit/JavassistClassTest.java
- profiler-test/src/test/java/com/navercorp/pinpoint/test/javasssit/accessor/AccessorInjectionTest.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/DefaultAgent.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DefaultAsyncContext.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/DisableTrace.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/ApplicationContext.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/ApplicationContextModule.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/ApplicationContextModuleFactory.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/DefaultApplicationContext.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/ModuleFactory.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/DefaultTraceContextTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/MockApplicationContext.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/MockApplicationContextFactory.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/MockTraceContextFactory.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/active/ActiveTraceRepositoryTest.java
- Remove  TraceContext assembly code
> [#noissue] Remove bootstrapping code for test

- collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/event/AgentEventBatchMapper.java
- collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/ActiveTraceBoMapper.java
- collector/src/main/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/TFActiveTraceMapper.java
- collector/src/test/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/ActiveTraceBoMapperTest.java
- collector/src/test/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/TFActiveTraceMapperTest.java
- collector/src/test/java/com/navercorp/pinpoint/collector/mapper/thrift/stat/TFAgentStatMapperTest.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/ActiveTraceHistogramBo.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v2/ActiveTraceCodecV2.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/ActiveTraceBo.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/stat/ActiveTraceHistogram.java
- commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/ActiveTraceHistogramBoTest.java
- commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/codec/stat/TestAgentStatFactory.java
- commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v1/ActiveTraceCodecV1Test.java
- commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/codec/stat/v2/ActiveTraceCodecV2Test.java
- web/src/main/java/com/navercorp/pinpoint/web/dao/hbase/stat/v1/Aggregator.java
- web/src/main/java/com/navercorp/pinpoint/web/mapper/stat/AgentStatMapperV1.java
- web/src/main/java/com/navercorp/pinpoint/web/mapper/stat/sampling/sampler/ActiveTraceSampler.java
> [#noissue] Refactor ActiveTraceHistogram

- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/jdbc/JdbcUrlParser.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/monitor/metric/transaction/DefaultTransactionMetric.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/Application.java
> [#noissue] Fixed klockwork issue

- web/src/main/webapp/features/agentInfo/agent-info.directive.js
- Sometimes the 'addData()' method fails to call
> [#noissue] bug-fix.

- doc/application-inspector.md
> Adds English guide for application inspector documentation

- web/src/main/java/com/navercorp/pinpoint/web/view/ActiveTracePointSerializer.java
- web/src/main/java/com/navercorp/pinpoint/web/view/AgentStatPointSerializer.java
- web/src/main/java/com/navercorp/pinpoint/web/view/CpuLoadPointSerializer.java
- web/src/main/java/com/navercorp/pinpoint/web/view/DataSourcePointSerializer.java
- web/src/main/java/com/navercorp/pinpoint/web/view/MemoryPointSerializer.java
- web/src/main/java/com/navercorp/pinpoint/web/view/ResponseTimePointSerializer.java
- web/src/main/java/com/navercorp/pinpoint/web/view/StatChartGroupSerializer.java
- web/src/main/java/com/navercorp/pinpoint/web/view/TitledAgentStatPointSerializer.java
- web/src/main/java/com/navercorp/pinpoint/web/view/TransactionPointSerializer.java
- web/src/main/resources/pinpoint-web.properties
> Removes deprecated stat chart v1 serialization

- web/src/main/java/com/navercorp/pinpoint/web/websocket/ActiveThreadCountHandler.java
- web/src/main/java/com/navercorp/pinpoint/web/websocket/message/RequestMessage.java
- web/src/main/java/com/navercorp/pinpoint/web/websocket/message/ResponseMessage.java
- web/src/main/java/com/navercorp/pinpoint/web/websocket/message/SendMessage.java
> [#noissue] Refactor WebSocketHandler

- collector/src/main/resources/applicationContext-collector.xml
- collector/src/main/resources/applicationContext-hbase.xml
Hi,
remove unused schema from application context.
> Cleanup application context

- plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/VertxPlugin.java
- plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/interceptor/HttpClientImplDoRequestInterceptor.java
> [#3526] fix requestAbs() of vertx http client 3.4.2

- web/src/main/java/com/navercorp/pinpoint/web/mapper/stat/sampling/sampler/DataSourceSampler.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/chart/Point.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/chart/TimeSeriesChartBuilder.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/stat/SampledActiveTrace.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/stat/SampledCpuLoad.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/stat/SampledDataSource.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/stat/SampledDeadlock.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/stat/SampledJvmGc.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/stat/SampledJvmGcDetailed.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/stat/SampledResponseTime.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/stat/SampledTransaction.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/stat/chart/agent/DataSourceChart.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/stat/chart/application/ActiveTracePoint.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/stat/chart/application/ApplicationActiveTraceChart.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/stat/chart/application/ApplicationCpuLoadChart.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/stat/chart/application/ApplicationDataSourceChart.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/stat/chart/application/ApplicationMemoryChart.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/stat/chart/application/ApplicationResponseTimeChart.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/stat/chart/application/ApplicationTransactionChart.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/stat/chart/application/CpuLoadPoint.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/stat/chart/application/DataSourcePoint.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/stat/chart/application/MemoryPoint.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/stat/chart/application/ResponseTimePoint.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/stat/chart/application/TransactionPoint.java
- web/src/test/java/com/navercorp/pinpoint/web/vo/chart/TimeSeriesChartBuilderTest.java
> [#noissue] fix typo

- profiler/src/main/java/com/navercorp/pinpoint/profiler/AgentInfoSender.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/AgentInfoSenderListener.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/AgentInfoSenderTest.java
> Refactors for simpler agent info send task management

- web/src/main/java/com/navercorp/pinpoint/web/scatter/DotGroup.java
- web/src/main/java/com/navercorp/pinpoint/web/scatter/DotGroups.java
- web/src/main/java/com/navercorp/pinpoint/web/view/ScatterDataSerializer.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/scatter/Dot.java
- web/src/test/java/com/navercorp/pinpoint/web/scatter/ScatterDataTest.java
> #3548 Change the storage type of Dot from HashSet to ArrayList

- collector/src/main/resources/servlet-context.xml
> Removes deprecated collector servlet configurations

- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/DispatchWorker.java
- collector/src/test/java/com/navercorp/pinpoint/collector/receiver/udp/TestUDPReceiver.java
> [#noissue] fix log message

- web/src/main/java/com/navercorp/pinpoint/web/dao/AgentDownloadInfoDaoFactory.java
- web/src/main/java/com/navercorp/pinpoint/web/dao/memory/MemoryAgentDownloadInfoDao.java
- web/src/main/java/com/navercorp/pinpoint/web/dao/rest/GithubAgentDownloadInfoDao.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/AgentDownloadInfo.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/GithubAgentDownloadInfo.java
- web/src/main/resources/applicationContext-dao-config.xml
- web/src/main/resources/pinpoint-web.properties
- web/src/test/java/com/navercorp/pinpoint/web/vo/AgentDownloadInfoTest.java
1. add download info configuration
2. Makes api call lazilly
> [#3580] Fixed accessing github api at startup in web

- web/src/main/webapp/common/services/active-thread-chart-dao.service.js
- web/src/main/webapp/common/services/cpu-load-chart-dao.service.js
- web/src/main/webapp/common/services/memory-chart-dao.service.js
- web/src/main/webapp/common/services/response-time-chart-dao.service.js
- web/src/main/webapp/common/services/tps-chart-dao.service.js
- web/src/main/webapp/features/statisticChart/statistic-chart.directive.js
Do not display legend value when data is '-1'
> [#noissue] Change legend display

- web/src/main/java/com/navercorp/pinpoint/web/service/stat/DataSourceChartService.java
- web/src/main/java/com/navercorp/pinpoint/web/vo/stat/chart/agent/DataSourceChart.java
- web/src/test/java/com/navercorp/pinpoint/web/vo/stat/chart/agent/DataSourceChartGroupTest.java
if has no data
before====
"y" : {}
after====
"y" : { "ACTIVE_CONNECTION_SIZE" : [], "MAX_CONNECTION_SIZE" : []}
> [#noissue] change datasource response format

- agent/src/test/java/com/navercorp/pinpoint/plugin/config/PropertiesVerificationTest.java
- collector/src/test/java/com/navercorp/pinpoint/collector/config/PropertiesVerificationTest.java
- web/src/test/java/com/navercorp/pinpoint/web/config/PropertiesVerificationTest.java
1. add properties verification test
> [#noissue] add properties verification test

- collector/pom.xml
- web/pom.xml
- web/src/main/java/com/navercorp/pinpoint/web/websocket/message/PinpointWebSocketMessageConverter.java
update jackson library (2.8.5 -> 2.8.10)
> [#noissue] update jackson library

- doc/application-inspector.md
- profiler-optional/README.md
> typo-fixed

- web/src/main/java/com/navercorp/pinpoint/web/dao/rest/GithubAgentDownloadInfoDao.java
improve null and empty value validation checks
> [#noissue] improve validation checks

- collector/src/main/java/com/navercorp/pinpoint/collector/cluster/route/DefaultRouteEvent.java
- collector/src/main/java/com/navercorp/pinpoint/collector/cluster/route/RequestEvent.java
- collector/src/main/java/com/navercorp/pinpoint/collector/cluster/route/ResponseEvent.java
- collector/src/main/java/com/navercorp/pinpoint/collector/cluster/route/StreamEvent.java
- collector/src/main/java/com/navercorp/pinpoint/collector/cluster/route/StreamRouteHandler.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/server/DefaultPinpointServer.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/server/PinpointServerAcceptor.java
Improved logs for human readability
> [#noissue] Improved logs for human readability

- web/src/main/resources/jdbc.properties
- web/src/main/webapp/common/help/help-content-en.js
- web/src/main/webapp/common/help/help-content-ko.js
- web/src/main/webapp/features/agentList/agent-list.directive.js
- web/src/main/webapp/features/agentList/agentList.html
- web/src/main/webapp/pages/inspector/inspector.html
> [#noissue] add guide message for application inspector

- pom.xml
add owasp dependency check maven plugin for finding publicly disclosed and vulnerabilities
> [#3640] add owasp dependency check maven plugin

- web/src/grunt/concat.js
- web/src/main/resources/hbase.properties
- web/src/main/webapp/common/services/active-thread-chart-dao.service.js
- web/src/main/webapp/common/services/cpu-load-chart-dao.service.js
- web/src/main/webapp/common/services/memory-chart-dao.service.js
- web/src/main/webapp/common/services/response-time-chart-dao.service.js
- web/src/main/webapp/common/services/tps-chart-dao.service.js
- web/src/main/webapp/components/time-slider/time-slider.focus.js
- web/src/main/webapp/components/time-slider/time-slider.js
- web/src/main/webapp/features/agentInfo/agent-info.directive.js
- web/src/main/webapp/features/applicationStatistic/application-statistic.directive.js
- web/src/main/webapp/index.html
- web/src/main/webapp/styles/inspector.css
- Message pop-up in agent info does not close properly.
- When the value of y is -1, it is drawn on the chart.
- It also shows the location of the chart's hover event on the timeline.
> [#noissue] bug fix and add feature

- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/tcp/AgentBaseDataReceiver.java
- collector/src/main/java/com/navercorp/pinpoint/collector/rpc/handler/AgentLifeCycleHandler.java
- collector/src/main/java/com/navercorp/pinpoint/collector/service/AgentEventService.java
- collector/src/main/resources/applicationContext-collector.xml
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/ThreadPoolExecutorFactoryBean.java
> [#3583] Apply Spring @Async to collector

- collector/src/main/resources/applicationContext-hbase.xml
- commons-hbase/pom.xml
- commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/PooledHTableFactory.java
- commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/TableFactory.java
- commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/parallel/ScanTask.java
- commons-hbase/src/test/java/com/navercorp/pinpoint/common/hbase/HbaseTemplate2IT.java
- web/src/main/resources/applicationContext-hbase.xml
> [#3590] Change ThreadPool management of HbaseTemplate

- plugins/jetty/pom.xml
- plugins/jetty/src/main/java-jetty/org/eclipse/jetty/server/AbstractHttpConnection.java
- plugins/jetty/src/main/java-jetty/org/eclipse/jetty/server/HttpConnection.java
- plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/JettyPlugin.java
- plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/interceptor/AbstractServerHandleInterceptor.java
- plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/interceptor/Jetty8ServerHandleInterceptor.java
- plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/interceptor/Jetty8xServerHandleInterceptor.java
> [#3688] remove reflection code

- agent/src/main/resources-local/pinpoint.config
- agent/src/main/resources-release/pinpoint.config
- agent/src/main/resources/pinpoint-real-env-lowoverhead-sample.config
- plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/JettyConfiguration.java
- plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/JettyPlugin.java
- plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/aspect/RequestAspect.java
- plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/interceptor/AbstractServerHandleInterceptor.java
- plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/interceptor/Jetty8ServerHandleInterceptor.java
- plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/interceptor/Jetty8xServerHandleInterceptor.java
- plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/interceptor/ServerHandleInterceptor.java
- quickstart/agent/src/main/resources/pinpoint.config
> [#3694] Add hide-pinpoint-header option for JettyPlugin

- collector/src/main/java/com/navercorp/pinpoint/collector/cluster/connection/CollectorClusterAcceptor.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/AddressFilterAdaptor.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/DataReceiverGroup.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/StatReceiver.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/tcp/AgentBaseDataReceiver.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/tcp/TCPReceiver.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/udp/BaseUDPHandlerFactory.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/udp/UDPReceiver.java
- collector/src/main/resources/applicationContext-collector.xml
- collector/src/test/java/com/navercorp/pinpoint/collector/receiver/AddressFilterAdaptorTest.java
- collector/src/test/java/com/navercorp/pinpoint/collector/receiver/DataReceiverGroupTest.java
- collector/src/test/java/com/navercorp/pinpoint/collector/receiver/tcp/TCPReceiverTest.java
- collector/src/test/java/com/navercorp/pinpoint/collector/receiver/udp/UDPReceiverTest.java
- commons-server/pom.xml
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/AddressFilter.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/IgnoreAddressFilter.java
- commons-server/src/main/java/com/navercorp/pinpoint/common/server/util/InetAddressUtils.java
- commons-server/src/test/java/com/navercorp/pinpoint/common/server/util/IgnoreAddressFilterTest.java
- flink/src/main/java/com/navercorp/pinpoint/flink/receiver/AddressFilterAdaptor.java
- flink/src/main/java/com/navercorp/pinpoint/flink/receiver/TCPReceiver.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/server/ChannelFilter.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/server/PinpointServerAcceptor.java
- web/src/main/java/com/navercorp/pinpoint/web/cluster/connection/ClusterAcceptor.java
- Cleanup duplicate code of IP ignore feature
> [#3618] Refactor ignore address

- web/src/main/webapp/features/agentInspectorChart/agent-inspector-chart.directive.js
- web/src/main/webapp/features/dataSourceChart/data-source-chart.directive.js
- web/src/main/webapp/features/statisticChart/statistic-chart.directive.js
- Occurs when you zoom in on a chart and have different x-axis ranges between charts.
- 1775
> [#noissue] Freezing occurs in chart hover event synchronization

- collector/src/main/resources/applicationContext-collector.xml
> [#3618] fix spring config of collector

- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/classloading/PlainClassLoaderHandler.java
> [#3709] fix PlainClassLoaderHandler for jboss

- profiler/src/main/java/com/navercorp/pinpoint/profiler/monitor/DeadlockThreadRegistry.java
Fix concurrency issue in DeadlockThreadRegistry
> [#3712] Fix concurrency issue in DeadlockThreadRegistry

- flink/src/main/resources/applicationContext-hbase.xml
Flink had outdated configuration
> Changes ThreadPool management of HbaseTemplate

- plugins/jboss/src/main/java/com/navercorp/pinpoint/plugin/jboss/JbossPlugin.java
- plugins/jboss/src/main/java/com/navercorp/pinpoint/plugin/jboss/aspect/RequestFacadeAspect.java
> [#3716] Add hide-pinpoint-header for JBossPlugin

- web/src/main/webapp/common/help/help-content-en.js
- web/src/main/webapp/common/help/help-content-ko.js
- web/src/main/webapp/features/agentInfo/agentInfoMain.html
- web/src/main/webapp/features/applicationStatistic/applicationStatistic.html
- web/src/main/webapp/features/configuration/userGroup/pinpointUser.html
> [#noissue] change text

- web/src/main/webapp/common/services/alarm-ajax.service.js
- web/src/main/webapp/features/configuration/userGroup/user-group.directive.js
- parse error when has not parameter
> [#3726] bug fix

- collector/src/main/resources/applicationContext-collector.xml
> [#3729] Fix wrong configuration

- agent/src/main/resources-local/pinpoint.config
- agent/src/main/resources-release/pinpoint.config
- agent/src/main/resources/pinpoint-real-env-lowoverhead-sample.config
- plugins/vertx/pom.xml
- plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/VertxHttpHeaderFilter.java
- plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/VertxHttpServerConfig.java
- plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/VertxPlugin.java
- plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/interceptor/HttpServerResponseImplInterceptor.java
- plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/interceptor/ServerConnectionHandleRequestInterceptor.java
- pom.xml
- quickstart/agent/src/main/resources/pinpoint.config
> [#3741] Apply vertx.io 3.5.0 version for VertxPlugin

- pom.xml
- profiler-optional/profiler-optional-jdk7/pom.xml
- profiler-test/pom.xml
- profiler/pom.xml
> [#3722] Apply ASM version 6.0

- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/DefaultProfilerConfig.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/config/ProfilerConfig.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/DefaultAgent.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/DefaultApplicationContext.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/DefaultModuleFactoryProvider.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/ModuleFactoryProvider.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/graph/DependencyGraph.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/module/DefaultApplicationContextTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/module/ModuleFactoryProviderTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/monitor/CollectJobTest.java
Allows the profiler to change the guice's module creation
> [#3747] Allows the profiler to change the guice's module creation

- collector/src/main/java/com/navercorp/pinpoint/collector/controller/ServerTimeController.java
- collector/src/main/resources/servlet-context.xml
- quickstart/bin/start-collector.sh
- quickstart/bin/start-testapp.sh
- quickstart/bin/start-web.sh
1. change validation (check port -> check to call url)
2. change format (tab -> 4space)
> [#3743] Change validation (check port -> check to call url)

- _config.yml
- web/src/main/webapp/common/help/help-content-en.js
> Remove git page, Review help

- plugins/postgresql-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/postgresql/PostgreSqlConfig.java
- plugins/postgresql-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/postgresql/PostgreSqlPlugin.java
> [#3775] Allow disabling PostgreSQL bound values

- index.md
- pages/alarm.md
- pages/application-inspector.md
- pages/faq.md
- pages/history.md
- pages/installation.md
- pages/per-request-feature-guide.md
- pages/techdetail.md
> Capitalize Title

- web/src/main/webapp/features/configuration/userGroup/pinpoint-user.directive.js
- web/src/main/webapp/features/configuration/userGroup/user-group.directive.js
- web/src/main/webapp/styles/configuration.css
- show remove button when user group selected
> [#3799] bug fix 

- collector/src/main/resources/applicationContext-collector-namespace.xml
- collector/src/main/resources/applicationContext-collector.xml
- collector/src/main/resources/applicationContext-hbase.xml
- collector/src/main/resources/hbase.properties
- commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseTableNameProvider.java
- commons-hbase/src/test/java/com/navercorp/pinpoint/common/hbase/HbaseTableNameProviderTest.java
- commons/src/test/resources/test-hbase.properties
- flink/src/main/resources/applicationContext-hbase.xml
- flink/src/main/resources/hbase.properties
- quickstart/collector/src/main/resources/hbase.properties
- quickstart/web/src/main/resources/hbase.properties
- web/src/main/resources/applicationContext-hbase.xml
- web/src/main/resources/applicationContext-web-namespace.xml
- web/src/main/resources/applicationContext-web.xml
- web/src/main/resources/hbase.properties
> Separates namespace wiring configuration

- thrift/src/main/java/com/navercorp/pinpoint/thrift/io/TCommandRegistry.java
- thrift/src/main/java/com/navercorp/pinpoint/thrift/io/TCommandType.java
- thrift/src/test/java/com/navercorp/pinpoint/thrift/io/TCommandRegistryTest.java
- Replace unnecessary ConcurrentHashMap
- Reduce memory allocation
- pre-build index
> [#noissue] TCommandRegistry performance optimization

- plugins/mariadb-jdbc/src/main/java/com/navercorp/pinpoint/plugin/jdbc/mariadb/MariaDBJdbcUrlParser.java
Differences in class load timing between **MariaDBJdbcUrlParser** and **MariaDBJdbcUrlParser$Type** was causing *IllegalAccessError* in certain situations (#3857 for more detail).
This introduces a static reference to **MariaDBJdbcUrlParser$Type** to make it load when the outer **MariaDBJdbcUrlParser** is initialized.
resolves #3857
> Loads Type on outer class initialization

- plugins/rabbitmq/src/main/java/com/navercorp/pinpoint/plugin/rabbitmq/interceptor/RabbitMQConsumeInterceptor.java
- plugins/rabbitmq/src/main/java/com/navercorp/pinpoint/plugin/rabbitmq/interceptor/RabbitMQPublishInterceptor.java
> [#1412] RabbitMq code cleanup

- plugins/rabbitmq/src/main/java/com/navercorp/pinpoint/plugin/rabbitmq/interceptor/RabbitMQConsumeInterceptor.java
This is a bug fix for rabbitmq plugin.
> [#3818] NullPointerExp in rabbitmq consumer side.

- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/tcp/AgentBaseDataReceiver.java
- collector/src/main/resources/applicationContext-collector.xml
- collector/src/test/java/com/navercorp/pinpoint/collector/receiver/tcp/TCPReceiverTest.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/module/ApplicationContextModule.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/ConnectionFactoryProviderProvider.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/PinpointClientFactoryProvider.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/PipelineFactory.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/client/ClientCodecPipelineFactory.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/client/Connection.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/client/ConnectionFactory.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/client/ConnectionFactoryProvider.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/client/DefaultConnectionFactoryProvider.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/client/DefaultPinpointClientFactory.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/server/PinpointServerAcceptor.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/server/ServerCodecPipelineFactory.java
- rpc/src/test/java/com/navercorp/pinpoint/rpc/DiscardServerHandler.java
- rpc/src/test/java/com/navercorp/pinpoint/rpc/server/PinpointServerSocketTest.java
- rpc/src/test/java/com/navercorp/pinpoint/rpc/server/PipelineFactoryTest.java
Change to the structure that can change codec processing in rpc
> [#3869] Change to the structure that can change codec processing in rpc

- web/src/main/webapp/features/configuration/userGroup/group-member.directive.js
- web/src/main/webapp/features/configuration/userGroup/pinpoint-user.directive.js
- web/src/main/webapp/features/configuration/userGroup/pinpointUser.html
- web/src/main/webapp/features/configuration/userGroup/user-group-container.directive.js
- unable to remove from group member
> [#3898] bug fix.

- web/src/main/webapp/features/agentInfo/agent-info.directive.js
- web/src/main/webapp/features/agentInfo/agentInfoMain.html
- web/src/main/webapp/features/applicationStatistic/application-statistic.directive.js
- web/src/main/webapp/features/serverMap/server-map.directive.js
> [#3907] bug fix

- rpc/src/test/java/com/navercorp/pinpoint/rpc/DiscardServerHandler.java
- rpc/src/test/java/com/navercorp/pinpoint/rpc/client/HealthCheckTest.java
- rpc/src/test/java/com/navercorp/pinpoint/rpc/codec/TestCodec.java
- rpc/src/test/java/com/navercorp/pinpoint/rpc/server/ControlPacketServerTest.java
- rpc/src/test/java/com/navercorp/pinpoint/rpc/server/EventHandlerTest.java
- rpc/src/test/java/com/navercorp/pinpoint/rpc/server/PinpointServerStateTest.java
> [#noissue] cleanup rpc test code

- _data/sidebars/mydoc_sidebar.yml
- _includes/sidebar.html
- css/theme-black.css
- index.md
empty commit to rebuild github page
> [#noissue] rebuild github page

- pom.xml
> [#3958] ASM version up

- pom.xml
> [#3976] Javassist version update for java9

- commons/src/main/java/com/navercorp/pinpoint/common/util/JvmType.java
- commons/src/main/java/com/navercorp/pinpoint/common/util/OsType.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/stat/filedescriptor/FileDescriptorMetricProvider.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/context/provider/stat/filedescriptor/FileDescriptorMetricProviderTest.java
> [#3839] Fix Linux&oracleJDK env

- web/src/main/webapp/common/services/open-file-descriptor-chart-dao.service.js
- web/src/main/webapp/pages/transactionView/transaction-view.controller.js
> [#3839] bug fix.

- profiler-optional/profiler-optional-jdk8/src/test/java/com/navercorp/test/pinpoint/jdk8/interfaces/MethodInterface.java
- profiler-optional/profiler-optional-jdk8/src/test/java/com/navercorp/test/pinpoint/jdk8/interfaces/MethodInterfaceClass.java
- profiler-optional/profiler-optional-jdk8/src/test/java/com/navercorp/test/pinpoint/jdk8/interfaces/MethodInterfaceTest.java
- profiler-optional/profiler-optional-jdk8/src/test/java/com/navercorp/test/pinpoint/jdk8/interfaces/SimpleAccessor.java
- profiler-optional/profiler-optional-jdk8/src/test/java/com/navercorp/test/pinpoint/jdk8/interfaces/SimpleClass.java
- profiler-optional/profiler-optional-jdk8/src/test/java/com/navercorp/test/pinpoint/jdk8/interfaces/SimpleInterceptor.java
- profiler-optional/profiler-optional-jdk8/src/test/java/com/navercorp/test/pinpoint/jdk8/interfaces/SimpleInterface.java
- profiler-optional/profiler-optional-jdk8/src/test/java/com/navercorp/test/pinpoint/jdk8/interfaces/SimpleInterfaceClass.java
- profiler-optional/profiler-optional-jdk8/src/test/resources/log4j.xml
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMClass.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMClassNodeAdapter.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/JavassistClass.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/instrument/ASMClassTest.java
> [#3837] Support java 8  interface static/default method

- plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/OkHttpConstants.java
- plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/v2/OkHttpPlugin.java
- plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/v3/OkHttpPlugin.java
- plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/v3/UserRequestGetter.java
- plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/v3/UserResponseGetter.java
- plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/v3/interceptor/HttpEngineConnectMethodInterceptor.java
- plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/v3/interceptor/HttpEngineReadResponseMethodInterceptor.java
- plugins/okhttp/src/main/java/com/navercorp/pinpoint/plugin/okhttp/v3/interceptor/HttpEngineSendRequestMethodInterceptor.java
> [#3761] Support okhttp 3.3.1

- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/RequestTrace.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/proxy/ProxyHttpHeaderRecorder.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/request/RequestTraceReader.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/request/ServerRequestRecorder.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/request/ServerRequestTrace.java
- bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/plugin/proxy/ProxyHttpHeaderRecorderTest.java
- bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/plugin/request/RequestTraceReaderTest.java
- bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/plugin/request/ServerRequestRecorderTest.java
- plugins/jboss/src/main/java/com/navercorp/pinpoint/plugin/jboss/JbossServerRequestTrace.java
- plugins/jboss/src/main/java/com/navercorp/pinpoint/plugin/jboss/interceptor/StandardHostValveInvokeInterceptor.java
- plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/JettyServerRequestTrace.java
- plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/interceptor/AbstractServerHandleInterceptor.java
- plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/interceptor/Jetty8ServerHandleInterceptor.java
- plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/interceptor/Jetty8xServerHandleInterceptor.java
- plugins/jetty/src/main/java/com/navercorp/pinpoint/plugin/jetty/interceptor/ServerHandleInterceptor.java
- plugins/resin/src/main/java/com/navercorp/pinpoint/plugin/resin/ResinServerRequestTrace.java
- plugins/resin/src/main/java/com/navercorp/pinpoint/plugin/resin/interceptor/ServletInvocationInterceptor.java
- plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/TomcatServerRequestTrace.java
- plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/interceptor/StandardHostValveInvokeInterceptor.java
- plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/VertxHttpServerServerRequestTrace.java
- plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/interceptor/ServerConnectionHandleRequestInterceptor.java
- plugins/websphere/src/main/java/com/navercorp/pinpoint/plugin/websphere/WebsphereServerRequestTrace.java
- plugins/websphere/src/main/java/com/navercorp/pinpoint/plugin/websphere/interceptor/AbstractServerHandleInterceptor.java
#3815 
* Add request trace reader.
* Add server request recorder.
> [#3815] Add RequestTraceReader and ServerRequestRecorder

- agent/src/test/java/com/navercorp/pinpoint/plugin/jdk7/rabbitmq/spring/SpringAmqpRabbit_1_7_0_to_1_7_7_IT.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/jdk7/rabbitmq/spring/SpringAmqpRabbit_1_7_7_to_2_0_0_IT.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/jdk7/rabbitmq/spring/SpringAmqpRabbit_2_0_0_to_2_0_3_IT.java
- agent/src/test/java/com/navercorp/pinpoint/plugin/jdk7/rabbitmq/spring/SpringAmqpRabbit_2_0_3_to_2_x_IT.java
- plugins/rabbitmq/README.md
- plugins/rabbitmq/src/main/java/com/navercorp/pinpoint/plugin/rabbitmq/client/RabbitMQClientPlugin.java
> Adds support for spring amqp rabbit 1.7.7 and 2.0.3

- web/src/main/java/com/navercorp/pinpoint/web/task/TimerTaskDecorator.java
- web/src/main/java/com/navercorp/pinpoint/web/task/TimerTaskDecoratorFactory.java
- web/src/main/java/com/navercorp/pinpoint/web/websocket/ActiveThreadCountHandler.java
- web/src/main/java/com/navercorp/pinpoint/web/websocket/ActiveThreadCountResponseAggregator.java
- web/src/main/java/com/navercorp/pinpoint/web/websocket/ActiveThreadCountWorker.java
- web/src/main/java/com/navercorp/pinpoint/web/websocket/PinpointWebSocketTimerTaskDecoratorFactory.java
- web/src/main/java/com/navercorp/pinpoint/web/websocket/WorkerActiveManager.java
- web/src/test/java/com/navercorp/pinpoint/web/websocket/PinpointWebSocketTimerTaskDecoratorTest.java
> Propagates security context to active thread count timer tasks

- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/classloader/PinpointClassLoaderFactory.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/util/jdk/ThreadLocalRandomUtils.java
- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/AgentClassLoader.java
> [#noissue] cleanup deprecated api in java9

- plugins/rabbitmq/src/main/java/com/navercorp/pinpoint/plugin/rabbitmq/client/interceptor/ChannelBasicPublishInterceptor.java
If args[n]==null then instanceof will always fail, so check it before instanceof.
> [#3995] rabbitmq plugin not pass traceId

- web/src/grunt/concat.js
- web/src/main/webapp/common/help/help-content-en.js
- web/src/main/webapp/common/help/help-content-ko.js
- web/src/main/webapp/common/services/agent-ajax.service.js
- web/src/main/webapp/common/services/direct-buffer-chart-dao.service.js
- web/src/main/webapp/common/services/memory-chart-dao.service.js
- web/src/main/webapp/common/services/open-file-descriptor-chart-dao.service.js
- web/src/main/webapp/common/services/tooltip.service.js
- web/src/main/webapp/features/agentInfo/agent-info.directive.js
- web/src/main/webapp/features/agentInfo/agentInfoMain.html
- web/src/main/webapp/features/applicationStatistic/application-statistic.directive.js
- web/src/main/webapp/features/applicationStatistic/applicationStatistic.html
- web/src/main/webapp/index.html
- Direct buffer count chart
- Direct buffer memory chart
- Mapped buffer count chart
- Mapped buffer memory chart
> [#3967] add Direct Buffer chart to inspector.

- agent/src/main/resources-local/pinpoint.config
- agent/src/main/resources-release/pinpoint.config
- quickstart/agent/src/main/resources/pinpoint.config
* Add comment for excludeurl
* Activate vertx options
> [#noissue] Update config

- quickstart/README.md
> [#noissue] fix quickstart readme

- web/src/main/resources/pinpoint-web.properties
The feature is still under development.
(cherry picked from commit 8c69f2f65c983e7e46177712b60c5a013f41b220)
> Backports realtime server map configuration change

- web/src/grunt/concat.js
- web/src/main/webapp/common/help/help-content-en.js
- web/src/main/webapp/common/help/help-content-ko.js
- web/src/main/webapp/common/services/agent-ajax.service.js
- web/src/main/webapp/common/services/alarm-util.service.js
- web/src/main/webapp/common/services/direct-buffer-chart-dao.service.js
- web/src/main/webapp/common/services/memory-chart-dao.service.js
- web/src/main/webapp/common/services/open-file-descriptor-chart-dao.service.js
- web/src/main/webapp/common/services/tooltip.service.js
- web/src/main/webapp/features/agentInfo/agent-info.directive.js
- web/src/main/webapp/features/agentInfo/agentInfoMain.html
- web/src/main/webapp/features/applicationStatistic/application-statistic.directive.js
- web/src/main/webapp/features/applicationStatistic/applicationStatistic.html
- web/src/main/webapp/features/configuration/userGroup/user-group.directive.js
- web/src/main/webapp/index.html
- Send default parameter userId when get user-group data
>  [#noissue] bug fix

- .mvn/wrapper/maven-wrapper.properties
> Changes maven wrapper to use maven 3.5.3

- pom.xml
> [#3986] Upgrade maven plugins for java9, 10

- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/module/ModuleSupport.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/module/ModuleSupportFactory.java
- bootstrap-java9/src/main/java/com/navercorp/pinpoint/bootstrap/module/Java9ModuleSupport.java
- bootstrap-java9/src/main/java/com/navercorp/pinpoint/bootstrap/module/Java9ModuleSupportFactory.java
- bootstrap-java9/src/test/java/com/navercorp/pinpoint/bootstrap/classloader/PlatformClassLoaderTest.java
- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/ModuleBootLoader.java
- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/ModuleUtils.java
- bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/PinpointBootStrap.java
- add temporary fix for http connector
> [#4081] java9 module system support

- collector/src/main/resources/applicationContext-hbase.xml
- commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/AdminFactory.java
- commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/ConnectionFactoryBean.java
- commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HBaseAdminTemplate.java
- commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseAdminFactory.java
- commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseTableFactory.java
- commons-hbase/src/test/java/com/navercorp/pinpoint/common/hbase/HbaseTemplate2IT.java
- flink/src/main/resources/applicationContext-hbase.xml
- web/src/main/resources/applicationContext-hbase.xml
Refactors hbase **Connection** creations to have it shared between different hbase templates.
resolves #4088
> Refactors hbase Connection creation

- plugins/jdk-http/src/main/java/com/navercorp/pinpoint/plugin/jdk/http/JdkHttpPlugin.java
> Traces https calls made via JDK http connector

- collector/src/main/java/com/navercorp/pinpoint/collector/cluster/ClusterPointRouter.java
- collector/src/main/java/com/navercorp/pinpoint/collector/service/AgentEventService.java
- web/src/main/java/com/navercorp/pinpoint/web/controller/CommandController.java
- web/src/main/java/com/navercorp/pinpoint/web/service/AgentServiceImpl.java
> [#noissue] cleanup spring qualifier

- commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/AdminCallback.java
- commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HBaseAdminTemplate.java
- commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseAdminFactory.java
This introduces a callback when making Hbase **Admin** calls to simplify error handling and clean up.
related to #4088
> Refactors Hbase admin callback

- collector/src/main/java/com/navercorp/pinpoint/collector/handler/AgentEventHandler.java
- collector/src/main/java/com/navercorp/pinpoint/collector/handler/AgentInfoHandler.java
- collector/src/main/java/com/navercorp/pinpoint/collector/handler/AgentStatHandlerV2.java
- collector/src/main/java/com/navercorp/pinpoint/collector/handler/SpanChunkHandler.java
- collector/src/main/java/com/navercorp/pinpoint/collector/handler/SpanHandler.java
- collector/src/test/java/com/navercorp/pinpoint/collector/receiver/DispatchHandlerTest.java
This logic will always throw exceptions.
I added else statement to solve this issue.
> [#4127] bug fix

- agent/pom.xml
- plugins/activemq-client/pom.xml
- plugins/arcus/pom.xml
- plugins/bom/.gitignore
- plugins/bom/pom.xml
- plugins/cassandra/pom.xml
- plugins/cxf/pom.xml
- plugins/dbcp/pom.xml
- plugins/dbcp2/pom.xml
- plugins/dubbo/pom.xml
- plugins/google-httpclient/pom.xml
- plugins/httpclient3/pom.xml
- plugins/httpclient4/pom.xml
- plugins/hystrix/pom.xml
- plugins/jsp/pom.xml
- plugins/jtds/pom.xml
- plugins/mariadb-jdbc/pom.xml
- plugins/mysql-jdbc/pom.xml
- plugins/ning-asynchttpclient/pom.xml
- plugins/okhttp/pom.xml
- plugins/pom.xml
- plugins/postgresql-jdbc/pom.xml
- plugins/rabbitmq/pom.xml
- plugins/redis/pom.xml
- plugins/rxjava/pom.xml
- plugins/tomcat/pom.xml
- pom.xml
- web/pom.xml
- Introduce maven BOM for plugin dependency
> [#4183] Cleanup plugin dependency

- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/TCPReceiverBean.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/tcp/DefaultTCPReceiver.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/tcp/TCPReceiver.java
To extend the usability of the TCPReceiver, change it to interface.
> [#github_4199] Change TCPReceiver to interface

- collector/src/main/java/com/navercorp/pinpoint/collector/cluster/zookeeper/DefaultZookeeperClient.java
- collector/src/main/java/com/navercorp/pinpoint/collector/cluster/zookeeper/ZookeeperClient.java
- collector/src/main/java/com/navercorp/pinpoint/collector/cluster/zookeeper/ZookeeperJobWorker.java
- collector/src/main/java/com/navercorp/pinpoint/collector/cluster/zookeeper/ZookeeperUtils.java
- collector/src/test/java/com/navercorp/pinpoint/collector/cluster/zookeeper/ZookeeperJobWorkerTest.java
1. add createNodeMethod
2. move some utility method
> [#noissue] cleanup collector's zookeepr code

- collector/src/main/resources/applicationContext-collector.xml
currently, spanReceiver bean name is spanTcpReceiver, spanUdpReceiver
statReceiver bean name is tcpStatReceiver, udpStatReceiver
Make the format as same .
> [#noissue] cleanup spring bean name

- collector/src/main/java/com/navercorp/pinpoint/collector/cluster/ClusterPointRouter.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/tcp/DefaultTCPPacketHandler.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/tcp/TCPServerResponse.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/CommandDispatcher.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/AgentInfoSenderTest.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/PinpointSocket.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/client/DefaultPinpointClient.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/client/SimpleMessageListener.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/server/DefaultPinpointServer.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/server/LoggingServerMessageListenerFactory.java
- rpc/src/test/java/com/navercorp/pinpoint/rpc/server/EchoServerMessageListenerFactory.java
- rpc/src/test/java/com/navercorp/pinpoint/rpc/server/HandshakeVerifyMessageListenerFactory.java
- rpc/src/test/java/com/navercorp/pinpoint/rpc/util/PinpointRPCTestUtils.java
- thrift/src/main/java/com/navercorp/pinpoint/io/request/AttributeMap.java
- thrift/src/main/java/com/navercorp/pinpoint/io/request/DefaultAttributeMap.java
- thrift/src/main/java/com/navercorp/pinpoint/io/request/DefaultServerRequest.java
- thrift/src/main/java/com/navercorp/pinpoint/io/request/ServerRequest.java
- web/src/main/java/com/navercorp/pinpoint/web/cluster/DefaultPinpointRouteResponse.java
- web/src/main/java/com/navercorp/pinpoint/web/websocket/ActiveThreadCountWorker.java
> [#4272] Refactor DispatchHandler

- profiler/src/main/java/com/navercorp/pinpoint/profiler/objectfactory/ConstructorResolver.java
> [#4293] Fix Class conflict

- web/pom.xml
> [#4293] dependency-scope rollback

- rpc/src/main/java/com/navercorp/pinpoint/rpc/client/ConnectFuture.java
add break condition for ConnectFuture.awaitUninterruptibly method
> [#noissue] add break condition

- rpc/src/main/java/com/navercorp/pinpoint/rpc/client/DefaultPinpointClientHandler.java
1. handle exception when execute channel open operation
> [#4326] Enhances handling when an exception occurs in PinpointClientHandler

- web/src/main/java/com/navercorp/pinpoint/web/vo/callstacks/ExceptionRecord.java
> [#4338] Fix web call tree exception record

- .travis.yml
- pom.xml
> [#4330] Modify build requirements to java8

- collector/src/main/java/com/navercorp/pinpoint/collector/cluster/connection/CollectorClusterConnector.java
- collector/src/main/java/com/navercorp/pinpoint/collector/cluster/flink/FlinkClusterConnectionManager.java
- collector/src/test/java/com/navercorp/pinpoint/collector/receiver/DataReceiverGroupTest.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/PinpointClientFactoryProvider.java
- profiler/src/main/java/com/navercorp/pinpoint/profiler/context/provider/SpanStatClientFactoryProvider.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/AgentInfoSenderTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/sender/TcpDataSenderReconnectTest.java
- profiler/src/test/java/com/navercorp/pinpoint/profiler/sender/TcpDataSenderTest.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/client/ClientOption.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/client/DefaultPinpointClientFactory.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/client/DefaultPinpointClientHandler.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/client/PinpointClientFactory.java
- rpc/src/test/java/com/navercorp/pinpoint/rpc/client/ReconnectTest.java
- web/src/main/java/com/navercorp/pinpoint/web/cluster/connection/ClusterConnector.java
Separates timeout option in ClientOption
> [#4341] Separates timeout option in ClientOption

- collector/src/main/java/com/navercorp/pinpoint/collector/cluster/connection/CollectorClusterAcceptor.java
- collector/src/main/java/com/navercorp/pinpoint/collector/receiver/PinpointServerAcceptorProvider.java
- collector/src/main/resources/applicationContext-collector.xml
- collector/src/main/resources/pinpoint-collector.properties
- rpc/src/main/java/com/navercorp/pinpoint/rpc/server/HealthCheckManager.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/server/PinpointServerAcceptor.java
- rpc/src/main/java/com/navercorp/pinpoint/rpc/server/ServerOption.java
- web/src/main/java/com/navercorp/pinpoint/web/cluster/connection/ClusterAcceptor.java
allows the Option in Collector's PinpointServerAcceptor setting in the setup file(pinpoint-collector.properties).
> [#4350] Allows the Option in Acceptor setting in the setup file

- plugins/akka-http/pom.xml
- plugins/akka-http/src/main/java/com/navercorp/pinpoint/plugin/akka/http/AkkaHttpPlugin.java
> [#4360] fix build fail

- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/request/ContinueTraceHeader.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/request/DefaultTraceHeaderReader.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/request/DisableTraceHeader.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/request/NewTraceHeader.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/request/RequestTraceReader.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/request/TraceHeader.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/request/TraceHeaderReader.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/request/TraceHeaderState.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/request/util/BypassNameSpaceChecker.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/request/util/DefaultNameSpaceChecker.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/request/util/NameSpaceCheckFactory.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/request/util/NameSpaceChecker.java
- bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/request/util/RealIpHeaderResolver.java
- bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/plugin/request/RequestWrapperReaderTest.java
- bootstrap-core/src/test/java/com/navercorp/pinpoint/bootstrap/plugin/request/util/NameSpaceCheckFactoryTest.java
> [#4271] Refactor ServletRequestListener
